### ISSUE TITLE
field manager: "prepare all" or "import all" should not trigger workstations that already have a job running

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#1012]
I had a prepare job running, then started "prepare all" and it started the job again. It should only start those workstation that are not prepared and are not on it.

**Comment by urapadmin** [comment]
### @test kiosk 0.11
- [ ] when there are already all eligible workstations for the respective action being processed the attempt to do a batch action like prepare all or import all should lead to "no workstation is currently eligible for the task" or such.

**Comment by luizaogs** [comment]
Works.
