### ISSUE TITLE
triggering an action that a workstation isn't offering should not be possible

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#1023]
... but it is, theoretically, by using curl or some tool that just sends a post request.
The kioskfilemakerworkstationcontroller should check the action against the available options when being triggered.

**Comment by urapadmin** [comment]
### Kiosk 0.25.6
- did that for KioskFileMakerWorkstation
- did that for KioskReportingDock but there it is of entirely hypothetical nature, currently, since all options are always available anyhow
- didn't do it for KioskExportWorkstation because there it is really entirely hypothetical.

**Comment by luizaogs** [comment]
Oops - Lutz I also need you to update PASU test to this when you can (not tonight, go to sleep!). I can't test reporting on PVD.

[while I am bothering you, what should I put under "unit" to test the run report function of the reporting dock?]

**Comment by luizaogs** [comment]
Ah unit is archaeological unit. That was dumb and I figured it out.

This is all fine.
