### ISSUE TITLE
director's view: make headings static

### ISSUE THREAD

**Issue by lbestock** [arch-kiosk/arch-kiosk-office#1068]
In director's view when there is a long list of stuff scrolling down means one loses the headings. And then one doesn't know what the checkmarks mean anymore. It would be helpful if the headings could stay static.
<img width="868" alt="image" src="https://user-images.githubusercontent.com/49291909/117217043-c7affd80-adce-11eb-9eaa-4291b23d7b91.png">

**Comment by urapadmin** [comment]
it is very finicky in the director's view and the layout needs a different general approach in kiosk than my original from a couple of years ago. This is connected to #23. But I don't have the time right now, so there is a temporary solution in place that works almost everywhere but sucks on phones and perhaps looks strange on ipads.

**Comment by lbestock** [comment]
Testing it first on the mac in 0.12 on PVD: it's still not behaving as I expected it to. Two shots: one what it looks like when I scroll down, and one when I haven't scrolled down (which is what I expected it to look like always - with the headings there.) Have checked features and loci but not yet CM but assume it's the same).

![image](https://user-images.githubusercontent.com/49291909/124195211-f9280b00-da97-11eb-90e0-0fcebcc62291.png)

![image](https://user-images.githubusercontent.com/49291909/124195200-ef9ea300-da97-11eb-974b-01ab91447fa5.png)

**Comment by urapadmin** [comment]
I see, you meant the headings within the widgets. That won't happen in v1. It looks trivial but I don't have a trivial answer for it.

**Comment by urapadmin** [comment]
### kiosk 1.3
- using sticky headers now for the context, collected material and feature widgets. It seems to be okay on Safari, but needs some testing with a bit more data

**Comment by luizaogs** [comment]
iOS Safari and Chrome: works
Mac Safari and Chrome: works
