### ISSUE TITLE
QC: file import must reevaluate qc results

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#1072]
- when importing files via upload or local import qc rules need to be recalculated

**Comment by urapadmin** [comment]
### @test 0.12
That's how you test: You have a locus without an opening photo. So the respective rule should be active for that locus and in the director's view you should get the warning for that locus.

- [ ] when importing a file via upload that is assigned to that locus the requirement is now met so the warning should disappear in the director's view
- [ ] same if the file gets imported via bulk import

**Comment by luizaogs** [comment]
Worked for upload but I can't test the bulk import part.
