### ISSUE TITLE
make it easy to find out WHICH locus relations are problematic

### ISSUE THREAD

**Issue by lbestock** [arch-kiosk/arch-kiosk-office#1094]
We have gotten URAP down to two problematic locus relations but it is not clear which ones. We need an easy way to see this. Previously Lutz created a database query that gave me a list. 

I have resolved all of the ones there, I think, with the exception of EC-002 to EC-004, which I don't understand why it is on the list at all. The relation is in both places and is properly reciprocal (cut by/cuts through) and there are no additional relations between these two.

**Comment by urapadmin** [comment]
do this together with #1401

**Comment by urapadmin** [comment]
### kiosk 0.16
from now on kiosk reports up to 20 problematic locus relations below the warning (if you use the details button)

**Comment by luizaogs** [comment]
Indeed it does.
