### ISSUE TITLE
new config section i18n: Translation and general/current_language

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#1133]
### @test filemaker 10.7

Currently only s'Urachi ceramics and preprocessing is internationalized and there only the labels on the form itself. Messages and valuelists are still in English.
However, these keys control it in the i18n section of the config:
Let xx be what is being set as current language in general (should be en for English, it for Italian or what have you):

key:
su_ceramics_xx: 

value: 
identifier:identifier
observations:observations
object:object
functional_category:functional category
functional_sub_category:sub category
comments_on_form_and_comparison:form and comparison
drawing:drawn
photographed:photographed
images:images
ceramics:ceramics
fabric:observations concerning the fabric
manufacture:observations concerning the manufacture
finish_and_decoration:about finish and decoration
other_observations:other observations
measurements:measurements
chronology:chronology
coarseness:coarseness

key:
su_ceramics_preprocessing_en
value:
cat_1:category one
cat_2:category two
count:count
weight:weight(gr)

**Comment by lbestock** [comment]
How do I actually switch between Italian and English? And the valuelists will still all be in Italian, right? (They are in Italian. You had made most of them so, with the exception of thicklish thinnish. Which I was loathe to leave, but I did change that to be what they actually have.)

**Comment by urapadmin** [comment]
there is a configuration key "current_language" under general in the recording. In SU it is set to either it or en. That id is used as a suffix into the keys under i18n:

you find the keys "su_ceramics" and "su_ceramics_preprocessing" in an "_en" and an "_it" version. Depending on the "current_language" setting the one or the other would be used.

If you'd create a German version, you would just add (you can't) keys "su_ceramics_de" and "su_ceramics_preprocessing_de" and set the current language to "de".

**Comment by urapadmin** [comment]
and yes, this is currently only changing the labels on the form not any values or selections or some such
