### ISSUE TITLE
s'Urachi fragments: possible to organize by number?

### ISSUE THREAD

**Issue by lbestock** [arch-kiosk/arch-kiosk-office#1148]
In the stage 2 processing for s'Urachi ceramics I noted that the list reorganized itself alphabetically regardless of what order one did the data entry in, so that one always got functional categories all together. This strikes me as very helpful. Something similar would be useful in the stage 3 processing, the fragments stuff in Peter's original format. Here if I make fragments in order 2, 3, 48, 1, they stay in that order in the list on the left. Could they arrange themselves into 1, 2, 3, 48? My thinking is that they are going to be doing this by picking up pre-numbered sherds that are arranged on a table, not necessarily numerically. They are highly unlikely to make the records sequentially. But they are very likely to want to have the records sequentially even here in the recording, for instance if they need to add more information or an image to a record they made previously and have to find it in that list.

**Comment by urapadmin** [comment]
### @test 10.7.1
Did that.

**Comment by lbestock** [comment]
It's so helpful.

**Comment by lbestock** [comment]
Whoops not quite because computers are so smart:
![image](https://user-images.githubusercontent.com/49291909/121708977-11fb5d00-caa6-11eb-9ec0-430be07a65c4.png)

**Comment by urapadmin** [comment]
I am not sure that I can enforce a numerical order here. This is aplhapetical because it includes the first part of the identifier. Perhaps I can make a difference between domain and id?

**Comment by lbestock** [comment]
That is correct.
