### ISSUE TITLE
file import with QR code and filename data not working

### ISSUE THREAD

**Issue by aes1884** [arch-kiosk/arch-kiosk-office#1199]
Trying to upload both object photos and site drone photos to the file repository (through the bunch upload option) has not been working with either the QR code or the filename to automatically assign context. 

Object photo QR code uploads were attempted with the black velvet background option and drone photo uploads were attempted with the Sahara option. The screenshot below shows the result of trying to upload object photo files using the QR code.
![image](https://user-images.githubusercontent.com/68443221/132336684-7b04b55a-c155-492a-8792-493a7964ee49.png)

The object photos will draw their context from the filename either. They are named with their collected material number and then a sequential number for the objects that have more than one photo (e.g. MB10-009-77_1). The screenshot below shows the result of trying to upload them with the filename choice.
![image](https://user-images.githubusercontent.com/68443221/132337080-2bde4e4c-83d8-46de-b36d-4a52bf9d65cc.png)

**Comment by urapadmin** [comment]
can you please upload DSCN3612.jpg either here or email it to me?

**Comment by urapadmin** [comment]
unfortunately I don't have access to the log files of the virtual machine. I would need the said kiosk_Tue_070921-0700.log. You can download it in kiosk if you go to administration first and then open the menu again where you would find "logs" in the sub menu. 
![image](https://user-images.githubusercontent.com/38838314/132414065-54c46e23-a2d3-4edb-9dc1-2b9c53607541.png)

**Comment by urapadmin** [comment]
I found a configuration issue in arch1900. Unfortunately I cannot fix this without access to the virtual machine. 
There is just an old file that is in the way and needs to be deleted. 
So, forget about the log file. But please give me the DSCN3612.jpg. 

And then please hand over the VM to Laurel. I would want to upgrade the vm to the latest kiosk version anyhow.

**Comment by urapadmin** [comment]
The updated arch1900 vm now has version 0.13.3 and I removed the file that was in the way of the file import. 

While I have tested the file import by file name I have not had an example I could have used for the qr code import. But it is quite likely that removing the superfluous file has enabled the qr code import as well.

@aes1884: If you import a file using the "context from operating system" option the filename must start with the context and may have an additional description but separated from the rest by a space: a filename like "mb10-009-26.jpg" is okay and so is "mb10-009-25 my description". "mb10-009-26_1" is not correct because it assumes an archaeological identifier "mb10-009-26_1". We should write about that in the user's manual one day.

**Comment by urapadmin** [comment]
This got a bit confusing, I guess. There is an open question to you, Anna:
@aes1884: can you please upload DSCN3612.jpg either here or email it to me?

**Comment by aes1884** [comment]
Sorry for leaving this so long unattended! I just tried uploading both a drone photo and an object photo using the QR code and both worked. For the drone photos, it still has trouble with the ones taken from higher up, but the closer shots work just fine.

**Comment by urapadmin** [comment]
so we can close this?

**Comment by urapadmin** [comment]
How many photos have you imported using the qr code method and what in your estimate is the success rate?

**Comment by urapadmin** [comment]
@aes1884 ?

**Comment by lbestock** [comment]
I have now tested this using bunch and ton, QR codes and file names and folder names, all with success. It seems likely that unrecognized QR codes were simply too far away. If there is an ARCH1900 specific problem still lurking that can be made a new ticket, but in terms of testing local servers for 2022 summer field seasons, the import seems to be working very well (provided one remembers to click the right check boxes). So I'll close this.
