### ISSUE TITLE
general search in file repository

### ISSUE THREAD

**Issue by lbestock** [arch-kiosk/arch-kiosk-office#1243]
Currently one has to know what field to search in in the file repository. That makes a lot of sense for contexts. Is it worth considering a general search, and how much work would that be to implement? I sometimes forget if "Abi" is a tag or a description (and it might in fact be either or both). I can also imagine this being useful for nicknames. I can also see if one numbered entity is referred to in the description of another you would want to get it from a search. The thought arose out of pondering where and how people use nicknames.

**Comment by urapadmin** [comment]
closed because #2631 takes over
