### ISSUE TITLE
file repository fetching language

### ISSUE THREAD

**Issue by luizaogs** [arch-kiosk/arch-kiosk-office#1248]
I noticed this yesterday when searching for my FM database in the file repository and then forgot to open a ticket and upload my screenshot. This is small and pretty insignificant and I don't know if you can even change it, but if only one file is found in the search one still gets "files" mentioned and is told to "fetch 'em" rather than "it".

<img width="1512" alt="Screen Shot 2021-11-08 at 7 56 44 AM" src="https://user-images.githubusercontent.com/67970402/140746153-3f5a559d-8ecf-49af-9285-88fcfed68e24.png">

**Comment by urapadmin** [comment]
you ...

**Comment by urapadmin** [comment]
:o)

**Comment by urapadmin** [comment]
so what do they say in Texas when there's an isolated ontological entity to be fetched?

**Comment by luizaogs** [comment]
Sorry, you should feel free to ignore me. And I have no idea but have now uselessly learned a lot about Texas hold 'em, which was at least distracting.

**Comment by urapadmin** [comment]
### kiosk 0.25.4
I felt the need to do something productive and for your's truly on this strange day. And it comes with a poem because I thought of this strange Machado de Assis novella in the past days. Total tangent. But what isn't.

Let it Go
It is this deep blankness is the real thing strange.
   The more things happen to you the more you can't
       Tell or remember even what they were.

The contradictions cover such a range
    The talk would talk and go so far aslant  
          You don't want madhouse and the whole thing there.

**Comment by urapadmin** [comment]
William Empson.

**Comment by luizaogs** [comment]
The days keep getting stranger and stranger. A madhouse, indeed. But this project remains a source of comforting distraction for yours truly :) I had missed the poems!

[And here goes my tangent, from the novel I am currently reading, a quote that stuck with me that I thought you might appreciate: “Although, if you like everything you read, I can't take you seriously. Perhaps you didn't think about these books long enough.”]
