### ISSUE TITLE
Stop execution of the current script during inserting an image

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#1264]
@test 11.6.6
Since this version I am using a special command that suppresses the option for a user to interrupt a running script. But the command has to be applied to every single script (although I really don't want any user to interrupt any script ever, given the undetermined outcome). 

Luiza tested this relentlessly with this result:
>I can still provoke it with mad clicking on the screen, but it is much harder now than it was before. So not sure if you can do >anything else about it...

![IMG_0240](https://user-images.githubusercontent.com/67970402/141695389-207701bd-97e3-4620-968c-6376ae31d454.PNG)

_Originally posted by @luizaogs in https://github.com/urapadmin/kiosk/issues/1253#issuecomment-968349052_

**Comment by luizaogs** [comment]
So for this…did you mean that I should make a note of whenever I encounter the issue, or did you want me to madly click around in different forms and approach it more systematically? If that is possible.

**Comment by urapadmin** [comment]
I just parked it here for later. My plan is to secure this one until you cannot with all the madness you can mobilize provoke the error. After that I know where the leaks were and then I can apply them to all the numerous scripts around the other containers. 

So next will be as soon as you get a @test comment here you can test this particular container.

**Comment by luizaogs** [comment]
Ah. I saw it on the needs triage pane so thought you wanted me to do it now. Never mind :)

**Comment by lbestock** [comment]
I just provoked it with not mad clicking, just what I consider ordinary use (I wasn't trying to).
I took a locus photo. I then clicked in the description field. I got the "stop executing script" message, clicked, and it shut filemaker. When I went back in, my photo was there.
I repeated my steps with a second photo. This time it didn't even give me the dialog, it simply shut filemaker. And this time my image was not there.

**Comment by urapadmin** [comment]
### @test 11.6.25
I have plastered the code with commands to disallow user interruption. I hope it helps. Unfortunately every single bloody script has to disallow it again (we have hundreds of them), so I will always miss out on the one or the other. Filemaker is really so bad.

**Comment by luizaogs** [comment]
Ha, I got it again (again with mad clicking). I think it might have had to do with accidentally clicking on the pinboard? I'm sorry, this isn't very helpful but not sure how else to keep track of the mad clickings...

**Comment by urapadmin** [comment]
I don't really know what else to do. If it only happens with mad clicking (you mean tapping, you are testing this on the ipad, right?), I would live with it. If it happens accidentally during normal usage I would want to find out about the exact location. Since Laurel's last occurrence while using it normally I have added several more operations to avoid user interruptions and we have the Please Wait panel now. 
So I'd wait for the next unforced appearance and then try to dive deeper into that one. By the way, it can potentially happen everywhere and locus photos are not necessarily the most vulnerable part. Locus relations, might be worse.

**Comment by luizaogs** [comment]
Yes, testing on the iPad. And alright, then I'll leave it alone (unless you want me to see how it fares in locus relations, that is).

**Comment by urapadmin** [comment]
let's just leave this open and report here when it happens during our normal tests (and since we just tested locus relations extensively it does not seem to happen easily).

**Comment by urapadmin** [comment]
- [ ] documentation: We will presumably not be able to get rid of it entirely. The thing needs documentation so that users have a chance to know what to click on (don't cancel the script) and that it is benign. I have seen this happening during our video tutorial filming at least twice in totally different parts of the system.

**Comment by luizaogs** [comment]
Just for the record, I just added 40 images in two different layouts and never got this. (I wasn't trying to provoke it, of course.)

**Comment by luizaogs** [comment]
And if we document this (add to the Q&A guide) I think we can close it too, no?

**Comment by urapadmin** [comment]
it can always pop up in different locations. It gets down to me having to tell FileMaker over and over again not to allow the user to cancel a process. And I will forget this over and over again. So I think the best way is to document it as a phenomenon and then make a new ticket wherever it pops up again.

**Comment by luizaogs** [comment]
Ok. I'll add it to the Q&A in a bit.
