### ISSUE TITLE
images without a direct identifier should show "included in" identifiers in the file repository overview

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#1265]
I think this is working, at least there is definitely an "included in" even if there is not a "directly assigned to". But things with only the former still do not look like they have an identifier in the file repository:
![image](https://user-images.githubusercontent.com/49291909/138524021-37e4fcc9-4861-42da-ae01-f7285e7de7bb.png)
I think we want that "included in" to show up as the context in the tile view in file repository if that is possible. It doesn't matter with this example since it was arrived at by searching the context, and thus clearly belongs to it, but I can envision cases where it would be confusing.

_Originally posted by @lbestock in https://github.com/urapadmin/kiosk/issues/843#issuecomment-949967320_

**Comment by urapadmin** [comment]
### kiosk 1.3
- if (and only if) the image has no direct identifier the indirect identifiers will be shown in brackets.

**Comment by luizaogs** [comment]
The stop licking Omar (poor kitten) now has the identifier in parenthesis and other images in the file repository still look as they should, so I think this is working.
