### ISSUE TITLE
jpf image file format incompatible

### ISSUE THREAD

**Issue by lbestock** [arch-kiosk/arch-kiosk-office#1288]
Adobe has a new image file format, the jpf. I accidentally made a bunch of them thinking I was making jpgs - it seems to be Photoshop's new default. If I did it, others will do it. I tried to import them into kiosk and got tentaculaires. 

I was going to attach one here for you but GitHub doesn't support it either and I can't.

**Comment by urapadmin** [comment]
Is this meant to be an export format of photoshop or photoshop's own 
file format? We do not suppord .psds either (if so then rather by 
accident). There are bizillion of proprietary file formats out there.

You can always append all kinds of file formats by zipping them first.

Am 12.01.2022 um 18:51 schrieb lbestock - ***@***.***:

**Comment by urapadmin** [comment]
JPF is the extension of the JPEG2000 image file format which supersedes JPEG. It is poorly supported by browsers. Only Safari supports it. That means as an output format it is by and large useless for us. We could support it as an import format.

**Comment by urapadmin** [comment]
do it together with #846

**Comment by urapadmin** [comment]
I have no idea how you even made those jpfs. My photoshop is not offering me any such thing and is spitting out normal jpegs. So what exactly did you do and could you please provide an example file?

**Comment by urapadmin** [comment]
Ah, got it. Save As and then JPEG2000.
So jpf is really not a new standard in Photoshop. In fact it has always been there. You just should not use "save as" but "export" and then use JPEG (I suppose you can choose JPEG also in "save as".

**Comment by urapadmin** [comment]
### Kiosk 1.3
JPEG2000 now supported as jp2, jpx and jpf

**Comment by luizaogs** [comment]
Hmm. My jpf is still a tentaculaire (the tag is "sunny", so you can find it)

**Comment by urapadmin** [comment]
very sunny. 🌞 
Much unlike New England.
Please try again with another one.

**Comment by luizaogs** [comment]
Try Chicago. Gross.

This one worked (llama)

**Comment by urapadmin** [comment]
you may, but the important part is really to see if the format gets processed correctly. A real llama would be nice :)On 5. Jan 2023, at 10:28, luizaogs ***@***.***> wrote:﻿
Should I try jp2, jpx too?

**Comment by luizaogs** [comment]
Ha turns out that I don't know how to get either of those.

**Comment by luizaogs** [comment]
But you get a real llama anyway (tag is real llama, of course).

I saw that real llama spit on some tourists. Funny times.

**Comment by urapadmin** [comment]
oh, they are the same thing. Just with a different file extension. So renaming a .jpf to .jp2 does it. On 5. Jan 2023, at 12:14, luizaogs ***@***.***> wrote:﻿
Ha turns out that I don't know how to get either of those.

**Comment by urapadmin** [comment]
that one looks like quite looking down on some tourists, ready to fire again.

**Comment by luizaogs** [comment]
Pff no, it was saying hi to me!

**Comment by urapadmin** [comment]
oh :o) But it does look a bit condescending, doesn't it?

**Comment by luizaogs** [comment]
Certainly, but with reason - the llama is clearly much cooler than I :)
