### ISSUE TITLE
locus navigation with arrows does not trigger qc warning

### ISSUE THREAD

**Issue by luizaogs** [arch-kiosk/arch-kiosk-office#1294]
Not sure if this is purposeful, but if I am switching between loci with the arrows in the top banner rather than going back to the locus menu and picking one from there I do not get that "something looks really wrong" message if there are errors on the form.

**Comment by urapadmin** [comment]
I am not sure, either, frankly. Stepping through a bunch of loci would be a real pain if a few of them have issues. 
But it is certainly a backdoor out of the check. @lbestock What do you think?

**Comment by urapadmin** [comment]
we keep it the way it is. I am actually glad it doesn't trigger qc.
