### ISSUE TITLE
switch from pip-compile to handling of the requirements manually or by pycharm itself

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#1310]
pip-compile causes only problems one would not have without it.

**Comment by urapadmin** [comment]
or think about it again. The one feature of pip-compile, to make sure no version gets installed that is too new for some package is perhaps a good feature. But whenever possible the version that's being used in the development environment should be used.

**Comment by PeterDeathBredon** [comment]
no, don't think about it. It sucks. 
see #1647

**Comment by urapadmin** [comment]
turns out that pip-compile lowered my flask version to 1.1.1 or so because I had set it to that in the requirements.in. So that was my bad. However, pip-compile still tries to install version higher than those in the development environment and I simply don't like that. It would mean that the target system runs on more recent code than my local development system for which I wrote the code. 

I'd rather come up with my own way of just replicating the current requirements.txt on the basis of a new requirements.dist documented here.

**Comment by urapadmin** [comment]
- [ ] implement collecting kiosk requirements in packkiosk
- [ ] implementing deleting packages in unpackkiosk
- [ ] implement installing kiosk requirements from local packages in unpackkiosk
- [ ] implement installing kiosk requirements in unpackkiosk

**Comment by urapadmin** [comment]
### kiosk 0.26
- [ ] Needs a test on a computer that already had Kiosk
- [ ] Needs a test on a new computer

**Comment by urapadmin** [comment]
done, but leaving testing for the next time a server needs to be set up or updated.

**Comment by urapadmin** [comment]
Looked okay when setting up the new arch1900 server.
