### ISSUE TITLE
iPad kiosk can't scroll in edit file view in file repository

### ISSUE THREAD

**Issue by mcornacchia25** [arch-kiosk/arch-kiosk-office#1323]
On the purple iPad, I went into the file repository and clicked on the thumbnails of several images. I can't scroll down in any of these edit file windows and the text below is cut off.

**Comment by urapadmin** [comment]
Safari. Hmpf. here a screenshot would help me to see what your viewport shows. On what iPadOS Version are you on that device?

**Comment by mcornacchia25** [comment]
![IMG_2C80190E9133-1](https://user-images.githubusercontent.com/96021337/150877911-868eecb3-56e8-433d-8937-9c759e07f3c6.jpeg)

Here's a screenshot. The iPad is on 15.1

**Comment by lbestock** [comment]
Here's a funny picture of two minis next to one another (Laurel's new 6th gen and purple) doing it differently:
![image](https://user-images.githubusercontent.com/49291909/151036260-01906c3d-e7e8-4685-82ae-78a0180f250d.png)

**Comment by urapadmin** [comment]
the difference between the 2 ipads is okay. The new ipad simply has more pixels and so the edit controls can be shown right of the image. The question is: Were you able to scroll on the smaller one?

**Comment by urapadmin** [comment]
well, since that is the purple ipad I suppose the answer is no :o)

**Comment by urapadmin** [comment]
ja, Safari (and in this case also Chrome since they are forced to use Apple's shitty rendering engine) does not scroll there, rendering the dialog useless with some images. I need to fuzz around with layouting options.

**Comment by urapadmin** [comment]
### kiosk 0.25.1
- I think I have improved this. Everything should be accessible now

**Comment by lbestock** [comment]
Works just fine in Chrome and Safari.
