### ISSUE TITLE
system messaging: system messages do not get updated until changing the current website or refresh it

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#1353]
I was staring for quite a while at administration and the file repos while the system messages changed in the background.  
The current view does not get updated. But it should.

**Comment by urapadmin** [comment]
### kiosk v0.14.6
- Messages should go away once somebody closes them. So open two browser tabs and close the message in one. After a while (up to a minute) the messages should disappear in the other.

**Comment by urapadmin** [comment]
I have seen it work on Beset. But I have also seen it not work. So it seems still flaky at least in the minutes after the server restarted.

**Comment by urapadmin** [comment]
This here is really about the messages disappearing automatically once they have been closed by anybody somewhere. So If you have to refresh your tab it is still not working. 
But I can imagine that we have a cache issue here, too. So I would ask you to really reset your cache - the thing I never know how to do on a Mac. In Windows/Firefox or Chrome the lightest version is ctrl+F5, the most thorough version ctrl+shift+DEL.
Mac do not even have a DEL key. We should document how that works on a Mac, I think.

**Comment by luizaogs** [comment]
I usually clear the cache on my Mac by going into the Chrome settings -- more tools -- clear browsing data.

**Comment by luizaogs** [comment]
And now it worked! Weird since I had cleared the cache last night, but maybe it wasn't immediately before testing this. At any rate, it works it seems.

**Comment by urapadmin** [comment]
I do. Because I saw it working, too and then I saw it not working. Let's keep it under observation for a bit.

**Comment by urapadmin** [comment]
-[ ] I missed out on this one:

**Comment by luizaogs** [comment]
Just tried this again, right after clearing the cache, and it only worked with a refresh.

**Comment by urapadmin** [comment]
Perhaps I should have mentioned that it can take up to a minute before the message disappears automatically in the other window?

**Comment by urapadmin** [comment]
as do I since I forgot that I mentioned it :o)
So it worked with a bit more patience?

**Comment by luizaogs** [comment]
Yes, just tried again.

**Comment by luizaogs** [comment]
This is working in PVD in 0.19, just fyi.
