### ISSUE TITLE
field manager: logging does not work anymore

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#1368]
no matter what process one starts or with what workstation, if MCP is involved then logging does not work anymore. 
It seems that the central KioskLogger class is not catching anything. Might be a late side effect of #903. 

That must be also the reason for #1354

**Comment by urapadmin** [comment]
### kiosk v0.15
  - that was just little oops. Should work again.

**Comment by luizaogs** [comment]
Works.

**Comment by urapadmin** [comment]
needs reopening again since it does not work on PACHA

**Comment by urapadmin** [comment]
### kiosk 0.16.2

this is a borderline case: It does work. But if one is too quick in cancelling the job and the error message is "Can't set os_pid for job with status JOB_STATUS_CANCELLING" then there is indeed no log because the operation did not actually start.

- I am indicating this now with "- there will be no further log for this error." after the error.
It can be provoked only by starting an operation in the field manager and then quickly click on the workstation and cancel the operation.

**Comment by luizaogs** [comment]
Yep, this is there now.

**Comment by urapadmin** [comment]
the latter extension is pretty special knowledge but I added the user manual anyhow since it is knowledge after all.
