### ISSUE TITLE
Canon Raw File blocks fork

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#1369]
Just to make sure, is this the error that should appear if the zip would be too big?

<img width="1512" alt="Screen Shot 2022-02-13 at 7 31 44 PM" src="https://user-images.githubusercontent.com/67970402/153785578-2965ee2c-3dca-4f3b-9a54-e67c50860697.png">

_Originally posted by @luizaogs in https://github.com/arch-kiosk/kiosk/issues/1363#issuecomment-1038533631_

**Comment by urapadmin** [comment]
@luizaogs: 🦢 . I can't reproduce this even on Beset.

**Comment by luizaogs** [comment]
:(

Are you using my file picking rules? Because I used dummy for contextuals in an attempt to dodge it.

**Comment by urapadmin** [comment]
can't do it

**Comment by luizaogs** [comment]
I seem to manufacture issues left and right, yikes.

**Comment by urapadmin** [comment]
can you make this happen again?

**Comment by luizaogs** [comment]
I can try...

**Comment by luizaogs** [comment]
Can you go back to the 100MB limit?

**Comment by urapadmin** [comment]
that I can do ... done.

**Comment by luizaogs** [comment]
Ugh. I used the same settings as I had before when I got that (I believe) but now I get the "export is too big" error. I don't know what to tell you.

**Comment by urapadmin** [comment]
ja, that happened to me, too. Then I bumped the limit up to 500 and in the end it started exporting.

**Comment by urapadmin** [comment]
well, at least I have a clear error message to go with. I will try to hypothesize about what might have happened. But not today. Hungry. 🇭🇺 (There is only a :hungary emoji)

**Comment by urapadmin** [comment]
the logs did not reveal more and the code looks okay. I have added a few more log lines to have a better picture should this occur again. I have deleted the raw files in question and now add them to the file repository as a zip-file (I can't add them to GitHub, they might be too large). They can be found under tag "issue_#1369".

**Comment by luizaogs** [comment]
Speaking of "under observation," I have never ever seen this again.

**Comment by urapadmin** [comment]
means it just bloody happened again or let's forget about it?

**Comment by luizaogs** [comment]
The latter.

**Comment by urapadmin** [comment]
you may do your favorite thing then...

**Comment by luizaogs** [comment]
If you insist.
