### ISSUE TITLE
file manager: Presumably a caching issue when downloading files that came out of an export

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#1372]
this comes out of #1370 and #1365 where @luizaogs repeatedly had the problem that her changes to the export workstations were not leading to a change in the downloaded zip file. 

This has never happened in Windows/Firefox so far.
@luizaogs: Can you please add OS and Browser here? And I suppose you just use the Finder to open the ZIP files, right?

**Comment by luizaogs** [comment]
Yes, I use Finder. 

Chrome 98.0.4758.80, Mac OS Monterey 12.2.1.

**Comment by luizaogs** [comment]
Hmpf this just happened again in 0.16.3, same operating system as above, as I am testing #1453.

It happened twice (by which I mean, twice I exported Excel files and got CSVs in my downloads). Once I cleared my cache, and exported again without changing any settings, it worked.

**Comment by urapadmin** [comment]
ja, that really looks like a rather severe caching failure. We leave it open until I get my hands on a Mac and time to care about it.

**Comment by urapadmin** [comment]
had that on Chrome on Windows, too. Now with reporting, which uses the file manager for download. That needs to be tackled before May.

**Comment by luizaogs** [comment]
I've basically always had this issue when using the file export but just tried five different downloads, changing the settings in between exports, and had absolutely no issues so I am inclined to think that it is fixed.

**Comment by urapadmin** [comment]
it is a possibility. Let's leave it in "under observation" for a bit.

**Comment by urapadmin** [comment]
I think we are over this one, now.
