### ISSUE TITLE
new way of dealing with locus-type specific data

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#1374]
The current way of dealing with it in the first tab of the locus information is not sustainable. More data has to be included there and so we run out of space. But also the layout gets too complex and too slow if we cram in more fields that have to be switched between visible and invisible. 

So it needs a new solution. Making a new tab is only partly a solution. It would solve the space issue but not the issue of complexity. So in fact a complete change of layout would be better. A pity that Filemaker does not know subforms, like Access does. 

👉 we will move type-specific locus information to a new layout.

### prerequisites
- [x] #1409
- [x] #1404
- [x] #1405
- [x] #1406

**Comment by urapadmin** [comment]
I start with #1376

**Comment by urapadmin** [comment]
### first test kiosk 12.1.0
This is just a first test if we want to do it that way. It should work as before just with separate layouts for the details of a locus type. See also the more specific test issues in the body of this ticket here.

**Comment by luizaogs** [comment]
This is all working (but see ticket #1410)
