### ISSUE TITLE
extend archictecture data

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#1375]
locus type architecture needs an update. We also want to add more detailed mudbrick (and perhaps stone?) analysis.

- needs a concept first (with @lbestock)

### prerequisites
- [x] #1374

**Comment by urapadmin** [comment]
@lbestock: We have to do look at FAIMS again and see if our architecture data covers what Parker needs.

**Comment by lbestock** [comment]
It doesn't even cover what we need - he's got N brick sizes and that is so great and I want it. No more ranges, just objective measurements of actual bricks.

**Comment by urapadmin** [comment]
@lbestock: It's fine that you find it great. I need to know what the summer projects actually need and if they need more than we have right now. You want to clarify that with Parker. Now.

**Comment by urapadmin** [comment]
@nparkervan: Perhaps you can help here. If you look at a locus of type architecture and the details for the type. Is that enough for you or is there anything you would want added for this summer?

**Comment by urapadmin** [comment]
okay, I move this until after the summer projects. There does not seem to be any additional need.

**Comment by luizaogs** [comment]
After this season I have ideas for this. Recording individual blocks as collected material worked but isn't ideal because then registration and looking at actual finds is difficult. So anyway, if you guys want to return to thinking about this the MDAP data might be useful and I would be happy to talk about it, too.

**Comment by urapadmin** [comment]
oh, are you back on US turf?

**Comment by luizaogs** [comment]
Not yet.
