### ISSUE TITLE
extend deposit data

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#1376]
deposit data needs an update. 

### prerequisites
- [x] #1374 
- [x] #1419
- [x] #1420

### tracking
- [x] #1431

**Comment by urapadmin** [comment]
# spec
 - the soil particle sorting is controlled by the config key valuelists/valuelist_particle_sorting. -
 - the valuelist refers to images managed by the now extended "customize design" option you find on the start page under "admin"
 - the custom design form shows an error message on entering if you are not in a template file. You can make changes but those changes will not sync!

**Comment by urapadmin** [comment]
### recording 12.2
- should be fully implemented (see specs)

**Comment by lbestock** [comment]
I want us all having an eye on this one, please @luizaogs @mcornacchia25 @lbestock

**Comment by luizaogs** [comment]
I believe this is all working for me.

**Comment by mcornacchia25** [comment]
This all seems to be working for me.

**Comment by urapadmin** [comment]
all checked here -> closed.
