### ISSUE TITLE
locus form: deleting a locus seems to trigger qc for that locus

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#1400]
I deleted an accidentally made locus (made in the locus layout with the plus button) and got a qc warning after the locus got deleted. On dismissing it I found myself back in the locus list of the unit (correct).

**Comment by urapadmin** [comment]
### test: recording 12.1.0
fixedin both cases:
- when the locus is totally empty
- when the locus has related records (locus photos or some such)

After deleting the locus the locus edit form should close and got back to excavating.

**Comment by luizaogs** [comment]
Two questions: I should only be able to delete as admin, right? And by going back to excavating you mean back to the locus list?

**Comment by urapadmin** [comment]
that would be two yesses.

**Comment by luizaogs** [comment]
Splendid.
