### ISSUE TITLE
locus relations: Kiosk needs to synchronize and fix the new chronology field

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#1401]
not only that: Also fixing problematic locus relations needs to fix the chronology field

**Comment by urapadmin** [comment]
do it with #1094

**Comment by urapadmin** [comment]
### test: kiosk 0.16
- should synchronize the new chronology field correctly
- when kiosk adds missing or replaces corrupt relations it will add the chronology now by choosing the opposite chronology for the opposite relation. To do that it accesses the same config key we use in filemaker

**Comment by luizaogs** [comment]
Ha well, clearly I should look at all new tickets being tested before assuming that things are bugs.

**Comment by urapadmin** [comment]
working like this with tickets is just a bit messy. Next to the thing called "overthinking" there is also "over-optimization", which I fall into the longer I think about how to organize us here. 
🥳 I think we do it nicely, currently.

**Comment by luizaogs** [comment]
:)

This works.
