### ISSUE TITLE
locus type architecture: test layout

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#1405]
### test recording 12.1.0
the layout that would have been revealed on the locus layout itself moved to its its own layout, triggered by the "record details" button on the locus form.

- [x] test especially the little record markers in the lower right corner
- [x] test if switching from locus to locus show the correct forms and data when the locus types vary or stay the same across several records
- [x] test compatibility with current data (so the old pvd data should now simply show in the new layouts)

**Comment by luizaogs** [comment]
Same comment as in #1436
