### ISSUE TITLE
locus type deposit: test layout

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#1406]
### test recording 12.1.0
the layout that would have been revealed on the locus layout itself moved to its its own layout, triggered by the "record details" button on the locus form.

- [x] test especially the little record markers in the lower right corner
- [x] test if switching from locus to locus show the correct forms and data when the locus types vary or stay the same across several records
- [x] test compatibility with current data (so the old pvd data should now simply show in the new layouts)

**Comment by luizaogs** [comment]
Hmm, currently I seem to be unable to click on the "record details" button -- both for new loci and old PVD loci. I see it but it's really faint against the dark background and I can't do anything with it: 

![IMG_E9603F0F96F8-1](https://user-images.githubusercontent.com/67970402/155258511-e8cb7dec-5118-4611-9158-445d4a8645de.jpeg)

**Comment by luizaogs** [comment]
Well ok this was the screenshot for architecture but I'm having the same problem across all of them.

**Comment by luizaogs** [comment]
I'm just kidding. I missed that other ticket about configuration, I think...

**Comment by urapadmin** [comment]
well, at least it really does not look right, faint as it is.
But yes, for it to function properly the locus types need to be setup properly for PVD. see #1374

**Comment by urapadmin** [comment]
the faintness is an error. While the button is invisible the label isn't. That's a small thing. Keep testing with the locus type set up

**Comment by luizaogs** [comment]
Yes, now that I've figured out the configuration this is working. Should I make the faint thing a new ticket? It applies to all of them (and is visible for locus types such as container, for which it shouldn't show up at all?).

**Comment by luizaogs** [comment]
I just answered my own question here because it became a bigger problem in locus type other, so see ticket:
