### ISSUE TITLE
locus elevations: synchronize the new ten! elevations fields

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#1407]
just add the new fields to the data set definition.

**Comment by urapadmin** [comment]
### test: kiosk 0.15.1
- please test if all the elevation fields synchronize properly

**Comment by luizaogs** [comment]
Works.

**Comment by urapadmin** [comment]
I have to reopen this one because of #1417

**Comment by urapadmin** [comment]
- [ ] add center elevations to dataset definition

**Comment by urapadmin** [comment]
### recording 12.2, kiosk 0.16.1
this should work now. see #1417

**Comment by mcornacchia25** [comment]
This worked for me.
