### ISSUE TITLE
locus_types: synchronize new field detail_layout

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#1409]
the locus types have a new field "detail_layout" pointing to the name of the layout that shows the details for a certain locus type.

It needs to get synchronized properly

**Comment by urapadmin** [comment]
### test: recording 12.1.0 / kiosk 0.16
- pvd needs to be configured on this front. These are the layouts that need to get assigned to the locus types:
  - ac: locus_type_ac
  - dp: locus_type_dp
  - bu: locus_type_bu

**Comment by luizaogs** [comment]
I don't think this is synchronizing, somehow? I'm pretty sure I added the config and synchronized (see log below), but if I go back into a newly downloaded workstation the config isn't there and I need to add it again as admin.

<img width="843" alt="Screen Shot 2022-02-22 at 10 31 16 PM" src="https://user-images.githubusercontent.com/67970402/155262022-49949ccf-cc5a-47fc-a589-60cac89665ff.png">

**Comment by urapadmin** [comment]
oh d**t, I forgot something on Beset :(

**Comment by urapadmin** [comment]
now it should work

**Comment by luizaogs** [comment]
Meh: 

<img width="1512" alt="Screen Shot 2022-02-22 at 11 08 00 PM" src="https://user-images.githubusercontent.com/67970402/155264694-9a6da94d-7dd1-44ad-b830-dd278add9b97.png">

**Comment by urapadmin** [comment]
that was just a hiccup. Don't know why that happened.

**Comment by urapadmin** [comment]
there should be a hiccup emoj

**Comment by urapadmin** [comment]
🛌 💤

**Comment by luizaogs** [comment]
Hmpf I still don't get the config after downloading. I must be doing something wrong!

**Comment by urapadmin** [comment]
what does it mean you don't get the config?

**Comment by urapadmin** [comment]
you entered stuff to the locus types and they don't get synchronized?

**Comment by luizaogs** [comment]
Yes. If I go into locus types after downloading again (after synchronizing) it's all blank.

**Comment by luizaogs** [comment]
Well not all blank, the detail recording specifications.

**Comment by urapadmin** [comment]
we are talking about the layout field, right? Have you typed the layouts in again after I made that last change on Beset?

**Comment by luizaogs** [comment]
Yes. I'll do it again :)

**Comment by urapadmin** [comment]
sorry. little mistakes can cause a lot of confusion.

**Comment by urapadmin** [comment]
but now, really: 🛌 💤

**Comment by luizaogs** [comment]
Jesus. Yes, it is working now and as usual I don't know what I did before. Well. I'm going to bed.
