### ISSUE TITLE
start screen search: list of matching identifiers!

### ISSUE THREAD

**Issue by luizaogs** [arch-kiosk/arch-kiosk-office#1411]
Related to comments in #1403. It might be useful to have a list of matching identifiers come up as one types what they are looking for  in the start screen of FM (would probably make getting to what one is looking for quicker, too).

**Comment by urapadmin** [comment]
### @test 12.3
- There is a new config key: general/"max_find_results". It controls after how many finds the search function on the start page stops in order not to overwhelm the view.

**Comment by luizaogs** [comment]
I'm not getting tags to show up, even if typing them in exactly. Unless the tag identifier is not the actual tag name?

**Comment by luizaogs** [comment]
The alignment is also a bit wonky but not sure if you can do anything about it: 

<img width="885" alt="Screen Shot 2022-04-04 at 6 45 05 PM" src="https://user-images.githubusercontent.com/67970402/161650138-dcfd052d-205e-4884-aa0b-884e3a0dd8b0.png">

**Comment by luizaogs** [comment]
The rest is working!

**Comment by urapadmin** [comment]
### @test recording 12.3.1 
- the layout issue needed me to patch something. Hadn't done that for a while. So with the next update the first workstation will get the message that it got an update and needs to synchronize. Then in the next round the layout issue should be okay for everybody.
- fixed the tag issue

**Comment by luizaogs** [comment]
The orientation is now fine (I synchronized the update) but the tags are still weird. Some (e.g., Oren's Backpack) don't work at all and some only work if there's a space after the text in the search bar (e.g., "Site 11 human leisure zone" gives me nothing but "Site 11 human leisure zone SPACE" does.) So essentially if one copies and pastes the tag from the tag menu thing it will work because the space comes with it, but if someone just types it in and likely doesn't add the space then it does not.

**Comment by urapadmin** [comment]
### @test 12.4.1
- if somebody made a tag with a trailing space, then that space is part of the tag. So that is expected. But I have made sure now that one CANNOT enter a tag with leading or trailing spaces. And I have made the search on the start page tolerant on that fronts for the old tags with spaces.
- Oren's Backpacks fate was its little '. That should work now, too.

**Comment by luizaogs** [comment]
Works.
