### ISSUE TITLE
add labels to the locus elevations

### ISSUE THREAD

**Issue by luizaogs** [arch-kiosk/arch-kiosk-office#1413]
The current layout lacks NW, SW, SE, NE, see below: 

![IMG_84CB47F8D40E-1](https://user-images.githubusercontent.com/67970402/155266009-984578c8-722c-48cd-9941-41b1b4bade64.jpeg)

**Comment by urapadmin** [comment]
well, I thought it would not need labels :o)

**Comment by luizaogs** [comment]
I would never underestimate the need for coordinates :) But I guess they're not super necessary!

**Comment by urapadmin** [comment]
no, full coordinates were not asked for here. It is really only the Z axis. But I guess adding the labels would make this clearer nonetheless.

**Comment by luizaogs** [comment]
You should know by now not to take my sleepy and incoherent ramblings very seriously, ha.

**Comment by urapadmin** [comment]
### test recording 12.2
- [ ] labels are there now
- [ ] there is also a little help message configured by help/help_elevations_short_description. It only shows if there is actually something in that configuration key.

**Comment by lbestock** [comment]
:) @luizaogs you opened this one (though I complained about it, too) so I'll let you be the one to close it when it's closeable.
