### ISSUE TITLE
changing the default setting for the chronology of a locus relation: warning is buggy

### ISSUE THREAD

**Issue by luizaogs** [arch-kiosk/arch-kiosk-office#1414]
If I try to change the chronology of an above relation to "same time as" I get the warning below. Shouldn't it say "Are you sure you want to use 'same time as' instead"? The "don't" is confusing me.

<img width="1023" alt="Screen Shot 2022-02-23 at 9 48 20 AM" src="https://user-images.githubusercontent.com/67970402/155355175-5bd1bbe1-4828-4bc4-a49e-468ac3d082ef.png">

**Comment by luizaogs** [comment]
Also, if I press "no" here I can't leave the relations form -- everywhere I click simply gives me the warning again.

**Comment by urapadmin** [comment]
The former is a typo, 
the latter is a filemaker specialty. If you choose "yes" you can leave without having selected the default, if you choose "no" you have to change your selection. As long as the selection is not finalized the value in the field itself stays what it was. 
I will try to revert the field value, perhaps that has a better feel to it.

**Comment by urapadmin** [comment]
### recording 12.1.1
- I fixed the message 

- BUT there is no way to revert the selection properly so that the confusion between field value and current selection wouldn't occur. That's just filemaker.

**Comment by luizaogs** [comment]
It is better, yes.
