### ISSUE TITLE
relations: default chronology stays if there is no default for new relation type

### ISSUE THREAD

**Issue by luizaogs** [arch-kiosk/arch-kiosk-office#1415]
Ok the title of this issue is not super clear, I know, but I don't know how to phrase it. I also don't know if this is on purpose but since I didn't know I am making it a ticket.

If I start with a relation that doesn't have a default chronology, such as "bonds with", I don't get anything automatically in the chronology selection, which seems proper. However, if I then change that to something with a default -- say, above -- and then change it BACK to "bonds with", "later than" stays in the chronology field.

If I, however, change it from "above" to another type with a default value (say, below), it changes to "earlier than" as it should.

**Comment by urapadmin** [comment]
> Ah, this is also related to "the chron type of B will be removed (if there was one) if the chron type of A is empty" in the specs of ticket #614, I believe.
> 
> I cannot empty the selection box myself. The only way to get it empty is if I start with a relation that doesn't have a default chron value, in which case the chron value of the opposite relation is indeed still empty.

that is a bug. I should add an empty line to the selection because fm go doesn't .. #*+!5$&% allow for removing a selected value (well technically it does, you have to manage to remove the checkmark)

**Comment by urapadmin** [comment]
you can always add that selection to the configuration.

**Comment by urapadmin** [comment]
question remains:
- do we leave it as it is (field values are not replaced on a spatial selection without default) or 
- do we always remove the chron selection on selecting a spatial selection that has no default.

**Comment by luizaogs** [comment]
The "-" does remove it and I get the warning, but it currently only does so for the relation being changed -- the opposite one is not updated. I assume it should be?

**Comment by luizaogs** [comment]
I've also added "indeterminate" to PVD.

**Comment by urapadmin** [comment]
> The "-" does remove it and I get the warning, but it currently only does so for the relation being changed -- the opposite one is not updated. I assume it should be?

### recording 12.2
this should work now
