### ISSUE TITLE
locus elevations: add center elevations

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#1417]
- [x] both opening and closing elevations get another one: a center elevation.

**Comment by urapadmin** [comment]
### recording 12.1.2
- [ ] center elevation as a simple Z coordinate is there now

but we should discuss #1379 on elevations

**Comment by lbestock** [comment]
@mcornacchia25 one for you.

**Comment by mcornacchia25** [comment]
The center elevation field is visible and saved/synched properly in my test.
