### ISSUE TITLE
designer needed: vector graphic svg for soil particle sorting chart

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#1421]
I need svgs for the elements of the soil chart (so one for each type).
the label will be added at runtime, so only the grahic is necessary. But it has to be a real vector drawing (like in touchdraw or illustrator), not just a bitmap packed into a vector format (like pasting a jpg into an illustrator drawing). 

![Graphical-representation-of-grain-sorting-after-various-sources](https://user-images.githubusercontent.com/38838314/155590327-7020737f-63bf-4dc4-a2e9-3bdda111eda8.png)

**Comment by urapadmin** [comment]
@lbestock: Can you do this? Or delegate it?

**Comment by lbestock** [comment]
I can do it!

**Comment by urapadmin** [comment]
I thought so.

**Comment by lbestock** [comment]
![very well sorted](https://user-images.githubusercontent.com/49291909/155632656-dd195db8-f8d1-4022-9bc0-63a2743b95c7.svg)

**Comment by urapadmin** [comment]
works. You may make the other ones!

**Comment by urapadmin** [comment]
"poorly sorted.svg" has a runaway to the left.

**Comment by lbestock** [comment]
Try "terribly sorted" on for size.

**Comment by lbestock** [comment]
"Poorly sorted" updated to delete the runaway.

**Comment by urapadmin** [comment]
okay, we're done here.
