### ISSUE TITLE
formation process configurable

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#1424]
### spec
Formation process gets a default that is configured on locus type level (admin/locus types).
- "enabled" checkmark instead of visible - controls whether formation process can be changed. It will always be visible.
- formation process remains on locus sheet and does NOT move to the type specific layout.
- to allow for an empty formation process the formation process valuelist in both locus layout and locus_type config needs to include a " - " (that's a - surrounded by spaces) as the first element. That's how all valuelists that must offer an empty selection work in future.
- the new formation process default value will be put into the formation process field of a locus on selection of a locus type regardless of what might already be in the formation field.
-  if a locus type does NOT have a default value the selection for formation process in the locus layout will always show no matter if it should be editable or not

### tracking
- [x] #1430 
- [x] #1427

**Comment by urapadmin** [comment]
### recording 12.2
- that should work according to the specs above

**Comment by luizaogs** [comment]
See #1427 and #1429. The rest is working for me.

**Comment by urapadmin** [comment]
### recording 12.2.1
- specs changed because of #1427:  if a locus type does NOT have a default value the selection for formation process in the locus layout will always show no matter if it should be editable or not.

**Comment by urapadmin** [comment]
@arch-kiosk/test: nobody likes this ticket 😮

**Comment by luizaogs** [comment]
Do you need me to do anything else here?

**Comment by urapadmin** [comment]
just close it, if the latest change in 12.2.1 tests okay

**Comment by luizaogs** [comment]
It does.

**Comment by urapadmin** [comment]
thank you :)
