### ISSUE TITLE
locus measurements: width, length, depth, volume need to synchronize properly

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#1425]
- [x] measurements tab gets four new numerical fields: width, length, depth and volume
- [x] they need to be part of synchronization

**Comment by lbestock** [comment]
When the releases are up, @mcornacchia25 this one's for you!

**Comment by mcornacchia25** [comment]
I filled out all of the measurement fields, reuploaded, synched, redownloaded, and they were all correctly preserved as far as I can tell.
