### ISSUE TITLE
invisible (?) formation process?

### ISSUE THREAD

**Issue by luizaogs** [arch-kiosk/arch-kiosk-office#1427]
I'm not sure if I misunderstood this, but from the specs in #1424 it sounded to me like the formation process should always be visible (but not always editable). Well, currently it does not seem to always be visible -- for those locus types without the checkmark that makes the formation process editable I get the label for formation process but nothing next to it: 

![IMG_28C816BE5476-1](https://user-images.githubusercontent.com/67970402/155870574-30812a45-cd54-4e8e-a4c4-807c6bb7ff89.jpeg)

**Comment by luizaogs** [comment]
Ah wait, I assume the default formation process should show up there? I just saw that in the locus types config. Even so, though, once I pick one for burial it still does not show up on the form.

**Comment by luizaogs** [comment]
These are my current settings, for reference: 

![IMG_F0C757C98EFF-1](https://user-images.githubusercontent.com/67970402/155871536-52a4cad0-0e08-4d00-8ec6-061044a84564.jpeg)

**Comment by urapadmin** [comment]
The formation processes default is set whenever you select a locus type and, of course, only if there is in fact a default configured.

What this does not address is setting a value for all the legacy records that have been created before this default thingy got in place and all locus types got a default. That is for another ticket. 

And so whenever you see a label (which you should always see) but no value, this is presumably either a legacy record or a record that got its locus type before a default was configured for that locus type.

for the user's manual: All locus types should have a default formation process.

**Comment by urapadmin** [comment]
so, if what I describe above is in line what you see, this ticket here would not be a bug and could be closed.

**Comment by luizaogs** [comment]
No, I'm not referring to legacy data. With the settings above, I still have the problem described in the third comment, that the default process does not show up for its proper locus type but only when I switch that locus type to something else. So, for instance, architecture (configured above to always be anthropogenic) will not show up with its default when I create a new architecture locus. But if I then switch that locus to type container, it will show up as anthropogenic. But container does not have a default set.

![IMG_42772303F109-1](https://user-images.githubusercontent.com/67970402/155896698-2c5e8df9-3a28-4ac8-b85c-c9d310d98816.jpeg)

![IMG_0286](https://user-images.githubusercontent.com/67970402/155896721-c2dc174d-5b36-44f5-948c-ad7b96e97c37.PNG)

**Comment by urapadmin** [comment]
that's wrong then, indeed.

**Comment by urapadmin** [comment]
### recording 12.2.1
- this should be fixed AND there is a small change to the specs: if a locus type does NOT have a default value the selection for formation process in the locus layout will always show no matter if it should be editable or not.

**Comment by luizaogs** [comment]
Should this appear? Anthropogenic is the default.

![IMG_27E429C5FD48-1](https://user-images.githubusercontent.com/67970402/155903153-bf0832e0-d8f5-4157-a1d4-89962528fc77.jpeg)

**Comment by luizaogs** [comment]
Ha well, it appears whether I click on cancel or ok.

**Comment by luizaogs** [comment]
I also get the following if I create a locus with no default formation process: 

![IMG_55512D112B28-1](https://user-images.githubusercontent.com/67970402/155903227-ba9761b1-d5c5-4bc5-aef9-0f671e6eb518.jpeg)

**Comment by luizaogs** [comment]
Clicking on either "cancel" or "ok" above gives me the selection box, so that part of the new specs is working.

**Comment by urapadmin** [comment]
oops.

**Comment by urapadmin** [comment]
I forgot a message to myself in there (talking a lot to myself through such message boxes all day)

**Comment by urapadmin** [comment]
### kiosk 14.2.2
- this should be done now

**Comment by luizaogs** [comment]
(I was happy to hear the good news this morning!)
