### ISSUE TITLE
help texts in configuration not going away

### ISSUE THREAD

**Issue by luizaogs** [arch-kiosk/arch-kiosk-office#1428]
If I click on one of the configuration items in admin and a green help text pops up, it doesn't go away -- whenever I go back into configuration in the same session that same warning is there. If I log out and come back in as admin the warning is gone but if I then click on another configuration topic that warning will pop up and stay there.

I am sometimes able to change the warning if I click on a different configuration item, but that doesn't always work either.

This is on my iPad, 12.2.

**Comment by luizaogs** [comment]
Oh wait, right, it changes only if I click in the text box of the configuration item.

**Comment by urapadmin** [comment]
### recording 12.4.3
- Gone now when you enter
- it also changes now if you click on the green help button.

**Comment by luizaogs** [comment]
Do you also want them to disappear if you are moving between config modules? They don't currently (so if I click on a help text in labels and move to help, for instance, it will still be on the screen).

This is fine otherwise, though.

**Comment by urapadmin** [comment]
### 12.5
- help text vanishes between category changes.

**Comment by luizaogs** [comment]
Hmm it is not vanishing.

**Comment by luizaogs** [comment]
Wait, this is on my Mac. Let me check the iPad.

**Comment by luizaogs** [comment]
Ja, not working on the iPad either.

**Comment by urapadmin** [comment]
### 12.5.1
battling the rubble here. I hope I got this now

**Comment by luizaogs** [comment]
Yup!
