### ISSUE TITLE
help buttons in locus types config confusingly placed

### ISSUE THREAD

**Issue by luizaogs** [arch-kiosk/arch-kiosk-office#1429]
Picky. Sorry. But this threw me off so I thought I would point it out. The help buttons below, for additional field set and layout for details, are so far to the right that they seem to refer to layout for details and formation process default instead. If it's possible to move them to the left, closer to the labels they pertain to, that might be helpful.

![IMG_0650C0DE6AF3-1](https://user-images.githubusercontent.com/67970402/155871139-7fb7ae6f-7a37-4bcf-8059-1c52f4aded3f.jpeg)

**Comment by urapadmin** [comment]
### recording 12.2.1
- this is fixed now and the help text is configurable (preparation for a potential internationalization of this layout): help/help_locus_types_help_text
