### ISSUE TITLE
locus types help text: update needed

### ISSUE THREAD

**Issue by luizaogs** [arch-kiosk/arch-kiosk-office#1430]
Should the help text here be editable in configuration? I couldn't find it. At any rate, I suppose it should be consistent so not something I should be updating myself. 

I think it might be good to change the description for the formation process from "should be shown" to "should be editable" or something? The text also doesn't mention layout for details or default formation process, since those are new.

![IMG_F0C757C98EFF-1](https://user-images.githubusercontent.com/67970402/155871536-52a4cad0-0e08-4d00-8ec6-061044a84564.jpeg)

_Originally posted by @luizaogs in https://github.com/arch-kiosk/arch-kiosk-office/issues/1427#issuecomment-1053244386_

**Comment by urapadmin** [comment]
### recording 12.2.1
- this is fixed now and the help text is configurable (preparation for a potential internationalization of this layout): help/help_locus_types_help_text
