### ISSUE TITLE
two error messages upon entering "customize design" in admin

### ISSUE THREAD

**Issue by luizaogs** [arch-kiosk/arch-kiosk-office#1431]
I know I should get an error when entering this form since I'm not using a template, but I am getting two different errors and not totally sure if the first one should pop up or not. So:

Before I get to the "This is not a template" error (which I assume is the one you refer to in #1376), I get the following error both when clicking on customize design and once I'm in customize design, before I get the "this is not a template error". If I click on ok I am able to get past it both times.

![IMG_0284](https://user-images.githubusercontent.com/67970402/155885951-1ff95e33-8daa-4a35-a230-568007a4c915.PNG)

**Comment by urapadmin** [comment]
### recording 12.2.1
hm. Does not appear on Windows, of course. I have removed a line that might have been the culprit, please try again.

**Comment by luizaogs** [comment]
Yep, it's gone.
