### ISSUE TITLE
Reopens measurement field when you press enter

### ISSUE THREAD

**Issue by mcornacchia25** [arch-kiosk/arch-kiosk-office#1437]
I'm working on #1425 in locus measurements.

Not sure if this is intended, but pressing enter on a measurement entry reopens the first field, regardless of whether or not there is text in it. However, when you press enter while the current field is empty, it send you to the next one. This is on the iPad where a number pad shows up for these fields.

**Comment by urapadmin** [comment]
### kiosk 12.2.2
Ja, there was a tab order set. I eliminated it and so hitting enter should not do anything at all anymore.

**Comment by luizaogs** [comment]
Pressing enter currently reopens the keyboard for that same field (so the number pad gets minimized and comes up again automatically). Not sure if that's what's intended.

**Comment by urapadmin** [comment]
ja, that‘s all I can do here, I am afraid.

**Comment by urapadmin** [comment]
means: we have to decide whether we want enter to move to the next field here or stay in the current field. By and large I have given up on tab order almost everywhere because I got too many tickets where it was annoying. 
In this case I am not sure what is more annoying.

**Comment by luizaogs** [comment]
Hm…what we have now might be less annoying but I’m not really sure either.

**Comment by urapadmin** [comment]
perhaps I have misunderstood Meghan's original issue. Perhaps the tab order was simply wrong. There seems some use in hitting enter and going to the next input field (the question unfortunately always remains what happens with the last one). Just closing the keyboard is not an option, I think, in FM.

**Comment by urapadmin** [comment]
@mcornacchia25: Meghan?

**Comment by mcornacchia25** [comment]
Sorry. Must have missed the email. From what I remember, if I pressed the enter button on the number pad in any field, it would bring me back to the first entry and open the number pad there. I guess the optimal behavior would either be to have it move to the next entry or just close the number pad and trigger the flash/processing thing that happens when you click out instead. Because of the size of the iPad mini, it's often difficult to click out of the keyboard without triggering another field, so I often have to click to minimize the keyboard and then click somewhere on the screen to trigger the flash/processing. This is in general, but I'm not sure there is anything that can be done about it.

**Comment by urapadmin** [comment]
I close this. There does not seem to be a preferable solution for it.
