### ISSUE TITLE
drawing (photo) numbers aka. filename attribute

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#1446]
I somehow see this coming. Drawings need their own number. 
How do we go about this? 
- We could give drawings an ascending unique number in Kiosk only. Caveat: The drawing number is accessible in the recording only for images that have been through synchronization. The advantage here is that files (images) that come in through the file repository would get their central number by kiosk, too.  
- If we use the numbering system of the recording we would have to teach kiosk the whole numbering system as well. I'd rather not, that would take me quite a while. 

We would use drawing numbers like this:
- in reporting to refer to images and files (because we might not be able to include them directly)
- file downloads can get the file number instead or in addition to the title. 
- the file repo can include them as filter
- they can be used in future as permanent identifiers that allow access to a file in kiosk

⏰ Just to make sure: This would not only apply to "drawings" (a category of image I don't even know about) but to all images (and in fact all files, I guess? I can't always tell an image from a file). 

----
Okay, this is how we do it:
we'll have a new "filename" attribute for each image. It is a free input. Kiosk only makes sure that no two records use the same "filename" (but it can be reused! When a file is deleted its "filename" can be applied to a different file). For drawings the filename can be used as drawing number, for images to control what filename will be used in data export or when downloading the file. The filename will also be used by reports when they list files.

- It will be accessible in the file repository 
- it will be shown in the recording in the gallery and in the pop-overs. But it is read only in the recording.
- it has to be unique
- if a file has a filename it is used when downloading the image otherwise the usual filename is going to be rendered
- if a file has a filename it is shown in the file repository with the thumbnails
- a file can be found by its filename when using the "description" filter in the file repository

----
- [x] new field "export_filename" in images table in DSD
- [x] #1610
- [x] #1609
- [x] #1611
- [x] #1614
- [x] #1612

**Comment by urapadmin** [comment]
@lbestock: Do you think am ascending unique number is sufficient?

**Comment by urapadmin** [comment]
@lbestock: Laurel? Input needed.

**Comment by lbestock** [comment]
I think an ascending unique number is the right thing, not just for ease for you.  However I do have one concern and that is that drawings are by definition images made not in the system or even on a computer usually. If a project numbers drawings as the drawings are made, that happens outside the system. In that case they would have to add them in the order they were numbered. But honestly that should be possible and even necessary; they should be keeping those drawings in order physically or they would have a major muddle. 

What I don't understand is when you say "Caveat: The drawing number is accessible in the recording only for images that have been through synchronization." Even having been through synchronization, how would a drawing then end up in the recording? Its number is assigned by kiosk. It would have to be linked to its context to end up in the recording. It should, of course, be linked to the context of the thing the drawing represents (in the case of a drawing). How do you envision that happening? Or I guess rather, how is the ascending number going to be created and assigned? I imagine scanning 30 drawings in one go and uploading them all without any contextual information because it would be a much bigger pain to get that to go in automatically than, in this case, to add contexts later one by one. But do I click a button that tells the import to assign all these files drawing numbers? Or does the drawing number get created for an already uploaded image? Or both are possible?

**Comment by urapadmin** [comment]
we have to talk about this. I don't think my solution will work at all for the field from what you write here.

**Comment by urapadmin** [comment]
drawing numbers and photo numbers might also be different? However, USTP needs a list of photo-references to put in the context-sheet form. We have no such thing currently because we cannot refer to an image. I could use the filename their as it would be issues by file export and download but we could also use the photo number there once we have it.

**Comment by urapadmin** [comment]
I think we have two different things here: A general photo number (and that would include photos made with ipads) and what you have in mind as drawing number. I was under the assumption that it is all one, so there is only a sequential photo number. And that can only be generated by kiosk itself. For iPad photos that would happen during synchronization - when the images enter the system for the first time. And for file imports it would be done by the file import. 

I am always assuming here that ALL drawings are photographed. But they can only be labeled with their final number when the system issues that number. I am not sure that that is feasible. 

The only other thing then would be a new identification method for photos and that is a real bummer because that identification method would have to work in Kiosk in the file import as well. We don't have such a thing in Kiosk. That won't happen before Summer and I don't like it.

Finally a totally different, hands on approach: they add their own number to the drawing when they draw it. In Kiosk we allow for a new field "photo number" or so in the file repository. And there they can enter the number that is on the drawing. That's some additional work but doable (photographing and importing it is more work). Should the photo number (an identifier, in fact, so could be a text as well) entered collide with an existing number the system will refuse the number and suggest a new one. Then they can re-label the drawing.

**Comment by urapadmin** [comment]
Okay, this is how we do it:
we'll have a new "filename" attribute for each image. It is a free input of whatever somebody wants to add. Kiosk only makes sure that no two records use the same "filename". For drawings the filename can be used as drawing number, for images to control what filename will be used in data export or when downloading the file. The filename will also be used by reports when they list files.

- It will be accessible in the file repository 
- it will be shown in the recording in the gallery and in the pop-overs. But it is read only in the recording.
- it has to be unique
- if a file has a filename it is used when downloading the image otherwise the usual filename is going to be rendered
- if a file has a filename it is shown in the file repository with the thumbnails
- a file can be found by its filename when using the "description" filter in the file repository

**Comment by urapadmin** [comment]
### kiosk 0.19
this is implemented now (except for the director's view, which can wait).
- the testing should happen in the tracked tickets or it gets too longish here.

**Comment by urapadmin** [comment]
### todo user manual / tutorial:
This really needs an explanation. Something from the archaeologists point of view like "how to manage drawing numbers as filenames".

**Comment by lbestock** [comment]
Has been added to the questions guide, both as a question about drawing numbers and as a question about filenames for reports.
