### ISSUE TITLE
filemaker: making identifier lists 

### ISSUE THREAD

**Issue by lbestock** [arch-kiosk/arch-kiosk-office#1449]
Small formatting issue: the instructions are hidden by the field:
![image](https://user-images.githubusercontent.com/49291909/156859647-28bd175f-3670-4def-957a-7b11902e716a.png)

**Comment by lbestock** [comment]
(Forgot to note: I am on my laptop for configuration, not my iPad. So that is how it looks on a Mac.)

**Comment by urapadmin** [comment]
### @test recording 12.3
Should be okay now.

**Comment by luizaogs** [comment]
Yep.
