### ISSUE TITLE
ustp: spec for new context sheet for reporting

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#1450]
On the basis of the reporting I have made a document that is supposed to serve as the specification. The idea is to discuss and decide details in that document. In the end that is what I will implement.

The document in on the google drive: ustp/specs/SPEC_In_US_Unità Stratigrafica_modello per rilevamento sul campo_2021_ENGLISH.doc. 

- [ ] Candace and Tyler do the specs in the document
- [x] #1530

**Comment by lbestock** [comment]
I do not understand the document or how it relates to the actual recording of data in the first place, and I've been here while you developed the strategy for working on reporting. Maybe we should all zoom so you can tell us what you want us to do.

**Comment by urapadmin** [comment]
that was my intention. I think I have a clear enough concept now to do that, at least for the context sheets.

**Comment by urapadmin** [comment]
Oops. We forgot. Yes, we will keep all documents to share between field projects and us on a google drive. Everything else was too complicated. I have now invited both of you to the google drive on which you will find a folder USTP.

As for the document in question. Just have a quick look at it before we zoom, more is not necessary at this point.

**Comment by urapadmin** [comment]
okay, I have completed the specification as far as I could but that's not very far. I simply don't know enough about too many things and my hunches are not good most of the time. So the document is on the google drive under specs and has a ton of comments in it that mark fields in need of an Archaeologist.
