### ISSUE TITLE
PACHA: Questions and topics for meeting on 03/10/2022

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#1451]
@urapadmin, @lbestock, @nparkervan: collecting topics for our next meeting here as they come up:

- does Parker get GitHub messages? he does not really.
- clarify elevations and coordinates. #1380
- reporting - what do the authorities require and what does Parker expect from the system on this front?
- talk about deposit details: #1419
- #1387 
- discuss and clarify [workflow specification](https://docs.google.com/document/d/1Dk6truLtnCSNiCnt13lfIqvcxaiLMb6ozzK_fvcA7eg/edit) document that will serve as the basis of configuration
- what data of the former season does Parker want imported and how important is that at all?
- i18N gets a bit less likely each day since time is ticking so fast and reporting is big. It might still be happening but I want to rae the real possibility that the whole thing will be in English
- drawing (photo) numbers: #1446 I am planning to introduce a sequential (but not gap-less) automatic number assigned on synchronization (so not in the field). Are drawing (photo) numbers used in PACHA and would that still be necessary the same way now that photos can be imported to be context-bound? What were the rules for that number?

**Comment by urapadmin** [comment]
@urapadmin, @lbestock, @nparkervan: collecting topics for our next meeting here as they come up:

> - does Parker get GitHub messages? 
he does not really.

> what do the authorities require and what does Parker expect from the system on this front?
Parker sends a sample of their former reporting 
> - #1387 
Parker sends something to the google drive

> - [x] discuss and clarify [workflow specification](https://docs.google.com/document/d/1Dk6truLtnCSNiCnt13lfIqvcxaiLMb6ozzK_fvcA7eg/edit) document that will serve as the basis of configuration
Laurel's notes

### we didn't get to these:
- [ ] what data of the former season does Parker want imported and how important is that at all?
- [ ] i18N gets a bit less likely each day since time is ticking so fast and reporting is big. It might still be happening but I want to raise the real possibility that the whole thing will be in English
- [ ] drawing (photo) numbers: #1446 I am planning to introduce a sequential (but not gap-less) automatic number assigned on synchronization (so not in the field). Are drawing (photo) numbers used in PACHA and would that still be necessary the same way now that photos can be imported to be context-bound? What were the rules for that number?

> - clarify elevations and coordinates. #1380
> - talk about deposit details: #1419
we'll discuss that when the first version is out

**Comment by nparkervan** [comment]
I got this!

**Comment by urapadmin** [comment]
Thanks for letting me know.
