### ISSUE TITLE
hub (field manager): heavy refactoring

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#1453]
The "field manager" or "sync manager" is now called the Hub
Workstations are now called "docks" (unless they are recording workstations, which is a kind of dock now)
Recording groups are now called ports. For the time being we will stick to "recording group" in the realm of filemaker recording. It is simply unnecessary work, currently, to rename all references to workstation.

- [x] all kinds of name changes and changes of internal references etc. applied to the core sources
- [x] heavy refactoring of the workstation class architecture in preparation for the new reporting docks.

**Comment by urapadmin** [comment]
### @test kiosk 0.14.3
The whole hub (formerly field manager) needs full testing: 
- create workstations of all types
- edit workstations of all types
- all options should work properly
- synchronization should still run properly (you don't need to test if synchronization actually did its job right, just that it runs)

**Comment by urapadmin** [comment]
@lbestock: That's also a good case for documentation and how complex it can get. If we had a documentation already, all occurrences of workstation, field manager (workstation manager) would have to be renamed. Naming is such a problem ...

**Comment by luizaogs** [comment]
So when you say this is the first round of renaming, you expect that import all workstations, prepare all workstations, etc. still say "workstations" correct? And that I should only look for the new names in the cases you mention with the checkboxes above?

**Comment by luizaogs** [comment]
(I love hubbub.)

**Comment by luizaogs** [comment]
I just tested everything for FM recording (including synchronization), file export, and permanent download docks and it is all working (other than my naming question above). If a single test here is sufficient and we do not need other eyes on it, I believe this can be closed.

**Comment by urapadmin** [comment]
@arch-kiosk/test 

> So when you say this is the first round of renaming, you expect that import all workstations, prepare all workstations, etc. still say "workstations" correct? And that I should only look for the new names in the cases you mention with the checkboxes above?

yes, right, if I'd go and rename all the occurrences of "workstation" everywhere there would be no field season for anybody this year (and I would go mad). We have to live for a while with both old and new terminology mixed. But should you spot a particularly dumb (means confusing) instance of it, let me know and I attend to it. It is easier for me to change it on UI level than in the code.

That being said, we can close this one here. The functional test was most important.

**Comment by luizaogs** [comment]
Got it!
