### ISSUE TITLE
recording: formatting in locus

### ISSUE THREAD

**Issue by lbestock** [arch-kiosk/arch-kiosk-office#1483]
locus layout formation process slight formatting bug

I select the formation process and it looks fine.
If I then click on the black area below the formation process, a white sort of shadow text appears over the formation process rendering it unreadable. It says "natural" if what I have input is "natural", and "anthropogenic" if what I have input is "anthropogenic". This happens either on the iPad or on the mac. The screenshot is from my iPad PVD but I also just saw it in the demo version (both are 12.2.2).

![image](https://user-images.githubusercontent.com/49291909/158081421-8f197f6a-8b0b-4f5e-8058-79cf8d14545f.png)

**where exactly did it happen**
filemaker
- locus layout, formation process

**Comment by luizaogs** [comment]
I had not seen this before and I know I just closed #1424 but this is still happening in 12.4.1, too.

**Comment by urapadmin** [comment]
### @test recording 12.4.2
ja, there was still something twisty. Again:
| locus types formation process default? | formation process editable? | visible in locus |
| ------------------------------------------| ----------------------------- | ---------------- |
| not given | not set | the listbox |
| not given | set | the listbox |
| given | not set | the label (no editing) |
| given | set | the listbox |

**Comment by luizaogs** [comment]
Ok I believe this is all good now.
