### ISSUE TITLE
backup and restore file repository automatically

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#1493]
currently the file repository has to be backed up externally. It is not included in the backup process under administration.
It would be much easier to explain backuping kiosk if it were included. 

- [x] A simple backup to an external folder should do. In Kiosk one selects a path for the backup anyhow, so let's just copy the file repository into a sub-directory "files" in that path. A second backup into the same folder should just add modified or new files to speed up the process.
- [x] restore works the other direction.

**Comment by urapadmin** [comment]
what about restore? It should also restore things, shouldn't it? Housekeeping can deal with the cache later on.

**Comment by urapadmin** [comment]
### @test kiosk 0.20
- backup now has a "backup file repository" checkbox that backs up the file repository - that can take a while on first use but should be fairly quick subsequently
- restore has a checkbox "restore file repository, too" that works in the other direction

so if you backup first and then delete a bunch of images from the file repository and then restore they should be back.
But: You do have to run housekeeping - it recreates the thumbnails for the restored images.
When you query the file repository you may run into a cache issue, so if you don't see thumbnails after the housekeeping run, use Strg+F5 or whatever it is on Mac to force your browser to do a full reload.

**Comment by lbestock** [comment]
Works like a charm. I did not run into the cache issue. I ran into no issues. It was easy and intuitive and did what it was supposed to and I have added how to do it into the questions document (though that can't be finished until we have done and described this from a local server).
