### ISSUE TITLE
locus: collected material list needs filters

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#1498]
The list of collected material ought to have filters:
- by cm type/small find type

**Comment by urapadmin** [comment]
see also #287

**Comment by urapadmin** [comment]
### @test recording 12.3
- there is a filter now that filters the type / small find type by text
- there is also a row counter now that shows how many rows the filter yielded

**Comment by luizaogs** [comment]
Ok, dumb question (have you missed those?). Filtering by type (bulk, small find, and sample) works fine, but I am not sure what you mean by "small find type"? If I try to sort by material of the small find nothing happens.

**Comment by urapadmin** [comment]
once you have given the small find a type it shows up behind the collected material type in the list in the locus:
something like "small find/broken pot". And then you can filter for "pot", too. That way you can count all the gold coins you found in the locus and think again if handing it over is the right thing to do.

**Comment by luizaogs** [comment]
Ah.

**Comment by urapadmin** [comment]
### @test 12.4.1
reopened because of #287: identifier did not fit.
- I have done the same here as in full excavation: identifier / lot appears in one field if there is a lot. And the heading shows "/lot" if use_lots is on.

**Comment by luizaogs** [comment]
Same question I had in #287 applies here - if use_lots is off the lot disappears from the heading but the lots show up in the list. Correct?

**Comment by urapadmin** [comment]
yup here too
