### ISSUE TITLE
PASU (s'URachi): improve presorting UI

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#1499]
Not sure if the ui should move somewhere else. Perhaps it is okay to keep it in collected material under "ceramics". But it might want some improvements:

The new UI should have a few helpful features that could make inputting that kind of data easier. 
- [x] The first and easiest thing would be to add a new record that copies the functional category from the last record. Assuming that they work methodically one functional category at a time.
- [x] it should have sorting by functional category, 
- [x] it should show the basic sums and count as they appear in Peter's excel sheet.
- [x] it should have filtering (and the sums and counts should react to it)
- [x] there is an error when clicking on the little modified_by/date button.

**Comment by lbestock** [comment]
A pie chart per locus makes a lot of sense. It is a quick view on the nature of the locus and thus its interpretation.

A pie chart per unit I think does not make sense in the recording system and I suspect would only be at the GIS level anyway - it is to compare units, primarily.

**Comment by urapadmin** [comment]
new ticket for the pie chart per locus:

**Comment by urapadmin** [comment]
### recording 12.6
- this should all be available now

**Comment by lbestock** [comment]
Pie chart issue: it is not super straightforward as to what the pie chart should show, in fact. I think best would be sherd count per functional category (so adding all the rims, bases, etc). I do not think different slices per component (rims and bases of cooking pots being separate, for instance) makes as much sense.

**Comment by lbestock** [comment]
@aes1884 we'll take a look at this when we meet to do valuelists and really walk through if it is the right solution.

**Comment by urapadmin** [comment]
so? Can we close this?

**Comment by lbestock** [comment]
I declare it good and close this.
