### ISSUE TITLE
importing and exporting identification methods

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#1500]
That was a pain last time because we had to type them in again. Should have at least a simple XML export and import.

Since you are on it: Look at the import and export of qc settings

**Comment by urapadmin** [comment]
qc settings was more than fine. It even allows partial imports.

identification methods can now be imported - they will always only be added. They get new UUIDs, so there can be duplicates after an import. It makes sense to delete the old identification methods first - unless they are needed.

**Comment by urapadmin** [comment]
### @test recording 12.3

identification methods can now be imported - they will always only be added. They get new unique identifiers (not visible), so there can be duplicates after an import. It makes sense to delete the old identification methods first - unless they are needed.

**Comment by luizaogs** [comment]
Same funny switching of the functions of downward and upward arrows as reported in #1501 here.

**Comment by urapadmin** [comment]
Refused for the same reasons as in #1501
