### ISSUE TITLE
import and export collected material types

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#1501]
As with identification methods this is likely something we will copy & paste between projects, so an export and import will come in handy.

**Comment by urapadmin** [comment]
### @test recording 12.3
this exist now (as does the whole collected material type ui).

**Comment by luizaogs** [comment]
So I probably shouldn't be testing this because I don't know what the XML should look like and so can't upload it BUT I can express my confusion at the downward arrow being for upload and the upward arrow for download? The file repository has them configured in the opposite way (and I think pretty much anywhere else I see downward and upward arrows on the internet, but that might be irrelevant).

**Comment by urapadmin** [comment]
see, that's why I need "your's truely". There is something we call "betriebsblind" that keeps me from seeing the obvious. (I also had some Wee Beastie so don't take me too seriously)

**Comment by luizaogs** [comment]
Well I am glad someone appreciates my OCD.

(Wee Beastie is hilarious.)

**Comment by urapadmin** [comment]
it has 47,4%. Nothing Wee about it :o)

**Comment by urapadmin** [comment]
what is OCD?

**Comment by luizaogs** [comment]
Obsessive compulsive disorder. Which is really not something I should joke about, in retrospect. Wee Beastie, on the other hand, is actually funny. So Scottish.

**Comment by lbestock** [comment]
Mmm not just Scottish, Scotch.

**Comment by luizaogs** [comment]
I did look it up :) since when Lutz first mentioned it I had no idea what he meant.

**Comment by urapadmin** [comment]
you guys all have some kind of abbreviation thingy. Indeed not funny on so many levels. 
Hence the Wee Beasty. (Empty 😨 )

**Comment by urapadmin** [comment]
Refused. In this case it is not only a arrow it is combined with a trayish thingy: So something gets out of the tray (export) and something getting into the tray (import). It is correct.
