### ISSUE TITLE
new cm: compatibility issues with cm and small finds records prior to v12.3

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#1502]
This at least is important for urap and pvd:
when the new collected material with types is available, several compatibility issues for former projects have to be solved:

- [x] all cm marked with "isObject" -> now type "small find"
- [x] all other cm must get type "bulk"
- [x] add bulk, sample and special find to the collected material types if there are none
- [x] all small finds descriptions need to be appended to the cm description. The small find description is obsolete

**Comment by urapadmin** [comment]
### @test kiosk 0.17
comes together with recording 12.3 and the new collected material types.

**Comment by urapadmin** [comment]
### @arch-kiosk/test: recording 12.4.1
From my perspective this looks okay.
- Please test the collected materials and small find records you are most familiar with and check that they all have the proper cm type (small finds should be small finds, or whatever it is configured to be called in PVD and the rest should be bulk)
- for small finds: So far we had two different descriptions: one for CM and an additional one in the small finds tab. The latter is gone now but the data should have been appended to the cm description.

**Comment by luizaogs** [comment]
Ok you'll kill me, but: this all looks good in PVD but when you appended the small finds description to the cm description you seem to have missed a space :) (There isn't one after "box" below, for instance.) So, largely irrelevant, but if I didn't point it out I wouldn't be me so here you go.

<img width="647" alt="Screen Shot 2022-04-05 at 2 28 40 PM" src="https://user-images.githubusercontent.com/67970402/161834440-b8d17f57-320b-4fb9-b169-9a2fe9c29b1a.png">

**Comment by urapadmin** [comment]
that is a signature-style omission. You are right but I was too lazy. We'll live with it.
