### ISSUE TITLE
lots: disable the option to add a collected material here.

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#1505]
until #1408 is implemented there should be no option anymore to create a collected material right out of a lot

**Comment by urapadmin** [comment]
### @test recording 0.12.3
- button not available anymore

**Comment by urapadmin** [comment]
Forgot it in extended excavation layout. It has lots, too.

**Comment by urapadmin** [comment]
### @test 12.4.1
now it does not have lots anymore. I got rid of them here.

**Comment by luizaogs** [comment]
Extended excavation layout = full excavating, and by no lots you mean that the lots tab is gone right?

**Comment by luizaogs** [comment]
(If so this is good to go.)

**Comment by urapadmin** [comment]
yes, you got my meaning. When I am moving fast my English gets a bit into trouble.

**Comment by luizaogs** [comment]
Your English is perfectly fine. I just don't know what I'm doing half the time :)
