### ISSUE TITLE
to do, documentation: "how do I X?" guide

### ISSUE THREAD

**Issue by lbestock** [arch-kiosk/arch-kiosk-office#1506]
This is the ticket used to track issues/topics that need to go in the section of the manual that gives answers to basic "how do I?" questions that we expect will be asked by regular users of the software.

Currently we are envisioning this section as its own short part of the documentation.  

### Categories of documentation needed for this:

- text

There is a [working document](https://docs.google.com/document/d/1dqfxMFzLSU4B0CYsFSdqE1Y-TXNcHEl2VY6TkqqsAh0/edit) in the GoogleDrive for these questions.

**Comment by lbestock** [comment]
There is a different [working document](https://docs.google.com/document/d/1z7NWa2Cy64zgrxv6u4SeldYl738V2kmkIT4vIE0ExMg/edit) now where answers grow like cancers.

**Comment by luizaogs** [comment]
Oops?

**Comment by lbestock** [comment]
What? Why oops?

**Comment by luizaogs** [comment]
I always feel slightly bad about imposing order on your chaos with my new organized documents.

**Comment by lbestock** [comment]
This is growing and presumably will never be done, will always need updating. But it has become a thing we think of and update and I don't think a ticket is needed any longer.
