### ISSUE TITLE
remove CM from configuration: identification methods

### ISSUE THREAD

**Issue by lbestock** [arch-kiosk/arch-kiosk-office#1510]
Since CM configuration and application of ID methods now happens in a separate location, the now defunct configuration bits should be removed from the ordinary ID method section of configuration. It is certainly confusing to a configurer, and does it do anything troublesome in the background to have "bulk" as the method in one place and "numerical serial number depending on locus" in the other?

**Comment by urapadmin** [comment]
that's a compatibility issue for the time being. Which method is being used and where the system finds it is due to priorities documented in #1489

**Comment by urapadmin** [comment]
but I have changed the help texts for the cm identification methods in configuration. They say now that the setting is obsolete.

**Comment by luizaogs** [comment]
Hmm these are the cm identification methods in the identification part of config? I'm not seeing any of those warnings in 12.4.3 -- looks normal.

<img width="1022" alt="Screen Shot 2022-04-05 at 5 36 56 PM" src="https://user-images.githubusercontent.com/67970402/161862334-f7ede440-0e09-4a42-bbe2-db1897965534.png">

**Comment by urapadmin** [comment]
I suppose I would have had to patch those and didn't. Next version:
### 12.5
- patched - first workstation must synchronize

**Comment by luizaogs** [comment]
It's there now!

But you said they should be empty and I got what looks like an image uid in features so just checking if it should be there: 

<img width="739" alt="Screen Shot 2022-04-07 at 6 22 59 AM" src="https://user-images.githubusercontent.com/67970402/162187993-fbdc17bc-0682-452c-9edf-270f12703e73.png">

**Comment by urapadmin** [comment]
not an issue but also not optimal, I'll patch this again, I guess.

**Comment by urapadmin** [comment]
### recording 12.5.1
next try. all obsoletes should be empty now.

**Comment by luizaogs** [comment]
They are.
