### ISSUE TITLE
human remains in cm material list gets cut off

### ISSUE THREAD

**Issue by luizaogs** [arch-kiosk/arch-kiosk-office#1511]
This is in 12.4.1, Mac. (Ignore the potatoes. That's small finds. I was trying to check whether changing the name in the configuration worked and was hungry, so...potatoes.)

<img width="921" alt="Screen Shot 2022-04-05 at 3 02 11 PM" src="https://user-images.githubusercontent.com/67970402/161839549-e39564c8-1ab4-4827-9cd4-8048ee24abc4.png">

**Comment by urapadmin** [comment]
I am a Kraut. We like potatoes 🥔

**Comment by urapadmin** [comment]
### recording 12.4.2
- fits now on Windows in full excavation and locus layout

**Comment by luizaogs** [comment]
Potatoes and tomatoes are my favorites (and they rhyme).

Also this is fine now.

**Comment by luizaogs** [comment]
Ha! I like the friendly potato in FM.

**Comment by lbestock** [comment]
It's like a friendly potato in a halo of EU stars. I like it, too, and wish I had made potatoes for dinner.

**Comment by luizaogs** [comment]
I had tomatoes 🍅 close enough
