### ISSUE TITLE
kiosk: show screen capture while downloading a workstation that shows how to proceed

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#1513]
the screen capture should start once the download starts. It should show what to do after the download on ipads.

- see also #1512

**Comment by urapadmin** [comment]
because of #1631 wait with this.Using Chrome might be a real game changer because Apple software just sucks all the time.
when using Chrome the video would look very different and I even wonder if it is necessary at all.

**Comment by lbestock** [comment]
can't get there before the projects start

**Comment by urapadmin** [comment]
ha. That was me writing from Laurel's compute. Still: I can't get there. But in this direction Chrome does help a lot, anyways.

**Comment by lbestock** [comment]
From a user's perspective #1663 was huge here, too. Takes some of the pressure off.

**Comment by urapadmin** [comment]
postponed and we decide again for the next version.

**Comment by urapadmin** [comment]
I think I drop this and just leave it as an idea for the time being. It has issues like different videos depending on the Browser etc. that would make it a real undertaking. So I just take it out of 1.2. 
If we had a platform on which to publish video tutorials we could easily embed a link there. But we don't have any such thing, yet.

**Comment by urapadmin** [comment]
moved to the iOS download upload manager and postponed.
