### ISSUE TITLE
configuration: separate hiding of visibility of count and weight

### ISSUE THREAD

**Issue by lbestock** [arch-kiosk/arch-kiosk-office#1514]
It is imaginable that a project would want to hide only count or only weight for some categories of bulk collected material, not both. Currently while it is possible to choose to show count and weight separately, hiding one but not the other for defined categories of material is not possible. For instance, bulk animal bones should be weighed but not counted.

I would like configuration in visibility to have two separate categories "hide count for materials" and "hide weight for materials".

This is not urgent.

**Comment by urapadmin** [comment]
### recording 12.5
- this is done. There are two different keys now: hide_quantity_for_collected material and hide_count_for_collected_material.
- as long as no material is selected both fields will be hidden from now on

note that the old key to hide weight and count is now obsolete but I cannot delete it.

**Comment by luizaogs** [comment]
I suspect this is a stupid question resulting from unfamiliarity with this part of configuration but those are not the configuration options I'm seeing for cm in visibility in 12.5.1? I get these: 

<img width="827" alt="Screen Shot 2022-04-07 at 6 47 52 PM" src="https://user-images.githubusercontent.com/67970402/162337224-2fa7db60-649a-46f5-897b-13e01ee92321.png">

**Comment by luizaogs** [comment]
So seems like the two are still linked? Or is hide_count_and_weight_for_materials meant to be just count and it's mislabeled?

**Comment by urapadmin** [comment]
the only stupid here is me not learning my own patching mechanism. I would have had to patch this change because it was an existing key (the hide_count_and_weight_for... will be renamed to hide_quantity_for...). 

### 12.5.2
- next try

**Comment by luizaogs** [comment]
Looks good now.
