### ISSUE TITLE
filemaker new CM: cannot create bulk of different materials if ID method is context

### ISSUE THREAD

**Issue by lbestock** [arch-kiosk/arch-kiosk-office#1516]
Testing configuration of the new CM as though I were USTP. So I have set bulk to be the context number, and small finds to be free input (because they use a wacko system there) and samples to be sequential.

In the old CM USTP (and S'Urachi) we had it so that the assignment of a material in combination with the number allowed for a unique ID. Meaning that there could be multiple CM with the same number - it's just the locus number - they were distinguished only by material. This has gotten lost in the new CM and needs to be reinstated. 

I made a faience bulk. I then tried to make an ivory bulk, which I expected to work. I got this:
![image](https://user-images.githubusercontent.com/49291909/161997031-c6d5602f-e952-4d24-8e09-d04abf755a26.png)

(Ignore the SU2013- prefix here. It's a problem but dealt with in ticket #1515.)

**Comment by urapadmin** [comment]
No, this is not how the old USTP is configured. The old USTP simply accepts USTP# even if they are not unique. Only VISUALLY the material helps to differentiate between bulk with the same number. Practically there can be two "1258 animal bone" or more bags.

It is in PASU (s'Urachi) that we have made the material a part of the collected material number and there it must be unique. But It would still crash with small finds.

**Comment by urapadmin** [comment]
I think I will update USTP-test so that you can test the new recording on the USTP test server.

**Comment by lbestock** [comment]
You can't update USTP until they import and synchronize everything, about which I reminded Candace last week.

**Comment by urapadmin** [comment]
that is why we entertain a test server

**Comment by urapadmin** [comment]
what I seem to have lost somewhere is the ability to have non-unique cm numbers at all with the the formatting function idfmt_input.
