### ISSUE TITLE
plural missing in synchronization window (I know, I know)

### ISSUE THREAD

**Issue by luizaogs** [arch-kiosk/arch-kiosk-office#1517]
Hi, hello, a new day, a new annoying ticket from yours truly.

Not sure if this was introduced when you changed the terminology from workstations to docks because I hadn't seen it before but it should probably be "Not all workstationS are back from the field."

<img width="594" alt="Screen Shot 2022-04-06 at 11 04 08 AM" src="https://user-images.githubusercontent.com/67970402/162018463-124a1786-0824-49a7-82e5-bc715ef660e0.png">

**Comment by urapadmin** [comment]
### kiosk 0.17.1
- fixed
