### ISSUE TITLE
typo in deletion warning in file repository

### ISSUE THREAD

**Issue by luizaogs** [arch-kiosk/arch-kiosk-office#1518]
Since you said I could make these tickets if I signed them from yours truly .... I'm kidding, I am not looking for them I swear. 

"Stared" should be "starred".

<img width="399" alt="Screen Shot 2022-04-06 at 11 49 08 AM" src="https://user-images.githubusercontent.com/67970402/162026539-020b3c77-381f-4683-9ba1-b0b1bcbdc150.png">

yours truly,

**Comment by urapadmin** [comment]
### kiosk 0.17.1
- learned something and made it starred

**Comment by luizaogs** [comment]
Will start calling typos wee beasties.
