### ISSUE TITLE
QC only implemented in simple excavation - what about full excavation?

### ISSUE THREAD

**Issue by luizaogs** [arch-kiosk/arch-kiosk-office#1521]
Hmm so my configuration is set to allow QC both in general and in lists, but in 12.4.3 the buttons are gone from the locus list. It's still working in the individual loci themselves, though, so not sure what is up.

<img width="1010" alt="Screen Shot 2022-04-06 at 4 00 15 PM" src="https://user-images.githubusercontent.com/67970402/162070004-1eb000ff-1941-453a-b8f4-3149e1c75e56.png">

**Comment by luizaogs** [comment]
Hm wait. It is there in simple excavating, actually, not in full excavating. Is that how it's supposed to work? Oops if so I never realized it.

**Comment by urapadmin** [comment]
yes, I implemented it only in simple excavation because I got the feeling that full excavation would die ... well, we just revived it so now I think simple excavation will rather die. So I reopen this because I have to do something about it.

**Comment by urapadmin** [comment]
@lbestock:
In fact it would be easiest to move the new collected material list to simple excavation and then get rid of full excavation for good. Unless somebody objects?

**Comment by lbestock** [comment]
I do not object at all. It is what should happen.

**Comment by urapadmin** [comment]
### @test receording 12.5
okay, full excavation given up on. Instead simple excavation now looks like full excavation did before - there should be no difference except that simple excavation has QC. 
To test you have to switch simple excavation on. I leave full excavation and its options in the system until we have finished testing this here. Then it will finally go.

**Comment by luizaogs** [comment]
This looks ok to me visually, in terms of tabs. Is there any configuration stuff (other than QC) that I should be looking for?

**Comment by mcornacchia25** [comment]
Really basic question: What does QC mean? What is it supposed to look like/do?

**Comment by mcornacchia25** [comment]
Managed to get them to show up at least. I don't know if everything's working correctly, but they're at least visible once I switch to simple excavation. One small thing: LA-024 is type fill but the warning given for it both when you click on the red exclamation point and when you try to leave it says "Please select a material for a context of type architecture." Maybe it was previously architecture but then changed context type and the error didn't change?

**Comment by urapadmin** [comment]
ja, you got an old one there that I cannot fix easily. It happens indeed when a locus changes its type (which is pretty unnatural in the field). For reference: #1460 was the old, closed one (don't worry, you could never have found it) and I'll use this here to think about it again.

**Comment by urapadmin** [comment]
I suppose we can close this here.
