### ISSUE TITLE
Collected material Material Type Menu Blocks Itself

### ISSUE THREAD

**Issue by mcornacchia25** [arch-kiosk/arch-kiosk-office#1522]
This is just a small annoying thing. It may be easy to fix, but if not, it's fine to leave it. I'm working on the purple ipad.

When creating a new collected material, I click the plus and then this screen pops up:
![IMG_F46DAAE65882-1](https://user-images.githubusercontent.com/96021337/162105548-88ae315b-44e6-4fbd-b280-edddd722049f.jpeg)

That menu pops up immediately without clicking the menu, and it covers the prompt that the menu is supposed to answer. If it opened to the right instead of the left or if the title was moved, I feel like that would make it a bit more clear. 

But again, not a big deal if it's at all difficult to fix.

**Comment by urapadmin** [comment]
indeed, that is not optimal. I'll see what I can do. Filemaker is deciding on that position automatically, but maybe I can do something to prod it in a different direction.

**Comment by urapadmin** [comment]
### recording 12.5
I tried some trick here:
1. it should not open that material list automatically when the dialog pops up
2. when you open it using the arrow key (from now on you have to really click on the arrow key and not on the text) the selection should be on the right.

**Comment by luizaogs** [comment]
This is working, but the keyboard pops up automatically (rather than the list). If I either minimize the keyboard or click outside of it I can then click on the arrow and proceed as you say above. If that is ok, this can be closed.

**Comment by urapadmin** [comment]
That was not the plan. I am not so sure if that is much better? @mcornacchia25, what do you think?

**Comment by urapadmin** [comment]
ja, that configuration is a mess. I think I will download a version and define a coherent configuration myself so that you guys can test at all. 

### recording 12.5.1
As for the material selection: I have tried yet another trick and hope filemaker go obeys now.

**Comment by mcornacchia25** [comment]
I'm not sure I understand completely how configuration works with respect to uploading/syncing, and I don't want to mess anything up. This morning I downloaded a workstation and attempted some testing before the configuration was fixed. If I upload this workstation, will it mess with any changes you have made in the meantime? If so, is there a way for me to get the new workstation without uploading this one and syncing it?

**Comment by urapadmin** [comment]
thanks to the synchronizing nature of the system you usually don't need to worry about it. 
But on the test server I reset all workstations regardless of their state brutally all the time when I install an update. So if you planned to upload your workstation, you won't be able to do that anymore. 

To get a new one you simply prepare your workstation again and download it, much as you are used to.

And don't generally worry about messing things up: a) we are on a test system and b) if users can mess the system up easily I want to know so I can do something about it.

**Comment by urapadmin** [comment]
ah and by the way, you should now be able to test this particular case now by creating a new bulk collected material.

**Comment by luizaogs** [comment]
This looks good now, no more keyboard.
