### ISSUE TITLE
features:  implement new cm type approach

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#1523]
in feature/collected material we need the same three buttons with the same functionality as in locus to create new collected materials.
Also the cm list needs to be modernized, too.

**Comment by urapadmin** [comment]
### recording 12.5
- this is done. 

Note that collected material in survey units is using its own identification method that depends on the unit number rather than on the locus number as is typical for excavation units

**Comment by luizaogs** [comment]
Now that we have a PVD configuration this looks ok to me but I assume you want the others to check as well so won't close it.

**Comment by urapadmin** [comment]
@arch-kiosk/test: yup, please everybody have a look on the collected material list in here.

**Comment by mcornacchia25** [comment]
Everything looks ok to me

**Comment by urapadmin** [comment]
and closed it is.
