### ISSUE TITLE
survey units: implement new cm type approach

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#1524]
in survey/collected material we need the same three buttons with the same functionality as in locus to create new collected materials.
Also the cm list needs to be modernized, too.

**Comment by urapadmin** [comment]
Note that collected material in survey units is using its own identification method that depends on the unit number rather than on the locus number as is typical for excavation units

**Comment by luizaogs** [comment]
Also working fine for me (though see #1528) but I won't close it in case others need to test it.

**Comment by urapadmin** [comment]
@arch-kiosk/test: Quick look by everybody on the collected material, please.

**Comment by mcornacchia25** [comment]
All looks good to me.

**Comment by urapadmin** [comment]
then I close this.
