### ISSUE TITLE
message when entering collected material list

### ISSUE THREAD

**Issue by luizaogs** [arch-kiosk/arch-kiosk-office#1526]
Ha. I got this message in 12.5 when trying to click on the collected material list for the unit:

![IMG_5BCD87EA3B7C-1](https://user-images.githubusercontent.com/67970402/162189816-b79b2e90-739f-4937-beb6-7c494b2c1c55.jpeg)

It happened after I had configured the bulk ceramic type, if that makes a difference (to bulk).

**Comment by luizaogs** [comment]
If I click ok I get to the list normally.

**Comment by luizaogs** [comment]
(This also happens in both full and simple excavation.)

**Comment by urapadmin** [comment]
ooops :o)

**Comment by urapadmin** [comment]
or as we say Upsalla.

**Comment by luizaogs** [comment]
I'm going to start saying that!

**Comment by lbestock** [comment]
I wonder how the Swedes would feel about it?

**Comment by luizaogs** [comment]
Now I'm of course researching German ways to say oops and apparently Hoppsala and Hopps are also a thing? Hopps is pretty good.

**Comment by urapadmin** [comment]
now where are the Portuguese Oopses?

**Comment by luizaogs** [comment]
Well this German on reddit gave me wrong information. Boo.

**Comment by urapadmin** [comment]
Perhaps somewhere in Germany somebody says Hops. It is a typical non-word that one can even personalize. 

opa? That's what we call our Grandpa. 

And those are the most ridiculous you can come up with in your language?

**Comment by urapadmin** [comment]
I'll try to go with ops for a while. But those words are particularly hard to control, they tend to rather slip out. Even in writing. Funny thing, language.

**Comment by luizaogs** [comment]
If ridiculous Brazilian expressions are what you are looking for I can write you a whole fat book. We are just conventional in our oops usage, I guess.

Here are three of my favorites. I'll let you guess what they mean: 

Tira o seu cavalinho da chuva = take your little horse out of the rain
Vai catar coquinho = go harvest little coconuts
Enfiar o pé na jaca = to stick one's foot in the jackfruit

You're welcome.

**Comment by mcornacchia25** [comment]
Just got this same message. The first time I did it I clicked ok and got a "Do you want to interrupt this script?" message as well. I clicked no and proceeded to the menu as usual. I tried it a couple times after that and got the "asdfasdafds" message every time, but not the script one.

**Comment by urapadmin** [comment]
to stick one's foot in the jackfruit = shit hits the fan
go harvest little coconuts = hm. We have something similar: Kleine Brötchen backen. (go bake small rolls) which means to go hang your head and be modest after you were pretty loud and string about something you were even more wrong about.
I have no idea why I would take my little horse out of the rain.

**Comment by urapadmin** [comment]
### recording 12.5.1 
- ridiculous message gone

**Comment by luizaogs** [comment]
The message is indeed gone.

**Comment by luizaogs** [comment]
As for the crazy expressions. 

Enfiar o pé na jaca is often used when someone gets really drunk, which is not a use very frequent in my life, but it can also mean that someone exaggerated/did something in excess. Vai catar coquinho is said when you want to tell someone to go to hell but in a gentle way (I say that a lot. All the time). And tirar o cavalinho da chuva ... well, is basically the equivalent of English's don't hold your breath.
