### ISSUE TITLE
amending file identifier cache can take long

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#1527]
perhaps too long if a project goes crazy with images. I worry that it screws the workstation preparation one day.
So:
- [x] give it a generous timeout
- [x] invent a configuration key that suppresses the whole step
- [-] look again into speeding it up

**Comment by urapadmin** [comment]
Kiosk Config "filemakerrecording"/"timeout_amend_file_identifier_cache" is now responsible for setting the timeout in seconds. If set to 0 the file identifier cache won't be amended at all and the whole step gets skipped. A warning will be the result in the log.

**Comment by luizaogs** [comment]
Hmm how do I test this? I feel like I should know where the kiosk config is but I do not.

**Comment by urapadmin** [comment]
Hello to West Virginia! No, no, you can't :o) And you should not really know. This is rather for me.

**Comment by urapadmin** [comment]
a pity you are not here. We could all have a nice crazy roll out party with cocktails and crazy bugs and all
🍸 🐞

**Comment by luizaogs** [comment]
a Providence flight left about 20 minutes ago and I was tempted :)

**Comment by lbestock** [comment]
We would so have got you an Uber (can't pick you up, not on first cocktail).
If another one goes before the Miami flight attendant arrives....

**Comment by luizaogs** [comment]
Ha. I’ll let you know.

**Comment by lbestock** [comment]
There's Billy Joel, and booze, and people who love you.

**Comment by luizaogs** [comment]
Ugh I want to be there!

**Comment by lbestock** [comment]
The people who love you (and the cat) are old and will not pull an all nighter. Man oh man I hope you make it to Chicago.

**Comment by luizaogs** [comment]
Good night :)

**Comment by urapadmin** [comment]
- [ ] documentation added [https://wiki.arch-kiosk.brown.edu/urapdev/doku.php?id=manuals:developer_manual:kiosk_configuration:the_filemakerrecording_section#filemakerrecording](https://wiki.arch-kiosk.brown.edu/urapdev/doku.php?id=manuals:developer_manual:kiosk_configuration:the_filemakerrecording_section#filemakerrecording)
