### ISSUE TITLE
bulk identifiers: a question

### ISSUE THREAD

**Issue by luizaogs** [arch-kiosk/arch-kiosk-office#1528]
This is a question, not a bug. But since I don't understand bulk numbering I want to ask because I don't know if it's an actual issue. The current PVD configuration in 12.5.1 is using bulk numbers for bulk CM. Fine. But should I always get the error below when trying to create two different bulk records in the same locus or unit? For different materials? I am getting it in loci, features, and survey units and I guess it is because all materials are currently getting an "O" as their identifier but since I didn't see a way to configure this in collected material types I wanted to make sure it was ok.

<img width="438" alt="Screen Shot 2022-04-07 at 6 34 38 PM" src="https://user-images.githubusercontent.com/67970402/162336046-dff9f346-c380-483e-87ef-c4a1dcaa3908.png">

**Comment by mcornacchia25** [comment]
I am getting the same exact problem. All but "ceramic - diag." seem to be labelled O and it won't let me create a second bulk. But I had one in the same locus before the naming change, and that seems to be fine with the first one created after the naming change.

**Comment by urapadmin** [comment]
ja, current configuration makes little sense on that front, sorry.
Here is how the mechanism works: The material you select is looked up in the configuration key "visibility/key_value_list_material_codes" there you find a list of key-value pairs. On the left side is the material as you select it from the list and on the right side of the = is the code to use for the number. Now I have not touched that configuration key so all materials fall back to the default, which is "O" (configured somewhere else, nevermind).

### 12.5.2
I have now inserted the latest list here that we just agreed on for USTP and things should make more sense now.

**Comment by luizaogs** [comment]
Ah. Yes. That is fine now.
