### ISSUE TITLE
qc: change of locus type results in wrong qc messages about former locus type details

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#1529]
Managed to get them to show up at least. I don't know if everything's working correctly, but they're at least visible once I switch to simple excavation. One small thing: LA-024 is type fill but the warning given for it both when you click on the red exclamation point and when you try to leave it says "Please select a material for a context of type architecture." Maybe it was previously architecture but then changed context type and the error didn't change?

_Originally posted by @mcornacchia25 in https://github.com/arch-kiosk/arch-kiosk-office/issues/1521#issuecomment-1092353267_

**Comment by urapadmin** [comment]
this is the old #1460. So far I have no real idea how to tackle it. I could delete the detail record once the type changes but I always liked the effect that an accidental change of locus type would not delete the old inputs immediately. 
So I am still not sure what to do here.

**Comment by urapadmin** [comment]
let's try to delete superfluous detail records right before quality control starts.

**Comment by urapadmin** [comment]
### kiosk 12.15
This is finicky and there is no 100% solution to it. This is how it should behave now:
- when changing the locus type back and forth without doing anything else (especially clicking on the details button and going to the locus type details) the information entered in the locus type detail form should prevail
- when leaving the form, clicking on a QC button or leaving / reentering the layout all detail records that are not synchronous with the locus type get deleted.
- after they are deleted QC rules work properly. So let's assume you forgot to enter a material in architecture. You would get a qc warning. Now you change to "burial" -> the qc warning does not go away. Now you click on the qc button -> the qc warning does go away.

In a real world scenario I think the little caveat with the delayed qc warning should not be an issue.

**Comment by urapadmin** [comment]
for the developer manual:
There is a new config key "locus_type_tables" under system which translates the "field set" setting for a locus type to the name of the detail table (and layout) that is required to delete the records.

**Comment by lbestock** [comment]
@mcornacchia25 I let you keep going on this one as it was yours!

**Comment by luizaogs** [comment]
Since Lutz asked us all to look at it I gave it a quick look, and I think it is all working.

**Comment by mcornacchia25** [comment]
Seems fixed to me

**Comment by urapadmin** [comment]
then let's close it,
