### ISSUE TITLE
USTP context sheet pdf and reporting definitions

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#1530]
This is about actually creating the pdf and accompanying definition files for the USTP context sheep reporting.

**Comment by urapadmin** [comment]
### kiosk 0.17.2 and 
- first version installed on ustp-test on 10.04. Can be looked at. Unfortunately there are so many gaps still in the spec and in the data that the reports look very meager. But at least one can see reporting happening at this stage.

**Comment by urapadmin** [comment]
### 11.IV.2021 ustp-test: new improved version of the report installed 
- I can give this to the testing project now

To test the report you simply go to the Hub, find the reporting port and the "context sheet" dock. Click on it and you find "run" to process the report (better us the "zip" checkbox") while download sends you the the file manager where you can download it.

**Comment by urapadmin** [comment]
first change:
once #1446 is implemented the context sheet report should use the new filename to refer to files. Only files with filenames should be referred to, I'd say. That allows USTP do actually define which images are listed for the government.

**Comment by urapadmin** [comment]
### kiosk 0.19
#1446, especially #1614 is implemented now and this here is the best way to test it:
- in a context sheet in USTP all photos of a context that do have a filename set in the file repository should be listed in "photography" with that filename.

**Comment by urapadmin** [comment]
- first test revealed that a photo that has no filename still leaves an empty line in the field "photography". That was not the plan.

**Comment by urapadmin** [comment]
### kiosk 0.20.1
- lists with photos that do not have a filename should not lead to an empty line. Such photos should just be missing. (photography field)

**Comment by lbestock** [comment]
This seems to be working by context with photo numbers. 

I am not sure I understand how to create a report of all contexts at once. I tried this year's contexts and it just came back with one context (1000), which was not what I expected.

**Comment by urapadmin** [comment]
I tried "this year's contexts" and got two: 1000 and 1001 and I looked and those are the two that had been created this year.

**Comment by urapadmin** [comment]
As of now too many of the "needs help" comments were unanswered, so I can't continue this, currently.

**Comment by urapadmin** [comment]
I have made a few minor improvements on this for S'Urachi that can be used equally for USTP.
