### ISSUE TITLE
hub: "there is no access to the actions panel of this workstation"

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#1534]
![image](https://user-images.githubusercontent.com/38838314/162724633-690d2e02-e892-4981-95bf-10408c271c17.png)

This is a pretty general error for a rather specific issue: My session expired. I see that a lot and it should be possible to give a better feedback to the user here.

**Comment by urapadmin** [comment]
### kiosk 0.20.1
Well, I am not entirely happy but it should do for the time being: 
- the new message now says something like "no access, presumably your session has timed out, try a fresh login.
- It allows that said fresh login with a link.

**Comment by luizaogs** [comment]
Ok yes, you were right. I did not realize that capitalization would make a difference.

**Comment by luizaogs** [comment]
One last thing which just caught my eye: when a new dock is being created and thus in the default port it is never the last in the default port. Not sure if that matters.

**Comment by luizaogs** [comment]
Oops. Comments meant for another ticket. Ignore those.

**Comment by luizaogs** [comment]
Works!
