### ISSUE TITLE
ustp: locus creation with free input?

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#1537]
I was very surprised, to find free input for locus creation here. How does that work in the field?

**Comment by lbestock** [comment]
I guess we have to do something about that, too, right? Or did we already?

**Comment by lbestock** [comment]
Wow it is confusing when you pose as me, my god. We don't have to do anything about this that you haven't already done. Free input for loci is always necessary when a project is doing legacy data entry, as they were. Now it's configured to range per device which I am pretty sure is indeed what we discussed with them.
