### ISSUE TITLE
pasu: context and finds report

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#1541]
that's the nightmare report. It follows the specification on the google drive:   
- \pasu\specs\pasu_contexts_finds_report_listing_spec and 

The definition file and the template excel file are in the pasu repository:   
[https://github.com/arch-kiosk/pasu/tree/main/kiosk/reporting/contexts_finds_report](https://github.com/arch-kiosk/pasu/tree/main/kiosk/reporting/contexts_finds_report)

### prerequisistes
if this issue depends on other issues that should be tracked, add a task list here:
- [ ] #1539

**Comment by urapadmin** [comment]
### 18.IV.2022 First version installed on Beset/pasu
- this first version has the area sheet and the ceramics sheet. The other two are presumably not even necessary -> Peter needs to tell us.
- Now we need some data on PASU to actually test this.

**Comment by urapadmin** [comment]
- [ ]make sure that only cm_type "bulk" is used in ceramic counts and sums

**Comment by urapadmin** [comment]
### 20.IV.2022 
- report updated

**Comment by lbestock** [comment]
On pasu-test with just a few data in there but enough to do a preliminary test, I was unable to run the report or download. My dialog could not be initialized, please try again was what I got on running the report. I got a full blown Kiosk is Unwell screen when I tried to download anyway.

**Comment by lbestock** [comment]
The basic unit report seems to work in PASU test now. Is this ready on PASU local? I have made more data to test it there.

**Comment by lbestock** [comment]
Now being tested with real data as input by Peter and Anna, in ticket #1680. So closing this.
