### ISSUE TITLE
move PASU third stage ceramic processing to registration?

### ISSUE THREAD

**Issue by lbestock** [arch-kiosk/arch-kiosk-office#1542]
The question arose as to where the third stage of ceramic processing should reside for PASU. This phase is the penultimate. 
(The workflow document is confusing on this front because it skips the in the field collection stage.)
Stage 1: collect in field and assign bulk # (which is not a number but a code)
Stage 2: spread out ceramics of a context, separate diagnostics and non-diagnostics, and count and weight information is gathered and entered for both bags.
Stage 3: diagnostic bag is reopened, separation into functional categories and component parts. Each sherd is numbered. Record made of how many of each category/part. Bagged by category/part.
Stage 4: Category/part bags are opened and individual sherds are described, drawn, and photographed.

Implications for recording:

- The first stage necessarily happens in CM, and the second, though it is in the sherd yard, should be recorded there, too. As at that time one is not digging, presumably the ordinary registration tab for CM is the way to do this.
- The third stage we have a special bit for in PASU (though it's not configured in the totally blank one up right now). This is currently done through the locus, but this is what I wonder if it should be rather a separate ceramics button on the registration tab. I will also say though that I don't think it's of vital importance. They will have to learn the steps of accessing the right part regardless. And the types of records made here are by locus, with the whole team doing a single locus together (But using one recording device.) So there is not a lot of back and forthing, and that probably means it's less important where it is.
- Stage four we have a whole special module for in PASU accessed through the ceramics processing in registration. 

If we move stage three to registration then naming it distinctly from stage four becomes a bit of an issue?

**Comment by urapadmin** [comment]
In fact I don't see an advantage of moving it INTO registration. It resides in the same tab on the start page under "ceramics" and why not leave it there?

**Comment by urapadmin** [comment]
we leave it where it is for now,
