### ISSUE TITLE
PASU: sum and count of ceramics must be summed up and updated in collected material

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#1544]
- the cm weight / count fields can be shown but not be edited in this case
- only for certain material types. In this case "ceramics-diag". "ceramics-nondiag" still has its weight and count being but in manually
- see also #1499

**Comment by urapadmin** [comment]
### recording 12.6
this only happens if:
- the collected material has the "ceramics" tab with the su ceramic preprocessing in it
- the configuration key "su_auto_cm_count_and_weight" under "modules" is set to "yup"
- the configuration keys "collected_material_show_quantity" and "collected_material_show_weight" under "visibility" are set to "yup"
- the configuration keys "hide_quantity_for_materials" and "hide_weight_for_materials" do not have the material in the list that activates the su ceramics preprocessing in collected material

Ja, that's crazy, I know. But there it is.

if all this is set correctly, then this is what happens:
- count and weight are read-only fields in collected material/basics and get updated automatically by the entries under "ceramics"
- count and weight are normal input fields for collected material that does not have the su ceramic preprocessing tab

**Comment by lbestock** [comment]
A note that came out in testing:
Currently this works as expected if no filter is applied in the ceramics tab of CM ceramics-diag. If there IS a filter then the count and weight on the basics tab report the results of the filter count, not the total for the bulk CM. Is there a way to separate that? It is good that when filtering in the ceramics tab the count and weight there reflect the filter - that's the point. But on the basics tab it should always be everything. Perhaps this could be accomplished by making any filter apply only as long as one is on the tab, and then disappear? If the filter stays applied I do also see a slight danger that one goes back to that tab and does not see that there is a filter. That's relatively minor, while the basics count and weight is not so much. I do note that the filter gets unapplied as soon as one creates a new line in the ceramics tab, which is good.

**Comment by urapadmin** [comment]
ja, that is a bug.
- [ ] collected material / su_ceramics_preprocessing: weight and quantity wrong when filter applied

**Comment by urapadmin** [comment]
### recording 12.8
- weight and count should be updated correctly even if a filter is active.

**Comment by luizaogs** [comment]
This is working now in terms of the count and weight remaining accurate in the basics tab for the total even if there is a filter applied. 

Laurel also mentioned above that it might be good to deactivate the filter when one leaves the tab and comes back I think, which is currently not the case. Not sure if that is still a relevant point, so not closing this yet and sending it back to you Lutz so you can see it.

**Comment by urapadmin** [comment]
I think it's fine now. The filter question can be discussed separately.
