### ISSUE TITLE
su ceramics preprocessing: pie chart to show proportions per context

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#1545]
_Originally posted by @urapadmin in https://github.com/arch-kiosk/arch-kiosk-office/issues/1499#issuecomment-1100422780_

**Comment by urapadmin** [comment]
@lbestock says:
>Pie chart issue: it is not super straightforward as to what the pie chart should show, in fact. I think best would be sherd count per functional category (so adding all the rims, bases, etc). I do not think different slices per component (rims and bases of cooking pots being separate, for instance) makes as much sense.

**Comment by urapadmin** [comment]
### recording 12.17
there is a button now in ceramics preprocessing that opens a pop-over with two pie charts

**Comment by luizaogs** [comment]
This looks great.
