### ISSUE TITLE
backup: invalid format string

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#1548]
something not right anymore with the filename:

`backup_filename_template: "urap_#a_#d#m#y-#h#m#s.dmp"`

Should work but throws a invalid format string error. When changing it to a simple urap_backup.dmp backup works.

**Comment by luizaogs** [comment]
Ok how do I test this? I tried backing up PASU to see but it didn't save in that format so I'm not sure.

**Comment by urapadmin** [comment]
what did it do? I should have thought that PASU still had the wrong backup filenamer template and so the backup would have created a kiosk_... .dmp file.

**Comment by luizaogs** [comment]
Just pasu_backup.dmp. No date or time.

**Comment by urapadmin** [comment]
ah. I see. I took the short cut for PASU.

**Comment by luizaogs** [comment]
Should I test it in PVD then?

**Comment by urapadmin** [comment]
no, I have reconfigured PASU so that it would create what was originally an error. Now kiosk... .dmp should be the result.

**Comment by luizaogs** [comment]
Ok interesting. It did save as such but it is not showing up under the options for restore?

**Comment by urapadmin** [comment]
Different issue .o)
I have now reconfigured PASU again and this time it should do what it's supposed to do: Create a pasu ... .dmp with date and time in it.

**Comment by urapadmin** [comment]
not that anybody of those archaeologists will ever hit the backup button...

**Comment by luizaogs** [comment]
Woo!
