### ISSUE TITLE
import failed: PASU import refused

### ISSUE THREAD

**Issue by lbestock** [arch-kiosk/arch-kiosk-office#1552]
Kiosk Hubbub: upload of PASU was fine, but import was refused

I entered a bunch of data into PASU to do an initial test of reporting, but I was not able to import my file. The error messages are shown below.

![image](https://user-images.githubusercontent.com/49291909/163741419-8ef4e2fc-6ecf-4a5b-924a-0bb8a3432217.png)

**Comment by lbestock** [comment]
Now this happened in USTP. Is it possible I failed to apply a patch?
![image](https://user-images.githubusercontent.com/49291909/164109490-258b9aa9-3845-45f3-98ef-83afc316b0c7.png)

**Comment by urapadmin** [comment]
no. All workstations need to be deleted and recreated, I am afraid. I am a bit surprised about PASU, though. I thought I did that with yours.

**Comment by urapadmin** [comment]
if you don't want to lose your PASU data, I can tweak it so that you can import if you want me to.

**Comment by lbestock** [comment]
It was only a little data to do the final test of image imports, which I mostly did anyway with the watch the other day. I can recreate it.

**Comment by lbestock** [comment]
Ah. No. I need you.
![image](https://user-images.githubusercontent.com/49291909/164112819-df7af5c3-5728-4524-ab20-3ef0b0fa61b5.png)

**Comment by urapadmin** [comment]
a conundrum :o)

**Comment by urapadmin** [comment]
oh, that's ustp

**Comment by urapadmin** [comment]
in PASU you are still "in the field"

**Comment by lbestock** [comment]
Argh you said PASU while I meant USTP - I can't keep them all straight! And PASU is on my iPad and USTP on my laptop, and the cat is doing gross things beside me. 

I should be in the field with PASU. I was doing a USTP ticket here, and had uploaded and then tried to import.

**Comment by lbestock** [comment]
There are no CAT emoji? That cannot be possible. No cats licking their bellies emoji I expected, but not no cats. Where are my glasses, these things are tiny.

**Comment by urapadmin** [comment]
🐱 🐈 😹 🐈‍ 😸 
what are you talking about?

**Comment by lbestock** [comment]
I really didn't see them. I did get these cheap reading glasses at CVS Sunday. Now I can read Schott's Miscellany in bed again, and perhaps it would help me see some cats designed for younger eyes.

**Comment by urapadmin** [comment]
don't wear CVS glasses, please 🤓

**Comment by lbestock** [comment]
I won't buy real ones until you are there to serve as better than any mirror. But I wanted to read Schott's Miscellany in bed.

**Comment by urapadmin** [comment]
you also need a opth...mologist
