### ISSUE TITLE
idgen_sample_type: new identification method

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#1555]
For pacha and pasu likewise: sample numbers like this:
{context-id}-smp{T}{000}
- With 000 being a running number that is unique within the context. It should not have leading zeroes, so the first would be SU22-G000-smp1 and the second SU22-G000-smp2
- with T being a sample type. Currently we do not have a sample type even as a field. 
- Much like with the material-based cm numbers the sample type should be a drop-down users would have to select BEFORE the sample is created. It will have a long and a code version - like cm again - and the code is used for the number. 

### prerequisites
- [x] #1556

**Comment by urapadmin** [comment]
what's the state here? Have we used this?

**Comment by urapadmin** [comment]
@lbestock: Does that ring a bell for you? I am not sure why this is still open and if it is in any way still relevant.

**Comment by lbestock** [comment]
It does ring a bell but I deem it unimportant. No one has asked about it again. And it is a relic of PACHA style worries about identifiers having all the info in them, whereas given the various methods of sorting in registration for instance it's not necessary at all. "Sample type" is itself vague - sort of a combination between material sampled and analysis to be performed on it. And both of those more precise things we do have. So I close this.
