### ISSUE TITLE
collected material sample: sample type

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#1556]
samples don't have any special fields, currently. 

The sample type would be the first. I suppose it is a valuelist. What values would it have, usually (sure, I will make it configurable)?

Any other fields for samples that we would need? Since I am on it ...

- [x] #1566

**Comment by lbestock** [comment]
It isn't quite "sample type" it is rather "analysis type", but that might be splitting hairs. The collected samples for C14 and Paleobotany look identical in the field for PACHA, it's just what is done with them later that differs. They get separate numbers from the beginning to make sure that they have enough and have earmarked enough for each purpose.

From a combination of PACHA, URAP, and PASU we know we need:

C14
OSL
Paleobotanical
Microbotanical
Micromorphological

I didn't lack anything else when recording fake samples.

**Comment by lbestock** [comment]
Liters. Peter wants to record how many liters of sample are taken.

**Comment by urapadmin** [comment]
since we are talking about a collected material, can we make that a general collected material field? Would it be volume?

**Comment by lbestock** [comment]
We can make volume a general CM type but it won't be relevant for non-samples. Eventually (not highest priority) it would be nice if it can be made visible or invisible by tab.

**Comment by urapadmin** [comment]
if it never will be relevant for anything but samples it makes no sense to make it a collected material attribute

**Comment by urapadmin** [comment]
analysis_type will also be a collected_material attribute even though it might only be used for samples.

**Comment by urapadmin** [comment]
### recording 12.8
configuration keys galore:
- visibility/show_analysis_method_for_cm_type controls for which cm types the new analysis method is shown. You want the cm type id here, so small_find, bulk or sample. As a gimmick you can use "*" here. That allows me to avoid the combination of "show_" and "hide_".
- visibility/show_volume_for_material controls for which cm material the new volume field is shown. As a gimmick you can use "*" here. That allows me to avoid the combination of "show_" and "hide_".
- valuelist_cm_analysis_types: The valuelist for the analysis types

**Comment by luizaogs** [comment]
I think you accidentally created a new configuration topic for "valuelist" instead of adding valuelists/valuelist_cm_analysis_types to "valuelists"?

<img width="1017" alt="Screen Shot 2022-04-19 at 2 38 43 PM" src="https://user-images.githubusercontent.com/67970402/164082574-b9e71221-890b-4e78-9c9d-9f665e243e78.png">

**Comment by luizaogs** [comment]
The rest is working, I believe.

**Comment by urapadmin** [comment]
ja, I did that. 🥟

**Comment by luizaogs** [comment]
Is that a...dumpling? Empanada?

**Comment by urapadmin** [comment]
shouldn't you be in 🇪🇬 ?

**Comment by luizaogs** [comment]
Next week :)

**Comment by urapadmin** [comment]
ja, there is no :dumb so I used a :dumpling

**Comment by luizaogs** [comment]
Ha!

**Comment by urapadmin** [comment]
(why is there no :pyramids emoji? That so lame) That's good. I can flood you with more tickets until then!

**Comment by luizaogs** [comment]
I so often need a pyramid emoji. I should write to Apple.

And yes, you are welcome to :)

**Comment by urapadmin** [comment]
no :pharao, no :sphinx, no :tut, no :pyramid, no :mummy even. What's wrong with them? We should start a petition.

**Comment by urapadmin** [comment]
but a 🍔 

The Emojipedia really needs some decolonizing.

**Comment by luizaogs** [comment]
Hey if you phrase it like that I bet our petition would get a lot of traction.

The closest I can get to archaeology is this guy: 🏺

**Comment by urapadmin** [comment]
What is it? 
I have a ⚰️
No :scarab? What movies are those emoji-inventing kids looking?

**Comment by urapadmin** [comment]
⚱️ 🏺 got it :o)

**Comment by luizaogs** [comment]
It's a boring Greek-ish vase! Bah. They should be watching The Mummy.

**Comment by urapadmin** [comment]
a shame.
(who dares closing this ticket?)

**Comment by luizaogs** [comment]
Oh is it ready to be closed? You know I love closing tickets.

**Comment by urapadmin** [comment]
Isn't it? 😕 Oh. because of that valuelist thingy... I'll make that a new ticket...  #1567 

no :trowel ? Honestly?

**Comment by luizaogs** [comment]
No nothing. They suck. 

Closed!

**Comment by urapadmin** [comment]
kinda harsh

**Comment by luizaogs** [comment]
Oh I've been annoyed with this for years :)

**Comment by urapadmin** [comment]
no, the closing ...

**Comment by luizaogs** [comment]
Sorry. I thought you were tired of my emoji rant.
