### ISSUE TITLE
identification method surachi ceramics: free input of the number part

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#1560]
that's what the special identification methods was for!

**Comment by urapadmin** [comment]
### recording 12.8
- I have made it something more general now: idgen_partial_input can be used for all kinds of combinations of a domain and a partial input now. 
- in PASU it is now responsible for generating the fragment number

**Comment by lbestock** [comment]
Hey now it even goes in order in the list! And adds the appropriate number of zeros itself!
