### ISSUE TITLE
"small find" should be "special find"

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#1561]
Do we already have a configuration key for that? I wonder.

**Comment by urapadmin** [comment]
### recording 12.7
This was by and large already done thanks to the name one chose in the collected material types for "small_find". 
But a few places still used "small find" hard-coded:
- delete locus with a small find record leads to a warning that there is a "small find" (should now be whatever name is chosen)
- the little record info button under "small find" details in collected material was still calling it a small finds record. That should not be the case anymore.

**Comment by luizaogs** [comment]
Ah, I had missed my Easter eggs (though I have more actual Easter eggs than I need in my kitchen at the moment). I think this is all fine -- the two instances you mention above are now customizable, and I've been puttering around looking for others and have not found them.

**Comment by PeterDeathBredon** [comment]
I have had only one (a real one). Dieting!

**Comment by luizaogs** [comment]
Easter is not the right time to diet, Lutz!

**Comment by PeterDeathBredon** [comment]
there really is no such time :)
