### ISSUE TITLE
collected material layout: material selection must be editable depending on cm_type

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#1562]
currently there is just a config key that makes it editable or not independent of the material type.
But in PASU we have "bulk" where the material must not get changed afterwards and "small find" where it must be editable.

**Comment by urapadmin** [comment]
### recording 12.9
- the new config key "visibility/lock_material_for_cm_types" does that. It takes a list (one value per line) of collected material type Ids (currently only small_find, bulk, sample). If a cm is of one of those types the material will be read-only.
- there is also a new way the old "allow_change_material_type" works now: If set to "nope" - which means the material type is not accessible - it will only lock the material if it actually has a value. In fact that should suffice for most use-cases where the material simply should not be changed after the original creation of the collected material IF the material is set during that creation, as is the case with material code numbering.

**Comment by luizaogs** [comment]
Hm wait, should this be 12.9 or 12.8? I didn't realize you had said 12.9 but the new key is already there and working in 12.8. But the patch of the old key (and the obsolete label) are not there, so not sure if you are planning to do that for 12.9?

**Comment by luizaogs** [comment]
Oh wait, I just realized that I wasn't the first person to download this update so I didn't get the patch. Guess I'll wait for a synchronization and check again.

**Comment by lbestock** [comment]
Right, @mcornacchia25 this is your first patch I think! Go for it.

**Comment by mcornacchia25** [comment]
I uploaded and synched, so I think everyone should be able to use it now, but I'll also give it a shot myself

**Comment by luizaogs** [comment]
Did you synchronize? It still shows as waiting for synchronization but I don't want to synchronize it and mess something up.

**Comment by mcornacchia25** [comment]
I thought I did, but I guess not. Doing it now.

**Comment by luizaogs** [comment]
First patch successful, Meghan :) This is all looking good to me.

**Comment by urapadmin** [comment]
sorry about the 12.9. Sometimes I confuse myself. 12.8. was correct.

**Comment by urapadmin** [comment]
sometimes I reread those tickets and am surprised that anybody can actually understand what I mean :o)

**Comment by urapadmin** [comment]
@arch-kiosk/test : This seems stuck. Can we close this?

**Comment by luizaogs** [comment]
I think so - it was fine when I looked at it.

**Comment by urapadmin** [comment]
🏺 Hello to Luxor! 🏺

**Comment by luizaogs** [comment]
Hello to Edfu, now!

**Comment by lbestock** [comment]
Wohoo! Now I hope you can get some sleep.
