### ISSUE TITLE
simple configuration: show a selection of configuration keys that are configured to be relevant in the field

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#1564]
configuration has a ton of items and is scary just because of its size. But during a field season there might be a few configuration values project managers want to change. We could mark those beforehand and invent a new user interface in filemaker that only shows those.

**Comment by lbestock** [comment]
I liked the idea when I first saw the ticket. But even after going through configuration for a project today I need to think through what would be useful and for this I do not have the head right now. Post-ARCE.

**Comment by lbestock** [comment]
An upcoming URAP season is in fact a good excuse to think this through (with an example, happy me). Which configuration keys might I want to change in the field, realistically? Inventing the method of marking them is separate than choosing which to mark. What about also a search function in configuration? I have often thought that might help me find what I am looking for, though it really might be more a test issue and marking for a season might make it irrelevant. The idea of a user interface being able to show only the marked ones sounds particularly helpful.

**Comment by urapadmin** [comment]
ja. The season didn't happen so no thinking happened, either. I'll implement this in a way that postpones the user feedback. I am good at that.

**Comment by urapadmin** [comment]
### recording 14.2
- config keys can be marked as "include in reduced configuration" or so in the meta settings of a config key
- the configuration has a menu button now. It includes all the buttons that were in the header before and a longish button to switch between advanced and reduced (or simple, don't remember) configuration.
- in advanced configuration the category selector is red. In reduced configuration it is white
- in advanced you have access to all config keys
- in reduced mode you only see the keys that are included in the reduced config according to the setting described above
- see also #2002

**Comment by luizaogs** [comment]
Um. Where are the meta settings of config keys?

**Comment by urapadmin** [comment]
oh, can you not see them as admin? That might mean they are only visible in developer mode. I'll look that up ...

**Comment by urapadmin** [comment]
you can't, indeed. And it does even make some sense since we don't want even admin users mess around here. You can either make yourself a developer (see #2002) or switch the test mode on.

**Comment by luizaogs** [comment]
Works and is pretty great.

**Comment by urapadmin** [comment]
- as normal admin (and test mode off) you should also have access to the meta settings. They are green in this case and only reveal the benign options I would allow normal field admins to access. It also makes it easier for others but me to decide on the set of reduced config keys.

**Comment by luizaogs** [comment]
Hm, did you release 14.3? I got the notification but both PVD and KHPP still have 14.2 for me.

**Comment by urapadmin** [comment]
I thought I did, yes.

**Comment by urapadmin** [comment]
I just used Bridge to get my own new workstation from khpp and it is on 14.3

**Comment by luizaogs** [comment]
Jesus, I am losing my mind. Sorry.

**Comment by urapadmin** [comment]
🍨

**Comment by luizaogs** [comment]
When I enter configuration I have general selected, but if I then click on the arrow in the selection box I get "no values defined", I assume because this is simple config and I haven't actually added anything to it yet? Maybe better to have nothing in the selection box to start with? 

<img width="1024" alt="Screenshot 2023-04-13 at 12 41 20 PM" src="https://user-images.githubusercontent.com/67970402/231841245-22fc82aa-f379-4b47-83b3-092b884ddc31.png">
<img width="1023" alt="Screenshot 2023-04-13 at 12 42 42 PM" src="https://user-images.githubusercontent.com/67970402/231841253-0163dec9-f469-4737-98a3-a1950d463a22.png">

**Comment by luizaogs** [comment]
The rest is good here.

**Comment by urapadmin** [comment]
That's FM. I can't really access that. Since it only occurs if NO config key is marked for reduced configuration I can live with it.
So I close this.

**Comment by luizaogs** [comment]
Oh wait, sorry. Adding keys from general and modules worked, but then I added a couple from i18n and I don't see them in simple. This did not happen this morning...

**Comment by luizaogs** [comment]
Hm. And then I added e-ink, and that isn't visible either, but now i18n has shown up.

**Comment by luizaogs** [comment]
And then I added labels and both labels and e-ink showed up. I'm not sure I see a pattern.

**Comment by urapadmin** [comment]
That sounds like a refresh issue. If you leave the config and go back, do things show up then? 
(BTW: If you try to put something from 'html' or 'system' to the reduced config, it won't show up. )

**Comment by luizaogs** [comment]
Yes, they're all there now. I will try starting over and seeing if leaving and coming back helps.

**Comment by urapadmin** [comment]
ja, clearly one of FMs famous refresh patterns. I can do something about it. Just leave this open for another round.

**Comment by luizaogs** [comment]
Ok!

**Comment by urapadmin** [comment]
### recording 14.4
- it should be better now

**Comment by luizaogs** [comment]
Yep.
