### ISSUE TITLE
config: valuelist_cm_analysis_types has created a category "valuelist"

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#1567]
I think you accidentally created a new configuration topic for "valuelist" instead of adding valuelists/valuelist_cm_analysis_types to "valuelists"?

<img width="1017" alt="Screen Shot 2022-04-19 at 2 38 43 PM" src="https://user-images.githubusercontent.com/67970402/164082574-b9e71221-890b-4e78-9c9d-9f665e243e78.png">

_Originally posted by @luizaogs in https://github.com/arch-kiosk/arch-kiosk-office/issues/1556#issuecomment-1103027910_

**Comment by urapadmin** [comment]
### recording 12.10
I have changed this but it needs to be patched before it will be fixed on all devices. So please synchronize.

**Comment by luizaogs** [comment]
Bless you for giving me an excuse to stop packing.

**Comment by luizaogs** [comment]
This is good now, and I synchronized so should be good for others.

**Comment by urapadmin** [comment]
oh you are packing. It'll be hard without you :o)

Am 23.04.2022 um 23:51 schrieb luizaogs - ***@***.***:

**Comment by luizaogs** [comment]
Well the iPad is being packed also :)

**Comment by urapadmin** [comment]
you‘ll have internet access in Egypt? Ha. I always think excavations are off grid and off civilization. Take care!

**Comment by luizaogs** [comment]
I should have internet access, and so should not necessarily disappear entirely. We shall see!
