### ISSUE TITLE
PASU: additional configuration and next steps

### ISSUE THREAD

**Issue by lbestock** [arch-kiosk/arch-kiosk-office#1568]
PASU is mostly configured. There are a few additional points, and then a few steps that will require configuration changes.

- Change small finds to special finds.
- [x] #1571
- [x] #1570

After that, we can give it to two sets of tests. Anna will do a fake process of digging her own new unit this summer to see if it is behaving as expected. And the ordinary testing team can keep working on specific tickets as well as trying everything to break it.

Next we'll wipe out all the data, and we will reconfigure the ID methods to free input. 

Peter and Anna will both then input legacy data, and this in particular will be used to test the reporting. 

ID methods will be reset to as they are now, and lists will be created for the expected unit(s) for this season. And they will be good to go.

attend to first:
- [x]  #1651 
- [x] #1644

**Comment by lbestock** [comment]
We also confirmed that registration will not be configured currently but rather in the field. They will be doing registration somewhat differently in the field. @aes1884 and Jeremy will walk through together how he will work and how the system might support that, and will then make it do so. She has promised to document the process of arriving at registration configuration so that it can serve as a users manual for others in the same position later.

**Comment by urapadmin** [comment]
> * Change small finds to special finds.

this is done by changing the "name" attribute of the collected material with the id "small_find". The id has to stay "small_find" but it never shows.

**Comment by urapadmin** [comment]
> We also confirmed that registration will not be configured currently but rather in the field. They will be doing registration somewhat differently in the field. @aes1884 and Jeremy will walk through together how he will work and how the system might support that, and will then make it do so. She has promised to document the process of arriving at registration configuration so that it can serve as a users manual for others in the same position later.

registration cannot be in good shape, honestly. The change from small find being a check box to small finds being a type alone should render it more or less useless. Honestly, I did not really expect them to use it.

**Comment by urapadmin** [comment]
except for registration these things should be okay now.

**Comment by lbestock** [comment]
Both Kiosk and the recording are not in the same version for the PASU test and PASU proper. When #1644 is taken care of I think this is ready to go to @Petervdom and @aes1884 for legacy data input. This ticket should not be closed; the resetting of ID methods for new field input has to happen after legacy data are input and used to test reporting. Any bugs or hiccups encountered in inputting data should be their own tickets.

**Comment by urapadmin** [comment]
PASU Kiosk is updated and good to go, I think.

**Comment by urapadmin** [comment]
- [ ] reset free input to sequential input whichever that was.

**Comment by lbestock** [comment]
Configuration things I'm catching in PASU.

- [ ] Locus numbers should be sequential per unit starting with 000, not reliant on a parition.

**Comment by urapadmin** [comment]
> [ ] Set default for image import to have no extensions, if that is possible and easy.

this is stored by user, too. So in the case of your own user the system default would not be used. Apart from that: It is possible,
