### ISSUE TITLE
unit: auto-fill of the word for "context"

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#1570]
> Make it so that a new unit does not auto-fill the word for context. Currently one really has to remember to change it from "context" to "Strat. Unit" even though Strat. Unit is the only word in the value list for that.

I guess the right thing to do here is to prefill the term fields with the right values, should there be any.

**Comment by urapadmin** [comment]
-  "term for unit" I fetch the first value of the value list "valuelist_locus_terms" and apply it. If there is more than one value in the list I leave the field blank.
-  "term for area": I use the first value I can find in the value list "valuelist_unit_terms" and use that unless there are more than one

**Comment by urapadmin** [comment]
@lbestock
- changed configuration for PASU to "Strat.Unit" (Yes, I got rid of that whitespace in the value list, too).

**Comment by luizaogs** [comment]
This is working in general but not sure if it is meant to be tested for PASU specifically so not closing it.

**Comment by lbestock** [comment]
@urapadmin 
Did you upload and synchronize those changes? Because I just prepared and downloaded and they aren't in PASU.

**Comment by lbestock** [comment]
But no matter. I did it again and it survived a syncrhonization (and I removed the white space again for you, too).
