### ISSUE TITLE
unit creation: Insist on a value in "term for unit" and "term for locus"

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#1572]
Currently one can erase those fields and leave. But the result makes no sense.

**Comment by urapadmin** [comment]
- changed configuration for PASU to "Strat.Unit" (Yes, I got rid of that whitespace in the value list, too).

**Comment by luizaogs** [comment]
These are drop-downs, no? Or am I looking at the wrong thing?

**Comment by urapadmin** [comment]
they are and it isn‘t easy to delete the contents in filemaker. But it is possible: open dropdown, ESC to close it, DEL to delete the contents.

**Comment by luizaogs** [comment]
Oh wild. Yes, ok, you got it.
