### ISSUE TITLE
'area' label on first screen

### ISSUE THREAD

**Issue by aes1884** [arch-kiosk/arch-kiosk-office#1574]
Is this meant to say 'Sector / Area' (see photo). I think it should be just 'area'.
<img width="757" alt="image" src="https://user-images.githubusercontent.com/68443221/164468403-4bb78bf7-32d7-402f-a75b-48e0e69ca740.png">

**Comment by urapadmin** [comment]
I have changed this in the configuration

**Comment by luizaogs** [comment]
I just downloaded the new database and it does only say "area" now.
