### ISSUE TITLE
Strat Unit observations: can't record soil particle sorting

### ISSUE THREAD

**Issue by aes1884** [arch-kiosk/arch-kiosk-office#1575]
In describing a new test Stratigraphic Unit (SU22-A001), I attempted to choose one of the soil particle sorting options, or write in the box, or in some way indicate the degree of sorting, but cannot. Nothing happens when I click in the box.

**Comment by luizaogs** [comment]
Weird, this worked for me. I think this is what it should look like, Anna: 

<img width="998" alt="Screen Shot 2022-04-21 at 10 55 42 AM" src="https://user-images.githubusercontent.com/67970402/164501625-6ecef5df-42d8-46c1-b238-d3376ef0ff04.png">

**Comment by aes1884** [comment]
That's odd. This is what I'm getting, no green box appears when I click. 
<img width="753" alt="image" src="https://user-images.githubusercontent.com/68443221/164550256-eac3620f-de9e-48bb-8b02-c7ff94c4751d.png">
I'm working on a PC laptop, rather than an iPad - could that be the difference?

**Comment by luizaogs** [comment]
Hmm this was on my Mac so I’m not sure.

**Comment by urapadmin** [comment]
Windows should work - I am developing on Windows. What is your FileMaker version, Anna? Are you using the most recent version?

**Comment by urapadmin** [comment]
It does take two clicks, though. But I suspect you tried that.

**Comment by urapadmin** [comment]
@aes1884: What is the state here?

**Comment by aes1884** [comment]
I'm running v12.9 of the database on Filemaker Pro 19.2.2. I just uploaded and redownloaded today in case that was the problem, and it's still not working.

**Comment by urapadmin** [comment]
this is really strange. Can you use the search button on the start page and click on a search result in there?

Are you on Windows 12? Do you have Chrome installed?

**Comment by urapadmin** [comment]
Current FileMaker Pro Version is 19.4.2. 
Can you please try installing the most recent version? That might solve the issue.

**Comment by aes1884** [comment]
Installing Filemaker Pro 19.4.2 solved the problem

**Comment by urapadmin** [comment]
@arch-kiosk/test: Note that we need FM 19.4 now.
