### ISSUE TITLE
inventory headings cut off

### ISSUE THREAD

**Issue by luizaogs** [arch-kiosk/arch-kiosk-office#1576]
Very minor, but some of the headings in inventory are cut off. This is PASU, 12.9.

<img width="1022" alt="Screen Shot 2022-04-21 at 10 38 43 AM" src="https://user-images.githubusercontent.com/67970402/164498329-2769f919-fddc-4d33-a976-08c360c1c2fe.png">

**Comment by urapadmin** [comment]
### recording 12.10
On what device does that happen? 
I have wiggled it a little bit but there is very little wiggle room. I hope it is better now.

**Comment by luizaogs** [comment]
This was my Mac, which is fine now. Also checked the iPad, also fine.
