### ISSUE TITLE
help buttons on interpretation tab need some help

### ISSUE THREAD

**Issue by luizaogs** [arch-kiosk/arch-kiosk-office#1577]
Again, minor, but perhaps in need of updating before the field season. The interpretation text box says to click on the help button to learn what to type in interpretation but there is no help button for interpretation there currently. So I guess either take that out if the help button is unnecessary for the PASU team, or add the help button if keeping the text in the text box? 

Also, the tags help button needs to actually include information on how to use tags if it is being kept for the season.

<img width="1023" alt="Screen Shot 2022-04-21 at 11 00 50 AM" src="https://user-images.githubusercontent.com/67970402/164502537-00782578-a08a-4295-a638-04155f947227.png">

<img width="607" alt="Screen Shot 2022-04-21 at 11 01 00 AM" src="https://user-images.githubusercontent.com/67970402/164502551-28c948f3-1ffe-4178-be78-0322051c6992.png">

**Comment by urapadmin** [comment]
this has to be done in the respective projects:
- PASU
- PACHA
- USTP

It is all just configuration

**Comment by urapadmin** [comment]
khpp might want help here, too

**Comment by urapadmin** [comment]
I close this
