### ISSUE TITLE
failure in creating feature (no collected material id method?)

### ISSUE THREAD

**Issue by luizaogs** [arch-kiosk/arch-kiosk-office#1580]
I think this is a bug? PASU, 12.9.

I tried creating a feature in a survey unit (not sure if they even need survey units, but whatever) and got the following error, which seems to pertain to collected material and not feature creation itself? Also there IS a configuration for CM found in feature units in the collected material types, but I don't know if that differs from CM in features themselves? 

Confusing myself so will stop rambling. Here is a screenshot.

<img width="1026" alt="Screen Shot 2022-04-21 at 11 45 51 AM" src="https://user-images.githubusercontent.com/67970402/164510607-9c48746a-4ef2-4667-9bed-f0699a8cc421.png">

**Comment by urapadmin** [comment]
I suspect nobody thought about features, yet. s'urachi does not seem to record feature unit.
@lbestock, @aes1884?

**Comment by aes1884** [comment]
We're not surveying, so this seems like a non-issue for us at least

**Comment by urapadmin** [comment]
This is simply not configured for PASU. 

In which case we should remove "pedestrian survey" from the config key "valuelist_unit_types" which is under "system" because it is such a dangerous one.

Will you record features?

**Comment by urapadmin** [comment]
see #1602: This is a bug

**Comment by urapadmin** [comment]
closed because of duplicate. See #1602
