### ISSUE TITLE
incomplete sample identifiers in image gallery

### ISSUE THREAD

**Issue by luizaogs** [arch-kiosk/arch-kiosk-office#1581]
I don't know if you want the whole CM identifiers in there in the first place, but the whole identifier is there for special finds and bulk but not for samples so I thought I would point it out.

The first picture of the cat is fine, since that has the whole thing. The dinosaur mug picture is a sample (SU22-C200-sample0) so the sample part is missing. Image three, the Christmas tree, is a bulk so that's also fine.

<img width="1023" alt="Screen Shot 2022-04-21 at 11 49 43 AM" src="https://user-images.githubusercontent.com/67970402/164511670-55af8423-60a7-49a4-bd32-d05ccb5959de.png">

**Comment by urapadmin** [comment]
### recording 12.10
I suppose that is just yet another layout issue where filemaker cuts off text. 
I have changed the font from bold to normal here. There isn't more room on ipads here, I suspect, so I'd rather not touch the sizes.

**Comment by luizaogs** [comment]
This fits on both iPads and Macs now. But a question: did you switch the order of identifiers on purpose, or was that an undesired side effect? I'm also getting tags showing up here now, which I didn't before.

<img width="1028" alt="Screen Shot 2022-04-23 at 4 59 05 PM" src="https://user-images.githubusercontent.com/67970402/164947321-1eaea73c-97a6-4de8-8754-00e053b8beaa.png">

**Comment by urapadmin** [comment]
that must be coincidence. Tags are identifiers but added as such only by kiosk itself to the file-identifier-cache. So you see a slightly different result in the gallery after a synchronization than before when the file-identifier-cache had only been populated by filemaker itself. That's at least my guess (you should think I know, but ... ).

Looks okay to me

**Comment by urapadmin** [comment]
That cat is simply amazing.

**Comment by luizaogs** [comment]
Well if it looks ok to you, it is ok :)

I love that cat. But if you touch her belly you die.

**Comment by urapadmin** [comment]
a trap then :o) Quite luring.

**Comment by luizaogs** [comment]
She is quite the tease.
