### ISSUE TITLE
registration CM label

### ISSUE THREAD

**Issue by luizaogs** [arch-kiosk/arch-kiosk-office#1582]
This is PASU, 12.9.

Should it be bulk# in the header? Is that not confusing, since some are also samples and some are special finds?

<img width="1026" alt="Screen Shot 2022-04-21 at 12 19 04 PM" src="https://user-images.githubusercontent.com/67970402/164515813-063cd821-f51b-4282-aa2d-4f06d45a8b4b.png">

**Comment by urapadmin** [comment]
we have not really touched registration so far. This needs to change, indeed.

**Comment by urapadmin** [comment]
ha. I forgot. That is controlled by the configuration key: "labels/label_bulk_number". We should set it to "CM#" in PASU.

**Comment by luizaogs** [comment]
Done!

**Comment by urapadmin** [comment]
thanks :o)
