### ISSUE TITLE
unable to access preprocessing tab

### ISSUE THREAD

**Issue by luizaogs** [arch-kiosk/arch-kiosk-office#1583]
Well I just said this to you both in an email but now that I know what the tab is supposed to look like (from #1145) I know that I am definitely not seeing it anywhere. I assume it is because I am doing something incorrectly, but I've tried adding ceramic-diag as bulk, sample, and special finds and have gotten it to show up for none of those, so I do not know.

This is PASU, 12.9.

**Comment by urapadmin** [comment]
you are totally right. The issue was a configuration issue. I had changed the material code for "ceramics-diag" and forgot about the implications. It should work now.

**Comment by urapadmin** [comment]
### available now 22.IV. 18:25 GMT-4

**Comment by luizaogs** [comment]
It does.
