### ISSUE TITLE
image gallery heading cut off

### ISSUE THREAD

**Issue by aes1884** [arch-kiosk/arch-kiosk-office#1585]
Another minor issue, but the image gallery heading is cut off. The screen shot is from the ceramics analysis, but this happens across the board.
<img width="470" alt="image" src="https://user-images.githubusercontent.com/68443221/164568669-4eadd174-770b-4a35-bd2f-c428dd145800.png">

**Comment by urapadmin** [comment]
what operating system are you using? Windows? 
What Version? 

If it is Windows, do you use a scaled font? (right click on your desktop -> Display settings and then "Scale and layout":
![image](https://user-images.githubusercontent.com/38838314/164942692-43a4272d-83e5-4c8a-87e2-71d2f0f13704.png)

If you use something else than 100% FileMaker tends to mess up scaling and the screen looks kinda blurry in general.

**Comment by urapadmin** [comment]
### recording 12.10
- Since there was space, I have nonetheless extended the label so that it should fit.

**Comment by luizaogs** [comment]
Looks good now. This had also been an issue for me previously but again had never registered as one -- I don't think I've ever seen the full "search by search term / recording context" label!
