### ISSUE TITLE
collected material: ceramics preprocessing not showing up

### ISSUE THREAD

**Issue by aes1884** [arch-kiosk/arch-kiosk-office#1586]
I may be remembering incorrectly from our meeting on Monday, but the ceramics preprocessing form is supposed to be accessible from within a bulk diagnostic ceramics collected materials page, correct? If that's the case, it's not there. If it should be accessible from somewhere else, I cannot find it.

<img width="776" alt="image" src="https://user-images.githubusercontent.com/68443221/164571245-25a24b15-db17-48e3-b5b6-eb5c0532d16b.png">

**Comment by luizaogs** [comment]
Anna, I just randomly saw this and thought I would tell you that I had the same issue earlier (see #1583). It was a configuration problem that Lutz has since fixed, so if you synchronize your current database and download a new one it should be fixed.

**Comment by urapadmin** [comment]
yes, this should be fixed.

**Comment by aes1884** [comment]
Uploaded and redownloaded, and it's all working!
