### ISSUE TITLE
human-readable QR code label cut off

### ISSUE THREAD

**Issue by aes1884** [arch-kiosk/arch-kiosk-office#1587]
When generating QR codes for samples, the sample number in the human-readable portion is cut off. (This should probably be checked on the iPads though, as I'm working on a PC laptop, and that might be the issue/is also not what is going to be used as a photo board).
<img width="791" alt="image" src="https://user-images.githubusercontent.com/68443221/164572322-a9228926-219d-4ba0-8944-b8cb3fa890e4.png">

The same thing is happening for the QR codes generated for special finds.
<img width="794" alt="image" src="https://user-images.githubusercontent.com/68443221/164572606-58a1b4dc-e718-4bed-b01b-200d284d58c6.png">

**Comment by urapadmin** [comment]
well, what can I say. Those identifiers are too long. I will reduce the font-size and perhaps use two columns if I can find a way. And I will try to right-align it so that the first part rather than the last part gets cut off. But generally speaking this shows that we have to try to keep identifiers as short as possible.

**Comment by urapadmin** [comment]
more alarming here is that the qr-codes themselves are cut off. I doubt that those QR-codes would still be read properly.

**Comment by urapadmin** [comment]
### recording 12.10
- should be better now. Particularly the qr code should not be cut off! 
- If the identifiers still not fit, we can switch to the rotated label by setting the config key "QR_label_rotated" to "yup"

**Comment by luizaogs** [comment]
This is what it looks like for samples now (on both a Mac and an iPad):

<img width="1026" alt="Screen Shot 2022-04-23 at 5 22 40 PM" src="https://user-images.githubusercontent.com/67970402/164947946-7b555a7c-e879-4ebf-b4c9-ee5a07aa7576.png">

And special finds, again on both devices: 

<img width="1024" alt="Screen Shot 2022-04-23 at 5 23 49 PM" src="https://user-images.githubusercontent.com/67970402/164947956-71c384f8-851f-42eb-9678-52280079a65c.png">

So still not ideal? But the QR codes themselves are fine.

**Comment by luizaogs** [comment]
This is what the sample looks like rotated: 

<img width="1027" alt="Screen Shot 2022-04-23 at 5 25 21 PM" src="https://user-images.githubusercontent.com/67970402/164947986-219fbcc6-bf40-4e65-9bd5-c46f51d95fbf.png">

And special finds: 

<img width="1026" alt="Screen Shot 2022-04-23 at 5 25 58 PM" src="https://user-images.githubusercontent.com/67970402/164948004-e0ba7f79-8065-4d08-a255-9210634b1286.png">

**Comment by luizaogs** [comment]
Not sure if the latter is ok or if you want to tweak it further.

**Comment by urapadmin** [comment]
the qr codes still look cut off. But the rotated labels would work, I suppose. 

Those identifiers are simply not practical.

**Comment by urapadmin** [comment]
definitely needs further improvement.

**Comment by urapadmin** [comment]
on the other hand ... these are all screenshots of desktops. What we really need to know is how the ipads behave here. Testing with iPads is key here.

**Comment by luizaogs** [comment]
Oh I checked them all on both - they looked exactly the same. I just used desktop screenshots because that was easier.

**Comment by urapadmin** [comment]
does it scroll on your screen? I can't see a scroll bar. 
It looks quite different on my screen:
![image](https://user-images.githubusercontent.com/38838314/164976178-49c6f2b3-2ed9-4096-9f48-aa4d2a2a37cf.png)

**Comment by urapadmin** [comment]
(the close button is only visible to developers)

**Comment by luizaogs** [comment]
Wait, no, I lied. I was paying more attention to the labels than the QR codes, and those do look the same, but the QR codes are whole on the iPad: 

![IMG_0292](https://user-images.githubusercontent.com/67970402/164976202-1c8f3047-6fda-469e-84d6-c63b33adceb1.PNG)

![IMG_0291](https://user-images.githubusercontent.com/67970402/164976209-35962309-bf02-4ac2-a9e9-7abde2bacb04.PNG)

**Comment by luizaogs** [comment]
You were right :) Sorry!

**Comment by urapadmin** [comment]
that is the important part. Okay. That's better.

**Comment by urapadmin** [comment]
Does the Mac have something like a screen scale setting? Something that scales fonts and icons up in order to make them legible on a screen that has ten bizzillion pixels per inch but is too small for it? Windows does have something like that and it screws things up regularly.

**Comment by urapadmin** [comment]
### recording 12.10.1
- I have wiggled and prodded the layout and changed the font for the vertical label (with the letters from top to bottom) to a monospace font. 
- projects with excessive identifiers must use the rotated label

**Comment by luizaogs** [comment]
> Does the Mac have something like a screen scale setting? Something that scales fonts and icons up in order to make them legible on a screen that has ten bizzillion pixels per inch but is too small for it? Windows does have something like that and it screws things up regularly.

There's this: 

<img width="662" alt="Screen Shot 2022-04-24 at 7 26 53 AM" src="https://user-images.githubusercontent.com/67970402/164976468-86166bdc-6726-41c1-ab91-ca9fc44e717a.png">

**Comment by urapadmin** [comment]
well, if that's the same you would be on a non-scaled setting. Hmpf. I guess I just hope that 12.10.1 makes things a bit better. Otherwise I need to follow this up back in Providence. The priority is on the ipads, anyways.

When are you leaving?

**Comment by luizaogs** [comment]
I have a stupidly early flight to New York tomorrow morning and then leave for Cairo on Tuesday, because my Monday flight was cancelled. Woohoo.

**Comment by urapadmin** [comment]
the excavation business mostly sucks from traveling in my humble opinion. If I could just be beamed up to Uronarti (and back) I would give it another try, perhaps.

**Comment by luizaogs** [comment]
Ok, so Mac: 

<img width="1023" alt="Screen Shot 2022-04-24 at 7 54 04 AM" src="https://user-images.githubusercontent.com/67970402/164977572-e04dd1c9-0845-4a09-be80-d4e22e3c2a6b.png">

<img width="1027" alt="Screen Shot 2022-04-24 at 7 54 45 AM" src="https://user-images.githubusercontent.com/67970402/164977575-ee5763c3-0e7b-4a59-be47-9c319fe1118b.png">

iPad: 

![IMG_0294](https://user-images.githubusercontent.com/67970402/164977696-36d19cdc-0933-4250-b648-b38b273bea9d.PNG)

![IMG_0293](https://user-images.githubusercontent.com/67970402/164977699-95c6b3f8-7ae2-4f89-8180-28044913fba9.PNG)

**Comment by luizaogs** [comment]
So looks ok, I think? If so I can configure PASU to use the rotated labels.

**Comment by luizaogs** [comment]
> the excavation business mostly sucks from traveling in my humble opinion. If I could just be beamed up to Uronarti (and back) I would give it another try, perhaps.

I would LOVE to be beamed up right now. Ugh.

**Comment by urapadmin** [comment]
if only one weren't disassembled so thoroughly in that process.
yes, I think we can close this for now

**Comment by luizaogs** [comment]
Good, and PASU is now configured for this.
