### ISSUE TITLE
pasu: Area label disappears in "collected material by area" tab

### ISSUE THREAD

**Issue by mcornacchia25** [arch-kiosk/arch-kiosk-office#1589]
In the "collected material by area" tab, the area label disappears. This is what it looks like in the area tab for example:
![IMG_D7FB88355684-1](https://user-images.githubusercontent.com/96021337/164816232-6fd7c354-381f-431e-b47f-538e601a98f2.jpeg)

As opposed to on the "collected material by area" tab:
![IMG_64A126B4DA4E-1](https://user-images.githubusercontent.com/96021337/164816297-e4415e47-e8bd-4160-a2fc-73305fde8053.jpeg)

**Comment by urapadmin** [comment]
### recording 12.10
- fixed

**Comment by luizaogs** [comment]
This is fixed.
