### ISSUE TITLE
pasu: No matches found window when clicking tag category field

### ISSUE THREAD

**Issue by mcornacchia25** [arch-kiosk/arch-kiosk-office#1590]
I tried to create a tag from the interpretation menu of a Strat.Unit. When I clicked the category field, this weird menu popped up that I haven't seen before. I'm testing on the purple iPad. Here is what it looked like:

![IMG_CFF0189805C5-1](https://user-images.githubusercontent.com/96021337/164817096-98d28f42-613e-483a-beaa-5a12da4d01c8.jpeg)

I was still able to type in a category that applied itself, but I think the menu popping up in this situation would be confusing. However, when I created another tag, that menu changed to display the category that I created, and it behaved as I expected when I clicked on that category by applying that category to the tag. Here is the new menu:
![IMG_3BDBC43B632C-1](https://user-images.githubusercontent.com/96021337/164817496-5e4c2a65-377c-470e-8bac-152f4dfaeb91.jpeg)

I don't know if that's a menu you can change (or if it's worth it before we just abandon Filemaker), but I figured I'd point it out.

**Comment by urapadmin** [comment]
this is by design. The selection reflects what categories are already there and auto-expands when new ones are typed in.
In the beginning that looks confusing but I can't keep filemaker from opening an empty selection.
