### ISSUE TITLE
collected material: new field number of bags

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#1592]
a field for collected material / bulk but hardly for samples and small finds, I suppose. 
So I will bind it's visibility on the cm_type. For URAP no type would make it visible.

- [x] #1594

**Comment by urapadmin** [comment]
config key **show_cm_number_of_bags**: list all cm-type Id's for which the number of bags should be visible. "*" makes it visible for all.

**Comment by urapadmin** [comment]
### kiosk 0.18.3 / recording 12.10
- config key **show_cm_number_of_bags**: list all cm-type Id's for which the number of bags should be visible. "*" makes it visible for all.
- don't forget to test if it synchronizes

**Comment by luizaogs** [comment]
Works, including synchronization.
