### ISSUE TITLE
collected material: coordinates

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#1593]
a coordinate with three fields: x,y,z is wanted here. What format does the data in those fields have?
I suspect we are talking about simple 3D Coordinates here with floating point numbers.

**Comment by urapadmin** [comment]
### kiosk 0.18.3
- added to dataset definition, so synchronization should work for these new fields.

### recording 12.10
- added to collected material. Shown dependent on the config key **show_cm_coordinates**. Add all cm-type Ids in that list or "*" for all to show the fields.

**Comment by luizaogs** [comment]
Works, including synchronization.

But is the x / y / z label enough of a label? (A genuine question, not meant to imply that I think it does not.)

**Comment by urapadmin** [comment]
I don‘t know :) I got no precise instructions. And you know, space ….

**Comment by urapadmin** [comment]
@lbestock agrees. I don't, really. What else but a coordinate would x,y,z be? I'll try to cram the term in somewhere but it won't get prettier.

**Comment by urapadmin** [comment]
### recording 12.16.1
This looks different now

**Comment by luizaogs** [comment]
It does.
