### ISSUE TITLE
Master Control not up still pops up like a bad penny

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#1595]
maddening. PASU is particularly prone to it and there I have even suppressed that particular check. That's new.
for reference see: #1009

**Comment by urapadmin** [comment]
see also #1443 That could have to do with it.

**Comment by luizaogs** [comment]
Should this go to "under observation"?

**Comment by luizaogs** [comment]
Is this suppressed on PVD too? Because I am seeing it there currently in 0.19, and since export works it seems to be one of the fake MCP warnings.

**Comment by urapadmin** [comment]
no, in PVD it is not suppressed and my latest attempt to make it more reliable has failed, apparently.

**Comment by urapadmin** [comment]
but now I got it in PASU again and there it is suppressed:
`'suppress_messages':` {'sys_msg_id_mcp_not_up': True},

Maddening.

**Comment by urapadmin** [comment]
I can't see the issue why suppressing the message shouldn't work. I added a logline in case an exception is thrown there to find out. But no new suppression mechanism on top of the already existing one.
