### ISSUE TITLE
idgen_partial_input: code fragments of early s'urachi 

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#1597]
idgen_partial_input is supposed to be universal and yet is still bound to su_ceramics_cm? Something went wrong.

![image](https://user-images.githubusercontent.com/38838314/164996289-7d1e19e2-2003-4865-b168-5b9639054f60.png)

- [x] #1608

**Comment by urapadmin** [comment]
### recording 12.10.2
- fixed

**Comment by urapadmin** [comment]
you are more international than I am so you would know :o)
How are you holding up in Efri? Or was it Efru? I can't get my Egyptian thingies straight. And don't you have dirty work to do, hm?

**Comment by luizaogs** [comment]
Edfu! I have lots of dirty work to do, but it is currently 40 degrees celsius or something so we cannot work after 1pm or so :)

**Comment by urapadmin** [comment]
funny team dynamics galore?

**Comment by urapadmin** [comment]
🍦 does somebody get you ice cream? 🍦

**Comment by urapadmin** [comment]
"Oha" is what you'd say if you dig your pit and all of a sudden you stare into this entrance to those unheard of ancient underground catacombs that lead you straight to all the stuff that will catch dust in a museum afterwards. Well, at least if your are British "Oha" is all you say. Bit of a euphemism in that case.

**Comment by luizaogs** [comment]
Something to aspire to.

**Comment by urapadmin** [comment]
Oha. that's a real bug. Not just configuration. I'll even have to think about it...

**Comment by urapadmin** [comment]
(I would be soooo miserable there)

**Comment by luizaogs** [comment]
You totally would. I love it.

**Comment by urapadmin** [comment]
### 28.IV. 11 am EST
a non issue. I thought and there was a way to solve it in the way of configuration.
Should work now

**Comment by luizaogs** [comment]
It does. Something like SU22-D300-001 would be fine, right?

**Comment by luizaogs** [comment]
Ha ha ha!
