### ISSUE TITLE
unit / locus: show bulk, small find, sample button only if identification method is assigned

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#1598]
if survey units don't have an identification method assigned for one of the three collected material types the button should be invisible.
This must be implemented in the collected material lists in survey units, feature units and locus layout

**Comment by urapadmin** [comment]
@lbestock: Is that reasonable? It would allow us to not have a "sample" or a "small find" button in survey units because there is always only bulk in survey units. I suppose particularly the sample button makes little sense in survey and feature units.

**Comment by urapadmin** [comment]
### recording 12.15.1
well, for what it's worth: 
- [ ] if an identification method is missing in a collected material type for a certain locus type / material type the button won't be visible. That way we can suppress "samples" in survey units or features.
- [ ] to delete an identification method from a collected material type each selector has a reset button now

**Comment by lbestock** [comment]
Ah, it was reasonable just lost in an unreasonable Dallas trip. And it works and is elegant - I really like the new CM handling.
