### ISSUE TITLE
pacha numbering: add hyphens

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#1603]
- [x] locus: {SITE}{UNIT}-{0000}
- [x] survey unit: {Site}S-{XXX}
- [x] bulk: {locus-id}-{M}
- [x] special finds: {locus-id}-SF{000}
- [x] samples: {locus-id}-smp{000}

**Comment by urapadmin** [comment]
### 27.04.2022 - 9:12 EST

**Comment by lbestock** [comment]
@lbestock test after #1607 done.
