### ISSUE TITLE
identifier groups: That is not the best UI, improve it.

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#1604]
a) it should be possible to add/select an identifier group and see all the ranges in a list below
b) move it to "registrar", it sits a bit oddly in administration.

**Comment by urapadmin** [comment]
### recording 12.12
First I have moved the button to registrar.

**Comment by lbestock** [comment]
Well and that puts paid to #1607! But that is part b) and as a) does not seem attended to yet I leave this open.

**Comment by urapadmin** [comment]
### recording 12.13
- I think it is better now
