### ISSUE TITLE
collected material: improvements for filters

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#1605]
> > > ... but also that should be a drop-down menu if possible, since bulk, small find, and sample are set).
> > 
> > 
> > No, a dropdown does not work here because once it is a small find, the small find type is also part of the type displayed here and can be filtered as well. cm type and small find type can't share a list. But even with only cm: Peter has ceramic-diag and ceramic-non-diag or so and the text filter allows to filter by "ceramic" and get both types
> 
> Hmpf this tripped me up again. The "insert" menu still flies around uselessly, though it no longer prevents me from typing. But I tried to filter by small finds and it really took me four tries to get it. First I capitalized it. Then I hit return for enter, which not only doesn't enter, it gives another line which then screws up the search. Then I said small finds, but it is small find.

You are not using it the way it is meant to be used. No reason to type in small finds. type "find" or "small" or what not. Much quicker. 
- [x] I will try do do something about the insert menu. No idea why it is open at all.
- [x] I will make sure that capitalization makes not difference (I do recommend to switch off the really not smart capitalization feature of the iPad, though. I always think it does as much harm as it helps)
- [x] I can do something about the ENTER because that is also annoying on PCs (see below)
- [x] delete button to empty the filter (maybe even on the main layout)

I really don't see a reason to limit functionality artificially to what you can imagine right now (right now that you are also annoyed with how it works). Since we don't have any other way for analysis this is a simple but powerful feature if used correctly. I wanted to extend the cm type/material field in fact so that it contains a detail for bulk and samples as well. Bulk and samples just don't have any details, yet. Perhaps we could get rid of the "material" column entirely and use that instead.

_Originally posted by @urapadmin in https://github.com/arch-kiosk/arch-kiosk-office/issues/1520#issuecomment-1097668673_

**Comment by urapadmin** [comment]
### recording 12.13
all tasks done for 
- [ ] excavation
- [ ] simple excavation
- [ ] feature
- [ ] survey
- [ ] locus

**Comment by lbestock** [comment]
This is all so much better.
