### ISSUE TITLE
config: show su preprocessing but not the main ceramic analysis module under registrar

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#1606]
needed for PACHA.

**Comment by urapadmin** [comment]
### recording 12.13
visibility/hide_main_ceramic_analysis: If yup, the ceramics section under "registrar" vanishes.

**Comment by lbestock** [comment]
As currently configured the special ceramics module is gone, but so is the intermediate ceramics processing we wanted to leave on as a tab in the CM.

**Comment by urapadmin** [comment]
### 28.IV. 
configured now
