### ISSUE TITLE
PACHA: lost ability to make identifier lists

### ISSUE THREAD

**Issue by lbestock** [arch-kiosk/arch-kiosk-office#1607]
FM configuration

I expected to be able to create identifier lists for PACHA. 
The ID method for loci requires identifier lists per unit.
There is no button for identifier lists on the administration tab in PACHA now (and was not before I changed some configurations - I went back to an unsullied download to make sure I hadn't screwed that up).

As far as I can see this is not just a visibility setting, so I don't know how to turn it back on. It needs to be possible (and in fact configured with units and identifier lists) before Parker is given his first copy!

**Comment by lbestock** [comment]
It exists somewhere still hidden - I can make more loci properly in units that already have loci.

**Comment by urapadmin** [comment]
I have moved it to registrar/specialist in anticipation of #1604.  It isn't really placed well in administration. My rationale was that registrar level should be sufficient to make a new identifier group once the UI is a bit more user friendly.

**Comment by lbestock** [comment]
Makes perfect sense, I just hadn’t seen #1604 yet when I tried last night to make loci.
