### ISSUE TITLE
implement filename attribute: file repository edit dialog

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#1609]
- [x] new edit field to actually set and modify the filename
- [x] download needs to use the filename attribute

**Comment by urapadmin** [comment]
### kiosk 0.19
- test adding and editing a filename
- when using the download button the filename should be used if there is one otherwise the common way of creating a filename should still work

**Comment by luizaogs** [comment]
Works! This is cool.
