### ISSUE TITLE
implement filename attribute: filemaker recording

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#1612]
filenames are read-only because they are assigned in kiosk itself.

- [x] show the new filename in the gallery
- [x] show the new filename in the thumbnail view (if there is enough space) and pop-over view of every image (there are so many ...)

**Comment by luizaogs** [comment]
Oh oops you haven't done this yet, have you? But just to let you know that I got the following when trying to export a workstation after adding a file name, I expect because you haven't done this yet (sorry, I am tired and annoyed with this extremely loud mosque next to us): 

<img width="1481" alt="Screen Shot 2022-04-30 at 9 24 52 PM" src="https://user-images.githubusercontent.com/67970402/166119866-e631902f-487d-4c07-a782-2d108b360aea.png">

**Comment by urapadmin** [comment]
I have not :) It‘s next.

**Comment by urapadmin** [comment]
### recording 12.15
To test this there is something that helps in the gallery if you are in test mode (remember: check box in registrar and specialists):
![image](https://user-images.githubusercontent.com/38838314/166143568-c5185774-3aa0-44ed-ae79-10a995744803.png)
The red input field top right allows you to input a filename for an image - that is normally not allowed in the recording.

available now 
- [ ] in the gallery in both the list and the pop-over view
- [ ] full excavation - dayplans
- [ ] simple excavation - dayplains
- [ ] survey recording - photos
- [ ] feature recording - photos
- [ ] locus photos
- [ ] collected material photos
- [ ] site map
- [ ] site note photos
- [ ] su main ceramics analysis
- [ ] wc pottery
- [ ] tag analysis

**Comment by lbestock** [comment]
Outside of the gallery this doesn't allow me to add filenames, is that what you intended? It makes it a bit harder to test, but I can do it if this was intended. 

I can see the filenames outside the gallery in the pop-overs, and I can change one that exists, but I cannot make one if none is there.

**Comment by urapadmin** [comment]
- new filenames only in the gallery with the red input field. For testing purposes you don't need to create a ton of them.
- nowhere else in the recording should you be able to modify or create a filename.

**Comment by urapadmin** [comment]
I might have forgotten to set the filenames to read-only. Hmpf. In that case I would have forgotten it for ALL of them. Double hmpf. I will have to change all of them again. I hate filemaker and image containers.

**Comment by luizaogs** [comment]
Yeah I can totally modify existing file names elsewhere in the recording, too.

**Comment by urapadmin** [comment]
pity

**Comment by urapadmin** [comment]
### recording 12.15.2
- painful but done

**Comment by lbestock** [comment]
Now for testing. First I have to make in the gallery a filename for each category, and then to go to it in the recording and make sure it is present but not changeable.
- [x] in the gallery in both the list and the pop-over view
- [x] full excavation - dayplans - pop-over only
- [x] simple excavation - dayplains - pop-over only
- [x] survey recording - photos - pop-over only
- [x] feature recording - photos - pop-over only
- [x] locus photos
- [x] collected material photos
- [x] site map
- [x] site note photos pop-over only
- [x] su main ceramics analysis pop-over only
- [x] wc pottery - pop-over only
- [x] tag analysis - only pop-over

**Comment by lbestock** [comment]
In the gallery the filename is visible but read only in the list, is visible and writable in the "image" in the popup, and is not visible at all in the information of the popup. The first seems right to me, the middle right for the testing only scenario, and the latter maybe to think about - should it be visible there?

(I am able to make a duplicate filename in the gallery, but since this is really and truly just a test feature I'm going to tell you but suppose that is no problem.)

Isn't full excavation deprecated? I did change the configuration setting to check this, but am confused.

**Comment by lbestock** [comment]
Visible on the sitemap if one accesses it through the gear, but is not visible on the sitemap as displayed on the start page. This is what you intended?

**Comment by urapadmin** [comment]
> Visible on the sitemap if one accesses it through the gear, but is not visible on the sitemap as displayed on the start page. This is what you intended?

ja, I didn't find it very useful but rather in the way on the start page.

**Comment by urapadmin** [comment]
> In the gallery the filename is visible but read only in the list, is visible and writable in the "image" in the popup, and is not visible at all in the information of the popup. The first seems right to me, the middle right for the testing only scenario, and the latter maybe to think about - should it be visible there?
It does not even exist there. I don't see a reason.
> 
> (I am able to make a duplicate filename in the gallery, but since this is really and truly just a test feature I'm going to tell you but suppose that is no problem.)
Indeed, no problem.
> 
> Isn't full excavation deprecated? I did change the configuration setting to check this, but am confused.
I have not switched it off, yet. IT was more complicated than I thought and I am not sure which of the two I will drop. So for the time being we have to keep testing both.

**Comment by lbestock** [comment]
What the heck is WC pottery?

**Comment by urapadmin** [comment]
Warecode

**Comment by lbestock** [comment]
Argh that means changing configuration to get that up in PVD. OK.

**Comment by lbestock** [comment]
SU ceramics analysis doesn't have a popover. This is visible in the main immagini. But I think that is right.
