### ISSUE TITLE
hub: Sorting the ports isn't optimal

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#1613]
currently the whole thing is sorted by workstation-id. And the port of the workstation-id that comes first seems to come first.
I think we should sort by port and within the port by workstation-id.

but even that ... sometimes it makes the wrong port bubble up. Think of a way to control the order of the ports more directly.

**Comment by urapadmin** [comment]
### kiosk 0.20.1
docks are now sorted by port and dock-id controlled by the kiosk configuration key "ports" as documented here [https://wiki.arch-kiosk.brown.edu/urapdev/doku.php?id=manuals:developer_manual:kiosk_configuration:the_syncmanagerplugin_section](https://wiki.arch-kiosk.brown.edu/urapdev/doku.php?id=manuals:developer_manual:kiosk_configuration:the_syncmanagerplugin_section).

I have set it to ["default", "*", "reporting"], which means that:
- the default port should always be on top
- all others ports, whatever their name is, come afterwards in alphabetical order
- "reporting" must be last port (even outside of the alphabetical order)
- within the ports the docks must appear in alphabetical order of their dock id

**Comment by luizaogs** [comment]
I don't think the alphabetical order worked here? But it did in the default port in PVD so not sure what is up.

<img width="1478" alt="Screen Shot 2022-05-08 at 4 01 24 PM" src="https://user-images.githubusercontent.com/67970402/167299875-126e9451-e170-4b2f-8e3c-9ecf0cca8916.png">

**Comment by luizaogs** [comment]
Other than that, this seems good to me.

**Comment by urapadmin** [comment]
The "L" might come before the "e" because uppercase letters come first in the code map:
![image](https://user-images.githubusercontent.com/38838314/167300015-50dae396-7af8-4fdb-9688-1ab5ccd1672d.png)

**Comment by urapadmin** [comment]
I suggest you create something with a lowercase l in addition or so to see how that reacts.

**Comment by urapadmin** [comment]
@arch-kiosk/test: This was far from trivial to implement so I encourage everybody to attack it

**Comment by luizaogs** [comment]
Ok yes, you were right. I did not realize that capitalization would make a difference.

**Comment by luizaogs** [comment]
One last thing which just caught my eye: when a new dock is being created and thus in the default port it is never the last in the default port. Not sure if that matters.

**Comment by lbestock** [comment]
That it is capitalization in the ID not the name makes it particularly confusing since one sees the name much more prominently. Well, we should not have capital letters in the ID.

But the creation of the dock is alphabetical in terms of its location in the default group, too, spinning where it would end up if it were a default dock. I feel like this is fine. In the past I have often not seen a dock being created since it was always at the bottom, and sometimes I got confused and thought nothing was happening. This is much less likely now.

**Comment by urapadmin** [comment]
I'll thing about ignoring capitalization during sorting. But in general: Capitalization in ids will always lead to some confusion somewhere down the road. That's just one of life's wisdoms.

**Comment by lbestock** [comment]
Yes I thought about it more from the perspective of advice about conventions to chaotic archaeologists, not about something for kiosk to tackle.

**Comment by urapadmin** [comment]
### kiosk 0.25.1
- [ ] A port "Zussli" must now be after "file picking" because capital letters are interpreted as lowercase.

**Comment by lbestock** [comment]
What is this??
![image](https://user-images.githubusercontent.com/49291909/170843981-9909c58c-dc52-4516-8463-9abd5ca92e5e.png)

**Comment by lbestock** [comment]
And where can I find instructions on setting up a reporting dock?

**Comment by urapadmin** [comment]
that is sorting docks within a port

**Comment by urapadmin** [comment]
> And where can I find instructions on setting up a reporting dock?

nowhere. Because, well, without getting reporting files from me there is little use in it, anyways. But since this here is about testing sorting ports and nothing else you can always create a workstation that is in the recording group Zussli (or what have you)

**Comment by lbestock** [comment]
Ah I didn't know I could create a meaningful reporting port without a reporting dock. But just calling it reporting does indeed make it come last. I still don't get the Zussli sorting above, though.

**Comment by urapadmin** [comment]
this ticket was about sorting the ports correctly, which is the most important part. You may file a new ticket for docks.

**Comment by urapadmin** [comment]
can we close this?
