### ISSUE TITLE
file repository: show preview of .ai files

### ISSUE THREAD

**Issue by lbestock** [arch-kiosk/arch-kiosk-office#1615]
Adobe Illustrator files do not have previews in the file repository. It would be nice if they could.

As is the case with jpgs, pdfs, svgs, and heics (oh and the raw photos too) it would be helpful if .ai files could have a preview. This is a common type of file for archaeologists and now that we're thinking about how to manage drawings in kiosk with filenames it would be useful.

**Comment by urapadmin** [comment]
no chance. AI is a propriatary Adobe format.

**Comment by urapadmin** [comment]
as is psd

**Comment by lbestock** [comment]
Hmpf.
