### ISSUE TITLE
PASU: ceramic images not assigned properly to context

### ISSUE THREAD

**Issue by lbestock** [arch-kiosk/arch-kiosk-office#1617]
Ceramic images in the PASU sherd processing are not assigned properly to their context. The result is twofold: they have no "directly assigned to" context when seen in the File Repository after synchronization, and they are deleted from the recording system (though their image containers remain).

Images were created for sherds in the PASU ceramics module.

After upload and synchronization, those images were in the File Repository but had no context at all. They were neither directly assigned to the sherd number context, nor recognized as being part of the locus they were from. 

After prep and download, those images are now missing from the recording. But their image containers are still there. I am not sure if related, but If I click on an image container to insert an image (on my Mac) I have once been able to do so (using insert photo) but three times not, receiving rather this error:

![image](https://user-images.githubusercontent.com/49291909/166167902-0a14f9f8-f3c1-4dd0-9469-30c0db9d0bf1.png)

**Comment by urapadmin** [comment]
- Wow. This is all just kiosk configuration. I was able to configure the new su_ceramics as a context in and of itself. And now it is. 
- Good news: The images definitely made it to kiosk and are properly stored. So no synchronization issues here.

**Comment by urapadmin** [comment]
### PASU 02.V.2022 08:15 EST
this is fixed for PASU. It will be the same for PACHA and USTP (all su ceramic style pottery is affected) but for the time being I have only configured in for PASU to test.

**Comment by lbestock** [comment]
I have tested this in PASU through an upload and re-download cycle and everything is working as I expected it to. Though I didn't expect but did find that it restored context (correctly) to ceramic images that were made before you did the change. However I have not done a thing with file picking and your final comment above sounded like there are still lurking issues, so I will either let you close this or let you tell me what else to do to test it.

**Comment by urapadmin** [comment]
Context management in kiosk is magic. So magic that I myself have issues handling it. 
I am on the one thing to examine here but that's for insiders.
This here can be closed if it is okay. With the next kiosk upgrades the other projects that use su ceramics will be mended, too.
