### ISSUE TITLE
Filename: accept Umlaute

### ISSUE THREAD

**Issue by lbestock** [arch-kiosk/arch-kiosk-office#1619]
In attempting to get a 𝚫 into a filename, I also tried other things that cannot be directly typed on an American keyboard. I was not surprised to be denied ü and ë and ï but am told they should be accepted 👻

**Comment by urapadmin** [comment]
refused after some thinking. It would be politically incorrect to allow äöüÄÖÜß but not any of the other ten bizillion characters other languages are using. So keep it limited to IBM English. That's what computers understand.
