### ISSUE TITLE
file repository not finding image by description

### ISSUE THREAD

**Issue by luizaogs** [arch-kiosk/arch-kiosk-office#1623]
I think this is a problem but am very tired and can't remember. I am testing #1620 and just found the contextless image for a sherd in the file repository as expected. BUT I was unable to find it by searching for its description "yale library," which is in fact showing up in the image popup in the file repository? So I am not sure what is up and would have expected it to come up when I searched for it. (My internet is also crap here so if it works on your end that is probably why it is not working for me.)

Image is 

<img width="260" alt="Screen Shot 2022-05-03 at 5 07 15 PM" src="https://user-images.githubusercontent.com/67970402/166480728-64367c3b-0abd-45de-af5b-339333e91c61.png">

**Comment by urapadmin** [comment]
I cannot even find that image under its uid. What does it look like? We are talking about test, right? 
Even when sorting by "latest" I can't find it.

**Comment by luizaogs** [comment]
You know, I don't think spoiled Brazilians who grew up with AC are suited for manual labor in 45 degrees.

**Comment by luizaogs** [comment]
<img width="150" alt="Screen Shot 2022-05-03 at 6 00 41 PM" src="https://user-images.githubusercontent.com/67970402/166490642-b97bee3d-1fbf-44f7-8b67-5e7fdea698c2.png">

It's the first in the seventh row when sorting by latest, I suppose because of lot of the ones above do not have dates.

**Comment by urapadmin** [comment]
I mean as in freezing 🥶

**Comment by luizaogs** [comment]
Everywhere else, yes. Here I shiver because of the beginnings of a sun stroke (I am feeling better now).

**Comment by urapadmin** [comment]
got it (the image). Not happy about your beginnings of a sun stroke. Rest and get somebody to bloody get you some bloody ice cream.

**Comment by luizaogs** [comment]
I will survive, I am sure!

**Comment by urapadmin** [comment]
unharmed! 🍨

**Comment by urapadmin** [comment]
mere survival is entirely overrated, in my opinion.

**Comment by luizaogs** [comment]
I don’t disagree :)

**Comment by urapadmin** [comment]
okay, this is not critical and all only surfaces because we make a testing mess. The right question here is: "Why can it show a contextual description" although it has no context. And I have no clear answer to that one :o) 
But the search works a bit differently and cannot find context-related descriptions of images that are NOT context related. 

So the search is correct, the image view isn't. But all really as an effect of having tweaked it for testing purposes. 
We can close this.

**Comment by urapadmin** [comment]
But we should keep an eye on it in PASU - there the sherds should be context-bound and be searchable by their description.

Besides, I did not find it by its uid because I was to lazy to type the whole thing. But with the UID one has to. Once I did that it worked.

**Comment by luizaogs** [comment]
Ok so I looked at PASU and searching for description didn’t work either, for what it’s worth. I tried the “i miss pvd” image I had added for a sherd.

**Comment by urapadmin** [comment]
because I do mess up ...
That was yet another configuration errror which is fixed now and you can find your image (and now it also has a context)

**Comment by luizaogs** [comment]
Yes, and yes.
