### ISSUE TITLE
Hubbub: status of dock not reset after second upload

### ISSUE THREAD

**Issue by lbestock** [arch-kiosk/arch-kiosk-office#1624]
Hubbub dock status not updated after second upload

Tiny bug. I uploaded the wrong file, and tried to import it. My file was rejected, of course. I then went back and uploaded the correct file. But once that was uploaded the status of the dock did not change from the error I had with the bad import. So in order to import, which was my next step, I had to go in to "more options". I expected, after performing a step, that the dock would automatically be ready for the next step.

I'm in pasu-test, though I imagine that does not matter.

**Comment by urapadmin** [comment]
can't explain why this little error is harder to eliminate than you think. This is not going to happen before the summer projects. Too dangerous.

**Comment by urapadmin** [comment]
see #1696: A former error state prevails because the mcp process is still around. But the workstation has already moved on state-wise, so the warning is outdated.

**Comment by urapadmin** [comment]
I need a general command to reset a former job before a new job starts.

**Comment by urapadmin** [comment]
### Kiosk 1.2.8
- the error from a former import failure should vanish as soon as a new file got uploaded
