### ISSUE TITLE
PASU CM configuration: ceramic-diag in special finds gets intermediate processing

### ISSUE THREAD

**Issue by lbestock** [arch-kiosk/arch-kiosk-office#1625]
Special finds choice of material "ceramic-diag" pulls up the intermediate ceramic processing. This will presumably be an issue in other configurations, too, and I'm not sure yet if it will mess up reporting, but it wants attention on its own.

I made a special find in the current PASU configuration and, pretending I had found a lovely Roman lamp, I called it diagnostic ceramics. This is totally believable. But but virtue of being a special find it is by definition a single object - sherd counts of different types make no sense. That could be ignored (depending on its effect on reporting) but it has one real problem for recording my lamp: I can't get a weight in the special finds form because the weight for ceramic-diag is read-only.

What would be right is that the intermediate processing is only applied (and weight and count only read-only) when it is ceramic-diag AND bulk. For either special finds or samples ceramic-diag is just a material with no other consequences.

**Comment by urapadmin** [comment]
reminds me that I have to double check that I have renamed the significant material names in the report.

**Comment by urapadmin** [comment]
@lbestock, @aes1884:
The question that remains here is a pasu reporting question and I think we already answered that but I am not sure:
- If a special find is of type ceramic-diag as described above, should its weight and count be added in the finds/context report? Or is the example not a real scenario for PASU anyhow?

**Comment by aes1884** [comment]
My gut answer is to say no, the count and weight for the special find should not be added into the report. This is because I am fairly certain that it would have been counted/weighed in the bulk diag-ceramic and only later singled out for attention as a special find. That said, I am not 100% certain because I'm not entirely clear on the way Peter is intending to use the special find designation, as it has never been clearly defined to me before.

**Comment by lbestock** [comment]
I agree we should leave it as it is currently. In addition to Anna's reasoning, I add that the bulk weight and number counts from an analytical perspective are really about broken stuff and are rough indicators rather than relying on absolute precision for interpretation. And that the report is not a final tool for analysis but rather for reporting to the government, where super accuracy is also not needed.

The current configuration of bulk diagnostic ceramics and special finds in PASU corresponds to the above description and matches what I expected to see. The pie chart generation function is great. @aes1884 you should download a workstation from [PASU](https://pasu.arch-kiosk.brown.edu/syncmanager) and take a look at that.

As all is working as expected I'll close this ticket.
