### ISSUE TITLE
file import: include location data in exif data

### ISSUE THREAD

**Issue by lbestock** [arch-kiosk/arch-kiosk-office#1628]
Parker asked if files imported with information from exif data could be plotted on the basis of their location data and attached to a specific context on the basis of location. They cannot, currently, and whether or not that is desired in a future iteration is a question. We have not been thinking of mapping but rather of how to get data into the GIS, but we have also been thinking of what useful visualizations for analysis would look like in the future. 

I put this here just to ask: are the location data saved with the file when imported, even though they play no role in identifying it to kiosk? Parker says that when his team has done survey in the past they have used GPS enabled cameras and then plotted them on a map. If he downloaded a bunch of photos from the file repository that had been taken with a GPS enabled camera, would he be able to plot them just outside Kiosk?

**Comment by urapadmin** [comment]
yes. Kiosk stores the original file without any modifications.

**Comment by urapadmin** [comment]
if I understand this correctly this is not asking for a new feature in Kiosk, right?

**Comment by nparkervan** [comment]
Not from me! Laurel just noting it for discussion
