### ISSUE TITLE
kiosk hamburger and user menus overlap

### ISSUE THREAD

**Issue by luizaogs** [arch-kiosk/arch-kiosk-office#1634]
This is super minor and so maybe something you don't want to deal with, but since it has now tripped me up twice I mention it. In Kiosk (this is 0.21), if I open the hamburger menu and then for some reason the user menu, they end up overlapping and so if I then want to get back to the hamburger menu I need to close the other one (this happens both ways). It seems more intuitive to me to automatically close one if the other is being opened, or at least that is what I expected would happen.

<img width="359" alt="Screen Shot 2022-05-08 at 4 29 27 PM" src="https://user-images.githubusercontent.com/67970402/167301098-2dc2ab03-58e6-41e8-b357-83a35727b421.png">

**Comment by urapadmin** [comment]
ja, that's ooooold and trips me up at times, too.

**Comment by urapadmin** [comment]
### kiosk 1.2.9
should be less annoying now after all those years
