### ISSUE TITLE
file repository: fieldworker access limited to thumbnails

### ISSUE THREAD

**Issue by lbestock** [arch-kiosk/arch-kiosk-office#1635]
In the File Repository (currently PASU test 0.21) a field worker has access to the file repository but not to the files within it. When I click a thumbnail, I get just a greyed screen. Is this intentional? I expected to be able to see and download an image as a fieldworker and would like that to be possible. When writing trench reports at the end of the season it would be vital. If we want to be fancy we might limit a field worker's ability to delete things, but I would even want to be able to add description as a fieldworker and possibly additional contexts. And I would rather have full capabilities than none if it is either/or.

**Comment by urapadmin** [comment]
I simply only assigned the download and upload workstation privileges to filed workers. You may add others as you see fit yourself: [https://wiki.arch-kiosk.brown.edu/urapdev/doku.php?id=kiosk_privileges](https://wiki.arch-kiosk.brown.edu/urapdev/doku.php?id=kiosk_privileges). You would want the privileges for the file repository, so "download file" and "modify data"
