### ISSUE TITLE
delete unit / locus / collected material ONLY if there is no fragment in su ceramics

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#1636]
### recording 12.16.1
Prior to 12.16.1 it was possible to delete a collected material (or a locus or a unit) although a fragment in su ceramics (the one accessible on the start page under registrar) was connected to them.

This must not be the case anymore:

- [x] if a collected material has at least one fragment in su ceramics (the one under "registrar" user's will be warned about it and cannot delete the collected material until all fragments have been manually deleted.

---- 
- [x] if a locus refers to a cm that still refers to a fragment, the locus cannot be deleted by normal users
- [x] if a unit refers to such a locus, the unit cannot be deleted by normal users
- [x] Registrars will just be warned but can acknowledge the deletion, in which case the related fragments will be deleted, too.
- [x] The latter can be tested by creating a cm and a sherd for it, let's say a fragment LA-014C-001. Then delete the CM. And then create a CM under the same number, so LA-014C again. Go to su ceramics and try to create the same fragment CA-014C again. That should be possible.

**Comment by luizaogs** [comment]
Can normal users and registrars delete loci and units in the first place? I should definitely know this by now but do not see that option anywhere.

**Comment by luizaogs** [comment]
Hmm I deleted the sherds and then tried to delete the bulk diag in CM but am still getting the warning that there are sherds associated with it, even though there are not. Related to #1142 ?

**Comment by urapadmin** [comment]
what‘s the exact bulk and is it synched so that I can look at it?

**Comment by luizaogs** [comment]
It's the bulk shown in the warning above, SU22-A008A-DIAG. It is synched but the deletions are not synched, so if you delete the individual sherds and then try to delete the CM I assume you'll have the same issue.

**Comment by urapadmin** [comment]
Ah, right. I should really not read these things on my phone because it does not show me the images.
I'll try. I have a hunch that there might be old records dangling around from the time when they were not deleted with the bulk.

**Comment by urapadmin** [comment]
oh. "ceramic record" might even be a warecode pottery record that you can't see in the s'Urachi part. We need to clean up PVD at some point :o)

**Comment by luizaogs** [comment]
Oh woops, I should have mentioned that this is PASU test.

**Comment by urapadmin** [comment]
oh. okay. That's different.  So you are on pasu-test.arch-kiosk

**Comment by luizaogs** [comment]
Yes, I thought it made more sense to test this there.

**Comment by luizaogs** [comment]
Yes, I got a patch so had to synchronize it.

**Comment by urapadmin** [comment]
okay, so "ceramic record" refers to the ceramic preprocessing records in the "ceramic" tab under bulk

**Comment by urapadmin** [comment]
now that I have deleted them I don't get that warning anymore. and once I have also deleted the sherds in the ceramic analysis module I can delete the whole cm.

**Comment by urapadmin** [comment]
Am I missing something?

**Comment by urapadmin** [comment]
how to delete a unit:
![image](https://user-images.githubusercontent.com/38838314/168291967-5d60ca7c-3610-4836-9788-7ff822eab9fb.png)
The little red trash can appears for registrars

Hidden in the menu is the trash can for loci:
![image](https://user-images.githubusercontent.com/38838314/168292127-4c745286-75e4-4c99-ac3a-99d230839030.png)
That one is also accessible for registrars.

User's manual, I'd say.

**Comment by luizaogs** [comment]
Oh. So I need to delete everything in preprocessing and ceramics. Ok, that worked.

**Comment by urapadmin** [comment]
yes, that is correct. We have a bit of a muddle with the two different "ceramics".

**Comment by luizaogs** [comment]
I'm not seeing any delete buttons as a registrar, not sure why: 

<img width="1014" alt="Screen Shot 2022-05-13 at 3 26 40 PM" src="https://user-images.githubusercontent.com/67970402/168293918-9c30b12c-fe9f-4589-b113-ea0432ce71a3.png">

**Comment by urapadmin** [comment]
dumb question: You are marked a registrar in PASU?

**Comment by luizaogs** [comment]
Yes.

**Comment by urapadmin** [comment]
wow. Now I got it. It's me. The whole problem is being me (not only naturally so). When I am logged in as developer to filemaker (I I always do that) I am automatically admin. So in fact this is only available to the admin, currently. 
@lbestock, @luizaogs: Question is, do we want it to be available to registrars? Deleting a whole unit with all the related records is a big deal.

**Comment by lbestock** [comment]
No! We do not want registrars to be able to delete units with records. The potential for catastrophe if someone doesn’t really understand things is much too high.

**Comment by urapadmin** [comment]
This is also about loci. What about loci?

Am 13.05.2022 um 21:30 schrieb lbestock - ***@***.***:

**Comment by lbestock** [comment]
Loci I would leave deletable by registrars. I can imagine a situation where it would be helpful and cannot immediately come up with one where it would be accidentally catastrophic, so the opposite of units. But with a so strong warning that deleting it on the device will delete it from the database.

**Comment by lbestock** [comment]
Hmpf this is in conflict with #1142 where it seemed that it should be possible to delete a CM with fragments: https://github.com/arch-kiosk/arch-kiosk-office/issues/1142#issuecomment-1108916013

But this here, #1636, is what I expect and want so I would say close that one.

**Comment by urapadmin** [comment]
left to do: 
- [ ] registrars should be able to delete loci after being questioned
- [ ] admins should be able to delete units after being questioned

**Comment by urapadmin** [comment]
### recording 12.17
- this should be limited to the right privileges now

**Comment by luizaogs** [comment]
Hm nope. As a registrar I can delete a unit now, and I don't even get a warning. It just goes poof.

The rest seems ok.

**Comment by urapadmin** [comment]
is that true for a unit that has loci etc. in it? Otherwise it would be 
okay. As long as a unit does not have any records attached to it, 
deleting it is a benign task.

Am 26.05.2022 um 14:15 schrieb luizaogs - ***@***.***:

**Comment by luizaogs** [comment]
Ah yes, you're right. This only applies to units with nothing in them. So we can close this?

**Comment by urapadmin** [comment]
If you cannot delete a unit that is in use as a registrar but can do it 
as admin, then yes.

Am 26.05.2022 um 14:38 schrieb luizaogs - ***@***.***:

**Comment by luizaogs** [comment]
Yep.
