### ISSUE TITLE
PACHA: error during export to workstation because of wrong time zone setting

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#1638]
![image](https://user-images.githubusercontent.com/38838314/168210480-336fdd52-7216-4c7f-b244-88b856604883.png)

**Comment by urapadmin** [comment]
This is happening because when the workstation was created the GMT-TimeZone was set to "PERU", which is not an integer. Something like -5 or so would be expected here. 
I have changed that for the workstation and now the preparation worked fine.

**Comment by urapadmin** [comment]
To prevent this in the future:
- [ ] Check whether time zone setting makes sense and has the right format.

**Comment by urapadmin** [comment]
> @nparkervan wrote: Since the field seemed to be free text, i assumed it wasn't linked to anything. Wonder if drop-down menu in that location would be possible if you add time zones later on.

yes, in a future version a proper timezone selector would be nice. 

Just to explain a general strategy I have been following: All the more administrative user interfaces are pretty bare bones in the current version. A lot of development time can go into checking things and making sure that user's don't make wrong inputs and help them with selections. Our strategy so far was to spent tome rather on adding new functionality and thus neglect these convenience things. So in all administrative user interfaces: Be extra careful about your inputs - there is not much tolerance built into the system, yet. But it is good now to see where things can get screwed up and I will attend to them as they trickle in.

**Comment by urapadmin** [comment]
### kiosk 0.22.1
Time Zone setting is now checked on creation of the workstation

**Comment by luizaogs** [comment]
Yep.
