### ISSUE TITLE
deletion in ceramic preprocessing typo (?)

### ISSUE THREAD

**Issue by luizaogs** [arch-kiosk/arch-kiosk-office#1639]
Is this a typo? I don't know if you actually meant to say "somethin" but in that case I would expect "somethin' ".

<img width="435" alt="Screen Shot 2022-05-13 at 3 21 45 PM" src="https://user-images.githubusercontent.com/67970402/168293139-67fbf4d8-d051-4709-8837-ba159a1bc293.png">

**Comment by urapadmin** [comment]
No, I made this one for your's-truely.

**Comment by urapadmin** [comment]
### recording 12.17
better? :o)

**Comment by luizaogs** [comment]
Ha, yes.
