### ISSUE TITLE
New workstation fails

### ISSUE THREAD

**Issue by nparkervan** [arch-kiosk/arch-kiosk-office#1640]
![BBE128AD-1DAB-4E4A-BA9D-BC802EF07147](https://user-images.githubusercontent.com/7636871/168306881-7e74f9ad-4ae7-4885-b569-97e934000ca2.png)

**Comment by urapadmin** [comment]
Presumably we have a capitalization issue here. To be on the safe side

**Comment by urapadmin** [comment]
the issue here is that "Pachapad01" has a space as the last character in the id. It is "Pachapad01 ". That screws things up.

- [ ] I suppose I better add some kind of check for illegal characters and troublesome spaces for the id field in future.

**Comment by urapadmin** [comment]
@nparkervan: I had to delete this workstation manually. Pleas avoid leading and trailing spaces, special characters and capitalization for identifiers. In a future version I will do that automatically to avoid this issue.

**Comment by urapadmin** [comment]
### kiosk 0.22.1
spaces and some special characters are now automatically cut from the workstation id

**Comment by luizaogs** [comment]
They are.
