### ISSUE TITLE
PASU admin login: Filemaker tools accessible

### ISSUE THREAD

**Issue by lbestock** [arch-kiosk/arch-kiosk-office#1644]
Logging into PASU's database in FM Go as admin leads to access to the Filemaker tools, which should not be the case.

The little down arrow in the upper left corner is accessible to admin users, which allows access to the Launch Center, etc. That should not be possible. 

This is true both for PASU test and PASU the real deal. I haven't checked the others, but this is 12.17.

**Comment by lbestock** [comment]
PASU and PASU test are not in the same place - it's 12.15.1 on PASU. I have just used that to update the ID methods for Stratigraphic Units to free input, and have synchronized. I do not have the FM tools problem on my Mac, just on my iPad.

**Comment by urapadmin** [comment]
that is by design. Only on the start page should you have access to the filemaker menu if you are logged in as admin. (well there are a few other places as well but not excavation. Doesn't really matter.)
The filemaker menu can potentially come in handy for remote support that's why it is that way.
