### ISSUE TITLE
On Chrome: Caching prevents download of new workstation

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#1651]
Chrome's caching issues are numerous. Just that we found out that Chrome is the better Browser on iOS we had to realize that it is caching downloads in a way that prevents downloading a workstation again. The download is fast like lightspeed and all one gets is some 12KB big file.

That might be a caching or a MIME Type issue. 
see also:
- [ ] #22 
- [x] #1631 
- [ ] #1372

**Comment by urapadmin** [comment]
> Is this only on the iPads? I returned my loaned iPad for use in the field, so I no longer have an iPad to test with.

we have encountered it on ipads but it cannot hurt to test it on all platforms we have available. So give it a go (once 0.21.1 is out).

**Comment by luizaogs** [comment]
I've never had this issue on my Mac (on Chrome, even though I have had caching issues with non-workstation file exports). ]

But I just got it twice in a row on my iPad. Chrome tells me the download should be 18 MB or something, but then when I download it I get 12 KB and the file does not open in Filemaker.

**Comment by urapadmin** [comment]
> I've never had this issue on my Mac (on Chrome, even though I have had caching issues with non-workstation file exports).
> 
> But I just got it three times in a row on my iPad. Chrome tells me the download should be 18 MB or something, but then when I download it I get 12 KB and the file does not open in Filemaker.

That sounds like the very issue. What project are you using? PVD? However you might have to reinstall the Chrome app and try again.

**Comment by luizaogs** [comment]
PASU test. I can definitely reinstall Chrome but I’ve never used it to download anything from PASU test so not sure why anything would be cached? Let me see…

**Comment by luizaogs** [comment]
Ok, it seems to be working now. Hm.

**Comment by urapadmin** [comment]
you think I should know these things, hm? 
I, too, am just guessing :o)

**Comment by luizaogs** [comment]
Ha but you were right! I'll move this back to "under observation".

**Comment by urapadmin** [comment]
I suppose that's what they call an educated guess :)

**Comment by urapadmin** [comment]
it has happened again to Laurel using the local PASU Server. So this is not finally solved.
- I'll think about a more brutal caching option after some research on Chrome.

**Comment by urapadmin** [comment]
### kiosk 0.23
- there are more "don't cache" commands for chrome now. Let's see if it is better.

**Comment by urapadmin** [comment]
this appears to be fine now. We had an issue in Italy with Chrome but it was not the usual caching issue. Candace reported something about popup blockers. A different issue.

**Comment by lbestock** [comment]
Not investigated yet, but I have just had a zero KB download in Chrome on an iPad I was using yesterday. PACHA. Two other weird things surrounded it - I was asked to use my password instead of my fingerprint to open the iPad, though it did not indicate it had updated. And at the same time it did the phantom download it asked me if I wanted to install Google Drive. This is the new iPad so possibly related to whatever Candace saw?

**Comment by urapadmin** [comment]
I suspect this is a different issue than the original cache issue. We should open a new ticket for it.

**Comment by luizaogs** [comment]
I just opened the new ticket (#1762) so closing this.
