### ISSUE TITLE
PASU CM: one can create a bulk without a material selected

### ISSUE THREAD

**Issue by lbestock** [arch-kiosk/arch-kiosk-office#1653]
Filemaker, testing PASU before giving it to them.

I clicked the "bulk" CM creation button. The drop down menu for selecting material appeared.
I did not select a material, I just clicked the check box.
It created the CM with code O which is not even a code in the current configuration ("other" is H).

I would have expected it to be impossible to create a bulk with no material, and would prefer that if the material code is to be part of the number.

**Comment by urapadmin** [comment]
### recording 12.17
- that should not be possible anymore with the material selection
- it should also not possible with free input (unit)
- and it should be caught in sherd analysis when creating a new sherd.

**Comment by lbestock** [comment]
I do not understand the latter two check boxes in relation to material selection, but the issue I thought the ticket was about is fixed.

**Comment by urapadmin** [comment]
You just ran into it in one type of generation method, I look at all of them to see if the same error exists elsewhere.

same issues: 
- You were able to click okay without having input anything with free input (unit's, e.g.) and 
- when creating a new sherd we have the partial input method which also allowed you to input nothing any yet click okay.

**Comment by lbestock** [comment]
All good!
