### ISSUE TITLE
filemaker: several issues with importing and exporting of configuration and identification methods

### ISSUE THREAD

**Issue by lbestock** [arch-kiosk/arch-kiosk-office#1654]
I downloaded the PASU file from the online server. I exported ID methods, configuration, and CM methods.

I then deleted the FM file itself, and logged on to the local server for PASU and downloaded that. I then imported the above things. Two things went wrong.

First, the ID methods were not updated in the FM file for some reason. They were still the gobbly gook. Since the ID methods themselves HAD been properly imported and updated, I reapplied the proper settings. I was then able to create units as expected.

I then uploaded the FM file back to the local server PASU Kiosk. My import was refused. This has happened multiple times now and it confuses me particularly because somehow it thinks I uploaded from a file that was for LDB ipad. There is only one FM file anywhere on this computer right now, and it is the one I just created for LDB Mac. So something in importing those methods has changed the file in a way that it now thinks it is the wrong file.

![image](https://user-images.githubusercontent.com/49291909/168896926-5eea2bb0-4c51-4fac-8f1c-820d9ffbb96c.png)

**Comment by urapadmin** [comment]
ja, this was a bad idea of mine: Importing the configuration puts the workstation in a state that it can't be uploaded again. 
- [ ] that could be changed by not importing "system" keys

And then the other issue here might be that importing identification methods changes the uids of the methods and so they don't match the configuration anymore
- [ ] keep uids for identification methods when importing them

**Comment by urapadmin** [comment]
I close this because the immediate issue is solved. The general issue that transferring configurations is more or less impossible currently is in #1699.
