### ISSUE TITLE
synchchronization: after rewiring a file, delete the image record in the file repository

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#1655]
currently it seems that when synchronization rewires a file after the upload failed because one was duplicate the image record of the duplicate file is kept. I should deleted it because it appears as a "broken_file" in the file repository.

**Comment by urapadmin** [comment]
### kiosk 0.22.1
this should be solved. I have only dry tested it, so this need a proper test and please on a server where nothing can go kaputt!

**Comment by lbestock** [comment]
Done on PASU Hillside and it performs entirely as it should!
