### ISSUE TITLE
FM magnifying glass search tool: include fragment numbers in results

### ISSUE THREAD

**Issue by lbestock** [arch-kiosk/arch-kiosk-office#1657]
My feature request is related to a problem. The workflow for object photography relies on being able to quickly find records of objects to make QR codes for them. Navigating through the system is unworkable. The search is perfect. But currently the search does not include fragment numbers, and that is one of the most likely areas where PASU is going to want QR code photos using the Apple Watch. 

I want to be able to jump to a sherd record from the magnifying glass on the home page when I type the identifier. 

However, I recognize that this would have downsides and so I'm not sure my solution is the right one. If there are lots of sherds (and there always will be) then the list of possible contexts when one starts typing is really long, and that list is not scrollable and it makes the search unusable for other stuff. So this isn't quite a request, it's a ticket defining a problem that is not a bug.

**Comment by urapadmin** [comment]
as for timing: You think this is necessary for the upcoming field seasons?

**Comment by lbestock** [comment]
Aha! I didn't even know about the search function in ceramics processing. Well, that makes that whole interface much easier and makes this situation moot. Peter does need this functionality this season but since he already has it, I will amend my object photos instructions and close this here ticket.

**Comment by lbestock** [comment]
I tried it briefly on the iPad for PASU and it seemed to be working just fine.
