### ISSUE TITLE
file import: immediate answer looks like it is doing something but isn't

### ISSUE THREAD

**Issue by lbestock** [arch-kiosk/arch-kiosk-office#1658]
We tried importing a ton of files with extensions defined and failed twice before figuring out that NEF cannot be capitalized. (A space might have been a problem, too.) But more important: we got what looked like a process still running to Laurel but was recognizable as being finished to Lutz. It said undefined number of images processed and imported. 

Local server PASU import using a ton from an SD card.

**Comment by urapadmin** [comment]
- [ ] delete spaces from the list of files and perhaps lowercase everything (or make sure that the case does not matter later when searching)
- [ ] make sure that the process actually shows something even if no files are going to be imported or even touched
- [ ] make sure the process has a response that shows that it is done

**Comment by urapadmin** [comment]
### kiosk 0.22.1
it should all be better now.

**Comment by luizaogs** [comment]
Should this be tested with a ton, or can I test it with a bunch?

**Comment by urapadmin** [comment]
it‘s a ton only.

**Comment by lbestock** [comment]
And now on the testing front...
- [ ] delete spaces from the list of files and perhaps lowercase everything (or make sure that the case does not matter later when searching)
- [ ] make sure that the process actually shows something even if no files are going to be imported or even touched
- [ ] make sure the process has a response that shows that it is done

**Comment by lbestock** [comment]
Works!
