### ISSUE TITLE
file repository: download of smaller versions of a file by users

### ISSUE THREAD

**Issue by lbestock** [arch-kiosk/arch-kiosk-office#1665]
Sometimes I want to download smaller versions of images, not NEFs. Is this something kiosk could itself accomplish instead of what I do now, which is download the big one then shrink it and save it separately?

Most of the time I use images I do not in fact want the full size ones. For instance, in a powerpoint the huge images are a pain, not a boon, and if I'm handing stuff over to the government they don't need enormous files. I really only need the enormous ones for publication, in fact. Could kiosk give me the option to download the original or a smaller version? Think of all the things that would be saved, from time to rainforests.

**Comment by urapadmin** [comment]
yes, kiosk is downright made for this

**Comment by lbestock** [comment]
Kiosk is pretty fantastic, I must say.

**Comment by urapadmin** [comment]
### kiosk 1.2.9
- there is a little menu opening up with download options
- except for "download original file" all other items depend entirely on what file representations are configured for the project

**Comment by luizaogs** [comment]
This seems to be working quite well, but I assume it is something @lbestock would like to look at herself so I do not close it.

**Comment by urapadmin** [comment]
@lbestock: Would you have you look, please?

**Comment by lbestock** [comment]
This is so great. It works.
