### ISSUE TITLE
backup reminder 

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#1668]
I will not get to backuping automatically before importing workstations. But what I should be able to do is bring up a reminder that the last backup was xx days ago or that there is no backup since the last synchronization. 

Perhaps the hub can do that? Wit a link that start the backup dialog. 

Only "prepare_workstations" privileges should see that

**Comment by lbestock** [comment]
Test on a local server. PACHA, we have decided, since everything else has real data and is getting dangerous for the testing.

**Comment by urapadmin** [comment]
Little flaw in the backup reminder: It says "your backup was x days ago" but what it really shows is how long ago the last reminder was triggered. So it works but the message does not make complete sense.

**Comment by urapadmin** [comment]
### Kiosk 0.25.4
- if there was no backup at all the backup reminder will point that out. 
- The backup reminder should properly refer back to the time of the last backup in its message if there was a backup
- The reminder reappears every day (unless kiosk/backup_reminder_days is set to something else than the default of 1)
- The reminder will not appear at all if kiosk/backup_reminder_days is set to 0
