### ISSUE TITLE
file import: local server forgets local path

### ISSUE THREAD

**Issue by lbestock** [arch-kiosk/arch-kiosk-office#1669]
PASU local server latest iteration forgets the local filepath for "ton" image import. This wasn't the case last week, I believe. It remembers the file-extensions last used, but I had to type in e:\ again. It was really helpful when it knew that already - that will be an oft-repeated step.

**Comment by urapadmin** [comment]
- think about how my last changes to suppress querying drives might have affected this
- at least in "ton" there has never been an explicit saving of the configuration keys per user so where did it save except for the browser cookie?
-

**Comment by urapadmin** [comment]
### kiosk 0.24
- [ ] it should remember the import path now per user
- [ ] there was a bug that would have also kept it from showing all drives available in windows. That is important. On the real local servers a plugged in sd card should be listed.

**Comment by lbestock** [comment]
All good. AND added to the documentation already. Closed.
