### ISSUE TITLE
PASU local server reporting not working

### ISSUE THREAD

**Issue by lbestock** [arch-kiosk/arch-kiosk-office#1670]
PASU local Hillside server running 0.22.2 - problems with file manager and reporting.
This is after Lutz updated the server in response to a renewed cache issue - still not nuclear but peppered with warnings not to cache things. But the first try on that didn't work and Lutz discovered other problems, and asked that I check all sorts of processes. This ticket is in response to that request.

File manager: inconsistent results when I click the arrows on the left. First reporting was always telling me Kiosk is unwell. After a reboot, that button now seems to work to ask me to drag a file to upload. But now I get the Kiosk is unwell message by clicking the file export button.

When I go to the reporting dock I cannot run a new report. (But then I looked into the definitions for the dock and those seem to have been erased, so this is no wonder.) But it is in a state of "report can be downloaded" and I can't do that, either. There I can click the button but once I am taken to the file manager I am told that Kiosk is unwell. 

No problems with upload, download, or any other hubbub processes I have tried with default docks, which includes creating a new dock.
No problems synchronizing. 
No problems managing users.
No problems backup.
No problems housekeeping.

Nothing else yet tried.

**Comment by urapadmin** [comment]
Well, honestly I think I just have not ever installed those reports.

**Comment by urapadmin** [comment]
### should be fixed as of 24.V.2022 11:30 pm

**Comment by lbestock** [comment]
This worked at Brown yesterday. Bugs in the report is a separate ticket.
