### ISSUE TITLE
download fails in Firefox

### ISSUE THREAD

**Issue by lbestock** [arch-kiosk/arch-kiosk-office#1671]
For fun I downloaded Firefox to my ipad to see what fun that would be with caches and filenames. No problem connecting to kiosk and telling my workstation to download. It even gives me a download manager that says the file is 33MB. But it fails immediately when I tell it to download, and Lutz says a week ago Firefox didn't even have a downloads manager...

**Comment by urapadmin** [comment]
I close this because KioskBridge is taking over.
