### ISSUE TITLE
kiosk admin: restart server button did not work

### ISSUE THREAD

**Issue by lbestock** [arch-kiosk/arch-kiosk-office#1672]
Local PASU server. I restored the database after testing that I had cleared all the data for #1660. It worked and then I went to restart the server. I received an error message that it would not work, twice. I have now simply rebooted the computer and run housekeeping and all seems to be fine. Now if I click the restart server button it does what I expect it to.

**Comment by urapadmin** [comment]
The restart button does not work on local servers. I am flummoxed that 
you report otherwise.

Am 24.05.2022 um 16:42 schrieb lbestock - ***@***.***:

**Comment by urapadmin** [comment]
- [ ] don't show the restart button on local servers in administration

**Comment by urapadmin** [comment]
### kiosk 0.24
- [ ] apart from my disbelief that hitting the button did anything on a local server, which I simply cannot believe, the button should now be gone on local servers (if they are marked as such in the configuration, that is).

**Comment by lbestock** [comment]
Restart button does not exist. Closed.
