### ISSUE TITLE
PACHA: Configuration on online server, backup / restore before field season

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#1677]
I guess that's how we should do it. Parker can play on both systems. But only online do we configure properly and create users and privileges.

Then before the field season we backup online and restore it to the local server.

**Comment by lbestock** [comment]
Task from local server testing:

IP address not showing up on desktop.

**Comment by urapadmin** [comment]
- [ ] IP Addresses now showing

> The local server DOES have the configuration of locus numbers and CM that looks to me like the latest version for PACHA.

yes, it does. I installed that yesterday. Nonetheless, if we find other issues with the config they must be made online and then Parker will have to restore a backup.

**Comment by lbestock** [comment]
But otherwise this seems good to me, including configuration, and so we can test splashtop and be done.

**Comment by lbestock** [comment]
IP address up. Splashed the top. Closing.
