### ISSUE TITLE
test PACHA synchronization with text fields typed in Spanish

### ISSUE THREAD

**Issue by lbestock** [arch-kiosk/arch-kiosk-office#1678]
PACHA will be keeping records in Spanish. We need to test this! Emoji have crashed things in the past - are tildes a disaster? Test this on the PACHA online server.

**Comment by luizaogs** [comment]
Can you give me a PACHA log in? I do not think I have one.

**Comment by urapadmin** [comment]
there you go. It is logs and you'll be asked to give yourself a 🗝️ password

**Comment by luizaogs** [comment]
Gracias. I shall do this later today.

**Comment by urapadmin** [comment]
Oh, my pleasure. I remember I tried a little test myself with some Machado de Assis and think it worked. But how would I know ...

When do we have you back from Egypt?

**Comment by luizaogs** [comment]
:) I leave on the 29.

**Comment by luizaogs** [comment]
PACHA now has a bunch of random quotes from La casa de los espíritus because I am reading it currently. I had tildes and other accent marks and upside down question and exclamation points in different text fields and it all synched perfectly, so I think this is fine.
