### ISSUE TITLE
FM: observations overview update in unit locus

### ISSUE THREAD

**Issue by lbestock** [arch-kiosk/arch-kiosk-office#1679]
The overview of loci in the FM should be updated to reflect changes in locus types. For "observations" this is not yet grabbing the new deposit data, for instance.
![image](https://user-images.githubusercontent.com/49291909/170303051-3f3c48a3-6927-4895-9b3f-bdaf7edcad27.png)

This locus has a visual "very well sorted" that it would be nice to see there, too.

Not critical.

**Comment by urapadmin** [comment]
question remains if we should get rid of the whole section below the locus list in general (perhaps in simple excavation?)

**Comment by lbestock** [comment]
I really like it in fact - helpful to be able to flip through when one doesn't remember which locus something is (so descriptions and photos, really). And Peter yesterday pointed to it as helpful. I would not get rid of it even in simple, but think removing observations was the right call.

**Comment by lbestock** [comment]
Still need to test the simple excavating question; not in my current context.

**Comment by luizaogs** [comment]
I was just switching between simple and full to test dummy images and they look exactly the same to me other than the fact that simple has QC enabled in the locus list while full does not, so in my mind it makes sense to get rid of full and make simple the default.

**Comment by lbestock** [comment]
I likewise have poked around in this and cannot see any reason not to use simple. I have this niggling suspicion in the back of my head that there was something that wasn't so simple about switching to simple but I cannot remember or find what it was. From my perspective as a user, we should switch. Also is it new that I can't see the + button in CM by trench? Appreciated. New ticket for switching to simple excavating.
