### ISSUE TITLE
pacha: reconfiguration after meeting on 25 May

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#1682]
- [x] inventory number stays just an alternative number that the lab people fill in as they like
- [x] #1701 
- [x] config: the bulk number will be [locus#][M]-[SEQ] with locus# being the locus identifier, M being the material code and SEQ being a sequential number within that material code. So C-001 and M-001 coexist within one locus
- [x] allow quantity and weight field for all material types and collected material types
- [x] show period (done in both collected material and small find)
- [x] no s'urachi style ceramics preprocessing, so we don't need the distinction between ceramic diag/non-diag either
- we decided not to put L in front of the locus id or U in front of the unit Id

**Comment by urapadmin** [comment]
### can be tested since May 30st

**Comment by luizaogs** [comment]
This is all fine.
