### ISSUE TITLE
PASU necessary local server tasks

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#1684]
- BGInfo is not updating the desktop
- Laurel found a bug? Was that the thing with the "insert" and the floating keyboard?
- switch from free input for loci to automatic numbering: In F next should be F-61 while in something like G we should start with 0

**Comment by lbestock** [comment]
My bug was the floating keyboard insert thing. If I went to insert and chose barcode it got totally stuck in barcode mode and I could not get out of it. As you saw, it also could get stuck in that field. So: floating keyboard issue. I've been unable to provoke either problem again with the full keyboard this morning.
