### ISSUE TITLE
PACHA: image issues? 

### ISSUE THREAD

**Issue by luizaogs** [arch-kiosk/arch-kiosk-office#1690]
I was testing the Spanish characters thing and added two images with descriptions to see if that would synchronize properly. The images are both in the file repository, but neither returned to the iPad. 

One, a locus photo for locus 035 is a dummy but there are no file picking rules defined for PACHA as far as I can tell, so I am not sure why it would be a dummy. The other, in a collected material in that same locus, did not go back to the iPad at all - I have an empty image container but the modified button, so something seems wrong.

A caveat here is that I was using my Mac and used the drag and drop, but I always use that when using my Mac and have never had issues so not sure if that could have caused this.

Neither seem to be in the FM gallery.

### tracking
- [ ] #1692

**Comment by urapadmin** [comment]
> One, a locus photo for locus 035 is a dummy but there are no file picking rules defined for PACHA as far as I can tell, so I am not sure why it would be a dummy.

:info If no rule is given NO file will be included for a recording group. This is equivalent with setting “ALL” and resolution “dummy” as the first order rule (so you can omit that if it is what you want).

So that is as designed (totally different question that we should presumably make sure that all projects have contextuals / low set.

**Comment by luizaogs** [comment]
Ha awkward. And you guys think I know how to use file picking. Well, never mind!

**Comment by urapadmin** [comment]
🍼 Is that THAT gin from the ARCE conference? Don't drink to much of it (as I did yesterday 🪦 (why is there a `:headstone` but not a `:headache`?)

**Comment by luizaogs** [comment]
There's an ARCE conference gin? That I didn't know.

**Comment by urapadmin** [comment]
> The other, in a collected material in that same locus, did not go back to the iPad at all - I have an empty image container but the modified button, so something seems wrong.

🐛 And that's a bug. I confused the order of the dummy image container with the real image container when I introduced the filename. That can have potentially happened with every file container. So if you or someone else has the time, please have a look at the other's as well in the next iteration.

**Comment by urapadmin** [comment]
Nadine should know about it (and I am surprised you didn't get it in length from Laurel :o))

**Comment by urapadmin** [comment]
There really should be a `:mummy`. We should really file a petition.

**Comment by luizaogs** [comment]
> There really should be a `:mummy`. We should really file a petition.

I would help you, truly.

**Comment by urapadmin** [comment]
file picking holes not limited to pacha or this particular container. We need to test this again: #1692

**Comment by urapadmin** [comment]
### recording 12.17
fixed (tested in #1692

**Comment by luizaogs** [comment]
I assume this isn’t the old 12.17, right?

**Comment by urapadmin** [comment]
oh. Do we already have a 12.17? Hmpf. 
No, there will be a 12.17.1 then. argh.

**Comment by urapadmin** [comment]
or I rather make it a 12.18 then.

**Comment by luizaogs** [comment]
> So that is as designed (totally different question that we should presumably make sure that all projects have contextuals / low set.

Should this be a new ticket?

**Comment by luizaogs** [comment]
This can otherwise be closed.

**Comment by lbestock** [comment]
Added to the "to do" ticket for getting projects out the door.
