### ISSUE TITLE
plan to keep real PASU clean from test data

### ISSUE THREAD

**Issue by lbestock** [arch-kiosk/arch-kiosk-office#1694]
Um, what is the plan? Can it be bullet pointed here so I don't get hopelessly confused? Peter is still putting in real data, but from the local server download if I remember correctly. So we can muck up online PASU with test data even in real areas with real data?

**Comment by luizaogs** [comment]
I don’t think I mucked up anything? If I did it was unintentional…

**Comment by lbestock** [comment]
This was NOT a comment about anything you have done. An honest question about the plan so we can both be comfortable and efficient and not destructive.

**Comment by urapadmin** [comment]
Not sure what you mean.

- the PASU data is on the local server. You can't screw with it if it is in the bag.
- To test things we should work on pasu_test (I messed up by updating pasu, too, but it doesn't matter much, either)
