### ISSUE TITLE
Hubbub: wrong error message when re-preparing a workstation

### ISSUE THREAD

**Issue by lbestock** [arch-kiosk/arch-kiosk-office#1696]
I prepared a workstation (PVD 0.24). I didn't download it. Then I set a file picking rule, so I needed to prepare again. I did so apparently well but got an error message that I did not expect:
![image](https://user-images.githubusercontent.com/49291909/170615126-9364c378-b93d-4560-be36-052f22f831cb.png)

I was not in the field previously.

**Comment by urapadmin** [comment]
you had not downloaded before?

Am 26.05.2022 um 22:14 schrieb lbestock - ***@***.***:

**Comment by lbestock** [comment]
correct

**Comment by urapadmin** [comment]
please retest: prepare workstation, make sure you don't download and it is not "in the field".
repeat the last step "prepare for ..."

**Comment by urapadmin** [comment]
okay, thank you- I'll look into it

**Comment by lbestock** [comment]
Possibly related?
![image](https://user-images.githubusercontent.com/49291909/170841325-652b9126-b32c-4c5e-bb61-ab73736002b4.png)

My warnings after I overrode a refused import from an unopened file stick around even though I have now synchronized and should be a step beyond that.

**Comment by urapadmin** [comment]
no, different thing. The latter is rather the same as #1624 and I would not dare touching it right now. These issues go away after a couple of minutes automatically.

**Comment by urapadmin** [comment]
### kiosk 0.25.1
This here was not a bug. IN_THE_FIELD is the internal state of a workstation that had been already prepared (independent of whether it was being uploaded or not). That's confusing to users and so I have lowered this from a warning to an information in the log.

**Comment by luizaogs** [comment]
Yep.
