### ISSUE TITLE
switch to simple excavating

### ISSUE THREAD

**Issue by lbestock** [arch-kiosk/arch-kiosk-office#1697]
Simple excavating should be the default setting; perhaps it should become the only setting.

**Comment by urapadmin** [comment]
patched. Now it must be synchronized into the projects.

**Comment by luizaogs** [comment]
You did? I just downloaded both PVD and PACHA and wasn’t told to synchronize either.

**Comment by urapadmin** [comment]
because I have not uploaded this version online. We are frantically trying to get the local servers ready.

**Comment by luizaogs** [comment]
Never mind, then.

**Comment by urapadmin** [comment]
### recording 13.x
- should be patched now

**Comment by lbestock** [comment]
I did not get a patch synchronization warning on test when I downloaded?

**Comment by urapadmin** [comment]
… because I had already gotten it and synchronized it in.

**Comment by luizaogs** [comment]
This looks fine to me but the use_simple_excavating key is still available in configuration and it doesn’t say obsolete or anything - should that be the case?
