### ISSUE TITLE
Hubbub: import all workstations fails

### ISSUE THREAD

**Issue by lbestock** [arch-kiosk/arch-kiosk-office#1699]
Testing #1663 and now at the stage of importing multiple workstations at once, one of which should be just find and the other of which should trigger a rejection. But it never even tried. I chose "import filemaker workstations" from the hamburger and got this immediately:

![image](https://user-images.githubusercontent.com/49291909/170842031-c8e70795-f2ef-4b67-9ae2-479d5ebdddaf.png)

**Comment by lbestock** [comment]
Oh. Well. Then I refreshed and tried it again and it worked so this looks like nothing but a minor hiccup.

**Comment by urapadmin** [comment]
I was trying to find this in the logs but you are currently creating too many at the same minute to really have a chance without spending too long on it. Should anything like that happen again: Stop.

**Comment by lbestock** [comment]
A repeat of my steps did not return the same problem but rather worked as expected.

**Comment by urapadmin** [comment]
okay, let's keep an eye on it when testing this on a local server

**Comment by urapadmin** [comment]
I qualify this as a hiccup that just needs a refresh.
