### ISSUE TITLE
idgen_material_serial

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#1701]
Needed for PACHA: locus + material code and within that a sequential number

**Comment by urapadmin** [comment]
### recording 13.x
- this should be available in PACHA now

**Comment by luizaogs** [comment]
So for this, two charcoal bulks should be something like locus-K-001 and locus-K-002 right?

**Comment by urapadmin** [comment]
yes, that is right.

**Comment by luizaogs** [comment]
Then this is fine.
