### ISSUE TITLE
USTP: local server upload "Ton" does not even open and leads back to the file repository

### ISSUE THREAD

**Issue by lbestock** [arch-kiosk/arch-kiosk-office#1702]
File import: ton does not work.

Told to do this, it kicks you immediately to the file repository (and in fact fetches all the images). Original suspicion was a file path issue. Developer to the rescue.

**Comment by lbestock** [comment]
There are still problems. Per #714 an image with the name 2000 Omie.jpg should be imported as belonging to context 2000 with the description Omie. I just did an import of three images:
2000.jpg
2000 floral.jpg
2000 Omie.jpg

2000.jpg and 2000 Omie.jpg were both imported. Neither had the description added. Both also received as a context-independent description EC009;022 - I have no idea what that means or where it comes from. Omie lacks Omie. And floral wasn't imported at all.

**Comment by urapadmin** [comment]
### kiosk 0.25.3
- fixed and it should now show you the import path properly in the selection

**Comment by lbestock** [comment]
Yes.
