### ISSUE TITLE
USTP local server: import images does not get description from filename

### ISSUE THREAD

**Issue by lbestock** [arch-kiosk/arch-kiosk-office#1703]
From testing the fix for #1702 a new import problem:

https://github.com/arch-kiosk/arch-kiosk-office/issues/1702#issuecomment-1140644361

**Comment by lbestock** [comment]
Hmpf I meant to put the text in here:
There are still problems. Per #714 an image with the name 2000 Omie.jpg should be imported as belonging to context 2000 with the description Omie. I just did an import of three images:
2000.jpg
2000 floral.jpg
2000 Omie.jpg

2000.jpg and 2000 Omie.jpg were both imported. Neither had the description added. Both also received as a context-independent description EC009;022 - I have no idea what that means or where it comes from. Omie lacks Omie. And floral wasn't imported at all.

**Comment by lbestock** [comment]
The EC009;022 seems to have come from the EXIF data of the camera. Use EXIF data was NOT checked, so this should not have happened. 

Ah. Floral was a NEF, so that explains that.

And the get description from EXIF was checked though EXIF as a whole was unchecked.

**Comment by lbestock** [comment]
Most of the import settings are remembered between imports (per user, I think was the idea). But interestingly that little checkbox in EXIF data for description gets checked again even if I unchecked it.

**Comment by urapadmin** [comment]
### kiosk 0.25.4
- [ ] all the checkboxes should be saved between file imports. That was not the case. They would always fall back to the configured default. BUT: They are only saved per user and only as long as a server is running. When the machine gets restarted the whole thing falls back to the configured default. A permanent store for user configuration is a thing of the future.
- [ ] no matter what detail checkbox is set, if the main checkbox for a filter is not checked, the filter must not apply. That was the second issue here: the exif information would get interpreted although the filter was unchecked entirely.
