### ISSUE TITLE
locus ID methods: different methods for different units?

### ISSUE THREAD

**Issue by lbestock** [arch-kiosk/arch-kiosk-office#1704]
Discussing now a project that might need to be simultaneously doing field recording and legacy data input, we consider different ID methods for different units. A legacy unit would need free input, necessarily. A new unit would need however the project configures generation of new locus numbers. This may be a consideration for 2022 PASU in the field if they are doing object photography of old stuff while also digging new stuff.

**Comment by urapadmin** [comment]
I have to look into what became of this feature when we introduced the collected material types with their own identification methods. But I think it is still there. Will need testing.

**Comment by urapadmin** [comment]
yes, that works and is activated for PASU and their legacy unit.

**Comment by urapadmin** [comment]
### May 30
It is available now on test pasu to test.

**Comment by luizaogs** [comment]
Weird - I apparently currently have a user in the real PASU but not on PASU test so cannot test this at the moment.

**Comment by lbestock** [comment]
Oh yay something you can test, crazy insomniac :) You're a user now. Give it a go.

**Comment by urapadmin** [comment]
go to sleep, you mustn't topple over! 🛌

**Comment by luizaogs** [comment]
I have to wait for my damn bag to be delivered :(

**Comment by luizaogs** [comment]
The different identification methods work!

This would be a different ticket, but since I don't know if it should be a new ticket at all I am noting it here quickly and will open a new one if needed: aren't "legacy units" usually excavation/feature recording for URAP, and that is why we have the fedora as the icon for those? So if PASU needs legacy units with loci those icons will be the same as those for the field recording units (the trowel). That is fine, I assume?

**Comment by lbestock** [comment]
"Legacy" itself means different things :) You aren't wrong. But in this case they are putting in their own old data, collected stratigraphically. So locus recording is itself appropriate and in terms of data there are no differences to a new unit.

**Comment by urapadmin** [comment]
:bed 💤  :bed 💤  :bed 💤 :bed 💤

**Comment by urapadmin** [comment]
why there is a `:couch_and_lamp ` and not a `mummy` I will never understand

**Comment by luizaogs** [comment]
Ok, that's what I thought. So I believe this is good.

(Tell AA to deliver my bag more quickly and I will go to bed, Lutz!)

**Comment by luizaogs** [comment]
HA ha ha a very detailed couch and lamp.

**Comment by lbestock** [comment]
Oh it was American Airlines. Let's pause a moment and be shocked.

**Comment by urapadmin** [comment]
A A? Oh no. 💩

**Comment by luizaogs** [comment]
They suck. Incompetence makes me tired.

**Comment by urapadmin** [comment]
does anybody know why a poop is called a hankey?

**Comment by luizaogs** [comment]
Because of South Park, apparently? Wow.
