### ISSUE TITLE
option to change (all) identifiers manually

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#1705]
After we see that PASU has systematically mistyped identifiers and after Parker asked how he could change an identifier if it had been wrong, we need a solution.

There is absolutely no way to rename dependent identifiers automatically. So the solution is: To set the database in a certain mode that allows ALL identifiers to be renamed. And then it is up to the projects themselves to not only change the identifier they typed wrong but also all dependent identifiers.
### related
- [x] #1941

**Comment by urapadmin** [comment]
Peter's project quite shows the difficulties of this: He made a 123-39-sf or so and changing the identifier from -sf to -non-diag would not help at all. Some identifiers coincide with other things like material type or cm type and those can't be changed. So this is really of very limited use.

**Comment by nparkervan** [comment]
Hi All -- just pinging that i am now in Peru and we are starting
orientation for folks on Friday 7/1

**Comment by urapadmin** [comment]
arch1900 also had created a unit with a wrong identifier and a bunch of loci based on that wrong identifier.
In this case an option to override all these identifiers manually would have done no harm, archaeologically, and would not have screwed with functionality. 

I'll consider the renaming mode for the admin in version 14. Perhaps I can skip or give it an additional warning in regions where it is too dangerous (collected material as explained for Peter's example comes to mind).

**Comment by urapadmin** [comment]
Renaming must address the navigation history like deletion does:

**Comment by luizaogs** [comment]
I'm getting the same issue with cut off messages on my Mac for this one (as I did in #1716): 

<img width="1022" alt="Screenshot 2022-12-12 at 9 53 00 PM" src="https://user-images.githubusercontent.com/67970402/207223527-7765717d-5cdd-4bc6-b7c6-5682af098911.png">

**Comment by urapadmin** [comment]
> In su ceramics, the rename button only pops up once I have a fragment selected. I assume that is purposeful?

yes

**Comment by luizaogs** [comment]
Ok the cutoff message is not an issue on my iPad. I will wait to figure out the other two checkboxes in #1716.

**Comment by urapadmin** [comment]
### recording 13.11
- [ ] This is basically the same as #1716, so we test it there. You can close this when everything is okay there

**Comment by luizaogs** [comment]
Close this?

**Comment by urapadmin** [comment]
not yet: #1716

**Comment by urapadmin** [comment]
and #1941
