### ISSUE TITLE
another insignificant typo

### ISSUE THREAD

**Issue by luizaogs** [arch-kiosk/arch-kiosk-office#1706]
That should presumably be "sequential" :) This appears when creating a new unit in PASU test v13 but I assume it is in other places where this option is available.

<img width="723" alt="Screen Shot 2022-05-30 at 11 17 37 AM" src="https://user-images.githubusercontent.com/67970402/171030663-df99ab20-a980-405b-ab64-1e7a0ac39865.png">

yours truly,

**Comment by urapadmin** [comment]
can't be changed because the text is individual per project. It would have to be renamed in every project that has the typo and that's not worth the effort. Nobody ever really sees this.
