### ISSUE TITLE
get rid of BarcodeCreator for qr code generation

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#1707]
Barcode Creator is slow and needs a license. 
Instead I intend to use the stand-alone javascript library from here:
https://davidshimjs.github.io/qrcodejs/

It is MIT and so it can be just part of V1 on GitHub.

**Comment by urapadmin** [comment]
### recording 13.1
all qr codes should behave exactly like before just they should render muuuuuuch faster.

**Comment by lbestock** [comment]
This needs real testing with actual photos in realistic scenarios, not just creation of the codes, because the new QR codes have more pixels than the old ones. That the old ones were simple was not inadvertent.

**Comment by lbestock** [comment]
Well the QR codes never cease to impress me :) My first living room trial run that I expected to have one success and one failure with resulted in two files imported. I won't call it done until I get the drone out and it's too dreary today to mimic Saharan sun. The speed is certainly much faster, and I am in FM Go 19.5.1 (not 19.15 - was that a typo or were you referring to the desktop version?) and it closes no problem.

**Comment by urapadmin** [comment]
> I am in FM Go 19.5.1 (not 19.15 - was that a typo or were you referring to the desktop version?) and it closes no problem.

apparently the issue does not exist in FM Go. Even 19.4 works fine. And yes, version tumult was a typo

**Comment by urapadmin** [comment]
where are we with this? Stuck?

**Comment by lbestock** [comment]
I don't know!
