### ISSUE TITLE
hub: sorting docks within ports alphabetically

### ISSUE THREAD

**Issue by lbestock** [arch-kiosk/arch-kiosk-office#1710]
In testing #1613 it was noted that dock sorting within ports wants some attention as to alphabetization and perhaps capitalization.

What is this??
![image](https://user-images.githubusercontent.com/49291909/170843981-9909c58c-dc52-4516-8463-9abd5ca92e5e.png)

_Originally posted by @lbestock in https://github.com/arch-kiosk/arch-kiosk-office/issues/1613#issuecomment-1140334304_

**Comment by urapadmin** [comment]
What is what?

**Comment by urapadmin** [comment]
### kiosk 0.25.5
- now the docks are ordered within a port by dock-id not regarding capitalization

**Comment by luizaogs** [comment]
Yep.
