### ISSUE TITLE
locus relations: Don't seem to have a proper file timestamp?

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#1712]
Coming out of #1711:
files in the file repos are sorted by context and date (both incremental). It occurs that locus relations don't seem to have a proper timestamp? 

>I didn't expect it otherwise - that was what I expected (on the sorting within a context). Only I found that it holds true for all images except locus relation images, but even there I don't really think this is a problem. Short discussion. I think it is all fine.

_Originally posted by @lbestock in https://github.com/arch-kiosk/arch-kiosk-office/issues/1711#issuecomment-1166342152_

**Comment by urapadmin** [comment]
Hm. At least in FileMaker itself I cannot see that there is a date missing. All timestamps are recorded.

**Comment by urapadmin** [comment]
This seems to be a Kiosk issue if at all

**Comment by urapadmin** [comment]
I cannot really reconstruct #1711 anymore. There is no identifier "F", so that must have been a different project than PVD.
In PVD it all does seem okay with the locus relation images. They do have a date and they sort properly.

@lbestock: Can you please try to reconstruct this? It might be a project specific issue.

**Comment by lbestock** [comment]
I will look at it - it was PASU, not PVD.

**Comment by lbestock** [comment]
But PASU test has no locus relations images so I can't reconstruct it, either, and no longer know where it came from. And the other two I checked I don't see any problem with locus relations time stamps, either. I do not see a problem here.
