### ISSUE TITLE
sort order: CM by area/trench is not ordered by ID

### ISSUE THREAD

**Issue by lbestock** [arch-kiosk/arch-kiosk-office#1715]
Sort order for CM by area is not as I expected for PASU. I am not, in fact, sure what it is:
![image](https://user-images.githubusercontent.com/49291909/175795078-081b50b9-7df5-490f-9bc6-c869e475f398.png)
Why is 029D higher than 029B, with 030C in between them? I was hoping for (and thus, at least in this instance, expecting, though I'm open to being told there is a reason that trumps my expectation) a list in order by CM number, which is context bound and so would allow me to more easily test reporting.

**Comment by urapadmin** [comment]
I think the sort order here is not by context but by date of creation.

**Comment by lbestock** [comment]
Closed until and unless someone complains about it in the field. If you're going for CM by context you go to the context, not the unit, I suspect.

**Comment by lbestock** [comment]
Argh it's bugging me again, though, as I test PACHA. Because it isn't in the order I make them, either, which means that the one I just made is not at the top when I go back to the list, which drives me crazy. Those obviously are the same day, so date of creation might still be the first principle and then something else within it. But time of creation it is not.

**Comment by urapadmin** [comment]
### recording 13.3.1
Okay, the order was entirely nonsensical.
- now ordered by identifier, but note: This is alphanumeric order. So I am not sure if that makes you happy in all circumstances, either.

**Comment by lbestock** [comment]
At least it is a recognizable order now, and I can find things in the list without, currently, going crazy. I will close it again until the next time I go crazy.
