### ISSUE TITLE
filemaker: switch to free input temporarily

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#1716]
PASU created a bunch of wrong legacy records that now need to be deleted and then recreated with the correct type.
The issue is that they are now in the field and so identifiers will be created automatically - for legacy data that is still not what they would want. 

Here is what they could do right now:
- Go to the unit in which the wrong records are and select "free input" on unit level.
- make the changes in the legacy records
- go back and remove the free input (that's tricky and only works on desktops: select something and while the cursor is in the control but the selection list not expanded hit DEL or BACKSPACE).

This ticket here is on the idea to activate free input temporarily while in the layout:
- one would be in the collected material layout and in the menu or so there would be a button to activate free input. The next click on + would produce the free input instead of what the layout usually would activate.

### related
- [x] #1941 
- [x] #1943

**Comment by urapadmin** [comment]
Just adding that this would also have been useful for USTP. Tyler wants to add legacy data while in the field. He can do it the same way as above but it strikes me that switching to temporary free input (which would not synchronize as a setting) as an admin feature would be more convenient.

**Comment by urapadmin** [comment]
### recording 13.9.1
- there is a new button in all burger menus now: Looks like an edit field with a caret

**Comment by luizaogs** [comment]
Uh yikes my head hurts from reading half of that. I'm going to give this a try but not sure I am competent enough. Let us see...

**Comment by luizaogs** [comment]
When creating a new record using free input, the message box I get looks like this (this is the message I get after clicking on one of the red buttons): 

<img width="438" alt="Screenshot 2022-12-12 at 9 44 21 PM" src="https://user-images.githubusercontent.com/67970402/207221446-f90457d7-ecb6-46be-9f8c-72087b66609c.png">

Clicking on the green plus button gives me the rest of the message (which means that I only get the full message when it is full screen). This is on my Mac.

**Comment by luizaogs** [comment]
Ok meh I am just trying to test the first checkbox with "identification_method_free_input" and am already having trouble. That key is set to "free input of archaeological identifier" but when trying to create a locus I get this: 

<img width="1022" alt="Screenshot 2022-12-12 at 9 53 00 PM" src="https://user-images.githubusercontent.com/67970402/207222364-b3b0b5c9-2759-4919-a061-3bc52f08aaf8.png">

I'm sure I'm doing something wrong but I don't know what. Help? The config key identification_method_free_input_locus is also set to "temporary free input with serial number."

**Comment by urapadmin** [comment]
> When creating a new record using free input, the message box I get looks like this (this is the message I get after clicking on one of the red buttons):
> 
> <img alt="Screenshot 2022-12-12 at 9 44 21 PM" width="438" src="https://user-images.githubusercontent.com/67970402/207221446-f90457d7-ecb6-46be-9f8c-72087b66609c.png">
> 
> Clicking on the green plus button gives me the rest of the message (which means that I only get the full message when it is full screen). This is on my Mac.

That is FileMaker. You could have resized the message window, too. FileMaker is just not showing a Messagebox that is large enough for a somewhat more extensive message to begin with. It is so dumb. That's why we have our own MessageBoxes meanwhile but I can't use them in this situation because - guess what? of FileMaker. So there is no remedy for this. More important would be what it looks like on iPads.

**Comment by luizaogs** [comment]
The message looks fine on my iPad. Now I just don't know what to do with the error above.

**Comment by urapadmin** [comment]
Sorry for being 🐌 🐌 But I had my first official (as in electronically registered) 3 days of vacation since 1996. So I think I am not legally allowed to answer this :o) But I do it anyways: I can reproduce this now and I didn't realize the PVD was using identifier lists to create loci. So I am back to the drawing board.

**Comment by luizaogs** [comment]
Sorry to ruin your well-deserved vacation!

**Comment by urapadmin** [comment]
This is all bad and convoluted. I withdraw 13.10 and try something else.

**Comment by urapadmin** [comment]
### recording 13.11
we test this by record type:
- [ ] temporary free input override: add new / edit locus

**Comment by luizaogs** [comment]
I like the 13.11 icon :) hohoho

**Comment by luizaogs** [comment]
Everything mentioned in the bullet points above is working. I'll test the other tickets separately.

**Comment by luizaogs** [comment]
Not sure if you want this to be closed, but all of the 13.11 tickets are done.

**Comment by urapadmin** [comment]
### recording 13.12
There is one more:
- [ ] temporary free input: add/edit su ceramic fragment

**Comment by urapadmin** [comment]
and please don't forget 
-#1943 and 
- #1941

**Comment by luizaogs** [comment]
I haven't -- I just thought those were supposed to be tested when the respective projects got updated.

**Comment by urapadmin** [comment]
true, but before we shan't close this one here.

**Comment by urapadmin** [comment]
### receording 14
rolled out now to pasu-test and ustp-test. So you can do the last tests in the real projects.

**Comment by luizaogs** [comment]
Ok, now they're all done.
