### ISSUE TITLE
Hubbub: delete export workstation failed

### ISSUE THREAD

**Issue by lbestock** [arch-kiosk/arch-kiosk-office#1717]
This is in such an old kiosk that I am hesitant to ticket it; I am also not sure the behavior is unintended. But it surprised me so you get it.

I am in the demo server, running 0.18.5. I wanted to clean up the Hubbub so that when I shoot a little tutorial there aren't things hanging around that I don't want. I clicked on the export workstation and my deletion failed, with this message:
![image](https://user-images.githubusercontent.com/49291909/176280926-e9f2e70d-ba9c-4b16-a9a4-37b48b3fb526.png)

**Comment by urapadmin** [comment]
### kiosk 0.2x
This should be fixed meanwhile.
