### ISSUE TITLE
kiosk: export failure on demo.arch-kiosk

### ISSUE THREAD

**Issue by lbestock** [arch-kiosk/arch-kiosk-office#1719]
I attempted to export a workstation and it forked but did not export. The error message I received was:
![image](https://user-images.githubusercontent.com/49291909/176332571-6337634b-c1c7-4ef1-a932-6b4827253b74.png)

This was in demo 0.25.6 from my Mac.

**Comment by lbestock** [comment]
Whoa. I tried it again, and this time I got a bunch of Chinese???
![image](https://user-images.githubusercontent.com/49291909/176332816-646789b2-ddde-4f6d-9357-7eadbdb7bc80.png)

That seems quite unfair to hit you with on a morning of ferrying from the hospital and so I most assuredly will shut this computer and stop producing anything else. Good lord.

**Comment by urapadmin** [comment]
The demo server must have a helplessly old recording installed ...

**Comment by urapadmin** [comment]
Sloppy or rather lazy versioning on my side. An incompatible database structure between kiosk and recording should lead to a different error. 
The recording is updated now and all should be fine.
