### ISSUE TITLE
export to filemaker fails because of duplicate user

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#1728]
happened to Parker in the field: He typed in the SAME user with the same user id on two different ipads at the same time (same synchronization round) and synched. The synchronization works because Kiosk itself does not enforce that the user id in filemaker has to be unique. But the later export to filemaker fails because then we have two users with the same user id and filemaker enforces the internal contraint. 

That is the end of things in the field.

**Comment by urapadmin** [comment]
### recording 13.2.1
- fixed. One can now make two users with the same user id on two different ipads without screwing the export up.
- what one should not be able to do is create two users with the same id in the same filemaker database.
- in such a case one simply deletes one of the two users later.

**Comment by luizaogs** [comment]
Yep, the export worked in the first scenario.

**Comment by urapadmin** [comment]
second scenario? What do you mean?

**Comment by urapadmin** [comment]
oh that's just while you are in FileMaker in the team member dialog you should not be able to create two users with the same id.

**Comment by luizaogs** [comment]
I asked because I can't tell whether the two users made it back since I also stupidly gave them the same name. Hm. I'll do it again.

**Comment by urapadmin** [comment]
and then you delete one of them and after the next round you have only one left.

**Comment by urapadmin** [comment]
if you tried it and it is still there I have to look into it. But that is a blow.

**Comment by luizaogs** [comment]
Sorry :(

**Comment by urapadmin** [comment]
wow. This is bad.
I deleted one of the Potatoes and one of the Llamas. On import the two deleted rows were logged, so I am sure.
Synchronization got only rid of the one Llama but did not get rid of the Potato. That is scary.
I have to dive deeper into this. But it seems indeed the first synchronization error I have seen in years.

**Comment by urapadmin** [comment]
is there a stamping foot thingy?

**Comment by luizaogs** [comment]
Could it be related to the fact that the potatoes have the same id but not the same name?

**Comment by urapadmin** [comment]
At least I don't see why (not that that means a lot given my disbelief in the whole thing). I'll have to debug this locally in minute detail. Uff.

**Comment by luizaogs** [comment]
Ack, my goal was not to give you more work…

**Comment by urapadmin** [comment]
you know that its not your fault. I am very glad that I can rely on your test results.

**Comment by luizaogs** [comment]
Still!!

**Comment by urapadmin** [comment]
🍨 🍦 Who will buy you ice cream in Jordan?

**Comment by urapadmin** [comment]
first test: deleting two normal (not duplicate users): No issue. So there is at least not a general synchronization issue with deletion. But look at strange log entries in #1730 .

**Comment by luizaogs** [comment]
> 🍨 🍦 Who will buy you ice cream in Jordan?

probably myself 😇

**Comment by urapadmin** [comment]
the problem with deleting one of them is now in ticket #1737.
Because the original issue here is now solved, I close this.
