### ISSUE TITLE
documentation: How to prevent users from screwing with it

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#1729]
@lbestock @luizaogs 

What do we do? Can we organize it in a way that "our" document is somewhere else?

**Comment by urapadmin** [comment]
no it is not but the Wiki has been deemed too strange or complicated for nowaday's folks? They hardly read or edit a doc, the wiki was too much (remember Sam?)

**Comment by urapadmin** [comment]
why is everybody so quick and flaky and engagement so thin?

**Comment by urapadmin** [comment]
I have to correct myself: It is not true for everybody 🙄

**Comment by urapadmin** [comment]
I can't decipher that one :o)

**Comment by luizaogs** [comment]
just my general reaction to the world

**Comment by urapadmin** [comment]
closed due to despair
