### ISSUE TITLE
local timezone not shown properly when earlier than the server's

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#1731]
nasty little bug that keeps me from finding out what the actual timezone for Parker is.
Only happens if the local time zone is earlier(!) than the server's time zone. So California, vs PVD e.g.

**Comment by urapadmin** [comment]
### @test: fixed in recording 13.2.2
Not so easy to test, though. Set your local ipad earlier  than the server but make sure that your workstation in Kiosk does not have anything set in the GMT field. 
You should get this message: 
![image](https://user-images.githubusercontent.com/38838314/177771005-b5b378ef-2f7f-4de1-8204-1a578f9a2b77.png)
And everything is okay if you have some actual number in the first brackets "Your local time (GMT02:00:00)" and not just (GMT). Of course, your own numbers would be different.

**Comment by luizaogs** [comment]
![C7AF9150-EE12-410A-A178-118424C21E07](https://user-images.githubusercontent.com/67970402/178068383-82ea41eb-14f3-4288-bcd0-068290bcf04d.jpeg)

I actually get this following the steps you describe above. Whenever I get the warning you want my workstation and ipad times are both earlier than the server (and they match). Is that what I should be doing instead?

**Comment by urapadmin** [comment]
in Chicago you should get the other one all the time. You are GMT-5 naturally, aren't you? And the server is in Providence. So GMT-4. I am confused.

**Comment by luizaogs** [comment]
I set my iPad to Chicago, so earlier than the server. But I didn’t change the workstation GMT time since you say not to do that above, so I didn’t get the warning with the GMT time. In Chicago I do get it all the time, but only when both iPad and workstation are set to the same time (earlier than the server’s). Am I misunderstanding your instructions?

**Comment by urapadmin** [comment]
presumably. I want you to not have anything set in the time zone field in the dock (workstation, you know) settings in kiosk.

**Comment by luizaogs** [comment]
Bloody hell. Now it worked, but I didn’t have anything in the GMT field before either. Well I guess it’s fine then.
