### ISSUE TITLE
Time zone check not working properly in GMT-5

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#1733]
PACHA reports that setting server and the iPads to GMT-5 leads to a time zone warning on the ipads.
They run with the server on GMT-4 and as far as I understand (and I am not sure about it) the ipads on Lima GMT-5?

My suspicion is still that the whole issue arises from the server being on GMT-4 or worse when synchronizing and forking.  One must set the server to the correct GMT time BEFORE preparing the docks.

However, I want to add a configuration key that allows me to shut off a team if I know that everything is set correctly but the messages keep coming for reasons I can't understand.

**Comment by urapadmin** [comment]
### recording 13.2.2
- [ ] if config key admin/skip_check_timezone_server_earlier is set to yup (default is missing which equals nope) the recording will not check if the server's time is earlier than the ipad's because that is uncritical from a server perspective. So if the server is GMT-4 and the ipad is GMT-3 the check will be skipped.

A config key admin/skip_check_timezone_server_later won't happen because it is dangerous. This is why:
If at some same time in the universe when the docks are prepared the server is set to GMT-4 and the ipad is GMT-5 the server would be at 01:00 and the ipad would be at 00:00. if the ipad shoots a photo within the first hour those images are in danger of not being transported back to the server.

**Comment by urapadmin** [comment]
I have checked what happens when I set my local PC to Bogota, Lima, etc. Windows does not allow me to set the "adjust to daylight saving time" checkbox and FileMaker reports the correct GMT-5. But If I choose Havana (GMT-5) daylight saving time is available and if checked turns it into GMT-6. So that can be a potential source for the trouble.

**Comment by luizaogs** [comment]
This works. But I am not sure if you are still working in it based in your last comment? If not it can be closed.

**Comment by urapadmin** [comment]
let's leave it open for the time being. The Peruvian case is not closed.
