### ISSUE TITLE
import of filemaker db: Importing a different Db should avoid further checks

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#1735]
Prerequisite before you even test this:
- [x] #1734

I have two workstations: ipad1 and ipad2. ipad1 was prepared for the field first, ipad2 afterwards.
I have then changed things in both of them.
Then I uploaded the db of iPad2 to the dock of iPad1. 

I should have gotten the import error `Error importing data from a filemaker source originally exported to a different workstation`
But instead I got 
`Although this is the right database it cannot be the most recent version of it. It has been created AFTER the most recently prepared version, which is really weird.`
That is a correct error but the second problem with the different version is a consequence of the first error. And that one is the important one.

**Comment by urapadmin** [comment]
### Kiosk 0.26.4
- [ ] that's fixed. This can be tested without special manipulations. Just do it as described in the body up there.

**Comment by luizaogs** [comment]
Works.
