### ISSUE TITLE
Synchronization error: Not deleting a duplicate excavator

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#1737]
wow. This is bad.
I deleted one of the Potatoes and one of the Llamas. On import the two deleted rows were logged, so I am sure.
Synchronization got only rid of the one Llama but did not get rid of the Potato. That is scary.
I have to dive deeper into this. But it seems indeed the first synchronization error I have seen in years.

_Originally posted by @urapadmin in https://github.com/arch-kiosk/arch-kiosk-office/issues/1728#issuecomment-1176771727_

**Comment by urapadmin** [comment]
second test, this time in the development environment:
I created duplicate users: two Llamas and two Potatoes just like Luiza. The Llamas had the same user name, the Potatoes did not.
I synchronized and got the duplicates in the next workstation round. 
I deleted one Llama and one Potatoe. 
After synchronization they were gone.

So I can't reconstruct this in the local development environment.

**Comment by urapadmin** [comment]
still thinking about this, @luizaogs: Is it possible that in your original test in #1728 some kind of time zone difference could have been involved. I am just asking because we have that as a reason for synchronization trouble somewhere else and I learned that you are not in Chicago and on the move. 
Wild shot in the dark, but perhaps it jogs your brain ...

**Comment by luizaogs** [comment]
Hmm. I don’t think so? At least both my Mac and iPad were definitely set to Brazil time, and I would think my docks were as well. But I’ve changed the GMT times for those a bunch to test other things since then so can’t be sure.

**Comment by urapadmin** [comment]
### kiosk 0.26.6
I have not changed anything directly related to this but some things but we have to try to repeat this anyhow, so let's try it with a new version.

**Comment by luizaogs** [comment]
Nope, same issue.

I created Cat 1 and Cat 2 (both with ID Cat). Cat 1 was created on my iPad and Cat 2 on my Mac. I then tried deleting Cat 1 on my Mac, synchronizing, and downloading again. Cat 1 is still there.

**Comment by urapadmin** [comment]
Notes on reviewing the locs:
- the workstation import shows the deleted line
- in synchronization it does not get deleted which would suggest that the master data has some kind of precedent. But why?

@luizaogs: Can you please try exactly the same thing on test?

**Comment by luizaogs** [comment]
Same steps led to the same result in test: Cat 1 remains after deletion and synchronization.

**Comment by urapadmin** [comment]
wow.

**Comment by urapadmin** [comment]
I think I have an idea why this happens. Can you please do the whole thing again? And this time before you synchronize the deletion (upload and import it, just don't sync) stop and make a database backup - tell me the filename here. Then you can sync and make sure that the error happened again.

**Comment by urapadmin** [comment]
wait. GMT-3? Where are you? Are you East of Providence?

**Comment by luizaogs** [comment]
Well, I was in Rio :) So yes, GMT-3. I am now in GMT-5 and will do this for you shortly.

**Comment by lbestock** [comment]
Also Luiza it is not sane to test tickets ten seconds after stepping off a plane on a long international journey! Eat ice cream. We need you for the long haul.

**Comment by urapadmin** [comment]
in real life it is a non issue in many ways. First of all server and ipads are set to the same timezone. But even if not one usually creates a record on one day and then deletes it on the next day. There are hours and hours between the two operations and then everything is fine. The issue exists only of the creation and the deletion fall into the difference between the workstation and the server.

**Comment by urapadmin** [comment]
🍨

**Comment by luizaogs** [comment]
Since ice cream is really the only thing I have at home, that’s not a terrible idea :)

**Comment by urapadmin** [comment]
I will not roll this out before you have not eaten your ice cream

**Comment by urapadmin** [comment]
sounds like the US

**Comment by lbestock** [comment]
I forgot about lunch in a mad quest to find out about settlement remains at Abu Simbel. But there are chips and ice cream here, too!

**Comment by urapadmin** [comment]
even in ones own github tickets one isn't safe being on a diet

**Comment by luizaogs** [comment]
Healthy lunches all around!

**Comment by luizaogs** [comment]
Works!

**Comment by urapadmin** [comment]
you tested it back in Brazil?

**Comment by luizaogs** [comment]
ja

**Comment by urapadmin** [comment]
full marks!
