### ISSUE TITLE
FM config: a wee typo

### ISSUE THREAD

**Issue by luizaogs** [arch-kiosk/arch-kiosk-office#1738]
Don’t kill me. I found a teeny tiny typo in the help text for the new timezone config key. It kinda makes you sound like a pirate.

![5792B22F-6BEB-460D-9C31-410C7D7D7629](https://user-images.githubusercontent.com/67970402/178070652-9af07e0d-39fb-485b-bc35-e8de5e99924f.png)

**Comment by urapadmin** [comment]
☠️ I am a pirate

**Comment by urapadmin** [comment]
somewhere deep within me

**Comment by luizaogs** [comment]
ha ha ha waay deep

**Comment by urapadmin** [comment]
why is there a ☠️ but not a :rum or :gin or :scotch and the only bottles that exist are 🍼 and 🧴 ? How can one be a pirate these days?

**Comment by luizaogs** [comment]
🦜here’s a parrot you can put on your shoulder

yo ho yo ho a pirate’s life for me (you’re welcome)

**Comment by urapadmin** [comment]
### recording 13.3
entered

**Comment by lbestock** [comment]
Alas, this is what it looks like on Mac and iPad:
![image](https://user-images.githubusercontent.com/49291909/178121013-70f5f77f-2939-451c-8da5-12bfdbdec6a1.png)
Grammatically correct but lacking a legible piratical parenthetical.

**Comment by urapadmin** [comment]
just your stupid Mac. Hey ho.

**Comment by luizaogs** [comment]
What was the piratical parenthetical supposed to be? Now I need to know.

**Comment by urapadmin** [comment]
the parrot

Am 09.07.2022 um 22:39 schrieb luizaogs - ***@***.***:

**Comment by luizaogs** [comment]
🦜🦜🦜🦜

**Comment by urapadmin** [comment]
ja, that one. It didn' work. I can't be a pirate.

**Comment by luizaogs** [comment]
Well, you tried and that’s what matters.

**Comment by lbestock** [comment]
You'd be amazed how not universal that sentiment is :) And I have a suspicion pirates are amongst those who find that trying alone doesn't butter any parsnips.

**Comment by luizaogs** [comment]
Aye, guess I should go find Lutz some parrots then.

**Comment by urapadmin** [comment]
### recording 13.3.1
- gave up on my Pirate's life

**Comment by lbestock** [comment]
Argh.
