### ISSUE TITLE
PACHA numbering: Samples and Small Finds share numbers

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#1739]
Within one locus I can make a sample 00, then the next SMALL FIND would get the 01 and then the next sample the 02 again.
So instead of counting up within one collected material type it is counting up within the collected material.

That's not what Parker wants.

**Comment by urapadmin** [comment]
### recording 13.3
the remedy is called partitioning and is documented [here for the not too faint of heart.](https://wiki.arch-kiosk.brown.edu/urapdev/doku.php?id=manuals:developer_manual:context_identification_-_generation_functions#idgen_serial)

The pacha identification method "samples" needs these `generation parameters`: 
```
domain=current_locus::arch_context
type=numeric
range_from=1
partition_by=cm_type
partition=sample
```

The pacha identification method "special finds" needs these:
```
domain=current_locus::arch_context
type=numeric
range_from=1
partition_by=cm_type
partition=small_find
```

**Comment by lbestock** [comment]
This is working, but samples currently start with 0 and small finds with 1 and they should both start with 1. Configuration, only.

**Comment by lbestock** [comment]
In my downloaded version of PACHA test the sample range was still set to be from 0. And in light of having just caught that something else in ID methods did not synchronize, I wonder if this is related? #1744 

Otherwise this looked and functioned as expected (with samples starting at 0, as the ID method I received would have indicated).

**Comment by urapadmin** [comment]
yes, I only added the partition_by and partition. And indeed, Pacha samples were set to be starting with 0. There wasn't any real testing going on before PACHA started :o/

**Comment by urapadmin** [comment]
but it can be closed, right?

**Comment by lbestock** [comment]
It can.
