### ISSUE TITLE
PACHA: Stupendous identifiers pop the layout

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#1743]
### recording 13.3
I have tried to make more room for them in the locus layout and collected material layout. And I thing in the locus list of the simple excavating layout.
Please have a look at it. In one or two cases I have also adjusted the text orientation to right, so that the first part of the identifier rather than the last part gets lost.

**Comment by lbestock** [comment]
If one adds a totally absurd prefix then it is still possible to make this horrible - if the whole second part is so very long then I am still getting the first part only visible in the locus tab of the unit. But that was not realistic. Using PACHA's current conventions it does indeed look much better and fixes the problem.

**Comment by lbestock** [comment]
Stupendous identifiers that are normal for PACHA pop the layout still in locus relations - one can't read which loci are related.

**Comment by lbestock** [comment]
And in the CM tab, the locus selection drop down at the top of the page does not show what locus one is actually in because it shows the first part, not the last part, of the locus ID. It's fine in selection, but not in showing, where it should be right-justified so that the relevant part is visible.

**Comment by lbestock** [comment]
And let us not mention QR codes.

**Comment by urapadmin** [comment]
### recording 13.3.1

> And in the CM tab, the locus selection drop down at the top of the page does not show what locus one is actually in
- Should fit now
> pop the layout still in locus relations
- more space, smaller sketch.

**Comment by lbestock** [comment]
Works in locus relations.

But I still can't see it on the iPad in the drop downs. No idea what locus I'm in here:
![image](https://user-images.githubusercontent.com/49291909/178162307-08270f32-c9da-4ad5-981f-32f3ad1047d5.png) and it's the same still in CM, too:
![image](https://user-images.githubusercontent.com/49291909/178162358-b61cbb5f-686b-43b2-8e62-d124781b7d37.png)

**Comment by lbestock** [comment]
Whoops that was the wrong screen shot. CM by locus, not by unit, is where the problem lies.

**Comment by urapadmin** [comment]
### recording 13.3.2
I have tried to make things even longer. I hope not for the worse.

**Comment by urapadmin** [comment]
not so weird :o) I have restored a real pacha database because I am in the middle of testing strange synchronization stuff.

**Comment by luizaogs** [comment]
Ah, then I will leave it alone!

**Comment by luizaogs** [comment]
Ok, CM by locus looks ok as do most of the dropdowns. But not all, and the ones that don’t work are ones with omar in them (see below) so I am guessing that doesn’t matter?

![AEDB4A03-84E8-4D9B-BAE1-36A46CE214A3](https://user-images.githubusercontent.com/67970402/178375885-01a17500-a5ad-4927-8624-b05637a4b424.png)

**Comment by urapadmin** [comment]
there must be a limit. The Omar identifiers are even longer than the PACHA identifiers. Next I am asked to support two screens.
I think we should call it okay, hm?
