### ISSUE TITLE
kiosk: new user not asked to set password

### ISSUE THREAD

**Issue by luizaogs** [arch-kiosk/arch-kiosk-office#1745]
Laurel just gave me a new login for PACHA test and I assumed kiosk would ask me to set a new password when I first logged in but it did not (I got an error that that wasn’t working or something but was so confused that I forgot to screenshot it). I’m in kiosk but never set a password at all. Weird? 

(I know I can reset the password now that I’m in but haven’t yet in case you need to see what happened.)

**Comment by luizaogs** [comment]
Hmm ok I logged out and tried coming back in and now it asked me to set the password, so this might be a hiccup rather than a bug but I will let you decide.

**Comment by urapadmin** [comment]
Given that we switch running system to different systems here I can imagine reasons how that might have happened that do not exist in real life. So I am inclined to call that a hiccup until somebody reproduces this

**Comment by luizaogs** [comment]
I also forgot to say that it happened when kiosk was being really slow, only I am not sure if that was because of the server or my crappy hotel wifi. When it went back to normal functioning I got the reset password thing no problem.

Just so you have all of the information.

**Comment by urapadmin** [comment]
Hotel? Are you on your way to the other chaos troup?

**Comment by urapadmin** [comment]
`bug`  is such a hard word :o)

**Comment by luizaogs** [comment]
Ha, not yet. That’s August. We came to Ouro Preto for the weekend. You should look it up - Brazil’s crowing baroque jewel (as if you didn’t have enough baroque in Germany)

**Comment by urapadmin** [comment]
Ha. And here I thought I was talking to you in Chicago. 
I hope there are some of those baroque-featured monkeys around. Their faces would fit a German baroque church pretty well. Some of our Baby-Jesus depictions have such faces.

**Comment by luizaogs** [comment]
Sadly no! But plenty of weird Jesus faces, for sure.

**Comment by luizaogs** [comment]
Sadly no! But plenty of weird Jesus faces, for sure.
