### ISSUE TITLE
CM small finds: period for small finds is present twice and does not copy

### ISSUE THREAD

**Issue by lbestock** [arch-kiosk/arch-kiosk-office#1746]
Testing PACHA update in FM Go 19.5.1.31, in which special finds got a bit of tweaking.

Period is a drop-down menu field on the general CM landing tab. It is also a field in the small finds tab, drawing from the same value list. When one has already filled it in on the general tab, it does not get automatically filled on the small finds, and it is thus possible to assign two different periods to the same object. (I haven't synchronized yet so I don't know if that will mess things up.)

**Comment by urapadmin** [comment]
well, collected material and small finds do have separate period fields. That is how the data structure on Uronarti has always been.
Now that we have small finds as a collected material type as a first solution I would just hide the period field under collected material.

**Comment by urapadmin** [comment]
### recording 13.3.1
no period under collected material visible in small finds

**Comment by lbestock** [comment]
A small find should be coterminous with its collected material. I mean, in PASU they create the former from the latter, but it still then gets its own CM record. 

There are many debates to have in here (an object has a date of manufacture but that is not necessarily its date of use, or not its only date of use, let alone its date of deposit). But in CM we are talking about date of manufacture and in SF about single objects.

Current solution is fine.
