### ISSUE TITLE
hub: reset template of a workstation should only be prohibited if there is a running job

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#1750]
up to Kiosk 0.26.4 you'll find the option "reset recording group" only in a workstation's option list (under more) if all workstations of that recording group (aka port) are in state "synchronized . waiting ...". 

That is paranoid and can be problematic. That's why we change it:

**Comment by urapadmin** [comment]
### kiosk version 0.26.5
- the option "reset recording group" will always be accessible under "more options"
- it will always be executed EXCEPT if any dock of type FileMakerWorkstation in the same recording group of the dock you clicked is part of a running job (forking, exporting, something with a progress bar).

**Comment by luizaogs** [comment]
Works.
