### ISSUE TITLE
FM: gear button absent in trench 

### ISSUE THREAD

**Issue by lbestock** [arch-kiosk/arch-kiosk-office#1752]
In testing the current work around that will be solved by #1716, following the instructions Lutz gave to Tyler to use in the field, I noticed a discrepancy that I am not sure about.

In USTP (12.15.1) once I had changed configuration to show unit ID methods, I went back to the home page. At that point I entered a unit and from within that unit, on the unit tab, I had a gear button to click to adjust my ID methods.

I then went to see if one could do the backwards adjustment to restore the configured ID methods on my iPad, which Lutz had said might not be possible. On my iPad PACHA was running v.13.3.2 and so I just did the things there. I could delete the new method, but found that I could not enter the gear button at all from within the unit - it was missing. I could still get in from the home page, which let me do stuff. Why?

**Comment by urapadmin** [comment]
And the difference is:
simple excavating vs. full excavating (which we will drop). 
Simple excavating is so simple that it does not even offer that gear button anymore.

**Comment by lbestock** [comment]
I liked the gear button. But not enough to interrupt the transition. Lazy, as charged.
