### ISSUE TITLE
full text search to find a context

### ISSUE THREAD

**Issue by lbestock** [arch-kiosk/arch-kiosk-office#1754]
The file repository does not search terms past the CM level, which we decided and it was the right decision in general I still think. But today I was putting together a lecture and looking for images of the low fired and unfired pottery from URAP unit FH, and the term low fired only exists in ceramic notes. Took me forever to find what I was looking for and I even panicked a bit and went to the SD card to see if I had in fact taken pictures. That's old school - I am done looking for pictures in the big mass on an SD card. (I could at least have sorted for pottery photos in the FR, but panic.) I want a way to be able to search descriptions in ceramics in the file repository, but since that shouldn't happen with every search I thought maybe a button I could click to enable search deeper than CM?

**Comment by urapadmin** [comment]
Sounds as if you confuse two things. The file repository should find a pottery image if that pottery image itself has a description or if the pottery record has a description containing "low fired". 

What you might have in mind is the scope of an identifier. If you list all images of a locus or a unit it will not list pottery images. At least we have set it that way. If you list the images of a collected material identifier you should get the pottery images because they are in the scope of the context collected material.

**Comment by lbestock** [comment]
When I search "low fired" in the description it comes up with nothing, even if I specify "pottery" or "collected materials and small finds". I have no idea what the identifier is. I only know the unit, and that there is low fired pottery, and how to find that I could not figure out. (This might not be a file repository issue at all, however, in that an analysis tool would allow me to ask "which loci have low fired pottery" and then I could go from there. I do tend to use the file repository as a search tool not just for images but to find contexts.) In this case the term "low fired" appears to be appended to the remarks field that perhaps does not get searched? (It's also weird that this is repeated for every pottery line though it is remarks on the whole URAP#, but this is Christian's baby.)
<img width="1022" alt="image" src="https://user-images.githubusercontent.com/49291909/179373664-4be51132-de99-4d09-b4e5-1f9f29c87165.png">

**Comment by urapadmin** [comment]
yes. That is not what the file repository does. It searches for files and their description. So if Christian had given any of the images the description "low fired" it would have come up.
You indeed try to find the pottery record itself and that isn't something you can do, currently. Not a file repository issue.

**Comment by urapadmin** [comment]
what you want is a full text search.

**Comment by urapadmin** [comment]
btw: I can do that.

**Comment by lbestock** [comment]
You mean you can do a full text search? So if I say "help, what contexts, even what URAP#s, had unfired or low fired pottery" you can give me a list? Well you are collecting the types of questions that people actually ask of their material and this one is pretty basic but was a real question.

**Comment by urapadmin** [comment]
You'd be amazed what I can do with a sql database.
But yes, a full text query just to have a list of contexts is a universal requirement, I think.

**Comment by urapadmin** [comment]
since it seems really something people might need I will add a new search tab to the start page as a first solution, but that's for a different ticket (it won't really be a full text search).

**Comment by urapadmin** [comment]
the particular question I have moved to the discussion board on data analysis requests: #1788
