### ISSUE TITLE
searching for a context by description and narrative

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#1756]
It is so hot that I can't do anything complicated, anyways. So why not add a new tab to the search function in filemaker and offer a search for description?

**Comment by urapadmin** [comment]
and the see also #1708. I strikes me useful.

**Comment by lbestock** [comment]
Is that something you would roll out to projects in the field? I ask because of what to tell Jeremy. Are you willing meanwhile to do searches for teams? Something that perhaps can be done despite horrible heat?

**Comment by urapadmin** [comment]
I can also generate search lists for teams. I have a cool office.

**Comment by urapadmin** [comment]
### recording 13.14
- this is available now as a third tab in the search function
- the search dialog is now a popup
- the new search by text also searches the configured pottery module if there is one. So in Urap it searches warecode pottery, in PASU it searches su_ceramics

**Comment by lbestock** [comment]
First exploration is looking good and suggesting it should be added to the hamburger menu in all layouts.

One tiny annoyance: when one has done a search by text, and then clears the search using the button on the right, one is automatically jumped back to the "by identifier" tab. One cleared the "by text" search because one wanted to input a new text search and so it's confusing to be jumped - I keep typing my term into identifier and then being told it has no matches when I know full well there is a text match for what I just typed.

**Comment by lbestock** [comment]
Can you in fact release this for URAP? To test the ceramics thing I will make new records and then search accordingly in pasu, but it's exciting to have this and I want to try it on the material I know best.

**Comment by lbestock** [comment]
It is not getting something added to a special finds description in pasu, nor something in collected material bulk description in pasu.

**Comment by urapadmin** [comment]
> Can you in fact release this for URAP? To test the ceramics thing I will make new records and then search accordingly in pasu, but it's exciting to have this and I want to try it on the material I know best.

no, urap is too far off, currently, to release it easily.

**Comment by lbestock** [comment]
There are quite some places where this is still not catching things. Some of these are minor but not all. I will list all the places I have checked and check off those that are popping up via text search.
[x] area description
[x] narrative
[ ] dayplay description

**Comment by urapadmin** [comment]
Well, this is NOT a full text search. We will do that in Kiosk one day, where it can be done properly. I focus on the main description and narratives here. 

- No photo descriptions of any sort as they are searchable in the file repository and rarely used.

- I will add locus interpretation
- I do not understand bulk CM description because sample description, small find description and bulk description are all the same field but I'll look into that.

You don't seem to have checked 
- warecode pottery notes, 
- su_ceramic analysis text fields and 
- cm pottery notes (only applicable in warecode pottery processing)

**Comment by luizaogs** [comment]
Deleting the search word works fine now.

Searching in portrait mode works.

**Comment by luizaogs** [comment]
cm bulk: yes
sample: yes
small find: yes
cm material: yes (but unless it's an obscure material like leather the result will not come up because search seems to first pull up units and loci so "stone", for instance, will never show up without our current lack of scrolling)
small find type: yes
locus interpretation: yes, but see potential issue noted in #1759

**Comment by luizaogs** [comment]
So summary is that it all works but scrolling is a problem for cm material, and locus interpretation is potentially not working as it should.

Besides those two things, this can be closed from my perspective.

**Comment by luizaogs** [comment]
Kidding! I didn’t do warecode. I will try to figure that out later.

**Comment by urapadmin** [comment]
sometimes adding a feature just leads to a bunch of complaints :o) 
As far as a I can see this is as far as I can get in FileMaker. The scrolling is a filemaker (iOS/Safari) problem that I have not been able to wrap my head around so far. There is some hope, but I would see that as its own ticket independent of the current topic.

**Comment by urapadmin** [comment]
we can leave ware code pottery for Uronarti later. But let's make it a new ticket then.

**Comment by luizaogs** [comment]
Those were not supposed to be complaints :)

**Comment by urapadmin** [comment]
I am just whiny :o)

**Comment by urapadmin** [comment]
> Ok. So I'll open those two tickets, I guess, and close this one?

yes, one step forward, two steps back for me :o) But it is the right thing to do.

**Comment by luizaogs** [comment]
The search function is great.
