### ISSUE TITLE
Kiosk: unable to make a new dock

### ISSUE THREAD

**Issue by lbestock** [arch-kiosk/arch-kiosk-office#1757]
Pasu-test will not let me create a new dock, with the following error message:
<img width="745" alt="image" src="https://user-images.githubusercontent.com/49291909/179758276-fbe55715-71ff-4f8a-b7b9-02840d214c0f.png">

**Comment by urapadmin** [comment]
ja, that is a side effect of one of the last kiosk updates on test and pacha_test

**Comment by urapadmin** [comment]
it will affect all older kiosks

**Comment by urapadmin** [comment]
fixed for pasu_test

**Comment by urapadmin** [comment]
fixed for urap and ustp

**Comment by urapadmin** [comment]
can we close this?

**Comment by lbestock** [comment]
Yup.
