### ISSUE TITLE
FM: should search button lead to the page where the text appears or the context itself?

### ISSUE THREAD

**Issue by luizaogs** [arch-kiosk/arch-kiosk-office#1759]
Testing #1708 and I am wondering if the search button should lead to the exact page on which the searched word appears or the overall record of the context (or what have you)? For instance, if I am in unit LA in PVD and I search for "book" and click on LA-007, a container context, the word "book" does not appear on the observations tab (unless I'm blind), which is where I land when I click on the record. I thought that was weird so then clicked on interpretation to see if it appeared there and it does. So I guess search takes me to the context and not necessarily the page where the searched word appears, even though it is clearly searching that text.

Not sure if that is what was intended. So this isn't a bug, just a question.

**Comment by urapadmin** [comment]
it would be much better if it did. I can answer with Wilhelm Busch:

„Ein jeder Wunsch, wenn er erfüllt, 
Kriegt augenblicklich Junge.“

So this is indeed a new wish. I do not mark (and can not easily) the attribute that includes the search word. Same e.g. with small finds. If you search for "statue" and it is the small find type I do not switch to the small find tab. I just open the collected material layout.

**Comment by urapadmin** [comment]
This is just a quick solution to something that should happen in kiosk one day. And there the question won't come up.
