### ISSUE TITLE
FM: search function warecode pottery

### ISSUE THREAD

**Issue by luizaogs** [arch-kiosk/arch-kiosk-office#1760]
A ticket to remind us to test whether the search function in FM brings up warecode pottery notes and cm pottery notes. Can be tested when URAP is updated to 13.5.1.

Comes out of #1756

**Comment by urapadmin** [comment]
we can really wait until we reactivate URAP. It is quite behind, anyways.

**Comment by luizaogs** [comment]
Erm. What is the difference between warecode pottery notes and cm pottery notes? The actual "notes" button in warecode pottery does come up in the search function, but I don't know which one that is.

**Comment by luizaogs** [comment]
Oh wait, kidding. I think.

**Comment by luizaogs** [comment]
Yep, I figured it out. This works.
