### ISSUE TITLE
FM popup search function: scrolling does not work in FM Go 

### ISSUE THREAD

**Issue by luizaogs** [arch-kiosk/arch-kiosk-office#1761]
Comes out of #1756, related to #1661 (I thought at first it was a duplicate but that pertains to popovers so I am not sure).

Even though the search function in FM has become a popup window rather than a popover in 13.5 scrolling through search results still does not work properly. This is most problematic for fields such as cm material type, since the search brings up records such as units and loci before cm, which means that those cm records will usually not be visible if the material is something as common as stone.

**Comment by urapadmin** [comment]
adding @lbestock here.
I know now what is going on here. 
The list only scrolls after it has been clicked. So you have to search, then tap into the list and then you can scroll up and down. That isn't very intuitive, agreed. 

The only way to change this would be to not search while typing but have a button that does the search and afterwards sets the focus right into the list. 

I am not sure what is better. it is nice that the search results come in while one types.

**Comment by urapadmin** [comment]
yup, found an official statement on this from Claris:

> Development says this is intended behavior with a Web Viewer in FileMaker Go. The Web Viewer needs to be selected first. They also suggest using a script trigger to activate the Web Viewer.

**Comment by luizaogs** [comment]
Hmm to me it maybe sounds better to have the button that brings up everything at once and then the scrolling works without having to click on the list, but I am not sure.

**Comment by luizaogs** [comment]
Actually, now that I know how it is supposed to work it seems fine. So rather than changing it it might be enough to add something to a user's manual.

**Comment by urapadmin** [comment]
nobody reads user manuals. At least about something small like that, I suppose. 

- [ ] But I think I could simply put a little note on top of the control because it does look like a bug.

**Comment by urapadmin** [comment]
interestingly this issue does not seem to exist at all on MacOS. At least I can just scroll and click into it. I tested this particularly in the deposit details with the new horizontal selector of soil type and on MacOS one click is enough no matter where the current focus is.

**Comment by urapadmin** [comment]
In the USTP Meeting @lbestock  was not happy about this

**Comment by urapadmin** [comment]
which surprises me. @lbestock can you please test this again on your ipad. In fact it is really simple: The first click activates the list, then you can either click or scroll.

**Comment by urapadmin** [comment]
I close this. It is not moving.
