### ISSUE TITLE
FM: issue with zero KB download

### ISSUE THREAD

**Issue by luizaogs** [arch-kiosk/arch-kiosk-office#1762]
Original issue reported by @lbestock in #1651, but this seems to be something other than caching preventing download. The following are the descriptions of the issue as first reported by Laurel in that other ticket: 

Not investigated yet, but I have just had a zero KB download in Chrome on an iPad I was using yesterday. PACHA. Two other weird things surrounded it - I was asked to use my password instead of my fingerprint to open the iPad, though it did not indicate it had updated. And at the same time it did the phantom download it asked me if I wanted to install Google Drive. This is the new iPad so possibly related to whatever Candace saw?

This persisted after a new download, and there is nothing I see going on with popup windows. An incognito window allowed me to get a useable download, but that's not what we want.

Something up here. Next try (not incognito) it told me 17MB, as it had through incognito. But then when I hit download it told me "cannot download". I hit download again, and it was much too quick. And yet, it opens after I replace the old file.

I may have been too quick about popups - "install google drive" is still around in non-incognito.

**Comment by urapadmin** [comment]
you have tested a bit since then. Do you still encounter it? Or is it just gone?!?

**Comment by luizaogs** [comment]
This was Laurel, I never had the issue.

**Comment by urapadmin** [comment]
ah. oh. Confusing. But: Hi!

**Comment by luizaogs** [comment]
:)

**Comment by urapadmin** [comment]
I close this because a) we found out that older iOS Versions made Chrome have the issue and b) we now have KioskBridge.
