### ISSUE TITLE
collected material should be organized by collected material number rather than type

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#1764]
@aes1884 wrote per email: 
>Is there any way to switch the collected material back to being organized by collected material number rather than by type in the filemaker database? The organization by type is something new and a bit awkward for using when the rest of our system for dealing with objects revolves around the collected material number.

**Comment by aes1884** [comment]
In the new 2022 file, the collected material is arranged like this:
<img width="779" alt="image" src="https://user-images.githubusercontent.com/68443221/186221781-4e1332db-7572-4ca2-ad06-94d636b16ecf.png">
all the small finds are grouped together at the top, regardless of collected material number, while bulk finds are below.

It would be much easier to use if they remained organized by collected material number, as they were in the past (screenshot below from 2021 version)
<img width="776" alt="image" src="https://user-images.githubusercontent.com/68443221/186222372-f0f6893d-72a6-41f7-a8a7-860fb19fcd40.png">

Does that clarify the matter? My apologies for being confusing!

**Comment by urapadmin** [comment]
It seems the current sort order does not make sense even if we kept grouping by cm type. I'll look into it.

**Comment by urapadmin** [comment]
### recording 13.5.3
ja, there was no sort order at all on those records. There is no perfect sort order here, though.
I have now done this:
- in the locus layout collected material is order by creation descending. That keeps the collected materials in the order they have been recorded which makes some sense here
- in the unit layout (excavating) I can't do any better than using the cm identifier. BUT! That is an alphanumeric order and hence LA001-2-2 is on top of LA001-2-12.

**Comment by luizaogs** [comment]
Was going to test this but I realized I don't have a PASU test log in -- can you give me one?

**Comment by urapadmin** [comment]
Much better: I have rolled out a PVD birthday version.

**Comment by luizaogs** [comment]
An honor :) I was going to test it now but Kiosk is apparently in emergency state. Ha.

**Comment by luizaogs** [comment]
By creation descending (in locus layout) do you mean that the most recent should be on top? This is what I see currently: oldest on top and latest at the bottom, though even that is a bit confusing because then 29 VIII 2022 should be below 27 II 2022, no?

<img width="1018" alt="Screen Shot 2022-08-29 at 9 01 34 AM" src="https://user-images.githubusercontent.com/67970402/187219135-aeb3b6c1-39d7-48fa-9f6c-a4afe80490f4.png">

**Comment by luizaogs** [comment]
The order in the unit layout looks ok to me based on what you say above.

**Comment by urapadmin** [comment]
### recording 13.5.4
ja, got the wrong field to sort in collected material. 🥟 It should make more sense now.

**Comment by luizaogs** [comment]
Yup.

**Comment by urapadmin** [comment]
still need to update it for arch1900, so: reopened

**Comment by urapadmin** [comment]
I close this now because 13.5.4 is rolled out to arch1900
