### ISSUE TITLE
kiosk backup/restore: place the reminder file somewhere else but in the backup directory

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#1767]
it occurred to me when caring for pacha and pasu that I did not get a backup warning. The reason is: I don't have their backup drive. So I suppose of the backup drive is not connected one does not get the backup reminder. That does not really make much sense.

see also #1766

**Comment by luizaogs** [comment]
Eesh and should I know how to test this? Feeling slightly useless.

**Comment by urapadmin** [comment]
No, sorry, you can't. Particularly not with the online server. I just forgot to assigned it to myself.

**Comment by urapadmin** [comment]
this seems to work, we even get warnings on Beset. Those I have switched off now in the config.
