### ISSUE TITLE
find a way to rename the labels in the Users and Privileges

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#1771]
Something like "repl-id" etc. is not very helpful when typing. 
It would also help a bit, presumably to have some help about some fields, if FlaskAdmin allows for something like that.

**Comment by urapadmin** [comment]
### kiosk 1.2.8
- the user layout has better lables and a few help texts
- the privilege layout has better lables and particularly a selection box for the available privileges.

what those privileges mean is documented here [[https://wiki.arch-kiosk.brown.edu/urapdev/doku.php?id=kiosk_privileges#kiosk_privileges]]

**Comment by lbestock** [comment]
Omar is a PVD user :(

**Comment by urapadmin** [comment]
Aviva is flashing all day. That's okay.On 31. Oct 2022, at 23:26, lbestock ***@***.***> wrote:﻿
Omar is a PVD user :(

**Comment by luizaogs** [comment]
The label for "repl user id" has been changed in the layout where I get to create the user, but in the layout where the users are listed it is still "repl user id". Was that intended or should that one have been changed as well?

**Comment by urapadmin** [comment]
I suspect it can be done here, too, but I think the important part was the layout where one actually creates and modifies data.
I can live with this. In the end it is all provisional.

**Comment by luizaogs** [comment]
Alrighty, then.
