### ISSUE TITLE
fm_file_transfer table change: store representation instead of file picking resolution

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#1772]
Currently I store the file picking resolution in the file transfer table: something like "low" or "high". 
For the PWA it would be more useful to have the name of the actual representation (something like "1024x768" or "small") instead so that I can use it to fetch the image via the api. 

So the resolution field will contain:
"dummy" if file picking does not have a resolution
the representation if file picking and file handling yield one
an empty "" (not null!) if the raw file has to be used instead of a representation

**Comment by urapadmin** [comment]
@test: Kiosk 1.2.1
This is implemented. 
- [ ] It is important to test whether the filemaker fork and export work normally and the right images are transfered to filemaker. There might be side effects.

💡  To test this it makes sense to set up a workstation in a new port (recording group), define the file picking rules for that port and make sure to not only reset the workstation in that port in every new test iteration but also to reset the port (recording group) itself. That can be done by clicking on the dock and select reset recording group. But that's only available when the dock itself is reset.

**Comment by luizaogs** [comment]
I believe everything is working as it should.
