### ISSUE TITLE
FileMaker not showing svg images in image containers

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#1775]
They never improve this software in any meaningful way. They can show svgs on buttons but not in image containers. Why is not only beyond me.
This is a particular issue in the dayplans because you cannot really see your dayplans or you have to export a rasterized image which takes more space and has a crappy resolution later on. 

At least in the dayplan section I could try a webviewer. I just don't know where to show it.
Ideas:
- only in terms of an svg I could try to show a webviewer on top (or below) the image container.  But that will presumably screw up user interaction.
- for dayplans I was thinking of a map - narrative view that can be activated in the narrative: It shows the current SVG (this time in a web-viewer) and the current narrative more or less full screen. The narrative would be editable. That would allow a good map - narrative interaction: #1776 
- Touchdraw -> PDF does make some sense because the embedded image is still a vector but Filemaker can show a pdf. It just does not work the other way around: exporting such a pdf back to Touchdraw will hardly result in an svg. That is also the trouble with thumbnails.

**Comment by urapadmin** [comment]
### recording 13.7.6
- A bit experimental: In daylans images with an svg file in it are now shown as green panel that asks you to click. If you do, the svg is shown in its own popover. 
- The popover does close as soon as you click anywhere else, so looking at it while you type the narrative is in this solution not possible (but I could think of something in the next iteration if requested).
- for this first take on a solution you find this only in simple excavation (not in feature, survey etc.)

**Comment by lbestock** [comment]
Clicking on the green svg in the list of images on the ipad produces a white box that shouldn't be there.
![image](https://user-images.githubusercontent.com/49291909/202910289-35f611ea-f376-4a69-ad2b-3666007e3047.png)
I can make it disappear by clicking in the narrative section of the screen, but not by clicking on the preview of the image container down in the lower left.
Note that this happens only (and always, as far as I can see) if I hit the green svg placeholder in the image list. If I hit the description to the right of that svg placeholder then things look as they should.
![image](https://user-images.githubusercontent.com/49291909/202910384-437d6025-cf7a-4f19-88dc-94e585c2de78.png)
Viewing the svg works just fine as long as I get that latter view to begin with.

**Comment by urapadmin** [comment]
I don't understand. The white box is where the svg should be! It is clearly empty but that could be due to the specific svg. I would have to see it. 

How can viewing the svg be just fine otherwise? Where do you view it if not in that box?

**Comment by luizaogs** [comment]
I'm having the same issue on my Mac, and in fact for me even clicking on the "this is an svg, please click here to see it" does not work -- I still get the white box.

I am looking at the same two svgs as Laurel in CA, Lutz, so I assume you would get the same result if you try it too.

**Comment by lbestock** [comment]
This svg I can see by doing the following:
Click on the description part of the line to the right, so I get the same screen as the second screen shot above.
Clic on the little picture icon in the bottom left to pull up the "actions" menu.
Click "view".
Then the svg pops up and I see it on the whole screen. Nice little kiosk spiders, those two svgs, once with a hat and once without.

**Comment by urapadmin** [comment]
That you can pull up the actions menu has always been the case and it has always been the case that you can see the svg there. It is just that that would not work on Mac (right? There is no image view) and it happens full screen. I'll look at those two svgs. It must have something to do with them in particular.

**Comment by urapadmin** [comment]
okay, so this is what it should look like (well, at least what it looks like if it is working):
![image](https://user-images.githubusercontent.com/38838314/203129767-e00b18a8-8b04-4783-a391-1ef6fcd3d4a8.png)

**Comment by urapadmin** [comment]
So, I suppose we have a Safari issue here. I'll try a few things ...

**Comment by urapadmin** [comment]
### recording 13.8.3
- works on my ipad now.

**Comment by luizaogs** [comment]
Yes, works.

**Comment by lbestock** [comment]
This is now working on my iPad, too, which is where it was messed up yesterday.
