### ISSUE TITLE
Chrome again: Downloading Workstation does not work

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#1777]
After three successful summer seasons we have it back in arch1900: #1651. 
The symptoms are the same: On some? Institute iPads downloading in Chrome works once but on second download (?) one gets the way too small file that does not work. 

I keep #1651 closed to not make a mess and because I have my doubts that this is a cache issue. But who knows.

@lbestock, @Edbentl, @davise55 Please report everything you encounter and learn about the phenomenon here in Github. All information helps. 

We also have @luizaogs #1762 (turns out that was lbestock, originally) on the same topic. But I have not heard anything from her about it again.

I have suggested using the Incognito Window as workaround for now.

**Comment by urapadmin** [comment]
My own tests on a brand new Institute iPad have not had the issue. But then yesterday, I instructed Laurel to repeat a successful download and that worked. 
Does it happens only randomly?

**Comment by davise55** [comment]
It seems to happen randomly, and happens more often on the green iPad mini (the one labeled "Green iPad" in Kiosk).

**Comment by urapadmin** [comment]
> It seems to happen randomly, and happens more often on the green iPad mini (the one labeled "Green iPad" in Kiosk).

Okay, that is one of our oldest and slowest. If you have time to check: What iOS Version is it on? As soon as you can spare it, please leave it in the Institute, we'll pick it up for a test (@lbestock).

**Comment by urapadmin** [comment]
@cmrice-arch : Candace, I remember that you had issues downloading a workstation with Chrome in the very beginning of your season. Exactly like here: the download was ridiculously small and would not work. But you managed to fix it. Can you remember what you did or what the issue was?

**Comment by urapadmin** [comment]
Here is a somewhat less annoying workaround, @davise55, @Edbentl (also interesting news for @luizaogs): 
Unlike in Safari, in Chrome you can explicitly clear the browser's cache by going to the [...] menu -> settings -> privacy -> Clear Browsing Cache. And there it should suffice to clear the "cached images and files".

**Comment by urapadmin** [comment]
iOS Version on the Green iPad is way behind: 14.4.2. Might be worth comparing the iOS Versions of the iPads where it does happen and those where it doesn't (should they exist). In general we should make certain that we are all on the most recent version. Also dangerous: The green iPad had two Filemaker Go versions installed. Please check all the other iPads: Only FileMaker Go19 should be installed. Delete the others.

**Comment by urapadmin** [comment]
so far I can only report what did not solve the issue :
- I have tried to change all kinds of cache-settings on the server side: No change.
- for a moment I thought I got it. I signed out from iCloud. Afterwards Chrome downloaded the file twice without an issue. Then I made a coffee and afterwards the issue was back. 
- I have switched off all features in Chrome that might interfere: preloading, security features, ad blockers. No change.

**Comment by urapadmin** [comment]
Everything we use these days is so buggy. 
### The solution is:
- update iOS and Chrome (we did that) to the recent version (Currently I get ipadOS 15.7 or so). After that I cannot reproduce the download issue anymore on the green iPad, no matter how often I download, close Chrome, open again, wait in between etc.

Please reopen this if you get the issue again despite a updated iOS version.
