### ISSUE TITLE
move svg from computer to iPad in a way that allows it to be edited

### ISSUE THREAD

**Issue by lbestock** [arch-kiosk/arch-kiosk-office#1779]
Coming out of #1774 I have realized that I don't know how to move an svg from the computer (imagine file from surveyor) onto the iPad in a way that allows it to be edited as vectors, not just an image. I would like to figure that out. 

My first try was airdropping an svg from my mac to the ipad. The ipad gave me an error message "Failed to save item. Save to iCloud Drive instead?" (A problem in and of itself since we don't want cloud active.) When I selected "open with files" it saved the file. I tried this twice. When I saved it to my folder "Touchdraw", opened it in Touchdraw, closed it and then went to the folder to share it with FM, it sent it to FM as a .td2 file. When I saved it to "on my iPad" it saved as an svg that I was able to share as such to FM.

And now I try again with a different svg and tell it to save to files and it doesn't ask me where and while it makes the little noise suggesting it worked, the file is nowhere to be seen. 

Also, even the one that is saved as an svg, when I share it so it opens in Touchdraw the existing vectors are not editable. I can't tell why - it is clearly vectors still since I can zoom in indefinitely and never get pixilated. 

I wonder if this is even possible. If I make a vector file in TD, export it as an svg, reopen it in TD, I can't edit that either.

I don't even know what kind of ticket to make this, but I caught myself making a narrative in my test recording and that was clearly not the right way to track it.

**Comment by lbestock** [comment]
Hmmm I think this is something to do with the Apple Pencil.
I cannot use Touchdraw 2 at all without the Apple Pencil it seems. Even if I have bluetooth off, or the pencil unpaired. As soon as I do use the pencil I can edit the vectors of an svg that came in from outside.
![image](https://user-images.githubusercontent.com/49291909/192575374-6d288bac-f9a0-4cc7-8cd2-0d18b6c64e1d.png)

**Comment by lbestock** [comment]
Wow a documentation issue. This has nothing to do with moving svgs back and forth, and everything to do with pencil woes. If in TD2 the settings: drawing editor: pencil mode is set to "on" then only a pencil will work. If it is off, only a finger will work. If it is adaptive then it will decide what you want to do based on the presence or absence of the pencil and you can edit the svg that you brought in via the method above.

I do still need to know why one of the times I sent an svg to the iPad via airdrop it didn't work, and I need a non-airdrop method of doing this since airdrop has been fickle for us in the field.

**Comment by urapadmin** [comment]
TouchDraw should really be able to open an svg and edit it. Or do they have a native file format?
However, we could use kiosk to transfer the file to the filemaker database. Currently we might be turning svgs into thumbnails but that is just the way it is configured. I can totally leave svgs untouched (or we can even use filepicking to transfer some svgs as svgs and others as thumbnails so that they get properly displayed in FM itself).

**Comment by lbestock** [comment]
Touchdraw really can. It does have a native file format but if I take care of the pencil thing, I can edit a file that I exported as an svg and then opened in TD where it has a .t2d suffix. 

I have now done it by moving an svg in via the finder straight to Touchdraw with a wired connection, too, so no airplay.

But as you say, it should be kiosk. That is back to the old Petra workflow, in terms of surveyors giving files to trench supervisors via kiosk straight to the context they belong to. Then in the field the workflow would be to send the svg from FM to Touchdraw, edit, and send as an svg back to FM. The new svg is then uploaded and synchronized. It has to stay an svg the whole way.

**Comment by lbestock** [comment]
Easily tested. Even though it opens in TD with the extension t2d, if I export it as an svg to FM, it gets there as an svg. And if I then export THAT svg from FM to TD, it gets to TD as an editable vector svg. So it all works just fine, except that we can't see svgs in FM in the preview as previously discussed.

**Comment by lbestock** [comment]
We talked about PDFs as visible in thumbnails (and we talked about an svg viewer). I can now say that PDFs are not a good solution because there is no way to go from a PDF that has been imported in FM to an editable vector file in TD - I lose the option to export from FM to TD when the file is a PDF instead of an SVG.

**Comment by lbestock** [comment]
First trial run through Kiosk.

The file gets to FM without a thumbnail and as something that looks like an SVG.

![image](https://user-images.githubusercontent.com/49291909/192668790-4395cdc1-2e10-4629-98d3-ef3c38b8816f.png)

However, when sent to TD it is not editable as an SVG should be, and in fact does this super weird doubling thing:
![image](https://user-images.githubusercontent.com/49291909/192669034-24e4bf3f-dc81-4e40-b056-c3331c07750f.png)

Neither half of this is editable as a vector file. That it shows up up top as a t2d is immaterial - that happened with editable svgs, too, and it's not a pencil issue, either.

**Comment by lbestock** [comment]
Those two spiders (there was only one in the original file) come into TD as two separate layers, too.

**Comment by lbestock** [comment]
Makes no sense. Another one works. 

As Lutz noted, I needed to check if that svg worked in TD if I transported it elsewise. The answer was no. The plain spider SVG will not airdrop. I can transfer it with the wired connection. When I do that, it opens in TD the same way as when I transported it through kiosk - goes, but then opens as a two-layer file with one super fuzzy layer and the other looking like vectors but not editable. I checked in Illustrator on the mac - it is only one layer in the Illustrator file from which I exported an svg originally.

A different file (created in the same marathon of making spiders in Illustrator so I really don't know what is different about these files) can be airdropped to the iPad and opens editably with just one layer. This one goes through FM just fine, when imported through kiosk, too. It looks exactly the same in FM.
![image](https://user-images.githubusercontent.com/49291909/192672271-56659810-5c1f-4c0e-a630-2c6e5c060b4d.png)
But this one when I export it to TD I can edit as vectors. So Lutz was right it's something about the file itself, but WHAT I cannot see.

**Comment by urapadmin** [comment]
> Hmmm I think this is something to do with the Apple Pencil. I cannot use Touchdraw 2 at all without the Apple Pencil it seems. Even if I have bluetooth off, or the pencil unpaired. As soon as I do use the pencil I can edit the vectors of an svg that came in from outside. ![image](https://user-images.githubusercontent.com/49291909/192575374-6d288bac-f9a0-4cc7-8cd2-0d18b6c64e1d.png)

That's a png. Can't use that :o)
