### ISSUE TITLE
Kiosk Bridge: cannot deal with second file from filemaker

### ISSUE THREAD

**Issue by lbestock** [arch-kiosk/arch-kiosk-office#1786]
Testing #1783 by sending the wrong file through Bridge first and then the right file, I found that I was unable to get Bridge to deal with a second upload.

My steps:
Downloaded the wrong workstation using Chrome, worked in it, sent it to Files.

Downloaded the proper file through Bridge, worked in it.

Went to Files and sent the wrong file to Bridge. Uploaded it. The import failed, of course.

Went to FM and sent the right file to Bridge, and got an unexpected error message: "Can't deal with this file: a file has been sent to KioskBridge but no file was expected in the current state of the dock! File dismissed."

**Comment by urapadmin** [comment]
### KioskBridge 0.2.1
fixed

**Comment by lbestock** [comment]
Works, but the dock doesn't forget that it rejected the last import. It updates the upload time to the proper one, but one needs to know that it's possible to do the import again or one just sees the scary message.

**Comment by lbestock** [comment]
But, if that's a problem at all it isn't this one. I have been through this twice since the fix and it works perfectly.
