### ISSUE TITLE
identifier lists: ustp ran into bugs connected to deleting lists

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#1792]
Deleted lists popped up again next day. 
My hunch is they were deleted but then added again by some other device.

But we should test this together in pvd.

**Comment by lbestock** [comment]
Wasn't this in USTP rather?

**Comment by urapadmin** [comment]
🧠 Covid

**Comment by urapadmin** [comment]
Testing should nonetheless happen on the pvd server

**Comment by luizaogs** [comment]
These are valuelists rather than identification methods, right?

**Comment by urapadmin** [comment]
No, this is about the identifier lists. Since this is not about that they did not generated the correct identifiers but only about issues within the UI for identifier lists, we don't even need to change any identification methods. We just need to fuzz around with adding new records, synchronize, delete some records and then see if the deletion gets synchronized. 

You could start with a single iPad but my hunch is that the issue arises only when more than one ipad is in play at the same time.

**Comment by urapadmin** [comment]
so you might rather want to have a testing party with @lbestock

**Comment by luizaogs** [comment]
Well let me know when you'd like to have that party then, @lbestock.

**Comment by lbestock** [comment]
Testing party! I need to get through an initial sort of the fires in my inbox, and then make some more tea, and then I'm game if you are. 11:30 EDT today. All the cool people will be there.

**Comment by luizaogs** [comment]
Ha, can we rather do 11:30 Chicago time? I have a zoom until then, meh.

**Comment by lbestock** [comment]
Well leaving aside my opinions about zooming on Saturdays (doesn't stop me from doing it sometimes) of course. Maybe I'll have breakfast.

**Comment by luizaogs** [comment]
You should have breakfast.

**Comment by luizaogs** [comment]
Ok, reporting for testing party.

**Comment by lbestock** [comment]
First dance at the testing party:
LDB and LOGS both downloaded a PVD that had been configured with ID lists for contexts. Both created records. LDB then changed the numbers in one of the existing ID lists. Both uploaded and then synchronized.

Both download again and they look the same, having syncrhonized the change in ID partition ldb_ipad.

Second dance:
Both are making some records. LDB deleted the partition logsipad and made a new partition with the same name but different numbers. Upload, synchronize, download.

**Comment by lbestock** [comment]
And we got it! On the second dance. Here is what happened:

When I change an ID list, nothing is problematic.
When I DELETE an ID list and make a new one with the same partition, it looks good and works fine at first. But once I then logout, close, upload, syncrhonize, and download again, the ID lists are messed up. 

I deleted logsipad and recreated it with a different set of numbers. I get both back, so that it looks like this:
![D602C3C3-68DB-4145-97D5-09C34EEB2FD2](https://user-images.githubusercontent.com/49291909/194720851-7ac2b95f-55e7-40d1-af3d-40567a9e93be.jpeg)

It looks like that on both iPads we're testing with. Now LOGS will try to make a locus and should get an error message...

**Comment by luizaogs** [comment]
![IMG_0309](https://user-images.githubusercontent.com/67970402/194720906-14439e79-8df4-43e7-ac64-3561aa2f3758.PNG)

**Comment by lbestock** [comment]
I'm pretty confident this is precisely what USTP was running into, and somewhat amazed that my covid brain was able to tackle anything involving configuration. A nice party.

**Comment by urapadmin** [comment]
much what I expected. So please STOP there and tell me as precisely as you can when you synchronized the second time (the deletion / adding)

**Comment by urapadmin** [comment]
🎈

**Comment by lbestock** [comment]
About 1:50pm EDT 8 October 2022.

**Comment by urapadmin** [comment]
and you both uploaded / imported before the second synchronization, right?

**Comment by lbestock** [comment]
Yes.

**Comment by urapadmin** [comment]
### Kiosk 1.2.7
- this was in fact not a software issue but a configuration issue. But it affects all kiosk installations. For testing purposes I have fixed it for PVD. When the next projects will go into the field they all will have a new version.

**Comment by urapadmin** [comment]
for my records: This was a totally unnecessary "export_dont_truncate" meta setting for "identifier_lists" in the default.dsd3.yml.

**Comment by luizaogs** [comment]
@lbestock testing party round two?

**Comment by lbestock** [comment]
Totally, but not tonight. Is there a time you can tomorrow?

**Comment by luizaogs** [comment]
Yup, whenever.

**Comment by lbestock** [comment]
And then we can hit this one after we have our pottery party.

**Comment by luizaogs** [comment]
Two parties in a day?!

**Comment by lbestock** [comment]
Yeah I have a lecture to write and this sounds much more fun :)

**Comment by luizaogs** [comment]
I'm writing one right now and look forward to being saved by our parties.

**Comment by lbestock** [comment]
OK I've deleted and remade your partition here @luizaogs so when you can, download and let me know what it looks like...

**Comment by luizaogs** [comment]
![IMG_846705A503D7-1](https://user-images.githubusercontent.com/67970402/196047266-7d7bdca9-d834-4133-af93-b81688a343ab.jpeg)

**Comment by lbestock** [comment]
Oh my god that is not what that should look like. It bears no resemblance either to what I had undone nor to what I did again.

**Comment by lbestock** [comment]
I mean, the logsipad that I deleted had the range 900-999. 
And the logsipad that I created had range 100-150.
And the only other partition that should have been there at all was ldbipad and I didn't think that was its range, but I will have to go back to the old file to see that. Meanwhile when I reprepare and download again it also looks wrong, but differently wrong:
![image](https://user-images.githubusercontent.com/49291909/196047771-2452f625-3c75-4627-afec-07f37d6d04f6.png)
Those are the ranges I expected to see, but yours is obviously misnamed. I know what happened there. I started to type and expected to get an autofill option. I didn't get it, so I went to the down arrow to get a list to choose from and chose your partition. But it added the name to what I had already typed. I don't think it looked like that before I syncrhonized, though...

**Comment by luizaogs** [comment]
You're in feature numbers :) Are we doing feature numbers? I assumed context since that's what we did last time.

**Comment by lbestock** [comment]
Oh jesus I didn't even see that... I clearly should not be testing.
Let's do another round. This time I will change in contexts. Wait until I say ready.

**Comment by lbestock** [comment]
Alright yo. Try it again.

**Comment by luizaogs** [comment]
![IMG_0314](https://user-images.githubusercontent.com/67970402/196048422-7b32936c-9887-42a2-ae63-a2d7f7e9f414.PNG)

**Comment by urapadmin** [comment]
There he is again: 🧠

**Comment by lbestock** [comment]
I hate him. And is there an icon for a Middle School cold? 
But this ticket can be closed.

**Comment by lbestock** [comment]
The parties weren't very festive :( 
Zooarchaeology awaits me, alas.

**Comment by luizaogs** [comment]
Sounds a bit better than inclusive teaching, at least.

**Comment by lbestock** [comment]
Teaching about teaching always sounds so horrible to me. Give me dung spherulites over inclusive teaching any day.

**Comment by luizaogs** [comment]
Share the wealth, please. I too would like some dung spherulites right now.

**Comment by urapadmin** [comment]
are Spherulites painful? In combination with dung is sounds like a itching disease to me.

And I think methodological teaching has advantages over intuitive magic :o) But I don't want any enemies around here ...

**Comment by luizaogs** [comment]
Well since I have just decided to wing this class tomorrow (after huffing and puffing about it for what felt like an eternity but was probably not long enough) I’m not sure where I fall on that spectrum 🧙‍♀️
