### ISSUE TITLE
Recording: Navigation

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#1795]
### This is a general description of the new navigation feature:

- Back buttons should go back to exactly the layout and its state from where a user has left it.
- A button shows the navigation history in a list. We call that the "layout history".
- the back button always goes back to the top item of that list and removes it.
- Clicking on one of the items in the layout history navigates to that record and layout and removes that item and all the items on top if it from the layout history.
- the layout history is only populated with items that are connected to a layout change. Moving between records within the same layout should not add anything to the layout history. That makes sure that one does not have to click the back button several times just to undo all the back and forth between records within the same layout.
- in the navigation history popup there is also a "recently viewed" history. That one is populated whenever a new record is shown. Even if it is in the same layout. 
- when clicking on an item in the recently viewed history the item will stay.
- if more than a certain number of items is added to the recently viewed or the layout history, the oldest item will be dropped.
- if a record gets deleted its navigation entry must be deleted as well ❗ We will test the deletion in a second step.

this is not clarified, yet:
- [x] #1865
### here are the single tickets to implement and test:
- [x] #1863 
- [x] #1862 
- [x] #1870
- [x] #1861
- [x] #1889
- [x] #1890
- [x] #1869
- [x] #1871
- [x] #1851
- [x] #1852
- [x] #1853
- [x] #1854
- [x] #1866
- [x] #1874
- [x] #1875
- [x] #1876
- [x] #1867
- [x] #1868
- [x] #1881
- [x] #1882
- [x] #1880
- [x] #1873
- [x] #1860
- [x] #1859
- [x] #1858
- [x] #1857
- [x] #1856
- [x] #1855
- [x] #1884

**Comment by urapadmin** [comment]
### 13.6.3 has first preview (see release notes)
@lbestock @luizaogs What do ya think?

**Comment by urapadmin** [comment]
FYI: you can click in the history to go back more than one step.

**Comment by luizaogs** [comment]
Ooo this is cool. Just to make sure I am using it correctly: it is hierarchical, right? So from collected material the bottom footsteps will always go to the locus (while the top ones go straight to the unit), the footsteps in the locus always go to the unit, those in the unit always go to site, and so on?

**Comment by lbestock** [comment]
Oh interesting, here we can record how we understand it. I have just started futzing, and my understanding was rather that the footsteps in the central part of the header always go to the entity they are next to.

So far I quite like it, but I need more time to use it. The only thing I find a bit difficult currently is that the navigation history is a bit small to hit easily on the mini. I wonder if larger type but fewer lines would help?

**Comment by lbestock** [comment]
Oh wait two other things I note immediately about the navigation history.

If I navigate between loci not from the unit page but rather using the dropdown menu in the locus page itself, the locus I was just in does not get added to the navigation history.

If I use the navigation history to go back to somewhere I was previously, it erases any navigation I had done since I was in that place originally. So if I go from Start Page to CA to CA-005 to a CM, and then click the navigation history, my history tells me CA-005, CA, Start Page. (It hasn't added that CM to it yet because it seems to me that the current place one is gets added only when one leaves it.) But then if I click Start Page in that navigation history, and reenter CA from the start page, the navigation history forgets that I was recently at CA-005 and it never logs that I was in a CM at all, it just says Start Page.

**Comment by lbestock** [comment]
(I like the footsteps as the icon, quite a bit. And I totally tried to go to other layouts because I didn't read the release notes first.)

**Comment by urapadmin** [comment]
> Oh interesting, here we can record how we understand it. I have just started futzing, and my understanding was rather that the footsteps in the central part of the header always go to the entity they are next to.
That is how it is meant to be. Whenever there is a footstep in the future means navigating there and leaving a trace in the navigation history.

> So far I quite like it, but I need more time to use it. The only thing I find a bit difficult currently is that the navigation history is a bit small to hit easily on the mini. I wonder if larger type but fewer lines would help?
That can be done.

**Comment by lbestock** [comment]
It might help more even to have the lines with more space between them than to have the type larger.

**Comment by urapadmin** [comment]
> Oh wait two other things I note immediately about the navigation history.
> 
> If I navigate between loci not from the unit page but rather using the dropdown menu in the locus page itself, the locus I was just in does not get added to the navigation history.
> 

That is be design. as long as you stay within the same layout and have other means to walk between the entities of that layout use them. Otherwise what would happen? You would hop from locus to locus and then want to go back to the unit but you would not be able to. You would have to click the back button 5 times go move back through the loci again. So the back button and the history are meant to trace layout shifts. (It will get hard to maintain that distinction when it comes to searching / navigating).

> If I use the navigation history to go back to somewhere I was previously, it erases any navigation I had done since I was in that place originally. So if I go from Start Page to CA to CA-005 to a CM, and then click the navigation history, my history tells me CA-005, CA, Start Page. (It hasn't added that CM to it yet because it seems to me that the current place one is gets added only when one leaves it.) But then if I click Start Page in that navigation history, and reenter CA from the start page, the navigation history forgets that I was recently at CA-005 and it never logs that I was in a CM at all, it just says Start Page.

That is be design. It works like the back button of the browser. With every step back the last step is removed from the history. When you go several steps back all the steps in between are removed. This is not a list of all the places you have been to, today. 
I do not expect the history to be used too often (how often does anybody click with the right mouse on the back button of a browser?)

If we want something like "your favorite places of today's session" we can think of that as a separate means of navigation.

**Comment by lbestock** [comment]
> That is be design. as long as you stay within the same layout and have other means to walk between the entities of that layout use them. Otherwise what would happen? You would hop from locus to locus and then want to go back to the unit but you would not be able to. You would have to click the back button 5 times go move back through the loci again. So the back button and the history are meant to trace layout shifts. (It will get hard to maintain that distinction when it comes to searching / navigating).
> 
I could go back to the unit easily and would do it by hitting the footsteps next to the unit in the center of the header, not by using the history or back button. I found it weird that a context I had just been in wasn't in the list and I'm not sure I am done finding it weird or convinced it shouldn't be. If I go to CA-001 and look at that locus, and then switch to CA-006, and then go back to CA via the footsteps at the top, my navigation history only shows that I have been in CA-006, not CA-001. I had navigated there, and I had read the locus information there, and it short-circuits my brain to have the navigation history not reflect that and I can imagine that I would want to go there again, remembering that it was the second to last locus I read the description of but not what its number is.

**Comment by urapadmin** [comment]
> > That is be design. as long as you stay within the same layout and have other means to walk between the entities of that layout use them. Otherwise what would happen? You would hop from locus to locus and then want to go back to the unit but you would not be able to. You would have to click the back button 5 times go move back through the loci again. So the back button and the history are meant to trace layout shifts. (It will get hard to maintain that distinction when it comes to searching / navigating).
> 
> I could go back to the unit easily and would do it by hitting the footsteps next to the unit in the center of the header, not by using the history or back button. I found it weird that a context I had just been in wasn't in the list and I'm not sure I am done finding it weird or convinced it shouldn't be. If I go to CA-001 and look at that locus, and then switch to CA-006, and then go back to CA via the footsteps at the top, 

That's not going back that going TO. You are not using the back button.

my navigation history only shows that I have been in CA-006, not CA-001. I had navigated there, and I had read the locus information there, and it short-circuits my brain to have the navigation history not reflect that and I can imagine that I would want to go there again, remembering that it was the second to last locus I read the description of but not what its number is.

We have entered the usual discussion of what users expect from histories in certain situations and I have shown you an example above for a situation that is not yours right now, but could be, and you'd be annoyed and puzzled by the way the history works. This history serves the purpose to go back quickly through layouts (think of the registrar). Cluttering it with everything you have visited at some point defeats that purpose. The back button is tightly connected to that history. That is also why I remove everything you have visited once you have gone back to a point in history.

Again, what you want to do here is a different kind of history for which we might want a separate means of navigation and we might need different terms for it.

**Comment by urapadmin** [comment]
I wonder if it would make more sense to remove the history so that you can't see it and only use the back button. Then you are not puzzled anymore. I don't think you would have been puzzled that going back in the locus view in fact did NOT go back to the locus you had visited before and instead directly to excavation.

**Comment by lbestock** [comment]
Oh that's interesting because put that way I agree, I think I would not have been puzzled, whereas the above longer discussion still left me sputtering that I had been there, it was in my recent history. Hm.

But I am not convinced we should remove it to address this little confusion. I suspect it's more helpful than confusing.

**Comment by luizaogs** [comment]
> Oh interesting, here we can record how we understand it. I have just started futzing, and my understanding was rather that the footsteps in the central part of the header always go to the entity they are next to.

Wow, I did not get that at all. I think because the footsteps are so far away from the entities? Is there a way to move them to the left? Though I guess Laurel got it so maybe that's just a Luiza problem.

**Comment by luizaogs** [comment]
(I think I like the history. Otherwise I might feel like I'm going back blindly, even if it's just through layout shifts.)

**Comment by urapadmin** [comment]
> > Oh interesting, here we can record how we understand it. I have just started futzing, and my understanding was rather that the footsteps in the central part of the header always go to the entity they are next to.
> 
> Wow, I did not get that at all. I think because the footsteps are so far away from the entities? Is there a way to move them to the left? Though I guess Laurel got it so maybe that's just a Luiza problem.

Ja, I saw that problem, but "left" is harder, space-wise. I'll try something.

**Comment by urapadmin** [comment]
### recording 13.6.4
I tried to address your concerns in these two layouts: excavating and locus 
- Luiza gets a dotted line to help with connecting the footsteps with the item they belong to. Does that help?
- Laurel gets an entirely new separate navigation: "recently viewed". The history is now called "layout history". Better terms welcome. It might need some explaining:
   - here we collect each identifier a user visits. Demonstrated in locus (**right now it works only here!**): Using the listbox or the back and forth arrow buttons add all those loci to the recently viewed items but no to the layout history
   - when navigating to a recently viewed item it does not get removed from the recently viewed items
   - after 10 of them each new one replaces the oldest one in the recently viewed list (same in layout history, by the way)
   - the Start page is not added to the recently visited items (to save that slot for something useful). Just in case you wonder.
 
Better?

**Comment by luizaogs** [comment]
Yes! Much better. The dotted lines help those of us who are blind and I like having both histories. Just one thing, and I suspect it happened because you haven't implemented this fully yet but just in case it is a real error: when I click on a locus in the recently viewed I get this error (which is not something that happens when I click on something in the layout history): 

![IMG_0315](https://user-images.githubusercontent.com/67970402/196431465-0a8589fe-6846-4cd2-a245-2b0b0ab08ed6.PNG)

**Comment by urapadmin** [comment]
I cannot easily reproduce that. Can you please try to give me the steps? When I e.g. go to the locus layout and change a bit back and forth with the arrow buttons and then click on one of the created loci in the recently viewed, everything works fine. So, I need your help.

**Comment by luizaogs** [comment]
Umm. I didn’t give you the steps before because it happens literally every single time for me. So I am not sure what the deal is ….

**Comment by luizaogs** [comment]
Logged into FM, went to LA. Clicked on the contexts tab. Clicked on context 511. Went to recently viewed, clicked on LA. Error.

Logged out, logged back in. Clicked on LA. Clicked on contexts. Went to context 511, back to context list, and then went to context LA-017. Opened recently viewed while in LA-017, clicked on 511. Error. 

Etc.

**Comment by urapadmin** [comment]
Thanks, I thought you'd say that. Does not happen in my local version at all, so I guess I better download a version from pvd.

**Comment by urapadmin** [comment]
I am confused. I don't see a context 511. Did you make that one. In LA? I just downloaded your file, went to LA, then to LA-017, then clicked on "LA" in recently viewed and it worked fine.

**Comment by luizaogs** [comment]
Context 511 is one I made when I was testing with Laurel last week. The identifier lists. It should definitely be there.

**Comment by urapadmin** [comment]
sorry, I must have been in the wrong file (sheesh). Got it.

**Comment by urapadmin** [comment]
### recording 13.6.4 because of 🧠 
- should work now and I have added the recently used to collected material.

**Comment by lbestock** [comment]
Slight funniness on creating a new CM from within an old CM record.
![image](https://user-images.githubusercontent.com/49291909/196542828-c615183d-dc84-46f6-891b-2e30373abcdd.png)
That 709G bulk is funny?
If I create a new bulk CM from the CM page it registers only the line 709V(ivory) (for example), not also a 709V also. This is so super minor and I have trouble imagining anyone running into it or finding it a problem but you might want to know it happens.

**Comment by lbestock** [comment]
Hm I just saw the new icon...

**Comment by lbestock** [comment]
Luiza's problem is fixed and I like "recently viewed" a lot.

**Comment by luizaogs** [comment]
Good icon.

**Comment by lbestock** [comment]
Deletion is not working yet. I deleted 709G and it was gone from the list of CM as expected. However it is still present in navigation, and when I go to it via navigation I get this:
![image](https://user-images.githubusercontent.com/49291909/196544063-a7bad10d-022f-4b29-8acc-8085d7b4d410.png)

**Comment by lbestock** [comment]
And then the weird page enters the "recently viewed" (but not the navigation history) as a line that is wonky:
![image](https://user-images.githubusercontent.com/49291909/196544628-36c35ef1-5fc8-4d7f-ad60-1726daea5728.png)

**Comment by lbestock** [comment]
This ticket is getting cluttered - is it still helpful?
New navigation issue:
I have navigated around a bit and built myself a nice navigation history. I am currently in the CM tab of a locus (709 in CA for the current test). I go to navigation history and click on a locus I visited previously (CA-005 in this case). I land on the CM tab for CA-005 instead of the observations page for CA-005, which is not what I expect.

**Comment by urapadmin** [comment]
> This ticket is getting cluttered - is it still helpful?
> 
> New navigation issue:
> 
> I have navigated around a bit and built myself a nice navigation history. I am currently in the CM tab of a locus (709 in CA for the current test). I go to navigation history and click on a locus I visited previously (CA-005 in this case). I land on the CM tab for CA-005 instead of the observations page for CA-005, which is not what I expect.

if you left CA-005 from the CM tab then you go back to the CM tab if you use the layout history. Otherwise this is a bug.

**Comment by lbestock** [comment]
It's a bug. I tested it again using a locus where I had never been into the CM tab.

**Comment by urapadmin** [comment]
> It's a bug. I tested it again using a locus where I had never been into the CM tab.

we are talking about the layout history, not the recently viewed, right? I have tried to reproduce that and failed. Can you please try to give me your steps (as few as needed)?

**Comment by urapadmin** [comment]
> 709V(ivory)

Your description puzzles me but at least I think I can reproduce this: When creating a new cm from within collected material it registeres two records, one with and one without the material. That is, of course, wrong.

**Comment by urapadmin** [comment]
I think I call the concept as it is now accepted. So we can stop using this ticket for testing and instead test navigation per layout. That's where we can test things like deleting a record etc. In the very end we close this ticket here when we call navigation done. (That'll take a while). 

I add a ticket per layout in the body of this ticket for tracking.

**Comment by urapadmin** [comment]
Dear Testers: Watch out for ways to leave a layout that I have overlooked (I just remembered the burger menu and the home button)

**Comment by urapadmin** [comment]
@lbestock, @luizaogs: Okay, this says it is finished, now. 
I'll roll out 13.7 next (with #1897) and suggest you both navigate one more time like there is no tomorrow. And after that I can roll it out to the field projects.

**Comment by urapadmin** [comment]
### recording 13.7
that's rolled out now on test. Give it a last thorough prodding, please. And please use ipads in particular.

**Comment by luizaogs** [comment]
Ok I have poked and prodded and I can't find anything wrong with it. It's really great. (But I've also been poking and prodding it incessantly for a week now, so if there is something still wrong Laurel might be quicker in spotting it!)

**Comment by lbestock** [comment]
So far only one ticket #1901 coming out of poking and prodding (less incessantly and not as systematically as I would want). I note that there is no navigation in the locus details layouts. I don't think it is necessary - the back button goes to the locus and really if ever there is a place from which you just want to go back one that is it. But I'm not sure if that was intentional or overlooked, so I note it here.

**Comment by urapadmin** [comment]
> So far only one ticket #1901 coming out of poking and prodding (less incessantly and not as systematically as I would want). I note that there is no navigation in the locus details layouts. I don't think it is necessary - the back button goes to the locus and really if ever there is a place from which you just want to go back one that is it. But I'm not sure if that was intentional or overlooked, so I note it here.

intentional. The locus detail layouts are really meant to be sub-layouts that could as well be pop-ups.

**Comment by urapadmin** [comment]
@lbestock please tell me when you are done testing. I will attend to everything you find at once.

**Comment by lbestock** [comment]
When navigating back from warecode pottery to a context using navigation for some reason the Filemaker tools that are usually hidden are present and clickable:
![image](https://user-images.githubusercontent.com/49291909/198904640-f7ca7151-c6d6-456a-9b83-30a2aee1548c.png)
They go away again if I go back to start, and do not reappear if I go to the context again.
If I use the back button from the warecode pottery and then use navigation to get to the context I do not have the same problem. And if I navigate from warecode to the trench instead of a locus, I also do not encounter the problem, so it seems to be something specific to going from warecode to locus via navigation (recently viewed in this case, because it's my favorite).

**Comment by lbestock** [comment]
There is no navigation in the image gallery, though the image gallery does show up in recently viewed. This strikes me as proper but I note it in case it was not intentional.

**Comment by lbestock** [comment]
Neither team members nor define tags results in a line in navigation. I think this is fine, too, just noting everything I observe.

**Comment by lbestock** [comment]
One place where there is no access to my very appreciated recently viewed and where, in fact, I keep finding I want it, is the start page itself. My wanting it here may be a testing thing, though.

**Comment by lbestock** [comment]
I think I am done with this. I made the one weirdness I noted it's own ticket: #1904. I caught you a potential doozy in #1905, but it's not about navigation. The questions in comments above in this ticket are about intention of places where navigation is missing, but none of them strike me as problematic. If that is the case, this can be closed from my perspective.

**Comment by urapadmin** [comment]
> One place where there is no access to my very appreciated recently viewed and where, in fact, I keep finding I want it, is the start page itself. My wanting it here may be a testing thing, though.

You already have an orange footprint button on the start page for testing. Needs test mode on, though.
