### ISSUE TITLE
locus photos / collected material photos: New issues with the image list

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#1796]
USTP reported that they hit a 12 images limit in context/collected material (In fact I do suspect they refer rather to the photos in collected material). Since there is no such thing I suspect new FileMaker horrors with images and image lists. Usually we only test with up to 5 images. Now we need a test with a bucket load of images to see what filemaker is doing.

A quick test on my ipad mini showed already horrible behaviour (also: slow!)

**Comment by luizaogs** [comment]
Hm...I'm at 20 images in collected material and all is working just fine (other than #1805). Since the issue they reported was at 12 I don't think I am having it? I will now look at locus images.

**Comment by luizaogs** [comment]
Yeah so I'm also at 20 images in locus photos and everything is still fine. Do I finally have the only iPad that works properly? That would be a fun change.

**Comment by luizaogs** [comment]
Well judging from #1806 and #1807 maybe something is indeed rotten in the state of Denmark.

**Comment by luizaogs** [comment]
Lutz, is there anything else that can be done here for now?

**Comment by urapadmin** [comment]
only more testing, honestly. If everything works fine on your ipad then @lbestock has to try.

**Comment by luizaogs** [comment]
Yeah, I haven't had any problems.

**Comment by lbestock** [comment]
I have tried this on two of my iPads now, including a big one that is 6th generation, so not a spring chicken. I have not seen it.

**Comment by urapadmin** [comment]
I'll look at it with my own ipad once more. I remember having been puzzled by the cut-off digits in the image counters. But that is fixed.

**Comment by urapadmin** [comment]
we have to give this back to USTP for clarification and their own tests.
