### ISSUE TITLE
registration status: Make the "Done" Status accessible for registrars in collected material

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#1797]
- There might even already be a configuration key
- besides: It turns out that USTP only use "DONE" and not "TODO". We could make the use of TODO configurable. 
- PASU requested this, too. But they do use TODO and prefer the popups over the codes (in fact Anna asked to get rid of the codes)

**Comment by urapadmin** [comment]
- yes, there is a configuration key that makes the registration code accessible: "show_registration_status_in_cm". 
-

**Comment by lbestock** [comment]
How can I add a new check box to the pop-over? I can make a new code and give it a text that shows up properly, but I can't see how to turn it into a checkbox.

**Comment by urapadmin** [comment]
that should be in the user's manual :o) #35 
But believe me, I was about to make a ticket myself because I thought it might not be possible to do that with configuration.
Another instance where an information wasn't in the user's manual AND we both would not have looked it up. How far the latter is connected to assuming the former, I can't say.

**Comment by urapadmin** [comment]
Wait, I am not sure I understand. 
If you add lines to registration_codes_done (registration_codes_todo, respectively) that should add a new checkbox to the popover (but in your version not to the listbox in the collected material list). What does not happen is that the line adds something to the help text in the checkbox popover. That is definitely worth a ticket: #1930

**Comment by lbestock** [comment]
Yes, that does it!
