### ISSUE TITLE
going from ceramic photos to ceramic list takes you to context photos rather than ceramics

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#1800]
I suspect ceramic photos here means collected material photos. 
We were not sure what that actually means, so @Tfranconi wanted to ask the one who brought it up and @lbestock meant to remember having seen something like that. Perhaps @luizaogs can remember something like that?

**Comment by luizaogs** [comment]
Hmm no, and I just tried to replicate it and failed.

**Comment by urapadmin** [comment]
laurel might have had something like this #1326 in mind? I, too, have a bit the feeling I have seen something with locus photos but the Covid 🧠 is foggy about it.

**Comment by urapadmin** [comment]
### recording 13.6.7
This might be just gone now that we have the new navigation in registration and everywhere else. 
Since nobody really figured where the problem actually is, we just wait for Tyler to report it again once the new recording version is rolled out to USTP.
