### ISSUE TITLE
locus/collected material photos: second digit missing in image counter

### ISSUE THREAD

**Issue by luizaogs** [arch-kiosk/arch-kiosk-office#1805]
Comes out of testing #1796. The image below is image 10 (so the counter should show 1/10) but the image counter shows 1/1 because the ones digit isn't there, which is confusing. 

![IMG_0303](https://user-images.githubusercontent.com/67970402/194707462-8744fc0b-c598-4979-ab71-0eaf614fd93e.PNG)

**Comment by luizaogs** [comment]
Ah in fact we're missing that digit both in the first and second numbers in the image counter. For example, I now have 12 images in the list but everything after 9/1 (which should be 9/10) is 1/1, 1/1, 1/1.

**Comment by luizaogs** [comment]
Same issue with the image counters in locus photos (I assume it will be the case everywhere else, too).

**Comment by urapadmin** [comment]
### recording 13.6.1
Using a slightly different approach here now. So please keep an eye on it. 
If it happens every now and then that the display of the image number/count does not update, a click somewhere in the header or outside of the image list should make filemaker refresh and I accept that for the time being.

**Comment by luizaogs** [comment]
The counters themselves work fine, though I noted an issue regarding su ceramics in #1833. I can't test urap pottery because PVD is not configured for it and my brain is not working enough to try configuring that right now...

**Comment by lbestock** [comment]
Goodness, let's see if mine is. We really need a "how to" guide to set up ceramics processing in the different ways because it is so complicated I always have to look at the configuration of an existing database to figure it out.

**Comment by urapadmin** [comment]
This is the hardest because it IS complicated: #1131 
You have to got to modules, ceramic_module and add "pottery_processing" to get the warecode pottery module. That should do for this test.

**Comment by luizaogs** [comment]
Ha well if you manage it we should maybe do poor #1760 as well.

**Comment by lbestock** [comment]
I'm going to write a guide while I'm at it that shows the settings for USTP, PASU, and URAP because I do always forget how very many places it needs changes. @luizaogs, hold tight and I'll be with you soon.

**Comment by lbestock** [comment]
Ready for this one.

**Comment by luizaogs** [comment]
Ok, the counters themselves work just fine in warecode pottery though the same scrolling issue as reported in #1833 for su ceramics also happens. Since the counters themselves are fine, I will close this one.
