### ISSUE TITLE
flashing background window when going into a locus from locus list

### ISSUE THREAD

**Issue by luizaogs** [arch-kiosk/arch-kiosk-office#1806]
Comes out of testing #1796 so I wonder if it is related since I haven't seen this for a long time. But when I left the collected materials list I went to the locus list to try out locus photos next, and when I clicked on the first locus in that list (LA-024) I got a weird flashing of a background window (with a table of some sort). It went away on its own in a flash, but I assume it isn't supposed to show up.

**Comment by luizaogs** [comment]
Leaving that locus and going back into it from the locus list did not give me the same issue.

**Comment by luizaogs** [comment]
I also haven't gotten it going into other loci from the list, though some flash more than others.

**Comment by luizaogs** [comment]
Yep, it worked fine.

**Comment by urapadmin** [comment]
can you remember where exactly it occurred? When the locus layout got visible or when you were still in the list?

**Comment by luizaogs** [comment]
It was exactly when I clicked on the locus button. So when I was in the list, moving to the locus form.

**Comment by urapadmin** [comment]
@lbestock @luizaogs 
Is this annoying? Do you encounter it often enough so that you could even tell if any precautions I take make it better?
I move this to under observation until you insist tackling it.

**Comment by luizaogs** [comment]
No, I do not encounter it often. I think I only opened a ticket because I never see it, so it seemed anomalous.

**Comment by lbestock** [comment]
I don't encounter it often at all either. Whenever I encounter the background window it freaks me out, but this isn't usual and I wouldn't notice if you did anything.

**Comment by urapadmin** [comment]
degraded to a hiccup. Please report again it it occurs more often
