### ISSUE TITLE
back arrow disappears in locus form and screen freezes

### ISSUE THREAD

**Issue by luizaogs** [arch-kiosk/arch-kiosk-office#1807]
Again, not sure if this is due to adding a bunch of images when testing #1796 because I have never seen it before, but I was just trying to leave the locus photos list and the back arrow disappeared.

Ah ok, and then I clicked on the QC warning to see if that would work and um got this: 

![IMG_0305](https://user-images.githubusercontent.com/67970402/194708328-66110c4b-81e1-4de2-8887-fff7d22edc7e.PNG)

It doesn't go away on its own. I then closed FM and came back to the same locus and I could go in normally, the back arrow was back, and all of my 20 images were there.

**Comment by urapadmin** [comment]
That looks more like a quality control issue than anything related to images. USTP did not have QC switched on, so I think we should test the specific image issue with QC turned off.

**Comment by urapadmin** [comment]
May I ask for your current iOS/FM Go Versions?

**Comment by luizaogs** [comment]
iOS 15.7, FM Go 19.5.2.200.

**Comment by urapadmin** [comment]
@lbestock, @luizaogs: Independent of the image issues from the field we are trying to reproduce, can you reproduce this reliably some way?

**Comment by lbestock** [comment]
Pff I've never even seen it that I recall. I will keep my eye open.

**Comment by luizaogs** [comment]
Hm no, I just replicated all of my steps and it didn't happen again.

**Comment by urapadmin** [comment]
I am inclined to regard it as one of those hiccups filemaker has randomly. 
I'll move it to the observatory.

**Comment by luizaogs** [comment]
Can we close this? I haven't seen it in years. (Instead of writing the lecture I should be writing I felt like closing tickets.)

**Comment by urapadmin** [comment]
I think it is a good strategy to turn to achievable things when one is in a gap of achieving others. 
So go for it!

**Comment by luizaogs** [comment]
wooo
