### ISSUE TITLE
"Potential File Handling Error" should perhaps pop up only once

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#1810]
or something like "don't show this again until the next download" or so would make the life of those easier who work on a file off-season for a while

**Comment by urapadmin** [comment]
### recording 13.5..6
- [ ] The popup message indicating that the database has a "don't show this again until next download" or so
- [ ] if not checked, the popup keeps reappearing whenever the database is started again
- [ ] once checked the popup will not come up again when the same database is reopened
- [ ] after importing the data, synchronizing and downloading again the popup should reappear. The checkbox setting does not synchronize!

**Comment by luizaogs** [comment]
Hmm I thought this was the "this database is more than 18h old" warning but now I'm not sure because I don't get a pop up for it at all? I see it when logging in but it's a static warning and then I see it on the start page, but that is it. Am I looking at the wrong thing?

**Comment by urapadmin** [comment]
ja, that is the normal message that will not stop reminding you. Here we are talking about an annoying popup in your face that you really want to get rid of after a while. But, I just saw that there is another configuration key that might be set differently for PVD than for real projects:
"warn_db_age" under "general" might be set to "nope" on PVD?

**Comment by urapadmin** [comment]
Also noteworthy: system/message_inhibitors_per_download is where it gets registered that you set the "don't show this again" checkbox. If you erase the contents of that key you will get it again on startup.

**Comment by urapadmin** [comment]
ah. Found a but that keeps it from coming up at all again. On it ...

**Comment by luizaogs** [comment]
Ah ok. Because I just checked and that configuration key says "yup" on PVD so I guess it should have showed up.

**Comment by urapadmin** [comment]
### kiosk 13.6.2
Ja, that was a conundrum. I had to change this thoroughly, so now even the static message on the start screen might be affected.
- the static message must always be there (if the database is old, that is)
- the popup comes up only when the database is opened (and not again when going back to the start layout)
- the popup can be suppressed by the checkbox "don'T show ..."
- after that the static message keeps being there but the popup does not come up again after opening the database
- when downloading a new version the popup should come up again

**Comment by luizaogs** [comment]
(talking to myself: you need to test this over a period of a couple of days, so do the first few checkboxes tomorrow with the database you just downloaded and then upload and download again for the last couple)

**Comment by luizaogs** [comment]
Hm, I am still not getting the pop up (even if warn_db_age is set to yup). The static warning works fine.

(For the purposes of the user manual, the key that controls the static warning is actually show_age_warning)

**Comment by urapadmin** [comment]
> Hm, I am still not getting the pop up (even if warn_db_age is set to yup). The static warning works fine.
> 
> (For the purposes of the user manual, the key that controls the static warning is actually show_age_warning)

that is correct- warn_db_age controls the pop up and show_age_warning controls the static message on the start page

**Comment by urapadmin** [comment]
### 13.6.12
Please try again. I had clicked the checkbox that suppresses the popup in my development database and that became the default when rolling out.

**Comment by luizaogs** [comment]
Works.
