### ISSUE TITLE
"hyperlinks" from text fields to identifiers in FileMaker

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#1815]
this came out of the PASU meeting X/22, requested by Anna.
Navigating between narratives (also locus descriptions etc.) and loci / cm is hard. Jumping back and forth between things is simply not what the recording is made for, currently. 

While the real solution to any of this would be an analytic module in Kiosk itself, this here is about how to make the recording itself support such a workflow.

- [x] it would need #1795 first
- [x] #2088 
- [x] #2089

**Comment by urapadmin** [comment]
what about a simple button that can be placed next to a text field that analyzes the text field for identifiers and shows a list of them to jump to?

**Comment by urapadmin** [comment]
### recording 14.7
We refer to this as "reference navigation".
- available in unit narratives, locus description, locus interpretation, collected material description.
- Any other places where it would make sense?
- test this with ustp: USTP can have the same identifier twice (if I am not mistaken), once as locus and once as collected material. If that isn't the case in USTP anymore you can also just try to simulate it in PVD: Give the same identifier to a collected material and a locus (e.g. by using temporary free input or changing the identification method to "free input"). If that identifier is in a text, the reference navigation should list both destinations.
-

**Comment by luizaogs** [comment]
Hmm I don't think this is working. I see the footsteps and the "go to..." popup pops up, but the identifiers don't appear in it. And yes, LA-014 and LA-015 are real locus identifiers in the recording system.

<img width="1021" alt="Screenshot 2023-05-03 at 9 10 40 PM" src="https://user-images.githubusercontent.com/67970402/236096139-87c51ccf-7ab7-487f-9abb-18090831090a.png">

<img width="1018" alt="Screenshot 2023-05-03 at 9 10 50 PM" src="https://user-images.githubusercontent.com/67970402/236096147-67b4b082-1d4c-4d33-b467-3d94bfde960c.png">

**Comment by urapadmin** [comment]
That's bad. 
- However, even once I will have fixed the fact that the identifiers have not been found, I note also that if candidates for identifiers get found that aren't actually identifiers (Something like doodl-oo or a quote in double quotations marks) it must not show an empty list. Instead it must show a yellow sorry message.

**Comment by urapadmin** [comment]
I downloaded your workstation, it works for me, so I suspect we have Browser problems here (this is using a browser internally). What OS are you on? MacOS? Have you tried the iPad?

**Comment by lbestock** [comment]
I get this problem too on my iPad. iOS 16.3.1.
I get the yellow no pun intended message if there are no identifiers. If there ARE identifiers, I get a blank list like @luizaogs.

**Comment by lbestock** [comment]
And I see the same behavior on my MacBook.

**Comment by luizaogs** [comment]
Yeah, same for getting the yellow message on my Mac if there are no identifiers. Mac OS 13.3.1.

**Comment by urapadmin** [comment]
### recording 14.8.1
  - Safari! Hate it. It might work now.
  - what also works now is that if there are only identifierish things in the text, so looks like an identifier but does not exist as one, then the yellow page comes up to. It is ever so lightly different so that you can see your are testing the right thing:  ![image](https://user-images.githubusercontent.com/38838314/236290779-643f69e8-59b8-4f22-82ec-81dadb613f43.png)

**Comment by luizaogs** [comment]
Alright yes, the identifiers do show up now. I do not currently have the ability to test this thoroughly so I won't try, but I wanted to let you know that it seems (at least superficially) to be working.

**Comment by urapadmin** [comment]
You need to have this 8th of May behind you! 👀

**Comment by luizaogs** [comment]
🫠 (that’s me, slowly disintegrating)

**Comment by urapadmin** [comment]
🍪

**Comment by luizaogs** [comment]
I guess the idea here is that what's an identifier will be determined by project in the config? Because in PVD for instance, some CM have two hyphens in the identifier, so the reference navigation only catches the first part of the identifier (the locus), since that's the stuff after the first hyphen: 

![IMG_0338](https://user-images.githubusercontent.com/67970402/236691193-149546c8-6550-47f4-843a-acc0bd223685.PNG)

![IMG_0339](https://user-images.githubusercontent.com/67970402/236691186-e3c0e029-6f9b-4fd4-b965-9cdb9c7c7eb8.PNG)

**Comment by luizaogs** [comment]
If I use the reference navigation in a locus interpretation to go a locus mentioned in that interpretation, I get sent to that new locus' interpretation tab. Is that intended? 

Concrete example: 
Interpretation tab of LA-018
I added LA-014 to that text box
Use reference navigation to go to LA-014
Arrive in LA-014's interpretation tab, rather than the locus home page

**Comment by luizaogs** [comment]
Could it make sense in survey interpretation? Or feature interpretation, actually, since there isn't a way to link features.

**Comment by luizaogs** [comment]
Besides the questions above and #2101 I think this is working well.

**Comment by lbestock** [comment]
Excuse me while I butt in on this ticket to point out that one of you turned in a dissertation today and the other said over morning coffee that he was in danger of being a workaholic and would take a break today. And that it is definitely gorgeous in Providence and the weather app thinks it is gorgeous in Chicago, too.

**Comment by urapadmin** [comment]
😛

**Comment by luizaogs** [comment]
Enjoy the decent (not gorgeous) day would involve leaving my couch, which is not something I currently have the energy to do :) Lutz, take a break.

**Comment by urapadmin** [comment]
There is also a KAMBE VM. That has to be in the post office tomorrow, so this is not a holiday for me, anyways. and Luiza found what looks like real bugs, so ... But I'll have a break with Bob 🐱

**Comment by lbestock** [comment]
You'll have to kidnap him from my desk...

**Comment by urapadmin** [comment]
> I guess the idea here is that what's an identifier will be determined by project in the config? Because in PVD for instance, some CM have two hyphens in the identifier, so the reference navigation only catches the first part of the identifier (the locus), since that's the stuff after the first hyphen:
> 
> (so I assume it should catch LA-014-1 rather than just LA-014)
> 
> ![IMG_0338](https://user-images.githubusercontent.com/67970402/236691193-149546c8-6550-47f4-843a-acc0bd223685.PNG)
> 
> ![IMG_0339](https://user-images.githubusercontent.com/67970402/236691186-e3c0e029-6f9b-4fd4-b965-9cdb9c7c7eb8.PNG)

This should be fixed with 14.8.3

**Comment by urapadmin** [comment]
### 14.8.3
- Something like LA-13-2 should be recognize in its full length and not only up to the first dash

**Comment by luizaogs** [comment]
Yep.
