### ISSUE TITLE
define default todo registration codes depending on material type

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#1817]
As there is a typical workflow for certain materials / collected material types we could create default registration codes for every collected material.
Ceramics need to be washed, small finds need to be photographed, etc. ..
- see #1816 and #1797

**Comment by urapadmin** [comment]
- should be added (added because there could already be registration codes set for the collected material) once the material type is set or changed.
- registration codes will not be deleted (e.g. because some material type does not default to the same todo codes of a formerly selected material type)

**Comment by urapadmin** [comment]
you can also test if this covers these urap requirements: #34

**Comment by luizaogs** [comment]
I'm feeling a bit stupid but should I know what the B stands for? I don't see a B in any of the value lists.

**Comment by luizaogs** [comment]
In PVD we have these set for materials: 

<img width="129" alt="Screenshot 2022-11-20 at 7 19 52 PM" src="https://user-images.githubusercontent.com/67970402/202939160-4090581a-71fe-42fd-b0f1-402e573dcb1b.png">

I first had a small find set as beads, and then changed it to ceramic, and ended up with this code combination: 

<img width="356" alt="Screenshot 2022-11-20 at 7 25 21 PM" src="https://user-images.githubusercontent.com/67970402/202939266-0dc94727-d089-46f4-941e-2cb9efad3125.png">

Is this what you intended to happen? It seemed to me like the 5th bullet point above says so, but I'm a bit confused so wanted to check.

**Comment by luizaogs** [comment]
> * in both default settings a combination of codes lists the codes seprated by comma. E.g. B,R or B,C!. This is because theoretically codes can have more than two digits (see C!, but adding a ! should be the only reason to make a code having two digits).

Currently this is not the case and it seems to be working fine. Not sure if it should.

**Comment by luizaogs** [comment]
Everything else seems to be working.

**Comment by urapadmin** [comment]
> * in both default settings a combination of codes lists the codes seprated by comma. E.g. B,R or B,C!. This is because theoretically codes can have more than two digits (see C!, but adding a ! should be the only reason to make a code having two digits).

what is not the case currently?

**Comment by urapadmin** [comment]
> In PVD we have these set for materials:
> 
> <img alt="Screenshot 2022-11-20 at 7 19 52 PM" width="129" src="https://user-images.githubusercontent.com/67970402/202939160-4090581a-71fe-42fd-b0f1-402e573dcb1b.png">
> 
> I first had a small find set as beads, and then changed it to ceramic, and ended up with this code combination:
> 
> <img alt="Screenshot 2022-11-20 at 7 25 21 PM" width="356" src="https://user-images.githubusercontent.com/67970402/202939266-0dc94727-d089-46f4-941e-2cb9efad3125.png">
> 
> Is this what you intended to happen? It seemed to me like the 5th bullet point above says so, but I'm a bit confused so wanted to check.

no, the double W is redundant. It would have been correct if you had first made a ceramic (WC) and then switched to bead (W) and the result had been WC because the C would stay from the former type.

**Comment by luizaogs** [comment]
> > * in both default settings a combination of codes lists the codes seprated by comma. E.g. B,R or B,C!. This is because theoretically codes can have more than two digits (see C!, but adding a ! should be the only reason to make a code having two digits).
> 
> what is not the case currently?

There are no commas right now, anywhere.

**Comment by urapadmin** [comment]
ah! Well, then the configuration is wrong! it must be ceramics=W,C and beads=W. Sorry, I didn't see it. 
And that might explain the WWC issue above. In that case WC is treated as a single code which is different from W. 
Please try again with the correct comma.

**Comment by luizaogs** [comment]
Ok yes, with the commas the change from beads to ceramic leads to BRPWC, which seems correct.

**Comment by urapadmin** [comment]
I don't know. Might have been test stuff from former tests? The codes are really entirely up to whatever somebody chooses to configure. My "B" in my instructions has no meaning. It is a registration code I use in my very own project. It stands for, erm, bullsh... or brushit ... For the recording system it is all just some letters without meaning.
Except for H and R. They are hard-coded into the views.

**Comment by urapadmin** [comment]
It's abstract :o) That's how I like my stuff.

**Comment by luizaogs** [comment]
Oh. I thought they were supposed to be doing something specific and I was missing it :) Nevermind, then. This is working.

**Comment by lbestock** [comment]
Configuring URAP.
I did this on my mac after uploading my patch and feeling appreciative of Kiosk.
The current registration_code_cm_type_defaults is:
bulk=H small_find_H, P, R sample=H, R
This is the expected actual configuration for URAP.
But making a small find has not triggered the application of any registration todo codes that I can see in the CM record (whereas it worked properly for bulk).

**Comment by lbestock** [comment]
Oh whoops, that is not material type...

**Comment by luizaogs** [comment]
That’s so weird, it worked in PVD.

**Comment by luizaogs** [comment]
Typing everything in FM in URAP worked.
