### ISSUE TITLE
PASU: Report for sherds (special ceramics) on the basis of some pre-selection

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#1821]
Jeremy wants to assemble a few of the most precious finds in the special ceramic module in a report.
Not entirely sure how to do that. 
- Printing (to pdf) from within filemaker is possible but not what we usually do. Also: Filemaker has much lower resolution images than kiosk.
- It would be better to run the report in Kiosk with the reporting module (first time I would include images) but based on 
- a preselection made in either Filemaker (but that would need synchronization before the report can run ... hm) or 
- a selection made in Kiosk (which would need a useful user interface to make the selection - much work for the task).

**Comment by urapadmin** [comment]
see also #1546

**Comment by urapadmin** [comment]
waiting for PASU here. They want to check this out

**Comment by urapadmin** [comment]
But I should look at my options in the meantime: How to I get images into a pdf?

**Comment by urapadmin** [comment]
I don't. I decided that in fact HTML would be a much easier way to run a report for this.

**Comment by urapadmin** [comment]
so this here shall be a special version of the more generally useful html reporting dock: #2226

**Comment by urapadmin** [comment]
#### kiosk 1.5.7 on pasu-test
- the sherd report is there
- all other reports need to be tested as well. 
- does the ZIP option still appear for the other reports (no zip for the sherd report)?

**Comment by luizaogs** [comment]
Still can't test this with my current PASU-test permissions. Not that I'm sure I know how to test it, mind you.

**Comment by urapadmin** [comment]
oh, I am sorry, I believed you and Laurel had fixed that the other day. I have not made you an admin but an operator with the privileges to operate reporting and download files. Let me know if you still can't access something.

**Comment by luizaogs** [comment]
I can't download :)

**Comment by luizaogs** [comment]
Oh wait I don't need to download the sherd report, do I? I can view it.

**Comment by luizaogs** [comment]
Just going down the fields in the sherd form in FM you seem to be missing two in the report, but I don't know if that was purposeful. They are "Osservazioni sulla Manifattura" and "measurements".

**Comment by luizaogs** [comment]
Another thing: the report has running text for categories even if the entry in FM has different lines. Don't know if that's an issue. 

The form and comparison field in the report looks like this: 
<img width="1255" alt="Screenshot 2023-07-28 at 8 33 15 AM" src="https://github.com/arch-kiosk/arch-kiosk-office/assets/67970402/3c6a43ef-bbb8-43f5-90bc-87b76b2d10f3">

But in FM it looks like this: 
<img width="756" alt="Screenshot 2023-07-28 at 8 33 50 AM" src="https://github.com/arch-kiosk/arch-kiosk-office/assets/67970402/d18f6bc8-9dee-4a81-a565-970be2d79f5b">

**Comment by luizaogs** [comment]
Ok the above issue with the running text when it's supposed to be different lines is frequent and confusing, but I don't know if you can do anything about it.

**Comment by luizaogs** [comment]
The single fragment reports have the same issues as the ones reported above for the report with all fragments belonging to the material id, as expected.

**Comment by luizaogs** [comment]
And just to make sure: I should not have the option to download this one, correct? Only view?

**Comment by urapadmin** [comment]
> Oh wait I don't need to download the sherd report, do I? I can view it.

Correct, the sherd report is different from the others in that it isn't file pased. That's why it has a view instead of a download. If one would want a pdf one would have to print the page to a pdf.

**Comment by urapadmin** [comment]
> Just going down the fields in the sherd form in FM you seem to be missing two in the report, but I don't know if that was purposeful. They are "Osservazioni sulla Manifattura" and "measurements".

only fields with actual input are shown in the report. Is it possible that those two are empty in your example?

**Comment by urapadmin** [comment]
> Another thing: the report has running text for categories even if the entry in FM has different lines. Don't know if that's an issue.
> 
> The form and comparison field in the report looks like this: <img alt="Screenshot 2023-07-28 at 8 33 15 AM" width="1255" src="https://user-images.githubusercontent.com/67970402/256810791-3c6a43ef-bbb8-43f5-90bc-87b76b2d10f3.png">
> 
> But in FM it looks like this: <img alt="Screenshot 2023-07-28 at 8 33 50 AM" width="756" src="https://user-images.githubusercontent.com/67970402/256810850-d18f6bc8-9dee-4a81-a565-970be2d79f5b.png">
> 
> I see the same thing in this sherd's "to draw" entry in the report.

Yes, that is relevant:
- #2232

**Comment by urapadmin** [comment]
> > > Just going down the fields in the sherd form in FM you seem to be missing two in the report, but I don't know if that was purposeful. They are "Osservazioni sulla Manifattura" and "measurements".
> > 
> > 
> > only fields with actual input are shown in the report. Is it possible that those two are empty in your example?
> 
> Nope. I saw this repeatedly and most of the sherds had information in those fields.
in that case:
- #2233

**Comment by lbestock** [comment]
This looks good to me in the browser but when I print it as a PDF the image size is so crazy big that it's one image per page and no image shares a page with the text info. So an 18 sherd report becomes a 77 page PDF, and the connection between image and text is less useful.

**Comment by urapadmin** [comment]
Ja, that's the moment where I wish I understood what the actual users wan to do with it. They can't really want to print it. I suppose they will rather copy the images or so. Who knows.
However, I will try to address the printed page in particular. I think that is possible within limits.

**Comment by lbestock** [comment]
Their inspector can want them to print it. Rule nothing out.

**Comment by urapadmin** [comment]
I have changed it a bit so that two images are next to each other. I think it is better now, no?

**Comment by lbestock** [comment]
Definitely better - we're down to 53 pages from 77. There are still no images on the pages with text, which is a bit hard for me to deal with. If I were the one receiving these reports and if getting a photo on the text page is not possible I would ask if it could be made so the fragment number is on every page of the report that relates to that fragment, so at least when looking at photos I could be sure. However, I'm not and the strategy of waiting until asked, particularly on a report for one project, makes so much sense.

**Comment by urapadmin** [comment]
Text + Images:
![grafik](https://github.com/arch-kiosk/arch-kiosk-office/assets/38838314/670d8fd1-6377-4cec-ae4f-5246b50259e5)

**Comment by urapadmin** [comment]
Safari?

**Comment by urapadmin** [comment]
It can also help to play around a but with the page margins or something like that. Printing from a browser is a fiddely business.

**Comment by lbestock** [comment]
Ah let me mess around.

**Comment by lbestock** [comment]
Chrome. And yup, I have made it look like yours and now I am satisfied, full stop. 32 pages.
