### ISSUE TITLE
Rethink timestamps for found / recorded / created / modified etc.

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#1824]
this comes out of a PASU meeting X/2022

Their identifiers start with a prefix "SU22-" to connect a locus or an object in a certain season. 
- Since "SU22-" is part of the identifier it gets created when the context gets created. The collected material identifier just picks up the context identifier and adds a material. So the context "SU22-D244" was created in 2022 and the material "SU22-D244G" was found in that context. 

The implications are:
If an object or bag of bulk is found in context SU22-D244 in the year 22 but is analysed and recorded in a study season 2023 It would still keep the "SU22" prefix if it was created in the SU22- context. So a small find SF0 in that context would be SU22-D244SF0 although it might get created not before 2023.

There is no way to have a SU23- collected material in an SU22- context. PASU wants to create a new SU23-D244 context for material that is found in 2023. With the result that we have two context D244: One in 2022 and one in 2023.

BUT even though an "SU22" collected material has SU22 in its identifier, if it gets created in the study season 2023, its creation / modification date is 2023. And that is what I'd use for instance when I make a finds report. 

So the question for PASU is even: What is the right thing to do when it comes to reporting, On what basis should I include / exclude records? On the basis of the actual timestamps in the collected material record (creation date) or on the basis of the SU prefix?

The general question is: Should we not be more explicit about it and give all records a set of timestamps that clearly indicate:
- when was it found (in locus that would be the "date opened", in collected material we don't have any such thing) 
- when was it stored (if such a thing gets a date)
- when was it recorded (should be our current technical creation date)
- when was it last modified (our current technical modified date)

I would advocate for not using any prefix for that in an identifier but rather rely on the explicit dates. When it comes to labeling things It is always possible to put more than one datum on a label: identifier would be the "D244" for a locus and the "date opened" indicates the year it was created. That should be written on the label, as well. It is also not a problem to show a "label view" that combines things that should go on a label.

The goal is to not have two different loci SU22-D244 and SU23-D244 just because we need to keep the collected materials separate by year for the superintendanza.

**Comment by urapadmin** [comment]
@lbestock: This is still open from last PASU season. What shall we do about it? Bring it up with Peter? Decide ourselves?
At least perhaps the modifiable yet-another-date in collected material and preprocessing would make sense? 
You really have to wrap your head around this first.

**Comment by lbestock** [comment]
I think we should discuss it (and don't need to bring it up with Peter, at least, my initial thought is that it would take so much explaining that it's not going to get the attention an answer would need). I am trying to start wrapping my head around it but I think it takes a conversation.

A few initial notes.

Looking back at #1825 what I really wonder about is if a locus is excavated in multiple seasons. Really, does USTP just add new lines to the ceramics? Hard enough for me to get in my head that they bag multiple days together, but multiple seasons? That would be a killer. 

CM does have a "when collected" time stamp button.

I want to think through if it is a real issue in practice. I would expect that from a reporting perspective, the thing was found the year it was found, not the year it was made an individual record. It WAS reported the year it was found, as part of a bulk collection. The golden statues are going to get small finds numbers the year they are found anyway. The individual sherds that are only singled out in subsequent seasons aren't new artifacts, even if they are new records. And if I were publishing stuff, in prose I would say "found in 2022" if that is when it was excavated, even if it hadn't been individually numbered until 2023. But let's talk and go through Peter's reports to the superintendanza and see if we can figure out what makes sense PASUwise.

**Comment by urapadmin** [comment]
stale. dropped.
