### ISSUE TITLE
consolidated view of ceramic preprocessing records in filemaker,

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#1825]
coming out of #1809, which I closed:
 
In USTP in particular (does not happen with PASU) we often have more than one record per context, ware type and functional category. 
That makes it hard to see at a glance how many sherds of a certain ware type/functional category we have.

To allow for an easy view we will have a consolidated view on the data behind a button next to the ceramic records.

I am also wondering whether we should make the date of collection explicit instead of using the internal creation date. 
For legacy data I would have to default it with the creation date of the record. Or I could also just make the creation date acutally manipulable.

**Comment by urapadmin** [comment]
Not as simple as I would have hoped: FileMaker as a database does not support pivot table / cross-tab tables.
Sure, why would it? 

So back to the good old WebViewer: I need to do this with a combination of SQL, HTML and JavaScript. There are tools out there but it would take me longer to understand them than to develop this from the scratch.

**Comment by urapadmin** [comment]
### recording 13.6
This exists now and might want some testing: 
- It should consolidate multiple lines of the same categories
- It should not freak out when there are NO records or only one or so
- It should be able to handle lines without a category_2: In this case a new category "-" is created and the numbers shown in there.

**Comment by lbestock** [comment]
It doesn't freak out if there is no category two, but if there is a line with no category one then the whole thing goes blank. Why isn't this like when category two is blank and you get a "-"?

Otherwise it behaves just fine.

Style-wise, would it make sense to have a grid? I find it a quite hard to read.

**Comment by urapadmin** [comment]
You should think it's easy to style grid lines in HTML. They overlooked it. One can't really and needs to do hacky things. I'll look into those hacky things.

**Comment by urapadmin** [comment]
### 13.6.13
- it has a griddish now
- empty category 1 records show up in row "-"

**Comment by luizaogs** [comment]
Jesus. I still cannot get the preprocessing thing to show up. So I can't test this one, sorry!

**Comment by urapadmin** [comment]
we can leave this one for Laurel, anyhow. Some relaxing thing to do after too many interviews.
But: #1897 will come soon :o)

**Comment by luizaogs** [comment]
Ha I think Laurel should go to bed. But thank god for that button.

**Comment by lbestock** [comment]
Ooo you guys gave me a nice relaxing gift for after interviews.

**Comment by lbestock** [comment]
Laurel made the bed, so she can go to it later. And then tested this and it's all good!

**Comment by urapadmin** [comment]
what exactly does it mean when luizaogs reacts with the eye emoji?

**Comment by luizaogs** [comment]
It means that I'm giving Laurel a look indicating that I hope she indeed goes to bed after Birthday Round Two.

**Comment by lbestock** [comment]
I will have no choice but to fall deeply asleep at 9:15. You don't need to put the evil eye on me to make it happen.

**Comment by luizaogs** [comment]
:) good

**Comment by lbestock** [comment]
And no birthday round two until tomorrow.

**Comment by urapadmin** [comment]
how is one supposed to read all that in an emoji glimpse :o) ? Binary logic has some advantages.

**Comment by luizaogs** [comment]
I'm limited in my emoji reactions here, Lutz.

**Comment by urapadmin** [comment]
I don't even know how to make that evil eye. Is there a button somewhere?

**Comment by luizaogs** [comment]
It's not the evil eye!!! It's a caring eye. 

You click on the smiling face on the top left of the comment box :)

**Comment by urapadmin** [comment]
ah. got it. There is a button. I never use that one :o)

**Comment by urapadmin** [comment]
it has a little rocket, too

**Comment by luizaogs** [comment]
Do you think the rocket is more expressive than the eyes? I can switch my default reaction to rockets.

**Comment by lbestock** [comment]
🧿

**Comment by luizaogs** [comment]
See? I wasn't giving you that one. It was a nice eye.

**Comment by urapadmin** [comment]
no, in fact, it would have gotten the same puzzled question. I would be lost in the metaverse. 🪛

**Comment by urapadmin** [comment]
I roll out a button for ya guys ... ⏯️
