### ISSUE TITLE
changing valuelists isn't a good idea: Only additions to valuelists are a good idea

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#1826]
Because changing the value in a valuelist does not change the values that have been used in the records so far.

If there was a typo or so in a valuelist for years it needs to be changed in the value list but also all of the records where the wrong value was used need to be changed wit a bulk operation -> That needs the developer.

So this here is about keeping users from changing a valuelist: In the configuration there should at least be a warning not to do that.

**Comment by urapadmin** [comment]
### recording 13.7.6
- [ ] configuration values that are a list (not limited to the catgory valuelists: A list has more than one line) have an additional warning in the help text and an orange helptext.
- [ ] when such a value gets changed, an additional popup warning pops up. This is not perfect (it does not check what has actually been changed) but good enough to remind you that changing a value in a valuelist is not as easy as it seems. 
- [ ] The popup message can be suppressed for the current download because in a configuration session it can get quite annoying.

**Comment by lbestock** [comment]
The key in labels "label_for_unit_on_start_page" is a list, but doesn't pop up the warning. Same with "plurals" in labels. Not sure if you want me to go through and check all of them - I found these two quickly and accidentally.

**Comment by urapadmin** [comment]
do they have more than one item in them? Because that is how I find out if something is a list: If it has more than one line.

**Comment by lbestock** [comment]
Yes, both those have multiple values in different lines.

**Comment by urapadmin** [comment]
strange. I'll look at them. Don't go through the rest. These examples should do.

**Comment by luizaogs** [comment]
label_for_unit_on_start_page does have two items for me and I don't see a warning either. It looks like this: 

<img width="717" alt="Screenshot 2022-11-20 at 12 50 35 PM" src="https://user-images.githubusercontent.com/67970402/202917799-166e85b5-1583-416b-9ba0-f717193247d7.png">

**Comment by luizaogs** [comment]
Oh kidding. I get it once I try to add a line, not just upon clicking on it.

**Comment by luizaogs** [comment]
Ok yes. So those two (label_for_unit_on_start_page and plurals) get the pop up warning if I change something but they do not have the warning in the help text nor the orange help text. So they do not work with the first check box up there.

**Comment by urapadmin** [comment]
is it possible that the warning / helptext appear when you leave the field (now that it has two lines) and go back?

**Comment by luizaogs** [comment]
Nope.

**Comment by urapadmin** [comment]
then I'll have a last look at it (for closure's sake)

**Comment by urapadmin** [comment]
### recording 13.8.2
this has always been chaotic. I have chosen a different approach now to this help message. Please check if it behaves correctly (not only in terms the warning but also in general).
One caveat is accepted: Some help messages appear orange although they are not valuelists. That's because they have the term "arning" in their texts. That 's okay.

**Comment by luizaogs** [comment]
Yes, they look fine now.
