### ISSUE TITLE
USTP: "Miscellanesous" -> "Miscellaneous"

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#1827]
There is a wrong value for category one in USTP: Miscellaneous. Needs to be changed everywhere and then the valuelist in FileMaker as well.

**Comment by urapadmin** [comment]
do it together with #1831

**Comment by urapadmin** [comment]
### kiosk 1.3
- a migration script should take care of the legacy records
- the wrong entry in the configuration has been changed and synchronized.

**Comment by luizaogs** [comment]
Hmm I think I need a USTP login, too -- don't seem to have one currently.

**Comment by urapadmin** [comment]
USTP "logs" is added, no password.

**Comment by urapadmin** [comment]
PASU addd, too.
I have deliberately not made you an admin because we are testing too much as admins. So let me know if you can't access anything you need to.
