### ISSUE TITLE
filter locus list

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#1829]
We now have sorting a locus list #1791 but I still think 
filtering at least by type and recorded by does make some sense. At least I remember that in some of the projects somebody wanted to see only her contexts and while sorting is a possibility, filtering would work better.

So let's add a filter button to the locus list to make it even more complicated.

**Comment by urapadmin** [comment]
### recording 13.6
- list can now be filtered by type and/or recorded_by.
- a "filtered" marker appears once a filter is active and allows to get rid of all filters in one click

**Comment by luizaogs** [comment]
This is great.
