### ISSUE TITLE
new excavator property "tester"

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#1832]
there is a new property per user in "team members" which marks a user as tester.
If set the database will automatically switch test mode on if that user logs on.

**Comment by urapadmin** [comment]
### recording 13.5.6
that's implemented.

**Comment by lbestock** [comment]
Hey that's a pretty cool feature. It will get used.

**Comment by lbestock** [comment]
Once it is on, it stays on if I log out and then back in again as a user who does not have test privileges activated. Is this as intended?

**Comment by lbestock** [comment]
Otherwise this works exactly as I would expect from the above bullet points. It is very handy to be able to turn it both on and off this way.

**Comment by urapadmin** [comment]
### recording 13.6.1
I would not call it "intended". I did not think about it. It might come in handy when you switch to a normal user (in the end always testing in test mode is a but like always testing in admin mode -> it is a mode a normal user is not using)
- So from now on when you log in as a user that does not have testing privileges the test-mode will be switched off on start (or when you remove the privilege in the team member config)

**Comment by luizaogs** [comment]
Works.
