### ISSUE TITLE
relict organization in configuration wants some attention

### ISSUE THREAD

**Issue by lbestock** [arch-kiosk/arch-kiosk-office#1834]
Some configuration keys are not in places one would expect them. Most notably "general" has things that belong in "visibility" (for instance, "show spider button" and everything else that is "show") and "valuelists" ("warecodes").

**Comment by urapadmin** [comment]
### Kiosk 13.6.2
This needs patching, so remember that only in projects where the patch has been synchronized the keys will move permanently.
By moving the keys I also patch the value! I can't do it independently. That is why I won't touch warecode and registration codes right now. I don't want to override peoples settings.

- show_age_warning moved (and set to yup)
- warn_db_age moved (and set to yup)
- warecodes moved to valuelist (and set to

**Comment by luizaogs** [comment]
These are all now in visibility and with the values mentioned above. Not sure if this is meant to be closed or not, though.

**Comment by urapadmin** [comment]
#1836 is ready and so I can patch the left overs:

### this needs preparation in 13.7.4:
So, in PVD to test this, the easiest way would be to first set a few of those config values to something that is not the default and that you'd recognize BEFORE I update the template with 13.7.5, 

### recording 13.7.5
- urap_warecode_help moves to visibility (but keeps its value)
- warecode moves to visibility (where it already seemed to be in my development environment?)
- show_spider_button moves to visiblity (again) but this time without changing the value of the key
- identification_method_cm,  identification_method_feature_cm and identification_method_survey_cm move to deprecated
- registration_codes_done and registration_codes_todo move to valuelists without changing the project's value.

**Comment by urapadmin** [comment]
I have done the first part: The values from 13.7.4 stay intact while the new meta data gets patched with 13.7.5. 
You may look around yourself as to whether or not the config keys are correct now

**Comment by lbestock** [comment]
I don't agree that this is not inspiring, weirdly enough. But I have some questions. I don't really understand the difference between patch metadata and patch value. And as for locations, it seems to me you moved some of the above things already and not others? That's hardly a problem, just not what I expected.

**Comment by urapadmin** [comment]
If this inspires you, you need to see a doctor. It mind-numbs me to the nth. This is shoveling my own legacy from one corner to another. Not adding anything. 
Doesn't #1836 explain the difference?

I can't remember that I moved some and not others, so if you think there is something missing or wrong, please report it. Not sure, which keys you are referring to.

**Comment by lbestock** [comment]
Not entirely, on the making sense front from #1836. I don't understand how something I could do in PVD would affect all projects.

**Comment by urapadmin** [comment]
What you do does not. But I patch things on template level. And that affects all projects. All projects get the same template with the same patches. If I patch the ceramic_module config entry ALL projects with that template will get my setting for ceramic_module. That's what patching does. And with #1836 I can change to meta data for a config key without changing the value of that config key. So I can change the help text for "ceramic_module" without actually setting the ceramic_module for all projects to the same value. 
I hope that makes it clearer.

**Comment by lbestock** [comment]
Yes that helps. So when I am seeing the choice of patching metadata or value that is not in fact an option for me, I am just moving things around for a single project, the tools just look the same way they do for you in development, correct? It was the apparent choice that isn't really a choice that confused me.

So, then, moving things around is useless for me because we are trying to get this in shape for every project, and you must do that on template level. As such I just need to look to see if what you have done is proper, and now I've messed that up a bit by moving things around to try to understand. I believe the only thing I found that had not moved where I would expect it to be from the list above is that urap_warecode_help hadn't moved to visibility yet. The warecode thing is weird because here in 13.7.5 it is in visibility but I still have 13.7.4 on my iPad and there it is in general. I have looked through every other configuration key and found no other things that were manifestly in the wrong place.

The reason this interests me is because configuration has always been something I have done rather than something I have particularly understood, and so anything that gets me even a shade closer is of interest.

**Comment by urapadmin** [comment]
you don't see options to patch meta data as far as I know. Only if test mode on (as I have explained in #1913) so that you can see the meta settings of a certaing key. Otherwise you can't even see some of them. Particularly the sync_level, which, if I want you to look at it, I will explicitly mention.

You are not supposed to move anything around.

If you have moved things around you also have messed up because on next synchronization those things will get synchronized. If you don't synchronize, the patches will not get synchronized because it was your workstation that got the update.

So to get back to a coherent basis I would reset all workstations, reinstall the update again and then you can test again if things have been put in the right place by the update.

**Comment by urapadmin** [comment]
I have done that. Workstations reset, template reinstalled.

**Comment by lbestock** [comment]
Ha OK. I did synchronize the patch before I changed anything! But I will do it properly now and not mess with moving things around.

**Comment by lbestock** [comment]
And now I have looked again and everything looks proper and I have synchronized the patch without touching anything.

**Comment by luizaogs** [comment]
So do we close this?

**Comment by urapadmin** [comment]
I do
