### ISSUE TITLE
locus relations between units

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#1837]
Currently the UI only allows for locus relations in the same unit.
The UI needs to cross unit boundaries here. It still is the rarer case so I need a way to allow for that without making the every-day relation harder to create. 

- This might be needed for #1790 but was requested even without that.

- Additionally: How to include this into navigation? (#1795)

**Comment by urapadmin** [comment]
### recording 13.8
- last feature for 13.8: This is implemented now.
- there is a new button that allows you to link to a locus in a different unit. It opens a popup where you can comfortably choose that locus
- in case that a related locus is in a different unit you cannot use the drop down anymore
- in case a related locus is in a different unit you get foot steps to take you there
- now we always see the unit of the related locus above the related locus
- as long as the related locus field is empty OR the related locus is in the same unit everything should be as it was: You can simply use the drop down list

**Comment by luizaogs** [comment]
Works.

**Comment by urapadmin** [comment]
that was fast. You have been thorough? Did you look at the file identifier cache (the image gallery) if both loci and both units are registered with the image correctly?

**Comment by luizaogs** [comment]
Argh sorry, I looked at all of your bullet points above and checked the image but I always forget about the file identifier cache. 

No -- neither unit seems to get added to the image in the gallery. Both loci do.

**Comment by luizaogs** [comment]
I just checked with another relation (a normal one, not across units) and no, you don't seem to add the unit normally.

**Comment by urapadmin** [comment]
I looked it up in the code: Correct. The unit does not get added. 
So I close this.
