### ISSUE TITLE
Request rules from Parker for quality control and then set them up for him

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#1844]
@lbestock: I leave organizing the rules to you. I do the setting up.

**Comment by urapadmin** [comment]
no rules. I will install at least our standard qr rules for pacha.

**Comment by urapadmin** [comment]
### 03. Jan 2022:
- that's done for PACHA.

**Comment by luizaogs** [comment]
I need a PACHA login to test this.

**Comment by lbestock** [comment]
You have one now.
