### ISSUE TITLE
Navigation: Start Page

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#1851]
The start page is added to the layout history but not to the recently viewed history when it is left through any of the ways it can be left. And there are MANY! Click on any button and make sure the Start page is added to the layout history.

**Comment by urapadmin** [comment]
- Going to the start page always erases the layout history

**Comment by urapadmin** [comment]
### recording 13.6.7
- you should not be able to find a way to leave the start page to somewhere without being able to get back to the start page properly. Not all layouts have gotten the new navigation buttons but those that don't should just always go back to the start page and so no issue would arise. To test you can only poke around as systematically as you can.

**Comment by luizaogs** [comment]
I believe this is all ok.
