### ISSUE TITLE
Navigation: Image Gallery

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#1852]
- can't be left to anywhere else, so no layout history BUT 
- it should get added to the recently viewed

**Comment by urapadmin** [comment]
### recording 13.6.5
- added to recently viewed only if opened as a main layout. E.g. from the start page.
- NOT added to the recently viewed if opened as a popup ("insert from gallery")
- NOT added to the history simply because one cannot go anywhere from here.
- does not show the little history button

**Comment by luizaogs** [comment]
Works.
