### ISSUE TITLE
Navigation: Site Notes

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#1853]
- enters the navigation history (can be left and gotten back to via recently viewed)
- should get on the recently viewed

**Comment by urapadmin** [comment]
### recording 13.3.6
- going back to it goes back to the site that was active

**Comment by luizaogs** [comment]
Works.

**Comment by urapadmin** [comment]
last changes because of #1862 requires a new test of this one here.
