### ISSUE TITLE
Navigation: configuration (admin)

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#1859]
It does make some sense to go between administration an whereever one is.
So it will get on the recently viewed and for the back - and forth also on the layout navigation.

**Comment by urapadmin** [comment]
### recording 13.6.7
- admin has the usual navigation buttons
- when jumping somewhere using the recently viewed history and going back from there to the administration the last active category will be selected. That way we can jump more easily between configuration and a layout that we are in the process of configuring.

**Comment by luizaogs** [comment]
Hm. Weirdly in recently viewed I am only getting the general configuration page. The layout history seems to record other categories (identification, visibility, etc.), but not recently viewed.

**Comment by urapadmin** [comment]
### recording 13.6.8
- should be fixed

**Comment by luizaogs** [comment]
Ok, almost. If I navigate out of configuration by clicking on something in the layout history (in this case I'm clicking on LA) the correct configuration page does not update neither in layout history nor in recently viewed. If I leave configuration by clicking on something in recently viewed (let's say LA again) then both are updated properly.

**Comment by urapadmin** [comment]
### recording 13.6.9
hmpf.
I have added another line some where else to remedy that but I clearly see that I am starting to patch things instead of building something. Well, it's just filemaker. So It should be better now for the recently viewed but not necessarily for the layout history. But I can live with that.

**Comment by luizaogs** [comment]
Yeah, recently viewed is perfect but layout history is still iffy in that particular situation. But if you can live with that I certainly can, too.
