### ISSUE TITLE
Navigation: identifier lists

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#1860]
### recording 13.6.7
- has normal navigation buttons now
- when jumping to somewhere else the active identifier list is saved and restored when returning via back button

**Comment by luizaogs** [comment]
Hm. The specific identifier list category only seems to get updated on the recently viewed list when I return to it via the back button. 

Steps: 
1. For instance, start in context numbers identifier list
2. Go to somewhere else through the recently viewed (in my case, I'm going to LA-9 sample)
3. Going back to context numbers works fine
4. Now switch context numbers to survey numbers
5. Go back to LA-9
6. The layout history has the right Identifier Lists (survey numbers), but recently viewed looks like this: 
![IMG_FBD446957629-1](https://user-images.githubusercontent.com/67970402/197372593-be6c29d0-2237-459a-8b6e-f2f62276f7ba.jpeg)

7. If I go back with the back button, recently viewed updates now:
![IMG_47D2FC921A7D-1](https://user-images.githubusercontent.com/67970402/197372630-774301b6-1846-49c3-a73a-fd67b46d7b1d.jpeg)

**Comment by urapadmin** [comment]
### 13.6.8
should be fixed
