### ISSUE TITLE
Navigation: Adding a new collected material adds two entries in the navigation

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#1862]
Slight funniness on creating a new CM from within an old CM record.
![image](https://user-images.githubusercontent.com/49291909/196542828-c615183d-dc84-46f6-891b-2e30373abcdd.png)
That 709G bulk is funny?
If I create a new bulk CM from the CM page it registers only the line 709V(ivory) (for example), not also a 709V also. This is so super minor and I have trouble imagining anyone running into it or finding it a problem but you might want to know it happens.

_Originally posted by @lbestock in https://github.com/arch-kiosk/arch-kiosk-office/issues/1795#issuecomment-1282993982_

**Comment by urapadmin** [comment]
Your description puzzles me a bit but at least I think I can reproduce this: 
When creating a new cm from within collected material it registeres two records, one with and one without the material. That is, of course, wrong.

**Comment by urapadmin** [comment]
### recording
this was in fact not an issue limited to collected material but a general issue which just surfaced here. So: Even seemingly small things can point to bigger issues.

In each layout we have to test if records get correctly added to the recently viewed history.

**Comment by luizaogs** [comment]
Ah, so I guess this is connected to what just happened in #1868 ? I'll wait to test this here once that is resolved.

**Comment by urapadmin** [comment]
### recording 13.6.6
wow. This is pretty complicated. I have made sure now that this particular thing can't happen again. But here is the complication:
When you first create a collected material in the current PVD configuration (would be the same for URAP and ARCH1900), let's say LA-12-001 it does not have a material, so it is registered as LA-12-001 bulk ()  in the navigation. 
Now you change the material to, say Metal, leave the layout and come back. It is still the same material that is already in the history but now it is named LA-12-001 bulk(Metal). So when you change the material (or whatever might be part of a future collected material entry) the Navigation entry has to change as well. 

@lbestock, this is for you, too:
This is what I do now:
- when I register a layout / record in the recently viewed history I first look if it is already in there and if so, I drop that one
- I add it
The effect is that the recently viewed history gets free of old entries in the end.

- [ ] So this issue here (and #1686) is definitely solved by the mere fact that I am not using the identifier any longer to find out if there is already an entry but the technical record id in the background and that never changes when a material changes. 

- [ ] But we also want the entry in the navigation reflect the current state of the record it is referring to. And that is solved, too, now, but only for the recently viewed history.

Here is the catch: It can still happen in the layout history that you encounter the same collected material with different entries:
- make a new collected material, give it "beads". 
- Leave with the footsteps to the locus, 
- select the collected material again in the cm list of that locus, 
- change the material to "bones"
- footstep to the unit. And voila: The same bulk is in there with the new and the old material.

Should we learn in reality that this happens more often than I think I'll consider the case again.
 because here I do not exchange the older ones with the most recent one. It slows all navigation down generally and I think that cost outweighs the rather rare case of somewhat diverging entries in the navigation.

**Comment by luizaogs** [comment]
This is now working (and the two materials happen as you say they would in the navigation history if I follow those specific steps).
