### ISSUE TITLE
navigation: using "recently viewed" navigation and layout changes.

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#1865]
Currently navigation using a "recently viewed" entry works like this:

- when navigating to an item in the recently viewed history, the CURRENT layout must become part of the layout history so that clicking the back button in the target layout can lead back to the current layout. Example: You are in locus layout and click on "Image Gallery" in the recently viewed items. When in Image Gallery you want the back button to go back to the locus layout you just left.

I think everybody will agree on that part.

- BUT what if going to the recently viewed target does not actually change the layout? Example: You are in excavating: unit LA. You click on locus LA-001 and got to the locus layout. Now you click on a recently viewed LA-003. In LA-003 you move with the arrow keys to LA-001. Now you click the back button. What do you expect to happen? In the current implementation you will be taken back to LA because clicking on the most recently viewed LA-003 did NOT change the layout and hence it was not entered into the history.

Sounds good, doesn't it?

But here is the catch:
- Let's assume you are in Unit: LA and use the locus list to go to LA-001. 
- now you go back to the start page (doesn't matter how)
- you open unit "CA" and go to locus "CA-001"
- now you open the recently viewed items and click on LA-001, where you will be taken.
- now you click the back button: You are back at CA. 
- WHY? Because when going from CA-001 to LA-001 there was no layout change and hence no entry in the layout history.

complicated. Sometimes that might not be what you want and you will be surprised. Sometimes it might. What I cannot do is distinguish between layout changes that can not be reversed with controls in the layout from those that can be reversed (for instance by using the arrow keys). In the example above there is no way to go from LA-001 to CA-001 without leaving the layout (except if you use the recently viewed entry for CA-001). 

The alternative would be to always create a layout history entry when using a navigation from "recently viewed" (the same will be true for using the search function!). But then you might find yourself in a different different pickle:
- In LA-001
- jump to "most recently viewed" LA-003
- move to LA-001 with arrow keys
- click the back button -> Nothing seems to happen because you jumped back to LA-001 itself. 
- but even if you stay in LA-003 and hit the back button I feel it would be confusing NOT to change the layout.

@lbestock, @luizaogs: So I'd prefer the current implementation but we all need to form an opinion here, perhaps even in the field. Or does anybody have an idea for a third way?

**Comment by luizaogs** [comment]
Hmm. My immediate reaction is that the current implementation is not a huge problem, and that the alternative seems indeed more confusing (since I think users might approach the back button as similar to browser back buttons, and not going anywhere will be more puzzling than going somewhere perhaps a bit unexpected). I think. But I also think in order to really use this properly and form an informed opinion I would need a real world scenario (either a fake one or in the field -- fingers crossed for Uronarti).

**Comment by urapadmin** [comment]
No discussion unfolding. I close this and we go with the current implementation.
