### ISSUE TITLE
Navigation: excavating simple

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#1866]

**Comment by urapadmin** [comment]
### recording 13.6.5
- test going back and forth between excavating and the site notes (either using the button under "trench" or the foosteps next to site in the header)
- test going between excavating and locus
- test going between excavating and collected material

**Comment by luizaogs** [comment]
Seems to work fine.

**Comment by urapadmin** [comment]
last changes because of #1862 requires a new test of this one here.
