### ISSUE TITLE
Navigation: Leave Start Page in the layout history when the maximum is reached

### ISSUE THREAD

**Issue by luizaogs** [arch-kiosk/arch-kiosk-office#1870]
So I was testing the maximum lines allowed in the navigation history and am now finding myself in situations where the Start Page is nowhere to be found in the navigation history -- I suppose because I made the maximum 3 lines and once I've hit two contexts and a CM or something like that the Start Page is no longer there. But then that means that I have to go back (with the back button) a bunch of times if I want to go to the start page for any reason. I guess this is maybe more of a test than real life scenario, but since it bothered me in testing I thought I would bring it up. 

<img width="1023" alt="Screen Shot 2022-10-19 at 9 47 42 PM" src="https://user-images.githubusercontent.com/67970402/196844556-6c298bf3-b749-43a9-87ad-014ec4b76a0c.png">

**Comment by urapadmin** [comment]
what happens if you use the back button although the start page isn't in the list anymore?

**Comment by urapadmin** [comment]
This should in fact take you back to the start page. But I could think about making it explicit by adding the Start page back in the history as soon as there is space again.

**Comment by luizaogs** [comment]
I just have to go back a bunch. Like 4ish times.

**Comment by luizaogs** [comment]
Oh if the navigation is empty? Why would it be empty?

**Comment by urapadmin** [comment]
because you went back all the way and then there is nothing left in the history because the start page got dropped from it at some point.

**Comment by luizaogs** [comment]
Ah. Let me see.

**Comment by urapadmin** [comment]
Ah! I understand. You wanted to go back with one click and not back -  back  - back ... Understandable. So I think adding the Start Page back in makes some sense.
Of course one can always use the Burger menu and use the Home button. Oh Christ, I forgot about that one. That is another way of leaving a layout and it has to be integrated into the navigation history. Hmpf.

**Comment by luizaogs** [comment]
Ahhh ok I forgot there was a home button. That's kinda what I wanted, actually. So I don't know if the Start Page in the history is necessary. Hm. There are just a lot of buttons to remember :)

**Comment by urapadmin** [comment]
Ja, it cannot hurt to have that Start Page be always the root of the navigation for those who get used to it. In the end that is where you land if you use the back button.
New ticket for the home button in the burger menu, though: #1871

**Comment by luizaogs** [comment]
As always, yours truly giving you more work when you should be in bed.

**Comment by urapadmin** [comment]
so appreciated. But now: 🧠  -> 🛏️

**Comment by urapadmin** [comment]
### recording 13.6.6
I solved this slightly differently: Once the maximum is reached the second last entry is removed with the result that the "Start Page" entry never gets dropped.

**Comment by luizaogs** [comment]
Ah this is really wanted I wanted yesterday, so I think it's great.
