### ISSUE TITLE
Navigation: feature recording

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#1874]
### recording 13.3.7
- has the navigation buttons
- feature recording <-> collected material, which should restore the correct tab on the way back
- still NO jump to the "recorded in" unit. I'll leave that some later release: #1877
- but navigating to a feature from a survey or legacy unit and back should work fine (but that's listed in those unit types, anyway)

**Comment by luizaogs** [comment]
Hm so if I go to the cm from the feature layout I can go back to the feature layout through the layout history or recently viewed. But two things:

1. I get back to the photos/description rather than the collected material tab. 
2. If I navigate to the feature using the footsteps in the header I end up in the feature recording layout, rather than the feature itself. 

Are those two things purposeful?

**Comment by luizaogs** [comment]
Oh yikes, and then if I click on the features tab on the feature recording form I get the following error and weird layout: 

![216C850E-C511-42B0-BA85-2DBFE734E1B8](https://user-images.githubusercontent.com/67970402/197373178-15294fa7-d3f0-4626-9d9f-c37295f37721.png)
![4E40E70F-1389-47D6-AE69-38E0F0E2CCDD](https://user-images.githubusercontent.com/67970402/197373180-14a39bbe-e206-4be3-b527-3b61f5c78011.png)

**Comment by luizaogs** [comment]
When you say navigating e.g. to and from a survey unit you mean through the history or recently viewed, right? Not footsteps? Because I don’t see any that would work for that.

**Comment by luizaogs** [comment]
Last thing: should there be footsteps next to the site (in the header) in the feature layout? Not there currently.

**Comment by urapadmin** [comment]
> Last thing: should there be footsteps next to the site (in the header) in the feature layout? Not there currently.
### recording 13.6.8
Lazy Lutz. It is there now.

**Comment by urapadmin** [comment]
> When you say navigating e.g. to and from a survey unit you mean through the history or recently viewed, right? Not footsteps? Because I don’t see any that would work for that.

I mean through the back button. You jump from survey unit to feature and then back via the back button (or the histories)

**Comment by luizaogs** [comment]
Ok, going back to feature from the cm:

Going back through the layout history: I’m back to the collected material tab in feature, which I believe is what you want

Going back through recently viewed: I am taken to the main feature tab, which I don’t think is what you want? (ok actually this is the case sometimes and not others, I cannot find a pattern)

Going back through the footsteps next to the feature number in the header: THIS is the problem and it is how I get to what you called the legacy layout above

**Comment by luizaogs** [comment]
And yes, regarding your #2 question above, I get the error when I click on the feature itself, not the tab

**Comment by urapadmin** [comment]
> Hm so if I go to the cm from the feature layout I can go back to the feature layout through the layout history or recently viewed. But two things:
> 
>     1. I get back to the photos/description rather than the collected material tab.
> 
>     2. If I navigate to the feature using the footsteps in the header I end up in the feature recording layout, rather than the feature itself.
> 
> 
> Are those two things purposeful?

Got it: jumping from collected material via foot steps to the feature leads to the wrong layout: simple excavation.

**Comment by urapadmin** [comment]
### recording 13.6.7
This should all be fixed now. Almost all of it was due to jumping from cm to feature via footsteps.
