### ISSUE TITLE
Navigation: pedestrian survey

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#1875]
### recording 13.6.7
- the usual navigation buttons
- survey unit <-> collected material
- survey unit <-> feature unit

**Comment by luizaogs** [comment]
This is working, but see hidden locus issues in #1887.

**Comment by luizaogs** [comment]
Oh wait, I just realized: should there be footsteps next to the site in the header?

**Comment by luizaogs** [comment]
Ah also: using the footsteps next to the survey unit in the header in cm takes me not to the normal survey unit page, but rather to a weird survey/digging hybrid: 

![IMG_9C562BFCC564-1](https://user-images.githubusercontent.com/67970402/197373603-26e11fa4-7e56-4ad6-9cd0-226a3c458ffb.jpeg)

**Comment by urapadmin** [comment]
### 13.6.8
Same issues as with feature recording. It should all be fixed.

**Comment by urapadmin** [comment]
### 13.6.11
reopened because of 13.6.11
the jump to feature unit needs to be tested again (and its effects on navigation).
