### ISSUE TITLE
Hub: The "prepare workstations" privilege should be sufficient to reset a workstation

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#1878]
arch1900 ran into that.

**Comment by urapadmin** [comment]
### kiosk 1.2.8
- "prepare workstation" is sufficient to reset a filemaker workstation / reset all filemaker workstations

**Comment by luizaogs** [comment]
I'm testing this (finally) with user test, which has the privileges download workstation and prepare workstation only. I see the "reset workstation" option under more options, but when I click on it I get this: 

<img width="1512" alt="Screenshot 2022-11-09 at 7 28 56 AM" src="https://user-images.githubusercontent.com/67970402/200842812-977225c8-d794-47c5-9e96-f1e0cc0d0573.png">

**Comment by luizaogs** [comment]
I also don't see a "reset all workstations" option in the burger menu but I don't remember if that's a thing in the first place. I see "prepare all workstations" and "import all workstations".

**Comment by urapadmin** [comment]
### kiosk 1.2.10

> I also don't see a "reset all workstations" option in the burger menu but I don't remember if that's a thing in the first place. I see "prepare all workstations" and "import all workstations".

This should be visible now.

- and the job should start now. It was super secure.
