### ISSUE TITLE
collected material by trench makes no sense in legacy recording

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#1879]
But there it is.
It never shows anything because there are no loci that could refer to any collected material. 
So It needs to be disabled in legacy recording mode. (The thing is that I am using the simple excavation layout here as the basis and that's why the tab is there).

**Comment by urapadmin** [comment]
### recording 13.6.7
There is only a "-" tab now and it can't be clicked in legacy recording.

**Comment by lbestock** [comment]
How can that be? The whole reason we invented legacy recording was to get the CM from Wheeler into the URAP database. There are features under the Indy hat units, and features are (hidden) loci and those have CM that could be shown at the Indy hat unit level and make sense. Archaeological sense, while pointing yet again to the fact that this method of solving the problem in the data structure was a hack.

A question that then arises for me is if there would be value in seeing CM by survey unit that includes not only the CM of the survey unit but also of the associated features.

And I think in both the above cases there are obvious analytical reasons for looking at that stuff together but that it's not necessary in recording. But I'm also aware that I am in the state of torturing my brain to unthink anything I think I think, so I'll put it aside.

**Comment by urapadmin** [comment]
I wasn't saying that it does not make sense archaeologically. It cannot work the way it works for excavation units because the collected materials are not connected to loci that belong to the legacy unit. They are connected to invisible loci connected to the feature units that are connected to the legacy unit. So if we really wanted this we would have to implement legacy units as their own thing (like feature units, like survey units). I always try to avoid more more or less similar layouts to maintain. Hence the hack in the first place.

**Comment by lbestock** [comment]
We didn't have a single Indy Hat unit in PVD yet. Nuts.
But now we do and this works as it should.
