### ISSUE TITLE
Navigation: registration (collected material under specialists)

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#1880]
### recording 13.6.7
- navigation buttons
- registers in recently viewed
- jump to collected material. When coming back, the filter settings should still be active

**Comment by urapadmin** [comment]
### regording 13.4.1
- There was still a little snafu in the transition from registration to collected material: The current row in registration would jump to the top shortly before the layout switch. I repaired that but now I might have screwed up other things, so please look at:
  - jumping to CM from search
  - jumping to CM from a locus using the cm list
  - jumping to CM from a unit using the cm list
  - jumping to CM using the navigation history

**Comment by luizaogs** [comment]
Looks ok.
