### ISSUE TITLE
Navigation: urap pottery layout

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#1881]
### recording 13.6.7
- just the usual navigation buttons
- registers every opened collected material in recently viewed
- footstep button leads to the collected material and when coming back from there (or from where ever) the open cm is restored

**Comment by luizaogs** [comment]
I got the following error when in the urap pottery layout, after I clicked on a cm record in recently viewed to try and navigate there and back: 

![IMG_0327](https://user-images.githubusercontent.com/67970402/197373910-ece4b1c4-7334-486f-b677-a53f59b9474f.PNG)

**Comment by luizaogs** [comment]
After clicking ok, I did get sent to the cm record I had tried to navigate to before getting the error.
When looking at the navigation history in the cm layout, I can see that Pottery Processing was added to the layout history, but it was not added to the recently viewed.

**Comment by luizaogs** [comment]
Clicking on Pottery Processing in the layout history to try and get back to the urap ceramic processing gives me this error: 

![IMG_0328](https://user-images.githubusercontent.com/67970402/197374006-ee01dbcc-4b14-4961-9a83-468d6681a9b6.PNG)

**Comment by luizaogs** [comment]
Clicking ok does get me back to the urap pottery layout.

**Comment by luizaogs** [comment]
The rest seems ok.

**Comment by luizaogs** [comment]
Ah wait, kidding: clicking on the footsteps to go to the ceramic record does indeed work, but clicking on the ceramic record in the recently viewed does nothing.

**Comment by urapadmin** [comment]
### 12.6.8
This is the most finicky layout because it is soooo old and I should trash half of it. 
I think I have resolved all of it except that I am still able to create several "pottery processing" entries with NO collected material in the recently viewed history when going between the start page and the pottery processing. I might just ignore it.

**Comment by luizaogs** [comment]
Yup.
