### ISSUE TITLE
Navigation: su ceramics layout

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#1882]
### recording 13.6.7
- the usual navigation buttons
- jump to collected material via footsteps and back . When jumping back the correct collected material in the ceramics module must be opened

**Comment by luizaogs** [comment]
This is working, but I keep getting the "start ceramics processing for X?" question even though I have already said that I want to start the analysis before.

**Comment by urapadmin** [comment]
well, I am always on the fence of getting rid of that question at all. 
But until then: It goes away as soon as you have actually started to process the ceramics for X, meaning, you created a fragment in su_ceramics or a warecode record in urap pottery.

**Comment by luizaogs** [comment]
You're right -- I forgot to add the fragment with the plus button. Sorry. So this is fine.

**Comment by urapadmin** [comment]
🛏️ ❗

**Comment by urapadmin** [comment]
on my way :o)
