### ISSUE TITLE
unexpected transmission error

### ISSUE THREAD

**Issue by luizaogs** [arch-kiosk/arch-kiosk-office#1885]
I believe this is a hiccup rather than a bug, but ....

When synchronizing the workstation with the update for 13.6.7 I got an unexpected transmission error (see screenshot below), but then I hit the back arrow next to "show more details" (which by the way showed me no more details) and Kiosk told me that the synchronization was in progress, and it did indeed synchronize.

![IMG_0319](https://user-images.githubusercontent.com/67970402/197371624-60b2d10a-7da2-49d7-ae3e-5bb8528bed02.PNG)

**Comment by urapadmin** [comment]
ja, that is a hiccup. Happens. A browser refresh should always fix it.
And the more details issue is already somewhere in a ticket.
So I close this right away.
