### ISSUE TITLE
navigation to hidden locus

### ISSUE THREAD

**Issue by luizaogs** [arch-kiosk/arch-kiosk-office#1887]
I’m testing navigation for feature recording and just realized that I can totally navigate to the hidden loci of the feature units through the cm recorded in the feature units. Should this be the case? (I can get there through the footsteps in the header.)

**Comment by luizaogs** [comment]
I can also get there when in the cm form in survey units.

**Comment by urapadmin** [comment]
### recording 13.6.8
Those locus footsteps should not be visible when the cm belongs to a feature or survey unit
