### ISSUE TITLE
KioskBridge/Beset: Uploading via KioskBridge fails due to CSRF error

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#1888]
The logs show:
![image](https://user-images.githubusercontent.com/38838314/197406531-1942daa8-9f7e-4890-a22a-d32404d41196.png)

When I exempt the KioskFileMakerWorkstationController from CSRF protection, it works:
``` python
def init_controller():
    # if kioskglobals.get_development_option("webapp_development").lower() == "true":
    kioskglobals.csrf.exempt(kioskfilemakerworkstation)
```
I have checked the versions of flask-login, flask-allows, flask-httpauth, flask-wtf and wtforms and they match my development system. So it does not seem to be a library issue.

What can it be? We clearly don't have that issue on arch1900.

**Comment by urapadmin** [comment]
see also #895 and #1770

**Comment by urapadmin** [comment]
### Kiosk 1.2.8
The configuration key kiosk/kioskfilemakerworkstationplugin/no_csrf_defense switches the problematic CSRF defense mechanism off. I suppose we are still not a main target of cross site forgery attacks, so I can live with it. But this is not the solution to the problem, just a workaround. So please leave it open.

**Comment by urapadmin** [comment]
@lbestock: Can you please test this once more? This is the last ticket of 1.3. (Just don't close it afterwards)

**Comment by lbestock** [comment]
Testing this while in a zoom meeting. Works perfectly, with split attention.

**Comment by luizaogs** [comment]
Can I get this out of testing? I keep clicking on it because I forget there is nothing to be done at the moment (not that I could do it anyway because I forgot to ask you for Bridge. Dammit).

**Comment by urapadmin** [comment]
I have taken it out of testing. Somebody needs to take action.

**Comment by lbestock** [comment]
Why wasn't this closed? Taking out of testing is meaningless. I will close it.
