### ISSUE TITLE
After the navigation works everywhere we tackle Deleting records that are linked in the navigation.

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#1889]
### recording 13.6.9
- #1869 is done but missing something (see below)
- unit deletion: If we delete a unit that isn't empty, I just empty both histories. That's the simplest solution. 
- Otherwise, if the unit is empty, only the unit gets eliminated from both histories.
- locus deletion is fine for an empty locus. But if it has stuff, I'll take the same shortcut I used for units: I empty both histories.
- collected material: Surprisingly we don't allow deleting a collected material as long as it has photos, ceramics or whatnot. So here it is easy: When it gets deleted, it gets removed from the histories.
- tag analysis: Removing tags is wurscht. Nothing bad can happen if tag analysis is opened with a bunch of tags that don't exist anymore, I think. So I do nothing.

**Comment by luizaogs** [comment]
Ok so this is on my Mac: I deleted a locus with some stuff in it and the histories were emptied as you said they would be, but recently viewed had this still in it: (). 
Now I can't remember if I tried to click on it or if I just clicked outside of the navigation history but I have ended up with the following (a layout without the back button): 

<img width="1023" alt="Screen Shot 2022-10-24 at 1 40 54 PM" src="https://user-images.githubusercontent.com/67970402/197601301-31ab0d4e-daf7-49a4-b076-3139d7dda39d.png">

I'll try to do it again.

**Comment by luizaogs** [comment]
Oh wow and I just noticed the crazy string of numbers where the cm identifier should be, too.

**Comment by luizaogs** [comment]
Ah yeah, and if I use the footsteps next to the () next to the context I get this: 

<img width="1021" alt="Screen Shot 2022-10-24 at 1 43 20 PM" src="https://user-images.githubusercontent.com/67970402/197601581-1f9c8bdc-feb5-42b3-8840-c644b9fbc56a.png">

**Comment by luizaogs** [comment]
Ok now I tried again and none of that happened so I do not know how to recreate it, blah!

**Comment by luizaogs** [comment]
Deleting an empty cm gave me this (only in the recently viewed): 

<img width="1029" alt="Screen Shot 2022-10-24 at 1 49 14 PM" src="https://user-images.githubusercontent.com/67970402/197602694-3eca2a58-6d06-4ff1-aa5f-14c558f53085.png">

Upon clicking on it, I got this error: 

<img width="1033" alt="Screen Shot 2022-10-24 at 1 49 22 PM" src="https://user-images.githubusercontent.com/67970402/197602721-995e570a-a068-486b-a40c-deb0ebcf0b99.png">

**Comment by urapadmin** [comment]
### 13.6.10
- @lbestock, @luizaogs: if test mode is on there is a new feature that can help me understand what is going wrong: You should have a button "show history details" in the navigation history. If you have a history that looks strange (like above) just click that button and the layout should look something like this:
![image](https://user-images.githubusercontent.com/38838314/197623003-270f1525-b718-48f3-b9db-7d48f9ea4d4f.png)
Upper right corner has a copy to clipboard function. If you then paste the contents of that into the GitHub ticket I might get a better understanding of things. BUT: it only shows the history that was active in the layout history. So make sure you selected the right tab.
This feature should, of course, not be visible if test mode is off.
- as for the issue(s) at hand: Since I cannot reproduce any of it, I have put a safety catch in place that prevents the history from saving such empty entries at all.

**Comment by luizaogs** [comment]
Ok I just tried deleting everything again and did not get any of the weird empty entries and the new test mode feature works as it should, so I close this ticket.
