### ISSUE TITLE
navigating by search

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#1890]
one can either use search on the start page or from most of the burger menus. 
So that's another instance where the navigation needs to work.

**Comment by urapadmin** [comment]
### recording 13.6.9
- this is more or less the i-tüpfelchen on everything. It allows for the wildest navigation histories and covers just everything. So it is incredibly hard to test. All you can do is navigating everywhere from everywhere as systematic as you can. Navigate to survey units, feature units, legacy units etc. because it is slightly individually treated in the code and there are plenty of places where things might not add up from the angle of the search.
- and then walk back from there to the layout from which you started the search (in fact starting the search from the start page is the most boring version. Using it from the burger menus bears way more change to derail things).

**Comment by luizaogs** [comment]
I'm listing below all of the permutations I'm doing and will open new tickets for any issues: 

trench - survey
trench - feature
trench - legacy
trench - locus
trench - cm

survey - feature
survey - trench
survey - legacy
survey - locus 
survey - cm

feature - trench
feature - survey
feature - legacy
feature - locus 
feature - cm

locus - trench
locus - survey
locus - legacy
locus - feature
locus - cm

cm - trench
cm - survey
cm - feature
cm - legacy
cm - locus

start - trench
start - survey
start - feature
start - legacy
start - locus
start - cm

**Comment by luizaogs** [comment]
Ok, so look at the tickets linked above. I think those are all the layouts where search could be used, but if not let me know.

**Comment by urapadmin** [comment]
I added tag analysis in your permutation list since you can search for a tag and clicking on it will get you to the analysis page

**Comment by urapadmin** [comment]
but don't touch it, I will attend to the errors you already found first. It is all more or less the same, I hope.

**Comment by urapadmin** [comment]
### 13.6.12
Search should work now. Navigating to and from Tags had an issue, as well. But that is fixed, too.

**Comment by luizaogs** [comment]
Everything is working (including tag analysis), except for #1896

**Comment by luizaogs** [comment]
I believe this is good now!
