### ISSUE TITLE
empty recently viewed

### ISSUE THREAD

**Issue by luizaogs** [arch-kiosk/arch-kiosk-office#1891]
Um. Don't kill me. Recently viewed is not working anymore, it seems. In 13.6.10. And yes, I did check and the max number of entries for that is 10 in configuration but I am navigating around and nothing is getting added to it.

Layout history seems fine.

**Comment by urapadmin** [comment]
### recording 13.6.11
- wow. we need a new developer, That would really fix things. Until then I hope the old one got this now.

**Comment by luizaogs** [comment]
Um no new developers, thanks. We like this one.
