### ISSUE TITLE
search navigation: feature and back 

### ISSUE THREAD

**Issue by luizaogs** [arch-kiosk/arch-kiosk-office#1892]
I'm testing #1890 but going to open new tickets for any issues otherwise that one might get crazy. 

I'm working on searches that start on a feature layout, go somewhere else, and come back to the feature layout. 

Starting in feature F300, I searched for LA and got there just fine. On the way back through the layout history, I clicked on F300 but instead of the expected feature layout I got a survey layout: 

<img width="1025" alt="Screen Shot 2022-10-25 at 7 34 15 AM" src="https://user-images.githubusercontent.com/67970402/197774149-577f4692-46a1-4ef4-80d0-4162139ff8b3.png">

This does not happen when clicking on F300 on recently viewed, which correctly takes me to the feature layout as I expected.

The same exact issue happens when going from: 
feature - legacy

**Comment by urapadmin** [comment]
### 13.6.12
now it should work
