### ISSUE TITLE
search navigation: locus and back

### ISSUE THREAD

**Issue by luizaogs** [arch-kiosk/arch-kiosk-office#1893]
Again, this comes out of #1890. I'm looking at locus to other layouts and back, navigating through the search and the navigation history. 

When going from a locus to a survey unit and back: 

Started in locus 511. Search for survey unit 02 and got there just fine. When going back to locus 511 through the layout history, I get this: 

<img width="1023" alt="Screen Shot 2022-10-25 at 7 42 29 AM" src="https://user-images.githubusercontent.com/67970402/197775996-a9e65e56-7ee1-4eba-b033-34768f921354.png">

The same happens when navigating back to the locus through the recently viewed. 

And the same thing happens when doing the following: 
locus - legacy (only through the layout history, going back through recently viewed works fine)
locus - feature (only through the layout history, going back through recently viewed works fine)

**Comment by urapadmin** [comment]
### 13.6.12
- should be fine now
