### ISSUE TITLE
search navigation: cm and back

### ISSUE THREAD

**Issue by luizaogs** [arch-kiosk/arch-kiosk-office#1894]
Comes out of #1890. I'm starting in a cm layout and going elsewhere through the search. 

When going from cm to a survey unit and back: 
Started at LA-007-1. Searched for survey unit 02, and getting there worked fine. 
When trying to get back to LA-007-1 through the layout history, I get this: 

<img width="1026" alt="Screen Shot 2022-10-25 at 7 51 44 AM" src="https://user-images.githubusercontent.com/67970402/197777794-630139a0-4b0d-4146-af69-069738534669.png">

This happens through both layout history and recently viewed. 

The same happens in: 
cm - feature

**Comment by urapadmin** [comment]
### 13.6.12
That was even hard to spot. It should now show the right Unit LA when coming back.
