### ISSUE TITLE
search navigation: survey and back

### ISSUE THREAD

**Issue by luizaogs** [arch-kiosk/arch-kiosk-office#1895]
Testing #1890. Using the search to navigate from survey layout elsewhere. 

Starting in survey unit 02. Going to feature F300 through search worked fine. 
Going back to survey 02 through the layout history gave me this: 

<img width="1019" alt="Screen Shot 2022-10-25 at 8 04 03 AM" src="https://user-images.githubusercontent.com/67970402/197780470-300c0e1a-58c1-4a19-bd65-c6848983c742.png">

Going back through the recently viewed worked fine.

The same happened in: 
survey - legacy

**Comment by urapadmin** [comment]
### 13.6.12
- should be fixed
