### ISSUE TITLE
button for testers: Switch between su_ceramics (plus preprocessing) and warecode pottery

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#1897]
Nobody will ever remember all the steps, so I guess a button would make all our lives much easier.

**Comment by urapadmin** [comment]
### recording 13.6.14
- very important milestone :)
- One of the reasons it is so hard to ever see the ceramic preprocessing in PVD is that we have a ton of legacy collected material without a collected material type (bulk/small find etc.). If it isn't bulk it does not show in ceramics preprocessing. When you open a collected material that does not have a cm type, you will get a warning from now on. Then you might remember this explanation.

**Comment by urapadmin** [comment]
ah, by the way: The button is in "registrars and specialists" below the pottery button. And it should show only in test mode.

And and also by the way: You usually don't need to take care of the "Your workstation got an update" or whatever messages. I just keep forgetting not to click okay at some point during roll out 🙄

**Comment by luizaogs** [comment]
And here I thought I was killing the game by following all of your uploading instructions :) Ha ha.

**Comment by urapadmin** [comment]
you got yourself a bonus logo :o)

**Comment by luizaogs** [comment]
I love my logo.

**Comment by luizaogs** [comment]
Heh I click on it and get this: 

<img width="1021" alt="Screen Shot 2022-10-27 at 5 32 21 PM" src="https://user-images.githubusercontent.com/67970402/198410443-951aae3a-7d25-47da-a833-698427028a4c.png">

**Comment by urapadmin** [comment]
Arg. I forgot the darn "s". It is ceramics. Hmpf.

**Comment by urapadmin** [comment]
still a Covid 🧠

**Comment by luizaogs** [comment]
Maybe a tired one, no? It's uh late there.

**Comment by urapadmin** [comment]
💤 yup (but that's not it). I'll fix it tomorrow, though.

**Comment by luizaogs** [comment]
Yes, I'm now giving you the evil eye too. Sleep.

**Comment by urapadmin** [comment]
hm. Nothing to fix here, as far as I can see. I think that must be a wrong setting that got synchronized in PVD. 
If you click on Activate Warecode Pottery and then again on activate su ceramics, do you still have the issue?

**Comment by luizaogs** [comment]
Hmm no. I click on Activate Warecode Pottery and get the preprocessing warning about only appearing with ceramic or ceramic-diag. 

Then if I click on ceramics under registrar that's when I get that big scary error (screenshot above).

The error might be elsewhere, actually, if there is one: I never see "activate su ceramics." I seem to be stuck on the "activate warecode pottery" option.

**Comment by lbestock** [comment]
And I tested this last night (but was too tired to report back) and also never got the "activate su ceramics." Because the "activate warecode" didn't do anything. I had it properly configured, and could make pre-processing and SU processing records. But when I hit that activation button nothing changed, it was still just SU ceramics.

**Comment by urapadmin** [comment]
it must be because there is some nonsense in the ceramics module entry. Con you please go to the config/modules and set it to "pottery_processing"? After that the switch buttons should work.

**Comment by lbestock** [comment]
No, it still stays stuck on warecode for the processing. It changes preprocessing to tell me that the results of warecode processing are about to come here... And nothing happens.

**Comment by urapadmin** [comment]
wow. No wonder this happens on PVD and not on my development system. It is pretty random because of #1899 
### recording 13.6.14
- this instance of the bigger #1899 should be fixed

**Comment by luizaogs** [comment]
Ok wow this is cool. I love it.
