### ISSUE TITLE
👺 FileMaker Hate Part 999: = is NOT equals. 🧨 

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#1899]
FileMaker keeps surprising me with its non-standard idiocy. Too late in the game I found out (or I had forgotten after I found out, because something like that is too dumb to learn) that the operator "=" does not mean equals but "occurs". So whenever I am searching for something in the background (and I do that a lot!) all my searches are not finding records where a field equals a value I find all records where a field contains the word I am searching for. That is just horrible because it is something entirely different.
If I search for "ceramic" I get records with "ceramic - diag", "not a ceramic sherd" etc. AAAaaaaaagghhgghdshadsfkjwaer ##234ö"§$§$&!.

That is a MONSTER BUG. I mean really like this: 
![image](https://user-images.githubusercontent.com/38838314/198690196-bd5f89da-fbe1-4785-a651-08038d3a2117.png)

It is virtually untestable because e.g. EVERY BLOODY SINGLE CONFIGURATION KEY was searched for in the wrong way. 
And, yeah, for filemaker "this_does_not_even_have_a_space" = "even" is true! It is unbelievable. Only Apple can have such an idea. That is like putting the right mouse key to the left just to be different. Or no, just out of ignorance of all the people out there who already have understood something.

**Comment by urapadmin** [comment]
### recording 13.6.15
horrors. I had to change that about 30 times in the code all across the whole software. Most of the time I think it didn't make much of a difference (otherwise it would not have occurred that late in the game). 

- So mostly this was about finding configuration keys, which is really not testable because that happens all the time everywhere. Just be particularly alert for strange behavior (can even be labels that are missing, buttons missing, fields not accessible) you have not seen before or did not expect.

- In particular please look at locus relations (the whole thing, like creating them, creating the opposite, deleting them, making sure that the images are processed correctly)

I so loathe this software. The bugs may just eat it one day.

**Comment by luizaogs** [comment]
That's a really scary monster. Oh man!

**Comment by luizaogs** [comment]
Locus relations are totally fine.

**Comment by luizaogs** [comment]
Ok I have also gone through every layout and created new loci, cm, features, survey units, etc., and I cannot find anything wrong. But I am not sure if you want this closed or under observation.

**Comment by urapadmin** [comment]
No, let's leave it behind. One must leave such things behind.
