### ISSUE TITLE
ceramics module setting does not synchronize

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#1903]
Okay, I found out why the setting of the pottery module is not synchronizing: it is indeed not supposed to. Interesting. not sure, why I made that choice. I guess I thought I don't want anybody to change this permanently. So I have to initialize the templates for the different projects with the correct module myself. Hm. I really must not forget that with URAP or you would be changing this every day because it would never synchronize. 

Hm. 

...

I think, it is safer to make this key synchronize. I'll patch it as soon as #1836 is available. 
- [x] #1836 

_Originally posted by @urapadmin in https://github.com/arch-kiosk/arch-kiosk-office/issues/1901#issuecomment-1295868241_

**Comment by urapadmin** [comment]
ja, Covid 🧠. It isn't a big issue for URAP because it would only be reset to something else if it gets patched - which it does not. 
Nonetheless, I will switch it to a synchronizing config entry.

**Comment by urapadmin** [comment]
### recording 13.7.5
- You need #1913 first to test this
- The sync_level should be set to 1 for this key (means: the key synchronizes regularly

**Comment by luizaogs** [comment]
Looks fine in PVD. Let me check USTP test...

**Comment by luizaogs** [comment]
Yep, USTP test looks fine, too.
