### ISSUE TITLE
Filemaker: navigating back from warecode pottery to locus brings up FM tools

### ISSUE THREAD

**Issue by lbestock** [arch-kiosk/arch-kiosk-office#1904]
When navigating back from warecode pottery to a context using navigation for some reason the Filemaker tools that are usually hidden are present and clickable:
![image](https://user-images.githubusercontent.com/49291909/198904640-f7ca7151-c6d6-456a-9b83-30a2aee1548c.png)
They go away again if I go back to start, and do not reappear if I go to the context again.
If I use the back button from the warecode pottery and then use navigation to get to the context I do not have the same problem. And if I navigate from warecode to the trench instead of a locus, I also do not encounter the problem, so it seems to be something specific to going from warecode to locus via navigation (recently viewed in this case, because it's my favorite).

Interesting. Does it help you to catch it to know that it doesn't happen from SU ceramics? In any case, it doesn't happen from SU ceramics.

_Originally posted by @lbestock in https://github.com/arch-kiosk/arch-kiosk-office/issues/1795#issuecomment-1296366054_

**Comment by urapadmin** [comment]
### 13.7.2
fixed

**Comment by luizaogs** [comment]
Yup.
