### ISSUE TITLE
synchronization: SU ceramics do not survive synchronization in PVD 13.7

### ISSUE THREAD

**Issue by lbestock** [arch-kiosk/arch-kiosk-office#1905]
Testing in PVD where there is a test button to shift ceramics modes.
Module configuration does not yet synchronize (#1903).
Records made in SU ceramics seem to get lost in this cycle and we have never before lost records.

What happened:
I made a bunch of records, including SU ceramics records.
I uploaded and synchronized.
I downloaded again.
I had to sign in as admin to change the module back to pottery_processing.
I noted that previously made warecode records were intact. 
I logged in as test.
I used the button in registration to shift to SU ceramics.
I could not find the ceramics records I had previously made. In fact, no CMs had a little pot indicating that they had already had SU ceramics records. 

To be sure I was not crazy, I made a new SU record with a photo.
I uploaded and synchronized.
Lo and behold it is not there in the file repository. 
I downloaded again.
I switched the module again.
I noted that my warecode pottery was still there.
I switched to SU pottery.
Absent as expected from the File Repository result.

I will quit messing around - this seems like a big one. For logs if it's helpful I've been working only in unit PA this evening, and there should have been two uploads with SU ceramics records that now don't exist.

**Comment by urapadmin** [comment]
Not a bug. su ceramics do not get synchronized by Kiosk because the PVD Kiosk is configured to use warecode pottery. A project cannot switch between those. This is merely a testing issue.
