### ISSUE TITLE
kiosk director's view: formatting issue

### ISSUE THREAD

**Issue by lbestock** [arch-kiosk/arch-kiosk-office#1906]
Tiny little formatting funniness in director's view in Chrome on my Mac:
![image](https://user-images.githubusercontent.com/49291909/198912266-781ddf93-9cc3-4d63-9716-d45a2fd2c5e1.png)
The "files" widget is not confined to its bounding box, and stuff shows up below it.

**Comment by urapadmin** [comment]
### kiosk 1.2.10
This might be better now
