### ISSUE TITLE
sherd analysis in USTP?

### ISSUE THREAD

**Issue by luizaogs** [arch-kiosk/arch-kiosk-office#1907]
A question. Laurel's little ceramics configuration manual in the Drive says that USTP uses preprocessing but not sherd analysis. But I'm in USTP test in 13.7.2 and it's there. Should it just not show up for USTP? Is it dangerous to have that on there if they do not use it?

**Comment by luizaogs** [comment]
(The one that is turned on is su, not warecode)

**Comment by urapadmin** [comment]
they don't use it but they have also not complained. I'll switch it off one day.

**Comment by urapadmin** [comment]
needs #1903

**Comment by urapadmin** [comment]
### recording 13.7.3
- that should not happen again in future versions

**Comment by luizaogs** [comment]
Ha so your comment above was rather for #1908, I think? And this seems to have been addressed by #1910 ? Or are you still working on it?

**Comment by urapadmin** [comment]
erm. ja. doing too many things in too many tabs at once

**Comment by urapadmin** [comment]
In fact this here is really USTP. It needs configuration once I am updating the USTP server next time.
So this here must stay open.

**Comment by urapadmin** [comment]
:brain, you know

**Comment by luizaogs** [comment]
yes sir

**Comment by urapadmin** [comment]
### 13.7.5
see #1903

**Comment by luizaogs** [comment]
Yes, this is fine in USTP test. But I leave it open and in test for when USTP itself gets updated.
