### ISSUE TITLE
USTP 13.7.2: "LA" as default in search by text

### ISSUE THREAD

**Issue by luizaogs** [arch-kiosk/arch-kiosk-office#1908]
I'm looking at navigation in USTP and everything seems to be working fine, but I just noticed something funny: when searching by text "LA" is for some reason already in the search box even if I never typed that in there? The by identifier tab doesn't have any default entry, but LA is that for by text. 

To make sure I'm not crazy I'm going to download another workstation...

Yep, LA is there in the search by text already. This happens both in the start page search and if I search for things through the burger menu.

**Comment by urapadmin** [comment]
### recording 13.7.3
- that should not happen again in future versions (including this one): No matter which project, the first time you open this after a download, the search field should be empty. That is true, by the way, for all of the filters in locus, unit etc. It could have happened anywhere there, too, depending on what I did last in the development environment.

**Comment by urapadmin** [comment]
'tis fixed
