### ISSUE TITLE
configuration help locus_form has obsolete advice

### ISSUE THREAD

**Issue by lbestock** [arch-kiosk/arch-kiosk-office#1915]
The configuration key admin: locus_form has instructions that are different from the value currently in the key. When I change it to follow the advice in the help text I am unable to enter a locus at all. Do I need to change a different key, too, or is this obsolete? Either way not something a user of my level can do (but as it is not clear it should be, I have not said this is a bug).
![image](https://user-images.githubusercontent.com/49291909/199357054-a16e5d1a-9c73-49ba-b484-b1493ef4ceea.png)

**Comment by urapadmin** [comment]
just an old help text. The key is still active. But we are now at locus_edit_with_qce.

**Comment by urapadmin** [comment]
You will find quite a few configuration keys that you should not be using, throughout the configuration.  I am not sure it is worth the while of any of us to go through all of them.

**Comment by lbestock** [comment]
I don't usually mess around in there except to accomplish specific tasks.

**Comment by urapadmin** [comment]
why is this closed now?

**Comment by urapadmin** [comment]
for a more curated configuration we already have #1564 as a mid-term plan. The general configuration will always be a bit chaotic. It is like the windows registry. You wouldn't want to have a look at that.

**Comment by lbestock** [comment]
Because you answered my question and don't intend to do anything about it?

**Comment by urapadmin** [comment]
since now it is a ticket, I will attend to it
