### ISSUE TITLE
Apple: wrong date and time always on FM files in the OS so they are hard to find

### ISSUE THREAD

**Issue by lbestock** [arch-kiosk/arch-kiosk-office#1919]
Presumably this is an Apple sucking kind of thing, but it has driven me a little nuts and I don't know if you know about it or can do anything. When I am on my laptop, the filemaker file always gets the wrong date and time. Given the state of my downloads folder (which admittedly is an intersection then of an Apple problem and a Laurel problem) I can never find my file easily - it should be the most recent one, and it isn't. Since the date and time are all over our stuff and necessarily so and properly so, I don't know how Apple thinks this is the case.
![image](https://user-images.githubusercontent.com/49291909/200387655-67a9aec3-2f84-460c-827f-0b2b0bf4a165.png)

**Comment by lbestock** [comment]
I mean, I don't even know how Apple has different created on and modified on dates on there. That file didn't exist until an hour ago, and then I modified it today, too.

**Comment by lbestock** [comment]
Oh god. Where is the brain icon? I can't find it. That was not the right file even.

**Comment by lbestock** [comment]
Well, I found it and it had the right time stamps on it, it just doesn't show up in my recents at all. And a search for urap didn't give anything from today. Which is still dumb and I don't get it but that can't be anything you can have anything to do about, and I should have taken the nap I came home to take.

**Comment by urapadmin** [comment]
I cannot help you with that operating system. It does what it does. And I have indeed no control over what file date FileMaker is setting and which one MacOS is reading. The difference between created and modified is a looong story developers have been getting nuts about for decades, but you would not want to hear about it. 

Can we close this?

**Comment by lbestock** [comment]
Oh yes of course, it is a big nothingburger.
