### ISSUE TITLE
kiosk: error when creating user

### ISSUE THREAD

**Issue by luizaogs** [arch-kiosk/arch-kiosk-office#1920]
So I'm trying to create a test user (operator) to test #1878 and I keep getting the error in the screenshot below. It's very possible that I'm doing something wrong but I've created users successfully in the past so not sure what it might be.

<img width="1512" alt="Screenshot 2022-11-07 at 9 10 47 PM" src="https://user-images.githubusercontent.com/67970402/200466189-7636128e-34e5-4cb0-9f63-f2f637582857.png">

**Comment by urapadmin** [comment]
### kiosk 1.2.9
- fixed
