### ISSUE TITLE
small typo in file repository download

### ISSUE THREAD

**Issue by luizaogs** [arch-kiosk/arch-kiosk-office#1922]
Sorry. Just pointing it out because otherwise it will drive me nuts - do with it what you will :) 

"Download initiated, might even finished" should I guess either be "download initiated, maybe even finished" or "download initiated, might even be finished".

yours truly,

<img width="694" alt="Screenshot 2022-11-08 at 8 08 39 PM" src="https://user-images.githubusercontent.com/67970402/200719873-6dadb4fe-1fd0-43bd-90a4-7a36aeff1861.png">

**Comment by urapadmin** [comment]
Ha! I even saw that one and though of you :o) 
### kiosk 1.2.10
You found it, so I fixed it.

**Comment by luizaogs** [comment]
The most important ticket of all.
