### ISSUE TITLE
Kiosk: Hub docks invisible

### ISSUE THREAD

**Issue by lbestock** [arch-kiosk/arch-kiosk-office#1924]
Kiosk 1.2.10. Logged in as myself, the Hub looks empty:
![image](https://user-images.githubusercontent.com/49291909/200973115-3a03b6c2-90c7-4569-9f1d-472216c81e0a.png)

I tried to create a new dock but was told the dock name was already in use. 
I tried to create a new dock with a name I knew had not been used, and that seemed to be successful but was still invisible.

I have admin privileges (I can see administration just fine).

**Comment by urapadmin** [comment]
the urap_test and test servers are kaputt. I have no idea why, but I need to go to bed. Tomorrow.
Please stop using it and fuzzing around.
