### ISSUE TITLE
Registration view selection not fully working?

### ISSUE THREAD

**Issue by luizaogs** [arch-kiosk/arch-kiosk-office#1928]
13.7.5

Not sure whether I’m misunderstanding how this should work (and if you have changed this and it is just not yet in this version ignore me), but I am trying to use the filter/selection thingy in registration and I think some of it is not working? 

These are the finds from today with no filter:
![C093DDA1-932D-4141-A72A-AEDF921FB520](https://user-images.githubusercontent.com/67970402/201500691-a0abb861-f653-4d9d-b07f-5ea2183862b9.png)

The not home filter works fine, since it only shows me 814-1 because it is the only one not home. However, home not registered makes all of the records disappear and I think it should instead show all of them but 814-1, since I have registered none of them. And “something left to do” doesn’t select anything at all and leaves all records on the screen, but I expected to only see 814OR since it is the only one with something in the to do column.

**Comment by urapadmin** [comment]
"something left to do" tackled in #1929

**Comment by urapadmin** [comment]
in #35 you were well trained using this :o)

**Comment by urapadmin** [comment]
### the explanation 
okay, so here is how it works (it works as it was designed to work, which is not necessarily what we would want):
- "not home" lists everything that does not have "H" in the done field
- "home not registered" lists everything that has "R" in to do and "H" in done but not "R" in done. 

On Uronarti the workflow was like this: The common-and-garden registrar checks which bags came back from the field and adds a H for everything that actually showed up in the hut. That's what "not home" helps with.

Only "special finds" go through object registration. so the common-and-garden registrar gives it a "R" in to do (now we can do that automatically with the special finds default #1817). 

The super special object registrar (who is usually also the object photographer, namely Laurel) uses "home not registered" to look at all the items that are actually in the hut and are supposed to go through registration. If registartion is done they get a R in Done. That makes them disappear from the list.

### 13.6.7
- "something left to do" lists all materials that do not have anything done and all materials with a "to do" code that does not show up in "done" (while a done code that does not show up in to do is okay). That is why all your empty lines show up. There must be something to do if nothing at all has been done (at least H for home). Here I have made a slight change in 13.7.6: before that lines would also show up if they have no "to do" even though they have a "done". That is not any longer the case now

**Comment by luizaogs** [comment]
Ah. Ok clearly I didn't know how it was supposed to work before (and it is now working as you say it should). As far as whether this is how it should work, I defer to the super special object registrar @lbestock.

**Comment by lbestock** [comment]
The super special objects registrar recognized her own limitations and is off duty for the evening. I will give it a whirl tomorrow.

**Comment by lbestock** [comment]
Two thoughts:

Why is there an H in "to do"? It should never be clicked, right? And hence causes confusion.

The checkboxes should be ordered by workflow, not alphabetically. Their order should be the same as the rubric on the right.

**Comment by lbestock** [comment]
Or H should be automatically clicked in "To Do" as envisioned in #34 - same difference.

**Comment by urapadmin** [comment]
yes, so #34 needs testing (after configuration)
I would prefer that because it avoids special treatment of the H in the code. 
Though, I wonder if there can be collected material records without an H. Legacy records?

**Comment by luizaogs** [comment]
Is there anything to do here besides #34 ?

**Comment by urapadmin** [comment]
I consider this done. Laurel has to care for #34
