### ISSUE TITLE
registration: redesign status pop-over based on a web viewer

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#1931]
The native filemaker means are exhausted with the current pop-over. And as usual even though it is overly complicated and wrought, the result is not satisfactory. What users really would want is a pop-over that simply shows todo and done in real language and in chronological (or configuratble) order. 
That can only be done using a webviewer and javascript and it will take me 2 to 3 days, I suspect.

**Comment by urapadmin** [comment]
### recording 13.8.1
- the popover is now using a web-viewer and hence it looks the way one would expect it: task, todo, done.
- the priority codes (something with an !) are special and need special treatment everywhere. Here if you click on a C!, the "C" must get checked, too. On the other hand if you uncheck a "C", the "C!" must be unchecked, too.
- if something isn't "todo", it cannot be "done", so if you uncheck a todo, the done gets unchecked, too.
- on the other hand, if you check a "done", the todo gets checked automatically.
- if the configuration key 'edit_registration_status_in_cm' is set to registrar and you aren't a registrar or it is set to "nope", the checkboxes in "done" must be disabled. 
- yes, if they are disabled and you uncheck a todo, the "done" gets unchecked although you are not allowed to change a "done". That's okay for me.

**Comment by luizaogs** [comment]
> * on the other hand, if you check a "done", the todo gets checked automatically.

Ok, should I be able to check a "done" without checking a "to do"? Because I currently only see checkboxes under done if I check its counterpart in to do: 

<img width="588" alt="Screenshot 2022-11-20 at 12 11 44 PM" src="https://user-images.githubusercontent.com/67970402/202915783-c1032c63-bc9f-4d0f-a788-7d796c1d04eb.png">

**Comment by luizaogs** [comment]
> * if the configuration key 'edit_registration_status_in_cm' is set to registrar and you aren't a registrar or it is set to "nope", the checkboxes in "done" must be disabled.

Setting the configuration key to "nope" does not disable the checkboxes in done.

**Comment by urapadmin** [comment]
> > * if the configuration key 'edit_registration_status_in_cm' is set to registrar and you aren't a registrar or it is set to "nope", the checkboxes in "done" must be disabled.
> 
> Setting the configuration key to "nope" does not disable the checkboxes in done.
> 
> And if I'm not registrar I can't even see the options under registrar and specialists. That's right, no?

We are looking at the collected material layout here, right? Because it is only there that the "edit_registration_status" key is relevant. It controls what is possible in the collected material layout itself (not in the registration layout, which indeed, you can only enter as registrar to begin with)

**Comment by luizaogs** [comment]
Nope, I was totally looking in registration. I'll check again.

**Comment by luizaogs** [comment]
Ok, that is all fine in the cm view actually. So the only thing potentially left to do here is whether you want someone to be able to check a done without being able to check a to do first (see my first comment above). If it's fine as is this can be closed.

**Comment by urapadmin** [comment]
> > * on the other hand, if you check a "done", the todo gets checked automatically.
> 
> 
> 
> Ok, should I be able to check a "done" without checking a "to do"? Because I currently only see checkboxes under done if I check its counterpart in to do: 
> 
> 
> 
> <img width="588" alt="Screenshot 2022-11-20 at 12 11 44 PM" src="https://user-images.githubusercontent.com/67970402/202915783-c1032c63-bc9f-4d0f-a788-7d796c1d04eb.png">
> 
> 

honestly, I am not sure it you can get there anymore. I could in my development version for a while, so it might be a non-issue. But; you still can type H in the done field (pop-over and fields can both be used) but not in the todo field. But I think in that case I add the todo check when the pop-over appears.

**Comment by luizaogs** [comment]
Oh yes, that works just fine.
