### ISSUE TITLE
registration: locus and unit filter

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#1932]
@lbestock wrote:

The one substantial change I would make to the interface is what the title of the ticket says. Currently there is no way to sort or even see by unit or locus. That's because it was designed for Uronarti, where that information is part of the identifier. As one can clearly see in PVD now, with different identification methods that information is no longer clear in registration.  And since some projects separate CM by trench or locus, for instance putting everything from trench 4 on one table, and everything from trench 5 on another before the registrar attacks, we want to not only be able to see that but to sort by it and - if it works in the layout - be able to exclude all but one trench or all but one locus.

_Originally posted by @lbestock in https://github.com/arch-kiosk/arch-kiosk-office/issues/1816#issuecomment-1312607665_
      
so we need a filter much like in the locus or collected material list. By unit or unit/locus. It could be sorting, too.

**Comment by urapadmin** [comment]
### 13.7.6 
- there is the usual filter button now for unit and locus. Should be self-explanatory
- the difference between this one and those somewhere else is that the changes in the filter pop-over apply only after you press the ok button. If you close the pop-over any other way (tapping somewhere outside of it), the initial values should be restored and nothing should happen to the list.

**Comment by luizaogs** [comment]
This is all working, except for the drop-down for contexts (which, I don't know if there is supposed to be one there -- but there is one for trench, so I assumed).

**Comment by luizaogs** [comment]
Oh wait, also: if I clear the identifier from either the trench or the context box by using one of the minus signs the other one also gets deleted. I expected that only the one I actually deleted with the minus sign would disappear.

**Comment by urapadmin** [comment]
if you delete the unit, the locus needs to be deleted as well - it is related to the unit.

If you delete the locus the unit should stay. Does it not?

The dropdown for locus gets populated once you have selected a unit. Perhaps I should not even show the locus filter as long as there is not unit set.

**Comment by luizaogs** [comment]
The locus does not stay if I delete the unit.

**Comment by luizaogs** [comment]
Or rather the opposite of that. Maybe I also have some sort of brain disease.

**Comment by urapadmin** [comment]
what?!? Now you try to confuse me. If you delete (or change) the unit the locus mustn't stay. That is by design.
If you change (or delete) the locus filter it should not affect the unit filter.

**Comment by luizaogs** [comment]
Hm. Ok well the first time I tried it I clearly thought the locus filter also affected the unit filter, so seems not. 

Then the only thing to do here still is figure out whether you want to show the locus filter before one selects a unit.

**Comment by urapadmin** [comment]
that list has already severe issues with space (Think like PACHA!). I could add the unit. But do we really need the context in the list? Isn't the context always obvious from the cm identifier?

**Comment by urapadmin** [comment]
however, this is about filtering and not about the list, so you are in the wrong ticket :o)

**Comment by lbestock** [comment]
Whoops :) I must have hit the hot chocolate too hard.

**Comment by urapadmin** [comment]
### recording 13.8
- the udpaitgn message is now gone
- the locus filter is only visible if the unit is visible. Should it really be an issue in the future that one needs to know the unit to filter by locus we can use the new locus find popup from #1837 to search for a locus. But for now I am too lazy to change this again.
