### ISSUE TITLE
message when entering registration

### ISSUE THREAD

**Issue by luizaogs** [arch-kiosk/arch-kiosk-office#1935]
I got the following when entering the registration layout: 

<img width="1018" alt="Screenshot 2022-11-16 at 5 56 50 PM" src="https://user-images.githubusercontent.com/67970402/202312732-37456fe4-7050-4a67-840c-41983e12f731.png">

Pressing ok made it go away.

**Comment by luizaogs** [comment]
I also seem to get it whenever I do something in the registration layout (filtering, etc.)

**Comment by urapadmin** [comment]
that is correct. You don't like the typo? :o) The Covid-Brain makes funny typos. One can literally see how my brain works things out in the wrong order.

**Comment by lbestock** [comment]
The Covid-Brain over here needed to be told that was a typo of something that was supposed to make sense, and then took quite a turn around the block before it figured out what sense it made.

**Comment by luizaogs** [comment]
I wish you guys didn't have covid brains :(

**Comment by urapadmin** [comment]
enim si retteb !

**Comment by luizaogs** [comment]
That's a bit mean :)

**Comment by lbestock** [comment]
Ooo ooo I got it! Finally.

**Comment by urapadmin** [comment]
the old person over here had his tea and will go 💤 💤 💤

**Comment by luizaogs** [comment]
Before 3am??? Wow, thank god.

**Comment by urapadmin** [comment]
### 13.8
- should be gone
