### ISSUE TITLE
registration: missing sortable column headers

### ISSUE THREAD

**Issue by luizaogs** [arch-kiosk/arch-kiosk-office#1936]
I went to configuration to test out the new key for identifier sort method in registration. When I went back to registration via the start page the sortable column headers were invisible: 

<img width="1023" alt="Screenshot 2022-11-16 at 6 15 16 PM" src="https://user-images.githubusercontent.com/67970402/202315235-bbd87a58-fffc-442a-bb4b-435295c5db77.png">

They showed up when I clicked on the empty space in the gray header and worked fine after that.

**Comment by urapadmin** [comment]
I have seen this, too. But it seems to be rare I can't find a way to trigger it. 
You?

**Comment by luizaogs** [comment]
I seem to always get it when I first enter the registration layout. It does not matter if it's the first time I've ever entered the registration layout in that database, or if I've logged out and logged back in.

**Comment by urapadmin** [comment]
that gives me a hint

**Comment by urapadmin** [comment]
### recording 13.8.3
got it
