### ISSUE TITLE
inventory: images not appearing in file repository under "inventory" record type

### ISSUE THREAD

**Issue by lbestock** [arch-kiosk/arch-kiosk-office#1940]
URAP inventory includes images. They cannot be seen either in FM or in the File Repository.

I was looking at the URAP inventory to figure out where which object photography supplies are. In some cases I need to see the pictures associated with the records. I can tell there are such pictures because the jpg icon is there, for instance in the light holding arm record. That they didn't get transfered to the FM file makes sense because they have no context and file picking is set to contextuals, low. but I don't know why they are not visible in the File Repository when I choose "inventory" as the record type and have nothing else selected. No files match my criteria.

**Comment by urapadmin** [comment]
the issue here is rather that there is a record type "inventory". I don't think record types work at all without a context.

But for the time being you can always find the inventory images under the tag "inventory"

**Comment by urapadmin** [comment]
I have added the inventory photos to the FileMaker database with file picking

**Comment by lbestock** [comment]
Inventory images for URAP visible in FM as expected.

But the other issue - one CAN use "record type" without context to search the File Repository - it is in fact one of the ways I use the file repository most often. So since record type inventory cannot return any photos it really would be better that it not be possible to even select inventory in record type.

**Comment by urapadmin** [comment]
### Kiosk 1.4.6.0
- only the actually used record types are shown now. Please check if e.g. in urap this also includes pottery! Or in USTP.
- the "record type" selection addresses only parts of the "archaeological record". The records form the "inventory" are not strictly part of the archaeological record (hence they are not connected to any archaeological identifier). So you won't find the "Inventory" here anymore
- Inventory records can be addressed with the tag "inventory" in both file repository and file picking

**Comment by luizaogs** [comment]
PVD includes pottery too and the images come up in the file repository if I use "pottery," so I checked that here and it's fine. 

I was trying to test the file picking part but my workstation is pending forever so can't do that at the moment.

**Comment by urapadmin** [comment]
:computer server running again...
