### ISSUE TITLE
temporary free input / edit identifier: special solution for material based identifiers

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#1941]
Because #1716 and #1705 get too hard to handle for even a trained standard user an alternative for the common material based identifiers is this:

When temporary free input is on and a new identifier is created or an existing identifier is edited and the regular identification method is using idgen_material the free input identification method should be idgen_material_free_input.

If that is not the case, an error will occur.

The popup that takes the free input asks for the whole identifier, as usual, and for the serial id (if required: idgen_material comes in two flavors: with and without an additional serial id). It also asks for a material selection. And that is where the improvement for the user lies: selecting the material is easier to understand than typing a cryptic domain.

**Comment by urapadmin** [comment]
### recording 14
- both ustp and pasu are using idgen_material and version 14 is out now on their test servers

**Comment by luizaogs** [comment]
USTP is working fine. But it seems like you want PACHA tested as well?

**Comment by urapadmin** [comment]
Hm. The PACHA test server is not up to date. Let's skip it.
