### ISSUE TITLE
pasu ceramics: two red boxes in layout

### ISSUE THREAD

**Issue by luizaogs** [arch-kiosk/arch-kiosk-office#1942]
v13.10, Mac OS 13.0, FM Pro 19.6.1

Going into su ceramics gives me these two red outlined boxes: 

<img width="1031" alt="Screenshot 2022-12-12 at 9 38 01 PM" src="https://user-images.githubusercontent.com/67970402/207220858-e2913006-4c6b-4798-a583-68e9bb78b646.png">

If I click on a fragment I get this, but I assume I am not supposed to be seeing it? 

<img width="1026" alt="Screenshot 2022-12-12 at 9 40 11 PM" src="https://user-images.githubusercontent.com/67970402/207220906-5581e3ec-561e-4f59-ba7b-8a472e7ab026.png">

**Comment by urapadmin** [comment]
### recording 14
- they should not be visible anymore
