### ISSUE TITLE
temporary free input with idgen_group not working

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#1943]
idgen_group creates a "serial" id but without a domain! So this must be handled differently than idgen_serial.

_Originally posted by @urapadmin in https://github.com/arch-kiosk/arch-kiosk-office/issues/1716#issuecomment-1355501335_

**Comment by urapadmin** [comment]
### recording 13.11
- best tested with projects that actually use idgen_group somewhere in an identification method. I think PACHA does that, but USTP, too. So perhaps wait until it gets rolled out there or make sure you use idgen_group in PVD.
- usually tested in the context of #1944 but should work for all other record types as well, of course.

**Comment by urapadmin** [comment]
### recording 14
- USTP is using idgen_group for loci.

**Comment by luizaogs** [comment]
Working, I think.
