### ISSUE TITLE
temporary free input override: add new / edit locus

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#1944]
### recording 13.11
adding or editing loci with temporary free input on and whatever identification method active should work, but identification methods using the following generation function are typical for loci:
- idgen_serial
- idgen_group

**Comment by luizaogs** [comment]
Both of those are working just fine, I think. Should I be testing any others?

**Comment by urapadmin** [comment]
for loci these are really the most common.
idgen_partial_input might be used in pasu or pacha, if I am not mistaken.

**Comment by luizaogs** [comment]
Eesh I don't think that one is configured for PVD. Do we wait to test this in pasu or pacha?

**Comment by urapadmin** [comment]
yes, let's postpone this for a test with the real projects.
