### ISSUE TITLE
temporary free input: add / edit collected material

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#1945]
### recording 13.11
- [x] creating new collected materials of all types with temporary free input switched on should work
- [x] renaming collected materials with temporary free input switched on should work, too
- [ ] test adding a new collected material in lots (without temporary free input override, just to see if it still works)

**Comment by luizaogs** [comment]
I am not sure if this matters or if it is related, but I just realized that whenever I create a new bulk cm the selection box for the material shows up as red in the cm layout. Clicking outside of it does not change anything, nor does leaving the cm layout and coming back to it.

<img width="1027" alt="Screenshot 2022-12-26 at 10 05 28 AM" src="https://user-images.githubusercontent.com/67970402/209552204-a6f2bfa6-b88d-4517-9d26-0cdf07e5c3ea.png">

**Comment by luizaogs** [comment]
Hm. We can still add cm in lots? I thought not (because of #1505) and at any rate if we still can I can't figure out how to do it. Help.

**Comment by urapadmin** [comment]
no, you are correct, the add collected material button in the lots tab is gone for good.

**Comment by luizaogs** [comment]
Ok, so I close this.
