### ISSUE TITLE
temporary free input override: edit/add pedestrian surveys and features

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#1946]
- features and p.surveys have a hidden locus that is usually generated using the generation function idgen_copy_domain. ONLY in this case the renaming of such a unit is possible with the temporary free input override on. If the generation function of the hidden locus is not idgen_copy_domain, you should get an error when you try to rename the feature unit / pedestrian survey unit.

- if in the case above idgen_copy_domain is being used, the hidden locus should get properly renamed together with the unit

**Comment by urapadmin** [comment]
### recording 13.11
- note that identification methods that use "idgen_partial_input" as generation function are not working, yet.
- creating a new feature/survey unit with temporary free input should work
- renaming an existing feature/survey unit should work
- creating a new feature from within a survey unit (or a legacy unit) should work
- the hidden locus should get properly named / renamed together with the unit if idgen_copy_domain is being used for the identification method that creates the hidden locus (remember: that's a separate config key in the identification configuration)

**Comment by luizaogs** [comment]
How do I check the name of the hidden locus again?

**Comment by urapadmin** [comment]
if you are in test mode you should have a big orange button in the layout header of survey and feature units: "show hidden locus",

**Comment by luizaogs** [comment]
Ah I was testing as admin. I’ll look at test mode tomorrow.

**Comment by luizaogs** [comment]
Yes, this is fine.
