### ISSUE TITLE
termporary free input override: add / edit excavation / legacy unit

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#1947]
### recording 13.11
- [x] excavation units using idgen_input as generation function (or any other) can be added and changed
- [x] legacy units (feature recording) using idgen_input as generation function (or any other) can be added and changed

**Comment by luizaogs** [comment]
I've tested this with the default generation function in PVD for excavation and legacy units, which I believe is idgen_input based on the function's description in FM. 

BUT I don't really know how to change this and so can't test it for any other generation function. @lbestock help?

**Comment by luizaogs** [comment]
Oh nevermind, I figured out how to change this. But what would be other generation methods that might be used here?

**Comment by urapadmin** [comment]
Just to answer the question (I am not really expecting you to know how to configure all this): all generation functions could be used. But idgen_group, e.g. would make some sense. idgen_partial_input would make sense and why not idgen_serial, don't we do that in URAP? We could. You might have found it already, but the wiki has a few things on generation functions (or rather identification methods):
- [https://wiki.arch-kiosk.brown.edu/urapdev/doku.php?id=manuals:developer_manual:common_identification_methods&s[]=idgen&s[]=serial](https://wiki.arch-kiosk.brown.edu/urapdev/doku.php?id=manuals:developer_manual:common_identification_methods&s[]=idgen&s[]=serial)
- [https://wiki.arch-kiosk.brown.edu/urapdev/doku.php?id=manuals:developer_manual:context_identification_-_generation_functions&s[]=idgen&s[]=serial](https://wiki.arch-kiosk.brown.edu/urapdev/doku.php?id=manuals:developer_manual:context_identification_-_generation_functions&s[]=idgen&s[]=serial)

**Comment by luizaogs** [comment]
Right, but do you want them all tested? I figured out how to change them in configuration but adding a new one to identification methods still seems a bit difficult after reading the wiki pages :) As far as I can tell PVD doesn't have any of those ready to go for excavation or legacy units.

**Comment by urapadmin** [comment]
No, I think I don't want to prolong this already too extensive renaming project. Let's give the whole thing a test in the real projects after we have tested the basics in PVD.

So I close this.
