### ISSUE TITLE
a typo for Christmas

### ISSUE THREAD

**Issue by luizaogs** [arch-kiosk/arch-kiosk-office#1948]
A present from me to you. A fun typo ticket. I know, your favorite kind.

You want "intuitive" in this message that pops up when I'm using temporary free input to create a new context:

<img width="750" alt="Screenshot 2022-12-26 at 9 51 49 AM" src="https://user-images.githubusercontent.com/67970402/209551219-bf1f9028-0c85-4e36-b2dd-dbcdaf3a7d94.png">

yours truly, 
the typo Santa Claus (more like Krampus, I guess)

**Comment by urapadmin** [comment]
who is Krampus? Our Knecht Ruprecht?

**Comment by urapadmin** [comment]
The problem with my Christmas typo is that I can't find this message anywhere. In fact it rather looks like a message from the first attempt on free input that I dropped. But I can see that this is the right database version from the logo. 
I tried a full text search and nothing came up (does not mean all that much in FileMaker). I am flabbergasted.
How do you create this? Is this in loci or in collected material? What identification method / generation function are you using?

**Comment by luizaogs** [comment]
I meant that I was Krampus 👹

I’ll look at this again and see if I can reproduce it.

**Comment by luizaogs** [comment]
Ah found it, and you did not because I did not explain it properly. This is the help text (so what appears if I click on the little i icon) next to the empty text box for domain when creating a new context with free input enabled.

So if you just go to the help module of configuration and help_free_input_domain_part you will find it.

(I have "temporary free input with serial number" configured for identification_method_free_input_locus)

**Comment by urapadmin** [comment]
ah. that explains it, indeed.
We don't have a Krampus (we Middle and North Germans). Only Bavaria and Austria have Krampus. Wrong Germany.
We have a guy called Knecht Ruprecht. He serves the same purpose, though. He carries a birch rod to land on children's hind ends if they forgot their prayers.

**Comment by luizaogs** [comment]
Ah. My Brown German classes only taught me about the wonders of Krampus.

**Comment by urapadmin** [comment]
Because they confuse Bavarians and Austrians with Germans. Weißwurst and the Octoberfest - that's us. 🍺 🎠 🎡 :no-wurst-emoji

**Comment by urapadmin** [comment]
### recording 13.12
- I patched this.
