### ISSUE TITLE
previously selected bulk cm material seems to remain in menu when creating a subsequent bulk cm

### ISSUE THREAD

**Issue by luizaogs** [arch-kiosk/arch-kiosk-office#1949]
13.11, PVD

I'm testing using temporary free input to create cm of different types. I'm currently testing bulk, and I created one successfully for animal bone. When I went back to the cm layout and clicked on bulk again to create another cm I got the following screen, which you can see already has the "will be 'B' in number" (which is the code for animal bone in PVD) mentioned below the material for PVD# selection box even though I have not clicked on any material for this new cm: 

<img width="1025" alt="Screenshot 2022-12-26 at 10 03 24 AM" src="https://user-images.githubusercontent.com/67970402/209551997-95d250f7-a99b-475b-8b40-9740ad734728.png">

**Comment by luizaogs** [comment]
I am not sure if this matters or if it is related, but I just realized that whenever I create a new bulk cm the selection box for the material shows up as red in the cm layout. Clicking outside of it does not change anything, nor does leaving the cm layout and coming back to it.

<img width="1027" alt="Screenshot 2022-12-26 at 10 05 28 AM" src="https://user-images.githubusercontent.com/67970402/209552291-48de7413-3ce6-43ec-b203-de19a3cbf0e0.png">

**Comment by urapadmin** [comment]
those are two different things: 
- (for the user's manual): in temporary free input mode the material selection can be changed no matter what (often that is not the case, due to the config keys visibility/lock_material_for_cm_types and visibility/allow_change_material_type (obsolete), see also #1562). To indicate that something is behaving differently because of the activated free input mode it is red.
- the other one is a bug.

**Comment by urapadmin** [comment]
### recording 13.12

> 13.11, PVD
> 
> I'm testing using temporary free input to create cm of different types. I'm currently testing bulk, and I created one successfully for animal bone. When I went back to the cm layout and clicked on bulk again to create another cm I got the following screen, which you can see already has the "will be 'B' in number" (which is the code for animal bone in PVD) mentioned below the material for PVD# selection box even though I have not clicked on any material for this new cm:
> 
> <img alt="Screenshot 2022-12-26 at 10 03 24 AM" width="1025" src="https://user-images.githubusercontent.com/67970402/209551997-95d250f7-a99b-475b-8b40-9740ad734728.png">

- this should not happen anymore
