### ISSUE TITLE
back button in survey cm not working properly

### ISSUE THREAD

**Issue by luizaogs** [arch-kiosk/arch-kiosk-office#1950]
13.11

After creating a new small find cm in survey unit 02 in PVD I clicked on the back button, expecting that it would take me back to the cm menu where I can create new ones. Instead, the back button took me back to the dayplan and narratives screen, but I had not been there before creating the cm.

**Comment by luizaogs** [comment]
This does not seem to happen after creating a new sample.

**Comment by urapadmin** [comment]
### recording 14
- should be fixed
