### ISSUE TITLE
temporary free input: add/edit su ceramic fragment

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#1952]
### recording 13.12
This is using idgen_partial_input, which consists of a fixed prefix (the domain) and a manually entered local id.
- [x] So in temporary free input it must be possible to input the domain part (which is otherwise not editable) and the local id when creating a new fragment. 
- [x] When creating a new fragment with temporary free input the domain part should have the prefix as a default
- [x] when editing a fragment with temporary free input the domain part should reflect the actual domain part (which can be different from the fixed prefix due to using temporary free input before)

**Comment by luizaogs** [comment]
It looks like in PVD su ceramic fragments use idgen_serial? I don't see idgen_partial_input anywhere.

**Comment by urapadmin** [comment]
true. I have added a new identification method using idgen_partial_input and applied it to su ceramics. 
It creates identifiers like SU-{locus id}-{manual input}.

**Comment by luizaogs** [comment]
I believe this is all fine.

**Comment by urapadmin** [comment]
### recording 14
I only reopen this because pasu-test is rolled out now and I'd like to have a test in the real project.

**Comment by lbestock** [comment]
On it. As I haven't been following all these exciting developments it might take me a bit to get into this, but I'm preparing pasu-test now. Without the company of any of the useless house felines.

**Comment by lbestock** [comment]
By and large this seems to be working well, but one thing happened that I wasn't expecting.
I cannot make a new fragment with a number that violates the numbering function, which was neither here nor there in terms of my expectation. I attempted to create a fragment SU22-D244-cat, and was rejected. Fine.

But what happened when I went to change an existing fragment to that surprised me. There I get an error message:

![image](https://user-images.githubusercontent.com/49291909/210153399-3f295573-e111-4fde-93c5-820c5807cd73.png)

...but when I click "oha" it erases the identifier of the record totally rather than just rejecting my new impossible identifier.
![image](https://user-images.githubusercontent.com/49291909/210153373-233fab83-0b3c-40ed-91ad-f943dd502358.png)

**Comment by lbestock** [comment]
(Nice icon, very appreciated. As was that you scared up both actual cats, who now nap here.)

**Comment by lbestock** [comment]
Whoa weirdo. That was PASU on my mac. I am now trying this in PVD on my iPad and something super weird just happened.
New CM ceramics. New SU ceramics processing page, blank. I created a new sherd as expected. Then I switched on temporary free input. Then I changed my "1" to "2":
![image](https://user-images.githubusercontent.com/49291909/210153645-a27f2beb-2ca3-4501-ad76-feedca4abfab.png)

But it misunderstood me and somehow remembered the last freely input identifier I had made, which was in a different place entirely and for a CM. It told me that it deviated from the auto identifier:

![image](https://user-images.githubusercontent.com/49291909/210153684-947afcd0-aa1b-4d58-858a-85607d222922.png)

I told it fine, use mine, and it applied this weirdness. 
![image](https://user-images.githubusercontent.com/49291909/210153700-ace40426-ad6a-4e51-b677-66b1ef9a27ee.png)

A) It certainly should not have misunderstood the identifier I gave it, which was just changing a 1 to a 2. And B) should it have been willing to apply this particular identifier at all? I will now test PVD on the Mac to see if the same thing happened that just happened on my iPad.

**Comment by lbestock** [comment]
It's totally an iPad thing - exact same steps on the Mac changed me from 1 to 2 as expected.

**Comment by urapadmin** [comment]
> By and large this seems to be working well, but one thing happened that I wasn't expecting. I am testing this on my Mac. I cannot make a new fragment with a number that violates the numbering function, which was neither here nor there in terms of my expectation. I attempted to create a fragment SU22-D244-cat, and was rejected. Fine.
> 
> But what happened when I went to change an existing fragment to that surprised me. There I get an error message:
> 
> ![image](https://user-images.githubusercontent.com/49291909/210153399-3f295573-e111-4fde-93c5-820c5807cd73.png)
> 
> ...but when I click "oha" it erases the identifier of the record totally rather than just rejecting my new impossible identifier. ![image](https://user-images.githubusercontent.com/49291909/210153373-233fab83-0b3c-40ed-91ad-f943dd502358.png)

### recording 14.0.1
- this happens only when you edit an existing fragment and thereby violate the formatting function. Now your wrong identifier should get rejected and nothing should happen.

**Comment by urapadmin** [comment]
> It's totally an iPad thing - exact same steps on the Mac changed me from 1 to 2 as expected.

### recording 14.0.1
I don't think this had anything to do with ipad vs. Mac. Instead it depended on the exact steps you took before changing the fragment. Addinga collected material or so would have set a default that would have been still active when changing or adding the fragment. 
- However, you should not be able to reproduce this anywhere

**Comment by luizaogs** [comment]
> ### recording 14.0.1
> * this happens only when you edit an existing fragment and thereby violate the formatting function. Now your wrong identifier should get rejected and nothing should happen.

Yup.

**Comment by luizaogs** [comment]
> ### recording 14.0.1
> I don't think this had anything to do with ipad vs. Mac. Instead it depended on the exact steps you took before changing the fragment. Addinga collected material or so would have set a default that would have been still active when changing or adding the fragment.
> 
> * However, you should not be able to reproduce this anywhere

I can't, so I think this is fine.
