### ISSUE TITLE
get rid of barcode creator entirely

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#1953]
### recording 13.12
After #1707 I have now thrown out the code. 
Please check that creating qr codes is not in any way damaged now.
Note that the config key "general/qr_code_rendering" is now deprecated. It should be set to nothing for the time being (I will mark it obsolete and move it for Version 14).

**Comment by luizaogs** [comment]
I'm on my Mac and was planning to still check this on my iPad but I already found a problem: it doesn't seem to matter where I am rendering the qr code, they all come out with CA as the identifier.

**Comment by urapadmin** [comment]
oh, yes, that was still due to #37

**Comment by urapadmin** [comment]
### recording 13.13 (ui, don't touch any image containers)
- qr codes should work again.
- qr_code_rendering config key now obsolete and under "deprecated" (and patched)

**Comment by luizaogs** [comment]
Looks fine on both Mac and iPad.
