### ISSUE TITLE
identifier lists with nonexistent "locus numbers" preselected 

### ISSUE THREAD

**Issue by luizaogs** [arch-kiosk/arch-kiosk-office#1954]
v14 in both PVD and USTP-test
Mac

When entering the identifier lists layout the dropdown is filled with "locus numbers" (before I click on anything at all): 

<img width="1025" alt="Screenshot 2022-12-31 at 6 50 40 PM" src="https://user-images.githubusercontent.com/67970402/210156342-6a09fe68-4497-4b47-9566-9c33192dc894.png">

However, "locus numbers" is not actually an option in the dropdown when I go into it (both PVD and USTP test are using "context numbers" instead): 

<img width="1025" alt="Screenshot 2022-12-31 at 6 50 48 PM" src="https://user-images.githubusercontent.com/67970402/210156358-bb95031f-fe6e-47d0-8e32-52b1a55c3d38.png">

If I select one of the actual options from the list and come back into identifier lists "locus numbers" is no longer preselected.

**Comment by urapadmin** [comment]
### recording 14.0.1
