### ISSUE TITLE
ceramics module gone in ustp?

### ISSUE THREAD

**Issue by luizaogs** [arch-kiosk/arch-kiosk-office#1955]
I was going to try to test #1952 in 14.0.1 but it seems like the ceramics module in USTP test is ... gone? Or maybe I have gone insane.

**Comment by urapadmin** [comment]
Happy New Year, Luiza!As for the sanity: There has never been a ceramics module in USTP. That would be PASU. On 1. Jan 2023, at 08:42, luizaogs ***@***.***> wrote:﻿
I was going to try to test #1952 in 14.0.1 but it seems like the ceramics module in USTP test is ... gone? Or maybe I have gone insane.

**Comment by luizaogs** [comment]
Awkward. Happy New Year :)
