### ISSUE TITLE
finish checking URAP test data before updating

### ISSUE THREAD

**Issue by lbestock** [arch-kiosk/arch-kiosk-office#1957]
The database currently on URAP test will be moved to URAP, so it's not just configuration but the old data themselves that need to be examined to make sure nothing has gotten screwed up with all the major changes. @lbestock this one is for you. Locus details as expected? Locus relations? Collected material and small finds all as expected? Ceramic processing?

**Comment by urapadmin** [comment]
there's also #1835

**Comment by lbestock** [comment]
Samples are present as bulk CM with material sample. That could get confusing in the future if looking for all samples. @urapadmin, is it possible to do something about that?

**Comment by lbestock** [comment]
All records I have checked (by directly comparing a download from test and URAP itself) including ceramics and locus details seem to be present in the right places. So I have uploaded and synchronized URAP test, in which I made some but not all configuration changes that we will want for next season.

URAP can be updated.

**Comment by urapadmin** [comment]
I will ...
