### ISSUE TITLE
Data Query / Analysis module in Kiosk

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#1958]
I do think we won't be able to avoid at least a basic module for querying and displaying recording data in Kiosk proper. 
- make a concept
- design a module
- implement

### prerequisistes
- [ ]

**Comment by urapadmin** [comment]
in fact this is rather a project than a single ticket.

**Comment by luizaogs** [comment]
Can be closed??

**Comment by urapadmin** [comment]
ja, I guess so :o) It is a project indeed.
