### ISSUE TITLE
bump up to latest Flask 2.3 (when it is out) and latest Werkzeug

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#1961]
Might get rough...

**Comment by urapadmin** [comment]
will get rough: We are now up to 2.3.3 and I see quite some deprecated stuff. But my current hassle with JSON  and Flask suggests doing this now and then at least have cutting-edge hassle.

**Comment by urapadmin** [comment]
### Kiosk 1.5.9
- there is nothing new about this Kiosk version except that it runs on Flask 2.3.3 and Werkzeug 2.2.0, the main frameworks we use. Since they are the basis of everything, bugs can occur everywhere. So everything in Kiosk must be touched and tried. Backup, file repository, housekeeping, director's view, file picking, you name it
- I cannot install this on Beset without installing it for every project at once. So the local server is our only test platform for this

**Comment by lbestock** [comment]
Query and View is not behaving as I expect it to following this update. Testing on the local demo server.
Querying for materials in loci tagged "Bob" returns nothing. Looking in FM in tag analysis gives me three things that should show up as CM from loci tagged Bob.

**Comment by lbestock** [comment]
File imports seem to be working - I've done sequence, photoboard, and candids without context all as "ton". Do you need me to try all the types of file import? (As in, file name and folder, bunch rather than just ton...)?

**Comment by lbestock** [comment]
File picking still works.

**Comment by lbestock** [comment]
So far I am really not encountering any roughness, and I'm not sure what else to do to test this.
Backup works.
Restore works.
Housekeeping after backing up and restore - I don't know how to tell if that works but it didn't do anything I didn't expect and everything looks really good to me (except the weather).

**Comment by lbestock** [comment]
Ah, a restore issue has arisen.

**Comment by lbestock** [comment]
Quality control survives the update (at least, removing rules and flags works; I cannot write rules myself and did not try).

**Comment by lbestock** [comment]
I can make users who have the right privileges, and I can delete them.

**Comment by urapadmin** [comment]
okay, this looks good then for now. We let it loose on arch1900 before we update Beset.

**Comment by urapadmin** [comment]
### Kiosk 1.5.10.2
- This is the official rollout of the new Flask 2.2.3 based Kiosk.

**Comment by luizaogs** [comment]
I can do this on Beset. Soonish.

**Comment by urapadmin** [comment]
> I can do this on Beset. Soonish.

💊 you have to be well, though! 💊

**Comment by luizaogs** [comment]
What, you can hear me coughing all the way from over there? :) (not completely unbelievable, with this cough)

**Comment by luizaogs** [comment]
Back up: seems to have worked just fine.

**Comment by luizaogs** [comment]
I mentioned what I tested in the file repository above -- let me know if you need me to test anything else there specifically.

**Comment by urapadmin** [comment]
Forget about the things Laurel tested, as she tested on a local machine. The Beset test needs to go through everything again. And Everything is everything that is immediately Kiosk related, that is to say everything that you can trigger in Kiosk. Or are used to trigger (and now it might be gone).

**Comment by urapadmin** [comment]
new version coming up, so please wait for 1.5.10.3

**Comment by luizaogs** [comment]
Ok well, I can't test ton regardless :) I'm testing everything again, don't worry.

**Comment by luizaogs** [comment]
I'll wait to test the rest once the new version is out, then.

**Comment by urapadmin** [comment]
meanwhile: 💊 🍨 💊

**Comment by urapadmin** [comment]
and no, ton and the file sequence import are not available on Beset. We care for that test over here.

BTW: Are you going out with MKAP? I am a bit puzzled.

**Comment by luizaogs** [comment]
Yeah, for half of the season.

**Comment by urapadmin** [comment]
first half or second half?

**Comment by luizaogs** [comment]
Uhh, middle-ish. But she asked me to do a tutorial ... so I'm doing that tomorrow. They'll be fine without me.

**Comment by urapadmin** [comment]
I might not be :o)

**Comment by luizaogs** [comment]
Ha well. I'll do my best to anticipate problems.

**Comment by luizaogs** [comment]
Tests after 1.5.10.3.

Creating and editing users: works
Log viewer: works
Privileges: I can change them
Export: works
Edit dock: works
Disable/enable dock: works
Point repository looks the same

Am waiting to test file picking once MCP is back up (will test it by checking #2288 ), also whether quality control rules are working, download/upload/synch process, create new dock and then delete it, prepare docks, query and view (it currently tells me that the server is down)

**Comment by luizaogs** [comment]
Lutz, I've run all of the tests mentioned above and can't really think of anything else to test. Issues have tickets. Let me know if you need me to look at anything else.

**Comment by urapadmin** [comment]
thank you. I think it should really do but the coughy people get the right to close the ticket 🍨

**Comment by luizaogs** [comment]
The coughy people love to close tickets :)
