### ISSUE TITLE
URAP FM: missing unit icon

### ISSUE THREAD

**Issue by lbestock** [arch-kiosk/arch-kiosk-office#1964]
Unit FE in URAP is not accessible in Filemaker. It is a surface collection/locus recording unit (one can see it in the gear) and it had data attached to it (File Repository has images for it) so once upon a time it must have been accessible. But lacking an icon, one cannot get into it currently.

**Comment by lbestock** [comment]
Hm this is a unit type that is no longer available to create, which might be related?

**Comment by urapadmin** [comment]
### recording 14.0.3
- surface collection units should be accessible but you should not be able to create new ones
