### ISSUE TITLE
PVD server not working?

### ISSUE THREAD

**Issue by luizaogs** [arch-kiosk/arch-kiosk-office#1983]
I have a meeting with Katie Kearns on Tuesday morning to show her Kiosk and I think it might be good to show the whole upload and download process but the PVD server doesn't seem to be working. I could fudge it with Didi, but for this one it might be good to go through the entire process. 

Do you think you can get it back up by then?

**Comment by urapadmin** [comment]
Just the usual. Brown had restarted their servers. It is back.
.
A pity that you don't have KioskBridge.
