### ISSUE TITLE
hub: hard reset for a filemaker recording dock

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#1984]
something that would make my life much easier: "hard" resetting a workstation. While the normal reset only sets the workstation back into the idle mode, the hard reset drops all workstation resources and creates them afresh. So the workstation's table structures would be destroyed and remade. Sometimes that is necessary after a breaking change in an update. I would just keep the dock data in the workstation table.

**Comment by urapadmin** [comment]
### Kiosk 1.4.7.0
- there is a new "renew workstation" option that resets the whole database structure of a workstation. 
- the result from the point of a user is the same as "reset workstation": The workstation is reset to "needs preparation" but the subsequent fork can take a bit longer than with a normal reset.

**Comment by luizaogs** [comment]
Oh oops, should I not have tried this yet in 1.4.6? I just realized it says 1.4.7 in your comment and my workstation is currently pending forever, it seems.

**Comment by luizaogs** [comment]
Oh wait, I was trying to prepare another workstation to test something else, so the pending forever issue does not seem to necessarily be related to this?

**Comment by urapadmin** [comment]
no, looks like Master Control is down. Presumably Brown restarted our server. I'll look into it tomorrow. 💤

**Comment by luizaogs** [comment]
Works.
