### ISSUE TITLE
KHPP update testing

### ISSUE THREAD

**Issue by lbestock** [arch-kiosk/arch-kiosk-office#1989]
Testing KHPP. This is a ticket to record all the things I notice that are not right while I'm going through, not all of which will necessarily result in tickets. Some might be configuration. 

- [x] #1992
- [x] #1993
- [x] #1994 
- [x] #1995 
- [x] #1996
- [x] #2000

**Comment by lbestock** [comment]
Locus view, visible red box with a number up in the banner between unit and locus that should not be there.
![image](https://user-images.githubusercontent.com/49291909/220995047-4265fcc6-454b-4fc3-9cc0-7fe58ae152c1.png)

**Comment by lbestock** [comment]
Whoops: I can't enter any CM. I don't even have a plus button.

**Comment by lbestock** [comment]
Locus relations needs an "equivalent to" added.

**Comment by lbestock** [comment]
(Bigger than KHPP presumably): when I go to make a new feature from within a survey unit it asks me to give an identifier but calls it for survey, not for feature.

**Comment by lbestock** [comment]
There is a "bulk details" tab for a (pre-existing, since I can't make one yet) animal bone bulk CM. Why? I didn't expect it and am puzzled by it.

**Comment by lbestock** [comment]
Set the category one and category two labels in preprocessing configuration before showing that feature to KHPP.

**Comment by urapadmin** [comment]
> There is a "bulk details" tab for a (pre-existing, since I can't make one yet) animal bone bulk CM. Why? I didn't expect it and am puzzled by it.

"There" is where?

**Comment by lbestock** [comment]
You know, "there" :).
![image](https://user-images.githubusercontent.com/49291909/221209032-7776e6a6-1257-40e2-a6cd-e2b298c2a915.png)

**Comment by urapadmin** [comment]
erm, should I have told you that this is the khpp master database? Please don't create test records except in the playground.

**Comment by urapadmin** [comment]
> Locus view, visible red box with a number up in the banner between unit and locus that should not be there. ![image](https://user-images.githubusercontent.com/49291909/220995047-4265fcc6-454b-4fc3-9cc0-7fe58ae152c1.png)

now in #1992

**Comment by urapadmin** [comment]
> Whoops: I can't enter any CM. I don't have a plus button. And going into admin and CM configuration and setting ID methods (using those that had already been configured for CM) didn't do it, so @urapadmin will take a look at it.
That one was due to missing collected material type configuration

> 
> VERY strange. I went back into a different site and then back into Playground and now there are the buttons as there should be and I can use them properly. If I hadn't shown Lutz that it hadn't worked I would simply think I was crazy.
That one I don't understand at all and can't believe (as collected material types are not related to sites). 
It might also not matter anymore.
 
> Can amalgamate CM comments: there is one below about a bulk: animal bone CM record having a tab for "bulk details". And I don't remember there even being bulk details so I am not sure where that comes from - it looks like small finds details. Bulk carbon doesn't have it.
That is a real issue and will be tackled in #1993

**Comment by urapadmin** [comment]
> Locus relations needs an "equivalent to" added.

I have added it.

**Comment by lbestock** [comment]
Rusty getting back to this.
Configuration of ID methods for coordinates and SU ceramics is gibberish. The latter presumably doesn't matter. Does the former?

**Comment by lbestock** [comment]
These are notes for @lbestock while she is doing initial KHPP testing! So as not to lose anything. Then we will go through and decide which need to be tickets.

Testing on an iPad now.
Unit narratives behave strangely (but it's a familiar strangeness): they are sometimes just grey, no ability to see the narrative box. One can still click in it and make it appear. Sometimes it is all of them, sometimes just one. It is disconcerting and not ideal but it also doesn't affect functionalitiy. It stays like this even if one leaves the tab and comes back.
![image](https://user-images.githubusercontent.com/49291909/232793445-a5ba8024-adf3-44f8-8e23-29d65ecde98e.png)

**Comment by lbestock** [comment]
Oh god, what were the tickets from CA years ago with the imagery weirdness? Because I just made an image, it was blank. I made another, and it was also blank, and then I went to a different tab and back into my photos tab and they still weren't there. I have to exit the locus and then go back in to see them. Continues to happen if I add another image.

**Comment by lbestock** [comment]
Ah an actual bug so will make a ticket pronto: creating a lot creates instead a locus.

**Comment by lbestock** [comment]
They had burials last time, which in the old data are now locus type "other" specific type "burial". But in the current setup there is a locus type burial (which is really what it should be going forward, this "specific type" subdivision of locus type is crap). Not a problem for viewing the old data or anything, but I do wonder about queries in the future and burials of different seasons being called different types of loci and if we want to do anything about that.

**Comment by lbestock** [comment]
Did we ever go through the bug reports from KHPP? Turns out they used them rather extensively.

**Comment by lbestock** [comment]
> > Locus relations needs an "equivalent to" added.
> 
> I have added it.

But it isn't there, which makes me nervous since you said you added it.

**Comment by urapadmin** [comment]
is this done? then please close.

**Comment by urapadmin** [comment]
btw: Yes, I did go through their bug report back in the days 2018
