### ISSUE TITLE
khpp: set category one and category two labels in preprocessing configuration before showing that feature to KHPP.

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#1994]
Set the category one and category two labels in preprocessing configuration before showing that feature to KHPP.

_Originally posted by @lbestock in https://github.com/arch-kiosk/arch-kiosk-office/issues/1989#issuecomment-1442635530_

**Comment by lbestock** [comment]
I don't actually see how. I thought I could do that in configuration. But while there are valuelists for the values for these things, neither in valuelists nor in labels in configuration do I find a way to change those "category 1, category 2". They must be there - we can't have called them that for USTP.

**Comment by lbestock** [comment]
Huh, no, it is the same in USTP on the test server at least. It shouldn't be. In both it looks like this (also this is in the playground on KHPP, not to worry):
![image](https://user-images.githubusercontent.com/49291909/221371340-6b852721-3196-4077-95ac-a253fcfdb31d.png)
Those should read rather "type" and "component part" and I don't know how to make them do so, so back over to you @urapadmin.

**Comment by urapadmin** [comment]
Currently those headings are not configurable. I'll attend to it.
But you should be able to configure the actual value lists, right?

**Comment by lbestock** [comment]
Yup, those I can configure.On Feb 25, 2023, at 8:03 PM, kioskadmin ***@***.***> wrote:﻿
Currently those headings are not configurable. I'll attend to it.
But you should be able to configure the actual value lists, right?

**Comment by urapadmin** [comment]
ja. It was already configurable. But extra special: This is part of the first internationalization attempts and hence you'll find it under i18n (cool kid's term for internationalization because there are 18 letters between i and n). 
Even I had forgotten that I extended the i18n attempt beyond the special ceramics module. So I have added the search idea here: #2002

**Comment by urapadmin** [comment]
this does not need a new version. You can configure and close this.

**Comment by urapadmin** [comment]
@lbestock: have you done this and we can close this?

**Comment by lbestock** [comment]
Yup.
