### ISSUE TITLE
Creating a new feature from within a survey wants to create a new survey unit

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#1995]
>(Bigger than KHPP presumably): when I go to make a new feature from within a survey unit it asks me to give an identifier but calls it for survey, not for feature.

And then indeed it shows up in the banner as a survey unit, though it has the proper feature icon, and it shows up in the navigation history as survey, not feature.

![image](https://user-images.githubusercontent.com/49291909/221064077-9fd151bc-ada8-4922-bf34-f489aaa6a905.png)

_Originally posted by @lbestock in https://github.com/arch-kiosk/arch-kiosk-office/issues/1989#issuecomment-1442627254_

**Comment by urapadmin** [comment]
I checked it: identifications methods look okay. Simply free_input. So this seems a late side effect of the temporary free input extension.

**Comment by urapadmin** [comment]
definitely a problem of the free input method. Happens in all projects.

**Comment by urapadmin** [comment]
### recording 14.0.5
- when using free input it should have the correct title and not jump anywhere. Instead a new feature unit should be added to the list within the survey unit.
- sort of the same bug was in the unit creation on the start page: when using free input the "+" button would always show some random title for the type of unit (in fact it was related to whatever kind of unit had been created or visited last). Now it should show what is in "term for unit" in the New unit dialog.

**Comment by luizaogs** [comment]
Both are working.
