### ISSUE TITLE
export to filemaker: change from dummy to image and modified/modified_by

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#2001]
This is out of #1996. While the latter is solved now, I kept wondering:

What about a legal change from an image to dummy that happens without any change to any image record happening? 

I must test this:
- before fork after an import and sync that did not change any image records change the file picking rules so that a single image or a group of images must turn to dummies. 
- prepare for field -> do you get the warning (Kiosk 1.4.1b needed)?

_Originally posted by @urapadmin in https://github.com/arch-kiosk/arch-kiosk-office/issues/1996#issuecomment-1445531976_

**Comment by urapadmin** [comment]
yup. That's causing the exact same issue. So as a remedy that just steamrolls this issue I should just ALWAYS export the repl-data for the image table. But that will slow down import_files AND some other things. So perhaps I can find a more intelligent solution?

**Comment by urapadmin** [comment]
much harder to test than thought. The problem only occurs when switching images from dummy to a real file.

**Comment by urapadmin** [comment]
### kiosk 1.4.1c
- I have tested this locally in the development environment
- whoever wants to test it again: Go for it, it is a nightmare:
  1. tag a file that is bound to a context in the file repository with "test"
  2. create a workstation in the port (recording group) "development" or whatever
  3. make sure that that port has NO file picking rules
  4. prepare, download, import and synchronize so that synchronization has nothing to do (look at the details!)
  5. create a file picking rule for that port development that sets files that match a tag "test" to low.
  6. prepare the workstation again. It should run without any issues or warnings
  7. download the filemaker file and make sure that the file is the only file that is actually there. All others must be dummies. Don't change any data in the filemaker file, we don't want anything to synchronize.
  8. upload, import, snychronize: The synchronization log should show nothing again.

**Comment by luizaogs** [comment]
Works.
