### ISSUE TITLE
recording: search for term / key in configuration

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#2002]
since now we even have i18n it gets really difficult to know where which setting is hidden in the config. 
A search method seems indeed the best way of navigating this: One sees something on the ui that is the wrong term and finds the pertinent config key by searching for that value.

**Comment by urapadmin** [comment]
### recording 14.2
- there is a new search button next to the category selector
- the search button opens a new window where you can add a text that is being used to search ALL config keys
- in reduced config mode (see #1564) ALL means only the keys that are included in reduced config
- the search term is compared to the id, the category, the info text and the value of a key. That means typing in "yup" will bring up a lot of keys. I am not sure if including the info text was a good idea. 
- click on the green check mark or the key's id and the thing gets selected in the main configuration layout

**Comment by luizaogs** [comment]
Am I blind? 

![2632B023-EB9E-4049-9FC5-08D2EAC02036](https://user-images.githubusercontent.com/67970402/231630488-5aa865a9-d3b4-4cb9-a80d-330dd4984dcc.png)

**Comment by urapadmin** [comment]
where's the search button?

**Comment by urapadmin** [comment]
ja, copy & paste: The button is only visible if you are a developer (to continue you can simply set the developer_mode in the admin category to "true" [yes, this is the one exception from the "yup"s]).

**Comment by luizaogs** [comment]
When I click on the search button there is already something in the filter by search box: "template". Should that be the case?

**Comment by luizaogs** [comment]
The rest is working, so if the above is ok this can be closed.

**Comment by urapadmin** [comment]
### recording 14.3
- you should see the button now as normal admin
- as normal admin (and test mode off) you should also have access to the meta settings. They are green in this case and only reveal the benign options I would allow normal field admins to access. It also makes it easier for others but me to decide on the set of reduced config keys.

**Comment by luizaogs** [comment]
Looks good now.
