### ISSUE TITLE
Kiosk Point Repository: minor UI rearrangement

### ISSUE THREAD

**Issue by lbestock** [arch-kiosk/arch-kiosk-office#2007]
Not quite a bug, just a thing to change.
Currently in the FM UI for coordinates latitude is before longitude, which is standard.
In the UI in Kiosk point repository the two are reversed, so longitude is before latitude.

They should be swapped in how they appear in Kiosk.

**Comment by urapadmin** [comment]
really? Latitude first is standard. No wonder one gets entirely confused. Why is y first? People with left-right issues are constantly discriminated.

**Comment by lbestock** [comment]
But you did it that way in Filemaker...

**Comment by urapadmin** [comment]
longitude is x. if the equator is the x axis than the longitudes cut that x - axes and so they determine the x values. But then wanting me to have latitude first makes me crazy. I will obey, no matter where I did what until now. At least Latitude also comes before longitude in the csv files we got from Didi. So we should be consistent about that order everywhere. The biggest risk is from my point of view that the pair gets confused in the csv import and that'll be hard to spot at times. Unless whoever does the import has a good feeling for what a possible longitude and latitude is supposed to look like.

**Comment by lbestock** [comment]
I noticed it only because I noticed my values were reversed, which was easy to spot because one was negative.

**Comment by urapadmin** [comment]
> I noticed it only because I noticed my values were reversed, which was easy to spot because one was negative.

well, good you used real coordinates. I was about to laugh about that.

**Comment by urapadmin** [comment]
### addressed in Kiosk 1.4.2.1

**Comment by luizaogs** [comment]
Yup.
