### ISSUE TITLE
coordinate filtering does not drop current point selection

### ISSUE THREAD

**Issue by luizaogs** [arch-kiosk/arch-kiosk-office#2008]
Hm a question also for other places with filters. If I am in a record, and filter for a result that would not include that record, I nonetheless stay in the record. The list on the left reflects the filtering but I'm not kicked out of the one I am in. Is that expected?

_Originally posted by @lbestock in https://github.com/arch-kiosk/arch-kiosk-office/issues/1986#issuecomment-1481943049_

I'm opening a new ticket for this, mentioned by Laurel, because I am trying to test things now and getting lost on what is going on in that massive ticket.

**Comment by urapadmin** [comment]
### 1.4.1
- Coordinate filtering does drop the current selection

**Comment by lbestock** [comment]
It does indeed.
