### ISSUE TITLE
coordinate identifier not searchable in Kiosk file repository

### ISSUE THREAD

**Issue by luizaogs** [arch-kiosk/arch-kiosk-office#2010]
Maybe related to #2009 ? If I type in the point's identifier in the file repository I even get a suggestion of the complete identifier in the search box, but if I click on it I am told that the identifier I typed is unknown. With Huxlebob, for instance: 

<img width="1472" alt="Screenshot 2023-03-24 at 4 14 46 PM" src="https://user-images.githubusercontent.com/67970402/227546945-56456535-cf16-40e9-8f12-85e77287b6ea.png">

<img width="1473" alt="Screenshot 2023-03-24 at 4 15 02 PM" src="https://user-images.githubusercontent.com/67970402/227546987-74538a6e-f2ca-4154-8416-ef74adda1463.png">

**Comment by urapadmin** [comment]
### Kiosk 1.4.2.2
- this had nothing to do with coordinates. Selecting an identifier of whatever sort did not re-fetch the images.

**Comment by lbestock** [comment]
Works.
