### ISSUE TITLE
coordinates not allowed to not have a category

### ISSUE THREAD

**Issue by luizaogs** [arch-kiosk/arch-kiosk-office#2013]
### Kiosk 1.4.2.1
To test at least the first part here you need to allow the recording to have an empty category (see below under recording):
- if a point does not have a category it isn't showing any (was 'None' before)

This can't be tested with the current configuration because the category is taken from the filename (hence you cannot have NO category):
- if a point does not have a category it gets update only by a point in an import file if that one doesn't have a category, either

That's just the standard (and was already okay in the last version, but who knows if I screwed it up now?):
- if a point does have a category it gets updates only by a point in an import file that has the same category and point name

### recording
- if the config key general/coordinate_allow_no_category is yup (default is nope) coordinates can have an empty category. By default we want coordinates to have a category.

_Originally posted by @urapadmin in https://github.com/arch-kiosk/arch-kiosk-office/issues/1986#issuecomment-1482581481_

I get this error currently, if I turn the config key to "yup" and try to leave the page for the coordinate.

<img width="1022" alt="Screenshot 2023-03-26 at 6 02 28 PM" src="https://user-images.githubusercontent.com/67970402/227788461-a55fde8d-770e-47b1-a3c0-886b7dfa5b31.png">

<img width="814" alt="Screenshot 2023-03-26 at 6 04 33 PM" src="https://user-images.githubusercontent.com/67970402/227788538-3520977f-e021-4582-ac8a-b9e4fc63b336.png">

**Comment by urapadmin** [comment]
Slightly different but related issue:
- it does pop up wildly during adding a photo. 
- So when adding a new point I must switch to the first page of the tab control

This whole message is a disaster because FileMaker is a disaster on validation. Used right in the field it should work properly but when clicking around wildly or deleting a category and then clicking on add and such things this can go bonkers. Please report all weird combinations if they occur.

**Comment by urapadmin** [comment]
> ```
>           ### Kiosk 1.4.2.1
> ```
> 
> To test at least the first part here you need to allow the recording to have an empty category (see below under recording):
> 
>     * if a point does not have a category it isn't showing any (was 'None' before)
> 
> 
> This can't be tested with the current configuration because the category is taken from the filename (hence you cannot have NO category):
> 
>     * if a point does not have a category it gets update only by a point in an import file if that one doesn't have a category, either
> 
> 
> That's just the standard (and was already okay in the last version, but who knows if I screwed it up now?):
> 
>     * if a point does have a category it gets updates only by a point in an import file that has the same category and point name
> 
> 
> ### recording
> 
>     * if the config key general/coordinate_allow_no_category is yup (default is nope) coordinates can have an empty category. By default we want coordinates to have a category.
> 
> 
> _Originally posted by @urapadmin in [#1986 (comment)](https://github.com/arch-kiosk/arch-kiosk-office/issues/1986#issuecomment-1482581481)_
> 
> I get this error currently, if I turn the config key to "yup" and try to leave the page for the coordinate.
> 
> <img alt="Screenshot 2023-03-26 at 6 02 28 PM" width="1022" src="https://user-images.githubusercontent.com/67970402/227788461-a55fde8d-770e-47b1-a3c0-886b7dfa5b31.png">
> 
> <img alt="Screenshot 2023-03-26 at 6 04 33 PM" width="814" src="https://user-images.githubusercontent.com/67970402/227788538-3520977f-e021-4582-ac8a-b9e4fc63b336.png">

The issue here is that I typed in "nope" (in quotes) as a default, which is nonsense. It must be just nope. Or rather it has to be just yup instead of "yup". Everything that isn't yup is nope in this case.

**Comment by urapadmin** [comment]
### recording 14.1.2
While the original issue was only a configuration issue, I tackled the rest of the dumb validation:
- you get an error when you try to switch to the photo tab while the category is empty 
- while the photo tab is active: When you select a point that does not have a category the tab must switch back to "description". If you select a point that does have a category the photo tab can stay active,

**Comment by lbestock** [comment]
I get an error requiring me to set a category when I click off the description tab to go anywhere at all, not just to photos. That is expected?

**Comment by lbestock** [comment]
The jumping back to the description tab does work, as does the configuration key to allow me to have a blank category in order to test this. 

I think it's totally fine that if a category is required, you not only can't put a photo you can't leave the record. But since that isn't the precise definition of the behavior the ticket said to expect I will leave this for @urapadmin to check.

**Comment by urapadmin** [comment]
that's intended. Users must not have a chance to save a point without a category.
