### ISSUE TITLE
static header for point repository?

### ISSUE THREAD

**Issue by luizaogs** [arch-kiosk/arch-kiosk-office#2015]
Not a big deal if not or if it's too much work, but if there is a way to make the header in the point repository static that would be good. We now have a bunch of points in PVD and scrolling down means that I forget which is the category and which is the point, as well as which is the latitude and which is the longitude. I imagine that projects using this feature will have a lot of points, too, and so might also run into this problem.

**Comment by urapadmin** [comment]
I can totally do that!

**Comment by urapadmin** [comment]
### kiosk 1.4.6.0
- the header line should not scroll anymore once it has reached the top
