### ISSUE TITLE
Q&V: show archaeological data

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#2019]
This is a big task that needs to split up into several once under development:
Showing archaeological data in Kiosk includes showing single records, lists, image lists etc.

**Comment by luizaogs** [comment]
And this? Though I guess there are things you still need to add to Q&V, but those have their separate tickets.

**Comment by urapadmin** [comment]
ja, this is more or less the same thing. Too broad.
