### ISSUE TITLE
🎥 documentation: Tutorial(s) for 2023 season 🎥 

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#2028]
the tutorial from 2022 is too dated. We need a fresher one for khpp. Perhaps a series of smaller ones.

**Comment by lbestock** [comment]
I would lean towards a series of smaller ones. Easier to keep up to date, amongst other things.

**Comment by urapadmin** [comment]
we have a discussion on that one now: #2081
