### ISSUE TITLE
synchronization failed

### ISSUE THREAD

**Issue by luizaogs** [arch-kiosk/arch-kiosk-office#2031]
Huh. This was a database I had uploaded before the new update and the synchronization failed. Not sure if significant or if just a hiccup … so here’s a ticket.

![F2C0ABBE-CDA8-46E6-862D-FFCBC0890B7B](https://user-images.githubusercontent.com/67970402/231620341-fa0aef20-3aff-4b62-82dc-b0ce2cdb74ab.png)

**Comment by urapadmin** [comment]
that is just due to you testing and me already rolling out new stuff. I introduced a new field and so the latest imports are not compatible anymore. You will lose that test data 😫
