### ISSUE TITLE
Bridge: Error in tellServerDownload-WasSuccessful failed

### ISSUE THREAD

**Issue by luizaogs** [arch-kiosk/arch-kiosk-office#2032]
I got the error below when downloading my own workstation to check whether Didi’s changes had synchronized properly. After clicking on got it I was able to redownload, and that worked. I assume this is a hiccup…

![11DF4D84-0017-464A-87FA-BA9BB090543A](https://user-images.githubusercontent.com/67970402/231630061-27759657-cdf5-4dd9-9f37-1caeb45e56ef.png)

**Comment by urapadmin** [comment]
hm. I am a but reluctant to call that a hiccup. It can be connected to messing with privileges and installing new versions in between but we should have an eye on this. It is really key that we use KioskBridge only from this point on to see if it is really stable enough for the field.

**Comment by luizaogs** [comment]
Ok, I'll let you know if I see it again.

**Comment by urapadmin** [comment]
I close this. We have not seen it again.
