### ISSUE TITLE
"going back to tab admin" message

### ISSUE THREAD

**Issue by luizaogs** [arch-kiosk/arch-kiosk-office#2036]
Don't think this is a big deal because I've never seen it outside of developer mode, but in testing #2002 whenever I leave configuration and go back to the start page I get this message. If I click on ok, it takes me back to the admin tab as it says it will. If I click on cancel, it also takes me there anyway. So just letting you know it appears!

![IMG_0336](https://user-images.githubusercontent.com/67970402/231746598-abe3d3b5-aa45-4248-a6c4-0b2de42918f4.PNG)

**Comment by urapadmin** [comment]
yes, that is a feature for myself and I'll keep it for now.
