### ISSUE TITLE
KHPP: change old data so things with material types that include sample are now CM type sample

### ISSUE THREAD

**Issue by lbestock** [arch-kiosk/arch-kiosk-office#2040]
Samples: they were marked as samples by material in the old way ("archaeobotanic sample", "sample (other)" but with the changes these get labeled as type "bulk" now, not sample. This is an issue with the old data for KHPP and might need some fancy thinking? "Archaeobotanical sample" is still a material type, so it is possible to create new records this way, too. Ideal would be to a) make all the records of those two materials now have type sample, not bulk, and then b) change the configuration of the valuelists so it can't be done again in the future. So, new ticket for a) and add b) to the running list of configuration changes.

_Originally posted by @lbestock in https://github.com/arch-kiosk/arch-kiosk-office/issues/1989#issuecomment-1513860642_

**Comment by urapadmin** [comment]
I did that manually on the khpp server, so no versions involved.
Now you must change the valuelist for material

**Comment by urapadmin** [comment]
I hope this was done?

**Comment by lbestock** [comment]
Wow, I think so but...
