### ISSUE TITLE
KHPP elevations interface: expand text box size.

### ISSUE THREAD

**Issue by lbestock** [arch-kiosk/arch-kiosk-office#2042]
KHPP is using an old school style of elevations and there is no point in changing horses midstream.
But the interface is awkward for how they use it - they use a big text field and record both the elevations and where to find them on a drawn plan.
In the measurements tab for elevations for simple elevations we thought it would make sense to give them a big text field so they can see everything. There are only opening and closing, so those could be side by side instead of stacked and then it would be easy to read everything they have in there. E13.1-001 is a good example of a locus to look at to see if the adjustment indeed does what we want.

**Comment by urapadmin** [comment]
### recording 14.3.1
I have done two things:
- when in "show elevations" is "full" there is an additional info button behind which you find the descriptions. I thought it might be useful for all projects to write something textual about the elevations. Since basically that's what khpp always did, their elevation texts would show when clicking on that button. That would be an alternative to khpp's simple elevations.
- when in "simple" the text boxes are now a bit larger. The additional info button must not show in this mode.

**Comment by lbestock** [comment]
Can you make these side-by-side instead of stacked (I mean, opening elevations on the left, closing elevations on the right, text boxes more like squares than long lines)? Currently they don't display much more than they used to because when they have a lot of stuff in there it is a list:
![image](https://user-images.githubusercontent.com/49291909/233667999-7582012b-0f50-4202-900f-bf41e8b0b108.png)

**Comment by urapadmin** [comment]
have you looked at the new "full" elevations to see if that would be a viable option for khpp to go forward?

**Comment by lbestock** [comment]
It isn't really and this locus is a good illustration why - if you look at the plan that corresponds to these elevations then the first five points would work with "full" but the sixth does not and there is nowhere to record it currently.

**Comment by lbestock** [comment]
An image box in "simple" that is used usually with the signature feature to make just the quickest of sketches to indicate where they are might be of use. That's not a dayplan or locus drawing really, just a quick schematic to show where you are taking your points. In fact it would want one for opening and one for closing. That would solve the recording needs. It doesn't do anything for using elevations as data, but as you note repeatedly there really isn't anything valid that can be done on that front and if there is it's better done in GIS anyway. This would help with KAMBE, too.

**Comment by urapadmin** [comment]
> An image box in "simple" that is used usually with the signature feature to make just the quickest of sketches to indicate where they are might be of use. That's not a dayplan or locus drawing really, just a quick schematic to show where you are taking your points. In fact it would want one for opening and one for closing. That would solve the recording needs. It doesn't do anything for using elevations as data, but as you note repeatedly there really isn't anything valid that can be done on that front and if there is it's better done in GIS anyway. This would help with KAMBE, too.

That's a new request: #2063

**Comment by urapadmin** [comment]
> It isn't really and this locus is a good illustration why - if you look at the plan that corresponds to these elevations then the first five points would work with "full" but the sixth does not and there is nowhere to record it currently.

In the end elevations would have to be a list of whatever elevations somebody takes. The Pacha version was too specific. I have made this a new topic

**Comment by urapadmin** [comment]
- what about datum point elevation? Should that be visible if simple elevations are on?

**Comment by urapadmin** [comment]
### recording 14.3.8
- the text boxes are bigger now.

**Comment by luizaogs** [comment]
The text boxes look good now I think but I don't know the answer to the datum question so I leave this open (it is currently visible in both simple and full).

**Comment by urapadmin** [comment]
the answer was: Leave it there.
