### ISSUE TITLE
FM: "view" action from popup in locus relations photos does not work for old KHPP drawings

### ISSUE THREAD

**Issue by lbestock** [arch-kiosk/arch-kiosk-office#2043]
Testing KHPP on my iPad mini and not sure if this is more general.
Looking at old data, where there are drawings in the locus relations I can click on the image and bring up the "actions" popup menu. This is as expected. But if I hit "view" I am given just a blank black screen with the UID at the top of it. I can hit "done" and return. If I use our little expander button I can see the image larger in a popup. This only seems to be the case with images that are sketches, not with photos. And I am not sure how those sketches were made, since they are old. Might be signature function? But if I use the signature function now to create a new image for a locus relationship I am able to use that popup action to view it.

I have seen this behavior with two old relations drawings in E14.1.

I should note that this is not a big problem and unless you, @urapadmin, are worried it might be indicative of something more sinister, it is not a pre-season priority.

**Comment by urapadmin** [comment]
no, the "View" feature is beyond my influence. Not sure what can cause this. Is it possible that your general issues with showing images might have caused this? Please try again with apps (particularly Browser tabs) closed.

**Comment by lbestock** [comment]
I closed a whole browser and tons of apps and this still happens.

**Comment by urapadmin** [comment]
I think you figured that out, right? The answer is: Don't use dark mode on your ipad in the field.

**Comment by urapadmin** [comment]
have you added this somewhere in a doc?

**Comment by lbestock** [comment]
Yup.
