### ISSUE TITLE
update demo server with ARCH1900 data and check privacy issues

### ISSUE THREAD

**Issue by lbestock** [arch-kiosk/arch-kiosk-office#2045]
We would like to share demo versions with potential new projects during the recruitment phase. We have discussed using ARCH1900 data as the means to do this, in part because one new project we are talking to is interested specifically in recording a practicum class. One concern we have is student privacy.

**Comment by urapadmin** [comment]
I have done this. The demo server has arch1900 data but the users are the original for the demo server.

**Comment by urapadmin** [comment]
next would be to look through the data and see if we can use it without violating anybody's privacy

**Comment by urapadmin** [comment]
@lbestock Do you do that?

**Comment by lbestock** [comment]
I will.

**Comment by lbestock** [comment]
Ah I can't? Can you check on the demo server? I get an error in preparing, even though I deleted my dock and made myself a new one.

**Comment by urapadmin** [comment]
the online demo server is updated.

**Comment by lbestock** [comment]
This is riddled with privacy concerns. Not just that users whole names are in there, but also in narratives people are referred to by first and last name.

**Comment by urapadmin** [comment]
that's too bad. Then we cannot use it. Or do you see the possibility that we can catch them all? (I can do bulk search / replace on SQL level if I know what to search for and where)

**Comment by lbestock** [comment]
Problems we would have to replace:

- names in the team members - initials can stay, names cannot
- full names as used in trench narratives (warning! in at least one case a guest was referred to by full name and was not a student, so the list of students would have missed him)
- I've even hit one place in a CM where someone is referred to by name (nice recording, guys) but it is not a full name. Still, maybe we should search all description fields.

**Comment by lbestock** [comment]
There are a few with people, and even a few with labeled people. But they are few enough and easy enough to find in the File Repository that we can remove them singly with no problem.

There are also a few broken files in the File Repository.

**Comment by urapadmin** [comment]
well, then you should erase those photos and then we can sit down and erase the names together via SQL.

**Comment by lbestock** [comment]
All the bearded sampler photos removed.

**Comment by urapadmin** [comment]
closed in favour of #2662
