### ISSUE TITLE
"su_ceramics_processing" should not be necessary in "ceramic module" for preprocessing

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#2047]
but it is: Currently it is not possible to show the ceramics preprocessing without having su_ceramics_processing in "ceramics_module".

**Comment by urapadmin** [comment]
no, it is necessary. For the 100s time: the material determines the ceramic module id and the ceramic module id determines the main ceramic analysis layout. An that's the problem: the ceramic material must determine more than just the ceramic module. But since it does not and I cannot change this whole logic, we have to live with this. 
But I will amend the info in the help titles.

**Comment by urapadmin** [comment]
Already explained here: #1131

**Comment by urapadmin** [comment]
### recording 14.3.4
- added some words to the help texts of these and referred to #1131 and this here.

**Comment by lbestock** [comment]
The constant headaches appear likely to continue. But it works and KHPP is properly configured.
