### ISSUE TITLE
configuration: show_volume_for_material should refer to CM type sample

### ISSUE THREAD

**Issue by lbestock** [arch-kiosk/arch-kiosk-office#2048]
Result of changing CM. Volume used to be setable for material types, and in at least KHPP is set to soil. But really this should be about sample volume now and it is a useful thing to have, it just no longer really has a home - you wouldn't collect bulk soil, you would collect sample soil. And all samples, regardless of material, would want this, and no bulk would (I think). So I would want a way to make the configuration key refer to CM type, not material type.

**Comment by lbestock** [comment]
However, the valuelist for material is the same for sample as it is for bulk and special finds. So perhaps this isn't important. For KHPP for the time being at least I will make sure "soil" is a material type and that it triggers the volume measurement.

**Comment by urapadmin** [comment]
### recording 14.3.4
too much ado for a single field, if you ask me: 
- there is a key "show_volume_for_cm_type" now. The help text for it should explain what it does
- the key "show_volume_for_material" works alternatively, which means that for a cm_type that does not show volume on its own you can still make the volume visible for a certain material
