### ISSUE TITLE
KHPP survey unit bulk CM: lots is visible and has a choice it should not have

### ISSUE THREAD

**Issue by lbestock** [arch-kiosk/arch-kiosk-office#2050]
Testing KHPP on my iPad (acquired with Bridge, worked like a dream).
I have created a bulk CM record in a survey unit. It asks me to identify a lot, as though I were in an excavation unit. Not only that, but it gave me the option of two different lots to choose, which should not happen since the very locus here is hidden, never mind the lots.
![image](https://user-images.githubusercontent.com/49291909/233217931-a6571485-f9c6-4429-b7a8-960c70ec11e8.png)

**Comment by urapadmin** [comment]
if that survey unit is using "transect" then that can be correct. The transects are lots.

**Comment by lbestock** [comment]
Aha cool. Are, and should be. And yes, when I add another transect, there is a third lot so I can keep CM separate by transect if I want to.
