### ISSUE TITLE
locus formation process is editable even if configured not to be

### ISSUE THREAD

**Issue by lbestock** [arch-kiosk/arch-kiosk-office#2051]
Testing KHPP 14.3.4.
Architecture as a locus type does not have the "formation process editable" button clicked. But when I make a new architecture locus, I can choose, and it remains choosable. This is only the case if there is no preset, but even so it is disconcerting that something is said to be not-editable, and then it is.

**Comment by urapadmin** [comment]
it just does not make much sense to not have a preset and not have it choosable. That would always lead to an empty field. In that case why show it at all? I remember that that's the rational behind it. Should you forget to give it a default it becomes choosable. 
Or did I not understand your complaint?

**Comment by lbestock** [comment]
I missed it. You have understood me, and your explanation makes sense.
