### ISSUE TITLE
Start page: TEst mode and simple excavating should not be visible

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#2055]
except for testers and developers

**Comment by urapadmin** [comment]
### recording 14.3.6
- simple excavating is obsolete, anyhow, so that button won't be visible ever anymore.
- test mode should only be visible if test mode is off and the user has the "tester" privilege.

**Comment by lbestock** [comment]
Clicking the button to go into test mode as a tester also resets the configuration key in admin to yup. If that's what you expected, and forgetting the weird single incident of the admin user login mystery, this can be closed.

**Comment by urapadmin** [comment]
that is what the button does, yes. I have added a section about how to reset the admin password in the Q&A.
