### ISSUE TITLE
configuration "hide_main_ceramic_analysis" does not synchronize

### ISSUE THREAD

**Issue by lbestock** [arch-kiosk/arch-kiosk-office#2057]
Testing KHPP.
Twice now I have changed the "hide_main_ceramic_analysis" key from nope to yup and seen that it does work, it hides the main ceramic analysis. But then when I synchronize and download again, the key is back to nope and the ceramic analysis is there.

**Comment by urapadmin** [comment]
### recording 14.3.6
- correct. That was set to not synchronize for some reason. Now it should sync.

**Comment by lbestock** [comment]
Does. Bridge, I reiterate, is really great.
