### ISSUE TITLE
khpp config: It makes sense to write the registration code into the label of the code

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#2059]
The configuration keys in ToDo and Done translate a key into a label. Since one deals with the codes in the list view I think it is useful to have the codes in the labels so that one sees the connection between code and label in the popup with the checkboxes.

**Comment by lbestock** [comment]
This is not configurable by me right now? At least, the valuelists that give to do and done for the checkboxes already include the codes in the valuelists, but those codes are not present in the registration status popup where one checks boxes. I agree it is a good idea I just don't know how to make it happen.

**Comment by lbestock** [comment]
Ha idiot. Of course I can do it, I just have to make it say "H=H Expected back from the field"

**Comment by lbestock** [comment]
Done and synchronized.
