### ISSUE TITLE
FM simple configuration: "deprecated" is visible in the dropdown menu

### ISSUE THREAD

**Issue by lbestock** [arch-kiosk/arch-kiosk-office#2060]
The key "show_insert_qr_code_substitute" got turned on for simple configuration and so "deprecated" is available in the drop down menu, which is not what we want. Teeny tiny.

**Comment by urapadmin** [comment]
### recording 14.3.8
- that should be gone now

**Comment by lbestock** [comment]
Nope, still there.

**Comment by urapadmin** [comment]
you prepared yourself a new workstation?

**Comment by lbestock** [comment]
At least, I prepared an old workstation again and checked it was 14.3.8.

**Comment by urapadmin** [comment]
hmpf. Try again with 13.4 on khpp, please.

**Comment by lbestock** [comment]
What is 13.4?? 14.3??

**Comment by lbestock** [comment]
KHPP is on 14.4 now, and didn't give me the patch warning, and still has the single deprecated key hanging around in simple configuration.

**Comment by luizaogs** [comment]
Hm I'm looking at 14.4 for KHPP and do not see the deprecated key in simple at all. But I got the workstation with the patch, so I wonder if that is why?

**Comment by urapadmin** [comment]
@lbestock: That was yours
