### ISSUE TITLE
KAMBE concordance meeting

### ISSUE THREAD

**Issue by lbestock** [arch-kiosk/arch-kiosk-office#2062]
Laurel and Katie will meet Monday April 24 to talk KAMBE concordance. This ticket is for some questions before the meeting and some notes from the meeting.

The elevations records on the context sheets - we currently only have room for calculated elevations. Honestly I think it's easier to record the BS and instrument height and all on paper, but we should talk through that part of the workflow. Elevations are clearly a big part of the recording at KAMBE.

Plan drawing of contexts with elevations marked are also a thing. You could consider a template in TouchDraw that has the same instructions and base marks as the context sheet. 

Context type for KAMBE: "feature/wall". We use "feature" somewhat differently (oh my god, old nightmares will return). Ask Katie if "architecture" is OK here. (It was also a hand-filled in type of context when I ran into it on their recording; their sheets only allow for fill or cut.)

MAJOR: how are collected materials tagged and numbered? And moved around?

Valuelist: period

CM: do you want inventory number visible? And called what?
Do you want number of bags? For everything or only selected things?

If we leave ceramic preprocessing on, it is an option if we have count and weight auto-sum or have them as fillable fields.

**Comment by urapadmin** [comment]
I suppose we can close this?

**Comment by lbestock** [comment]
We can!
