### ISSUE TITLE
FM labels in deposit: changed terminology not reflected

### ISSUE THREAD

**Issue by lbestock** [arch-kiosk/arch-kiosk-office#2065]
KAMBE calls deposits fills.
This is configured for KAMBE and is reflected properly in some but not all locations. Two we caught:
![image](https://user-images.githubusercontent.com/49291909/233719128-db9015b5-8c9d-416b-b6f0-1b7b5dc392fc.png)

**Comment by urapadmin** [comment]
### 14.3.7
- that would have been the same with architecture and burial! If you name architecture structure and burial Grave or so those terms should be used in the title and headings
- and of course this should work in deposit

**Comment by luizaogs** [comment]
Works.
