### ISSUE TITLE
FM record details for deposit: no record created?

### ISSUE THREAD

**Issue by lbestock** [arch-kiosk/arch-kiosk-office#2066]
Strange behavior testing KAMBE.
The locus configuration has it as fill, but with deposit detail recording.
The locus is created properly. 
The details entry opens properly, but most of it cannot be entered and the "created by" thingee at the bottom left is empty. Clicking in most fields does not raise the keyboard or give us a cursor. Clicking on the sorting image has to be done twice to get one to highlight, and that isn't saved if one leaves the tab. The only editable field is soil colour, which can be filled in and retains its data.

This does not happen with the record details for architecture or burial, which behave as normal.

**Comment by urapadmin** [comment]
uugly error., Shows that we were not testing this anymore with real data and in all respects. This happens when going back from the deposit layout: The detail record gets deleted. Must come from deleting detail records after changing the context type.

**Comment by urapadmin** [comment]
there is a key system/locus_type_tables that I don't like. I would totally forget to add a new locus type to that one.

**Comment by urapadmin** [comment]
### recording 14.3.7
- the bug is fixed

**Comment by luizaogs** [comment]
Works now.

**Comment by lbestock** [comment]
I am only 98% sure of this and must test it again. But I put soil compaction in KAMBE last night when I was putting in real data, and it's not there for either of the loci it should be there for this morning. The soil color did synchronize. So this might not be solved after all, or else there is still something wrong in the KAMBE configuration.

**Comment by lbestock** [comment]
Definitely still losing the data at synchronization. @urapadmin I am not sure what I should do with configuration settings - can you please look at it?

**Comment by urapadmin** [comment]
This is an entirely different bug: #2074 
This here can stay closed.
