### ISSUE TITLE
FM valuelist soil compaction type: make non-sorting

### ISSUE THREAD

**Issue by lbestock** [arch-kiosk/arch-kiosk-office#2067]
Tiny little request.
The valuelist for soil compaction type sorts alphabetically. That list is an ordered one and would be easier to use if it didn't sort but rather reflected the order the values are put in in the valuelist.

**Comment by urapadmin** [comment]
### recording 14.4.1
- those are harder than you think. I would not want to many of those value lists that keep their sorting order. Please test, test that adding things in the config works 
- and test that period in collected material still works

**Comment by lbestock** [comment]
Both work, and allow me to add new lines to the valuelist and they do not sort, as they should not.
