### ISSUE TITLE
FM configuration: deposit_default_format not working

### ISSUE THREAD

**Issue by lbestock** [arch-kiosk/arch-kiosk-office#2070]
Testing in KHPP 14.4.1
The deposit_default_format key is set to text, but when one makes a new deposit locus and goes into the matrix tab, percentages are the open default. One can get to text, but it isn't the thing that pops up which is what this key is supposed to control.

**Comment by urapadmin** [comment]
### recording 14.4.1
- FileMaker. Wow. The lot-id as a whole was set to "Number", although it isn't a number. And so it does things. Should be better now.

**Comment by urapadmin** [comment]
### receording 14.4.2
- that was a mess since PACHA. Should be better now.
