### ISSUE TITLE
FM recording lots: tiny formatting issue

### ISSUE THREAD

**Issue by lbestock** [arch-kiosk/arch-kiosk-office#2071]
What, we have a European developer? 
Lots have an ID that has a comma where elsewhere there is a point. How does that even happen, since the locus has a point and the ID method is locus dependent? 

See here:
![image](https://user-images.githubusercontent.com/49291909/233857034-9a904d9b-0a58-4386-a511-b71e81c27786.png)

(Obviously I am testing in KHPP, 14.4.1.)

**Comment by urapadmin** [comment]
### recording 14.4.1
- Ja. FileMaker treating texts as numbers, I suspect. Is it gone?

**Comment by lbestock** [comment]
We're in the same version still, 14.4.1? But also no. When I create a new unit and locus and lots in it, this does not occur. But when I go back into E14.1-012, a real locus from KHPP, both the previously existing lot 1 and my newly created lot 2 have the comma instead of the point.

**Comment by urapadmin** [comment]
no, 14.4.2 has the fix. Coming up ... I confused versions.
