### ISSUE TITLE
FM recording: sample CM formatting issue

### ISSUE THREAD

**Issue by lbestock** [arch-kiosk/arch-kiosk-office#2072]
KHPP 14.4.1 testing
Sample creation in CM: there is a double label and thus an illegibility - the field is volume, but it is in the same location where weight would be on a bulk record. The "weight" label seems to be lurking around and making it impossible to read.

![image](https://user-images.githubusercontent.com/49291909/233858436-dccf1258-ad4c-4645-b0e4-c52af73c01e3.png)

For whom did we do volume? I would sure weigh rather than measure volume for my sampled soil, Jesus. Unless it was in absolutely massive bags. So I thought the simple solution here was just to get rid of the weight label, but in fact I think it would be more useful to move volume down and have both present for samples.

**Comment by urapadmin** [comment]
I suspect the idea here was that it should be either weight or volume. Can't it be configured that way?

**Comment by lbestock** [comment]
They appear to be separate. Weight can be hidden for particular materials (but not CM types). Volume can be shown for either CM types or materials listed. So theoretically one could have both, in which case they should not occupy the same space on the layout (which I guess is just what happens here).

**Comment by urapadmin** [comment]
of course it is, but I usually do that only if they are not meant to be visible at the same time. I don' think this is a mistake (in fact it is sheer horror in layouting to have things stacked on top of others). We have very limited space on that layout. So the question here is: Is it really necessary that they are visible at the same time? Otherwise configuration must be designed so that they are not.

**Comment by lbestock** [comment]
No, it is not necessary. It should be either/or, and I can see how to configure KHPP so that it is weight. 
Meanwhile however it looks different in CM feature recording where with the same configuration that was giving that mess above we can see volume only, not the doubled. Is that what you would expect??

**Comment by lbestock** [comment]
Ah no, ignore me. When one chooses a material that is so configured, one can still get the doubling. I see what to do. This is just me configuring, nothing for you to do here so I'll close it.
