### ISSUE TITLE
Kiosk restore: Restoring file repository says "backing up..."

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#2073]
instead of " restoring ... ". Just some copy & paste typo

**Comment by urapadmin** [comment]
could not really find that except when it was about the file repository. Was that what I meant then? A screenshot would have helped.

**Comment by luizaogs** [comment]
You didn't add a version here, so is there no new version? And is this testable on Beset?

**Comment by urapadmin** [comment]
I just forgot. Wasn't my best day today. And nothing is rolled out, yet. I hope for tomorrow.

**Comment by luizaogs** [comment]
Hm. Hope everything is ok.

**Comment by urapadmin** [comment]
just too blurry in the head.

**Comment by urapadmin** [comment]
### Kiosk 1.5.38.1
- could not really find that except when it was about the file repository. Was that what I meant then? A screenshot would have helped.
- I test this myself.
