### ISSUE TITLE
Files not imported because of wrong date and time on the local server

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#2075]
If date and time are not set properly, files won't be exported by file maker and the result is that they never get to synchronization.
That happened in our test with the khpp server.

So it is absolutely crucial to set the date and time properly on the server and on the ipads.

The server could create a reminder, I just don't know a proper trigger. Perhaps when it has not been switched on for a couple of days? 

Also: Can I think of a mechanism that catches this? Could the filemake workstation catch that it has not exported any images but that images had been changed during the session?

And why did the TimeZone check not kick in?

**Comment by urapadmin** [comment]
### recording 14.6
- This needs testing on both local server and PVD (the Chicago branch): @luizaogs are you out there?

**Comment by urapadmin** [comment]
good :o)

**Comment by luizaogs** [comment]
Ack Lutz sorry, I made a mess with the patch (long story short, I deleted a workstation and things moved around and I reset the one I should not have reset because I needed to import it for the patch). Can you override an import in logsmac? Or put the patch somewhere else?

**Comment by urapadmin** [comment]
just forget about the patch, not important

**Comment by luizaogs** [comment]
Ok then, with the workstation set to GMT-5 (Chicago time) I was able to import and synchronize both with the new config key turned on and off. Is that what's supposed to happen?

**Comment by urapadmin** [comment]
GMT-5 is your usual setting in Chicago, right? 
Yes, then it is okay. And if you get rid of the workstation setting entirely (and prepare again), you should not be let in.

**Comment by luizaogs** [comment]
Ok yes, with the config key set to yup and no GMT whatever in the workstation I get this: 

<img width="806" alt="Screenshot 2023-04-25 at 1 03 26 PM" src="https://user-images.githubusercontent.com/67970402/234363749-3b4dd1e9-7efd-46a8-8811-a650c0bbd375.png">

**Comment by luizaogs** [comment]
I can login as admin, yes. Which config key is it?

**Comment by luizaogs** [comment]
Or wait, do you mean the new config key?

**Comment by luizaogs** [comment]
Of course you mean this config key. If deactivated I get this when logging in as myself. Seems right?

<img width="805" alt="Screenshot 2023-04-25 at 1 12 53 PM" src="https://user-images.githubusercontent.com/67970402/234365374-3036e332-77da-4199-ae3e-9bd0c733265a.png">

**Comment by urapadmin** [comment]
yes, that is the old time zone message (which is still valid). So that's correct. But I am still battling errors here on local khpp, so this can't be closed, yet.

**Comment by urapadmin** [comment]
👀

**Comment by urapadmin** [comment]
is it correct, that when you usually start in Chicago with your workstation properly set to GMT-5 that you still get a warning when opening the database? Something that says "please consider switching your time zone" but lets you in?

**Comment by luizaogs** [comment]
Yes, I get this: 

<img width="806" alt="Screenshot 2023-04-25 at 2 13 24 PM" src="https://user-images.githubusercontent.com/67970402/234379372-d8b5366e-1605-49cd-b46e-7ec7120b6cc2.png">

**Comment by urapadmin** [comment]
good. That will look a bit different (less scary) with the next version but all is now in order here.

**Comment by urapadmin** [comment]
I have to reopen this because it is buggy: It operates only on time and not on date. So 01. June 23 05:00:00 pm is EARLIER than 31. May 23 11 pm.

Wow. Dumb.

**Comment by luizaogs** [comment]
Did all of the above tests again, this is working fine.
