### ISSUE TITLE
Test Ticket: FileMaker Go 2023 is out

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#2076]
And so we need to test it on the ipads with the current FileMaker Recording.

**Comment by urapadmin** [comment]
This means particularly the horrors: 😨  test all image containers

**Comment by luizaogs** [comment]
This might be a post May 8th and Luiza's self-imposed dissertation deadline ticket, I think. But I will do it.

**Comment by urapadmin** [comment]
might be an attempt to keep you from dissertating so that you won't deserting your rewarding Kiosk job 😈

**Comment by urapadmin** [comment]
But really, this has no urgency as we tell all projects that they stick to FM GO 19 for now.

**Comment by luizaogs** [comment]
I won't be deserting my rewarding Kiosk job regardless :) (would like to desert the dissertation, but it feels a bit too late now)

**Comment by luizaogs** [comment]
I just went through all image containers, created a bunch of records, etc. No issues at all, so I think the new FM Go is just fine to use. 

Do I close this or do you want in under observation?

**Comment by urapadmin** [comment]
Let's close it but please keep using it. You are now our 2023 ipad tester while @lbestock stays on 2019 to cover both for a while.
