### ISSUE TITLE
clear all data button in Filemaker: make less accessible

### ISSUE THREAD

**Issue by lbestock** [arch-kiosk/arch-kiosk-office#2077]
The "clear all data" button is accessible to admins in the admin tab of the FM recording. It does have a warning. But it is still too dangerous. Make accessible only to developers or at least only in test mode, but developers makes more sense.

**Comment by urapadmin** [comment]
### recording 14.6.3
- button should only be visible to testers and developers.

**Comment by luizaogs** [comment]
Hm. I should be able to see the button in the admin tab if I am an admin tester? I do not (but can see that test mode has been activated).

**Comment by luizaogs** [comment]
Beyond that I don't actually know how to make myself a developer, I realize now.

**Comment by urapadmin** [comment]
switch developer mode to "true" (yup, not yup in this case) in the config

**Comment by luizaogs** [comment]
Oh right, I had done that before. But hm I don't see the delete button in the admin tab as a developer either: 

<img width="1023" alt="Screenshot 2023-04-30 at 3 47 28 PM" src="https://user-images.githubusercontent.com/67970402/235375531-c3101a9b-ae4c-4408-be64-f378f3fbaec2.png">

**Comment by urapadmin** [comment]
not a very successful little update

**Comment by urapadmin** [comment]
I was wrong in describing this. It should have been visible only if your are logged in as admin AND if your are developer. Testers are not at all involved here (no tester ever needed to use this as far as I can remember).
So please check this again with the current version.

**Comment by urapadmin** [comment]
I was wrong in describing this. It should have been visible only if your were logged in as admin AND the admin is a tester. 
That does not really make all that much sense, actually. 
I'll change that  ...

**Comment by urapadmin** [comment]
### recording 14.6.4
The button should only be visible if you are logged in as admin and are either in development mode or in test mode (which unfortunately is not necessarily the same as being a tester. You can be in test mode without being a tester, but let's not splitting hairs too much).
