### ISSUE TITLE
sites.brown.edu/kiosk: things needed for the website

### ISSUE THREAD

**Issue by lbestock** [arch-kiosk/arch-kiosk-office#2078]
We have started working on this website. Two of us. We need to track things that are needed:

- [x] contact link on the Join our Team (and elsewhere)?
- [x] a menu - the pages are not navigable currently
- [ ] an editor with an axe to cut Laurel's proseyness
- [ ] an absolutely basic intro video, we currently are not in complete agreement about whether or not this can be the same one for actual users and for soliciting new users
- [x] high resolution image of Lutz at dusk on the computer
- [ ] Current Projects page with links
- [ ] required equipment section / list of specifications 
- [ ] required knowledge section (? Laurel said she wanted this in a comment in the article)
- [ ] a What It Does Not Do List, in addition to the Kiosk Lets You section?
- [ ] Killer Features list

**Comment by urapadmin** [comment]
no, I will not check kiosk@brown.edu regularly. I hardly ever check it at all.

**Comment by urapadmin** [comment]
has to be laurel_bestock or we need to find a way to have a brown email that redirects automatically to one of us

**Comment by luizaogs** [comment]
Well if you guys want the outreach coordinator for new project recruitment to check kiosk@brown.edu and use that, I would be happy to add the account to my Apple mail app which already has like 10 accounts anyway. But that means that I check it regularly.

**Comment by urapadmin** [comment]
How can you know about your title? Have you been allowed to peekhole (holepeek?) into Laurel's ridiculous about page?

**Comment by luizaogs** [comment]
… possibly 👀

**Comment by urapadmin** [comment]
she didn't dare to tell me about it. But I found out ...

**Comment by luizaogs** [comment]
Ha. I loved it.

**Comment by urapadmin** [comment]
I found it funny, too. But I don't tell her.

**Comment by luizaogs** [comment]
I think that cat is out of the bag, now :) woops

**Comment by lbestock** [comment]
The fur is in the martini!
I surely do like working with you guys. Also it sounds like the right solution for the outreach coordinator for new project recruitment to be on top of that email address and to use it for such inquiries.

**Comment by luizaogs** [comment]
Then she shall be on top of it. I will just need a password, of course, once you want me to start using it.

**Comment by urapadmin** [comment]
not before the 8th, though! 👀

**Comment by luizaogs** [comment]
😭

**Comment by luizaogs** [comment]
Laurel and I briefly touched on the importance of having a Current Projects page with links etc. on the website. I added the information here: https://docs.google.com/document/d/1jUt3K_wXgYSzHuNNAlenavnAvHIb1fAKvuXRQzPHSSc/edit?usp=sharing

(Obviously not sure if more is desired than is already there, so please edit away)

**Comment by luizaogs** [comment]
Also, the outreach coordinator for new project recruitment needs the email password :)

**Comment by urapadmin** [comment]
The issue with the email is that I have no idea how to do that and if it is even possible since your don't have a Brown account. I have put in am IT request, let's see if they know more.

You don't have a Brown account, right?

**Comment by luizaogs** [comment]
I have a Brown alumni account.

**Comment by luizaogs** [comment]
But wait, dumb question: isn’t that its own email account ? With its own password? Why do I myself need a Brown account?

**Comment by luizaogs** [comment]
I'm thinking your basic intro video should be something like this .... : https://www.diggitarchaeology.com/ 

heh heh heh

**Comment by urapadmin** [comment]
I think we should make clear that synchronizing with a cloud might work fine when excavating in London but not on an Island in the Nile. However, I would love to know the price tag on something like that just for comparison.

**Comment by luizaogs** [comment]
That's all going in the article, fear not.

**Comment by urapadmin** [comment]
@arch-kiosk/test Just occurred to me: Please don't put e-mail addresses, web-site urls, user-ids or anything that could be misused on GitHub. Public GitHub repositories are being crawled to fish for such information and spam the world.

**Comment by luizaogs** [comment]
A suggestion that you guys can either take or leave, as you see fit: it's actually hard to tell what the video tutorials are about with a casual glance because the thumbnails are much bigger and more attention grabbing than the video titles/descriptions. I think it might be easier to navigate if you had just the titles of the videos show when one first navigates to the page (under the headings First Steps, Photo Import, etc.) and clicking on the title brought up the thumbnail of the video. Don't know if that's possible, even, but thought I would point it out.

**Comment by urapadmin** [comment]
It isn't as far as I can see in this limited WordPress environment.But it would also make the page a list of titles - that's a bit meager, visually. 

Perhaps we can give a bit more information about the single videos themselves. I can also make the thumbnails smaller (I had it that way before but that rendered the titles in the thumbnails illegible but that might be less of an issue).

**Comment by luizaogs** [comment]
I don't think you need to see the titles in the videos when you're just looking at the thumbnails since they are labeled. So maybe making them smaller is helpful.

**Comment by urapadmin** [comment]
I have started to organize videos in groups of three with smaller thumbnails. Does it strike you a bit better?

**Comment by luizaogs** [comment]
Yes, I think it's a lot easier to see them this way.

**Comment by urapadmin** [comment]
> Yes, I think it's a lot easier to see them this way.

good, then I'll change them all to that format bit by bit.

**Comment by lbestock** [comment]
We need a "killer features" list. And then links from things in the list to give more explanation if needed, and/or to a video tutorial. We discussed doing this with the archaeological numbering, which sits awkwardly now as its own page. Let's here make a list of killer features; I don't want to make a new page until it's semi-complete.
- [ ] configurable archaeological numbering
- [ ] configurable terminology
- [ ] QR code photo recognition - use the iPad as a photoboard OR bracket a series of photos by shooting images of the iPad before and after, and have the photos between be automatically assigned to the context in the QR code
- [ ] registration
- [ ] ceramics pre-processing
- [ ] bring your own ceramics module
- [ ] context recording for excavation
- [ ] survey: transect or grab, feature creation
- [ ] Director's View
- [ ] quality control
- [ ] file picking
- [ ] synchronization itself is super killer - does it get a line item here?
- [ ] reports
- [ ] image tagging
- [ ] locus tagging
- [ ] inventory

**Comment by luizaogs** [comment]
I think the list is pretty complete? The only things that come to mind that are not in there are legacy recording, but at least in the article you didn't really want to highlight it as a separate thing, and the point repository with images for control points.

**Comment by lbestock** [comment]
Ha, definitely added file repository; that's a killer feature. I added the narrative journaling, too, but that is an interesting one. I can't imagine doing without it in the field, like you. But some directors are vehemently against allowing any records that are not context records. It's a sort of purity of MOLAS thing, in part. So a reaction against the idea that there is any room for the arbitrary in archaeology and we must concentrate exclusively on the intrinsic, which is of course as problematic as any other type of purity. But then I have also run into shades of the frustration we have that we tried to combat with separating observation and interpretation (and not calling observation "description"). I have definitely talked to people who find any allowance of narrative to mean their students record any and all interpretation narratively and then it gets mushy and all interconnected instead of arguing context by context why they interpret a context the way they do. Funny. I like archaeology. Anyway, I think some people will think narratives are a killer feature and some people with think narratives are horrible and if we designed a system that allows them we must not be proper archaeologists. I can live with it. Allowing for narrative without insisting on it is a killer feature.

**Comment by luizaogs** [comment]
I would think that's an issue with the students, not the narrative recording itself. Bah.

**Comment by lbestock** [comment]
Hm. Hm. I had started it thinking not, but presumably we need to imagine the role this list plays on the website to answer that.

**Comment by luizaogs** [comment]
Well, there is at least considerable overlap already with the Kiosk Lets You section.

**Comment by urapadmin** [comment]
The web site must go up the priority list for ARCE and this year I am in charge.

**Comment by urapadmin** [comment]
we have decided to be done with this
