### ISSUE TITLE
admin password changes if I make admin a registrar

### ISSUE THREAD

**Issue by luizaogs** [arch-kiosk/arch-kiosk-office#2079]
Weird bug (?). I'm trying to test #2077. I log in as admin with the usual admin password just fine, and head to the team members thingy. I make the admin a registrar. I log out. I try to log back in with the usual admin password and am told that it is wrong. So somehow the password changed after I made the admin a registrar? I tried this twice, it happened both times. 

14.6.3.

**Comment by luizaogs** [comment]
This also happens if I follow the same steps as above but instead of registrar I make the admin a tester.

**Comment by urapadmin** [comment]
In fact we have had that before. It is strange, indeed.

**Comment by urapadmin** [comment]
I cannot for the life of me reproduce that. Can you try to describe step by step what you do?

**Comment by urapadmin** [comment]
After checking the registrar box you do what? Leave via "X"? Move to the next record first?

But I guess it does not matter. I tried that. Can you check if on login when your password gets rejected the user id is capitalized and try around with lowercase / uppercase and see if that makes a difference? 

Does the same thing happen to a different user than admin?

**Comment by luizaogs** [comment]
I just leave via X, no moving to other records. 

It doesn't work with lowercase. Though I say lowercase but you know that it becomes uppercase when I click on enter on my Mac, I suspect? And so when I get the box to type in the password it's in uppercase. 

Let me check if I use caps lock to type in uppercase from the beginning ... yeah, no difference.

With other users: 
I logged in as LOGS. Went to the team members menu. I make Rose a registrar by checking the box. Close out of team members via X. Logout. Log back in as Rose just fine. So no, it seems like an admin thing (I assume because admin has a password in the first place.)

**Comment by urapadmin** [comment]
yes, that's what I had in mind. I really don't get what is going on there,

**Comment by luizaogs** [comment]
Ok. I gave user CAT a password (meow). Logged in using that password. Logged out as CAT. Logged back in as LOGS. Made CAT a registrar. Left the team members menu via the X. Logged out. Tried to log in as CAT and ... it worked. So I guess it is an admin problem.

**Comment by urapadmin** [comment]
### recording 14.6.5
Got him 🐛. I was looking in the wrong corner. Funny coincidence. Only happens with users that got their passwords while their user id was lowercase :o) Don't ask. Should not be a problem anymore.

**Comment by luizaogs** [comment]
Don't kill me. I am still getting it...

**Comment by luizaogs** [comment]
So you can see that I am on 14.6.5 :)

<img width="1019" alt="Screenshot 2023-05-01 at 7 59 44 PM" src="https://user-images.githubusercontent.com/67970402/235557356-ab12e11e-3968-4604-b378-6ce850bb7c86.png">

Blah.

**Comment by urapadmin** [comment]
what a nasty little fella...

**Comment by urapadmin** [comment]
### recording 14.7
- okay, I was just dumb, the fix did not make it into the update. Next try.

**Comment by luizaogs** [comment]
Phew.
