### ISSUE TITLE
new locus field "Excavated with" (valuelist: heavy machinery, pick, handpick, trowel, brush, small tools)

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#2082]
### recording 14.7
- controlled by the config key "valuelist_excavated_with"
- should not be visible at all if the valuelist is empty

**Comment by luizaogs** [comment]
This one also has the hyphen thingy I mentioned in #2084

**Comment by luizaogs** [comment]
If I delete all of the values I don't see the drop down in the locus form any longer but I see this: 

<img width="389" alt="Screenshot 2023-05-01 at 8 38 57 PM" src="https://user-images.githubusercontent.com/67970402/235561335-d0524135-aa04-47d3-8c47-544c113ee16f.png">

**Comment by luizaogs** [comment]
Synchronization worked, so I guess it's just the hyphen thing and the excavated with label still being visible after the value list has been emptied.

**Comment by urapadmin** [comment]
the hyphen thingy is fine, the prevailing label is not.

**Comment by urapadmin** [comment]
but that is tiny, I'll do that with the next feature, no new update just for that.

**Comment by urapadmin** [comment]
### recording 14.8
- the label should disappear together with the field now
