### ISSUE TITLE
new deposit field: Contamination

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#2083]
A valuelist of "high; mid-high; mid; mid-low; low; sealed" looks as if this had better keep its sort order as it was input in the valuelist.

**Comment by urapadmin** [comment]
### recording 14.7
- this valuelist should keep its sorting order
- the config key is valuelist_deposit_contamination

**Comment by luizaogs** [comment]
The key is fine, still need to check synchronization.

**Comment by luizaogs** [comment]
Synchronization worked.
