### ISSUE TITLE
new deposit fields: Clarity of horizon, top / bottom

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#2084]
so two new fields in the locus deposit layout using and showing the same valuelist:
clarity of horizon, top
clarity of horizon, bottom

values are: sharp; fair; merging

**Comment by urapadmin** [comment]
### recording 14.7
- config key for the value list is "valuelist_deposit_clarity_of_horizon"

**Comment by luizaogs** [comment]
Should these dropdowns have the option of a hyphen as the first value, and if I click on it it stays empty? (Somewhat related: I just noticed that soil texture also has that, but contamination and soil compaction type do not.)

**Comment by luizaogs** [comment]
Synchronization worked, so if the hyphen thing is fine this can be closed.

**Comment by urapadmin** [comment]
yes. That's the new way of doing valuelists (unfortunately not working for those that keep their order). Those valuelists have the ability to be easily blanked again. I am just really too lazy to go through ALL valuelists and apply this new technique.

**Comment by luizaogs** [comment]
Ah. Well then this is good!
