### ISSUE TITLE
Problems starting a virtual machine

### ISSUE THREAD

**Issue by lawarden** [arch-kiosk/arch-kiosk-office#2085]
When trying to start the virtual machine through Virtual Box, I am given the following error message:
![image](https://user-images.githubusercontent.com/132224283/235763562-e6134ac4-297d-452f-9f45-73b3cc126e08.png)

Now the virtual box says the start up was aborted. I ejected the media from Windows 11 but am worried about shutting down my machine as it tells me Virtual Box is still connected.

**Comment by urapadmin** [comment]
btw. if you shut down your machine anyhow, you can spare yourself the steps of ejecting your drives first. You can disconnect the drives once your computer is down. 

But since the drives were connected I suppose the usb hub was, too, so I am a bit at a loss why the network adapter wasn't present. Does rebooting your computer help?

**Comment by lawarden** [comment]
I feel ridiculous and overly nervous asking, but:

Will I break everything if I just reboot?

That was my first plan, but with the series of error messages (including noting that Virtual Box was still connected!) I was worried about breaking it. It seems silly to type, but there's a lot riding on this vm.

Leslie Anne Warden, PhD
Joanne Leonhardt Cassullo Associate Professor of Art History and Archaeology
Director, Kom el-Hisn Provincialism Project
Coordinator, Archaeological Sciences Concentration
Chair, Faculty Personnel Committee

Roanoke College, Dept. of Fine Arts
221 College Lane
Salem, VA 24153
***@***.***
pronouns: she/her/hers
________________________________

**Comment by urapadmin** [comment]
no, rebooting is often a good idea with such things. As long as you make sure that the OS inside the Virtual Machine is shut down (which is the case in your case as it never came up), rebooting and shutting down is safe.

I know, running a VM is a strange thing in the beginning and it never is flawless. You'll get into the swing, soon.

**Comment by urapadmin** [comment]
should this be persistent we can also take this as a good reason to just test the SOS remote access.

**Comment by lawarden** [comment]
Just rebooted and reconnected everything... same issue

**Comment by urapadmin** [comment]
So USB hub and everything is connected while you boot up? 
Can you please use [Win-Key]+X, network connections (on your Win 11) and look if your local windows shows you the Ethernet connection? And if so, please click on "private" (remember, that was part of setting it all up) and scroll all the way down to see if the Ethernet adapter actually says ASIX AX88... and shows you an ip address (should be 192.168.8.2) down there.

**Comment by lawarden** [comment]
Yes on usb hub being connected

Network stuff: in short, ethernet seems to be fine unless I am mistaken...

[cid:57bae6c5-e804-4f28-88b3-97e11f21cd0f]

[cid:7d61f912-a62e-4639-ba9f-4e29c38f9da5]

________________________________

**Comment by urapadmin** [comment]
Those might have been images - they did not come through, but I assume you found the network stuff as described. 
Alright, then next is going to Virtual Box and with the VM not running go to the settings of the Kiosk VM, network and make sure that the ASIX ethernet adapter select the ASIX Ethernet adapter again from the selection. After that you should be able to start the VM normally. 

Why Virtual Box has forgotten the former setting? I can't tell.

**Comment by lawarden** [comment]
That was it! Fixed and starting up. Thank you!

**Comment by urapadmin** [comment]
I have a hunch that you should remember the solution :o)

**Comment by urapadmin** [comment]
sorry, I meant memorize ... it might happen again,
