### ISSUE TITLE
FileMaker recording: The database has been prepared in the future

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#2087]
@cmkearns reported:

> Is there an easy way to check what the local time zone setting is and how to fix it? I'm now getting this error message in Kiosk in Filemaker Go, and there doesn't seem to be a way to bypass it like there was before - 
> 
> "the database has been prepared in the future (02.05.2023 22:34:35). That suggests that the server or the local ipad are not set to the same date and time. It is also possible that the workstation in Kiosk has a wrong time zone setting."
>

**Comment by cmkearns** [comment]
Many thanks! This all makes sense and after prepping for class I will return to the ipad to play around with it this evening.

Katie

**Comment by lbestock** [comment]
Has been added to the Answers to Questions manual.
