### ISSUE TITLE
navigating from narrative and back: Scroll to the last active narrative

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#2088]
The title says it: When navigating away from the current unit narrative with some navigation thing and then coming back through the back button the last active narrative must be activated again.

**Comment by urapadmin** [comment]
this is particularly helpful with #1815

**Comment by urapadmin** [comment]
### recording 14.7
- that was veeeery fiddly. Not only needs it testing itself
- also navigating away from the narratives and from the unit by other means (search / recently viewed) and back needs testing just to see if it behaves as it once did (note that the current narrative is only restored when using the new reference navigation)

**Comment by luizaogs** [comment]
Hmm, it is working but the current narrative is not only restored when using the new reference navigation. It did return to it when I was using the new reference navigation, but now also returning to the narratives tab from everything from coordinates to loci by different means (recently viewed, back button), etc., takes me back to the current narrative.

**Comment by luizaogs** [comment]
I'm trying to find a pattern and somewhat failing.

**Comment by urapadmin** [comment]
see #2100

**Comment by luizaogs** [comment]
I saw it! I had a cookie this morning!

**Comment by luizaogs** [comment]
> Hmm, it is working but the current narrative is not only restored when using the new reference navigation. It did return to it when I was using the new reference navigation, but now also returning to the narratives tab from everything from coordinates to loci by different means (recently viewed, back button), etc., takes me back to the current narrative.

Yeah this is the case even for records I didn't navigate TO with the reference navigation. So basically, it seems like once I use the reference navigation going back to narratives will always take me back to that narrative -- unless I'm going in through the start page, or just going to the unit itself through search.

**Comment by urapadmin** [comment]
that was a polite attempt to point your attention to where it must be.

**Comment by luizaogs** [comment]
I tried napping. I can't. So testing it is.

**Comment by urapadmin** [comment]
> Hmm, it is working but the current narrative is not only restored when using the new reference navigation. It did return to it when I was using the new reference navigation, but now also returning to the narratives tab from everything from coordinates to loci by different means (recently viewed, back button), etc., takes me back to the current narrative.

- It would be logical that the recently viewed takes you back to the narrative if that recently viewed item was created when jumping from the narrative somewhere else. That is also true for the entry in the navigation history.

- It is not okay if you e.g. jump from a narrative to a locus and use that same locus to jump forward to the same unit you came from. 
- Also not okay would be to use the ref navigation to a locus, go back to the narrative, then use the locus tab to jump to a locus and back again to the unit. 

I can imagine that the last two might happen due to a side effect...

**Comment by luizaogs** [comment]
No, the last two don't happen. But there was something else weird going on. Let me try to get it again.

**Comment by luizaogs** [comment]
Go to unit LA, narrative that mentions LA-014 and LA-015
Use reference navigation to go to LA-014
Use back arrow to go back, see the narrative, fine
Go to coordinate B2 via search, while the screen is still on that narrative with LA-014 and LA-015
Use the back button to go back to LA , and the narrative is still on the screen
Go to coordinate B3 via search, while the screen is still on that narrative with LA-014 and LA-015
Go back to LA via recently viewed, and that same narrative is restored again

That's what I meant, since I didn't use the reference navigation to go to coordinates at all. Is that ok?

**Comment by urapadmin** [comment]
yes. The restoring of the narrative is not a feature exclusive to the reference navigation it kicks in for search and using foot steps. Everything that is done by the new navigation system I came up with in the fall. 
Let me modify your test:

Go to unit LA, narrative that mentions LA-014 and LA-015 (Narrative A)
Use reference navigation to go to LA-014
Use back arrow to go back, see the narrative, fine
Go to coordinate B2 via search, while the screen is still on that narrative with LA-014 and LA-015
Use the back button to go back to LA , and the narrative is still on the screen
- Move to a different narrative  (Narrative B)
- Go to coordinate B3 via search
- Go back to LA via recently viewed, and that narrative B should be restored

**Comment by luizaogs** [comment]
Hm. No, I got narrative A at the end again. Let me try it one more time.

**Comment by luizaogs** [comment]
Yeah no, Narrative A is still the one coming up at the end there. I even clicked in the text box on Narrative B to see if that would change things and it did not.

**Comment by luizaogs** [comment]
So: 

Go to unit LA, narrative that mentions LA-014 and LA-015 (Narrative A)
Use reference navigation to go to LA-014
Use back arrow to go back, see the narrative, fine
Go to coordinate B2 via search, while the screen is still on that narrative with LA-014 and LA-015
Use the back button to go back to LA , and the narrative is still on the screen

Move to a different narrative (Narrative B)
Go to coordinate B3 via search
Go back to LA via recently viewed, and that narrative B should be restored --> But it's not. I get Narrative A back

**Comment by urapadmin** [comment]
- Does the same thing happen if you use the back button instead of recently viewed?
- Do you have two entries in the recently viewed pointing to that unit?

**Comment by luizaogs** [comment]
> * Does the same thing happen if you use the back button instead of recently viewed? --> Yes
> * Do you have two entries in the recently viewed pointing to that unit? --> No

**Comment by urapadmin** [comment]
### recording 14.8.3
This is fiddly but not critical. I have tried a somewhat different strategy:
- only if you use reference navigation you should come back to the narrative from where you started. The "recent " navigation can bring you back there too, on occasion but Is suspect mostly it won't. That's okay, I rather live with it than make changes with new side effects to the whole navigation system.
- the most important part here is navigating somewhere and getting back from there with the original narrative open.

**Comment by luizaogs** [comment]
Does the spider have a graduation cap now?

**Comment by luizaogs** [comment]
This is good now.

**Comment by urapadmin** [comment]
> Does the spider have a graduation cap now?

oh yes. Laurel made him a real Chicago graduation cap.

**Comment by luizaogs** [comment]
He’s so cute. I love it :)
