### ISSUE TITLE
goto_identifier needs to activate the correct session table

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#2089]
goto_identifier fails currently for loci, units etc. if it is called from a layout that is not based on excavating_session. So it must make sure that the correct session table is available before setting the parameters.

**Comment by urapadmin** [comment]
### recording 14.7
- that's implemented but it impacts navigating to identifiers in genera, so please test some searching for identifiers and going there and some navigating to them, particularly navigating to different record types

**Comment by luizaogs** [comment]
Everything is working as it should, as far as I can tell.
