### ISSUE TITLE
website thing(s)

### ISSUE THREAD

**Issue by luizaogs** [arch-kiosk/arch-kiosk-office#2093]
I saw the link to the website on Laurel's email signature the other day and looked at it again, and of course I noticed a typo and since it's on the email signature I figured I would tell you (and then promptly forgot, but here I am now). 

<img width="199" alt="Screenshot 2023-05-05 at 7 06 03 AM" src="https://user-images.githubusercontent.com/67970402/236453391-a277679e-538e-4e01-83a5-3ffc0d48d340.png">

Kiosk Lets You, rather :) (no apostrophe)

Also the about page isn't on the menu and that may very well be purposeful, but since it's hidden at the end of the Kiosk Lets You section I thought I would point that out, too.

**Comment by urapadmin** [comment]
typo changed
