### ISSUE TITLE
🎬 list of new features since Fall 2022 🎬 

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#2094]
means: Everything that has changed since the last version in the field.
What would that be?

### Users
- [x] KioskBridge (lkh)
- [x] Search button available in all layouts, which means: Also in SU ceramics analysis (ldb)
- [x] Navigation (lkh)
- [x] reference Navigation (lkh)
- [x] Filter in locus list - and filter elsewhere (e.g. in cm by trench which was already available last season) (ldb)
- [x] Extended locus relations (across units) (ldb)
- [x] new Narrative view (ldb)
### directors
- [x] updated registration (and just updated again) (ldb). see also #2151 
- [x] Temporary Free Input (lkh)
- [ ] coordinates (ldb)
- [x] Reduced / advanced configuration (and the search in the config) (lkh)
- [x] file sequence import (lkh)

And I guess there should be one for admins and one for users.

**Comment by urapadmin** [comment]
@luizaogs / @lbestock : Please add things you think should be mentioned in the "what's new" video.

**Comment by luizaogs** [comment]
Suggestions:

Reduced / advanced configuration
Filter in locus list
Extended locus relations
Query and view? or are you not including it because it's not done?

**Comment by urapadmin** [comment]
> Suggestions:
> 
> Reduced / advanced configuration Filter in locus list Extended locus relations Search button available in all layouts Query and view? or are you not including it because it's not done?

Indeed, it won't be rolled out to local servers because it is useless in the current state.

**Comment by urapadmin** [comment]
@arch-kiosk/test We must make sure that these topics are at least in a basic version addressed in the Q&A or any other written documentation. Not everybody likes video tutorials and in once in the field they can be useless due to lacking internet connectivity.

**Comment by urapadmin** [comment]
@lbestock I have deleted the one you made on registration. It was too chaotic. I guess that needs a little bit more planning.

**Comment by urapadmin** [comment]
We skip the coordinates and are done
