### ISSUE TITLE
Recording login does not work if user does not have a name

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#2095]
The title says it all: It is possible to leave the name blank but then login would not work with that user-id

**Comment by urapadmin** [comment]
### recording 14.8.2
I did a couple of things here:

- the user name is mandatory now
- I cut away spaces left and right of the user id and the user name when a new team member is being created (or one is modified) as those dangling spaces can be a tricky issue to spot
- login with a user id that does not have a user name is permitted now

**Comment by luizaogs** [comment]
I'm confused -- how do I test the last bullet point if I can't create a user without a name?

The rest is working fine.

**Comment by urapadmin** [comment]
you can't unless you find a user without a name among the already existing ones. 
But I will simply roll this out to KAMBE and then you should be able to test this since that's where the bug was found.

**Comment by urapadmin** [comment]
It is rolled out to KAMBE

**Comment by urapadmin** [comment]
well, since I was on it, I quickly tested it and it works.
