### ISSUE TITLE
Q&A manual: Explain patching the FileMaker recording app

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#2098]
PAtches: Users might run into the message that they got a patch. We should have a section in the Q&A that explains it and explains what to do.

**Comment by lbestock** [comment]
I can write the what to do part, but in fact I am not totally clear on why to do it and so this one needs either you teaching me or you writing it.

**Comment by urapadmin** [comment]
The why is simple: A patch can come as part of a new version of the recording app (not all new versions have a patch included). With a patch the kiosk team changes a project's configuration settings for the FileMaker recording app. The changed configuration needs to be synchronized like all other changes in the FileMaker app and that's why you have to make sure to upload/import a workstation that gets the patch message on the start page.

**Comment by lbestock** [comment]
Ah, but I always thought it had to be the first person to download the new one. So if a project has a patch and batch prepares 4 workstations, and the first download ends up not being used but the other 3 are, and only those 3 are uploaded and imported and synchronized, the patch is OK?

**Comment by urapadmin** [comment]
> Ah, but I always thought it had to be the first person to download the new one. So if a project has a patch and batch prepares 4 workstations, and the first download ends up not being used but the other 3 are, and only those 3 are uploaded and imported and synchronized, the patch is OK?


No. You remember that correctly. Only the dock that gets prepared first after the new app was installed will get the patch message. So one has to make sure that the first dock actually gets downloaded.

**Comment by lbestock** [comment]
But if one batch-prepares, and doesn't actually download the first dock, one would never even know there had been a patch.

**Comment by urapadmin** [comment]
correct

**Comment by lbestock** [comment]
So the developer would want to tell people "hey, there is a patch, make sure you patch it" in a non-test scenario.

**Comment by urapadmin** [comment]
> So the developer would want to tell people "hey, there is a patch, make sure you patch it" in a non-test scenario.

he might. Or he would assume that they use all their docks, anyway.

**Comment by lbestock** [comment]
I would not make that assumption. Not even about Uronarti, should one ever dig there again. Totally conceivable that I have a director's doc and it's first in line in default and I don't go into the field one day and only the excavators do.

**Comment by lbestock** [comment]
This one I put in both the admins and the field workers Q&As.
