### ISSUE TITLE
Q&A: What to do with a dock that you don't want to import (explaining reset workstation)

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#2099]
I am not sure if the Q&A mentions this. But all projects, particularly when they are preparing and testing need to use this option.
It should also mention that the User might want to use the "reset ..." option in the Kiosk Bridge settings so that the current state is properly discarded (I am not sure if it is actually necessary).

**Comment by lbestock** [comment]
Done, two ways. But in combination with an assumption Katie made it makes me think about the menu in the Hub, so #2104.
