### ISSUE TITLE
Luiza's Dissertation

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#2100]
🍨 🍨🍨🍨🍨🍨🍨🍨🍨🍨🍨🍨🍨🍨🍨🍨🍨🍨🍨🍨🍨🍨🍨🍨🍨🍨🍨🍨🍨🍨🍨🍨🍨🍨🍨🍨🍨🍨🍨🍨🍨🍨🍨🍨🍨🍨🍨🍨🍨🍨🍨🍨🍨🍨🍨🍨🍨🍨🍨🍨🍨🍨🍨🍨🍨🍨🍨🍨🍨🍨🍨🍨🍨🍨🍨🍨🍨🍨🍨🍨🍨🍨🍨🍨🍨🍨🍨🍨🍨🍨🍨🍨🍨🍨🍨🍨🍨🍨🍨🍨🍨🍨🍨🍨🍨🍨🍨🍨🍨🍨🍨🍨🍨🍨🍨🍨🍨🍨🍨🍨🍨🍨🍨🍨🍨🍨🍨🍨🍨🍨🍨🍨🍨🍨🍨🍨🍨🍨🍨🍨🍨🍨🍨🍨🍨🍨🍨🍨🍨🍨🍨🍨🍨🍨🍨🍨🍨🍨🍨🍨🍨🍨🍨🍨🍨🍨🍨🍨🍨🍨🍨🍨🍨🍨🍨🍨🍨🍨🍨🍨🍨🍨🍨🍨🍨🍨🍨🍨🍨🍨🍨🍨🍨🍨🍨🍨🍨🍨🍨🍨🍨🍨🍨🍨🍨🍨🍨🍨🍨🍨🍨🍨🍨🍨🍨🍨🍨🍨🍨🍨🍨🍨🍨🍨🍨🍨🍨🍨🍨🍨🍨🍨🍨🍨🍨🍨🍨🍨🍨🍨🍨🍨🍨🍨

🍪

**Comment by luizaogs** [comment]
ew ew ew

**Comment by luizaogs** [comment]
I hate it :)

**Comment by urapadmin** [comment]
I know. That's normal. One is also just sick of it and asks questions like "does it live up to all the effort I've put in?" and things. And in the end more or less every sentence seems lacking and awkward and clunky. 
And tomorrow there will be this gaaaaaaaap. 

You have every reason to hate it :o)

Good that god made cookies.

**Comment by luizaogs** [comment]
Cookies are pretty great.

**Comment by urapadmin** [comment]
but you know that if it comes from me that it is more a biscuit? We really abhor those floppy chewy American cookies (I feel confident at least to speak for the sane part of my culture who does not go to Starbucks).

So have some water and tea with it! 🍵 🐃

**Comment by luizaogs** [comment]
Oh no floppy cookies here. Shortbread is my favorite. With tea, of course.

**Comment by urapadmin** [comment]
And I thought we can close this today, no?

**Comment by luizaogs** [comment]
🥳

**Comment by luizaogs** [comment]
(until they all tell me that I need to re-do it, that is)

**Comment by urapadmin** [comment]
which, of course, they will (but that's confident, so don't tell anybody)

**Comment by urapadmin** [comment]
why is there no shaking head emoji? I do that all day and feel utterly under-represented in the Emoji world.

**Comment by urapadmin** [comment]
I should be careful with you. You know I am kidding, right? 🍪

**Comment by luizaogs** [comment]
☹️

**Comment by urapadmin** [comment]
I think you should go look behind your door (your real one) and look if the Osterhase brought you something instead of falling for my irony. You know quite well that they won't do that. Ha.

**Comment by luizaogs** [comment]
Yes, the shortbread fairy just arrived! You guys are nuts :) Thank you.

**Comment by luizaogs** [comment]
And I hear it was all you! You are now the shortbread fairy.

**Comment by urapadmin** [comment]
be careful with that coke! It is ... erm ... weird. But I'll have one, too.

**Comment by luizaogs** [comment]
I’m intrigued 👀

**Comment by luizaogs** [comment]
The soda isn't super weird! I am enjoying it.
