### ISSUE TITLE
reference navigation not working with identifiers in " "

### ISSUE THREAD

**Issue by luizaogs** [arch-kiosk/arch-kiosk-office#2101]
Testing #1815 

I will open tickets for what look like actual issues rather than just questions, or that ticket will get insane. From my understanding, reference navigation should catch any identifiers that are either between quotation marks or that have a hyphen. Yeah? Well the hyphen seems to be working (though look in #1815 for issues when the identifier has two hyphens), but the quotation marks don't seem to be. Unless I misunderstood how they're supposed to work, which is very possible. 

Example: 108 is a locus in PVD, in unit LA

![IMG_F66F3EDA417A-1](https://user-images.githubusercontent.com/67970402/236692271-9fd9f2af-831d-4275-8169-86a2d7943b5d.jpeg)

I added "108" to a narrative, assuming that I would be able to get to that locus through reference navigation

![IMG_0341](https://user-images.githubusercontent.com/67970402/236692204-46dade5e-c062-4731-88ce-7f4a273675db.PNG)

But I'm told that there are no identifiers in the text, with the yellow message.

**Comment by urapadmin** [comment]
Ja, that is the super smart iPad tricking us. IT has turned double quotes into something else: opening and closing double quotes.
Since that will happen to others as well I will try to change the regular expression to deal with it...

**Comment by urapadmin** [comment]
### recording 14.8.3
- It should work with both straight and curly double quotes
- new: it should also work with straight and curly single quotes (But one cannot mix up single and double quotes, just in case you try)

**Comment by luizaogs** [comment]
Works.
