### ISSUE TITLE
order and significance of menu options in the Hub in kiosk

### ISSUE THREAD

**Issue by lbestock** [arch-kiosk/arch-kiosk-office#2104]
We might think about the order and significance of menu options in the Hub. This arises because Katie assumed at first that "reset workstation" was going to be necessary as part of the ordinary cycle of work, and of course this is not only not the case it is a bit dangerous. The current menu reads:
![image](https://user-images.githubusercontent.com/49291909/236895890-50e2ada5-da11-405f-839d-9509cc7d6985.png)
I would be in favor of putting "prepare" "import" and "synchronize" at the top, still in that order, because those are the things one does daily. "new dock" I would put next - that isn't daily but is regular and harmless. I would put resetting at the bottom.

**Comment by urapadmin** [comment]
I will look into it but it might be less trivial than it seems.

**Comment by urapadmin** [comment]
### Kiosk 1.4.11.0
- I have tried to do that. It was trivial in the end because I already introduced a way to manipulate the order years ago. Just forgot about it.

**Comment by lbestock** [comment]
It takes ten seconds for me to get used to while testing the KAMBE local server, it but that's just fine. I think it's an improvement. I only don't close this because you haven't technically rolled out 1.4.11.0, but I'm in it on KAMBE and it's good.
