### ISSUE TITLE
file import: default file import path is neither taken from the config nor saved

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#2105]
- I am not sure if the last path should have been saved
- but I am sure that the local_file_paths setting under kiosk should do something. It isn't.
- for users it would be best to just show the last input and show the first import path as the default

**Comment by urapadmin** [comment]
Laurel reported that sometimes she does have to type the import path in and sometimes it remembers the former one. Not really consistent.

**Comment by urapadmin** [comment]
the latter I don't entirely understand and I have not done anything about it.
But the selection should now list the configured import paths. On KAMBE and later Kiosks that would only be "z:\file_import"

**Comment by lbestock** [comment]
This is working on the KAMBE local server. All before my first tea gets cold! Local servers are so fast and lovely.

**Comment by urapadmin** [comment]
I also found out under what circumstances the import path (and in fact all other settings) are restored to the last input: It depends on the last input within the same session.
