### ISSUE TITLE
documentation: Doc on KioskBridge needs some editing

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#2108]
That one: https://docs.google.com/document/d/1-sCt3FeH6ehHPFcRs8RBdQP2z3-ZX37N?rtpof=true&authuser=lutz_klein%40brown.edu&usp=drive_fs

**Comment by urapadmin** [comment]
@luizaogs: Unless you have a break from texts, would you please have a look at this one and make it publishable?

**Comment by luizaogs** [comment]
I edited it. I think it's ready.

**Comment by urapadmin** [comment]
Thanks.
