### ISSUE TITLE
documentation: Object Photography

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#2109]
There is a document on this from last year: https://docs.google.com/document/d/1IT4R_zhhcNUGW_je6lBjApG8CSkqC5SASKDVYkgSYvc?authuser=lutz_klein%40brown.edu&usp=drive_fs

@lbestock, Can you make it publishable?

**Comment by lbestock** [comment]
Yes, but only with a schorle 🍷.

**Comment by lbestock** [comment]
Too many schorles. But this was made publishable quite some time ago, and now has been updated to reflect that sequence QR codes might obviate the crazy workflow, depending on your setup. Go ahead and publish it.
