### ISSUE TITLE
update wiki with new projects

### ISSUE THREAD

**Issue by lbestock** [arch-kiosk/arch-kiosk-office#2113]
While the wiki is in some ways deprecated since we moved to GitHub and the much hated Googledrive, it is still the home for some stuff. Like links to the various project online servers, which I do still use. The master installation list seems to me not up to date (is SU PASU?) and KAMBE isn't on there at all and is so real it's actually en route to the field. Not exhaustive; @urapadmin you should check it out.

**Comment by urapadmin** [comment]
it is dead and I pointed you instead to the three tickets that I stuck to the top of the issues list: https://github.com/arch-kiosk/arch-kiosk-office/issues

**Comment by lbestock** [comment]
Yeah but you know the difference between the wiki and these tickets? The wiki had project websites as links. Here, trying to get to PACHA to prepare a workstation while eating your chips, I had to clean my fingers first so I could copy and paste the url instead of doing it all one-handed like a proper American.

**Comment by urapadmin** [comment]
you can, of course, totally help yourself and turn them all into links. That will need both hands, though,

**Comment by lbestock** [comment]
Having lunched like an adult by now I can actually do that.

**Comment by urapadmin** [comment]
ja, that didn't work. The easiest way to do that is to put a https:// in front of the address. Then you don't even need the strange []() notation.
