### ISSUE TITLE
FM search does not find ceramics

### ISSUE THREAD

**Issue by lbestock** [arch-kiosk/arch-kiosk-office#2114]
Is there a reason I have now forgotten why the magnifier find stuff search in FM cannot find sherds? They do have unique IDs, and they can be found in the File Repository by those IDs. But not in FM. I run into this because it is a significant hurdle to using the QR code object photography hack. I am currently in PASU. The QR code can be _generated_ that reads 035-005, for instance, but I cannot search for 035-005 and land on the record that would allow me to create that QR code. I have to go in through ceramics.

**Comment by urapadmin** [comment]
that was by design. There can be so many fragments and they are all more or less named like the collected material, the locus, the unit. So you get a ton of stuff you usually don't want to see. I think it is better to add this ONLY to the search function in the ceramics itself.

**Comment by lbestock** [comment]
Ja in general I can absolutely see why. What is this search function in ceramics itself, however? I miss the magnifying glass in the menu when I go into PASU ceramics.

**Comment by urapadmin** [comment]
### recording 15.1.1
- there is a magnifying glass now in su ceramics
- you can find your sherds there
- if you use the magnifying glass outside of the analysis module you can only find a sherd if you type in more than 6 characters (or so).
- This does not do anything at all if warecode pottery is activated (I am neglecting that part until we need it)

**Comment by lbestock** [comment]
I have already updated the Q&A and the object photography cheat sheet! Before testing that this actually works.

**Comment by luizaogs** [comment]
It works.
