### ISSUE TITLE
file repository feature: bulk tag removal

### ISSUE THREAD

**Issue by lbestock** [arch-kiosk/arch-kiosk-office#2116]
A feature that would be handy in the file repository is the ability to bulk remove tags. One can create or assign tags in bulk right now, and that's very handy for things like collecting images towards filing a report or putting together a ppt. But many of the needs to collect images are ephemeral and not intrinsic to the images themselves; those tags should be removed once the purpose is served. Currently I would have to go into each image and delete the tag.

**Comment by urapadmin** [comment]
no, I don't think that that's the case. The tag bulk processing allows for removing and even for creating new tags. 
I remember that I decided on a slightly unusual approach in the UI to allows for all of it at once so it might need a video tutorial or Q&A paragraph.

**Comment by urapadmin** [comment]
yup. Totally works. You mark all files (the only caveat is that it operates only on the files in the current page, so you might have to go through all pages), got to "tags only found on some .. "  and select what you want to do with the tag and the marked files.

**Comment by lbestock** [comment]
Aha. Totally works. Since I was poking at it precisely in preparation for making a video tutorial...
