### ISSUE TITLE
Test: Reference Navigation in PACHA, PASU and USTP

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#2118]
Since they all have different kinds of identifiers, please check if reference navigation works in these projects.

**Comment by luizaogs** [comment]
Uh well, PACHA works theoretically. Only their identifiers are ridiculous and no one refers to anything by their full identifiers in narratives, it seems, so it isn't actually catching anything -- it does when I type in the full identifier myself: 

For instance, in this narrative they refer to a locus as Locus 9200 so it doesn't work: 
<img width="1019" alt="Screenshot 2023-05-13 at 5 04 00 PM" src="https://github.com/arch-kiosk/arch-kiosk-office/assets/67970402/c8b400ff-aeb5-43f9-a61c-2f451a337a82">

<img width="1024" alt="Screenshot 2023-05-13 at 5 04 07 PM" src="https://github.com/arch-kiosk/arch-kiosk-office/assets/67970402/db61788b-8e23-4909-9935-27ec4eda5506">

Once I type in the full ridiculous identifier (PLMS0004-U008-9200), it works: 

<img width="1018" alt="Screenshot 2023-05-13 at 5 04 55 PM" src="https://github.com/arch-kiosk/arch-kiosk-office/assets/67970402/19e98214-2667-4a76-b709-0c978846cfb1">

<img width="1020" alt="Screenshot 2023-05-13 at 5 05 04 PM" src="https://github.com/arch-kiosk/arch-kiosk-office/assets/67970402/a6960ce5-c62d-460a-9904-47dce0272568">

**Comment by luizaogs** [comment]
The above PACHA situation is presumably not a Lutz problem, but I thought I would let you know. I will test PASU and USTP once they get updated.

**Comment by lbestock** [comment]
Funny, we were recalling today the meeting in which we tried to suggest a different identification scheme…

**Comment by urapadmin** [comment]
ja, that's their problem, not mine. We pointed the several disadvantages out of such identifiers, it wasn't heard.

**Comment by luizaogs** [comment]
Should this also catch locus numbers that are NOT in quotation marks? USTP for instance does not use hyphens and they mention loci in narratives but in parenthesis rather than quotation marks (in the following narrative for instance, 1941 etc.):

<img width="1017" alt="Screenshot 2023-05-14 at 4 52 29 PM" src="https://github.com/arch-kiosk/arch-kiosk-office/assets/67970402/7b01d995-6204-41c5-ad7b-b6a5df3d5508">

**Comment by urapadmin** [comment]
it could, that's a good idea. I will add a regular expression that covers opening and closing brackets.

**Comment by urapadmin** [comment]
what is up with that double ^ in that text? Is there something missing?

**Comment by luizaogs** [comment]
I didn't even see the ^^. I have no idea.

**Comment by urapadmin** [comment]
> I didn't even see the ^^. I have no idea.

I can't find the mustard in the refrigerator but semantic characters stick out to me like sore thumbs.

**Comment by luizaogs** [comment]
Last thing here is that PASU uses both full identifiers in narratives and sometimes just uses half of the identifier (the unique number part). Not sure if there is much to do about it, or even if doing anything about it is needed, but noting it: 

<img width="1021" alt="Screenshot 2023-05-14 at 5 13 37 PM" src="https://github.com/arch-kiosk/arch-kiosk-office/assets/67970402/c34987e6-3412-4a80-9ccd-7a8ea4ae9f65">

**Comment by urapadmin** [comment]
same issue as with PACHA. the only remedy might be #2119

**Comment by urapadmin** [comment]
I will add ^ ^, too and then we can close this. #2119 is its own ticket.

**Comment by urapadmin** [comment]
### kiosk 14.9.1
- identifiers enclosed in ^ characters should work

**Comment by luizaogs** [comment]
Hm wait, did you mean ^^ or ()? I had meant () to accommodate USTP, since they seem to frequently do (locus).

**Comment by urapadmin** [comment]
oh, sorry, I did that, too. No, I mean both. Brackets and the funny things that seem to be used for loci sometimes.

**Comment by lbestock** [comment]
This goes back to USTP having a convention on paper (Abydos uses it, too) of marking loci in descriptions with deltas. So it was a single carrot ^1066, for what was really wanted which was Δ1066. Can it trigger navigation if it is just a special character before a number, not an enclosing device?

**Comment by urapadmin** [comment]
enclosing is less ambiguous, but I can try to add it as a 🥕 that starts an identifier that ends with the next white space.

**Comment by urapadmin** [comment]
### kiosk 14.9.1
- identifiers started by a ^ characters and end with the next white space should work
- identifiers enclosed in round brackets are identified, too

**Comment by luizaogs** [comment]
Yep.
