### ISSUE TITLE
FM Search and Reference Navigation: What about alternative identifiers

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#2119]
I think at least collected material can have an alternative identifier.
We could also invent one for loci to give projects that have decided on clunky identifiers the opportunity to do something about it.
It would also solve the old question whether one wants "nick-names" for loci through the backdoor.

**Comment by lbestock** [comment]
Could we make the locus alternative identifier configurable so that it takes an insane identifier and makes it sane by lopping off the crazy parts, creating it automatically? Just thinking...

The original "nicknames" conversation was about units because KHPP named every unit after a Sesame Street character since their grid-square identifiers were hard to remember. Units are less relevant in navigation, but still very relevant in search, particularly once one has a ton of them.

**Comment by urapadmin** [comment]
> Could we make the locus alternative identifier configurable so that it takes an insane identifier and makes it sane by lopping off the crazy parts, creating it automatically? Just thinking...

vetoed. You make an algorithm create something insane and then have another algorithm to cut it down? Jesus. That is too PACHA-centered. I am thinking of this as a more general field that can be used for all kinds of things. 

> The original "nicknames" conversation was about units because KHPP named every unit after a Sesame Street character since their grid-square identifiers were hard to remember. Units are less relevant in navigation, but still very relevant in search, particularly once one has a ton of them.

doesn't matter to me. We can give units and loci an alternative identifier and they can use it for whatever they want.

**Comment by lbestock** [comment]
> > Could we make the locus alternative identifier configurable so that it takes an insane identifier and makes it sane by lopping off the crazy parts, creating it automatically? Just thinking...
> 
> vetoed. You make an algorithm create something insane and then have another algorithm to cut it down? Jesus. That is too PACHA-centered. I am thinking of this as a more general field that can be used for all kinds of things.

OK that is a good point. I will not seek a 2/3 majority to override your veto.

**Comment by urapadmin** [comment]
okay: Units already have an alternative id that becomes visible when setting the config key "label_legacy_unit_id". We'll use that.
- that one should also be visible (but not modifiable) on the first tab of excavating  (same with features and survey units).
- Loci now have one, too. Controlled the same way with the key "label_locus_alternate_id".
- collected materials already had one controlled by the key "label_cm_alternative_number"

**Comment by luizaogs** [comment]
The key "label_legacy_unit_id" is not synching, for some reason. Neither the fact that I had turned it on nor the ones I had entered are back in my new download.

The locus and CM keys synchronized just fine.

**Comment by luizaogs** [comment]
Oh wait, no, super weird. The fact that I had turned the label legacy unit key on did NOT synchronize, but apparently the individual nicknames I had entered did? So if you download the logsmac workstation right now you should not find the legacy unit label on any unit pages. BUT if you then turn it on in config and label it "nickname" (don't know if that matters or not) you should see the labels I had entered: "meow" in unit LA, "Sleepy" in survey unit 02, and "bloop" in feature F041 (yes I'm very creative at 11pm).

**Comment by luizaogs** [comment]
Reference navigation is also not working with these yet. I tried putting the nicknames in " ", ( ), and with the ^ in front and nothing.

**Comment by luizaogs** [comment]
The rest is ok.

**Comment by urapadmin** [comment]
> Oh wait, no, super weird. The fact that I had turned the label legacy unit key on did NOT synchronize, but apparently the individual nicknames I had entered did? So if you download the logsmac workstation right now you should not find the legacy unit label on any unit pages. BUT if you then turn it on in config and label it "nickname" (don't know if that matters or not) you should see the labels I had entered: "meow" in unit LA, "Sleepy" in survey unit 02, and "bloop" in feature F041 (yes I'm very creative at 11pm).

If the config key is set to nothing, this is what would happen (yes, the data would normally synchronize and it would be there, just not displayed)
What is hard to take as a fact here is that a config key does not sync all of a sudden. I looked at the configuration key, it is set to synchronize normally. Can you try that again? Does that key really not synchronize?

**Comment by luizaogs** [comment]
I mean, I'll try it again. I just find it somewhat hard to believe that I turned it on and labeled it "nickname", added the nickname to all those units, and then turned it off before uploading.  But let's see...

**Comment by luizaogs** [comment]
Ok well, now it's there. I swear I didn't turn it off last night (why would I have turned one off and not the others?) but seems like it's fine.

**Comment by urapadmin** [comment]
> Reference navigation is also not working with these yet. I tried putting the nicknames in " ", ( ), and with the ^ in front and nothing.

That one I found: I forgot to patch the config key "identifier_tables_and_fields" which determines which tables and fields have identifiers.

**Comment by urapadmin** [comment]
### recording 14.10.1
- reference navigation should work with alternate identifiers
- the other thing with the not syncing config key we can only try once more with the new version to see if it reappears.

**Comment by luizaogs** [comment]
The synching thing happened again. My iPad's database has a new label for that key: alternative id. 

![IMG_0345](https://github.com/arch-kiosk/arch-kiosk-office/assets/67970402/e50375dc-8212-4d13-8170-69cc10317299)

I uploaded and imported and synchronized, and then just downloaded the same workstation on my Mac so I could compare the two. In this download that key still has the old "nickname" label, which indicates that something did not synchronize. 

<img width="1026" alt="Screenshot 2023-05-19 at 4 47 30 PM" src="https://github.com/arch-kiosk/arch-kiosk-office/assets/67970402/120ddbc8-f54a-4df4-a979-061cb7b3347e">

**Comment by luizaogs** [comment]
The reference navigation works now, however.

**Comment by urapadmin** [comment]
Let's make this weird thing its own key: #2132 

And if that's the only thing that was missing for the original topic you may close this here.
