### ISSUE TITLE
USTP deposit/architecture details

### ISSUE THREAD

**Issue by luizaogs** [arch-kiosk/arch-kiosk-office#2120]
I'm checking if USTP deposit and architecture details are accessible, as requested in #1773 and um ... it looks like there are no deposit or architecture details recorded? Granted I haven't looked at all contexts but I've looked at quite a few. The form is accessible but there is nothing recorded -- not sure if that's just because no details were recorded in the first place, but I let you know.

**Comment by urapadmin** [comment]
yes, that is correct in USTP. That's exactly why I asked you guys to test this explicitly because last summer we screwed up and USTP did not have access to those detail forms (they also did not complain).

**Comment by luizaogs** [comment]
I checked that they were accessible for all three projects, and they are.
