### ISSUE TITLE
PACHA export error

### ISSUE THREAD

**Issue by luizaogs** [arch-kiosk/arch-kiosk-office#2121]
Just got this when preparing a PACHA workstation. Preparing a different workstation right after worked, so not sure if it is significant: 

<img width="1512" alt="Screenshot 2023-05-14 at 5 03 02 PM" src="https://github.com/arch-kiosk/arch-kiosk-office/assets/67970402/cca6e781-102e-4b16-a73c-47b17e7f6c57">

**Comment by urapadmin** [comment]
I would call that a hiccup unless it keeps occurring

**Comment by urapadmin** [comment]
hiccup
