### ISSUE TITLE
terminology in FM navigation does not reflect project terminology

### ISSUE THREAD

**Issue by lbestock** [arch-kiosk/arch-kiosk-office#2123]
Poking around in PASU, where Anna's meticulous records make navigation a breeze (not for the legacy data, though). 
However, PASU uses Strat. Units, not loci, and the navigation list I get on stepping on footsteps leads me to things called loci. Let's make that say Strat. Units. (Also a problem for KAMBE, of course. Not sure if it's worth getting in and fixing that remotely?)

**Comment by urapadmin** [comment]
no, KAMBE is out. And I cannot change their version since at this point it would need a new Kiosk version as well.

**Comment by urapadmin** [comment]
Honestly, we should change the terminology in PVD to something different from URAP so that we can spot such things during test.

**Comment by urapadmin** [comment]
a better description of where you see that would help. 
If this is about the list in either layout navigation or recently viewed then all I can see is that the term comes from what is set on unit level. Is it possible that in PASU the loci are actually set to locus?

**Comment by urapadmin** [comment]
no, it looks okay in PASU. And I can't see what you mean. Please give me a screenshot.

**Comment by lbestock** [comment]
Navigation in the latest development, as reached by the footsteps that read a narrative to find the identifiers:
![image](https://github.com/arch-kiosk/arch-kiosk-office/assets/49291909/daf996be-cff9-4d4c-85a4-a653d66680b5)

**Comment by urapadmin** [comment]
we call that reference navigation

**Comment by lbestock** [comment]
Oops. A terminology confusion when reporting on terminology confusion.

**Comment by urapadmin** [comment]
here it is strangely difficult to get the actual name of the archaeological element in. for Loci that is a term defined on the unit. That is why I have fallen back on using the record type. So what you see there are record type names. And those can be configured with the key "record_type_names". So if you enter locus=Strat.Unit. you will get what you want there. It will also need unit=area and whatever else we have in PASU.

**Comment by lbestock** [comment]
Is it possible we do not have a "to do" sheet for me for concordance meetings and things to remember to do while configuring a kiosk? Sheesh. That needs to happen. I don't even know what label to put on this to make sure I add it to that apparently future document, though just-config might do it.

**Comment by urapadmin** [comment]
make yourself a ticket. Somewhere else.

**Comment by lbestock** [comment]
PASU has been properly configured now for this.
