### ISSUE TITLE
PASU configuration 2023

### ISSUE THREAD

**Issue by lbestock** [arch-kiosk/arch-kiosk-office#2124]
Discussion with Anna about numbers leads to a need to check the configuration. New Strat. Units created this year will be prefixed SU23. HOWEVER it is vital that the numbers not start over again at 001. So next would be SU23-H028, for instance. And it needs to be possible to free input SU23-H027, since SU22-H027 already exists, must continue to exist as it might have CM associated with it, but will be dug this season as SU23-H027.

**Comment by urapadmin** [comment]
@lbestock Do you intend to do anything here before the 2023 season?

**Comment by lbestock** [comment]
Yes! If you release 15.1 to me for videoing then I will do the configuration as well today. Please make a backup. I will want to test it not only through creating records but through synchronizing them.

**Comment by lbestock** [comment]
The numbering issue presented by @aes1884 is taken care of. Next auto-generated number in H is SU23-H028. If you make a new area, it starts as SU23-X000. Using temporary free-input in H SU23-H027 can be created anew OR SU22-H027 can be renamed SU23-H027 (there are not any collected materials associated with it but there is a photo and there are relations). The latter needs logging in as admin admin.
