### ISSUE TITLE
new narrative view: switching between SVG and regular photo doesn't work

### ISSUE THREAD

**Issue by luizaogs** [arch-kiosk/arch-kiosk-office#2129]
I'm on my iPad (16.4.1, FM Go 2023), will test my Mac next 

I'm in CA because it has two SVGs. I scroll to the second narrative (because I had already messed with the first). Click on the calendar button. Go to the trowel tab, since there are no images associated with this specific narrative yet. Click on the SVG on the top -- it shows up fine. Click on the SVG below that, also shows up fine. Click on the image below that SVG of Laurel playing with a drone, also shows up. Hm. It hadn't before so let me try something else. 

Click on the first SVG, shows up. Link that SVG using the chain button. The SVG ceases to show up BUT if I click on it again it shows up then. Click on the second SVG, that shows up. Then I click on the picture of Laurel playing with the drone -- and that does not show up any longer. Aha, so that was it. Going back and forth between SVGs and regular photos works until I link an SVG to the narrative, then it no longer works. 

If I link that image of Laurel ... it shows up in the chain tab, and then going between the SVG and the image works -- both in the chain tab and in the trowel tab. 

I'm going to try this again with narrative 3, just for funsies:

Go to the third narrative in CA, the Formaggio deposit. Click on trowel tab. Click on the SVG on the top - it shows up normally, and it's the spider with the fedora. Click on the SVG below it - also shows up, hatless spider. Click on photo of Laurel with drone, shows up. Link first SVG using chain button. Doesn't show up at first, shows up if I click on the green thumbnail once more. Clicking on the SVG below it (hatless spider) works. Clicking on photo of Laurel with drone again does not work. Link Laurel's photo. Still doesn't show up, but if I go to the chain tab and click on it there it does. And then when I get back to the trowel tab I can move between images normally.

**Comment by luizaogs** [comment]
So yes, I guess there is an issue with going between SVGs and regular images but it seems minor. The above description might be slightly convoluted, and if it is let me know.

**Comment by luizaogs** [comment]
Mac 13.3.1

Same exact thing happens on my Mac.

**Comment by urapadmin** [comment]
### recording 14.10
- wow, FileMaker. I hacked this. A solution that needed  a big Gin-Tonic 🥃 and a variable called "$$stopdoingthis". That's like programming a computer in the early 80s!
- now this might have side effects. Like: Deleting an association deletes the wrong one or none at all or who knows what will happen ...

**Comment by urapadmin** [comment]
🥃 🥃

**Comment by luizaogs** [comment]
You won't like this but I'm still having the same issue...

**Comment by urapadmin** [comment]
you are right, I don't like that. Needs more Gin, it seems.

**Comment by urapadmin** [comment]
you have on your Mac, as well?

**Comment by luizaogs** [comment]
I didn't check my Mac. I'll do that now.

**Comment by urapadmin** [comment]
### recording 14.10.1
- next try

**Comment by luizaogs** [comment]
Worked.
