### ISSUE TITLE
going into narratives tab automatically activates paper clip

### ISSUE THREAD

**Issue by luizaogs** [arch-kiosk/arch-kiosk-office#2130]
14.9

Going into the narratives tab in different units now automatically activates the paper clip, and I assume that's not what you want? I just noticed it on my Mac but I am fairly certain it was also happening on my iPad. Let me check ... ha, funny. No, weirdly just on my Mac?

Ah. It might be rather that once the paper clip is activated in a unit, if I go to another unit it is activated there also. If I deactivate it and go to another unit, then it's not automatically showing up there.

**Comment by urapadmin** [comment]
activating / deactivating the paper clip is not unit bound. So If you activate it in one unit it is still activated in another unit. If you deactivate it in another unit it will be also deactivated in the original unit.
If that is what you are seeing, that's by design.

**Comment by luizaogs** [comment]
Ok, that's fine then.
