### ISSUE TITLE
config key unit_legacy_id does not sync properly

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#2132]
The synching thing happened again. My iPad's database has a new label for that key: alternative id. 

![IMG_0345](https://github.com/arch-kiosk/arch-kiosk-office/assets/67970402/e50375dc-8212-4d13-8170-69cc10317299)

I uploaded and imported and synchronized, and then just downloaded the same workstation on my Mac so I could compare the two. In this download that key still has the old "nickname" label, which indicates that something did not synchronize. 

<img width="1026" alt="Screenshot 2023-05-19 at 4 47 30 PM" src="https://github.com/arch-kiosk/arch-kiosk-office/assets/67970402/120ddbc8-f54a-4df4-a979-061cb7b3347e">

_Originally posted by @luizaogs in https://github.com/arch-kiosk/arch-kiosk-office/issues/2119#issuecomment-1555290432_

**Comment by urapadmin** [comment]
I cannot reproduce this. I created my dock, got the patch, changed the legacy_unit_id term, uploaded, imported, synchronized, prepared my workstation again, downloaded and my change had properly synchronized and correctly there in my workstation.

Now I wonder if it could have something to do with Chicago. Did you get a patch and changed the config key in the same session? Or did you first upload the patch, then prepared again and it was only then that you changed the key?

**Comment by urapadmin** [comment]
hm. Not sure if that has anything to do with it, but one of logs synchronization runs showed a deletion in constants:
> 6008/6344 5:35 pm "logsmac"."logsmac_constants": 1 deleted lines.

**Comment by luizaogs** [comment]
> I cannot reproduce this. I created my dock, got the patch, changed the legacy_unit_id term, uploaded, imported, synchronized, prepared my workstation again, downloaded and my change had properly synchronized and correctly there in my workstation.
> 
> Now I wonder if it could have something to do with Chicago. Did you get a patch and changed the config key in the same session? Or did you first upload the patch, then prepared again and it was only then that you changed the key?

Hm. This might be it. I did it with the patch this time -- not sure if I also did it at the same time I was uploading the patch last night, I can't remember. But the second time that it worked there was no longer a patch to upload.

**Comment by luizaogs** [comment]
Or I think I did it with the patch. I'm actually not sure -- too many uploads and downloads in quick succession.

**Comment by urapadmin** [comment]
So may I ask you to do it again? This time please apply your change to the legacy thingy in the same session with the patch. And then when synchronization is done, just stop and tell me the exact date and time, so that I can look up what happened in the logs. And then you can proceed and see if your change will actually be there. 
- If my theory is correct, that should be the case.
- now in that new download change the legacy thingy again to something else and upload, import etc ...
- tell me again what the time after the synchronization was.
- see if the change is visible in your next download. If my theory is correct, it won't.

**Comment by urapadmin** [comment]
I have reset your recording group (that is an option on docks that you have never used, for sure. That has the side effect that the patch will get reapplied. )

**Comment by luizaogs** [comment]
**First synchronization, changing legacy key with patch:** 
legacy key changed from "my unit id" to "nickname"
time of synchronization: 11:23pm May 19 (Chicago time) / 12:23am May 20 (Providence time)
you are correct, the change from "my unit id" to "nickname" was applied

**Second synchronization, changing legacy key without the patch:**
legacy key changed from "nickname" to "alternative id"
time of synchronization: 11:29pm May 19 (Chicago time) / 12:29am May 20 (Providence time)
ha well, the change to "alternative id" was also applied, so you seem to be half right

**Comment by urapadmin** [comment]
Ja, then this time it simply worked as it should. Then I am a bit at a loss here. Let's keep it in mind but I can't see that it's a general issue. Postponed.

**Comment by luizaogs** [comment]
And this? Hasn't come up again...

**Comment by urapadmin** [comment]
this one scares me more. I take synchronization issues very seriously. But I am not any wiser on this particular issue.
So yes, you may close it and we wait for something similar to happen. 
I have tagged it accordingly.
