### ISSUE TITLE
FM narrative/image link: request to show date

### ISSUE THREAD

**Issue by lbestock** [arch-kiosk/arch-kiosk-office#2139]
I have just been testing recording 15.1 on my iPad for the new QR code photo stuff.
For fun I have gone back to narrative image linking to think about a video.
One surprise that I don't remember: I can't see the date of creation of the narrative when I have it open in the pop up view. I thought I had been able to see date and person still, but there I do not trust my memory. I would like to be able to see date of creation.

**Comment by urapadmin** [comment]
### recording 15.1.1
- added date and excavator

**Comment by lbestock** [comment]
@urapadmin can you please roll out 15.1 to PASU? I want to record a tiny video about the narrative/image linking and PASU would be by far the best for it, but I want it to look as it will look for them.
