### ISSUE TITLE
KioskBridge crashes when hitting the upload button

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#2140]
lwarden reported from the field:
> This morning, I went to upload and sync the database and am struggling with Kiosk Bridge. The copy on our Registrar's iPad - the oldest device, admitedly (but running iOS 16.4.1) - keeps closing whenever I hit the "upload to kiosk" button. I tried turning the iPad on and off; plugging it into the wall; restarting all aps. All to no avail.

**Comment by urapadmin** [comment]
@arch-kiosk/test This is not something we have seen in tests, to my knowledge. I have prepared a new KioskBridge version that will allow me to collect a log from the field and it also has one fix that might have affected the upload (although I doubt it).
We have to wait what comes back from the field. Unless somebody can reproduce this with an older iPad?

**Comment by urapadmin** [comment]
### KioskBridge 0.2.2 (3)
This needs intensive testing again. iOS development is hell for me and I might have screwed things up that worked so far.

**Comment by luizaogs** [comment]
I have never seen this, but will test Bridge now and see if anything appears.

**Comment by luizaogs** [comment]
Kidding, I can't test this -- MCP seems to be down.

**Comment by urapadmin** [comment]
indeed. Fixed.

**Comment by luizaogs** [comment]
Bridge is working for me, as are the new features mentioned in #1773

**Comment by urapadmin** [comment]
The new Build 3 works for lwarden in the field, it appears. So I close this for now
