### ISSUE TITLE
registration - collected material: sort and filter by material

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#2141]
Not something we can do.
I will add a new filter and in the list the material type will be used (for small finds, too).

**Comment by urapadmin** [comment]
### recording 14.6.2 revision 1
- this is the version we would roll out only to khpp while they are in the field (we are already ahead of them and incompatible)
- it has a little gear button next to the type column that lets you select what value(s) appear in the column and hence what is sorted
- the filter popover has a material field 

@lbestock: This can be tested only locally on khpp using http://192.168.1.196

**Comment by urapadmin** [comment]
### recording 15.1.1
- same as 14.6.2 (see above) but for the regular line

**Comment by luizaogs** [comment]
I think I'm looking in the wrong place? I don't see a gear button anywhere.

This is what it looks like in the unit collected material list, where filtering by material works (is this what you are referring to? I thought that existed already): 

<img width="1029" alt="Screenshot 2023-05-30 at 8 15 25 PM" src="https://github.com/arch-kiosk/arch-kiosk-office/assets/67970402/b07512d0-2df0-4439-a09b-d261e7712d0d">

And this is what I see in the collected material list on locus level, where the filter only allows me to filter by type still: 

<img width="1024" alt="Screenshot 2023-05-30 at 8 16 41 PM" src="https://github.com/arch-kiosk/arch-kiosk-office/assets/67970402/6b1e00d7-d4d8-4488-992f-2e355e13df44">

**Comment by urapadmin** [comment]
I am sorry, the description kind a sucked for anybody outside of this house. This is about collected material registration

**Comment by urapadmin** [comment]
@lbestock this cannot be closed until it is tested for khpp here, locally

**Comment by lbestock** [comment]
This works on the local KHPP. I was very far from comprehensive, but I did make a bunch of types of records and synchronized them and I have not found any bugs introduced by this change.

**Comment by urapadmin** [comment]
reopened because of #2164

**Comment by urapadmin** [comment]
### recording 15.1.6
- This should still work as expected. It won't influence other parts of the recording app anymore (see #2164)
- also: changing the column value of the type column did not change the heading of that column. It should reflect the selected value.
