### ISSUE TITLE
Weird synchronization log

### ISSUE THREAD

**Issue by luizaogs** [arch-kiosk/arch-kiosk-office#2145]
Synchronization seems to have worked but I got an error I do not understand, so letting you know:

![IMG_0346](https://github.com/arch-kiosk/arch-kiosk-office/assets/67970402/c8a01baa-21cb-4890-ae54-e2b87157e83b)

**Comment by urapadmin** [comment]
the "unexpected transmission error" thingies are usually hiccups. 
If you go to the hub and then back in here (which you won't be able to do anymore by now), you'd be fine.

**Comment by luizaogs** [comment]
Ok, then never mind. (Yes, going back into synchronization doesn’t show the error any longer.)
