### ISSUE TITLE
registration: collected material filter - show that it is active

### ISSUE THREAD

**Issue by luizaogs** [arch-kiosk/arch-kiosk-office#2149]
When testing #2141 I kept forgetting that the filter was active and thus confused myself several times about why so few CM were showing up in the list. In other layouts (e.g., locus list, cm unit list, etc.) you indicate that the filter is active by making the icon yellow/orange. Is it possible to do that in the registration filter, too? I think that would be helpful.

OH wait, the registration filter apparently does become orange when I'm filtering by trench. But it does not when filtering by material, so I guess just add that if possible.

**Comment by urapadmin** [comment]
another issue connected to this is that the filters stay applied even after one closes the database. I think that is not a good idea. So I'll reset them when the database opens. (This will not be the case in the revision for khpp, though)

**Comment by urapadmin** [comment]
### recording 15.1.2
- filter button should be orange when filtering by material
- filters should be reset when restarting the database

**Comment by luizaogs** [comment]
Since Laurel didn't mention this for khpp, I assume it's fine there.

**Comment by lbestock** [comment]
To confirm, the filter is highlit in khpp for material filters.
