### ISSUE TITLE
🎬  Video tutorial (series?) on Registration

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#2151]
@lbestock: Do you feel up to do this, perhaps with 2 or three episodes (because of registration codes and how registration codes can be configured to be there after creating a new collected material ...)

_Originally posted by @urapadmin in https://github.com/arch-kiosk/arch-kiosk-office/discussions/2081#discussioncomment-6053203_

**Comment by lbestock** [comment]
I am not just up for it, I'm excited for it. But we need to talk it through together so I don't miss anything. I also think it helps me be at least a bit more succinct if we have talked through one before I make it.

**Comment by urapadmin** [comment]
did we do that?

**Comment by lbestock** [comment]
Oh yes. In three parts, so not so sure about the succinct...
