### ISSUE TITLE
registration: clear "from date"

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#2152]
It was impossible to clear the from date in iPads.

Although this UI is easier to use on PCs and Macs, this at least can be added.

**Comment by urapadmin** [comment]
### recording 15.1.4
- so I did

**Comment by lbestock** [comment]
You're quicker than a mosquito at dusk.

**Comment by urapadmin** [comment]
### khpp revision 1.1
- rolled out to the local 196 ip address

**Comment by urapadmin** [comment]
yes, that is the horror of a branch.

**Comment by lbestock** [comment]
The local KHPP server does not seem to be up. I'll test this after what promises to be a lovely meeting at Classical High School.

**Comment by urapadmin** [comment]
I tried to help the electricity bill and climate. It is running again.

**Comment by lbestock** [comment]
Works. And now you are saving the planet by drinking boxed wine.
