### ISSUE TITLE
director's view: collected materials widget is termed "bulk" 

### ISSUE THREAD

**Issue by lbestock** [arch-kiosk/arch-kiosk-office#2153]
Legacy of ways past:
The CM widget in Director's View is labeled bulk, but it gives results for all types of collected materials. It should be changed to "collected materials".

![image](https://github.com/arch-kiosk/arch-kiosk-office/assets/49291909/02ef1e8b-b7b4-4441-be86-9d2342cf7915)

**Comment by urapadmin** [comment]
that might be just configuration

**Comment by lbestock** [comment]
Then let's make sure PASU is configured properly before they head out.

**Comment by luizaogs** [comment]
I assume this has to be done locally on PASU?

**Comment by urapadmin** [comment]
yup.

**Comment by urapadmin** [comment]
waiting for #2706

**Comment by lbestock** [comment]
This has been tested locally and works, now we just have to remember to do it in the final PASU configuration. But that's already in that ticket, so I close this.
