### ISSUE TITLE
reporting: set variables depending on the selected base query

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#2154]
The idea here is that the sql statements can use something like a second level variable that itself consists of variable entries.
This would be very useful to have a where statement like "where {{#where_statemten}}"
And then the variable "#where_statement" is defined by the base_query section using the required variables like this:
#where_statement = "created between {{#from_date}} and {{#to_date}}"

That allows for totally different sql statements depending on the selected base query

**Comment by urapadmin** [comment]
see also #2155

**Comment by urapadmin** [comment]
### Kiosk 1.5.2
That's done. Those are not variables. I call them template strings. They get parsed before the variables, which means that they themselves can include variables.

Used for the PASU context/find report

**Comment by luizaogs** [comment]
Ha ok, I ran the report but when I tried to download it to see if the variable thing had worked I was told that I don't have enough privileges to download from the file manager.

**Comment by luizaogs** [comment]
I guess I should also check. These are the template strings? 

<img width="698" alt="Screenshot 2023-06-05 at 12 12 10 PM" src="https://github.com/arch-kiosk/arch-kiosk-office/assets/67970402/e4278cf4-3f2f-45d4-9b60-4e9ce997c120">

**Comment by urapadmin** [comment]
sorry, apart from testing if the report works, there is very little you can do. And if it works that proves that the new template strings work. I give you download permission.

**Comment by urapadmin** [comment]
done

**Comment by luizaogs** [comment]
Yes, it works.
