### ISSUE TITLE
reporting: try to support timestamp variables a bit better

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#2155]
- explain what date format is expected
- allow for localized timestamps
- allow for latin dates

**Comment by urapadmin** [comment]
German, US and Latin dates work, I save myself the user hint because this UI is going to be replaced by the new UI Technology I am developing for the query module soon.

**Comment by urapadmin** [comment]
### kiosk 1.5.2
- You should be able to type in German, US. latin and ISO8601 dates (YYYY-MM-DD) in the from and to fields.

**Comment by luizaogs** [comment]
YYYY-MM-DD worked. I tried US Latin which didn't work, but I think I'm using the wrong format. What would be the correct US Latin and German formats?

**Comment by urapadmin** [comment]
dd.LL.yyyy with LL being a month as Latin number Is the Latin, And dd.mm.yyyy is the German

**Comment by urapadmin** [comment]
US mm/dd/yyyy should work, too, I guess.

**Comment by urapadmin** [comment]
I suppose that's what I meant: US, Latin, ... There was a typo
