### ISSUE TITLE
PASU default registration codes?

### ISSUE THREAD

**Issue by luizaogs** [arch-kiosk/arch-kiosk-office#2165]
Still touching everything in PASU. I'm creating new bulk, small finds, and samples to make sure everything is ok. And I noticed that there are default registration codes popping up in the CM layout, but they do not seem to correspond to the check boxes? Is that by design? Not sure if I'm missing something here. 

New bulk gets BR but nothing gets checked in the checkboxes: 

![IMG_0348](https://github.com/arch-kiosk/arch-kiosk-office/assets/67970402/a45bba57-b506-42cf-bfc2-d042b2b303c2)

New small finds get BRP, and in that case "to be photographed" is automatically checked which makes me think the other ones are missing this automatic checking.

New sample gets BRL!, but again with nothing being automatically checked.

**Comment by lbestock** [comment]
Well then that is because all the new changes in registration have not made their way into the PASU configuration! Probably not a bug but I will take a look and add it to my configuration plans.

**Comment by lbestock** [comment]
OK I have mostly taken care of this, in part by changing St to T. 
@urapadmin there is work for you here: you should apply a general change to make the old Sts into Ts.

**Comment by urapadmin** [comment]
I did this on PASU

**Comment by luizaogs** [comment]
This issue here is solved. Still something weird happening with the St and T, though, and I'll mention that in #2167 since this one here was about the automatic codes.
