### ISSUE TITLE
PASU tag ... potatoes? 

### ISSUE THREAD

**Issue by luizaogs** [arch-kiosk/arch-kiosk-office#2166]
Guys. PASU has a potatoes tag. I am assuming this was me, because it sounds like me, but I assume it should um not be there? Can I delete it? Eesh.

**Comment by lbestock** [comment]
This is hilarious. It could equally well be one of us. I mean, Germans are known to appreciate potatoes (which cannot be had at this point in the spring). I would say that after you do a tag analysis and make sure it wasn't actually applied to anything that yes, you can delete that sucker.

**Comment by luizaogs** [comment]
"Potatoes are great" is the description. It is so funny.

**Comment by lbestock** [comment]
Potatoes ARE great.

**Comment by luizaogs** [comment]
They are. You're welcome, PASU.

**Comment by luizaogs** [comment]
Hm. Potatoes was used to tag something but I cannot figure out what it was because it was apparently not a Strat.Unit. But as a result I can't delete it.

**Comment by lbestock** [comment]
Ah. I think it was not - if you mean you can input it in tag analysis, but then you don't see any potatoes.
Any tag that exists, whether or not it has actually been applied, shows up in the list of tags to choose for analysis. So I think this can be safely deleted.

**Comment by urapadmin** [comment]
that tag could not be deleted because it tagged a locus that got deleted itself. That's of course a bug but for PASU I have removed this manually. The bug will move to a different ticket.

**Comment by urapadmin** [comment]
it was hard to delete the 🥔

**Comment by luizaogs** [comment]
Yours truly, always causing problems.

**Comment by lbestock** [comment]
You should, you know, eat some potatoes as a response. Now it's in a video tutorial!

**Comment by urapadmin** [comment]
please test that this is solved :o)

**Comment by lbestock** [comment]
Totally solved. At least, there are no potatoes lurking in PASU, but I'm not sure if Luiza has eaten her spuds yet.

**Comment by luizaogs** [comment]
Alas, I have not.
