### ISSUE TITLE
🎬 tutorial: Install and run reports 🎬 

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#2168]
- done
@lbestock  but this one really also needs to be in the Q&A

**Comment by urapadmin** [comment]
oops. Laurel might not have been done.

**Comment by lbestock** [comment]
Not done. Must watch you...

**Comment by lbestock** [comment]
Have watched you and it's now in the updated Q&A. Which we need to update on the website!
