### ISSUE TITLE
USTP patch

### ISSUE THREAD

**Issue by luizaogs** [arch-kiosk/arch-kiosk-office#2173]
Um ... can you repatch USTP, if that latest patch was important? I am having issues with timezones because I am not an admin in Kiosk and can't change the workstation timezones. Long story short, I won't be able to upload this patch because I had to re-prepare the workstation. Sorry!

**Comment by urapadmin** [comment]
yes, I can, no problem, since there will be another update anyhow

**Comment by urapadmin** [comment]
this should be done by now.
