### ISSUE TITLE
inventory: Kitchen

### ISSUE THREAD

**Issue by luizaogs** [arch-kiosk/arch-kiosk-office#2178]
Found this when testing USTP but just confirmed that it's also the case in PVD, so not sure if it's just the case in all projects. 

When first entering the inventory module, I get Kitchen in the category field. This occurs whether or not it is actually a category in the dropdown (it was not, for PVD or USTP). If I press the minus it disappears.

**Comment by urapadmin** [comment]
### recording 15.1.7
- no kitchen anymore
