### ISSUE TITLE
reporting: should new reports override past ones?

### ISSUE THREAD

**Issue by luizaogs** [arch-kiosk/arch-kiosk-office#2179]
Comes out of testing #2154 

I guess because of the template strings, if I decide to run a report with unit_year and one with unit, the second report I run will override the first. I know you can set a prefix for the file in the report settings, but in this case where you are getting reports with different template strings from the same workstation -- hence reports that would get the same prefix -- is it worth figuring out a way in which they wouldn't get erased if downloading different ones?

**Comment by urapadmin** [comment]
no, honestly, I don't think so. It is still really the same report and not replacing it might rather produce confusion on the other end. What you can always do, I think, is create a new reporting dock with the same definition files. That would be stored separate from the other one. But I can't really think of a scenario so far where that would be useful (except maybe in tests)

**Comment by luizaogs** [comment]
Ok.
