### ISSUE TITLE
file sequence import: Progress does not get updated for too long stretches

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#2184]
while actually importing a sequence the progress does not get updated. Because that takes too long the UI on the cllient's side flags. That on the other hand leads to aborting the whole import.

**Comment by urapadmin** [comment]
### Kiosk 1.5.2.4
- progress gets updated now while images of a sequence are being added to the file repository

**Comment by urapadmin** [comment]
@lbestock I suppose we can close this now, right?

**Comment by lbestock** [comment]
We can. I think we are getting close here...
