### ISSUE TITLE
unclutter logs

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#2185]
The logs get cluttered a lot when the logging level is debug. 
A few of those debug entries are so repetitive that I should get rid of them

**Comment by urapadmin** [comment]
### Kiosk 1.5.2.5
- the logs are a bit uncluttered.

**Comment by urapadmin** [comment]
does not seem to have side effects. 
I'll roll this out to PVD so that @luizaogs can have a round of download,uploads,syncs if she likes...

**Comment by luizaogs** [comment]
oh oops, I think PVD is still on 1.5.2.1?

**Comment by urapadmin** [comment]
I just upgraded it and wrestled with a little new bug. But it is up and running now on 1.5.2.5

**Comment by urapadmin** [comment]
💤 💤 🛏️

**Comment by urapadmin** [comment]
I hope you finished your scary thingy. We are close to sending USTP and PASU off and that's always a bit scary, too.

**Comment by luizaogs** [comment]
Oh I finished it this morning :)

**Comment by luizaogs** [comment]
This appears to be working normally. 

I hope PASU and USTP have smooth Kiosk seasons.
