### ISSUE TITLE
Filemaker: insert for material type in architecture details instead of just a drop down list

### ISSUE THREAD

**Issue by lbestock** [arch-kiosk/arch-kiosk-office#2187]
Teeny tiny doesn't stop things from working, just a slight annoyance. FM has the "insert" still there for the dropdown menu for materials in the architecture details locus details. If one puts in the wrong thing, then, it is hard to get back to the right dropdown menu.
![image](https://github.com/arch-kiosk/arch-kiosk-office/assets/49291909/4bd1f64a-8627-498b-bd97-146774e1df93)

**Comment by lbestock** [comment]
Wow how many bad options are there in FM? The dropdowns for the material and trench in the registration filter are also inserts, but those behave differently and maintain their list even after you put something in. So less troublesome but still not perfect.

**Comment by urapadmin** [comment]
this is not a drop down at all. It seems to be an autocomplete.
I have switched if off. No idea where the stuff comes from.

**Comment by urapadmin** [comment]
### recording 15.2
- architecture: I have turned material into a real drop down list that is populated by values that have been used before in this field. New values can be added by typing something new in.

**Comment by urapadmin** [comment]
> Wow how many bad options are there in FM? The dropdowns for the material and trench in the registration filter are also inserts, but those behave differently and maintain their list even after you put something in. So less troublesome but still not perfect.

- that I don't understand. Those are normal drop down lists with the ability to also type something in. But yes, those lists will not change because that would not make any sense here. Maybe you want me to turn them into mere selection dropdowns without the keyboard? I'll try that.

**Comment by urapadmin** [comment]
### recording 15.2
- architecture: I have turned material into a real drop down list that is populated by values that have been used before in this field. New values can be added by typing something new in.
