### ISSUE TITLE
FM navigation: going from preprocessing to a CM that is not ceramics retains ceramics tab

### ISSUE THREAD

**Issue by lbestock** [arch-kiosk/arch-kiosk-office#2188]
I was doing some preprocessing.
I used the navigation "recently viewed" to go to a different CM.
It was a small find and thus had no preprocessing, but the preprocessing tab stayed up. I can click on things in it (like the pie chart function) but not create records.
The same thing happens when I'm in small finds details and then navigate to a CM that is not a small find. 
This is not really a big deal. It cannot result in messing up recording. It is just a minor confusion and, having noticed it, I report it.
![image](https://github.com/arch-kiosk/arch-kiosk-office/assets/49291909/fea1bf2e-4413-4ac6-9031-b7c02a8661c1)

**Comment by urapadmin** [comment]
### recording app 19.20
- should not happen anymore

**Comment by luizaogs** [comment]
Can you release this for USTP? Or does PASU also use preprocessing now?

**Comment by urapadmin** [comment]
ceramic preprocessing was even invented for PASU. So yes, you can use PASU.

**Comment by luizaogs** [comment]
Huh oops.

**Comment by luizaogs** [comment]
Looks fine to me now.
