### ISSUE TITLE
locus detail record not created when entering the detail layout

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#2193]
USTP created a new locus type "structure" in 2022 but did not assign any layout or field set to it. The result was that we have all these "structure" loci that never got a detail attached to them.

in 2023 we fixed their entry and added the "ac" field set and the detail layout "locus_type_ac".

Now we have a detail button in the layout for locus type "structure" BUT when you enter the layout there is no record (means: not only are all the fields blank, you cannot enter anything and the record info label in the lower right corner is empty).

**Comment by luizaogs** [comment]
Works, including through synchronization.
