### ISSUE TITLE
PASU: offers "ceramic" when creating the first collected material after a fresh template

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#2194]
looks like a fragment in the template from a former use

**Comment by urapadmin** [comment]
### recording 15.2.1
- that's what it was. Should not happen again.

**Comment by urapadmin** [comment]
@lbestock Did you check this?

**Comment by luizaogs** [comment]
This is fine on PVD 15.2.1 but I don't know if that was an issue on PVD before.

**Comment by urapadmin** [comment]
nothing that you would have noticed.

**Comment by lbestock** [comment]
I didn't check it again, so you'll have to power up the PASU server for me.
