### ISSUE TITLE
Mastaba of Akhmerutnisut Documentation Project (MADP)

### ISSUE THREAD

**Issue by luizaogs** [arch-kiosk/arch-kiosk-office#2196]
I know, bad acronym. My friend Inês and I got a permit to study/document a mastaba at Giza, and I would like to try and use Kiosk but since it won't be excavation (at least not in this first season) using Kiosk and FM would take some thinking -- if you guys would be interested in thinking about how it might be used for something like that. 

This is by no means urgent, and the earliest I can foresee a season is December. Even that seems unlikely with my schedule, so next summer is more probable. 

IF you guys would want to try to support a project like this, we could use this ticket to track things that are needed. One thing I know we would absolutely need is to make sure that Kiosk/FM recognize the Arabic script.

**Comment by urapadmin** [comment]
willing to support your project?
You must be kidding. 👀

**Comment by lbestock** [comment]
Aaa permit! Mabruk :)

**Comment by luizaogs** [comment]
Well it was less about being willing to support it, more about whether Kiosk can support it :)

**Comment by urapadmin** [comment]
Or should. 
So we need to talk about what digital support you need for that kind of project. And then we can see if Kiosk can and should be the right tool for that.

**Comment by luizaogs** [comment]
Right. Well I have the grant proposal that explains what we would be recording and why, and can share that. Or we can just talk about it eventually and I can run you through the plan for the season. Again, not urgent.

**Comment by urapadmin** [comment]
since it might already overlap with other things we hear, it cannot hurt to get a first overview now. If we see synergies with what others do it is best to see them as early as possible. Also: Old head. Takes time to chew on things.

**Comment by luizaogs** [comment]
Ok, I just emailed you both the grant outlining the tentative plans for the season.

**Comment by luizaogs** [comment]
Quick update on this: it looks like the plan would be for a December season, if we get the security clearance on time (which is, of course, a big if).

**Comment by urapadmin** [comment]
I think we should meet and talk about the project so that I get a sense how Kiosk can fit in here. It is often helpful if I know what is coming up in even a somewhat more distant future when making my daily developing decisions.

**Comment by luizaogs** [comment]
I can meet whenever.

**Comment by urapadmin** [comment]
or we talk about it over dinner in Leiden!

**Comment by luizaogs** [comment]
Works too :) Yay.

**Comment by luizaogs** [comment]
We just got security clearance. So it looks like the plan would be to go in December.

**Comment by urapadmin** [comment]
That's exciting! You'll have a busy 4th quarter in 2023. I have forgotten almost everything about our conversation about Kiosk for the project in Leiden. Except that we had decided in the aftermath to not work on replacing FileMaker but on implementing a visual recording module. Basically marking regions in an image and adding discrete data to it. 
Do you have a better memory?

**Comment by luizaogs** [comment]
That's pretty much what I remember too, so, no :) I'm fairly certain that the image annotation module was the biggest thing that was needed that Kiosk doesn't currently have, though. It might make sense to also meet with Inês if you guys have time (after I come back from Egypt probably) to make sure she's on the same page, but in terms of things that we would need that we don't already have I think that's the main (possibly the only) one.

**Comment by urapadmin** [comment]
Perhaps being in Egypt ⛏️  gives you ideas, too, even though or perhaps particularly because the project is fairly different. And then I think the best would be to have a concordance meeting and try to configure Kiosk for it. That is usually when things have to get so concrete that the real thinking starts. (right, @lbestock?). In the meantime I'll order a server space for you guys ("MADP" is your last word on acronyms?)

**Comment by luizaogs** [comment]
Meh not very glamorous but yes, I suppose so! MADP it is.

**Comment by urapadmin** [comment]
> Meh not very glamorous but yes, I suppose so! MADP it is.

oh, no judging, I just need to make sure. This is the one thing you cannot change once it is set. (I still nightmare about when BUPsomething changed to BUPTAP).

**Comment by luizaogs** [comment]
...which subsequently changed to PTAP. 

I like the four letter acronyms, so we can stick with this one! (Better than MoADP)

**Comment by urapadmin** [comment]
> One thing I know we would absolutely need is to make sure that Kiosk/FM recognize the Arabic script
I must have unseen this. What does that mean? That you plan to type from right to left in Arabic?

**Comment by luizaogs** [comment]
Huh, I don't actually know if it goes from right to left in iPads. What I had meant is that some of our team members (three are Egyptian) will likely feel more comfortable typing in Arabic rather than using the Latin alphabet, and then I expect that I would go in and copy and paste the English text below or something.

**Comment by luizaogs** [comment]
Wait no that's dumb, it must go from right to left.

**Comment by lbestock** [comment]
Concordance is when things get real! But I think all of us need to be in on this one, really, definitely including Inês and probably Lutz. Because it's not just a matter of what to call or how to number things, nor of just a visual recording tool, there will need to be decisions about how these things interact. What are the units of analysis in this case, where is the intrinsic and where the arbitrary when recording relief on a wall? Or fragments of fallen relief that have to be recorded before you know which wall they fell from, where you record them as part of the archaeological context of fall but need to attach them to walls later on?

Security clearance is exciting :) You will be in Egypt a LOT!

**Comment by luizaogs** [comment]
Yes, I definitely don't know yet how we should be recording any of that so talking through it will be helpful. Just let me know when it would be best to start meeting, etc.

**Comment by urapadmin** [comment]
We should tackle a meeting here. Query and View has taken me a good month longer than I wanted and so it isn't realistic that there will be anything like an image tagging module in December. Maybe we should rather strategise how to record without it in a way that it can be made digital in Kiosk post season.

**Comment by luizaogs** [comment]
This week is pretty hectic for me, but when were you thinking?

**Comment by urapadmin** [comment]
> This week is pretty hectic for me, but when were you thinking?

That is entirely up to you guys - my calendar is entirely flexible. Non-hectic preferred, I'd say, as such a meeting needs creativity and some head space.

**Comment by lbestock** [comment]
Good thing you wake up so early, CA person...
Next week it can be, then, but it has to be next week because following
that I am hectic with four job candidate visits in two weeks.
Perhaps we could shoot for Thursday the 2nd at 11am Rhode Island, 8am
California, 4pm Portugal?

**Comment by luizaogs** [comment]
Ha. If 8am is the sweet spot for CA then I could also do this Thursday, if that is preferable for you Laurel (that is literally the only 8am I have free this week, so you see what I mean...)

Anyway, I've asked Inês about next Thursday for now and will let you know once I hear back.

**Comment by luizaogs** [comment]
Inês can't this Thursday either, but we are both free at that time on the 2nd!

**Comment by luizaogs** [comment]
Inês' husband Maarten let me know today that he will also be joining us (he and I are the ones mostly thinking about recording for this season). Hope that's ok! And if you want me to send out the link for the meeting, I'd be happy to do that, too.

**Comment by urapadmin** [comment]
I do. But I have some trouble envisioning that in the upper corners of either Kiosk or the recording. Perhaps just the Acronym would do?

**Comment by luizaogs** [comment]
You can use whatever you prefer, of course.

**Comment by urapadmin** [comment]
I should have been more specific, I suppose: The issue is of a technical nature. I think when it gets shrunk to 120x80px it is hard to see:

![image](https://github.com/arch-kiosk/arch-kiosk-office/assets/38838314/774cb781-c4ef-404f-8ad2-d9cb94c2026b)

**Comment by luizaogs** [comment]
Yes, I figured. Acronym is fine!

**Comment by urapadmin** [comment]
you don't want to put your Acronym in your image?

**Comment by luizaogs** [comment]
Oof I didn't make this. I'll ask Maarten.

**Comment by urapadmin** [comment]
oh. Ha. Well, it is really not a particularly pressing issue, I'd say. We can just make it a ticket for later. Also we can invite Inês and Maarten to GitHub and they can get involved.

**Comment by luizaogs** [comment]
Definitely not pressing! I just got the logo recently so thought I would share. And yes, we should add them. I am meeting with them before our meeting on Thursday to show them the software (so they are on the same page when we start talking about how we want to use it) so I'll mention Github to them then.

**Comment by lbestock** [comment]
@luizaogs  to do upon receipt of server:

- [ ] add Inês and Maarten as users in Kiosk
- [ ] add Inês and Maarten as users in recording
- [ ] create docks with the proper names for the configured identifier lists! Inês is i_ipad, and Maarten is m_ipad

**Comment by luizaogs** [comment]
@lbestock I have done all of the above already so if you add stuff please let me know! (I added the docks because I thought they would save since you had said to already add them as users in Kiosk, but if they do not I'll just add them back once I get the physical server)

**Comment by urapadmin** [comment]
@arch-kiosk/madp 

Okay, the local server is ready, too.

- the last simpler thing might be solved, too: see #2336 
- BUT: What we really need ASAP is anything from the conservator or we won't be able to tackle that until the end of November. That part needs work and testing etc. New ticket here: #2370 
- there's also the part about the existing data (you might want to incorporate it in any way). New ticket: #2371

**Comment by urapadmin** [comment]
@arch-kiosk/madp: The project has moved to its final destination and is now available online under madp.arch-kiosk.brown.edu

**Comment by luizaogs** [comment]
Hooray!

**Comment by urapadmin** [comment]
one day we should venture to find out if any other university were willing to grant a project access to a Windows server like Brown does. But not now :o)

**Comment by luizaogs** [comment]
I think we can close this now that the package is in the mail, yes?
