### ISSUE TITLE
Sequence File Import: Cannot convert file to ..\kiosk\temp

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#2197]
The sequence import fails with this error message for every single file when using the "numerical part of filename" sort.

**Comment by urapadmin** [comment]
### Kiosk 1.5.2.6
- that's fixed but the bug affects summer projects

**Comment by urapadmin** [comment]
This is not happening with the other sort method "file's creation time" which we must have used exclusively in tests.

**Comment by luizaogs** [comment]
I just noticed this ticket lurking in testing. I can't do sequence imports on Beset, can I?

**Comment by urapadmin** [comment]
no, that is not possible. Sequence import needs access to a local directory on the server.

**Comment by luizaogs** [comment]
Womp womp @lbestock then it's yours.

**Comment by urapadmin** [comment]
and postponed until September when there is a local Kiosk to test with

**Comment by urapadmin** [comment]
that might be what USTP ran into in the summer. It seems we have patched Peter's system and that is why Anna was able to do it.

**Comment by lbestock** [comment]
Tested on MKAP, works fine now.
