### ISSUE TITLE
Perhaps a bug: Please test if adding a duplicate still gets rewired properly

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#2201]
When one adds the same image twice or more in the recording app (not using the gallery, really adding it in two different locations form the iPad's photos), synchronization should recognize this as a problem and fix it automatically by rewiring the recording data so that it points to a single instance of the image (if the checkbox during synchronization is set, but it should).

This is an older feature and I thought it just works, but KHPP got this:

![image](https://github.com/arch-kiosk/arch-kiosk-office/assets/38838314/4c4abe62-63b8-4df0-8881-11fca7072c50)

If one always gets those red error messages although the issue is fixed properly by kiosk I should downgrade these messages from errors to infos.

If this does not work anymore I have to attend to that.

Please test.

**Comment by lbestock** [comment]
Testing in Demo Kiosk 1.5.2.6 and I have no problems at all. The synchronization returns no warnings or errors or anything, and the result in the file repository is one image with both of the contexts where it was put.

**Comment by lbestock** [comment]
Even unchecking the checkbox - that just made synchronization fail rather than reproducing KHPP's errors.

**Comment by urapadmin** [comment]
then make it certain by trying it again. (Whatever it exactly is you are trying).

**Comment by lbestock** [comment]
Just trying to see if I can get the same error messages Leslie got and how. But your basic question is answered: in 1.5.2.6 at least there is no problem with rewiring and it doesn't result in any message at all after synchronization.

**Comment by urapadmin** [comment]
closing this as it seems it had been tested
