### ISSUE TITLE
autocorrect being annoying: add to "how to prepare ipads" section of Q&A?

### ISSUE THREAD

**Issue by luizaogs** [arch-kiosk/arch-kiosk-office#2202]
Apparently KAMBE is also running into annoyances with common archaeological terms being autocorrected. Not a Kiosk issue, I know, but maybe something that can be added to the Q&A for directors when preparing iPads? So they know to turn it off (if they run into this problem).

(I read through that section of the Q&A and didn't find it, but if it is already elsewhere then ignore this.)

**Comment by urapadmin** [comment]
Indeed, nothing I can control via FileMaker. You may add how to switch it off to the Q&A.

**Comment by luizaogs** [comment]
Ok, added it to the section on preparing ipads in the Q&A for directors and admins.
