### ISSUE TITLE
kiosk 1.5.4 stems from a new development machine and has styling issues

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#2207]
In some regions the styling is entirely derailed. Strange buttons visible, no background color at all, Icons missing etc. 
I have fixed this already in Hub, query & view, director's view. But there are more places. 
@arch-kiosk/test: Please report here.

**Comment by urapadmin** [comment]
- [ ] file manager doesn't look healthy at all.

**Comment by luizaogs** [comment]
- [ ] the file import window looks a bit funny. I think you used to have separations between the categories, rather than just a wall of text? I can still click on the options, though.

**Comment by luizaogs** [comment]
The rest seems ok, as far as I can tell.

**Comment by urapadmin** [comment]
> * [x]  the file import window looks a bit funny. I think you used to have separations between the categories, rather than just a wall of text? I can still click on the options, though.

that's fixed but you can't see it anymore because online server should not offer local and sequence imports, anyways. That'S fixed now, too.

**Comment by urapadmin** [comment]
- [x] bugs & features
the rest should be okay,too.

**Comment by urapadmin** [comment]
but let's leave this open for now, the UI has very distant corners and we might run into more when testing MKAP in more depth

**Comment by urapadmin** [comment]
ja, I think we would have bumped into more of that. Closing is good, I feel like drowning.

**Comment by luizaogs** [comment]
Ha well, if closing tickets helps with drowning we can probably close a few more of the ones under observation...
