### ISSUE TITLE
file-import by filename for projects with illegal characters in identifiers

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#2210]
This came out of khhp 2023:

The file import can import files and attach them to a context accoding to their filename or directory name.
But this works only if ids don't have characters that are illegal as filenames. So if somebody uses a \ or a * or something like that in their identifiers, one cannot make a file like that.

Two ideas:   
  - Substitute characters (that would need a way to configure that for a project)
  - interpret unicode codes by default: E.g. 0x002a (or 0x2a) is a "*", 0x5c is a backslash etc. The Windows charmap helps with the code. So if somebody really wants a unit called F\1 then the filename would have to be F0x5c1. The 0x and the length of the unicode number would still need to be configurable. 
  
In fact I like the substitution a bit more because it would allow for the 0x5c, if I allow to substitute character sequence. This way one could also use shortcuts. E.g. if one has a lot of images starting with F0018dasdf-d one could simply use a short sequence and have it replaced with the longer one. It is a bit of an advanced feature but could be handy.

**Comment by urapadmin** [comment]
So the plan is the substitution strategy for it is much more flexible. In a first take I would like to have only one possible substitution. Should a team have several identifiers that need to have patterns replaced they would have to go through separate imports. So far we have only one example of a single unit at all. So I spare myself overly complicated UI work.

**Comment by urapadmin** [comment]
I'll also have a bit of an encoding in the search pattern: if it starts with \ everything up to the next : will be options for the substitution. The options are separated by comma.
I plan these options:
- [ ] ALL: All occurences will be replaced (the default is that only the first will be replaced)
- [ ] NOCASE: 
- [ ] REGEX: The search pattern is a regex pattern (default is that the search pattern ISN'T a regex pattern)
If a search pattern has to start with a "\" AND has a subsequent : (which is actually not possible at least for file names) then it needs emtpy options like this "\:" first. Everything after the empty options will be interpreted as the search pattern.

**Comment by urapadmin** [comment]
### Kiosk 1.5.6
- This is now fully implemented for file upload (bunch) and local import (ton)
- I did not see an actual case for the sequence import, so there the option is not available
- this needs documentation in both the Q&A and as a video tutorial, I guess.

**Comment by luizaogs** [comment]
Question: I'm reading the explanation in the Q&A and should you also mention that the "context from operating system file" should be checked in addition to "substitute patterns in identifiers" ? Or is that not the case? Because otherwise I can see people only checking the substitution.

**Comment by luizaogs** [comment]
I think MCP is down but I need to create a context with illegal characters to test this. Let me know when it's back up?

**Comment by urapadmin** [comment]
> Question: I'm reading the explanation in the Q&A and should you also mention that the "context from operating system file" should be checked in addition to "substitute patterns in identifiers" ? Or is that not the case? Because otherwise I can see people only checking the substitution.

Well, that depends. The substitution works on all methods to recognize a potential identifier - even on qr codes (where it makes very rarely any sense, but still). That is why the checkbox is independent of the filter settings. The most common import filters will be operating system file and operating system folder, of course. So you are welcome to add your advice, just don't forget the operating system folder filter.

**Comment by urapadmin** [comment]
> I think MCP is down but I need to create a context with illegal characters to test this. Let me know when it's back up?

oops. I forgot to restart it. It is up again.

**Comment by luizaogs** [comment]
> 

Never mind. I misunderstood what it could be used for.

**Comment by luizaogs** [comment]
Ugh did I mess it up? Import settings were "substitute patterns in identifiers" and "context from operating system file".

**Comment by luizaogs** [comment]
Yeah, no. I am apparently not only exhausted but also amnesiac. I will try again.

**Comment by luizaogs** [comment]
Oh wait, that selection is apparently the default? So I suspect it was checked, yes. Let me see...

**Comment by luizaogs** [comment]
Yes, it had been checked. I unchecked "get description from filename" this time and now I have no context or description attached to the images. But if it worked for you I must be doing something incorrectly, only I do not know what that is.

**Comment by luizaogs** [comment]
<img width="892" alt="Screenshot 2023-07-20 at 11 37 44 AM" src="https://github.com/arch-kiosk/arch-kiosk-office/assets/67970402/efd08829-f652-4eaa-938f-9708b773698c">

<img width="905" alt="Screenshot 2023-07-20 at 11 37 52 AM" src="https://github.com/arch-kiosk/arch-kiosk-office/assets/67970402/b1b4a2b6-9394-4a41-b041-7e350f347470">

**Comment by luizaogs** [comment]
Oh lord Jesus. Dr. Silva, ladies and gents.

**Comment by urapadmin** [comment]
I suppose it is a bit misleading to say that a pattern in an "identifier" will be substituted. But I could not think of a better way of putting it since the text that's to be manipulated (see, it is hard!) is not necessarily a filename.

**Comment by luizaogs** [comment]
It worked now, of course :) Lovely. But yes, the language confused me. Not that I have a better suggestion.

**Comment by luizaogs** [comment]
Wait, is it not necessarily the filename? When I saw identifier I assumed you meant the identifier in FM, which is why I ended up switching them around. Filename might be clearer?

**Comment by luizaogs** [comment]
You said the QR code substitution should work in the same way? I got this error: 

<img width="889" alt="Screenshot 2023-07-20 at 11 55 40 AM" src="https://github.com/arch-kiosk/arch-kiosk-office/assets/67970402/3b076644-4129-4a8c-82e5-5e45357f2d02">

**Comment by urapadmin** [comment]
different issue here. Aparently the qr code decoder or encoder has a problem with backslashs, too. (Backslashs is the most idiotic character someone could possibly choose and I can only hope nobody ever will). Nonetheless worth finding.

Apart from that:
Now you are going a bit the other way around again. There is already a 123\a encoded in your qr code (or would be if the other bug did not exist). So no _ in the identifier to substitute with a \\. And since you cannot easily make a qr code with a _, you need a different test scenario.

As I mentioned earlier, for qr codes it is rarely useful. A scenario where one could use it is if somebody shot a bunch of photos of a unit and shot the wrong qr code in (that of a different unit). In this case they could replace the wrong unit id that's encoded in the qr code with the right unit id for the import.

**Comment by luizaogs** [comment]
Sorry, I should have clarified: I got the error for the QR code without the substitution.

**Comment by luizaogs** [comment]
Do you need me to test anything else specific here?

**Comment by urapadmin** [comment]
> Wait, is it not necessarily the filename? When I saw identifier I assumed you meant the identifier in FM, which is why I ended up switching them around. Filename might be clearer?

it would be clearer if it weren't for the fact that the first source of the identifier is not necessarily a filename or folder name (which are already two things) but could also be the qr code (and whatever else we introduce here one day). So, I guess we should clarify it in the Q&A and any suggestion how to change the label (filename is just not exactly correct) here to avoid the confusion is appreciated.

**Comment by urapadmin** [comment]
if you have fun testing you may test if you can use the substitution for a qr code (just don't use backshlashs). Perhaps the way I described: Just replace one unit or locus identifier for another.

**Comment by urapadmin** [comment]
@arch-kiosk/test : We really should keep in mind and perhaps add it to the Q&A that some characters in identifiers will inevitably cause trouble: Backslashs, single and double quotes, percentage signs (%) and the wildcard (*). Those should be avoided.

**Comment by urapadmin** [comment]
you could also test to eat a lot of 🍨 and sleep a lot.

**Comment by luizaogs** [comment]
Substituting one unit for another with the wrong QR code, and then using the substitution during import worked!

**Comment by luizaogs** [comment]
> @arch-kiosk/test : We really should keep in mind and perhaps add it to the Q&A that some characters in identifiers will inevitably cause trouble: Backslashs, single and double quotes, percentage signs (%) and the wildcard (*). Those should be avoided.

I can do that, but not sure where it should go?

**Comment by urapadmin** [comment]
> > @arch-kiosk/test : We really should keep in mind and perhaps add it to the Q&A that some characters in identifiers will inevitably cause trouble: Backslashs, single and double quotes, percentage signs (%) and the wildcard (*). Those should be avoided.
> 
> I can do that, but not sure where it should go?

I am not sure, either. I don't think we have anything about numbering and identifiers at all so far in the Q&A because that's concordance stuff. And we don't have a user manual. So. "Keep in mind" it'll be, I guess.

**Comment by luizaogs** [comment]
Alrighty. So this ticket is done? Or do you want any more tests?

**Comment by urapadmin** [comment]
no, I think we can close it. The bugs you found are covered in separate tickets.
