### ISSUE TITLE
Upgrade of the Pillow library needs test of file import

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#2211]
### Kiosk 1.5.6
Once Kiosk 1.5.6 is online the file import needs testing:
> I found that the newer Pillow version (I am on 9.5.0 now) was not supported by the file import. So I upgraded the code (which got simpler) to support that version. But we have to test the file import on Beset since the code needs to support both, the new and the old Pillow version. On Beset I cannot upgrade to Pillow 9.5.0 until ALL projects are on Kiosk 1.5.6. So the new Kiosk versions needs to be downward compatible regarding Pillow.

So basically, just test the file upload import on Beset with a Kiosk 1.5.6 or higher.

**Comment by luizaogs** [comment]
I'm about to test this but first observation is that on PVD I have all of the options available: bunch, ton, and sequence. Shouldn't I only be able to see bunch because it's not a local server? Or has that changed?

**Comment by luizaogs** [comment]
Bunch file import works just fine.
