### ISSUE TITLE
kiosk patches: make them run even without a transfer_dir configured.

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#2212]
No need to refuse the installation of a patch before it has been unpacked just because it has no transfer_dir or because unpackkiosk is missing in the transfer_dir.

**Comment by luizaogs** [comment]
Lutz, this is yours to test, right?

**Comment by urapadmin** [comment]
totally

**Comment by urapadmin** [comment]
this has changed quite a bit with #2388 and I expect the transfer dir to be configured and existing now.
