### ISSUE TITLE
Kiosk operation fails: MCPQueue.queue: Cannot lock MCP

### ISSUE THREAD

**Issue by luizaogs** [arch-kiosk/arch-kiosk-office#2214]
Still trying to test #2210 but now this happened: 

<img width="1512" alt="Screenshot 2023-07-20 at 8 35 52 AM" src="https://github.com/arch-kiosk/arch-kiosk-office/assets/67970402/2c201d83-fa6d-4657-a90f-5ef5abdfe660">

**Comment by urapadmin** [comment]
does this happen repeatedly?

**Comment by urapadmin** [comment]
no, apparently it does not. Might be that there was a concurrent access to MCP at this time or the universe had a sneeze. I just synchronized and all seems okay now.

**Comment by urapadmin** [comment]
I reopen this because I have seen it too today when preparing my workstation. Twice might not just be coincidental so I put this on watch.

**Comment by urapadmin** [comment]
particularly because we do have a new MCP vesion since yesterday: 0.2

**Comment by luizaogs** [comment]
Ha I was going to suggest closing this one as well but then I realized that this is what we saw the other day in #2472. So I guess not?

**Comment by urapadmin** [comment]
honestly, you may. This has not happened in the field and even on Beset, where we have had quite a few things running in parallel these days, it happened only once to my knowledge. So at this rate it is not something I will (or even can) follow up.
