### ISSUE TITLE
file repository: Identifiers with \ in them are not found

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#2215]
not a common thing, but it could happen: special SQL characters in an identifier.
came out of #2210

**Comment by urapadmin** [comment]
### Kiosk 1.5.6.1
- images that have an identifier with a \ or more should be found in the file repository when searching by context
- images that have a \ in the description (context-dependent or -independent) should be found when searching by description

**Comment by luizaogs** [comment]
Works.
