### ISSUE TITLE
qr code encoding / decoding: Backslashs are lethal.

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#2216]
coming out of #2210 
Aparently the qr code decoder or encoder has a problem with backslashs, too. (Backslashs is the most idiotic character someone could possibly choose and I can only hope nobody ever will). Nonetheless worth finding.

**Comment by urapadmin** [comment]
the issue starts with the encoding in filemaker: The \ and the letter after the backslash are missing in the qr code

**Comment by urapadmin** [comment]
### recording app 15.2.2, Kiosk 1.5.6
- the backslash should be encoded properly now 
- the file import should import such a qr coded image without problems

**Comment by luizaogs** [comment]
Well that's a great FM icon :)

**Comment by luizaogs** [comment]
Works.

**Comment by urapadmin** [comment]
> Well that's a great FM icon :)

It's the "I was there when Luiza became a doctor" icon :o)

**Comment by luizaogs** [comment]
It is appreciated!
