### ISSUE TITLE
logs: Eat a lot of 🍨 and sleep a lot.

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#2217]
- [x] eat a lot of🍨 
- [ ] sleep a lot.

- [ ] repeat remember the image container bugs? Sometimes you need to repeat things a lot before you can be sure that it is fine)

_Originally posted by @urapadmin in https://github.com/arch-kiosk/arch-kiosk-office/issues/2210#issuecomment-1644168614_

**Comment by luizaogs** [comment]
The ice cream eating, at least, I can do.

**Comment by luizaogs** [comment]
Slept this weekend.

**Comment by lbestock** [comment]
Phew :)

**Comment by urapadmin** [comment]
she totally ignored the "repeat" task :o)

**Comment by luizaogs** [comment]
I didn't ignore it, I just don't think it likely :)
