### ISSUE TITLE
PASU: ceramics processing can't scroll through long lists of sherds

### ISSUE THREAD

**Issue by lbestock** [arch-kiosk/arch-kiosk-office#2219]
In the PASU specialists ceramics module, once one has selected one's processing context, if there are records for many sherds then the bottom of the list cannot be accessed. There is a scroll bar on the right but that is for the individual highlighted record so that the whole thing can be seen. Only as much of the list of sherds as occupies the vertical space taken up by a detailed record is actually visible.

The solution is for the PASU ceramics module to have a scroll bar on the left for the list of sherds.

Before that can happen, they can be advised that they can find sherd records through the search function even though they will not be able to see that whole list.

I tested this most easily by making a new ceramic processing record for a previously unprocessed DIAG ID. I made 26 sherd records. I can only see 23 of them.

**Comment by urapadmin** [comment]
### recording 15.2.3
- there is a scroll bar now (it is nonetheless necessary to scroll all the way down on the right scrollbar to see the lower down arrow of the left scrollbar)
- (different issue but I add here for matters of lazyness) I have allowed the rename button to appear for registrars in this layout. So one still has to switch temporary free input on to see the rename button but one does not have to be admin to see and click it

**Comment by urapadmin** [comment]
- I have tested that the new recording version can be installed on the PASU virtual machine

**Comment by luizaogs** [comment]
This is only testable on iPads, right? Or would a Mac test be sufficient? I do not have my iPad this weekend.

**Comment by urapadmin** [comment]
it should happen on both but an iPad test is the one that's really missing here.

**Comment by luizaogs** [comment]
Tried to test this but I do not have sufficient privileges in PASU test to prepare a workstation.

**Comment by lbestock** [comment]
You know you can log in as admin and change your own privileges...

**Comment by luizaogs** [comment]
I was never given the admin password for Kiosk, just for FM.

**Comment by urapadmin** [comment]
She can't. The admin passwords for the online servers are not "admin". And should you ever find one that is "admin", change it right away!

**Comment by luizaogs** [comment]
It has now been tested.
