### ISSUE TITLE
MKAP 2023 season priorities

### ISSUE THREAD

**Issue by lbestock** [arch-kiosk/arch-kiosk-office#2222]
Didi hits the field on 2 October 2023. We have a lot of stuff we need to do for her, though lots has already been done, too. This ticket supersedes #1980, which was discussion but not action plan.

- [x] #1986 
- [x] #2240
- [x] configure terms
- [x] configure numbering functions
- [x] ask Didi: will all elevations be taken with RTKs or will excavators hand measure off datum points, too?
- [ ] Didi needs a backup drive (wasn't in the box) and needs to assign that backup drive the drive letter Z:. it also needs to have a directory "backup" on it.
- [ ] #2288

**Comment by urapadmin** [comment]
we won't be able to do the bones recording for MKAP in 2023. But I though that was already discussed and it was also not all that likely that they'd hit dead people in the first season?

**Comment by urapadmin** [comment]
The Harris Matrix generator is my hobby project. It is not a module that is likely to be available in October. But in the field I think it is more important to record stratigraphic relationships meticulously (otherwise no Harris matrix can be generated) and that's already possible. So if I spend the Christmas break working on my hobby project it can still be used for MKAP then?

**Comment by urapadmin** [comment]
> This ticket supersedes https://github.com/arch-kiosk/arch-kiosk-office/issues/1980
So should we close that one?

**Comment by lbestock** [comment]
They aren't _intending_ to dig burials but intent in archaeology is a dangerous game and I wanted to leave it in as a matter of discussion. Can we, for instance, roll out a burial form that has everything but the fancy bone stuff and not have that be wasted effort for the eventual full thing?

**Comment by lbestock** [comment]
@urapadmin I do NOT know how to write an identification method that auto generates two-letter unit names a la Uronarti. URAP does it free input. Is that possible?

**Comment by urapadmin** [comment]
neither do I :o) I have to look that up.

**Comment by didi-elbehaedi** [comment]
Hope you guys are having a great weekend! ☺️

Laurel, we spoke about photogrammetry a bit last Friday! But, looking over stuff now, what we currently have in the “Coordinates” section doesn’t fully do what the photogrammetry form we used in Edfu does (I think Luiza had already mentioned this in ticket #1986).

For that, we would need to be able to add sketches to categories of points as well as descriptions (adding photos to individual points is helpful for GCPs), but for photogrammetry we need an overall sketch of all points and it might be a bit redundant to attach that same sketch to every point in the model. I’m thinking it would just be easier to have a single image attached to the category itself?

**Comment by didi-elbehaedi** [comment]
Also, just saw the note about elevation. Yes, all elevations will be taken with the RTK!

**Comment by urapadmin** [comment]
- [ ] Didi needs a backup drive (wasn't in the box) and needs to assign that backup drive the drive letter Z:. it also needs to have a directory "backup" on it.

**Comment by urapadmin** [comment]
@lbestock: as for configuration: is the season configured? That's helpful in the object registration module.

**Comment by didi-elbehaedi** [comment]
> * [ ]  Didi needs a backup drive (wasn't in the box) and needs to assign that backup drive the drive letter Z:. it also needs to have a directory "backup" on it.

Will do! I have the ADATA hard drive in hand already, so I'll go ahead and assign the drive letter when I get the Surface laptop back (couldn't find a way to do this via my MacBook - maybe it's only a Windows thing? No idea) and create a "backup" directory!

**Comment by urapadmin** [comment]
> > * [ ]   Didi needs a backup drive (wasn't in the box) and needs to assign that backup drive the drive letter Z:. it also needs to have a directory "backup" on it.
> 
> Will do! I have the ADATA hard drive in hand already, so I'll go ahead and assign the drive letter when I get the Surface laptop back (couldn't find a way to do this via my MacBook - maybe it's only a Windows thing? No idea) and create a "backup" directory!

Yes, it is a Windows thing. Don't worry, you'll get proper instructions!

**Comment by lbestock** [comment]
I THINK I am done configuring this and have backed up.

**Comment by urapadmin** [comment]
I think I am done with this. Let's box it up.
