### ISSUE TITLE
reporting dock: use HTML

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#2226]
HTML is in fact a good reporting format if exact paper layout does not matter that much. 
The idea here is that I simply use Jinja-templates in an new reporting dock type. That is of course a very customized format (not accessible even to power users) but should be easy to implement.

- #1821 is the test case for this

**Comment by urapadmin** [comment]
ja, that works well. But it will be a bit awkward once the images get embedded because the HTML file one downloads from the file manager will only show images if Kiosk is running. I could think about saving copies of the images together with the report BUT in that case the images would have to be downloaded as well. 
Hm.
I suppose I wait and see how awkward it actually looks like ...

**Comment by urapadmin** [comment]
I don't even get to awkward at all because it simply cannot work: the HTML file is opened locally and so I would need to know the complete http:// address to get to the image. But the server does not know what that address would be for a client. So this approach is not really reasonable. 
Two options:
- exporting the image with the html file and zipping both together. Then the zip would have to be downloaded and can be shown properly locally. 
- showing the report right away in a new browser tab. No downloading from the filemanager at all. In that case I think I should even save the file in the temporary directory instead of the report's file manager directory so that nobody ever thinks about downloading it at all.

**Comment by urapadmin** [comment]
I decided to offer a new option for such a dock: view report. So the report still gets rendered by "run". But instead of having an option to download it there is an option to view it right away in the current browser session. That makes Kiosk present the report and so all the data and the environment is available.

So far so good, but now I need an idea how to show all the rendered reports (one per arch-context) together. My idea is to render all the reports as sub-templates in the dock's report folder and integrate them in a main report that has a stable filename. That's the Jinja template that is rendered in "view"
- [ ] the dock's report directory needs to be cleared
- [ ] generate sub reports
- [ ] generate the main report on view only (but from its own template?)

**Comment by luizaogs** [comment]
How do I test this?

**Comment by urapadmin** [comment]
In the end the only way is to run the reports, see if the data matches the recording data for the pasu sherd report and report what you notice. Peter and his team can test the report itself and tell us if it does what they want. 

Since I have extended the whole reporting architecture a lot, it is important to look at the other reports. Do they still work? Not necessary to test the content but zipping should work, the report should be generated, downloading from the file manager should work etc.

**Comment by luizaogs** [comment]
Ok. I will report anything specific about the sherd report in #1821 (once I can download that, which I can't currently) and more general things about zipping and generating reports here.

**Comment by luizaogs** [comment]
Kidding, apparently I can just view and not download the sherd report. I need downloading privileges (which aren't working) to test the zipping and downloading for the other stuff.

**Comment by urapadmin** [comment]
> Kidding, apparently I can just view and not download the sherd report. I need downloading privileges (which aren't working) to test the zipping and downloading for the other stuff, which I will then report in this ticket.

For the others the Wiki tells me I have to grant you the ENTER_ADMINISTRATION_PRIVILEGE, which I did now. That's a bit sub-prime given that it also gives a user access to the whole administration plugin. However, you should be able to see the results of your reports now.

**Comment by luizaogs** [comment]
Hmpf, I now get to the file manager but still am not allowed to download.

**Comment by urapadmin** [comment]
> Hmpf, I now get to the file manager but still am not allowed to download.

what happens?

**Comment by luizaogs** [comment]
<img width="1512" alt="Screenshot 2023-07-28 at 10 18 33 AM" src="https://github.com/arch-kiosk/arch-kiosk-office/assets/67970402/06efa0a0-c8de-4df5-98e6-da6d0b678f16">

**Comment by urapadmin** [comment]
It turns out you even need the MANAGE_SERVER_PRIVILEGE but calling that subprime would be a euphemism. Let's call it a bug.

**Comment by urapadmin** [comment]
I have hand-patched that. Is it better?

**Comment by luizaogs** [comment]
Yup, worked.

**Comment by luizaogs** [comment]
Generating and zipping still all work, so I think this is ok?

**Comment by urapadmin** [comment]
Ah, you found the other reports faster than I could install them :o)

If it all works you may close this.

**Comment by luizaogs** [comment]
Oh wait, I ran the context sheet report for 2022 contexts and got this: 

<img width="1512" alt="Screenshot 2023-07-28 at 10 32 52 AM" src="https://github.com/arch-kiosk/arch-kiosk-office/assets/67970402/9802b64e-ae00-4ff2-9b9c-3279c1a3c252">

**Comment by luizaogs** [comment]
And then the Context Sheet dock says "report can be downloaded" but the only option I get when clicking on it is "run report"

**Comment by luizaogs** [comment]
Context List worked just fine.

**Comment by urapadmin** [comment]
The first is okay, I think. That's just a bunch of images missing. But the other thing sounds like a side effect of my latest changes. So I'll look into it (no hand patching this time).

**Comment by urapadmin** [comment]
### kiosk 1.5.7.1
- the PDF report (context sheet) should a) give you the option to zip files and b) the option to download the results afterwards

**Comment by lbestock** [comment]
I learned something new about Acrobat. If one combines all the downloaded zipped files into a single PDF then it doesn't work, it takes the information in the fields of the first PDF (say, description of context) and puts it in the description field for every other one of the combined PDFs. I can get them all together sort of by making a PDF Portfolio, but that is still individual files and I cannot scroll through one big fat notebook as I expected to be able to do. I can print that Portfolio, but what I can't figure out yet how to do is "print" it to a single running PDF. Weird. But on the Kiosk side everything is working as it should, the context sheet report lets me zip or not and download.

**Comment by lbestock** [comment]
Yeah wow. One can only do this by flattening the PDF, which renders it unfillable. You cannot preserve the ability to edit the information in the fields AND turn it into one big long document. 

But, the Kiosk part being done, and since the original point of this ticket was anyway the HTML reporting, I close this.
