### ISSUE TITLE
update images if image_load has a different number of records

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#2228]
This is coming out of #2227 
----
the logs showed that everything up to exporting to Tyler's workstation was fine. 
There we had two errors ony one of which was reported to me. The first error actually caused the second error (the one reported) to happen:

![grafik](https://github.com/arch-kiosk/arch-kiosk-office/assets/38838314/f43732ec-0c09-460c-b255-7e700291805e)

- This FileMaker Hiccup left the recording group in a state where the images_load table was updated but the contents not transferred to the images table by filemaker itself. 
- Tyler repeated his export and the export found that the images_load table was up to date, wo nothing needed to be transferred.
- While that was correct, the images table did not get updated, either, because the images_load table had nothing new
- but the images table had not been gotten up to date in the previous round and the result is the discrepancy reported in the subsequent error: The images table had less records than it should have.

_Originally posted by @urapadmin in https://github.com/arch-kiosk/arch-kiosk-office/issues/2227#issuecomment-1649199792_

**Comment by urapadmin** [comment]
so I must run the FileMaker script that transfers records from images_load to images even if images_load did not get an update. Perhaps I could compare the number of records in both tables? 
Or get rid of the check if images_load got updated entirely?

**Comment by urapadmin** [comment]
while this could potentially happen to MKAP as well, I doubt it. So this stays open. But we should remember it. This was not an issue of importing data (as was thought first) it was an issue of exporting TO a workstation or rather TO a recording group. Resetting the recording group would have cleared the issue.

**Comment by urapadmin** [comment]
another possibility after such an incident would be to reset the recording group. That's at least the manual remedy here.

**Comment by urapadmin** [comment]
### Kiosk 1.5.38
- I check explicitly now if the table "images" in filemaker matches the "images" table of the workstation in Kiosk. If that is not the case I run the step that otherwise would have been skipped because a different check for the "images_load" table thought it could be. That should help against an export that manages to export the "images_load" table and then aborts due to some random error. That was the case with Tyler's original issue. 
- as with #2719 I don't like working in these lines of code. It might screw things up more than it does any good. So the import / export / sync cycle needs to be tested. 
- The issue itself cannot be tested by @arch-kiosk/test but I have simulated and tested it and it seems to be working. So now it is under observation for a while, which means the whole export is under observation.

**Comment by luizaogs** [comment]
Wait, since this was under observation I didn't see it before. Do you want me to do the test mentioned in the last bullet point? Or is it just under observation?

**Comment by urapadmin** [comment]
ja, it is a difficult test. You would not easily be able to judge if a positive outcome actually proves that the issue is fixed. 
Since the issue is extremely rare (we had it only once with Tyler) it is more important to observe if my changes have any side effects on normal operation. Hence it is under observation. The real test here is just preparing, downloading, importing, syncing over and over again under realistic circumstances.

**Comment by urapadmin** [comment]
no observable side effects from this
