### ISSUE TITLE
PASU ceramics going between sherds - question

### ISSUE THREAD

**Issue by luizaogs** [arch-kiosk/arch-kiosk-office#2231]
This is super minor and so a question rather than a bug report. 

When moving between different Chiaves in PASU ceramics, if I am on the images tab for one and then click on another one I get taken to that images tab, rather than the observations tab. Is that purposeful? Does it matter?

**Comment by urapadmin** [comment]
You tell me :o) I guess it depends.

**Comment by luizaogs** [comment]
I mean, it wasn't what I expected to happen. But I think it's minor so don't know!

**Comment by urapadmin** [comment]
I can as well imagine that in some situations it is quite handy that you don't have to flip between those tabs over and over if you are clicking through the sherds to look at the images.

**Comment by luizaogs** [comment]
Right. Hence my uncertainty.

**Comment by urapadmin** [comment]
In which case I'd say: Let's leave it until a user complains.
