### ISSUE TITLE
Oh wait, I ran the context sheet report for 2022 contexts and got this:

### ISSUE THREAD

**Issue by lbestock** [arch-kiosk/arch-kiosk-office#2234]
Oh wait, I ran the context sheet report for 2022 contexts and got this: 

<img width="1512" alt="Screenshot 2023-07-28 at 10 32 52 AM" src="https://github.com/arch-kiosk/arch-kiosk-office/assets/67970402/9802b64e-ae00-4ff2-9b9c-3279c1a3c252">

_Originally posted by @luizaogs in https://github.com/arch-kiosk/arch-kiosk-office/issues/2226#issuecomment-1655691262_

**Comment by urapadmin** [comment]
That is not a meaningful title. 
Luiza already got this and it isn't an issue. Just missing images on the test server.

**Comment by lbestock** [comment]
Luiza noted the above in a ticket on HTML reporting and Lutz said it was just some missing images. But a context sheet report for contexts that have images in the reporting does not include any images at all and I did want to make double sure this was intended. What we talked about with USTP last year was that the photographs section of a context sheet needs not images themselves but a list of photo numbers.

**Comment by lbestock** [comment]
Argh I was editing it!

**Comment by urapadmin** [comment]
it is really not an issue as far as I remember. Just images that cannot be turned into filenames, presumably because they are missing or missing something else. I ignore this until one of the actual users of this context sheet tells me otherwise.

**Comment by lbestock** [comment]
And I really wasn't sure it was a non-issue. Photos that are in the file repository and in the recording on the test server are not in the report of the context generated on the test server. That isn't a problem?

**Comment by lbestock** [comment]
OK.

**Comment by urapadmin** [comment]
I looked up that it cannot be a side effect of my latest additions. The issue was already there before. The rest is hard to understand and I ignore it due to the fact that nobody is actually using this report for anything meaningful.
