### ISSUE TITLE
assignee test

### ISSUE THREAD

**Issue by PeterDeathBredon** [arch-kiosk/arch-kiosk-office#2236]
I want to be assigned

**Comment by PeterDeathBredon** [comment]
I GOT ASSIGNED! Yay.

**Comment by lbestock** [comment]
Good, because I hand-added you to another new ticket...

**Comment by urapadmin** [comment]
which was not necessary because urapadmin got assigned already automatically (it comes with a delay). Now both, the author and urapadmin get assigned.
