### ISSUE TITLE
ceramic pie chart formatting: can get very crowded

### ISSUE THREAD

**Issue by lbestock** [arch-kiosk/arch-kiosk-office#2238]
I am not sure if anything can be done about this, but in the epic pie charts of USTP, who really use them, there can be confusion because there is an overlap in text:
![image](https://github.com/arch-kiosk/arch-kiosk-office/assets/49291909/870a6cfc-76fa-4707-8611-9a6f20db9166)
I fudged this to make it look better for an illustration for the Advances in Archaeological Practice article, but perhaps we can think about making it so it doesn't happen.

**Comment by urapadmin** [comment]
can't be helped. FileMaker does not offer any options on that front.
