### ISSUE TITLE
Points: Categories need photos and description

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#2240]
- Coming out of #1986: 

> I’m not sure if the photogrammetry analysis module would need to be separate from what you’re envisioning here - the main difference I can think of is that there would need to be a way to add an image to the category, too, since one usually sketches the area being modeled in order to indicate where the markers were placed (that’s what the sketch is for in the paper form). Perhaps also making it possible to add a description to the category would be enough in terms of adding the other relevant information on the form (locus and feature numbers relevant to the model, etc).

**Comment by urapadmin** [comment]
@didi-elbehaedi / @luizaogs 
Does it only need one image per category (one sketch) or would it even need a list of images per category?_

**Comment by luizaogs** [comment]
I think one would suffice but Didi should confirm.

**Comment by didi-elbehaedi** [comment]
Yes, exactly! Only one image (the sketch) is needed per category.

**Comment by urapadmin** [comment]
Next question would be what exactly you do with this:

If you intend to find the category sketch via the category name in the file repository, we must give categories real identifiers. That makes it much more work and I fear we are cluttering the search function with non-archaeological identifiers. So I would prefer not to.

So my most simple approach would be that you can add an image and a description to the category once you have defined a category for a point. So first you need at least one point per category to access the category description and sketch. And the only way to see that sketch is to click on a point first to have access to that sketch. 

Would that allow you to do what you want to do with it?

![image](https://github.com/arch-kiosk/arch-kiosk-office/assets/38838314/e00b399d-93e7-4213-8124-d111285143f7)
(Prototype screenshot that shows you that only if a point is selected you get a tab with the category information. Ignore the red things on the UI, they are developer stuff)

**Comment by urapadmin** [comment]
### recording 15.3
- prototype for the coordinate categories. It works, but it does not sync! I just need to know if this is enough to serve the purpose first.

**Comment by luizaogs** [comment]
This looks fine to me. Would the sketches be findable in the file repository by searching for specific points? I guess yes, right?

Also, if this is too much work then ignore it, but would it be possible to add the reference navigation to the coordinate description? Just because I imagine that's where we would say "photogrammetry model for feature 56" or whatever, and so it would be nice to be able to navigate to it from there.

**Comment by urapadmin** [comment]
> This looks fine to me. Would the sketches be findable in the file repository by searching for specific points? I guess yes, right?
It should be possible but I have never configured Kiosk to do it this way. We'll find out :o)
 
> Also, if this is too much work then ignore it, but would it be possible to add the reference navigation to the coordinate description? Just because I imagine that's where we would say "photogrammetry model for feature 56" or whatever, and so it would be nice to be able to navigate to it from there.

Yes, that is no problem.

**Comment by urapadmin** [comment]
### recording 15.3.1 and Kiosk 1.5.8
- should be implemented 
- should sync properly
- category images should show up when searching for one of the points of that category in the file repository

**Comment by lbestock** [comment]
Reference navigation is currently by the image for coordinate category. That can't have text. Did you mean to put it next to the category description? Navigation works fine in the point description.

Whoa the synch log for 11:30am Berlin time is a mess. Trench A seems really unhappy. That wasn't me, and ldb_ipad seems happy enough so I will let you check that out and will proceed to look at if my additions synchronized properly.

**Comment by lbestock** [comment]
Ah no, needs you badly.
The images I added to points (three photos for two points and a category sketch) are not in the file repository at all and the identifiers (points) are not known to the file repository.

**Comment by lbestock** [comment]
Whoa wait, my ipad says it was not synchronized at all when I go back to the Hub.

**Comment by lbestock** [comment]
Here are the error messages as seen after synchronization:
![image](https://github.com/arch-kiosk/arch-kiosk-office/assets/49291909/3ffeb382-6662-42b9-9bde-4f13cd65cb50)

**Comment by urapadmin** [comment]
This presumably is a side-effect of me changing the data structure while docks are in various states. 
I have renewed all docks and hope it won't occur again. Otherwise I'll look into it closer.

**Comment by lbestock** [comment]
But it does reference search the description, so it's just a placement, which I had not realized at first.
All works now. 
Why in the File Repository are the identifiers given in a weird order?
![image](https://github.com/arch-kiosk/arch-kiosk-office/assets/49291909/c955623d-7353-4344-b2cc-cec08693756e)
I notice it particularly because it's not the order in which they were given the association with the IDs nor the order in which the IDs appear in the coordinates list.

**Comment by luizaogs** [comment]
In terms of testing this is done for now, yeah?

**Comment by urapadmin** [comment]
> But it does reference search the description, so it's just a placement, which I had not realized at first. All works now. Why in the File Repository are the identifiers given in a weird order? ![image](https://user-images.githubusercontent.com/49291909/260683031-c955623d-7353-4344-b2cc-cec08693756e.png) I notice it particularly because it's not the order in which they were given the association with the IDs nor the order in which the IDs appear in the coordinates list.

No mammoth tickets, please! This is a general file repository comment. please file a separate ticket.

**Comment by urapadmin** [comment]
> In terms of testing this is done for now, yeah?

Have you tested it yourself? For me the most important question here is if the whole topic is cared for now for MKAP. All that's left here is the placement of the reference navigation and I already cared for that. So it could be closed.

**Comment by luizaogs** [comment]
Yes, it looks good.
