### ISSUE TITLE
UCI practicum course

### ISSUE THREAD

**Issue by luizaogs** [arch-kiosk/arch-kiosk-office#2241]
UCI has a practicum course. I think taught by Ian Straughn, in the anthro department. Should I try to see if there would be interest/funding available to use Kiosk? (Not now, I suppose I should get there first, but just thought of it.)

**Comment by lbestock** [comment]
Oh totally. (I start thinking: what on earth is there to dig in Orange County? Really? Anything more than 50 years old is going to be Native American and not open for a practicum class...) 

And hi to Ian! Rose and Layali were best friends when they were little and I hope they are thriving.

**Comment by luizaogs** [comment]
Ha. I think they're old ("old") buildings on campus but I'm not totally sure.

**Comment by lbestock** [comment]
Hm if they are standing buildings then some of the issues we've been discussing that are more relevant to recording architecture and its decoration than excavation might even come into play.

**Comment by luizaogs** [comment]
Yeah my anxiety demanded that I cross something off my to-do list today, so this was it. Ian (who says hi back) is teaching it in the fall and thinks that is likely too soon to start using Kiosk. But he totally seems interested overall so maybe we can start talking to him about it relatively soon so it can be implemented next year. He also mentioned that there are other projects in the works so I will meet up with him when I'm there and see what we might be able to work with.

**Comment by luizaogs** [comment]
I'm meeting with Ian (and maybe another archaeologist) on Monday to talk about Kiosk. Is there any way I can get access to arch1900 to show them that data? Just because I think it might make more sense for them to see how it has been used in a practicum course. Or I guess you guys used the arch1900 data for the demo Kiosk, right? Should I use that?

**Comment by urapadmin** [comment]
Ja, I suppose the demo server would be the best address here. I will update it and the recording app to the latest version tomorrow.

**Comment by luizaogs** [comment]
Thank you. 

Also, a workflow question in case they ask: does arch1900 use an iPad per unit? Or how do they ensure that different students get a chance to try their hand at recording? (this might be a @lbestock question)

**Comment by luizaogs** [comment]
Ian thought Kiosk was great. The first thing he asked me was how to query the database - ha, good timing for q&v. He says he will keep it in mind as he figures out what the next iteration of the practicum course will be (as well as some other potential projects). Anyway, just to keep you updated.

**Comment by urapadmin** [comment]
arg. I totally forgot in the end that I needed to update the demo server. I hope that wasn't in the way when you met. My apologies.

**Comment by luizaogs** [comment]
It wasn’t! I chose to not bother you about it :)

**Comment by luizaogs** [comment]
Not yet. But I'm trying to start an archaeology research center here that will involve the Anthro archaeologists and so there is potential to involve Kiosk, even if doing so in the practicum course doesn't happen (though Ian was interested, funding would be the problem). I'll keep you updated.

**Comment by lbestock** [comment]
I'm surprised one of my colleagues hasn't started a movement to excavate cleared encampments yet. A new kind of campus archaeology.
As for funding, the price on iPads is now really pretty manageable... $250 per.

**Comment by luizaogs** [comment]
Yeah, but then there’s Filemaker and the server. I’ll be in touch with Ian about this research center proposal shortly so will ask him about this, too.

**Comment by urapadmin** [comment]
that kind of field school excavation could be done using an online Kiosk only. We run ARCH1900 here at Brown with a local server rather for the side effect of getting some real-life testing nearby.

**Comment by luizaogs** [comment]
Ah ok. Well, might make things easier. I'll ask.

**Comment by luizaogs** [comment]
Same with this.
