### ISSUE TITLE
file import: Suppress Apple's hidden files

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#2247]
Apple creates thumbnails whenever it sees a file on a disk. Those thumbnails are hidden on Mac OS but not on Windows.
The file repository should suppress files that start with a dot by default. For the rare case that a project would need to import files with a . I'll make it configurable.

- see also #844

**Comment by urapadmin** [comment]
### kiosk 1.5.10 (Flask 2.3.3 needed) / kiosk 1.5.7.103 (Flask 2.0.2)
- this should not happen any longer.

**Comment by luizaogs** [comment]
Is this a Lutz test? If not, how do I test it?

**Comment by urapadmin** [comment]
ja, let's call that a Lutz test

**Comment by urapadmin** [comment]
I think this is okay now.
