### ISSUE TITLE
retain usernames attached to created records when users are deleted

### ISSUE THREAD

**Issue by lbestock** [arch-kiosk/arch-kiosk-office#2249]
I am encountering this in URAP which is ooollld and it's possible we already took care of this.

Most records from prior to 2019 are recorded as made by "sys". That's presumably because the people who actually made them are no longer in the team members list. It's unwieldy to have a team members list that is larger than the current team, particularly for large and longer term projects that have changes every season, so I would imagine it would be common to delete old team members. I clearly did it myself without thinking of the implications. The implications are drastic - I have no idea who created most of the records from prior seasons.

If it isn't possible to freeze that, then we should have a serious warning on the delete button and a two-step delete for team members associated with records.

**Comment by urapadmin** [comment]
This is merely a fantasy. Apart from the fact that nobody ever deletes users, the user designation in the record stays the same and has always been that way.
The 'sys' stems from old bugs in Kiosk and early synchronization issues in FileMaker when mass manipulation of records changed the user-id. So we lost quite a few of them. Not a systemic issue any more nowadays BUT it could resurface in certain cases and would need to be filed as a new bug. But this here is just legacy.
