### ISSUE TITLE
update URAP

### ISSUE THREAD

**Issue by lbestock** [arch-kiosk/arch-kiosk-office#2250]
URAP is an old version of the recording software and Kiosk. I am making screenshots and little tiny videos for the website. I will use URAP for some of these and it would help to have it on the latest version so I can demonstrate things like navigation. (This has a deadline of about 10 September; I want the website significantly updated before the AIA award nomination goes in, which is no later than the 15th, and I expect to get things to Leslie on the 31st of August while you are in the air.)

**Comment by urapadmin** [comment]
Urap is up to date now.
