### ISSUE TITLE
PASU: Fragment report with a check box that includes images

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#2253]
It got suggested
> to prioritize the written information - which has prompted the suggestion, or perhaps question, whether it would be possible to create a report that first of all lists all the written info as in the example you have sent, and that might include, perhaps with a tick box, the option to include or not one or more photos.

**Comment by urapadmin** [comment]
### needs Kiosk 1.5.39
- added the ability to have a boolean variable in a report which will be shown as a checkbox in the report's UI
- added that to the PASU Sherd report so that it can be generated with or without images

**Comment by luizaogs** [comment]
Then I shall wait for those to be done.

**Comment by urapadmin** [comment]
@lbestock needs to be tested on local PASU, too!

**Comment by luizaogs** [comment]
Same comment here - should the fields be in Italian?

**Comment by luizaogs** [comment]
Ran the report for all fragments in 035A-DIAG and for some reason one of the fragments (035-006) did not include any images. There are 3 images for this fragment, I checked. But one is only an image container, so I don't know if that could have messed up the rendering of the report.

**Comment by luizaogs** [comment]
Just tried this twice and same results: 

If I first run a report (either for a single fragment or the whole CM) with images, if I then try to run that same report WITHOUT images it renders it with images when I try to do it without checking the images checkbox. If I then run it again (or twice more) without checking the images box, it finally gives it to me without images.

**Comment by luizaogs** [comment]
As far as data, I believe it's all there.

**Comment by urapadmin** [comment]
> Same comment here - should the fields be in Italian?

no, not in View. That's only a FileMaker demo feature.

**Comment by urapadmin** [comment]
> Just tried this twice and same results:
> 
> If I first run a report (either for a single fragment or the whole CM) with images, if I then try to run that same report WITHOUT images it renders it with images when I try to do it without checking the images checkbox. If I then run it again (or twice more) without checking the images box, it finally gives it to me without images.

I had seen that, too, and decided it smells like a cache issue. Does it also happen of you clear the cache in between the runs?

**Comment by luizaogs** [comment]
Apparently not.

**Comment by urapadmin** [comment]
> Ran the report for all fragments in 035A-DIAG and for some reason one of the fragments (035-006) did not include any images. There are 3 images for this fragment, I checked. But one is only an image container, so I don't know if that could have messed up the rendering of the report.

can't reproduce this. Just ran it for PASU and I see all three images. Does a Browser refresh help or change things?

**Comment by urapadmin** [comment]
what device are you on?

**Comment by luizaogs** [comment]
Mac. I'll try it again.

**Comment by luizaogs** [comment]
> Just tried this twice and same results:
> 
> If I first run a report (either for a single fragment or the whole CM) with images, if I then try to run that same report WITHOUT images it renders it with images when I try to do it without checking the images checkbox. If I then run it again (or twice more) without checking the images box, it finally gives it to me without images.

Ugh now I got the opposite, wanting images and getting none.

**Comment by luizaogs** [comment]
> > Ran the report for all fragments in 035A-DIAG and for some reason one of the fragments (035-006) did not include any images. There are 3 images for this fragment, I checked. But one is only an image container, so I don't know if that could have messed up the rendering of the report.
> 
> can't reproduce this. Just ran it for PASU and I see all three images. Does a Browser refresh help or change things?

Yeah, now they're there. I don't know.

**Comment by urapadmin** [comment]
> > > Ran the report for all fragments in 035A-DIAG and for some reason one of the fragments (035-006) did not include any images. There are 3 images for this fragment, I checked. But one is only an image container, so I don't know if that could have messed up the rendering of the report.
> > 
> > 
> > can't reproduce this. Just ran it for PASU and I see all three images. Does a Browser refresh help or change things?
> 
> Yeah, now they're there. I don't know.

It seems to swallow an image or three every now and then. Presumably because of network issues. But I am not sure what causes it. I have seen it, too.

**Comment by urapadmin** [comment]
> > Just tried this twice and same results:
> > If I first run a report (either for a single fragment or the whole CM) with images, if I then try to run that same report WITHOUT images it renders it with images when I try to do it without checking the images checkbox. If I then run it again (or twice more) without checking the images box, it finally gives it to me without images.
> 
> Ugh now I got the opposite, wanting images and getting none.

yup, it looks as if the last setting prevails until one runs the thing again. It does really smell like a cache issue but it might not be the browser causing it.

**Comment by luizaogs** [comment]
No, clearing the cache fixed it. But having to clear the cache every time seems a bit extreme.

**Comment by urapadmin** [comment]
> No, clearing the cache fixed it. But having to clear the cache every time seems a bit extreme.

agreed. But I might not find a reliable solution for the field, so would you please add a hint in the Q&A?

**Comment by urapadmin** [comment]
### kiosk 1.5.39.2
- I tried to instruct Chrome not to cache the report. In my development system I have not seen the issue again. I hope it makes a difference on your side, too.

**Comment by urapadmin** [comment]
### Kiosk 1.5.39.3
no, `no-cache` did at least not do it for me locally (it is possible, though, that it did it for Beset).
What seems more effective if this Flask option that is now part of our default configuration:
`TEMPLATES_AUTO_RELOAD: TRUE`

It was a clear case that only after restarting the Kiosk server locally would the report be reloaded when hitting "view" on the dock.

**Comment by luizaogs** [comment]
Ok so I wait to test it when you release 1.5.39.3?

**Comment by urapadmin** [comment]
oh, messed the versions up somewhere. It is rolled out.

**Comment by urapadmin** [comment]
- no,  didn't. The last thing is indeed not rolled out. yet. Too many versions in too quick succession

**Comment by luizaogs** [comment]
Looks good now. Does it still need to be tested locally? If so, over to @lbestock

**Comment by urapadmin** [comment]
I have don my testing hat and tested it on local Pasu successfully
