### ISSUE TITLE
registration in FM on the laptop: can create a new CM with command+N on the mac - whoops!

### ISSUE THREAD

**Issue by lbestock** [arch-kiosk/arch-kiosk-office#2254]
I was looking at registration for URAP on my mac.
I also had nine zillion things open on my computer, on two monitors.
I thought I was in Word and was creating a new document when I hit command N.
But I was still in FM, and I accidentally made a new CM record that has no attachment to anything, and that should really not be possible.
![image](https://github.com/arch-kiosk/arch-kiosk-office/assets/49291909/89c41d35-1a09-4320-9ec8-55c16b2b74bf)
![image](https://github.com/arch-kiosk/arch-kiosk-office/assets/49291909/506d7e17-bd98-4fc7-bb48-5b1d3f7c8d72)

**Comment by urapadmin** [comment]
I should look into shortcuts. I thought blocking the menus would block the shortcuts but that is clearly not the case in FileMaker.

**Comment by urapadmin** [comment]
### recording app 19.20
- this should not be the case anymore
