### ISSUE TITLE
NCAM Khartoum inventory report for URAP

### ISSUE THREAD

**Issue by lbestock** [arch-kiosk/arch-kiosk-office#2255]
NCAM has urgently requested an inventory of all our objects and their locations. The only ones that matter are Khartoum. I would like a report in the form of a list with thumbnail photos arranged something like this:
![image](https://github.com/arch-kiosk/arch-kiosk-office/assets/49291909/e230800b-96fc-4244-9b45-237f3919e6eb)
The information I need for each object is: URAP#; date; material; description; photo(s)

The criteria for determining which URAP#s to include:
Must be a small find.
Must have location either Khartoum or K.
Can include Wheeler things, so you will have funny URAP#s such as 28-3-345 and that is fine - my instructions to them say I have included those.

**Comment by urapadmin** [comment]
The "photos" column is the issue here. Would it suffice to just show the first photo per collected material?

**Comment by urapadmin** [comment]
nevermind, I'll try. It will be a HTML report anyhow, as we cannot embed images in PDF or Excel, yet.

**Comment by urapadmin** [comment]
### Kiosk 1.5.9
- needed a new Kiosk version because reporting could not do easily what we needed here. Now it can.
- the report is installed on urap.arch-kiosk.brown.edu

**Comment by urapadmin** [comment]
as for the "K" or "Khartoum": That's to complicated. Please just run the report twice with different locations

**Comment by lbestock** [comment]
No! Even that is wrong. I need the date that is in the date field on the CM record. That's quite important here - the Wheeler stuff needs to have the date of its excavation, and the URAP stuff needs to have the date given when excavated. Those records in particular get modified later (when the registrar touches them, when I discover something later and update the record) and the info I want on the list is excavation date.

**Comment by lbestock** [comment]
The Wheeler stuff has year and month but not date, so that information is not only not in there, it doesn't exist. Harumph. But I still want the report to give the date given in the date collected field of the CM, it'll just be blank for all those Wheeler objects.

**Comment by urapadmin** [comment]
> The Wheeler stuff has year and month but not date, so that information is not only not in there, it doesn't exist. Harumph. But I still want the report to give the date given in the date collected field of the CM, it'll just be blank for all those Wheeler objects.


So in other words it has not been recorded at all in the URAP database?

**Comment by lbestock** [comment]
> 

It wasn't even recorded in the Wheeler notebooks themselves, so I am not sure the information was ever there to begin with. Maybe on object cards in the MFA.

**Comment by lbestock** [comment]
Hm I am still getting the date the record was created, it looks like, not the date that is in the field "date collected".

**Comment by urapadmin** [comment]
> Hm I am still getting the date the record was created, it looks like, not the date that is in the field "date collected".

not anymore I hope

**Comment by lbestock** [comment]
Still not right, now even weirder!

![image](https://github.com/arch-kiosk/arch-kiosk-office/assets/49291909/5618b93a-9de5-42fc-8c21-5a846a84ef47)

**Comment by urapadmin** [comment]
you must have seen a preliminary state. I don't get that issue anymore.

**Comment by lbestock** [comment]
It's all good. Thank you!
