### ISSUE TITLE
"dear registrar" should be clickable in registration

### ISSUE THREAD

**Issue by lbestock** [arch-kiosk/arch-kiosk-office#2256]
Some things related to registration can be directly edited in the registration module itself (storage, to do/done). This is not true for "dear registrar" and I think it should be. If there are dear registrar notes they are sometimes too long to be entirely legible in the registration module itself, so clicking to read is even more important than editable but I can imagine cases where the latter is wanted, too. (I am having one now, as I get ready to give NCAM an inventory of things in Khartoum, but it's such a special case I won't argue too hard.)

**Comment by urapadmin** [comment]
are you doing this on your Mac? I remember that I made the layout slightly responsive to bigger screens than iPads.

**Comment by lbestock** [comment]
Yes, I'm on my mac here.

**Comment by urapadmin** [comment]
in fact it was editable had you been on a smaller screen (ipad). In that case it shows a button instead of the field and that opens a popup that allows manipulating the data.
But I have made the input field editable now, too.

**Comment by urapadmin** [comment]
### recording 15.4.2
- if you click on the dear registrar field a pop-over opens that allows you to type. In the end I abstained from making the edit field itself editable because it was just too small.

**Comment by luizaogs** [comment]
So I don't actually see the field at all any longer, just the button that I can click on to get the pop-over. Which is indeed editable. Was this the idea? (this is on my Mac)

<img width="1026" alt="Screenshot 2023-11-07 at 1 11 12 PM" src="https://github.com/arch-kiosk/arch-kiosk-office/assets/67970402/1799b633-1ad7-44dd-bb91-094ef5c6eab2">

**Comment by urapadmin** [comment]
that is the idea. It depends on the width of the window. I forgot where I set the limit, but somewhere at about 1000-1200px it flips from the button to the text field.

**Comment by urapadmin** [comment]
![image](https://github.com/arch-kiosk/arch-kiosk-office/assets/38838314/5e45bc33-e069-4043-82f5-dc2129a41b7b)

**Comment by luizaogs** [comment]
Ah yes. Works.
