### ISSUE TITLE
temporary free input: change CM ID and the material is lost

### ISSUE THREAD

**Issue by lbestock** [arch-kiosk/arch-kiosk-office#2257]
When I change the ID of a CM, the previously entered material is lost. I can enter it again, but it shouldn't get lost in the first place. I assume this is related to the fact that the material shows up in parenthesis next to the ID of the CM in lists.

Encountering this in URAP.

We were inconsistent in the beginning with how we put Wheeler artifacts in. Those that were given URAP numbers I am now changing to our later convention of using Wheeler's own numbers as URAP numbers. If I change FA-059-12, which appears in the small finds dropdown menu as FA-059-12 (wood) to 24-5-13, then wood gets lost as the material type and I have to choose it again from the material drop down.

**Comment by urapadmin** [comment]
apart from the error here, did you not record the Wheeler number as an alternative number at least?

**Comment by urapadmin** [comment]
> apart from the error here, did you not record the Wheeler number as an alternative number at least?

just asking because I can manipulate such things en masse so that you wouldn't have to go through all these records manually.

**Comment by lbestock** [comment]
Oh that is great. I changed the ones from FA already but I do believe there are more. I was doing it manually and it wasn't that difficult because yes, the Wheeler numbers were there in the record, they just weren't the ID.

**Comment by lbestock** [comment]
YES. There are quite a few things in EC that are Wheeler objects but have URAP numbers. They include the Wheeler number as a (presumably now defunct) field called Wheeler# on the small finds detail.

**Comment by urapadmin** [comment]
> YES. There are quite a few things in EC that are Wheeler objects but have URAP numbers. They include the Wheeler number as a (presumably now defunct) field called Wheeler# on the small finds detail.

No, can't be done. The external_id field has a few inputs that cannot be turned into an identifier.

**Comment by urapadmin** [comment]
### recording app 15.19.2
- the material should stay untouched now 
- EXCEPT if the number generation method is depend on the material. That would be idgen_material as we use it in PASU and USTP, I think. That one in particular needs a test to make sure I did not introduce a new bug with this

**Comment by luizaogs** [comment]
I'll try testing this along with #2188 once I get USTP.

**Comment by urapadmin** [comment]
I am not sure, it is possible that USTP is a better candidate here because it is using idgen_material. But I am not sure myself about PASU on that front.

**Comment by luizaogs** [comment]
Hm ok it looks like PASU uses idgen_material for bulk. Let me see if I can figure this out...

**Comment by luizaogs** [comment]
Ok wait, I'm confused. Tested this with non-bulk in PASU and the material didn't change, great. 

Now testing it with bulk in PASU, which uses idgen_material, and it is still not changing if I don't introduce a letter corresponding to a material. However, I just opened another CM bulk to see if I can change the material by using a letter with a material code and now the wrong letter is showing up in the dialogue: 

The previous CM I had changed did have a B at the end, because it was bone. But plaster should be F, so I'm not sure why there's a B here now other than that it is being reused from the previous modification somehow.

<img width="752" alt="Screenshot 2024-05-18 at 4 56 58 PM" src="https://github.com/arch-kiosk/arch-kiosk-office/assets/67970402/1eb8d89a-5810-482c-bb3a-08f7d049e3dc">

**Comment by luizaogs** [comment]
Yeah, more confused. I also tried to change the code that I know corresponds to bone in another CM, to see if the material would then change, but it didn't. I just have a funny looking identifier "catB" and the material is still stone.

<img width="1025" alt="Screenshot 2024-05-18 at 4 58 58 PM" src="https://github.com/arch-kiosk/arch-kiosk-office/assets/67970402/aaab7e12-a71d-43f1-b940-45d8e258912d">

Is it only supposed to change if I actually change it in the dialogue, then?

**Comment by urapadmin** [comment]
> Yeah, more confused. I also tried to change the code that I know corresponds to bone in another CM, to see if the material would then change, but it didn't. I just have a funny looking identifier "catB" and the material is still stone.
> <img alt="Screenshot 2024-05-18 at 4 58 58 PM" width="1025" src="https://private-user-images.githubusercontent.com/67970402/331837769-aaab7e12-a71d-43f1-b940-45d8e258912d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYxMzU1MjEsIm5iZiI6MTcxNjEzNTIyMSwicGF0aCI6Ii82Nzk3MDQwMi8zMzE4Mzc3NjktYWFhYjdlMTItYTcxZC00M2YxLWI5NDAtNDVkOGUyNTg5MTJkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE5VDE2MTM0MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI2ZWExZDlmZWJhMGZlODdmOWIwNDZiYWUxYThlMTM5MzUyYmFjMDg2NjlhZThlYjU2ZjkzNjE1MGJmMDdmNDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.yRPZbfU0MA1X4tbbv0VCxLiNqcNI_wEiMc5RlBbkaVg">
> 
> Is it only supposed to change if I actually change it in the dialogue, then?

ja, I think so. The moment the users takes over with temporary free input and renaming they are responsible for getting it right.  So with idgen_material in place the information from the dialog must be applied no matter what the data in the record was before. 
For identification methods other than idgen_material (and that is @lbestock 's  case) the material field has nothing to do with the identifier and hence there was no need to erase it. It should just stay untouched by renaming. 
So I am confused, too, is that what is happening?

**Comment by luizaogs** [comment]
@lbestock 's case above is resolved.

**Comment by luizaogs** [comment]
For idgen_material, the material is not changing either, if I change the ID. Only if I change the material in the dialogue as well. I just wanted to make sure that is what is intended.

**Comment by luizaogs** [comment]
> Ok wait, I'm confused. Tested this with non-bulk in PASU and the material didn't change, great.
> 
> Now testing it with bulk in PASU, which uses idgen_material, and it is still not changing if I don't introduce a letter corresponding to a material. However, I just opened another CM bulk to see if I can change the material by using a letter with a material code and now the wrong letter is showing up in the dialogue:
> 
> The previous CM I had changed did have a B at the end, because it was bone. But plaster should be F, so I'm not sure why there's a B here now other than that it is being reused from the previous modification somehow.
> 
> <img alt="Screenshot 2024-05-18 at 4 56 58 PM" width="752" src="https://private-user-images.githubusercontent.com/67970402/331837673-1eb8d89a-5810-482c-bb3a-08f7d049e3dc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTYxMzU5NzYsIm5iZiI6MTcxNjEzNTY3NiwicGF0aCI6Ii82Nzk3MDQwMi8zMzE4Mzc2NzMtMWViOGQ4OWEtNTgxMC00ODJjLWJiM2EtMDhmN2QwNDllM2RjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTE5VDE2MjExNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTM1YzY3NGQ5NTYzNTBkY2U4NDFjMjA1ZGQ5NjAzYzQwODA0MWNkZmI5MmUxOWMxZTExYzQxYjE2YWNiMDE2NGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.rrzPYvXGV2Yy5dWb_EBretByigQKiejkFPqTTWX4dWY">

This is the potential bug-ish thing.

**Comment by urapadmin** [comment]
> For idgen_material, the material is not changing either, if I only change the ID. Only if I change the material in the dialogue as well. I just wanted to make sure that is what is intended.

yes, that is what I intend. The connection between the identifier and the material is more of a project-dependent convention that they have to control themselves when they switch to free input.

**Comment by urapadmin** [comment]
But indeed, the "B" is not what should be shown when you select "Plaster" and I'll look into that.

**Comment by luizaogs** [comment]
I didn't select plaster - plaster is the material for that identifier, so it was selected already when I opened that dialogue. 

The issue is that the previous identifier I had changed, belonging to another CM, was bone. And so it seems like the B carried over to this dialogue, when the F should be showing up instead.

**Comment by urapadmin** [comment]
### recording app 15.20.1
- should not happen anymore
