### ISSUE TITLE
arch1900: 2023 Season

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#2260]
- [x] #2264
- [x] Concordance can be done with the online version once it is up and running. So that's my first task.
- [x] #2259 
- [x] #2265 
- [x] #1961 
- [x] install FileMaker 2023 on server
- [x] #2267 
- [x] change the colour of the IP message in the terminal in Kiosk. It is not legible and red isn't really the right colour. Also change the colour of the error messages as they aren't legible either (e.g. if Kiosk is in emergency mode because of redis not being up).
- [x] try to import "Albert" which isn't even in the field anymore.

**Comment by lbestock** [comment]
I would suggest keeping it the same system (and same server space) and making LAB a new site only. It is still ARCH1900. Same expedition, same methodology, different site of work.

**Comment by urapadmin** [comment]
> I would suggest keeping it the same system (and same server space) and making LAB a new site only. It is still ARCH1900. Same expedition, same methodology, different site of work.

and keep the arch1900 data in the same file repository etc?

**Comment by lbestock** [comment]
I would. Any search will be totally separate - the trenches will have different names. I can even see value in the students having access to previous records as examples (which, admittedly, would work better if records before were more complete, but my first thought is to say it is still more helpful than not). I do not think it would run the risk of being confusing to use in the field - the default would be to the LAB site and they wouldn't even see MB unless they changed the site.

**Comment by urapadmin** [comment]
done.
