### ISSUE TITLE
Kiosk/recording app: FileMaker 20 

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#2261]
Or "2023" as they call it now. But technically it is still version 20. This ticket here is about FileMaker Pro 2023 on the server side.
Of course, we also have a FM Go on the other side, but those are separate issues. FM 20 is still compatible backwards to FM Go 19 and vice versa.

However, we have to upgrade to 2023 to check if it still works. Projects can stay on 19 as long as they want.

**Comment by urapadmin** [comment]
### The Hillside Server
gets it first as we are testing #1961 here, anyhow. Next will be arch1900 and then mkap.

**Comment by luizaogs** [comment]
This has been tested, no? At least we haven’t run into issues with it here.

**Comment by urapadmin** [comment]
yes, I think we can say that it works (and the next albeit minor version is already out).
