### ISSUE TITLE
Sequence Qr codes should not be cut off in portrait mode

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#2262]
Might be the same for other qr codes. if it isn‘t possible to make this responsive it should at least keep it from working at all.

**Comment by urapadmin** [comment]
that is harder than it seems: The qr code javascript is using a fixed size of 512x512 pixel. So I have to experiment with that first.

**Comment by urapadmin** [comment]
### 15.3.2
until then I have added a reminder when trying to show a sequence qr code in portrait mode

**Comment by lbestock** [comment]
The reminder is only there for sequence QR codes in portrait mode, not yet for photoboard. 

Another horrible wrinkle making it even harder! If one creates the code in landscape and then turns the iPad you get a cutoff code. Even in sequence, that is still possible.

**Comment by urapadmin** [comment]
> The reminder is only there for sequence QR codes in portrait mode, not yet for photoboard.
> 
> Another horrible wrinkle making it even harder! If one creates the code in landscape and then turns the iPad you get a cutoff code. Even in sequence, that is still possible.

I know. To hell with all users who do that. I have to tackle this again, one day and make it properly responsive but for now I refuse.

**Comment by urapadmin** [comment]
could I issue a warning if the iPad gets rotated in the qr code view? We could require this to stay in landscape mode here.

**Comment by urapadmin** [comment]
### recording app 15.19.2
I hope this won't go wrong. 
So while the qr code is visible the app checks every three seconds again if the iPad is in Landscape mode. Otherwise one gets a warning.
Does that help?

The warning also comes now with normal photoboard qr codes

**Comment by luizaogs** [comment]
Yeah. I get the warning every time I'm in portrait, so I would think that would be enough.
