### ISSUE TITLE
closing qr codes is awkward

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#2263]
It needs a click on the qr code itself and even that does not work all that well often enough.

**Comment by urapadmin** [comment]
There is also no need to show the RasbPi option if no RasbPi is comfigured

**Comment by lbestock** [comment]
One needs to click the QR code twice to get the raspberry pi option, but that is not a problem and this is working so I close it.

**Comment by urapadmin** [comment]
> One needs to click the QR code twice to get the raspberry pi option, but that is not a problem and this is working so I close it.

That is the usual FileMaker Go issue with everything that uses a WebView: First one clicks on the Web thingy to activate it and then one can do the actual click. Dumb and will be there forever.
