### ISSUE TITLE
director's view: chaos in user IDs 

### ISSUE THREAD

**Issue by lbestock** [arch-kiosk/arch-kiosk-office#2269]
Testing #1961 and came across a problem in the Director's View, 1.5.10 on the local demo server.
I have no idea if this is related to the Flask update, but it should be tackled regardless. Two parts:
1. LDB and ldb show up as two separate people and have different records associated with them. The LDB records seem to be all those I made on the iPad, while the ldb records are part of the file import I did while logged in as myself to Kiosk. The parts of the import that were assigned to ldb are the candids that came in without context and were subsequently assigned contexts in the file repository, and the photos that came in with photoboard QR codes. That was all me, of course.
2. The photos that were imported as a sequence import have come in as "sys". That was me, too, of course. 

![image](https://github.com/arch-kiosk/arch-kiosk-office/assets/49291909/e12cbf42-d94b-4725-83f2-c367bfa87f6b)

- [ ] #2271
- [ ] #2272

**Comment by urapadmin** [comment]
As for 1.
that chaos is in the configuration and now in the records: I suspect that the repl_user_id of your Kiosk user is set to "LDB", capitalized while the user in the recording app is ldb no caps. Those are two different users. And no I cannot switch off capitalization here, unfortunately. I could force

**Comment by urapadmin** [comment]
As for 2.
as what user were you logged in when you ran the sequence import?

**Comment by lbestock** [comment]
As myself. Same login as the other import (which I accidentally ran first).

**Comment by urapadmin** [comment]
> As myself. Same login as the other import (which I accidentally ran first).

okay, that would be a bug in the sequence import not using the correct user id.

**Comment by lbestock** [comment]
The case thing was definitely a repl user in Kiosk not being capitalized, easily fixed.

**Comment by urapadmin** [comment]
> The case thing was definitely a repl user in Kiosk not being capitalized, easily fixed.

wait, so the user in the recording app was intentionally capitalized?

**Comment by lbestock** [comment]
At least, it is capitalized in the recording app and was not in Kiosk.

**Comment by lbestock** [comment]
And I have just made a new user in the recording app and NOT capitalized it, and the recording app turns it into capitalized.

**Comment by urapadmin** [comment]
okay, so we have two separate tickets here:
# 2271 and #2272

**Comment by urapadmin** [comment]
I close this one here because the director's view is fine
