### ISSUE TITLE
Query and View: not finding tagged contexts after Flask update

### ISSUE THREAD

**Issue by lbestock** [arch-kiosk/arch-kiosk-office#2270]
Query and View is not behaving as I expect it to following this update. Testing on the local demo server.
Querying for materials in loci tagged "Bob" returns nothing. Looking in FM in tag analysis gives me three things that should show up as CM from loci tagged Bob.

_Originally posted by @lbestock in https://github.com/arch-kiosk/arch-kiosk-office/issues/1961#issuecomment-1712663406_

**Comment by luizaogs** [comment]
I'm having the same thing in PVD as well after the update (1.5.10.3). Looking up the tag "nightstand" in query and view gives me no materials, but in FM I get several. I am also getting the following message in Kiosk when trying to run a Q&V search: 

<img width="1486" alt="Screenshot 2023-09-17 at 3 56 49 PM" src="https://github.com/arch-kiosk/arch-kiosk-office/assets/67970402/0648ff7f-1f1d-4f8c-a120-52d063b468af">

**Comment by urapadmin** [comment]
ja, query and view is not in good shape, currently...

**Comment by urapadmin** [comment]
but this has definitely nothing to do with the Flask update.

**Comment by urapadmin** [comment]
after I solved #2313 this should work, but it appears the query itself is also flawed.

**Comment by urapadmin** [comment]
Tested this and it works now. I get results for the nightstand.
I don't get results for "S800 Brassil Park Rest Area" although a locus with a collected material is tagged with it. Reason: The collected material has not material. And since the query is listing materials and collected material types, I accept that as a correct omission.
