### ISSUE TITLE
file sequence import:  logged in user is not being used when adding a file

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#2271]

**Comment by urapadmin** [comment]
### Kiosk 1.5.9.2
- logged in user should be used for file sequence import

**Comment by urapadmin** [comment]
tried this in USTP: Worked

**Comment by lbestock** [comment]
Not sure if this is the same thing, but I have an unexpected user again in the Director's View so I ask the question.

We imported a bunch of photos for BUAP. (@urapadmin did that via a local upload)
I am assigning them contexts in the file repository as I digitize old paper notes.
Once I do that they show up in the Director's View for the day the context itself was assigned. That is clearly catching the assignment of the context and thus the moving of the image into the recording, and this is what I would expect and want - it helps me use Director's View to have a view on what the legacy input team is doing. And the time stamp in Director's View addresses the time of the image being given a context, I believe. But it says admin did it, not that I did it, though I was logged in as myself to Kiosk.

**Comment by urapadmin** [comment]
so this did not happen during the import but during setting the context within the file edit dialog?

**Comment by lbestock** [comment]
Correct.

**Comment by urapadmin** [comment]
That's a different issue then: #2457
