### ISSUE TITLE
Kiosk User management: upcase repl user

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#2272]
as we are automatically up-casing the user id in FileMaker we have to do the same thing for the repl-id of the Kiosk User as that one is supposed to match the FileMaker user id exactly.

**Comment by urapadmin** [comment]
### Kiosk 1.5.10.3
- when adding a new user or saving an existing user in Kiosk the repl_id will automatically be upper cased. 
- only once we will uppercase all existing repl_ids, although that's kinda dangerous. But I do it anyways.

**Comment by luizaogs** [comment]
Works.
