### ISSUE TITLE
how to get images from Kiosk to the server

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#2278]
We don't really have a mechanism to transport an image to the recording app that works out of the box. Images that are not connected to a context do not travel to the recording app's gallery. The solution is file picking: All projects should include images that are tagged something that makes sure the images gets transported.

That way it would be possible to transport a site map to an iPad so that it can be attached to a site or to whatever.

**Comment by urapadmin** [comment]
This does not really need software but rather some sort of policy. All projects should have that file picking rule by default.

**Comment by urapadmin** [comment]
and then it needs an explanation to users as this is never really intuitive

**Comment by urapadmin** [comment]
for arch1900 I will just add a file picking rule that transports everything tagged as "map", too.

**Comment by urapadmin** [comment]
- #2288 has made this feature available to all projects and the official way to go about it. 
@arch-kiosk/test Anybody want to make a video tutorial on it or write something in the manual?

**Comment by luizaogs** [comment]
I can, but I don’t have a fancy recording studio. I can at least add it to the Q&A. Would it be just for admins? And this is recommended for maps only, yes?

**Comment by urapadmin** [comment]
Q&A for all I‘d say, can‘t hurt that users know about it. Let‘s hope field directors ever look into that manual, too. Manuals. I don‘t have good answers on that front.

**Comment by luizaogs** [comment]
done
