### ISSUE TITLE
sequence file import buggies

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#2281]
- [x] it seems to got through folders although scan subdirectories is off. Or rather it seems to count them at least. So I had a bunch of subfolders and the thing kept counting. Once I moved them away it did not happen again.

- [x] the logs do not actually show properly what image started or stopped a sequence until I look at debug messages. But that makes it harder. So make the logs more useful!

- [x] The checkbox "scan subfolders" always defaults, so it is not remembering the last user setting

**Comment by urapadmin** [comment]
### kiosk 1.5.10.3
- all three problems should be solved

**Comment by lbestock** [comment]
All three problems are solved!
