### ISSUE TITLE
ton import: "day" key missing or so when importing from folder names with the date

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#2282]
I ran the ton import taking the context from the folder name. All of the files threw an error because a key "day" was missing somehow. First: The get date from folder option should not be on by default and Second if it does not work I don't think it should throw errors.

**Comment by urapadmin** [comment]
### Kiosk 1.5.10.3
- by default "date" is not taken from operating system file folder anymore
- if it is checked, files that do not have a date, or worse: Files that have an incomplete date in them should not lead to the error anymore

**Comment by luizaogs** [comment]
Now that I have a local server I can test this, but just to make sure I understand: I am supposed to run ton using folder name and it should work normally? Then I try it again with the option to get the date from the folder too, and that should also work? How do I tell if the file has an incomplete date? (Sorry, probably a dumb question.)

**Comment by urapadmin** [comment]
More important: You are not supposed to test with your local server when it is your live server 😱

**Comment by luizaogs** [comment]
Ha I mean, I’m importing images daily anyway so was just going to use the folder name method… I did not think this was some crazy testing that could yield poor results.

**Comment by urapadmin** [comment]
I had to restore a USTP this year because of the ton import (admittedly that was a crazy case) and so there is a good reason for the old rule: Never test on live systems. 
But my plan was to ask you to keep ThinkPad as a test local server after the season. We don't really need it and that would it possible for you to test things about the server itself. In Hillside I am administering the local test server and that does not really count as a test when I do it myself. 
So let's keep it for after the season, ja?

**Comment by luizaogs** [comment]
yes sir

**Comment by luizaogs** [comment]
> Now that I have a local server I can test this, but just to make sure I understand: I am supposed to run ton using folder name and it should work normally? Then I try it again with the option to get the date from the folder too, and that should also work? How do I tell if the file has an incomplete date? (Sorry, probably a dumb question.)

Alright, so how do I do this?

**Comment by urapadmin** [comment]
- first of, all the folder import filter should not have "date" on by default 
- if it is on, the import should not throw an error if there is no discernible date in the folder name. So, if you have a folder "stuff", the folder filter's date option is on and the import finds a file in that folder and gets the date (and perhaps its identifier) from the file itself (having the options in the file filter on), the file should be imported and not throw an error. As a reminder I always need myself: The folder filter gets a file's date from the filename, the file filter gets a file's date from the operating system's data of the file. 
- If you have a folder "stuff", the folder filter's date option is on and the import finds a file in that folder and **doesn't get a date at all** from that file (having all other options to get a date set off), the file should be imported and not throw an error.

**Comment by luizaogs** [comment]
Ok I'm trying to set up the test import and I can't find this anywhere, which means that I have probably just missed it: what format should the date be in the filename?

**Comment by urapadmin** [comment]
> Ok I'm trying to set up the test import and I can't find this anywhere, which means that I have probably just missed it: what format should the date be in the filename?

Did the log not tell you anything or you could find it by tag, which should always be possible? 
The date can be a latin date like 02 IV 2023. Not as sophisticated as our current iteration of the date parser in your version, though, so don't try to leave the leading 0 out or using a two digit year.

**Comment by luizaogs** [comment]
Oh I haven't run the import yet since I didn't want to mess up the date format. I'll do it today.

**Comment by urapadmin** [comment]
I see. Ja, we just used the latin date for BUAP and that worked.

**Comment by luizaogs** [comment]
Worked.
