### ISSUE TITLE
bunch import: tags are correctly assigned but not queried by

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#2283]
I made a bunch import and assigned the tag "Room 48". It all worked fine but in the file repository it selected the tag "Room 4". Odd.

**Comment by urapadmin** [comment]
### Kiosk 1.5.10.3
- this was the same for bunch and ton and should not happen anymore

**Comment by luizaogs** [comment]
Worked with bunch. If ton needs to be tested as well I guess @lbestock it's yours

**Comment by urapadmin** [comment]
it doesn't. They share that code
