### ISSUE TITLE
Configuring volume and weight in collected material is hard

### ISSUE THREAD

**Issue by lbestock** [arch-kiosk/arch-kiosk-office#2285]
CM type sample has two labels on top of each other (volume and weight?) making it illegible.
Noticed in checking MKAP, not sure if universal.
![image](https://github.com/arch-kiosk/arch-kiosk-office/assets/49291909/2c84e747-51be-4bbb-a59b-a3369e73c83b)

**Comment by urapadmin** [comment]
that is a configuration issue. You have to decide between volume and weight

**Comment by urapadmin** [comment]
is this done?

**Comment by lbestock** [comment]
Yes, but the configuration confused me for a long time so I expect I will ask this again when next I configure a system.

**Comment by lbestock** [comment]
What it turned out to be (should I be able to find this ticket again next time I have this issue):
"show_volume_for_cm_type" was set to sample.
"show_volume_for_material" was set to soil.
"hide_weight_for_materials" was set to soil.

For all samples OTHER than soils, weight and volume both popped up and got confusing. For MKAP what needed to happen was to turn off the "show volume for CM" key so that samples in general were not given volumes, which only applies to soil (though that's really a USTP thing, but at least it was now a defined choice and not an accident.)

**Comment by urapadmin** [comment]
since we'll never have weight and volume at the same time I guess it should be possible to make volume the opposite of weight, so that at least the "hide_weight" would not be necessary (except when you want to hide the weight even though there is no volume). I'll keep this open and give it a meaningful title.

**Comment by urapadmin** [comment]
it is a bug. the labels don't behave the same way as the input fields.

**Comment by urapadmin** [comment]
### recording app 15.4.2
I have not had any idea how to simplify this. We have encountered all these options in different projects and so I just made it at least bug-free, or so I hope:

**Comment by luizaogs** [comment]
Looks ok now.
