### ISSUE TITLE
Director's View formatting: wrong term for locus in files widget

### ISSUE THREAD

**Issue by lbestock** [arch-kiosk/arch-kiosk-office#2286]
I am having deja vu so it's quite possible this exists already...
Director's View testing for MKAP I noticed that the "Files" section uses the wrong term for locus. The locus widget uses the right term. (In this case, it should be SU rather than locus). 
![image](https://github.com/arch-kiosk/arch-kiosk-office/assets/49291909/772cf9e5-eb74-41f8-87dd-f6222630745a)

**Comment by urapadmin** [comment]
That is foremost a configuration issue. Then we'll see. It is possible that the director's view is not perfect on that front.

**Comment by urapadmin** [comment]
so this was a config error and can be closed, right?
