### ISSUE TITLE
add the file picking rule that transports images tagged as "map" as a general rule

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#2288]
this rule allows projects to transport files to the recording app that are not yet linked to a context

**Comment by urapadmin** [comment]
not sure where to do that, though

**Comment by urapadmin** [comment]
### Kiosk 1.5.10.3
- added a migration script that inserts two file picking rules for the 'default' port: 
  - The default "contextuals" rule with order 0: 'contextuals' -> low
  - a tag rule with order 10: TAG IN 'map' -> low

**Comment by luizaogs** [comment]
In PVD we currently have contextuals (order 0) = dummy rather than low. Not sure if that conflicts with this, but I don't see a contextuals = low of order 0.

<img width="1480" alt="Screenshot 2023-09-17 at 1 11 06 PM" src="https://github.com/arch-kiosk/arch-kiosk-office/assets/67970402/04894ff7-cef8-4e96-8dc5-597d5eecf005">

**Comment by luizaogs** [comment]
MCP appears to be down so I can't test if my map got to my recording system. Help.

**Comment by urapadmin** [comment]
arg

**Comment by urapadmin** [comment]
I forgot. Now it is back.

**Comment by urapadmin** [comment]
and I already see that PVD is on an older template version. I'll fix that right away ...

**Comment by urapadmin** [comment]
done

**Comment by luizaogs** [comment]
Hmm. Is there an easy way to find the "map" in the image gallery after file picking? Because I can't search for it with no context.

**Comment by luizaogs** [comment]
Though wait actually, there isn't all that much in the gallery because of file picking. And I don't see it in there.

**Comment by urapadmin** [comment]
ja, I can confirm that it did not make it to the fm database.

**Comment by urapadmin** [comment]
> Hmm. Is there an easy way to find the "map" in the image gallery after file picking? Because I can't search for it with no context.

yes, when you search in the gallery, file tags are searched, too. Provided the image is there (grr).

**Comment by urapadmin** [comment]
meanwhile I have installed this on PVD (and I even remembered to restart MCP, yeah). The version is not up because this did not need any changes in the code.

On MKAP I have fixed it manually and tested.

**Comment by luizaogs** [comment]
I can see the map now. Is the contextuals thing I mentioned above ok? If so this can be closed.

**Comment by urapadmin** [comment]
if we really already had a contextuals / dummy before this got installed, it would not have replaced it. It should have only added a rule for the default FileMakerWorkstation order 0 if there isn't already one.

**Comment by luizaogs** [comment]
I THINK we did, but my memory isn't that good. I'm not sure. Can you update another Kiosk so I can check there?

**Comment by luizaogs** [comment]
Wait you already released it. Let me see.

**Comment by luizaogs** [comment]
Hm. I checked PACHA and URAP and neither has the contextuals 0 = low rule. And they don't have other contextual rules of order 0, either. They both have the map rule.

**Comment by urapadmin** [comment]
ja, sorry, I actually made it a bit smarter and forgot about it:
the contextuals=low is NOT added if there is either a rule with order 0 OR a contextuals rule on a different level within the FileMakerWorkstation/default path.
That's why it was not added to URAP or PACHA or in fact any of our current projects because they all must have a contextuals rule already. It is more targeted towards new projects where one tends to forget the initial rule. I'll delete it and run it again on PVD as a final test...

**Comment by urapadmin** [comment]
looks good
