### ISSUE TITLE
file manager not accessible?

### ISSUE THREAD

**Issue by luizaogs** [arch-kiosk/arch-kiosk-office#2289]
I might be going crazy, but wasn't/shouldn't the file manager be accessible from the hamburger menu in administration? (I realized this might be an issue when I tried to find the file for my test back up.) I don't see it currently and I also do not see another way to get to it. This is in PVD with the new Flask version.

**Comment by urapadmin** [comment]
you are not going crazy and you found the first issue that is actually related to the Flask update. Congratulations!

**Comment by luizaogs** [comment]
🤯

**Comment by urapadmin** [comment]
### Kiosk 1.5.10.3
- file manager should be back
