### ISSUE TITLE
housekeeping warning does not disappear after housekeeping

### ISSUE THREAD

**Issue by luizaogs** [arch-kiosk/arch-kiosk-office#2290]
Should it? 

I restored PVD and then Kiosk told me that a restore was needed -- fine, did that. I expected the warning to then disappear and it did not. Not sure if it should.

**Comment by luizaogs** [comment]
If I exit out of it it stays gone.

**Comment by urapadmin** [comment]
no, it does not. Those messages are like E-Mails. Once sent they have to be confirmed by somebody. It is the same with the "MCP is not up" message. It stays unless it is explicitly closed even if MCP is up meanwhile.
