### ISSUE TITLE
docks and workstations: typology confusion?

### ISSUE THREAD

**Issue by luizaogs** [arch-kiosk/arch-kiosk-office#2291]
I assume you know this but while we now use the term dock (and that's what shows up in the hamburger menu when creating a new one), the menu items in the docks themselves (renew, edit, etc.) all mention "workstations". Purposeful? Not important? Don't know, so I point it out.

**Comment by luizaogs** [comment]
Ah "workstations" is also used in the hamburger menu for prepare all, import all, etc.

**Comment by luizaogs** [comment]
(I have a vague recollection of seeing you mention this in a ticket before...)

**Comment by urapadmin** [comment]
ja. well. One day we should perhaps call everything dock. Currently it is more like this: A FileMaker workstation is a type of dock. So when we call something a workstation we mean usually a device running FileMaker. When you create a dock it isn't clear what kind of dock you are creating as it could be a FileMaker Workstation or a report or a FileExport dock etc. 

When you click on a dock that is a FileMaker Workstation things are called FileMaker Workstation as well. 

So it isn't as incoherent as it seems on first glance and so I postponed that renaming party to a more distant future (when I just get rid of FileMaker docks entirely).

**Comment by luizaogs** [comment]
Aaah ok. I did remember this - that was the vague recollection. Well. Ignore me.

**Comment by urapadmin** [comment]
only in this instance at this time

**Comment by luizaogs** [comment]
If you say so :)
