### ISSUE TITLE
double login required after restarting

### ISSUE THREAD

**Issue by lbestock** [arch-kiosk/arch-kiosk-office#2292]
Whenever I restart on a local server I must log in again. That I expect.
But then when I try to go to administration to run housekeeping I invariably get the warning that Kiosk is unwell and I need to login again. And I do login again and then it's fine and I can run housekeeping. But it is always somewhat disconcerting that I need to log in twice, and once is after I have logged in and then I see a nasty message. Is it indicative of something more sinister?

**Comment by urapadmin** [comment]
is that connected to restoring stuff?

**Comment by lbestock** [comment]
Yes.

**Comment by urapadmin** [comment]
the it is okay. Restore really needs a complete server restart to work properly. Only a test issue.
