### ISSUE TITLE
matrix field labels getting cut off

### ISSUE THREAD

**Issue by luizaogs** [arch-kiosk/arch-kiosk-office#2293]
An easy but probably annoying ticket for you. My specialty!

Looking at configured MKAP before this tutorial and I see that the labels for inclusions and composition in the matrix tab are getting cut off by the text boxes.

<img width="1021" alt="Screenshot 2023-09-18 at 6 56 25 AM" src="https://github.com/arch-kiosk/arch-kiosk-office/assets/67970402/b11a7317-9cd7-48c1-8dd6-55a8cb322fc6">

**Comment by urapadmin** [comment]
what is this? an iPad? iOS version?

**Comment by luizaogs** [comment]
Mac. I can look up the version when I get back home, if you need it.

**Comment by urapadmin** [comment]
Not in that case

**Comment by urapadmin** [comment]
### recording 15.4
should be fixed
