### ISSUE TITLE
bugs and features screen has red box in it

### ISSUE THREAD

**Issue by luizaogs** [arch-kiosk/arch-kiosk-office#2294]
Your second small but annoying ticket of the day. Still in configured MKAP. The bugs and features screen (does anyone actually use that instead of Github?) has a small red box towards the bottom. 

<img width="1026" alt="Screenshot 2023-09-18 at 7 06 56 AM" src="https://github.com/arch-kiosk/arch-kiosk-office/assets/67970402/d6d1e114-9476-446a-83f8-e46d7c84fbc0">

**Comment by urapadmin** [comment]
to my knowledge nobody has been using it. And we have not encouraged it. It is still a valid tool to be used in the trench, where GitHub is not an option and once you are back from the field you won't remember any details anymore.

**Comment by urapadmin** [comment]
### recording 15.4
- should be gone for non-developers
