### ISSUE TITLE
test: iOS 17 and FM GO 19 / 2023

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#2295]
iPadOS 17 is out. We need to test it. Please test with FM Go 2023 in particular as that will be our recommended platform in the near future.

**Comment by luizaogs** [comment]
Will do this soon.

**Comment by urapadmin** [comment]
@lbestock has started it, too. What you guys should focus on in particular is the bloody image containers. That's where I always expect new trouble.

**Comment by luizaogs** [comment]
I tested everything I could possibly think of and only had a couple of issues. Those have their own tickets.

**Comment by urapadmin** [comment]
I close this, I think we have not really found anything worrisome.
