### ISSUE TITLE
image counter showing up in collected material images

### ISSUE THREAD

**Issue by luizaogs** [arch-kiosk/arch-kiosk-office#2296]
Testing #2295 but I don't know if this has anything to do with the new iOS. I'm adding pictures to a new bulk and realized that there is an image counter showing up in the images after they have been added (on the upper right of the image, as you can see below): 

![IMG_9AFBFADF1B2C-1](https://github.com/arch-kiosk/arch-kiosk-office/assets/67970402/1bec7075-25f3-47cd-a14f-ba48d83f2ce7)

So far I've only seen it here and I've also tested image containers in units and loci.

**Comment by luizaogs** [comment]
Same issue in small finds and sample photos.

**Comment by urapadmin** [comment]
### recording app 15.4
- that must be superfluous. Strange that it surfaces only now. It is the same image list for all cm types.
