### ISSUE TITLE
site note image issue (?)

### ISSUE THREAD

**Issue by luizaogs** [arch-kiosk/arch-kiosk-office#2297]
Testing #2295 and noting this before I forget, so it might not be an issue - I need to see if I can repeat it first.

Anyway, for documentation's sake: 

Added an image to a site note by taking a photo, worked fine. Added another image container and took another photo. After taking the photo, not only did it not appear in the image container, it also led to an empty image container below where before my previous image had been. So I ended up with this: 

![IMG_BF9F2C5F154F-1](https://github.com/arch-kiosk/arch-kiosk-office/assets/67970402/0d188480-36ab-4efd-aab0-9460e67566ec)

**Comment by luizaogs** [comment]
Clicking in the gray area below the image containers does not bring them back, neither does clicking anywhere on the screen.

**Comment by luizaogs** [comment]
Ah. Even better: I just clicked on the site note below, which before had two proper images, and now those containers are blank as well.

**Comment by luizaogs** [comment]
Clicking on the purpose and site map tabs and coming back also does not bring them back.

**Comment by luizaogs** [comment]
But leaving site notes and going to the home screen, and then coming back brings all of them images back.

**Comment by luizaogs** [comment]
Adding a third image worked just fine. As did adding a fourth, so I'm not sure what happened here.

**Comment by urapadmin** [comment]
@lbestock 
Can you provoke this on your ipad?

Luiza: You are on FM Go 20 (2023) and iOS 17?

**Comment by luizaogs** [comment]
Yup.

**Comment by lbestock** [comment]
I cannot provoke this. I just added four pictures of Bob cleaning his butt while lying on my feet all in a row, no problem at all. Surprisingly fast and non-flickery, I would even have said.

**Comment by urapadmin** [comment]
that's how we love our filemaker

**Comment by lbestock** [comment]
I'm even on my own iPad here so I have seven zillion apps open, which was usually a problem in the past.

**Comment by urapadmin** [comment]
> I'm even on my own iPad here so I have seven zillion apps open, which was usually a problem in the past.

although according to all the tutorials I've been through while sick, it should never have had an influence. Theory and practice!

**Comment by urapadmin** [comment]
so, it is on you, @luizaogs to reproduce this in a way that seems to make it more likely or call and close it as a hiccup.

**Comment by urapadmin** [comment]
(being a tester is such a shitty job. Who would have thought that :o))

**Comment by luizaogs** [comment]
> > I'm even on my own iPad here so I have seven zillion apps open, which was usually a problem in the past.
> 
> although according to all the tutorials I've been through while sick, it should never have had an influence. Theory and practice!

You were sick too? Meh. I hope you're feeling better!

**Comment by luizaogs** [comment]
Can't reproduce it either, of course. Nice.
