### ISSUE TITLE
PASU ceramics: creating new sherd opens pinboard

### ISSUE THREAD

**Issue by luizaogs** [arch-kiosk/arch-kiosk-office#2298]
Still testing #2295 

In PASU ceramics, if I create a new sherd by clicking on the little ceramic vase and picking a find number, and say I want to start processing for that number by clicking "yes," then add a fragment with the + button, I get the pinboard popping up automatically: 

![IMG_0355](https://github.com/arch-kiosk/arch-kiosk-office/assets/67970402/90e331c1-f422-44e6-9925-76c5ec0b32a0)

I had something pinned.

**Comment by luizaogs** [comment]
If I clear the pinboard it disappears. 

If I have a cleared pinboard and go through that entire process again, the pinboard does not show up.

**Comment by urapadmin** [comment]
### recording 15.4
that's a weird one and I am not sure what caused this. That might be really a weird new behaviour in FM 20.
However, I found a bug that had nothing to do with it and eliminated the field order and now it seems to be gone.

**Comment by luizaogs** [comment]
'Tis gone.
