### ISSUE TITLE
collected material: change the collected material type. 

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#2299]
Coming out of arch1900:

> Is it possible to convert a small find bag into a bulk find bag later on? A few times yesterday students would start off a collection as a small find but then find multiple fragments and want to switch to a bulk find. The only way I knew how to do that was to start over with a bulk find bag and delete the small find file. Is there a way to do this without having to delete?

Particularly "switching" between bulk <-> small find might indeed make some sense every now and then. It isn't trivial because of numbering functions that are bound to the cm_type. 

It could make sense, anyhow, to add changing the cm_type to temporary free input (renaming).

**Comment by urapadmin** [comment]
No, renaming is not the right way to go about it. It is more complicated because changing the cm type is not only about changing the cm_type field. It also means dropping or adding a detail record. When changing from small find to bulk the small find record would have to be dropped - which can mean data loss - something we don't like. Well, I could preserve the data record and only add a new detail record if there isn't already one.

**Comment by urapadmin** [comment]
### recording app 15.4
So this is how it works:
- there is a new button between the temporary free input and rename button. It should only be visible for registrars
- when clicked it allows you to select a new cm type
- when you hit okay it changes the cm type of the current collected material and leaves the layout the same way it would if the user hit the back button
- if you switch from bulk to small find it is necessary to create a small find detail record. Otherwise the small find detail tab would not be clickable in the cm layout. 
- if you switch a certain cm from small finds (with some small find data entered) to bulk and then enter the collected material layout, the tab with the details should not be clickable
- same cm: if you switch back to small find and enter the cm layout again the tab should be visible again and the data that was previously entered when the cm was already a small find. That way I prevent users from losing data because of an accidental switch of the cm type.
- There are two new configuration settings involved:
  - "labels/label_cm_type": default is "collected material". It determines the text in the pop-up for changing the cm type.
  - "visibility/show_change_cm_type_warning": default is "yup" although for many projects it should be "nope". If this is "yup" the pop-up warns that after changing the cm type the user must check if the identifier is appropriate for the cm type. If that is not the case temporary free input / renaming is necessary to mend that. For projects that have the same numbering strategy for all cm-types it does not matter and can be changed to "nope".

**Comment by luizaogs** [comment]
> * if you switch a certain cm from small finds (with some small find data entered) to bulk and then enter the collected material layout, the tab with the details should not be clickable

The tab isn't even visible. Is that correct?

**Comment by luizaogs** [comment]
> * "visibility/show_change_cm_type_warning": default is "yup" although for many projects it should be "nope". If this is "yup" the pop-up warns that after changing the cm type the user must check if the identifier is appropriate for the cm type. If that is not the case temporary free input / renaming is necessary to mend that. For projects that have the same numbering strategy for all cm-types it does not matter and can be changed to "nope".

This key doesn't seem to be working. I get the warning whether I have "yup" or "nope" in there.

**Comment by luizaogs** [comment]
Also hehe a typo. Should be "alerts"

![IMG_0356](https://github.com/arch-kiosk/arch-kiosk-office/assets/67970402/3e271d87-d37c-4c1b-a008-b831eb60f883)

**Comment by luizaogs** [comment]
The rest of this is working.

**Comment by urapadmin** [comment]
> > * if you switch a certain cm from small finds (with some small find data entered) to bulk and then enter the collected material layout, the tab with the details should not be clickable
> 
> The tab isn't even visible. Is that correct?
> 
> Ah I suspect that is correct after having read the next bullet point.

correct

**Comment by urapadmin** [comment]
### recording 15.4.1
- typo eradicated
- key should be working now

**Comment by urapadmin** [comment]
@arch-kiosk/test: who wants to add instructions to the user's manual?

**Comment by luizaogs** [comment]
I can do it later today, though I don’t know project specifics so would talk about renaming more generally.

**Comment by luizaogs** [comment]
Done.

**Comment by urapadmin** [comment]
Thanks! And it is published.
