### ISSUE TITLE
locus sorting: date opened does not look right

### ISSUE THREAD

**Issue by luizaogs** [arch-kiosk/arch-kiosk-office#2306]
When first opening the database, the locus sorting is automatically done by date opened, which makes sense. However, the list looks super weird for some reason (see screenshot). They are not in order either by date or within dates themselves. Not sure if this is due to modification times or something, but if it's how it's supposed to look like can we make the default the sorting by SU identifier instead? That one is much more intuitive. 

![IMG_0362](https://github.com/arch-kiosk/arch-kiosk-office/assets/67970402/dcd08f24-85af-4ec3-8883-da94c07e0abc)

**Comment by luizaogs** [comment]
(You obviously don’t need to patch it for this season, it’s not a big deal. Noting it for the future.)

**Comment by urapadmin** [comment]
I would want to look at that database. I suppose with weird you mean that you would have expected the loci to appear in the order of their identifiers when being ordered by date. So would I and that's why I'd like to look at that database.

**Comment by luizaogs** [comment]
Ok. How do you want me to get it to you?

**Comment by urapadmin** [comment]
if you can log in to google drive, why not just dump it there: under Kiosk Shared Files\MKAP?

**Comment by urapadmin** [comment]
but I suppose we can also simply wait until MKAP is back online.

**Comment by luizaogs** [comment]
You can definitely wait :) I just thought it sounded like you wanted this specific file ha.

**Comment by urapadmin** [comment]
no, I think that won't be necessary. Let's hope MKAP will return to the online server in time (that is not always the case with these users)

**Comment by luizaogs** [comment]
I’ll make bloody sure it does…

**Comment by luizaogs** [comment]
In case you are bored with Q&V (ha ha): I've added a recent MKAP database to the Google Drive. Just because I had to airdrop it to my Mac anyway to write the excavation report more easily just now, so I figured why not. But Didi will put it back online once she is back.

**Comment by luizaogs** [comment]
Ja this is still super weird for some reason, as I was reminded when testing the harris matrix for AA.

**Comment by urapadmin** [comment]
### recording app 15.10.1
- should be better now

**Comment by luizaogs** [comment]
Can you release this for MKAP so I can test it there, since it was where I first noticed it? PVD is such a mess that I can't really tell what is going on. Or is updating MKAP a problem?

**Comment by urapadmin** [comment]
we have to finish #2415 first. Then I can update MKAP's Kiosk and Recording App together.

**Comment by luizaogs** [comment]
Ok. #2415 is good now I think so I will wait for the MKAP update for this.

**Comment by urapadmin** [comment]
MKAP is updated now

**Comment by luizaogs** [comment]
Looks good.
