### ISSUE TITLE
Q&V: New "go to" toolbar box

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#2322]
we need an easy way to open a new view for an identifier without going through a query.
A new combobox in the toolbar should do that. We also might need an api that sends both, the identifier and the record type. I am not sure if the current api that the file repository is using does that.

**Comment by luizaogs** [comment]
I think this can also be closed? (Trying to clean up a bit for you…)

**Comment by urapadmin** [comment]
yes, that has been used and works
