### ISSUE TITLE
khpp: "insert qr code substitute" is available but shouldn't

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#2327]
old configuration. I am suprised that one still even does anything.

**Comment by urapadmin** [comment]
it should in fact really be removed from the recording app

**Comment by urapadmin** [comment]
### recording 15.19.2
- kicked the whole thing off the image pop-over in dayplans (simple excavating, features and survey units)
- so, not matter what you set the already obsolete keys "show_insert_qr_code_substitute" and "use_qr_code_substitution" to, no button should appear in the pop-over. (And don't ask me why there were two different keys!)

**Comment by luizaogs** [comment]
show_insert_qr_code_substitute doesn't seem to exist anymore. But this looks fine.
