### ISSUE TITLE
mkap: local server to online server transfer

### ISSUE THREAD

**Issue by luizaogs** [arch-kiosk/arch-kiosk-office#2328]
MKAP's season ended today and Didi will be back in Chicago soon. She will want to transfer the database online once she is back, so I figured I would ask you Lutz how to do it now. I know that there's now a "transfer" button in admin but #2206 makes me think she will also need some specific files (as well as instructions).

**Comment by urapadmin** [comment]
yes, the transfer button does not work entirely automatically, it needs some input from me.
I'll send instructions later this week.

Note that transferring makes most sense once you have finished (most of) the image imports from the SLR.

**Comment by luizaogs** [comment]
Yep, that should be done already.

**Comment by urapadmin** [comment]
instructions sent via email

**Comment by luizaogs** [comment]
Thank you!
