### ISSUE TITLE
MADP: Logo & Color Scheme

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#2336]
MADP should have a logo and a color scheme. I usually use the logo as a starting point for a color scheme.

**Comment by urapadmin** [comment]
The first logo we got:
![279126422-670404f8-25f6-4581-8fc7-3662a5069464](https://github.com/arch-kiosk/arch-kiosk-office/assets/38838314/e1342993-37f7-46bd-aec2-dd690bad4cbe)

**Comment by urapadmin** [comment]
does not give me color clues (not so important) but also does not shrink well:
![279190116-774cb781-c4ef-404f-8ad2-d9cb94c2026b](https://github.com/arch-kiosk/arch-kiosk-office/assets/38838314/b8c14fcb-5ad3-4ed9-b02b-c1d6d09887a4)

We need something that can be shrunk to the range of 120px X 80px. I would suggest to use the Acronym instead of the full name in the logo (the full name is on the screen anyhow).

**Comment by urapadmin** [comment]
There it want to go:
![image](https://github.com/arch-kiosk/arch-kiosk-office/assets/38838314/dacd0df5-e7d6-48b6-9a77-a5a7f355eda1)

**Comment by luizaogs** [comment]
Maarten was going to figure that out. Were you able to add them to Github?

**Comment by urapadmin** [comment]
yes, both are invited and ``inesctorres`` has accepted

**Comment by luizaogs** [comment]
Is this better?

![WhatsApp Image 2023-11-07 at 07 23 51](https://github.com/arch-kiosk/arch-kiosk-office/assets/67970402/ad428c9f-008b-4616-a26b-147a032d6d5a)

**Comment by luizaogs** [comment]
Hang on hang on we changed it again (we're indecisive people)

**Comment by luizaogs** [comment]
![WhatsApp Image 2023-11-07 at 07 59 29](https://github.com/arch-kiosk/arch-kiosk-office/assets/67970402/edc2cfd1-d9a4-495c-80d8-458bb96c4dca)

**Comment by urapadmin** [comment]
Judge for yourself (it is the old version the result will be the same):

![281095508-ad428c9f-008b-4616-a26b-147a032d6d5a](https://github.com/arch-kiosk/arch-kiosk-office/assets/38838314/834a1682-408f-4fb3-a0fe-6a0f76e4a3e3)

As long as it is a 1500x1200 bitmap reducing it to 100x90 or so with very thin lines on a white background has the inevitable result of looking like a ghost. It would need someone to trace those lines with a thicker pen or something like that. And if you do that: Make an SVG because then the scaling won't be a problem ever again AND the image would be transparent and could be put on a coloured background as well.

**Comment by urapadmin** [comment]
but if you think it is good enough - technically I could use this now.

**Comment by luizaogs** [comment]
Hmpf definitely still looks awful but neither of us has the time to trace it and turn it into an SVG right now so you can use that. So we can keep this open and we will work on it and send you a new version during or after the season (knowing that you won't be able to change it until we get back).

**Comment by urapadmin** [comment]
oops. Forgot the hyphen.

**Comment by luizaogs** [comment]
Oh yeah that looks better!

**Comment by urapadmin** [comment]
![madp_logo](https://github.com/arch-kiosk/arch-kiosk-office/assets/38838314/e0752391-7f04-4ad5-b8a9-131d21d418cf)
Let's try this. I am afraid, I could not resist to use some colour.

**Comment by luizaogs** [comment]
Ah it's my favorite blue!

**Comment by urapadmin** [comment]
rolled out to demo.arch-kiosk.brown.edu.
The browser-cache might keep you from seeing it, so ctrl+f5 on windows and whatever it is on Mac will help.

**Comment by luizaogs** [comment]
Ooo I like it! Thank you :)

**Comment by urapadmin** [comment]
it is very blue, depending on one's display 😃

**Comment by luizaogs** [comment]
The exact shade of blue I requested, too :)

**Comment by luizaogs** [comment]
So I think actually this is good to go? If we end up tracing the logo/changing it for publication purposes in the future I can send it to you, but I think your solution worked well and looks good.

**Comment by urapadmin** [comment]
ja, it is possible that you might run into contrast issues somewhere (some reds on blue can be challenging). In that case please file a bug report. It is always helpful for me to find the places where colour schemes are challenging.
