### ISSUE TITLE
Kiosk: new user setting password needs to warn you if you mistype

### ISSUE THREAD

**Issue by lbestock** [arch-kiosk/arch-kiosk-office#2338]
When one is a new user and is prompted to set and then retype a password in Kiosk, if the two passwords are not typed the same then it just closes the popup and says "authentication failed". And if you try that user ID again with no password, it says again "authentication failed" - so you are stuck and cannot set a password.

It should rather, if the two are not the same, alert you to this and prompt you to fix it without kicking you out of the password setting popup.

I discovered this tiny treat when mistyping my own on setting up MADP.

**Comment by lbestock** [comment]
No one has apparently run into this in real life yet, so not totally critical. But it also shouldn't be forgotten about.

**Comment by urapadmin** [comment]
I cannot reconstruct this properly. I get a message that the passwords must match.

**Comment by urapadmin** [comment]
please try to reconstruct

**Comment by urapadmin** [comment]
what browser and device are you using?

**Comment by lbestock** [comment]
I was almost certainly using my Mac and Chrome - that was during an actual attempt to set up a real Kiosk. However I am not able to replicate this myself any longer - now it behaves as I expect it to. Great.

**Comment by urapadmin** [comment]
then I close this for now. I have a hunch what happened. Chrome has this stupid feature to go back on the page when you select something with a swipe from right to left. That might have tripped you up.
