### ISSUE TITLE
FM: configuration key "ceramic_module" does not synchronize

### ISSUE THREAD

**Issue by lbestock** [arch-kiosk/arch-kiosk-office#2339]
Setting up MADP and thought I would give them some URAP pottery processing. Changed configuration key to pottery_processing, made a record to make sure that the proper warecode module showed up and it did. But that configuration did not survive synchronization; it was reset to su_ceramics_processing.

**Comment by urapadmin** [comment]
ah. That one! Ja, that does not synchronize, indeed. It is not meant to be changed in a running project (makes some sense, you would never want to switch from warecode pottery to PASU-style processing). But it makes configuration much harder, so I guess I better allow this to synchronize.

**Comment by urapadmin** [comment]
but there is a configuration key that hides the main ceramic module: "hide_main_ceramic_analysis". There are so many 🥴

**Comment by urapadmin** [comment]
in future the setting for ceramic_module will synchronize.
