### ISSUE TITLE
q&v: clicking on an identifier while in a query only shows me the identifier view once I close the query results

### ISSUE THREAD

**Issue by luizaogs** [arch-kiosk/arch-kiosk-office#2345]
Pretty self explanatory title. When clicking on an identifier in the result list from a query, I only get the identifier window to show up once I actually close the query window. 

Click on "what trench/area exist per site" for instance.
Choose PVD.
Click on identifiers 2, 11, 20 -- their windows do not show up. 
Click on the x to close the query window.
Now I see all of the identifier windows (2, 11, and 20) and can click through them.

**Comment by luizaogs** [comment]
Wait. I think that's a lie.

**Comment by luizaogs** [comment]
Oh yes, they appear below. But I totally didn't see them. I wonder if there's a way to make that clearer.

**Comment by urapadmin** [comment]
That's why I mentioned the lacking user experience in the rollout text: if you work on a laptop your screen is a bit to small to actually enjoy this. That needs some thinking. But you can help yourself with setting your browser to a smaller zoom so that you actually see that things are happening.

**Comment by luizaogs** [comment]
Yeah I didn't understand what you meant with that bullet point. Never mind.
