### ISSUE TITLE
q&v: collected materials label does not appear in context view

### ISSUE THREAD

**Issue by luizaogs** [arch-kiosk/arch-kiosk-office#2346]
Small and I cannot reproduce it all the time, but it has happened enough that I will mention it. 

Sometimes the little black and white header for "collected materials" does not appear. In the screenshot below, for instance, all of the others do. This is what I get when using the fitforaGerman tag query and navigating to locus 814. But you might not get it -- like I said, I haven't figured out what causes the issue.

Clicking on the non-label works and brings up the collected material records, by the way.

<img width="1491" alt="Screenshot 2023-11-05 at 1 19 10 PM" src="https://github.com/arch-kiosk/arch-kiosk-office/assets/67970402/aef6b6ea-ac62-4f6e-ad1b-18ef1a82d9a9">

**Comment by luizaogs** [comment]
Hm using the query for the tag Nightstand and then clicking on locus LA-006 gives me the same problem.

**Comment by luizaogs** [comment]
Oh and weirder: I've already closed locus 814, which was opened before as you can see in the previous screenshot, and now have LA-006 open instead. But the black label in the window tells me it's still 814: 

<img width="1489" alt="Screenshot 2023-11-05 at 1 21 05 PM" src="https://github.com/arch-kiosk/arch-kiosk-office/assets/67970402/11d35d11-6480-4474-b294-2f23b2ce5327">

**Comment by luizaogs** [comment]
Ok actually, I think I figured out that the collected materials label is always missing from the context view. It's fine in the unit view. The comment above appears to be a separate issue.

**Comment by urapadmin** [comment]
The record type "collected_material" does not have a properly configured readable label in PVD. Just a config issue here.

**Comment by urapadmin** [comment]
same thing as with the site in a way. I was taking these from the file repository config and that is lacking in PVD. I'll switch to the glossary AND there is a new general behaviour in terms a config key is missing: The key itself is being used as the value. Documented here: https://wiki.arch-kiosk.brown.edu/urapdev/doku.php?id=manuals:developer_manual:symbolic_data_references#default_resultthe_modifier
