### ISSUE TITLE
q&V: closing one context window leaves me with the wrong label for another open context window

### ISSUE THREAD

**Issue by luizaogs** [arch-kiosk/arch-kiosk-office#2348]
Oh and weirder: I've already closed locus 814, which was opened before as you can see in the previous screenshot, and now have LA-006 open instead. But the black label in the window tells me it's still 814: 

<img width="1489" alt="Screenshot 2023-11-05 at 1 21 05 PM" src="https://github.com/arch-kiosk/arch-kiosk-office/assets/67970402/11d35d11-6480-4474-b294-2f23b2ce5327">

_Originally posted by @luizaogs in https://github.com/arch-kiosk/arch-kiosk-office/issues/2346#issuecomment-1793849426_

**Comment by luizaogs** [comment]
Originally posted that in 2346 and now figured out what the issue is. So: 

Run query what materials (and how much of each) were found in unit x? 
Click on LA.
Click on context LA-021. Works. 
Leave LA-021 open.
Go back to LA and click on context LA-017. Works. 
Now close LA-021 just by clicking on the x while still in LA-017.
Click on the LA-017 window again.
The context label (the black and white one) in the window for LA-017 now says LA-021.

<img width="1492" alt="Screenshot 2023-11-05 at 1 36 42 PM" src="https://github.com/arch-kiosk/arch-kiosk-office/assets/67970402/a26ae5fc-75bc-4141-ad51-d47cf77ba362">

**Comment by urapadmin** [comment]
presumably the same as #2330

**Comment by urapadmin** [comment]
if this is the same as #2330 it should be okay now and you can close it even though #2330 stays open.
