### ISSUE TITLE
q&v: playground records not coming up in search

### ISSUE THREAD

**Issue by luizaogs** [arch-kiosk/arch-kiosk-office#2354]
Some of the PLG site records do not come up properly if I just search for them without going through a query. Try searching for LA test, OStesttrench1, test. They all tell me there is no data (but I know there is). But then other PLG records come up properly with data in regular search: OM, FL, 47. Not sure why that is. 

All of these come up properly with data if I run the what trench/area exist per site? query and click on them that way.

(Obviously not very important on the playground front, but I figured it might be for those projects with more than one site.)

**Comment by urapadmin** [comment]
### kiosk version 1.5.13.1
identifiers should not be case sensitive. That's fixed now and so you should be able to go to all identifiers using the footsteps.
