### ISSUE TITLE
q&v: should site notes be included in site view?

### ISSUE THREAD

**Issue by luizaogs** [arch-kiosk/arch-kiosk-office#2355]
Well. Don't think I have much to explain here, but I ask because we have the unit narratives in the unit view so this seemed to make sense to me.

**Comment by luizaogs** [comment]
Also missing the photos associated with site notes in q&v.

**Comment by urapadmin** [comment]
### kiosk 1.5.13.2
- yes, it should. But the thing with the images is very complicated and postponed: #2378 and #2377 
- But the site notes themselves should at least be there.
