### ISSUE TITLE
q&v: missing fields for excavation units

### ISSUE THREAD

**Issue by luizaogs** [arch-kiosk/arch-kiosk-office#2359]
So far I've only noticed that coordinates are missing from those.

**Comment by luizaogs** [comment]
And I just made sure LA had all fields filled out and coordinates is indeed the only one missing here.

**Comment by urapadmin** [comment]
the value for the spider counter was missing, too :o)

**Comment by urapadmin** [comment]
### kiosk 1.5.13.2
- the missing fields should be there
- unless they are empty (no field will appear if it is empty)

**Comment by luizaogs** [comment]
The spider counter was off in PVD so I forget to check for it. Apologies for the oversight :)
