### ISSUE TITLE
q&V: small_find rather than small find in list of cm 

### ISSUE THREAD

**Issue by luizaogs** [arch-kiosk/arch-kiosk-office#2360]
Ha. As you mentioned in your email ... I see small_find rather than small find under cm type in the list of cm for unit PBA.

**Comment by urapadmin** [comment]
### Kiosk 1.5.13.2

it should reflect whatever is defined in the collected material type configuration in the recording app (it has its own ui because that's where one also defines the identification methods per cm type)
