### ISSUE TITLE
q&v: locus view issues

### ISSUE THREAD

**Issue by luizaogs** [arch-kiosk/arch-kiosk-office#2363]
Looking at locus type deposit:

Some of the fields seem to be in a somewhat weird order. Locus type should probably be next to formation process, for instance? Also the percentages under context deposit should maybe be grouped together? The measurements for the locus itself would be more helpful together, too.

And opening elevations should maybe appear before closing elevations?

<img width="1472" alt="Screenshot 2023-11-05 at 7 01 26 PM" src="https://github.com/arch-kiosk/arch-kiosk-office/assets/67970402/1fd8a6dd-3c54-48e0-97b6-293f291a73bf">

Locus type architecture: same comments as above.

Locus type burial: 
The order of the fields also seems a bit off. 

<img width="892" alt="Screenshot 2023-11-05 at 7 18 07 PM" src="https://github.com/arch-kiosk/arch-kiosk-office/assets/67970402/bb1be125-7fae-481c-b138-628ec1435629">

**Comment by luizaogs** [comment]
Missing from the locus view: lots.

**Comment by luizaogs** [comment]
Are the labels under locus relations supposed to include uid?

<img width="1478" alt="Screenshot 2023-11-05 at 7 09 58 PM" src="https://github.com/arch-kiosk/arch-kiosk-office/assets/67970402/f2c5dfbb-f95d-4359-8a7e-5ff934191cc3">

**Comment by luizaogs** [comment]
Should these appear too? If so, they do not currently.

<img width="504" alt="Screenshot 2023-11-05 at 7 14 39 PM" src="https://github.com/arch-kiosk/arch-kiosk-office/assets/67970402/bc0e5c58-0053-46e8-ae2f-396662fefb81">

**Comment by luizaogs** [comment]
In locus type other, the what type of name would you give this type of locus? field is missing. 

<img width="1002" alt="Screenshot 2023-11-05 at 7 21 22 PM" src="https://github.com/arch-kiosk/arch-kiosk-office/assets/67970402/d0989ddd-b575-4326-b06a-e08aab9f6463">

**Comment by luizaogs** [comment]
This is after testing complete records so this is all that is missing.

**Comment by urapadmin** [comment]
> Missing from the locus view: lots and tags. Also length.

lots and tags are postponed (more complicated), length, width etc. should be there, now.

**Comment by urapadmin** [comment]
> Should these appear too? If so, they do not currently.
> <img alt="Screenshot 2023-11-05 at 7 14 39 PM" width="504" src="https://user-images.githubusercontent.com/67970402/280584910-bc0e5c58-0053-46e8-ae2f-396662fefb81.png">

oh, those are my special friends. Yes, they should. But they can't because I was a but dumb when I gave them database names with whitespace. So that's postponed ...

**Comment by urapadmin** [comment]
> In locus type other, the what type of name would you give this type of locus? field is missing.
> <img alt="Screenshot 2023-11-05 at 7 21 22 PM" width="1002" src="https://user-images.githubusercontent.com/67970402/280585717-d0989ddd-b575-4326-b06a-e08aab9f6463.png">
> 
The other type is deprecated and not included here.

> Also the view for this mentions the color of the locus but I don't see it in FM so I don't know where it's coming from? This is PBA-005.

colour might not be visible in PVD (we introduced it for PACHA)

**Comment by urapadmin** [comment]
### kiosk 1.5.13.2
- a list of lots is there now in the locus view (if there are any lots)
- tags are not included, yet -> too complicated
- fields should be there now and in a better order
- cm type should show correctly in cm list
- lot should be included in cm list (for now for all projects, even if they don't even use lots)
-

**Comment by urapadmin** [comment]
as #2308 is solved now, this can be finally tested

**Comment by luizaogs** [comment]
Opening and closing elevations show up properly.
