### ISSUE TITLE
q&v: cm view

### ISSUE THREAD

**Issue by luizaogs** [arch-kiosk/arch-kiosk-office#2364]
"dear registrar" is missing a space: 

<img width="137" alt="Screenshot 2023-11-05 at 7 27 15 PM" src="https://github.com/arch-kiosk/arch-kiosk-office/assets/67970402/ae5f385c-5b9d-4279-b04d-69f38cafbc20">

**Comment by luizaogs** [comment]
For small finds, measured in situ appears as 1. Is there a way to have a check or something instead? 

<img width="1477" alt="Screenshot 2023-11-05 at 7 30 45 PM" src="https://github.com/arch-kiosk/arch-kiosk-office/assets/67970402/30c94445-6f87-4097-a9db-100a69eb0dd0">

**Comment by luizaogs** [comment]
This is after testing a complete record so this is all that is odd about cm views.

**Comment by urapadmin** [comment]
### kiosk 1.5.13.2
- dearregistrar fixed
- the 1 will one day become a checkbox or something. But that is postponed:
