### ISSUE TITLE
UI Component: paragraph separations not appearing

### ISSUE THREAD

**Issue by luizaogs** [arch-kiosk/arch-kiosk-office#2366]
Don't know if this is important, but paragraph separations are not appearing in q&v. An example: 

<img width="1024" alt="Screenshot 2023-11-05 at 7 39 00 PM" src="https://github.com/arch-kiosk/arch-kiosk-office/assets/67970402/8fe03d5a-3850-4d30-9ff6-90d0f6c29459">

<img width="1477" alt="Screenshot 2023-11-05 at 7 39 07 PM" src="https://github.com/arch-kiosk/arch-kiosk-office/assets/67970402/88db7c40-2602-461f-974a-5269883fe539">

**Comment by urapadmin** [comment]
good question. In fact I think sometimes it is even helpful that they are not appearing (it just occurs to me now). I'll switch them to showing up BUT we might want to have an option to suppress them in narratives.

**Comment by urapadmin** [comment]
### Kiosk 1.5.13.1
- line breaks (and tabs) within text fields are now preserved
