### ISSUE TITLE
q&v: in search, sites come up as site map rather than site

### ISSUE THREAD

**Issue by luizaogs** [arch-kiosk/arch-kiosk-office#2367]
Minor, I presume. When searching for PVD in q&v I am told that PVD is a site map, rather than just a site. 

<img width="528" alt="Screenshot 2023-11-05 at 7 44 18 PM" src="https://github.com/arch-kiosk/arch-kiosk-office/assets/67970402/07c45919-e2a6-4f62-adea-9e820f3a6edc">

**Comment by urapadmin** [comment]
ja, I was taking these from the file-repository configuration and that's not optimal. I'll use the glossary instead ...

**Comment by urapadmin** [comment]
### Kiosk 1.5.13.2
- done. Taken from the glossary now. So you should see "context" for PVD and "locus" for MADP or URAP.
- If a record type is not in the glossary it will be returned as is but with underscores turned to white space. That already covers collected_material even if it is not in the glossary. (I have tested that one).
