### ISSUE TITLE
Q&V: lots

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#2375]
Lots should appear in locus view and in collected material lists and collected material view

**Comment by urapadmin** [comment]
### kiosk 1.5.13.2
There is a list of lots in the locus view and lots are part of the cm-list
- see also #2363

**Comment by luizaogs** [comment]
You mean that lots are part of the cm list for loci only, yes? Should the header for that column be uid lot (what it is currently) or just lot?

uid lot is also the label used in the cm record itself: 

<img width="698" alt="Screenshot 2023-11-09 at 4 52 21 PM" src="https://github.com/arch-kiosk/arch-kiosk-office/assets/67970402/2f67f94b-d99c-44d2-ac79-7911b1105084">

**Comment by urapadmin** [comment]
ja, I kinda decided to leave lots out of the collected material lists in unit. But if anybody wants them there, too, they can be added easily.

**Comment by urapadmin** [comment]
### kiosk 1.5.13.6
- "uid lot" should be "lot" now everywhere

**Comment by luizaogs** [comment]
Nah, I think having lots in the locus view for the cm list is enough.
