### ISSUE TITLE
q&v: default values for symbolic references

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#2380]
Until now symbolic references (into the dictionary) that do not lead to a value would return nothing (undefined). That is in many cases not what one wants. So I have changed the default behaviour. The key itself will now be returned unless the ``?`` modified is being used. In the latter case the result will be ``undefined`` as before. see https://wiki.arch-kiosk.brown.edu/urapdev/doku.php?id=manuals:developer_manual:symbolic_data_references#default_resultthe_modifier

**Comment by urapadmin** [comment]
this is only supposed to have an effect for dictionary entries for the time being. It does not seem to make much sense to return the field name by default if a reference points to a field in a record.

**Comment by luizaogs** [comment]
Hmm do I test this? It's not in testing but it's in the release notes so I wasn't sure (also, if I should test it, how do I test it?)

**Comment by urapadmin** [comment]
you can't. that one is for me.
