### ISSUE TITLE
q&v: locus and context in PVD

### ISSUE THREAD

**Issue by luizaogs** [arch-kiosk/arch-kiosk-office#2386]
Based off your comment in #2367 it seems like PVD should now only use context? But I still see "locus", for instance in the search box: 

<img width="534" alt="Screenshot 2023-11-09 at 4 39 47 PM" src="https://github.com/arch-kiosk/arch-kiosk-office/assets/67970402/8948d7cf-5e99-40d7-87a3-b3b7e88c7db0">

I get context in PVD everywhere else though, I think.

**Comment by urapadmin** [comment]
ja, that is simply Kiosk configuration and will pop up left and right in old projects as those keys are still missing. So whenever you see it in a project, alert me to it. It would only appear in projects where it isn't "locus" or "unit" or "collected material" etc. 

Done for PVD

**Comment by luizaogs** [comment]
Will do.
