### ISSUE TITLE
patch intallation can't shut down the local WSGI server anymore

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#2388]
Werkzeug has dropped support for the shutdown procedure. Now one would have to jump through a lot of hoops to do the same. A pity. 
So questions now is: How do I go update major updates on local servers? I either need an external process so that users shut the server down themselves and then start it 
or I need to go jump those hoops.

I could also start the unpackkiosk process when the server tries to start next time and then at the very end restart the whole computer. 

Or I even restart the computer twice. But that is a pain for users, too.

**Comment by urapadmin** [comment]
- see also #2208 and #2212

**Comment by urapadmin** [comment]
after thinking about it for a bit I believe the most robust solution is to write an autonomous updater that gets started before MCP and Kiosk. It would check if there is an update and install it. 
When a patch gets uploaded all that Kiosk needs to do is save the patch and restart the whole machine.

**Comment by urapadmin** [comment]
### Kiosk 1.5.34
- a completely new kioskpatcher is implemented. Documented in https://wiki.arch-kiosk.brown.edu/urapdev/doku.php?id=manuals:developer_manual:how_to_create_a_patch_to_install_via_install_patch_in_kiosk#kiosk_startup

**Comment by urapadmin** [comment]
Ja, that didn't work. the kioskpatcher is blocking files that unpackkiosk tries to replace. That means the kioskpatcher must be part of the unpackkiosk dir and only use files that are local to unpackkiosk. Major change.

**Comment by urapadmin** [comment]
### kiosk 1.5.35.4
- kioskpatcher-cli can now run from within the transfer/unpackkiosk and only import files from that directory. No kiosk files should be blocked thus.
- start.ps1 must be adapted to this and MCP must be started with start.ps1 and not as a separate task. That's a manual configuration.
- start.ps1 must be started start with powershell 7 as only that version understands the demon start with &

**Comment by urapadmin** [comment]
so, here is a light patch for the local server of @luizaogs. It should solve the small issue #2701. This is how you apply it:
- power up your local server (always with the backup drive as it is being used by the patch installer), 
- make sure that the issue #2701 still exists
- go to administration, sub menu item install patch
- drop the patch file there. It should get immediately applied (no restart needed)
- the issue #2701 should be solved

You find the patch file on our google drive under material_for_test/quickfix_2701.zip.

Don't close this afterwards. This is just the first, rather light test.

**Comment by luizaogs** [comment]
It said the patch was applied successfully but the issue with the enter key has not been resolved.

**Comment by luizaogs** [comment]
Didn't help. I'm in Kiosk version 1.5.35.5, if that helps figure out what's going on.

**Comment by urapadmin** [comment]
not in case of this quick fix. It does not change the version. I am afraid I'd have to dial in and look at the results ...

**Comment by luizaogs** [comment]
Well it's on, if you want to look at it now.

**Comment by luizaogs** [comment]
Sure, just let me know when.

**Comment by urapadmin** [comment]
The quick fix was correctly installed, so the light version of patching worked, technically. Somebody was caching, though. I just don't know who. Might have been the Kiosk server itself? At least after restarting it Kiosk served the correct html file and #2701 was solved as it should have been. 
That sounds like I should always only run patches that request a restart of the Kiosk server.

**Comment by urapadmin** [comment]
I should add that both, Chrome and FireFox behaved the same. So it seems it is really the Kiosk Server that has some layer of caching templates. I thought it didn't do that.

**Comment by urapadmin** [comment]
next tests:
- a bigger kiosk patch that needs a restart 
- a complete new version packed into a patch

But first I have to solve a few tickets so that I have something to roll out ...

**Comment by lbestock** [comment]
This seems quite important before sending anyone else out? And what kind of documentation does it need?

**Comment by urapadmin** [comment]
None, the documentation is already in the manual. The UI has not changed.

**Comment by luizaogs** [comment]
Are you going to give me another patch to test this? Or are you guys doing it over there?

**Comment by urapadmin** [comment]
both. I just need a new Kiosk version that is worth to be rolled out. I got slowed down today.

**Comment by urapadmin** [comment]
alright, here is your next patch to test on your local server: kiosk_patch_1.5.38.1.zip. 
That's contains a whole new Kiosk (version 1.5.38.1). Installation as usual: Just administration, upload patch and then follow the instructions,

**Comment by urapadmin** [comment]
I should add that it will ask you to restart your server and then it will need more patience when the Kiosk server is starting again because that is when the patch is getting installed. And it will be doing a lot on the screen until you see the familiar message that Kiosk is listening on IP Address so and so.

**Comment by urapadmin** [comment]
I should also add that when Kiosk is finally up and you log in, you should get a green message that tells you that the patch was installed successfully.

**Comment by urapadmin** [comment]
My own test on PASU local was very smooth. Yeah.

**Comment by luizaogs** [comment]
I'm not home tomorrow and too incoherent to do it tonight, so it will be a Saturday project.

**Comment by urapadmin** [comment]
that is totally fine. Take your time.

**Comment by urapadmin** [comment]
### patch kiosk_patch_1.5.38.3.zip
I have made a new patch with the latest changes in the same location

**Comment by luizaogs** [comment]
Argh I'm trying to do this but Kiosk is telling me that the upload is failing with this error: "The upload failed (UserError("BadZipFile(File is not a zip file')")). Please try again." 

I'm trying to upload the exact zip I downloaded from the drive, though, so not sure what is going on.

**Comment by luizaogs** [comment]
I'm kidding. There were two files. Goddammit.

**Comment by luizaogs** [comment]
How long should this actually take? I clicked on the server and it's been doing nothing for 10 minutes but I'm scared to click on it again because I don't know if there is something happening in the background.

**Comment by luizaogs** [comment]
Oh kidding - I accidentally clicked "no" when asked if I wanted the app to make changes. Wow.

**Comment by luizaogs** [comment]
Worked.

**Comment by urapadmin** [comment]
who asked you when that an app is going to make changes? I am a bit surprised here. Did you restart your computer or did you try to manually restart the Kiosk server? (In the latter case I'd understand that windows asks, but not in any other case)

**Comment by luizaogs** [comment]
Manually restarted the server.

**Comment by urapadmin** [comment]
ah. Okay. I should change the message then, I think. It is better to restart the whole computer as that also shuts down Master Control.

**Comment by luizaogs** [comment]
Oh yeah, sorry, the message made me think I could do either.

**Comment by urapadmin** [comment]
and you can. You just have to make sure that both Master Control and the Kiosk Server get shut down before you restart the Kiosk Server (which then will start Master Control automatically these days). 
But for the average admin out there I think it is better to give clearer instructions.

**Comment by urapadmin** [comment]
But it makes me happy! I can now roll out complete Kiosk updates to remote servers without access to them. That's huge.
