### ISSUE TITLE
Q&V: dates (and some other types) have a different color than the average text field

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#2390]
This is not easy to spot in all projects. But dates definitely seem to use a different color than text fields. I have seen other field types deviate from the default color as well.

**Comment by urapadmin** [comment]
Yup. iOS and Safari have it different from all the others. Because its Apple and why would they care. 🍌 
### UIComponent 0.4.16 / Kiosk 1.5.13.7
- should be fixed now

**Comment by luizaogs** [comment]
<img width="1300" alt="Screenshot 2023-11-17 at 7 17 23 AM" src="https://github.com/arch-kiosk/arch-kiosk-office/assets/67970402/a7cac065-339d-4403-af9a-9025e0b86a0e">

Private window on Safari looks good to me.

**Comment by urapadmin** [comment]
on Mac you don't need a private window. You can just clear the cache: ALT + CMD + E, I suppose.

**Comment by luizaogs** [comment]
Ha well good to know!
