### ISSUE TITLE
Q&V: Sketch shows a camera instead of nothing when there is no sketch

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#2392]
That's what seems to be the case.

**Comment by urapadmin** [comment]
### Kiosk 1.5.35.5
- no camera anymore if there actually isn't a sketch

**Comment by luizaogs** [comment]
Slightly confused here. So the image holder should appear in Q&V but no actual image exists in the recording? In what scenario would that happen?

**Comment by urapadmin** [comment]
if there is no image there should also be no rectangle or anything let alone a camera. There is simply nothing.
if there is an image referenced but it is broken I(although I am not sure here, the server might send an octopus or some other proxy image in that case) or the server cannot send it (e.g. because the server is gone all of a sudden) the camera would still show up. You can neglect the latter case, I'd be the only one to test that reliably. Not important. 
The important part here was that the camera does not show if there is actually no sketch attached to the locus relation.

**Comment by luizaogs** [comment]
Ok, the relations part is fine.

BUT I have image containers showing up in LA in Q&V that exist in the recording as image containers and not images. Is that right still? Or should there just be nothing? 

This is what it looks like: 

<img width="1512" alt="Screenshot 2024-05-15 at 8 02 34 AM" src="https://github.com/arch-kiosk/arch-kiosk-office/assets/67970402/9a041f7f-1924-477e-8fdd-73719b5baece">

<img width="1027" alt="Screenshot 2024-05-15 at 8 02 46 AM" src="https://github.com/arch-kiosk/arch-kiosk-office/assets/67970402/3302671d-3b93-4556-9e88-a5fd98417dc5">

**Comment by urapadmin** [comment]
This is expected. You actually have a dayplan record (even some text with it) but not an image. So the absent image container is fine (there is none, that's why the layout looks bad there) but I would want to see the dayplan text and the layout should deal with the missing container better. 
But I make that a different ticket because it is a different problem:

**Comment by urapadmin** [comment]
so I think the original camera issue is solved

**Comment by luizaogs** [comment]
Ja.
