### ISSUE TITLE
Q&V request: sites show units within them

### ISSUE THREAD

**Issue by lbestock** [arch-kiosk/arch-kiosk-office#2395]
I would like to be able to see and navigate to units in Q&V from within a site. I am used to doing this for loci in a unit, and something similar at the site level would be very helpful.

I encounter the desire in URAP, which has a lot of sites. And I don't remember which unit I want, since it is a Wheeler unit in the site "Fortress". Which for this case means it would need to show features as well as excavation units, as the Wheeler units are features.

**Comment by luizaogs** [comment]
This. Yes, please.

**Comment by luizaogs** [comment]
Ha you already heard about my hardships? Yes, the internet is decent. But also this is not urgent if you have more pressing things to do.

**Comment by lbestock** [comment]
Didn't you already do this? I won't close it since you moved it to "next" really recently, but that was the whole "unit" instead of "units" per site issue - couldn't arise until this query was present.

**Comment by luizaogs** [comment]
This hasn't been done - at least in PVD, I do not see any units if looking at the site in view.

**Comment by urapadmin** [comment]
### Kiosk 1.5.38.1
- there is a list of units on the site sheet now
- I have limited the purpose description to 4 lines in height so that the list is still working as a list. 
- I could also drop te purpose entirely if that's better for you.

**Comment by luizaogs** [comment]
I think having the purpose is useful.
