### ISSUE TITLE
Harris Matrix: test first example from URAP

### ISSUE THREAD

**Issue by lbestock** [arch-kiosk/arch-kiosk-office#2399]
Testing Unit FA much as #2398 tests an MKAP unit.
![FA](https://github.com/arch-kiosk/arch-kiosk-office/assets/49291909/a162a918-c743-4b2a-b7aa-b96b69da0ba8)

Initial notes:

FA-001 and FA-002 are bonded. That is a "same time as" relationship and they are not on the same level. Furthermore FA-024 is known directly (now that I updated the relations) to be later than FA-001. Shouldn't FA-001 be lower than FA-024, then?

In general the levels are very poor indicators of chronology. Only the relations between individual nodes are useful on that front, the overall needs me to move things up or down all over the place. I note only the FA-001/2 thing because I thought this should have caught that with a relationship thus defined. (This is a problem with the HM generator, too. I 

There is a clear test case of the A-B-C issue in FA-025, FA-026, FA-027. If I am reading this purely for chronology, which I am, it does not bother me that this is represented as simple and linear while the physical relations were not.

**Comment by urapadmin** [comment]
Here is the new FA as an SVG:
![FA](https://github.com/arch-kiosk/arch-kiosk-office/assets/38838314/7d554035-832c-4904-a180-c0b20f5ba59f)

**Comment by urapadmin** [comment]
> In general the levels are very poor indicators of chronology. Only the relations between individual nodes are useful on that front, the overall needs me to move things up or down all over the place. 

Is that a critique of the concept of the Harris Matrix, then I agree, or do you think some of those loci could have been placed in a better layer by the algorithm on the basis of the available information?

**Comment by lbestock** [comment]
I need to test if it would be possible on the basis of available information. But it is clear to me that this could only be used in interpretation itself, not as an illustration of interpretation, if one cannot adjust the chronological levels/vertical positions of things manually. For instance I suspect strongly enough that it wants representation that FA-056 and FA-027 are contemporary. That is not algorithmically derivable. But I would like to move the whole of the left most column (Sondage 1) down so that FA-027 is at the same level as FA-056 (in Sondage 2). 

Note to myself: in terms of deriving things algorithmically, your test should be: You know that FA-005 is later than FA-002. Is there any way Kiosk should have known that? That should be complicated enough...

**Comment by urapadmin** [comment]
well, I "strongly suspect" is problematic enough. My suggestion would be that one can add interpretational relationships that would be visualized differently from the others and I can even imagine that one could add different sets of them. But lets not make it too complicated. If I give you the ability to establish an interpretational relationship in the graph that re-renders the thing (only be aware that re-rendering can change the whole graph substantially) then you could add the algorithmic data that makes the nodes move to the layers you suspect they belong.

**Comment by lbestock** [comment]
Well but that is just it, right? Is the HM a representation of the known certain chronological implications of stratigraphic relations? Or is it a representation of the interpretation of chronological events?  I want to be able to play around with an interpretational relationship and see what it does, but is that really complicated on your end?

I am currently struggling with an interesting case. FA-006 is a wall. All the walls were built before the floor was put down. The floor was put down in two phases, FA-023 is a mud layer, and then FA-024 is the bricks set in it. In the case of FA-006 we did not have a cut perpendicular to the wall, so we saw this only from the top, we could only record that FA-024 abuts the wall FA-006. I know from the relationship of those two floor phases to one another and how they must have been constructed, and can see in relation to other walls, that there is no way FA-023 can be the same date as FA-006 - the wall had to be there before any of the floor was built. I can only observe it for the top layer in this case. So I have an HM with FA-006 contemporary to FA-023, and that's not wrong algorithmically - they are both earlier than FA-024. But it is wrong and I know it to be so.

The relationship of the FA-024 floor to the walls is the place where I can best test the A-B-C issue. On a purely chronological level it's right everywhere else. But those are the major architectural phases of this unit and they touch each other and I really have to remind myself no, this does a different thing than a section drawing does.

**Comment by lbestock** [comment]
So now I have two interpretational relations I want to input if given that opportunity:
FA-027 is the same time as FA-056.
FA-006 is earlier than FA-023.

**Comment by lbestock** [comment]
I would also add interpretationally that:
FA-006 is earlier than FA-004.

That is a less secure interpretation, however, so wow danger.

I still really like this wonderful puzzle of a unit. It was so much fun.

**Comment by urapadmin** [comment]
> Well but that is just it, right? Is the HM a representation of the known certain chronological implications of stratigraphic relations? Or is it a representation of the interpretation of chronological events?

Or are there archaeologists with "formal training" in HM who do have expectations? Well, I don't know. But apart from that we can decide ourselves what we want it to be and how we want it to work. To me it seems much more useful as a tool to study your stratigraphy than as a somewhat static picture that tells you the stratigraphy (because it can't in part because there are many loci that cannot be put on one or the other layer). So playing around with it (coloring it, marking it, enriching it with other data from the record) would be interesting. 

There is just one major caveat from my point of view: if I give you the opportunity to play around with your stratigraphy you might be tempted to make it fit and add interpretational relationships until it is more plausible than it actually should be. 

But one can battle that part at least by visually distinguishing between relationships that have been recorded in the field or found otherwise physically compelling and suspected (or wished for :o)) relations added later.

**Comment by urapadmin** [comment]
perhaps somebody wants to read the manual? One can get it for free at http://harrismatrix.com/about-the-book/ in many languages 🌵

**Comment by luizaogs** [comment]
I like the idea of interpretational relations :)

**Comment by urapadmin** [comment]
While you guys are analyzing this please try to distill a few good archaeological cases out of this that show what I think is the main weakness of the harris matrix: Seemingly false precision. While I have to place a node (locus) on one of the layers often enough the data does not require it to be on exactly one and not any other layer. So the node seems to be contemporaneous with some other node but the data is not that clear. If was for a while thinking that one should draw the corridor of layers in which a locus exists relative to other layers. Could be a shaded background or so. But I think the Harris method does not do such a thing.

So if you run into actual archaeology that reveals the problem that I only see theoretically please write it down so that it can be explained in the class room.

**Comment by luizaogs** [comment]
Yeah I noted a few instances where I thought this had happened in the AA matrix in #2398 but I'll note more if I see them.

**Comment by urapadmin** [comment]
💤 Time for me. But this is fun.

**Comment by lbestock** [comment]
Musing by the fire. 
Yes, the false precision is an issue and a way to capture the imprecision would be good.
However. I was initially annoyed that things that are unknown are landing at the latest of the places they could be, since I often knew or suspected they were earlier, and I am not annoyed by that anymore. On the contrary, if we can't find a way to indicate imprecision, then things definitely belong on the latest possible position the algorithm returns. Why? Because the implications of dating something too late are usually much smaller than the implications of dating something too early. When someone makes a mistake too early they write books rewriting history and huge energy is needed to correct the mistake. Dating something too late usually just means you ignore it for longer than warranted. I am reminded of how I teach students to clean loci and how uncomfortable they are scraping the top of something away before beginning to collect from it, and how the division between those who get and value the problem of contamination and those who don't divides those who have a prayer of doing this from those who don't. Also my FA-006 example reminds me that "archaeology is destruction" is not a bad thing. If we had taken out FA-023 and FA-024 up to the wall that would no longer be ambiguous in the records because we could have documented the relationship instead of inferred it. 

I want interpretational relations for the HM. But where do they exist and how and how aside from the HM would they be seen and recorded? I'm very wary of having them in the recording in a way equivalent to the observed relations; the slippage where something recorded becomes something extant is scary to me. We have always been careful to separate the observation and interpretation for a reason. @urapadmin do you mean to give us these in a way that changes the matrix only, or that changes the recording?

**Comment by lbestock** [comment]
Another missing relation in the data that will make a difference:
FA-009 is above and thus later than FA-024.

(Take a look at FA-010 and FA-011 - if they are not contemporary with FA-009 something is weird, though there should not be any algorithmic way of determining that other than that they are all directly on top of FA-024.)

**Comment by lbestock** [comment]
Yeah wow. 
FA-017 is later than FA-008 and  FA-009 (abutting); and FA-024 (above).
Shoddy recording.

**Comment by lbestock** [comment]
(I want a quality control rule that nothing except bedrock or topsoil can possibly have only one locus relation, and even that would be suspect.)

I fixed those last ones but you might want to wait until I have gone through everything to run the HM again.

**Comment by lbestock** [comment]
Last not totally coherent thought before I go to bed:
I have been thinking of ambiguity in the places where there is a long vertical line. Those are obvious - the node can slide along that line. More insidious is that there is ambiguity in places that are denser, as in above, where FA-006 and FA-023 are on the same horizontal line and earlier than FA-024. Those are all short lines, they don't jump out at you as a place of ambiguity, but we know there should be three chronological steps there not two, so there is a whole horizontal section missing (not algorithmically, but archaeologically). So it's not just where things are phasing-wise, it's even how many phases there are, that get confused in that way. In a more minor way the case of equivalence between FA-027 and FA-05 is similar. There there would not be an increase in overall number of phases, but there needs to be a longer vertical line somewhere (where?) in the relations between layers in that sondage to get those into the same phase.

**Comment by lbestock** [comment]
Already with FA and certainly with anything that has more loci: an absolutely ideal HM UI would include the ability to search for and highlight a locus. I am doing so much going back and forth (I have the recording system open on two devices and sheets of paper flying all over the place too), so it's not just going from the matrix to the recording. I need to go the other direction, too. And then it takes me ages to find my locus.

**Comment by luizaogs** [comment]
> Already with FA and certainly with anything that has more loci: an absolutely ideal HM UI would include the ability to search for and highlight a locus. I am doing so much going back and forth (I have the recording system open on two devices and sheets of paper flying all over the place too), so it's not just going from the matrix to the recording. I need to go the other direction, too. And then it takes me ages to find my locus.

Oh yes, I second this if that’s possible to do. Even with AA yesterday which is much less complicated I kept losing loci and getting a headache going back and forth.

**Comment by lbestock** [comment]
A case of what I might call compound false precision that is interesting:
Several small but disconnected walls on the west side of FA are almost certainly all of the same chronological phase - they defined the bins in which grain was stored. I think I can see in looking at the matrix that there is no actual reason for them not to be on the same level, and indeed three of the five of them are. But the two that are not on that level are very not on that level, and not on the same level as one another. The matrix has not misinterpreted any of the entered archaeological relations incorrectly but it has made choices about where to put things that pretty seriously distort the sense because they seem precise and different.
The loci in question are:
FA-008
FA-009
FA-010
FA-011
FA-034

I can add these to the "interpretational" list above, but I note them separately here because I think this is what you are asking for in terms of false precision? 

A much more straightforward case is FA-058. Again no way for the algorithm to know. That is on the same level as FA-019, just for instance, and FA-058 is ancient and FA-019 is a modern looter's pit, so definitely not the same phase. But there is really no way an algorithm could know this. FA--58 was ancient but it is not a well-networked locus, being a floor on top of a floor and already exposed to the sky when we found it.

**Comment by urapadmin** [comment]
Okay, while we get many ideas on how to implement a Harris Matrix as a more interactive tool here, what I still need before I can do anything is:
Are the chronological relationships in FA (and AA) correct as far as the evidence allows an algorithm to infer chronology?

**Comment by urapadmin** [comment]
> A case of what I might call compound false precision that is interesting: Several small but disconnected walls on the west side of FA are almost certainly all of the same chronological phase ...
>
 FA-008 FA-009 FA-010 FA-011 FA-034
> 
> I can add these to the "interpretational" list above, but I note them separately here because I think this is what you are asking for in terms of false precision?
> 
> A much more straightforward case is FA-058. Again no way for the algorithm to know. That is on the same level as FA-019, just for instance, and FA-058 is ancient and FA-019 is a modern looter's pit, so definitely not the same phase. 

-[ ] I will look into these examples and if it turns out to be random, I will see if there is any option for me to tweak the algorithm so that it consistently puts them up (which it should be doing). But I have very limited influence on the positioning of the nodes. 

When you are finally done with FA and are absolutely convinced that you the locus relations in the recording database are correct as far as possible (no more shoddy recording) I will go through the not insubstantial labour again and put them in the HM composer to get a final opinion on what that one spits out.

**Comment by lbestock** [comment]
On a sense level (I still have not caught this out as having any errors in applying the relations) FA-017 needs to be later than all those little walls just listed above, and FA-018 later than FA-017. Some of this will get corrected when I add a couple of certain locus relations (argh, shoddy recording!) but I don't think all of it will.

**Comment by urapadmin** [comment]
okay. Tell me when you are done with the locus relations of FA and have synchronized your last changes.

**Comment by lbestock** [comment]
A possible error?
FA-024 is earlier than FA-009. That is a direct relationship. But they have been put on the same horizontal line.

**Comment by urapadmin** [comment]
> A possible error? FA-024 is earlier than FA-009. That is a direct relationship. But they have been put on the same horizontal line.

ui. I'll check that first. If we find that the algorithm errs in a single instance, we are mush.

**Comment by lbestock** [comment]
Yeah I know. There is always the possibility that it's a relation I entered since the last round of synchronizing - I caught it in the recording app, not Q&V.

**Comment by urapadmin** [comment]
oh. okay. Then I wait until you have synchronized again.

**Comment by lbestock** [comment]
Do you have any idea how long it takes to check these? And there will be many changes! I need to know if that is really an error so let me check the Q&V...

**Comment by urapadmin** [comment]
that it does take you very long to check these shows us that the hm does have a point in giving you an overview and good intuitive sense of your layers. But you were already a convert.

**Comment by urapadmin** [comment]
It does not take me long to render you a new graph, if that helps!

**Comment by lbestock** [comment]
No. I'm afraid you definitely have to check on things:
![image](https://github.com/arch-kiosk/arch-kiosk-office/assets/49291909/bc8ad33b-0514-41a1-88fb-77ac38e4df27)
Q&V and my svg of the FA HM (have some acronyms there) are contemporary to one another and should reflect the same stuff.

**Comment by urapadmin** [comment]
I don't have that relationship here, locally. Have you synchronized again at some point?

**Comment by lbestock** [comment]
Oh man, my brain. Not only did I synchronize last night, I also made a note here in this crazy thread that I added precisely that relationship before synchronizing. Whoops. I have caught no other problems. I have not checked all the relations for FA-002 because I know I changed many of them already in this round. I will upload and synchronize.

**Comment by lbestock** [comment]
Phew.

**Comment by urapadmin** [comment]
it is a confusing tasks. It will get worse ...

**Comment by lbestock** [comment]
I like it, though. And am definitely a convert. Doing it this way I caught so much that I had not caught when a couple of years ago I really tried to work on the stratigraphy of this unit.

**Comment by urapadmin** [comment]
I just feat that you work on it currently in a way you won't again. Next time you'll just trust what you see :o) 
But anyway, while it isn't perfect and one mustn't take it as that, handled properly I think it can be a huge help.

**Comment by lbestock** [comment]
Back over to you - my changes are synchronized.

**Comment by urapadmin** [comment]
Not our unit, but:
>WARNING: 2 locus relations still have issues that cannot be fixed automatically:
>INFO: BA-020 other BA-001
>INFO: BA-024 other BA-023

**Comment by lbestock** [comment]
I'm not so sure of that. Because it isn't anything in and of itself really, it is a guide to understanding the loci. I would never use it except that way I think - it tells me what order to look at my loci when I am trying to write a chronological history of what happened in the unit (from first to last in the past, not what happened archaeologically, there I use the narratives). So I might not test it the same way, but I also wouldn't write conclusions just based on it and so I think I will catch stuff again. I really like it. Whereas I always thought making one would be worse than eating broken glass, so for me at least having it generated and then checking is ideal.

**Comment by lbestock** [comment]
Yeah let me take care of that so we can get a clean synchronization.

**Comment by urapadmin** [comment]
> Yeah let me take care of that so we can get a clean synchronization.

I have already downloaded a backup. But it does not affect FA

**Comment by urapadmin** [comment]
Here is your new FA.
this time it is all squiggly. That is the only way to make my off-the-shelf layouter draw edges from the bottom side to the top side.
Personally, I don't like the squiggliness and I think it makes it harder to read. So I still would invest the time to invent my own orthogonal edge drawing algo. But I wanted to share this at least and get your opinion.
Apart from that, this is your new data in graph shape:
![FA](https://github.com/arch-kiosk/arch-kiosk-office/assets/38838314/3b9bf13a-71db-489e-bd9b-aba35232b7e7)

**Comment by lbestock** [comment]
Hm. I'm interested to note that still only two of the three sondages, which are pretty straightforward, show up here in an immediately obvious way. The first time I thought it didn't because Allie's recording was inadequate but I rather expected the other one to jump out now, too. Though thinking about it, the other two sondages hit things earlier than the walls. Cool. Not your concern.

The algorithmically correct false precision about the small cross walls is definitely still a thing, so I want my interpretational relations.

I don't like the swooshy lines either. But I prefer the rectangular nodes and the arrows that hit the nodes this way, bottom to top only.

**Comment by urapadmin** [comment]
As for the visualization: I suspect that is @luizaogs opinion, too, right? 
In that case I'll scratch my chin a lot but in the end, if I draw the whole thing myself (currently I just show an svg somebody else rendered for me) I can do more in terms of coloring, adding new lines, etc. We'll see if I can achieve that.

**Comment by urapadmin** [comment]
@luizaogs, @lbestock : For both of you a tip: If you open the svg in a browser you can user ctrl+f (who knows what it is on a Mac?) and search for an identifier. That's how I do it.

**Comment by lbestock** [comment]
Oh hey look. FA-005 is now later than FA-002.

**Comment by lbestock** [comment]
It won't even let me open that in a browser.

**Comment by lbestock** [comment]
Oh. It will let me open it in a browser if I access it through my email, where your comment comes with a "view on web" link that I don't get when I am in GitHub itself. Confusing. And then I can use command+f to find an identifier indeed.

**Comment by urapadmin** [comment]
> Oh. It will let me open it in a browser if I access it through my email, where your comment comes with a "view on web" link that I don't get when I am in GitHub itself. Confusing. And then I can use command+f to find an identifier indeed.

Isn't "in GitHub" in the browser? In that case I just click on the image and get it bigger in a new tab and can search, too. Or I download the image (right click, save image as) and work with it offline or .... There are so many options, particularly when you use the context menu.

**Comment by luizaogs** [comment]
> As for the visualization: I suspect that is @luizaogs opinion, too, right? In that case I'll scratch my chin a lot but in the end, if I draw the whole thing myself (currently I just show an svg somebody else rendered for me) I can do more in terms of coloring, adding new lines, etc. We'll see if I can achieve that.

Visualization in terms of rectangular boxes with arrows that appear from bottom to top only? Yes, please. The other one gives me a headache.

**Comment by urapadmin** [comment]
> > As for the visualization: I suspect that is @luizaogs opinion, too, right? In that case I'll scratch my chin a lot but in the end, if I draw the whole thing myself (currently I just show an svg somebody else rendered for me) I can do more in terms of coloring, adding new lines, etc. We'll see if I can achieve that.
> 
> Visualization in terms of rectangular boxes with arrows that appear from bottom to top only? Yes, please. The other one gives me a headache.

and this was about the squiggly lines (new in the latest FA above)

**Comment by luizaogs** [comment]
Oh yeah, don't love them. But better to have them than the ovals and arrows coming into nodes from all directions, I think.

**Comment by urapadmin** [comment]
> A case of what I might call compound false precision that is interesting: Several small but disconnected walls on the west side of FA are almost certainly all of the same chronological phase - they defined the bins in which grain was stored. I think I can see in looking at the matrix that there is no actual reason for them not to be on the same level, and indeed three of the five of them are. But the two that are not on that level are very not on that level, and not on the same level as one another. The matrix has not misinterpreted any of the entered archaeological relations incorrectly but it has made choices about where to put things that pretty seriously distort the sense because they seem precise and different. The loci in question are: FA-008 FA-009 FA-010 FA-011 FA-034
> 
> I can add these to the "interpretational" list above, but I note them separately here because I think this is what you are asking for in terms of false precision?
> 
> A much more straightforward case is FA-058. Again no way for the algorithm to know. That is on the same level as FA-019, just for instance, and FA-058 is ancient and FA-019 is a modern looter's pit, so definitely not the same phase. But there is really no way an algorithm could know this. FA--58 was ancient but it is not a well-networked locus, being a floor on top of a floor and already exposed to the sky when we found it.

Okay, I have looked into this. This is indeed the algorithm trying to avoid line crossings. And since there is no compelling reason to keep FA-010 on the same level as FA-009 it moves them around. There is nothing I can do about that. The layers don't mean anything It is really only the edges that show you if something is earlier or later. If there is no edge between to nodes you cannot know anything about it. I would have preferred an algorithm that is consistent in putting a node always on the layer closest to the nodes predecessor or successor but such an algorithm is not readily available. Interpretational relations are the only solution I can think of. E.g. one can cluster nodes if one is sure that they are contemporaneous:

**Comment by lbestock** [comment]
Oh look, I missed yet another relation: FA-008 also abuts FA-002. The clustering goes some way towards making it look more like the actual stratigraphy.

It occurs to me that the reason I am uncomfortable with the false precision in dense places like this is because there is no way to visually distinguish when the precision is false or not. FA-001 and FA-002 are so contemporary that they're bonded, but they don't look any more certain than any other two loci that might be just accidentally on the same line. The long vertical lines for some loci are such helpful indication that the precision is false. I wonder if I would like a longer more vertical matrix that always added another phase/horizontal line if it didn't know for sure that things were contemporary, so that you could trust the horizontals. And then the process of interpretation would be more straightforwardly determining which of the extra phases are not real by seeing if any things that are in separate lines belong in the same lines. It might be less confusing to me than this.

**Comment by urapadmin** [comment]
alright. I close these and work on solutions. We open new tickets when I have something to show

**Comment by urapadmin** [comment]
> Oh look, I missed yet another relation: FA-008 also abuts FA-002. The clustering goes some way towards making it look more like the actual stratigraphy.
> 
> It occurs to me that the reason I am uncomfortable with the false precision in dense places like this is because there is no way to visually distinguish when the precision is false or not. FA-001 and FA-002 are so contemporary that they're bonded, but they don't look any more certain than any other two loci that might be just accidentally on the same line. The long vertical lines for some loci are such helpful indication that the precision is false. I wonder if I would like a longer more vertical matrix that always added another phase/horizontal line if it didn't know for sure that things were contemporary, so that you could trust the horizontals. And then the process of interpretation would be more straightforwardly determining which of the extra phases are not real by seeing if any things that are in separate lines belong in the same lines. It might be less confusing to me than this.

A Harris Matrix, I think, never tells you anything about the loci on the same layer. It only tells your something about loci connected with edges. The layers themselves (not stratigraphic layers, I mean the horizontal strips nodes seem to share) get misinterpreted. I don't see how to get out of that, though. When you write that you don't know if a node being on a layer is false precision then the answer is almost always: Yes it is false precision if your read it as chronological  There is no reason for any of the nodes to be on a certain layer. How many layers even exist depends on the density of the stratigraphy in a certain region. 
I can't imagine how even on paper or with the HM composer this could be any other way. I suspect that the intuition one has trouble to suppress is simply a false intuition. 
But I also think that the absence of drawing contemporaneous relations is in the end part of the trouble. I will think about ways to overcome that (perhaps with colour or so).

**Comment by urapadmin** [comment]
If you think FA now has the proper relations I would feed it once more to the Composer and then you can muse about why that spits out a more useful or less counter-intuitive graph, if at all.

**Comment by urapadmin** [comment]
small update today today: FA with the actual contemporary relations marked by light grey arrows:

![FA](https://github.com/arch-kiosk/arch-kiosk-office/assets/38838314/817579f4-e290-484b-8512-3ad864bf949e)

(@lbestock: please answer the question above when you are ready!)

**Comment by luizaogs** [comment]
Thinking of the trouble I had with the AA matrix, that seems very helpful.

**Comment by lbestock** [comment]
I do have a question about why in the cluster one FA-008 is treated as having a different relationship to FA-002. Or at least, it is the only one of the cluster whose abutting to FA-002 is not rendered, and I thought I must have missed the relation but at least in the current version (so many versions, one of the problems) it is already in there.

So. I like the grey arrows. Not too intrusive, provide the answer as to which things are actually known to be contemporary. I dislike that it crosses FA-023 up there - @urapadmin you just added these, or were they taken into account when rendering? I am ready to compare this with the proprietary HM generator, so you can go ahead and feed that beast.

**Comment by urapadmin** [comment]
> Oh look, I missed yet another relation: FA-008 also abuts FA-002. The clustering goes some way towards making it look more like the actual stratigraphy.

Could that be the reason why?

**Comment by lbestock** [comment]
You don't? I downloaded afresh this morning and that abuts was in there I
thought. Possibly again I put it in after you created the above?

**Comment by urapadmin** [comment]
you might. I didn't. Yesterday when I made this I was still using the data from the day before. You must tell me when you actually synchronize a new relation. 
However, I have done that now and very little changes as FA-008 -> FA-002 is transitive (and hence removed) because of FA-008 -> FA-004 -> FA-002.

**Comment by urapadmin** [comment]
Here is the HM Composer version of that unit. To stay under the 48 node limit I had to cut out a few more boring relations:
5->22 -> 25 -> 27 -> 26 -> 28
39 -> 50 -> 52 -> 56 -> 57
31 -> 32 -> 33

I was trying to cut out edges that would have the least impact on the overall graph. The result is this:

![image](https://github.com/arch-kiosk/arch-kiosk-office/assets/38838314/02a71f7d-8836-4e95-abe7-d0126136a380)

**Comment by urapadmin** [comment]
So: Supposing that I can get closer to the orthogonal lines of the hm composer (I will not avoid crossings as well as that one), how close are we here from the archaeological standpoint? Can you find advantages in a region? 
Note how the HM Composer is treating the floating nodes (the ones that could be on any layer, like FA-036, FA-058, FA-030 and FA-029, but also FA-010 and FA-011).

**Comment by lbestock** [comment]
Comparing these is complicated; I'll make notes here as I go.

Are all the locus relations for FA-033 input for the HM? If so it has made a mistake; FA-033 is by direct relationship earlier than FA-030 and the HM composer has them on the same line.

**Comment by urapadmin** [comment]
> Are all the locus relations for FA-033 input for the HM? If so it has made a mistake; FA-033 is by direct relationship earlier than FA-030 and the HM composer has them on the same line.

I missed that one. No bugs in the hm composer.

**Comment by urapadmin** [comment]
and as for nodes on the same layer: We must once and for all accept that unless there is a direct contemporary relation between two loci one must not read the fact that two loci share a layer as any indication that they are contemporary. That is really misreading a Harris Matrix. I wonder if Harris himself pointed that fact out in his book that everybody refuses to read.

**Comment by lbestock** [comment]
He absolutely deletes superfluous relationships, so we and the HM composer have his blessing there.

**Comment by urapadmin** [comment]
does that tell me anything about the constant misinterpretation of the Harris Matrix? Does it mean one mustn't show Harris Matrixes of whole units?

**Comment by lbestock** [comment]
It doesn't tell you anything about the constant misinterpretation of the Harris Matrix. Whether or not it means a whole unit shouldn't be shown but just a section so that the matrix and the section drawing work together I am not yet sure. It is not a short book.

**Comment by lbestock** [comment]
> makes me, of course, suspicious that you read it the way good old Christians read the bible.

Quite a well-founded suspicion.

**Comment by lbestock** [comment]
It is the second edition of Harris that I am reading. In his definition of archaeological laws the only relation he recognizes stratigraphically as a contemporary one at all is a case that he calls the "once whole" context, as in a layer that used to be a single layer, was cut in two by a ditch and thus encountered as two physically separate things, but which was once whole. (That this itself is an interpretation he does not directly address. This is our relation "equivalent to".) In chapter 11 he does discuss in depth why contemporeneity is itself foreign to the Harris Matrix as used in the trench - it's not just that it isn't always meant when things are on the same level, it is that it is never meant in the sequence itself. The archaeological laws he defines and on which he bases his system do not include same time as. He shows why the notion of "horizontal stratigraphy" is not subject to laws of the sort he employs.

Directly to the point, he would define moving a locus up and down within its possible bounds as the **permutation of a multilinear stratigraphic sequence**: "the changing of the chronological order of stratigraphic units of different stratigraphic sequences, every permutation being a different arrangement of which the units are capable and which is not contradicted by the recorded stratigraphic relationships." (Harris, 129). He notes here that this is not a matter of stratigraphy at all but one of analysis, eg of the artifacts in the strata.

He notes that one very frequent mistake that is made about HMs is to regard them as representing physical relations. And he is utterly clear about the importance of removing transitive relations - the goal is as clean as possible a diagrammatic representation of the befores and afters. 

He, as Bibby evidently followed and as is clear with Harris's discussion of permutations, absolutely separates between the making a matrix as you go as an important tool to help you dig stratigraphically in the first place and record the relations of your strata while working, and the interpretation and phasing that lead to a matrix that is a representation of the phased stratigraphy. And he stresses that the final one relies on interpretation of the stuff in the strata and cannot be done before lab analyses are complete. He is adamant about this being a two-step process. In my words but very much following what he says here: there is no single "Harris Matrix". There is a HM produced as a tool during excavation, and then there is a phased HM as a representation of the interpreted stratigraphic relations of an area of analysis. They are related but not the same.

**Comment by lbestock** [comment]
Oh, ja, I didn't expect to get so extensive, nor really think about it. Bibby is the author of a chapter in the second Harris book, the one on putting the matrix into practice. I will make us some notes and put the two volumes and the notes in a google folder and remove them from this ticket, once I get a fire going.

**Comment by urapadmin** [comment]
@lbestock: FA with only very minor issues:
![image](https://github.com/arch-kiosk/arch-kiosk-office/assets/38838314/11a9f33b-68b2-45ab-b194-b8579a1d4b3c)

**Comment by urapadmin** [comment]
and not anymore substantially wider than the spline version:
![image](https://github.com/arch-kiosk/arch-kiosk-office/assets/38838314/ee700767-f88d-4704-a350-268de3ef3ae8)

**Comment by urapadmin** [comment]
we also still have wider nodes and I can collapse the empty vertical columns. That'll gain a few more pixels. I think I got it.

**Comment by luizaogs** [comment]
I think we can close this one, no?

**Comment by urapadmin** [comment]
@lbestock can we close this?

**Comment by urapadmin** [comment]
closing it
