### ISSUE TITLE
recording app: expanded notes for survey units?

### ISSUE THREAD

**Issue by luizaogs** [arch-kiosk/arch-kiosk-office#2401]
This is super random because I am not currently running a survey from my bed, but it came to mind when I saw @lbestock 's #2396 request the other day and I made a note of it and I just found the note so opening this before I forget it again (especially because now I have thrown the note away!). 

I've always kinda wondered why we don't have something like narratives for survey units. Is the single text field for purpose/description/notes sufficient? What if a survey is being run across multiple days and notes need to be added across that time span? I don't know - it seems more intuitive to me to have the option of adding distinct time stamped notes there, too.

**Comment by lbestock** [comment]
Oh the floating notes! 
I am not so sure we need this, though the ticket can stay open until we have someone running a survey and we can ask then. Here you have site notes where you can talk about the process of a survey. A survey almost always takes multiple days, but more or less by definition a single survey unit needs to be done in one run (hence things like "sun conditions"). I just looked at the URAP survey stuff, all in the site Western Desert (different from Fortress). And yeah, well, there no one even used the description field that does exist for the survey units, except to input images. Features got described, but not survey units (which they should have been). And no one made any site notes at all, which also should have happened, such as "Four people out after excavation to survey today, going to the Semna Wall area." and "Jesus Christ if they don't get back from surveying soon we will have to send a rescue mission out in the dark and I don't even know how to get a fisherman out here to get us across to the West Bank, they are not allowed out again this week."

**Comment by lbestock** [comment]
:) I think this is OCD brain. Think about how simple a survey unit is. Also because this was designed in consultation with people who have lots of experience in Mediterranean survey and so on this front I'm wary of changes made by excavators like us.

**Comment by luizaogs** [comment]
Then never mind :)

**Comment by urapadmin** [comment]
> Also because this was designed in consultation with people who have lots of experience in Mediterranean survey and so on this front I'm wary of changes made by excavators like us.

Structurally I do not like that argument. It's an authoritarian argument which often enough boils down to "we have always done it that way" on closer look. We got the unit - locus - cm hierarchy that way. People who have a lot of experience in the field don't necessarily have a lot of imagination in terms of what could be done now that paper isn't the limiting media anymore. 

On the particular case, I think at this point that all description fields should in fact be lists of description fields with a time and person stamp even if it seems over the top in some cases. This would also solve #2396 and I think it can be useful for simple loci descriptions as well (which also have only one description field).

But: As long as we are in FileMaker I'd rather not. So I keep this closed (but for a different reason).

**Comment by urapadmin** [comment]
what is OCD? Something compulsive?

**Comment by luizaogs** [comment]
Yeah, that's how my little problematic brain works :)

**Comment by luizaogs** [comment]
I don't usually :) It just sounded like here I need more order than is actually useful to other people.
