### ISSUE TITLE
URAP: Harris Matrix for CC shows a cycle, for CA it shows that CA looks strange

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#2402]
@lbestock: First I would like you to confirm these:
CC has at least one cycle. which means that something later AND earlier than something else. E.g. A -> B -> C -> A or so. Unfortunately such a cycle form over quite a few relations.
CA looks unreasonable:

![image](https://github.com/arch-kiosk/arch-kiosk-office/assets/38838314/ca37f0c0-5500-45f8-a324-8d97fef1c7a9)

Looks like things that are set to be contemporary are also later or earlier. 

All I need here is confirmation that the algorithm is correct in its response. You don't need to fix it. 

Second it shows me that the Harris Matrix and even the computational algorithms behind it (testing for cyclic relations) can improve the recording in the field. But also the director's view could hint at issues with a unit. Would that make sense?

**Comment by lbestock** [comment]
This is very funny. I will look at it and am not surprised.

But first. YES to Director's View. YES.

**Comment by lbestock** [comment]
Can you tell me where the apparent cycle in CC is?

**Comment by lbestock** [comment]
First note about CA: CA-001 has two relationships to CA-002. One is adjacent to, with no chronological relation given. One is seals, which is later than. The above has CA-001 and CA-002 on the same line, which should not be the case with the second of these relations, but how much does it blow its mind to have two relations from the same to loci?

**Comment by urapadmin** [comment]
Apart from the fact that that is a funny question (where does a cycle begin?) I will be able to show which loci are involved one day, but currently I only know that it is cyclic. On 27. Nov 2023, at 23:48, lbestock ***@***.***> wrote:﻿
Can you tell me where the apparent cycle in CC is?

**Comment by urapadmin** [comment]
I interpolate the usual missing chronological relations. On 27. Nov 2023, at 23:55, lbestock ***@***.***> wrote:﻿
First note about CA: CA-001 has two relationships to CA-002. One is adjacent to, with no chronological relation given. One is seals, which is later than. The above has CA-001 and CA-002 on the same line, which should not be the case with the second of these relations, but how much does it blow its mind to have two relations from the same to loci?

**Comment by lbestock** [comment]
CA-001 is also later than CA-006 but they are on the same line. In that case there is no second relationship between the two.

**Comment by lbestock** [comment]
And CA-001 is later than CA-004.

**Comment by lbestock** [comment]
But the 004 and 006 relations were clear "later than" ones and yet they are on the same line, too.

**Comment by urapadmin** [comment]
because many "adjacent to" relations are lifting the whole thing up.

**Comment by lbestock** [comment]
Why don't you run it again with that out of the way and then I'll take a look again.

**Comment by urapadmin** [comment]
![image](https://github.com/arch-kiosk/arch-kiosk-office/assets/38838314/a91bf58b-6c73-44e1-9537-5a377718d868)

**Comment by urapadmin** [comment]
looks like a proper graph now

**Comment by urapadmin** [comment]
leaves us with CC (which did not benefit from this change)

**Comment by lbestock** [comment]
That one will take some sleuthing presumably, and my brain is fried by ChatGPT.

**Comment by urapadmin** [comment]
that's fine. I wanted to shut down my computer long ago.

**Comment by lbestock** [comment]
I got all set up to do a complex cycle search (seemed better than grading before my second tea is cold). But I caught one super early and simple. Can it be the only thing, or you expect more?
CC-003 is both earlier and later than CC-006 in its own relations.

**Comment by urapadmin** [comment]
> I got all set up to do a complex cycle search (seemed better than grading before my second tea is cold). But I caught one super early and simple. Can it be the only thing, or you expect more? CC-003 is both earlier and later than CC-006 in its own relations.

one cycle is enough for me as a test if my algorithm is right about it. After I delete those relations it turns out to be cyclic still. But that's okay with me. You might want to attend to in in URAP one day. But I might also be able to tell you the cycle(s) one day, too.

**Comment by urapadmin** [comment]
> But the very need for that shows us that a locus is not quite so intrinsic as I am used to thinking. We need to find something discrete and bounded so we can label and analyze it. But that is simplifying complex processes and nowhere is that more evident than when the time and space things don't seem to align quite right.

I see the point. I am just not sure how consequential it is. I mean I would want to see a real example where interpreting it the one or the other way leads to significantly (also problematic) different interpretations. Otherwise it is still a bit, well, academic. Somebody should write a paper. 

However, while I do accept that indeed something can be on top and below something else in a way somehow, I do not accept that it can be later and earlier at the same time. So in this case, and that is for the archaeologist's handbook, one must change the time relation. so that that is at least consistent. Unfortunately one cannot remove a time relation. We should introduce a "undefinable" or so to keep Kiosk from setting a missing time relation on the basis of the physical relation.

**Comment by luizaogs** [comment]
Can I get this out of testing? And #2399 ?

**Comment by urapadmin** [comment]
### hm plugin 0.9
- those problems are "solved" (as in removed) by #2512 now.

**Comment by luizaogs** [comment]
Well this must be a @lbestock test because I don't know either of these units.

**Comment by luizaogs** [comment]
Looking at CA now to try and think about #2530 and I'm confused because it seems like two relations that were ok were removed? CA-002 and CA-001: 

<img width="322" alt="Screenshot 2024-03-06 at 3 09 10 PM" src="https://github.com/arch-kiosk/arch-kiosk-office/assets/67970402/5a252478-c0a0-49c3-a125-e9ad0f012ddc">

Or is that something to do with the wording in the error pane that I'm not understanding? When "cycles" have been removed in CC they are all "earlier" so now that I see both "earlier" and "later" for the same loci I'm thinking that's not a cycle?

**Comment by urapadmin** [comment]
That took me a while to find out: 
Whoever recorded this must have been bitten by a goat: 
CA-002 is not only sealed by CA-001, it is also "adjacent to" and vice versa. And that's where the system gets confused.
Hmpf.

**Comment by urapadmin** [comment]
### plugin 0.13
- okay, after #2572 this should look better now. SEALS and SEALED BY had not been removed and should not appear that way any longer. What had been removed were the "adjacent to" relations between 001 and 002 and that should be correct. 
- see #2572 for details on how errors of excess relations and non-temporal relations appear in their own section now

This is getting baroque.

**Comment by luizaogs** [comment]
Sounds like you guys should have a goat button, too...

**Comment by luizaogs** [comment]
Ok the above looks good now I believe, but I presume this needs to stay open for Laurel to actually look at the archaeology.

**Comment by luizaogs** [comment]
Oh wait. So the CA-010 and CA-012 mess is the contradictory relation, yes? In URAP it's showing up under the "relations dropped for other reasons" but it seems like it should be under the "Removed relations that were part of a cycle or contradictory" ?

**Comment by luizaogs** [comment]
Ugh now I'm looking at #2572 and you say there that it's correct. Sorry. There are too many tickets.

**Comment by urapadmin** [comment]
Yes, there are too many tickets, indeed. Argh.
I guess it is a matter of order. If you have A and B with A abutted by B AND A is above B and vice versa, you have an excess relation and it is even contradictory. I check for excess first, so miss the contradiction.

In the particular case there is no contradiction, right? CA-010 abuts and is above CA-012 and that is the same chronological relation.

**Comment by luizaogs** [comment]
Yes, those would have the same temporal meaning.

**Comment by lbestock** [comment]
In CC all the removed cyclical relations are also excess ones. They are also very simple ones, and derive from the goat: someone misunderstood what "abuts" means and used it when they meant adjacent. And created two relations in each case it seems like.

Also makes me angry again. That part is simple and the goat is a nice little cute guy, but diving into it the recording is so infuriating. CC-003 has this kind of nonsense relation. But it (a wall) is also marked as adjacent to windblown sand that is clearly later than it, and no relation at all is given for the deposit it sits on top of between the base of the wall and the floor that is so textbook a case of phasing and has deep interpretational significance. Hate.

Since the relations that were duplicate with chronological impact are removed as per #2572, this looks right from the perspective of the HM. Just bad archaeology.

The CA HM also looks right. CA was a difficult unit and the problems are less stupid.

**Comment by urapadmin** [comment]
you really misunderstood the goat thing: The archaeologist in training was not the goat (that would be really insulting to the goat) it should have been bitten by the goat
