### ISSUE TITLE
file repository: make new sort options that sort undated photos always to the end

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#2404]
Sorting by "latest" is annoying because one gets all the undated photos first.
I want to add a "latest and undated first" option that does exactly that and then change "latest" to a sorting order that sorts the undated ones to the end.

**Comment by urapadmin** [comment]
### Kiosk 1.5.16
- we have "undated, then latest" which behaves as before "latest" would have
- we have "latest" which now sorts the undated photos to the end.

**Comment by luizaogs** [comment]
Quite weird and I'm not sure what is going on. When I sort using those two I get the same results, but somehow when using undated then latest the same pictures appear without dates, and then when using latest they appear with dates: 

<img width="1512" alt="Screenshot 2024-01-02 at 10 32 08 PM" src="https://github.com/arch-kiosk/arch-kiosk-office/assets/67970402/4547ce09-4046-4493-8a69-f4dea532efa8">

<img width="1512" alt="Screenshot 2024-01-02 at 10 32 19 PM" src="https://github.com/arch-kiosk/arch-kiosk-office/assets/67970402/cfa24c12-6c65-4361-a8b3-c7889b31a648">

**Comment by luizaogs** [comment]
The images that appear undated when using that selection do in fact have dates if you click on them, which is weirder.

**Comment by luizaogs** [comment]
Yes. They are the same exact images that appear with the blue dates in the other screenshot. And when I click on them that field is filled out.

**Comment by urapadmin** [comment]
> Yes. They are the same exact images that appear with the blue dates in the other screenshot. And when I click on them that field is filled out.

ah, okay, I misunderstood. As long as they appeared with a blue date in one of them, all is fine. The other makes sense to me, weird as it seems,

**Comment by luizaogs** [comment]
Huh, really? Alright then.

**Comment by urapadmin** [comment]
no, no, ha. I meant the bug makes sense to me, as in "I found it right away from the description".

**Comment by luizaogs** [comment]
Oh. Ok good. I was admittedly confused :)

**Comment by urapadmin** [comment]
### Kiosk 1.5.16.1
- dates should show for all options that sort by date
- the sort options were still not doing what they were supposed to do. I think now they are okay.

**Comment by urapadmin** [comment]
> Oh. Ok good. I was admittedly confused :)

don't you let any developer insist on obvious nonsense :o)

**Comment by luizaogs** [comment]
Looks good now :)
