### ISSUE TITLE
recording: can't delete site notes image containers

### ISSUE THREAD

**Issue by luizaogs** [arch-kiosk/arch-kiosk-office#2407]
Not sure if this is actually a bug or if it's just an unwanted feature, but I accidentally added a site image container when trying to add a new site note instead and I don't seem to be able to then delete the empty image container. I would like to, since I didn't want to add an image there.

**Comment by urapadmin** [comment]
you should be able to do that in the pop over of the image. A trash button in the list of images had so little space that I skipped it there.

**Comment by luizaogs** [comment]
Ah.
