### ISSUE TITLE
recording: field for site measurements?

### ISSUE THREAD

**Issue by luizaogs** [arch-kiosk/arch-kiosk-office#2408]
You guys will probably hate this, but I open it because I wanted to have this field today and I did not. 

My site is the tomb -- maybe I should have done it differently, but this was the best way I could think of to have each room of the tomb be a unit, and then each wall of each room be a locus. So, site = tomb. Which is slightly problematic, because I want to record things like measurements for the tomb (site) as a whole and I don't have fields for that. For now I just wrote it in either site notes or in the site purpose (I can't remember), which is fine. But I wonder, if you guys want to expand Kiosk to be used for projects like this one -- so potentially other tombs -- might it be useful to think about expanding the site recording form? Currently I have only needed it for measurements, but if other things come up I can also let you know.

**Comment by urapadmin** [comment]
we won't implement that as long as we have FileMaker as recording app. So for the time being the site notes are your friend.
