### ISSUE TITLE
kiosk and recording: I want some context-bound photos in the file repository but not in the recording

### ISSUE THREAD

**Issue by luizaogs** [arch-kiosk/arch-kiosk-office#2409]
Another potentially infuriating ticket for you both :) And more of a musing than an actual request of any sort. It's also possible that I'm just not using the file repository properly right now, since I have never actually had to decide how to use Kiosk for a real project before. 

I'm uploading our images at the end of every day, so I don't end up with a huge backlog. I've been uploading everything we took that day, rather than sorting much before doing so, because I want to have the images at hand (even if some are quite similar) in case we need slightly different views or what have you for publications and talks, etc. I'm attaching those imported images to contexts so they are easily findable in the repository. BUT that means that they all go back to the recording, and I don't really need or want three images from slightly different angles in dayplans, especially because then I have to go in and write descriptions for all of them because having images without descriptions in the recording looks sloppy and annoys me. My workflow has been pretty stupid on this front -- I upload the images, connect them to the contexts, they all go back to the recording, then I go through the images in the recording and delete superfluous ones (knowing that they will remain in the gallery and so not disappear from the file repository). File picking doesn't solve the problem, because then I have a gajillion dummies rather than not having a bunch of very similar images in the recording system.

Which makes me wonder if it makes sense to have an option in the file repository where one can decide whether imports go back to the recording at all or not? In my head I imagine something as simple as an empty checkbox with "do not send back to recording system" per image record, which is probably unrealistic and it would be something much more complicated. Oh actually, maybe even a file picking rule that would just keep images tagged with a certain thing out of the recording app.

And, of course, this might be overthinking it, as is my wont. I'm curious to hear what @lbestock does with URAP -- do you just sort through all the images before importing? Or do you just have a bunch of very similar images in the file repository and thus in the recording app?

(These are not photogrammetry images, by the way. I'm aware that the file repository is not meant to store those.)

**Comment by urapadmin** [comment]
let me try to understand this first:
- when you delete superfluous images in the recording app what you actually delete is their connection to the archaeological record. So you'll end up with a bunch of photos in the file repository that are not connected to any archaeological context? That's what you want? Why not delete them entirely?
- file picking is definitely the only way to suppress images. The fact that there is an image connected to a specific archaeological record is part of the archaeological record and we cannot suppress parts of the archaeological record
- What I can imagine is an option in the recording app to not hide image relations to dummies. That would in fact solve your problem, wouldn't it?

**Comment by luizaogs** [comment]
Ha wow I’m dumb. I forgot that deleting them in the recording would delete their contexts in the repository, too. Well even better, now I need to go back and recontextualize them. I want to keep them because they are slightly different views of the same thing, and I don’t know which one I might need in the future. But then having a bunch of images that look quite the same in the recording clutters things and is unhelpful. 

I’m not sure I understand the last bullet point - do you mean that there would be an option to not show the dummies in their proper places in the recording? Yes, that would solve it.

**Comment by lbestock** [comment]
I think dummies not shown wouldn't solve it? Because how would you have half the images for a unit or context be dummies and the other half not, and you don't want to not show ANY photos of a context, you want to be able to choose which you show. You'll even have a set that are nearly identical - taken the same day, same context, same camera, same upload, there is literally no variable aside from your decision that one is representative for the recording system and the others you want to live elsewhere.

**Comment by lbestock** [comment]
On the URAP front: it just doesn't arise :) Two reasons, first being that I don't have this kind of similar image, and second that I don't mind images without descriptions in the recording app. I even kinda like that the absence of a description shows me I didn't describe it in the field - it's a super quick visual sort between SLR images and iPad images.

**Comment by urapadmin** [comment]
> Ha wow I’m dumb. I forgot that deleting them in the recording would delete their contexts in the repository, too. Well even better, now I need to go back and recontextualize them. I want to keep them because they are slightly different views of the same thing, and I don’t know which one I might need in the future. But then having a bunch of images that look quite the same in the recording clutters things and is unhelpful.
> 
> I’m not sure I understand the last bullet point - do you mean that there would be an option to not show the dummies in their proper places in the recording? Yes, that would solve it.

Yes, that's what I mean. And then your checkbox (that's the answer to Laurel's objection) would be an image tag that you set whenever you don't want to see (or you do it the other way around) an image. What you could not distinguish in the recording app would be dummies that became dummies because of that tag and dummies that became dummies because of a different rule. You can only hide or show them all. But I think, that might even be helpful for users who just don't want to stare at a bunch of dummy images in general.

**Comment by urapadmin** [comment]
if you tell me where you'd need this the most we could run a trial with that part. Sending you an update of the recording app is really simple.

**Comment by luizaogs** [comment]
> > Ha wow I’m dumb. I forgot that deleting them in the recording would delete their contexts in the repository, too. Well even better, now I need to go back and recontextualize them. I want to keep them because they are slightly different views of the same thing, and I don’t know which one I might need in the future. But then having a bunch of images that look quite the same in the recording clutters things and is unhelpful.
> > I’m not sure I understand the last bullet point - do you mean that there would be an option to not show the dummies in their proper places in the recording? Yes, that would solve it.
> 
> Yes, that's what I mean. And then your checkbox (that's the answer to Laurel's objection) would be an image tag that you set whenever you don't want to see (or you do it the other way around) an image. What you could not distinguish in the recording app would be dummies that became dummies because of that tag and dummies that became dummies because of a different rule. You can only hide or show them all. But I think, that might even be helpful for users who just don't want to stare at a bunch of dummy images in general.

Yes, that seems fine to me.

**Comment by luizaogs** [comment]
> if you tell me where you'd need this the most we could run a trial with that part. Sending you an update of the recording app is really simple.

You mean in the recording? So far it has been most needed in both dayplans and locus photos, but now that I’ve assigned cm numbers to things like parts of walls that will happen for cm too. So basically take your pick.

**Comment by urapadmin** [comment]
> This sounds quite cool. Could the check box be a bulk action? I'm reminded of #929, here, too, and wondering if that would be of help in such circumstances.

as image tags are bulk operations in the file repository, yes. There won't be any checkbox. It is a tag and entirely a convention (as in: this won't be a particular mechanism in Kiosk, it will work entirely based on Luiza's conventions).

**Comment by luizaogs** [comment]
But maybe it can be a set tag, like map or import, that other projects can use if they wish to do so?

**Comment by urapadmin** [comment]
> But maybe it can be a set tag, like map or import, that other projects can use if they wish to do so?

in which case we would simply supply the same file picking rule to all projects. But in the end there is no special mechanism. We just use what we have: tags and file picking. That how I like it.

**Comment by luizaogs** [comment]
Works for me.

**Comment by urapadmin** [comment]
there is a new config key now: "show_dummy_image_rows" that is set to "nope" by default. I think that most projects would agree that seeing all those dummy images is rather annoying. I have made one qualification: If there is a description for the image in the context it gets displayed (remember, descriptions are bound to the relation between a context and a the image, not the image itself) then a dummy image will be shown no matter what the setting here is.

**Comment by urapadmin** [comment]
### recording app 15.5
- unless "show_dummy_image_rows" isn't explicitly set to "yup" dummy images in image lists will be hidden if 
  - they don't have a description in the displaying context
  - you are in dayplans, site notes photos, locus photos or collected material photos
- all those lists show the number of available images in the lists somewhere. dayplans and site notes in a heading, locus photos and collected material with the images. Those numbers are off because they count all images and not only the visible. I am currently not sure what to do about it. In a way I even like that one gets a hint that there is more than meets the eye but on the other hand the numbers differ for no apparent reason from what one sees. In the current version I leave it at that and make a new ticket for it.

**Comment by luizaogs** [comment]
Works well - thank you.

**Comment by urapadmin** [comment]
my pleasure 👀
