### ISSUE TITLE
recording: make in-text navigation possible from site notes too

### ISSUE THREAD

**Issue by luizaogs** [arch-kiosk/arch-kiosk-office#2413]
I might be using site notes more than they are usually used, but for me it would be helpful to be able to navigate to records by clicking on identifiers in those text fields, too.

**Comment by urapadmin** [comment]
### recording 15.6
- there it is

**Comment by luizaogs** [comment]
Super weird. This works, BUT if I go into site notes before doing anything else and try to navigate somewhere using this the records I go to are all empty, which gave me a heart attack. I then went to that record through home, rather than navigation, and the stuff was there as it should be. THEN going to the records through the site notes navigation worked, so it seems like there’s an issue with navigating to records through site notes if none of those records have been accessed first.

**Comment by luizaogs** [comment]
If I log out and back in and then go straight to navigating through site notes that works fine, so seems like this is an issue only when the recording app is first accessed.

**Comment by urapadmin** [comment]
that sounds quite weird, indeed. I'll have a look at the startup routines but currently with no clue what I could possibly find.

**Comment by luizaogs** [comment]
If you need a MADP database just let me know.

**Comment by urapadmin** [comment]
there is something you can try to see if it actually happens again with a fresh database: reset you "recording group" or (same thing) reinstall the latest template and then prepare your workstation again. If you have leisure time...

**Comment by luizaogs** [comment]
Sure, I can try later.

**Comment by luizaogs** [comment]
Same issue as described above after the reset.

**Comment by urapadmin** [comment]
last question before I tackle this myself: Does it not happen in unit narratives if you go there first?

**Comment by luizaogs** [comment]
It does not.

**Comment by urapadmin** [comment]
### recording 15.7.2
Got it. In fact it happened because there was nothing selected on the start page, yet. So the issue was that site notes could not jump to anything properly unless it was something in the current site AND the site was already properly selected on the start page. 
Or so. 
However, it should be okay now

**Comment by urapadmin** [comment]
ah, sorry, I forgot to mention it in the release notes: You find an update 15.7.2 zip on the web site.

**Comment by luizaogs** [comment]
Works.
