### ISSUE TITLE
recording app: date fields are hard to enter because of the format and because they sometimes require a time

### ISSUE THREAD

**Issue by lbestock** [arch-kiosk/arch-kiosk-office#2416]
Inputting legacy data from BUAP.

Creating new narratives with timestamp is complicated by the need for the entire time, including hour and minute, to be in there. I would prefer that the narrative reflect the day it was actually made, not the day I input the data. I can't even type that format easily and it is inaccurate as it includes a time that is made up.

My current workaround is to hit the time stamp and then change the date but just leave the time as it is. This is OK for what we are doing, but a bit of a pain and I wonder if it would be possible to have just a date, not a timestamp, when one knows one is putting in old stuff.

**Comment by urapadmin** [comment]
### recording app 15.6
that was never an issue before, apparently. I suspect we have not typed in much legacy data. 
I have developed a new, somewhat experimental method that parses and changes the user input before it gets handed over to FileMaker's validation. You can now type:
- dates in the date format that is set as default in FileMaker (presumably in the confusing US order) without a time (leads to 00:00:00 as time).
- dates in latin format. That means anything that has the day, then a latin month and then a year (either two or 4 digits). The separator is irelevant and can even be omitted. So "1IV23" leads to 01 April 2023. But you can also type "01.IV.23" and the the same result. 
- dates in latin format can have an additional time but that needs to be separated by exactly one space character and nothing else
- a perhaps confusing side effect of my hackneyed parser: the latin date XIII is read as XII and the latin date IIIV comes out as 3. I can live with that unless it causes mistakes in practice. Please report.

If this makes for easier input, we can equip all date and date/time fields with this method.

**Comment by lbestock** [comment]
Wow it even lets me do either 23 or 2023. It is great. Please put it everywhere - I immediately want it in loci and lots. We are looking at stuff with Latin dates on paper, and the ability to put them in AS Latin dates is great; the potential for human error in translating that while typing records is not small.

**Comment by urapadmin** [comment]
### recording 15.7.1
applied to 
- [ ] unit narrative
- [ ] locus opening / closing
- [ ] lot
- [ ] collected material
- [ ] unit narrative view
- [ ] site notes
- [ ] unit creation
- [ ] collected material registration (filter from date)

**Comment by lbestock** [comment]
![image](https://github.com/arch-kiosk/arch-kiosk-office/assets/49291909/fca3561f-36dc-48b1-8f18-f1bebf3a7b28)
How does that happen?
Looked good after I had added a few, but then I scrolled down and this one got messed up.

**Comment by lbestock** [comment]
And then I added another and this one corrected itself, and a different record was messed up.
And then I added another and everything looked good...

**Comment by lbestock** [comment]
![image](https://github.com/arch-kiosk/arch-kiosk-office/assets/49291909/9b851f2c-93ae-4e81-9e85-afc4766a756b)
This one was entered American style: 12/23/23
Translated properly at first.
Made another record, and this is what is displayed from my first record.

**Comment by lbestock** [comment]
I'm testing this in PVD.

**Comment by urapadmin** [comment]
Might be a refresh issue. Try clicking on it if it is wrong. Or try leaving and coming back in. Does that change anything?

**Comment by lbestock** [comment]
![image](https://github.com/arch-kiosk/arch-kiosk-office/assets/49291909/4fd7355f-67d0-438d-a629-29e0fc575ecd)
I am also encountering this occasionally, where the Latin date does not display as I scroll down through my narratives (these are all narratives). If I then click in the text of the narrative it does display above again.

**Comment by lbestock** [comment]
Leaving and coming back seems to work. All of them convert properly originally, it's just down the list that I run into these issues.

**Comment by lbestock** [comment]
How does it know that 89 is 1989 and 23 is 2023 and 24 is 2024?

**Comment by lbestock** [comment]
Not yet applied to Locus Closing.

**Comment by urapadmin** [comment]
ja, that's just FileMaker refresh issues. There is very little I can do about that. It is just crap.

**Comment by lbestock** [comment]
Tiniest weird thing:
If I put in the date American style - 12/23/23 and then a space and the time 8, or 10, it will reject it.
If I put in the date American style and a space and then the time 8:00 or 10:00 it will accept it.
If I put in a date Latin style and then a space, it will accept 8 or 10 as a time and convert it to 8:00 or 10:00.

**Comment by urapadmin** [comment]
> Tiniest weird thing: If I put in the date American style - 12/23/23 and then a space and the time 8, or 10, it will reject it. If I put in the date American style and a space and then the time 8:00 or 10:00 it will accept it. If I put in a date Latin style and then a space, it will accept 8 or 10 as a time and convert it to 8:00 or 10:00.

Latin date has clear advantages

**Comment by lbestock** [comment]
Otherwise works as expected (aside from my severe difficulties to actually type a date in American style). The checklist above has unit narrative twice (once with view) but to my mind this is a redundancy. If I am correct and the discrepancy in the time of day entry by Latin/US date is not a problem, there then this ticket can be closed.

**Comment by urapadmin** [comment]
"unit narrative view" is referring to the new user interface where you can assign images to narratives. If I am not mistaken you can also change the date in there, no?

**Comment by lbestock** [comment]
You can indeed. And it works.

**Comment by urapadmin** [comment]
reopened because of #2451

**Comment by luizaogs** [comment]
Works.
