### ISSUE TITLE
recording app: configuration of ID methods not synchronizing for BUAP

### ISSUE THREAD

**Issue by lbestock** [arch-kiosk/arch-kiosk-office#2418]
I changed all the ID methods in BUAP to free input because it is entirely a legacy project. They were all lost with synchronization. This is high priority (and familiar but I can't find the ticket on a quick search).

**Comment by urapadmin** [comment]
high priority? 
Shouldn't we care for the changes we need in the recording app, first, before subpar data gets entered? Years pass and then all of a sudden it is a crazy rush?

**Comment by urapadmin** [comment]
my suspicion here is that the reason for this is me being in Germany (6 hours ahead).

**Comment by lbestock** [comment]
Years pass and then all of a sudden I have people who are capable of and interested in entering data (which are subpar recording but exciting archaeologically), rather. And this keeps them from working. 

But I changed them myself and then they didn't synchronize, and I'm in the same place as the server.

**Comment by urapadmin** [comment]
but I am not. And I changed them, too, today

**Comment by lbestock** [comment]
And indeed now they are fine once I change them again.
