### ISSUE TITLE
recording app: lots - request to be able to configure ID method and delete lots

### ISSUE THREAD

**Issue by lbestock** [arch-kiosk/arch-kiosk-office#2419]
Entering old BUAP data, on a project that used lots regularly.

It would be very helpful to be able to configure the ID method for lots - we do not always encounter them in order in the record keeping, so making them in the order we encounter them would be helpful.

We also discovered that it is not possible to delete a lot.

**Comment by urapadmin** [comment]
>It would be very helpful to be able to configure the ID method for lots - we do not always encounter them in order in the record keeping, so making them in the order we encounter them would be helpful.

This would be a lot of work. Lots are oooold and have never been converted to our configurable identification system. The lot number simply gets counted up and that's it. That's why I also cannot use our temporary free input system or anything. 
To get to a working solution quickly I would suggest that we introduce a new configuration key that allows you to choose between the automatic numbering and a free input of the running lot number. Would that suffice?

**Comment by urapadmin** [comment]
> We also discovered that it is not possible to delete a lot.

Strangely that was only allowed for developers. I am not sure why. There might have been a reason. I change this to registrar status but please have an eye on it. It might have side effects?

**Comment by lbestock** [comment]
Free input via configuration key would be absolutely enough. And we will test deleting lots and keep an eye on it. I will add the BUAP team to this ticket.

(Abydos, by longstanding tradition, did surface collection on every unit and called it locus 0 lot 0. So....we need to be able to name things zero or we will run into collected material problems.)

**Comment by urapadmin** [comment]
### recording 15.6
- lots can now be deleted by registrars. This feature was already there but strangely disabled so please have an eye on it.

**Comment by urapadmin** [comment]
### recording 15.7
- If the configuration key "lot_auto_generate" is set to "yup" everything should be as usual: automatic lot generation
- if it is set to "nope" the next lot will be generated and you can either accept it in an input dialog or change it there to a different lot number
- you should not be allowed to assign the same lot number twice in the same locus

**Comment by lbestock** [comment]
You get a major grin from the "ach" button.

This works as configured for BUAP and solves the problem. I have not tested the configuration yet so the ticket sticks around at least until after latkes, more probably tomorrow.

**Comment by lbestock** [comment]
All works.

**Comment by lbestock** [comment]
Wow wild. I forgot my own previous system. At Abydos we didn't start over with lot 1 in each locus, on the contrary, at least before we had forms. I will have to look at the form-based recording. But in the notebook days lots were unique within the unit, so it went locus 0 lot 0, locus 1 lot 1, locus 1 lot 2, locus 2 lot 3 on up. And looking at the records that makes perfect sense - it is much easier to keep track of in a running log and also provided another measure of security against human numbering error on tags.

**Comment by urapadmin** [comment]
is that reopening it? Lots are locus bound (and I am not going to change that!) and so are the numbers. The only thing I can offer you here is something like an alternative number for lots where you could add the original lot number. But that a structural change, Is that really necessary? I mean, if they add the actual lot number you just come out with non-sequential lot numbers attached to the locus id. Looks weird but the original information is at least there.

**Comment by lbestock** [comment]
Oh no, I did not reopen it because I don't want anything else on this front. The ability to give the original lot numbers is right and proper. But I am making a note of it because I find it interesting and this is part of the recording. Also I would like to be scrupulous in recording our actions around inputting the legacy data from Abydos. This is already proving very interesting and I have a strong suspicion I want to give an ARCE paper next year about using Kiosk to digitize legacy data with Abydos as the example.

**Comment by urapadmin** [comment]
I am not sure if making notes of that sort in closed tickets about the recording software make much sense, though.
