### ISSUE TITLE
BUAP: importing CM records from the old Abydos object database

### ISSUE THREAD

**Issue by lbestock** [arch-kiosk/arch-kiosk-office#2420]
The CM database for Abydos North was kept in common between multiple projects. It is a FM database, a very basic one. I hope it will be possible to bring these records into Kiosk instead of creating them all again?

I think that doing concordance will be easy; some fields are unnecessary in Kiosk at the CM level (eg excavator) and most are a straight map into CM. Since it was a database held in common, it includes a lot of material that is not BUAP. It is easy to separate out as the site field in the database is different (two sites were dug by the BUAP; neither was dug, up to that point, by anyone else who used this database, and I only have the database up to the point where I stopped digging). And of course the relevant units and loci won't be in there unless they are BUAP CM.

How can this be done?

The database itself has been converted to a modern file and can be read now in FM 19. It has been put in the BUAP GoogleDrive. 

#### import of all records
- [x] #2464
- [x] we keep material "sample" as a bulk type and not make a cm_type sample
- [x] we skip material "VOID" records entirely
- [x] map fields from ANC onto Kiosk fields
- [x] normalize material_1 and material_2
- [x] parse number and unit from weight and turn into grams
- [x] if "object" is set create small find types from nouns in the notes
- [x] Photo number and Drawing number: Only import a boolean "drawing" or "photo" in first step.
- [x] format ANC# 
- [x] Turn "drawing" and "photo" into "to be drawn" and "to be photographed" states
- [x] object? -> cm_type "small find" otherwise "bulk"
#### collected material creation on locus availability
- [x] as soon as a locus and lot that a collected material from the ANC-DB is connected to appears, the ANC-DB record is imported. This only gets triggered on BUAP as it is a project specific plugin.
- [x] #2480 
- [x] #2479 
- [x] #2478

**Comment by urapadmin** [comment]
I'll have a look at it. Should be possible, so for the time being you should avoid entering any data that we would import from that database.

**Comment by urapadmin** [comment]
As a general note: Not much there. "partial falcon mummy" is all there was to say about a partial falcon mummy? 

Poking around I run into a lot of chaos about ANC# numbers being moved from bags to objects (where object is NO) etc... So very mixed quality. 

So my question is: What part of those records is the part that has relevance? 

The main difficulty is as usual that we cannot import a collected material (and that's all we have here, right?) if there is no locus there in the first place to attach it to. Where would those loci come from? I can generate them but they'd be all empty loci with really no datum (not even an opening date or an excavator). Is that helpful?

**Comment by lbestock** [comment]
This is only collected material. 

What would be most useful is a way to easily run it over and over again where it only imports records for which there are indeed loci. Having the CM without the loci makes no sense indeed. We definitely need this albeit scanty data in the BUAP Kiosk. Those are the CM. We will have photos to attach to some of them. And while scanty, the registrars did make notes in that database that are not anywhere else and should not be lost.

Ideal: we are inputting OPs. When we are done with each one, we run the import of the CM, which brings in anythign that can be attached to these newly made loci. We can then check that all the CM of that OP are in there before moving on to the next OP. Each OP notebook has a list of the ANC#s associated with it, against which to check the import. And we do this every time we complete an OP.

**Comment by urapadmin** [comment]
I see. Well, we could hook this as a BUAP-specific module (that I would have to develop first) into synchronization. The result would be that after you synchronize, Kiosk would try to import more data from the BUAP database. That's like having your freshly added locus relations rectified as part of synchronization. 

what are OPs?

**Comment by lbestock** [comment]
OPs are units.

I think it really would be helpful for this project at least, which is real. There are thousands. It is not impossible it would be relevant for other legacy projects. Object databases were used long before any other type of digital recording by a lot of people.

**Comment by urapadmin** [comment]
it will just be always totally different for other legacy projects. That is the kind of thing that always needs project-specific development. It cannot possibly be generalized because of the vastly different input formats and requirements. Think about USTPs import request. Entirely different. 

But that's why Kiosk can have project-specific modules hooked up without affecting other projects.

the questions is: When do you need this? This isn't exactly difficult but it is work and needs testing etc. So it will keep me occupied a few days.

**Comment by lbestock** [comment]
It is not so super urgent. I don't have a sense yet of how fast @maychu16 and @hschaef1 are going to be able to digitize things. Certainly we don't need it before they get to the end of their first physical notebooks, and even then I think we would not be slowed down to wait. In a few weeks?

**Comment by urapadmin** [comment]
do you have a sense now when you'd want this?

**Comment by lbestock** [comment]
Sooner rather than later. May has input a lot of stuff and we can't be done with any OP until the CM are in there.

**Comment by urapadmin** [comment]
alright. Then that is next before HM.

**Comment by urapadmin** [comment]
on it.
First issue: The FileMaker database is using an FM concept called "repeating fields" which, erm, should never have existed in the first place. Repeated fields store more than one value in a single field. So although your database has only one "photo nr field" a record can have multiple value in that single field. Pretty horrifying. 

I caught it being used in ANC#03645 for Photo numbers. It is also potentially being used for drawing numbers. Apart from these two I can't see it being used again. 

So the question here is: Do you need all drawing and photo numbers? The first value of such a field would be exported by FileMaker and so can be imported into Kiosk. Subsequent values of the same field would not. Unless I put some effort in here.

**Comment by urapadmin** [comment]
next issue: The ANC number is a number field that FM miraculously allows to have a leading zero. Classic. That should not have been a number. Do you need that leading zero?

**Comment by urapadmin** [comment]
all measurements, although numbers again in FM, have the unit (cm, mm) included. So those are not numbers anymore and we would not be able to import them without further transformation into Kiosk. We need to decide what to do here.

**Comment by urapadmin** [comment]
"VOID" appears several times in the "material" column (and only there, it seems). What do we do with those?

**Comment by urapadmin** [comment]
- [ ] introduce new material field (further specification of the material)
- [ ]

**Comment by urapadmin** [comment]
### Kiosk 1.5.20
- we need to test this! I will make a test server ..

**Comment by luizaogs** [comment]
If you guys want me to help with testing this (which I can, if that would be helpful) I think I will need a bit of an explanation...

**Comment by urapadmin** [comment]
> If you guys want me to help with testing this (which I can, if that would be helpful) I think I will need a bit of an explanation...

Thank you. But testing this needs the Abydos journals, so with this we are on our own 🌵 .

**Comment by urapadmin** [comment]
since we set the modification and creation dates to the original Abydos dates the Director's view cannot see that something was going on today. So no, it should not.

**Comment by urapadmin** [comment]
no, I don't. I need to transfer it to the real BUAP

**Comment by urapadmin** [comment]
### Kiosk 1.5.20.1 and recording app 15.12.1 rolled out to @arch-kiosk/buap 
- after the tests in buap-test were successful this is now available for BUAP proper
- the collected materials for the existing loci and lots are already transformed into collected materials

**Comment by urapadmin** [comment]
I must reopen this because there are bugs
