### ISSUE TITLE
recording app legacy data images: a way to get date from file when placing files in FM rather than importing?

### ISSUE THREAD

**Issue by lbestock** [arch-kiosk/arch-kiosk-office#2425]
BUAP is digitizing old data. One thing this means is attaching photos that had been in folders that are only sorted by the date directly into records. This is so far easiest while in the recording itself, and I expect that to remain the case since our digitizers are not familiar with the material and not all images have labels in them. But unlike with an import, when a photo is brought in this way (as a file, since they are NEFs) then its original date is lost. That will lead to chaos in the File Repository and throws out an important piece of information (in fact the only one that was originally attached to the photo files). So far I have been going in and changing them all, but not only is that inefficient it also risks errors.

Is there a way we could set it so that files or images added to the recording app get their original date, not the date of the image container's creation?

**Comment by urapadmin** [comment]
we have decided on a different strategy here:
- with #2427 ready we will import the images through the normal file import first
- in the gallery we can find the files by the date they were shot (which the file import has to set properly) and apply them to a context
- #2428 is a potential improvement that would allow using the file repository to look at the images and then the short id to find an image quickly in the gallery. But we wait with that for now.

**Comment by urapadmin** [comment]
@lbestock Next is setting up the import and doing some trial run with a smaller unit

**Comment by lbestock** [comment]
It will be by date, not by unit, necessarily. Let's start with December 2008. That is when OP145 was opened and that's a notebook I have here at home.

**Comment by lbestock** [comment]
Has worked well for @lbestock inputting BUAP stuff. Instructions now sent to @maychu16 and @hschaef1 and this ticket can be closed.
