### ISSUE TITLE
recording app: gallery expansion for legacy data input

### ISSUE THREAD

**Issue by lbestock** [arch-kiosk/arch-kiosk-office#2427]
BUAP is making us think about legacy data imports.
How to get the images in, both in terms of workflow and assigning the correct original date to them, is a challenge.
We have ideas!

- Get the images into Kiosk with the correct dates via an import using folders for date - this is how they are already sorted.
- Get the thumbnails of the right dates into the recording app using file picking.
- Put the images into containers using the gallery.

How to get the images from the gallery into the image containers is the part that will need @urapadmin to design some new stuff.

The two things we need first off are:

1. show date of image (not file creation!) in the gallery
2. sort the gallery by date

Additionally we have spoken of a way to create a short in the file repository that can be used to search in the gallery for a specific image.

**Comment by urapadmin** [comment]
3. was showing an image in a more useful size in the gallery on click or so

**Comment by urapadmin** [comment]
### recording 15.8
- you can now sort in the gallery (e.g. by the date and time when the file was shot)
- the date and time when the photo was shot is shown as a little yellow label on the image in the gallery
- you can search for a date (this accepts latin dates)
- if you click on an image it is show a bit larger (there isn't that much space, unfortunately)
-

**Comment by lbestock** [comment]
The sort by date is for when it was added, not when the file was shot. Likewise the yellow label is the added on date.

**Comment by lbestock** [comment]
Ah, no I misunderstood a bit. I can sort either by added or by shot. What is the rationale behind added being descending and shot being ascending? 

The label is indeed the added on date, not the shot on date.

The larger size popup is helpful.

The search by Latin date works. The search by US date does not seem to (I tried the same date both ways and did not get the same results).

**Comment by urapadmin** [comment]
> The label is indeed the added on date, not the shot on date.
That one I can't confirm. I double checked and I am using the right database field at least. Any possible test data issues that might mislead you to this assumption?

**Comment by urapadmin** [comment]
> Ah, no I misunderstood a bit. I can sort either by added or by shot. What is the rationale behind added being descending and shot being ascending?

I just felt that when sorting by added (that's more when in the field) it makes sense to have the latest on top in order to find the latest quickly). So needs descending. 
I did not feel the same about the date when the file was shot (that's usually when dealing with imported stuff).

**Comment by urapadmin** [comment]
### 
- The search by US date does not seem to (I tried the same date both ways and did not get the same results).
This FM Bug is really severe. It forces a us date into a European date no matter what I do. So I get things lks 07.17.2021 which isn't even a valid European date. It is just nonsense. I have now added a pretty bespoke US date parser which reacts to a slash. So whenever somebody writes a date with a slash, it will be interpreted as a US date and, believe it or not, I switch month and day and feed a wrong date to FileMaker to get the right one out. Aaaargh.

**Comment by lbestock** [comment]
I will test the latter when you release it! But I can confirm now that the "shot on" date for things coming in through the File Repository is as wanted.

**Comment by urapadmin** [comment]
> But I can confirm now that the "shot on" date for things coming in through the File Repository is as wanted

I don't understand.

**Comment by lbestock** [comment]
This was just the thing that I misunderstood and was getting the "added" date where I expected the "shot on" date because of how I was getting the images into the recording. Having now done what I was supposed to through the file import, I can attest that that part of this ticket was working. 

But I am still having trouble with the American date search in the gallery (this is 15.8.2):
10/8/22 returns the same results as 8X22, as I expect.
1/24/08 returns no results, nor does 01/24/08, or 01/24/2008, but 24i08 does.

**Comment by urapadmin** [comment]
> 1/24/08 returns no results, nor does 01/24/08, or 01/24/2008, but 24i08 does.

Try 1/24/2008. Does that work?

**Comment by lbestock** [comment]
Now 15.9:
Same problem searching for American date as noted above with 15.8.2.

**Comment by lbestock** [comment]
> > 1/24/08 returns no results, nor does 01/24/08, or 01/24/2008, but 24i08 does.
> 
> Try 1/24/2008. Does that work?

No.

**Comment by urapadmin** [comment]
### recording 15.9.1
- ja, I was using the easy path. New attempt...

**Comment by lbestock** [comment]
Works.
