### ISSUE TITLE
recording app: restore session record on start up

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#2432]
coming out of #2431:

if the session record is absent or there are two, recover the situation on start up.

_Originally posted by @urapadmin in https://github.com/arch-kiosk/arch-kiosk-office/issues/2431#issuecomment-1867130914_

**Comment by luizaogs** [comment]
How does one test this?

**Comment by urapadmin** [comment]
it is hard because we don't know how May managed to delete the session record. One way of doing it might be using FileMaker on Mac as a registrar. I think in that case you have access to the FileMaker menu. And then you might be able to be on the start page and delete the current record. It might even be possible to use the DEL key to delete the current session on the start page. 

After the record is deleted you can't select anything anymore. On next start of the database everything should be back to normal.

**Comment by luizaogs** [comment]
I tried pressing delete while on the start page but I can still select a site after doing so, so I don't think this is what you want...

**Comment by urapadmin** [comment]
no, it isn't. Delete doesn't work indeed. I wish I had an idea how May managed to delete the session record.
However, you should have a record menu when logged in as admin:
![image](https://github.com/arch-kiosk/arch-kiosk-office/assets/38838314/dfa08e66-0beb-4fa5-b2e0-458098610f8a)
There's a delete record that should get you to the state that looks like you have lost all data. And then after a restart everything should be fine.

**Comment by luizaogs** [comment]
Yep.

**Comment by maychu16** [comment]
I was going back and forth between filemaker and safari. I used Command + T to open a new tab in safari but my swipe didn't fully take me to safari and my laptop was still on filemaker window and Command + T key was pressed. That was when I got the error message that records can't be saved.

**Comment by urapadmin** [comment]
good you found that out! We

**Comment by urapadmin** [comment]
### recording 15.9.2
- that's done. It should be even enough to go back to the start page. But that's hard to test now that CMD+T isn't an option any more in most layouts. So I simply close this.
