### ISSUE TITLE
Kiosk: Cannot Open "record details for other" for locus type

### ISSUE THREAD

**Issue by maychu16** [arch-kiosk/arch-kiosk-office#2433]
I don't know if it is a bug or I am not supposed to type anything in this box. I selected Other and wanted to type in something but the detail record box won't open. 

<img width="1512" alt="Screenshot 2023-12-22 at 11 38 32 PM" src="https://github.com/arch-kiosk/arch-kiosk-office/assets/153842762/8a7edc71-6f29-447a-b337-dddb9a9e1863">

**Comment by urapadmin** [comment]
@lbestock this might raise the general question what to do with "other" and what the specific locus was. We got rid of the other description because you don't want other types. 

Apart from that the fact that the button here is visible is a configuration issue for BUAP that I'll attend to. You are indeed not supposed to see the button.

**Comment by lbestock** [comment]
On the general front, I tend towards treating "other" like the kind of thing in a store that the checkout kid can't actually ring up without a manager's override. To my mind it is usually a sign of not making up one's mind or being clear on the part of an excavator and needs a consultation with the director, not a permanent status of "other", which is then unusable as data. As such it should barely exist at all and shouldn't be given opportunities for excavators to define new types of others, etc. I would get rid of it entirely but that I suspect someone would complain.

It is interesting to think about it, though, with legacy data. No more possibility of calling the director over to the trench and discussing what kind of locus it really is. 

In this case @maychu16 the archaeological part let's deal with via email. Shoot me a line so we can discuss what kind of locus this one is, and if we want to standardize something for the BUAP digitization. There are legitimate fuzzy areas around whether or not, for instance, a coffin is its own locus.

**Comment by urapadmin** [comment]
on the specific front I have configured "other" so that it does neither show the button for the detailed record nor offers to select a type of other. It is just "other" and that's it now.

**Comment by urapadmin** [comment]
please close this when you think it is done.
