### ISSUE TITLE
Recording: Photos not showing?

### ISSUE THREAD

**Issue by maychu16** [arch-kiosk/arch-kiosk-office#2436]
I am trying to put photos into the recording app now. When I click images/unit narrative and then + button and then insert file, it lets me insert the photo but it doesn't show me the photo I inserted. It just shows me an icon and the name of the file. But in Laurel's Op, it shows the photo. 

Oh...I did "insert photo" and then it finally shows the photo (but not the .NEF file extension photos that are in the drive, I tried with a screenshot) but Laurel said do it with "insert file" because these are large raw photo files. 

Please let me know how to proceed with these. Does it matter that the photo can't be opened in the recording app? 

<img width="1512" alt="Screenshot 2023-12-24 at 8 10 36 PM" src="https://github.com/arch-kiosk/arch-kiosk-office/assets/153842762/37e5f29e-3c13-41c9-a60f-f09cd31a3ae3">
<img width="1512" alt="Screenshot 2023-12-24 at 8 10 46 PM" src="https://github.com/arch-kiosk/arch-kiosk-office/assets/153842762/96feb791-f95e-4507-90fb-7619c4d6f5c0">
@lbestock

**Comment by maychu16** [comment]
ah nevermind, I commented too soon...after I synced it to the hub and downloaded it again, the photos show up in the recording app

**Comment by urapadmin** [comment]
yes, this is what is expected. FileMaker cannot show NEF files. During synchronization Kiosk stores the NEF file but also generates JPG thumbnails and next time you prepare your dock you get that thumbnail instead of the original NEF. 
That's just for background. Everything okay here.
