### ISSUE TITLE
Kiosk: Warning

### ISSUE THREAD

**Issue by maychu16** [arch-kiosk/arch-kiosk-office#2437]
I don't know what this mean. I am just reporting it since it tells me to. 
<img width="1512" alt="Screenshot 2023-12-24 at 8 33 56 PM" src="https://github.com/arch-kiosk/arch-kiosk-office/assets/153842762/c1a9a383-f9c0-46c3-a4df-62e9de0eb21b">

**Comment by maychu16** [comment]
I guess this is because I went into the file repository and change the date of the photo taken

**Comment by urapadmin** [comment]
yes, that would be a reasonable explanation. This is really a safety catch that can indicate some issue in the field where the synchronization turnarounds have more time between them.
