### ISSUE TITLE
Kiosk: Can't change photo date

### ISSUE THREAD

**Issue by maychu16** [arch-kiosk/arch-kiosk-office#2438]
I was in the file repository in Kiosk trying to change the date of the photo taken. It worked fine when I was changing the date taken to 30.XII.2010 etc but when I tried 1.I.2011 or 2.I.2011, the system is giving me an error. 
<img width="1512" alt="Screenshot 2023-12-24 at 9 58 21 PM" src="https://github.com/arch-kiosk/arch-kiosk-office/assets/153842762/dcd149ea-5c55-49f0-88fb-8578eebece6e">

**Comment by maychu16** [comment]
ahh..I was just dumb. I tried 01.I.2011 and it worked

**Comment by maychu16** [comment]
ahh..I was just dumb. I tried 01.I.2011 and it worked

**Comment by urapadmin** [comment]
It is not just dumb. In the recording app we would accept 1.I. and not need a leading zero, so this could be improved in Kiosk itself. Let's leave it open.

**Comment by urapadmin** [comment]
### kiosk 1.5.16
- this allows for single digit days and months now (e.g. 28/2/1973 or 28 II 1973)
- it also allows for two-digit years and everything greater than the current YY plus 3 will be turned into 1 1900 year while everything below to a 2000 year. For instance 73 will be 1973 and 24 will be 2024
- latin dates can either be written with a dot or a space as separator. So 1 II 73 equals 1.II.73

What isn't allowed is writing a Latin date without a separator. So 1II73 will be accepted as 01 February 1973 in the recording app but not here in the file repository.

**Comment by luizaogs** [comment]
This should have worked, no?

<img width="1473" alt="Screenshot 2024-01-02 at 10 09 16 PM" src="https://github.com/arch-kiosk/arch-kiosk-office/assets/67970402/94ba695b-d200-4133-ad24-d9bf05e21299">

**Comment by luizaogs** [comment]
<img width="373" alt="Screenshot 2024-01-02 at 10 24 11 PM" src="https://github.com/arch-kiosk/arch-kiosk-office/assets/67970402/efa72297-0e0e-4521-8104-bdb197b85aa6">

**Comment by luizaogs** [comment]
Typing two digits 73 gave me 2073 instead of 1973: 

<img width="385" alt="Screenshot 2024-01-02 at 10 25 23 PM" src="https://github.com/arch-kiosk/arch-kiosk-office/assets/67970402/ef8cd69c-43c4-4970-a97c-4000cf461b7e">

**Comment by luizaogs** [comment]
The rest is ok I think.

**Comment by urapadmin** [comment]
> <img alt="Screenshot 2024-01-02 at 10 24 11 PM" width="373" src="https://private-user-images.githubusercontent.com/67970402/293845680-efa72297-0e0e-4521-8104-bdb197b85aa6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQyOTk0NDcsIm5iZiI6MTcwNDI5OTE0NywicGF0aCI6Ii82Nzk3MDQwMi8yOTM4NDU2ODAtZWZhNzIyOTctMGUwZS00NTIxLTgxMDQtYmRiMTk3Yjg1YWE2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTAzVDE2MjU0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZjMzMwMjc1YjU2MGY3ZWJlOTc0ZmI0NjIyMzAxZDRhMjg3MzFlMzgzNzIxOWVmZjUyMjY5OTMyYjFlMzNhOTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.QAG6nnNuEU7jGA-LIHd49wo7C9Hb9XbmHPAPQFt8P0w">

that was due to my bad example. 2/28/1973 is accepted.

**Comment by urapadmin** [comment]
### Kiosk 1.5.16.1
- 73 should be 1973 now
