### ISSUE TITLE
kiosk file repository: search by date, not just sort by date

### ISSUE THREAD

**Issue by lbestock** [arch-kiosk/arch-kiosk-office#2439]
As we greatly expand the use of dates with images in response to inputting legacy data from BUAP, it strikes me that it would be useful to be able to search in the File Repository by image date, not just to sort by it. If the date one wishes to see images from is in the middle of the range then using pagination to get there is a pain.

**Comment by urapadmin** [comment]
### Kiosk 1.5.16
- the file repository has two new filter fields: From and To. You can add all kinds of dates that follow the format explained in #2438 
- Additionally you can just type in a year here in the file repository.

**Comment by luizaogs** [comment]
This should have worked, no? 

<img width="1473" alt="Screenshot 2024-01-02 at 10 09 16 PM" src="https://github.com/arch-kiosk/arch-kiosk-office/assets/67970402/66dbf31f-99c4-41fd-9bef-b15690a02b60">

**Comment by luizaogs** [comment]
And this? 

<img width="1472" alt="Screenshot 2024-01-02 at 10 15 42 PM" src="https://github.com/arch-kiosk/arch-kiosk-office/assets/67970402/58034e9e-344a-4158-bbfb-3f1337650d09">

**Comment by luizaogs** [comment]
The rest of the possibilities as explained in #2438 are working.

**Comment by urapadmin** [comment]
### Kiosk 15.16.1
- 73 should be interpreted as 1973 now

**Comment by luizaogs** [comment]
Oh funny :) I was copying the example you gave in #2438

**Comment by urapadmin** [comment]
> Oh funny :) I was copying the example you gave in #2438
> 
> Yes, 2/28/2021 works.

Ja, I should not give examples, anyhow. Testers tend to use them instead of mad up data. The issue with that is that the examples are usually the dates I tested myself, except for the month / day mistake I made here. So it is always a good idea to take my examples as illustrations of the rule but use different data, too.

**Comment by luizaogs** [comment]
Well I changed the year :) 11pm post-almost-fainting Luiza was not very creative. But I'll keep that in mind.

**Comment by urapadmin** [comment]
🍫 👀

**Comment by lbestock** [comment]
This is not working as I expect it to in URAP.
A search for 1/19/19 returns 759 files, not all of which date to 19 January 2019.
A search for 19I19 is an invalid date form and I thought Latin dates could be done like that, no spaces.

**Comment by urapadmin** [comment]
### Kiosk 1.5.34.1
- latin dates like "1X23" should work now
- if the year is a two-digit year that is more than 3 years in the future (so in the year 2024 it would be 28), it is interpreted as a 1900 year. So 27 -> 2027, but 28 -> 1928. That's not limited to latin dates, it is a general rule for two-digit years.

**Comment by urapadmin** [comment]
> A search for 1/19/19 returns 759 files, not all of which date to 19 January 2019.

That's not how it works. If you type 1/19/19 in the from field only you'll get all files that are from that date **or later**.
If you want all files from exactly that date, you have to type the 1/19/19 in both ´the from-date and the to-date fields. If you type a date only in the to-date field, you'll get all files from before or on that date but none later than that.

**Comment by luizaogs** [comment]
I believe this is working.
