### ISSUE TITLE
kiosk: changing colors of pictures???

### ISSUE THREAD

**Issue by luizaogs** [arch-kiosk/arch-kiosk-office#2440]
Uh. Help. We noticed when inserting pictures into the report that the ones downloaded from Kiosk have an orange tint to them, one that is missing from pictures taken straight off the SD card. Is this possible? That would mean that I would have to reimport everything and I don't even want to contemplate that possibility. 

Three examples below. All orange ones are from the database, all normal looking ones are from the SD card.

Example 1: 
![WhatsApp Image 2023-12-27 at 19 47 06](https://github.com/arch-kiosk/arch-kiosk-office/assets/67970402/b73cca8a-9503-4f9e-ab63-11a927c37d9c)

![WhatsApp Image 2023-12-27 at 19 47 12](https://github.com/arch-kiosk/arch-kiosk-office/assets/67970402/c2ea2513-2ba6-4241-9568-58332ee53aae)

Example 2: 
![WhatsApp Image 2023-12-27 at 19 47 31](https://github.com/arch-kiosk/arch-kiosk-office/assets/67970402/00fec52b-aa2b-4ae9-9dc8-ae63504f34e6)

![WhatsApp Image 2023-12-27 at 19 48 56](https://github.com/arch-kiosk/arch-kiosk-office/assets/67970402/3ec29f89-a7dc-4ba1-975f-4a69e0317347)

Example 3: 
![WhatsApp Image 2023-12-27 at 19 49 34](https://github.com/arch-kiosk/arch-kiosk-office/assets/67970402/2207ab58-1179-41f0-90f1-d8eb38472223)

![WhatsApp Image 2023-12-27 at 19 49 46](https://github.com/arch-kiosk/arch-kiosk-office/assets/67970402/44229702-0525-49d8-90ac-2d7983d5fa05)

**Comment by luizaogs** [comment]
A less extreme example, but still clearly showing a color change from gray to orange: 

![WhatsApp Image 2023-12-27 at 19 58 19](https://github.com/arch-kiosk/arch-kiosk-office/assets/67970402/c4cd95bf-16e1-420e-8eb9-273084f47bae)

![WhatsApp Image 2023-12-27 at 19 58 24](https://github.com/arch-kiosk/arch-kiosk-office/assets/67970402/e0828639-33b7-4923-bea2-80acd1fd1a06)

**Comment by luizaogs** [comment]
Ok Jesus. I just had a heart attack but I have now downloaded one of the original files (it's a NEF) and it looks fine. So the issue is when I download the JPEG 1024X768 screen size file. 

BUT, more problematically, the thumbnails in the file repository are all bright orange. So downloading the originals works, but something is going on in the file repository in that the images are changing colors.

(We tested changing a NEF to a JPG outside of Kiosk, and there the color also changed. But very slightly. It gets slightly ever so slightly darker, not ORANGE.)

**Comment by urapadmin** [comment]
that's strange that this never happened before. We are even using webp for thumbnails at this point,  thought. 
I'll look into the thumbnail issue - but never worry about your raw files - they are always safe because I deliberately never process the original files.

**Comment by urapadmin** [comment]
can you please send me one raw file? Or are you using jpeg for your raw file format and I can use one of the above jpegs?

**Comment by urapadmin** [comment]
this does not happen to thumbnails of photos that were made with the FileMaker?

**Comment by luizaogs** [comment]
Raws are all NEFs. I’ll send you one and check on the FM images after I get back from site today.

**Comment by luizaogs** [comment]
I am uploading a NEF to the drive now.

**Comment by luizaogs** [comment]
And yes, the pictures taken with the iPad in FM have the same issue:

This first one is the original file, redownloaded from Kiosk and it looks as it should. 
![original](https://github.com/arch-kiosk/arch-kiosk-office/assets/67970402/3d351c1d-d39f-41af-b000-a1a0874bffda)

This second one is whiter in color, as you can clearly see in Inês' face, so the color has changed. This is the thumbnail that appears in the file repository, too. So the thumbnail is the modified file.
![jpg2](https://github.com/arch-kiosk/arch-kiosk-office/assets/67970402/6d3bf1d1-146d-4d25-827c-9daa9dc11e87)

**Comment by urapadmin** [comment]
I might be getting old but I have trouble seeing a striking difference between those two. For my eye the difference is within an acceptable range. Much unlike the ones above.
We have meanwhile looked at URAP and found that the same issue occurs there. Funny how this has never bothered anybody enough to mention it. Some early step in compressing and scaling down must be tampering with the colour map.

**Comment by luizaogs** [comment]
I mean, there is a difference - whether it is acceptable or not is another issue, I suppose :)

**Comment by luizaogs** [comment]
(Also, I am sorry - I feel like I've been super annoying this season. Kiosk has been wonderful. I hope the many annoying requests have not made you think otherwise.)

**Comment by urapadmin** [comment]
acceptable as in way beyond the difference that you will see across different screens, anyhow. But I do suspect that battling the more striking examples will solve this one, too. 

(I have now hidden you guys because I try to keep our GitHub free of personal information).

**Comment by urapadmin** [comment]
> (Also, I am sorry - I feel like I've been super annoying this season. Kiosk has been wonderful. I hope the many annoying requests have not made you think otherwise.)

I have not seen any unreasonable request from your side :o) You know how happy I am about constructive feedback. And having experienced how terrible my mood becomes in the desert under subpar circumstances I have a lot of patience for people in the field. But you know all that :o)

**Comment by luizaogs** [comment]
Hm. If you say so.

**Comment by urapadmin** [comment]
This will be harder to find and I am trying to set priorities. Do you need this fixed, soon, or are you on to something else, anyhow?

**Comment by luizaogs** [comment]
No, since downloading the originals means no orange pictures I do not need it soon.

**Comment by urapadmin** [comment]
the problem is extreme in BUAP: I guess I should rather look into it.
![image](https://github.com/arch-kiosk/arch-kiosk-office/assets/38838314/a8551a36-affd-4db7-8c82-13312ec29b67)

**Comment by lbestock** [comment]
Harpocrates got jaundice :)

**Comment by urapadmin** [comment]
I have a hunch that this happens with the webp format in particular. The first thing I should try is going back to jpg with the 1024x786 version.

**Comment by urapadmin** [comment]
- the webp filter is not responsible for this because the master representation is already orange.

**Comment by urapadmin** [comment]
updating rawpy, numpy and pillow did not help

**Comment by urapadmin** [comment]
this seems helpful on the orange front:
- https://github.com/letmaik/rawpy/issues/118#issue-668716894

It appears that we might never really get a optimal colour in the representations because that seems widely a question of interpreting the camera settings of different manufacturers. But with this I got better results for the very orange BUAP thumbnails.

**Comment by urapadmin** [comment]
I tried to use the camera's white balance but although that looks a bit better, the auto white balance looks more accurate on the white front to me:
**camera white balance**
![orange-camera-wb](https://github.com/arch-kiosk/arch-kiosk-office/assets/38838314/8c68c37e-1f8c-4ffc-afc1-680923e21b7c)

**auto-white-balance**
![orange-auto-white-balance](https://github.com/arch-kiosk/arch-kiosk-office/assets/38838314/ebd140cc-cd0e-44b6-b5d0-30e2e952d2ea)

**Comment by urapadmin** [comment]
but here is a screenshot of the NEF displayed by Windows:
![image](https://github.com/arch-kiosk/arch-kiosk-office/assets/38838314/646b447b-619f-4b20-a112-ca8bdc670768)

**Comment by urapadmin** [comment]
So using the camera's white balance does not lead to the whitest white but that's what Windows and Affinity do. Using the auto white balance might even come closer to what the camera originally shot. Clearly, making photos needs a calibration strategy if colour is of the essence.

**Comment by urapadmin** [comment]
### Kiosk 1.5.20.7
- did that. The standard for opening raw files is now the camera white balance, which is warmer than the alternative:
- when the representation calls for a manipulation "AUTO_WHITE_BALANCE" the result should be the whiter and paler version of a thumbnail. 
- When applied to the master representation the outcome is that all other thumbnails based on that master will have the same color

**Comment by urapadmin** [comment]
while I think this is solved now, applying it means to render all thumbnails again and that takes hours.
We need a tool that does that quietly in the background before we let this loose on PACHA (> 7000 files).
But that's for another ticket:

**Comment by urapadmin** [comment]
So this was a clear issue of converting NEFs to JPGs. But I am not sure if all of the photos your were unhappy with actually were NEFs. At least the photo with you and Înes seemed to have been a JPG. I downloaded that one, too and I cannot "see" (maybe one should use a tool) a difference between what Windows shows me in a preview of the original file and what Kiosk creates as a preview window for the file edit dialog. Can you look into that one again, please? Or was there a NEF and a JPG version?

**Comment by urapadmin** [comment]
It seems all the examples up there are jpgs? That confuses me.

**Comment by urapadmin** [comment]
okay, I read our thread again. Apparently that I see a JPGs in here is because you had to convert them and the difference occurred with the NEFs. 
But photo with Înes and you is a JPEG in Kiosk in its original. So I am still a bit confused (although that's the one where I was hard pressed to admit a difference back then).

**Comment by luizaogs** [comment]
The photo with Inês is a JPEG because you asked me to check if the difference also happened with original JPEGs, not NEFs. For that one, there was a small difference but one you did not think was very visible/significant.

**Comment by luizaogs** [comment]
Ah no, you wanted me to check if the issue happened with photos made in FM (so taken with the iPad). That's why that one was a JPEG.

**Comment by luizaogs** [comment]
(Sorry, should I have closed this? The JPEG one looks ok to me, so if there is a difference it seems indeed to be small.)

**Comment by urapadmin** [comment]
I stared at the Înes and you photo and did all kinds of things to get an unbiased view on it. In the end to me the Kiosk version is if anything paler than the original JPG. And some ever so slight difference between a highly compressed and a not so compressed image is inevitable. I find it okay. I would even use that Kiosk JPG in a presentation without noting a problem.
But if you find an image that was originally a JPG and is off in color in Kiosk's preview image (the bigger one in the file edit dialog), please let me know. For now we keep this closed.
