### ISSUE TITLE
recording app: show and manipulate date when photo was shot

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#2441]
For legacy data input it makes sense to have the date when a file was shot available both to see it and to manipulate it right in the app.

**Comment by urapadmin** [comment]
### recording app 15.9
- gallery: shown on all images in the gallery and can be manipulated on the second page of the pop-over
- dayplans: can be seen and manipulated in the pop-over. Also the little green/yellow record information button in dayplans shows the date when being clicked on
- same in loci as in dayplans

**Comment by lbestock** [comment]
All of this works properly and synchronizes properly. I appreciate that it is possible and that it is not all that easy to change. Definitely needs a paragraph in the user's manual.

**Comment by urapadmin** [comment]
not only that, I think that @maychu16 and @hschaef1 should know about this feature. You don't have to go through the file repository anymore to change the date when the photo was shot!
