### ISSUE TITLE
kiosk: show time zone in hub for workstations

### ISSUE THREAD

**Issue by lbestock** [arch-kiosk/arch-kiosk-office#2442]
It strikes me that it might be helpful to be able to see if a time zone is set for a workstation, if that could be displayed easily.

**Comment by urapadmin** [comment]
### kiosk 1.5.16
- time zone setting showing as part of the dock's description now. But only if set.

**Comment by luizaogs** [comment]
Oh wow super helpful. I always forget when I have set mine and can never remember if it's Brazil, Chicago, CA, Egypt ...
