### ISSUE TITLE
kiosk: import of files with multiple identifiers

### ISSUE THREAD

**Issue by luizaogs** [arch-kiosk/arch-kiosk-office#2443]
Trying to import archival images into the file repository. Many of them need to be assigned to multiple contexts and I thought it would be possible to do that using file names but so far I have been unsuccessful. I've tried separating identifiers with semicolons and commas and nothing has worked. Which makes me think that maybe this is not supported? Is that possible? Would it be possible to implement, if it is not supported yet? Or am I just being incompetent? I didn't find an answer in any manuals or tickets so here I am.

**Comment by urapadmin** [comment]
no, this is not implemented. And a major request. That would need a major change of the whole architecture of the file import.
Would implementing #929 be an alternative?

**Comment by luizaogs** [comment]
If it's a major request that would give you trouble it probably doesn't make sense - though I am somewhat surprised I am the first to need it. #929 would help in such cases, yes. For now I guess we will do it manually.

**Comment by urapadmin** [comment]
No, we are really talking about at least a week of work and turning something that works upside down. 
Assigning images to multiple contexts in and of itself is not very common in other projects. They usually shoot the same thing over and over again or leave it in only one place. You are actually the first to use that extensively. 
I can't raise your hopes for a quick solution on assigning bulk contexts, either. There is a reason that ticket is so old. It is a hard one.
So, yeah, manual it is 😬

**Comment by luizaogs** [comment]
It's fine. I just thought I was being dumb and missing an obvious thing. So I will close this, then.
