### ISSUE TITLE
kiosk: MADP server transfer

### ISSUE THREAD

**Issue by luizaogs** [arch-kiosk/arch-kiosk-office#2444]
Transfer files please :) I might try to do it tomorrow before I fly because having it only on the local server when traveling makes me nervous, but I am not sure the internet will allow me to do so. Anyway, if that's too soon no worries.

**Comment by urapadmin** [comment]
you find your cat_file.json on the google drive in \MAD-P\transfer.

Do you remember the drill? In case you don't (copied from khpp):
- make sure your backup drive is connected
- log in to your local Kiosk as admin
- go to the administration and hit the new "transfer" button
- drag & drop or open the cat_file.json you downloaded -> The upload button turns into a green success bar when the upload was accepted
- "transfer destination" should suggest "z:\transfer", where the results of the upcoming process will be stored. That's on your backup drive.
- once the process is ready (it should take a while as all images you added or changed during your season will be copied) you should see something like this:
 
![grafik](https://github.com/arch-kiosk/arch-kiosk-office/assets/38838314/841513fb-4a8b-4313-9922-e31177677e72)

- that directory "z:\transfer\030723-0727" on your backup drive (of course, it will have a different name in your case) needs to be copied from your backup drive to the transfer directory on the shared google folder.

**Comment by luizaogs** [comment]
Thank you. I'll probably do it tomorrow night, so nothing to import today. I'll let you know when it's in the drive.

**Comment by luizaogs** [comment]
Yeah the internet is definitely not enough for this so I'll upload it once I am home.

**Comment by urapadmin** [comment]
you have made regular backups, haven't you? In that case your backup drive should help with being nervous.

**Comment by luizaogs** [comment]
Yup. I'm sure it's fine :) I mostly do not want to pack and was trying to procrastinate...

**Comment by luizaogs** [comment]
It's there.

**Comment by urapadmin** [comment]
finished on my side (the first preparation of a dock can take quite a while because more thumbnails might be created ...)

**Comment by luizaogs** [comment]
Looks good to me. Thank you.
