### ISSUE TITLE
kiosk hub: show last workstation action

### ISSUE THREAD

**Issue by lbestock** [arch-kiosk/arch-kiosk-office#2445]
When I am directing a project that is not currently in the field, and where the various people using workstations thus have different schedules and workflows, it would be helpful for me to be able to see at a glance in the Hub when and what the last action was for each workstation. This is the case when a station is in the field; I request that there always be such information visible. It would also be handy to have for Kiosk as a whole a "last synchronized on" date visible from the Hub.

**Comment by urapadmin** [comment]
it might be a little bit easier for me if I write a log of all major activities and make that available to you. So the information would not be shown right on the dock but you'd get a new menu item in the hub that shows you that specific log. 
Would that do?

**Comment by lbestock** [comment]
I think so? But it runs the risk that things that haven't been done for awhile are not easily findable. So If I want to see when a report was last run, or when my codirector last looked at his files, it might be way down the list. My thinking wasn't so much "what was done last?" as "when was the last time THAT thing was done?", hence thinking of it as dock-bound.

**Comment by urapadmin** [comment]
okay. Bigger task then.

**Comment by urapadmin** [comment]
I still tend to implement this as a list with all events that can be sorted and filtered. That way it is of more broader use.

**Comment by urapadmin** [comment]
### Kiosk 1.5.18
- there is a new menu item in the hub: "sync & dock events" that shows you the log of everything that was going on in the hub of late
- if you click on a specific dock (currently only implemented for FileMaker workstations), you'll find the new "show event log" under "more options".
- all of that only works if you have the "prepare workstation" privilege. I think the menu item even only appears if you are admin.

**Comment by urapadmin** [comment]
I should add here that the event log only shows events that occurred with this new version. Former versions did not log those events. So you have to do stuff to see something.

**Comment by luizaogs** [comment]
Should the user not show up? 

<img width="786" alt="Screenshot 2024-01-08 at 7 22 09 AM" src="https://github.com/arch-kiosk/arch-kiosk-office/assets/67970402/fe6a44f2-09ae-4806-9618-a9dda973a2e8">

**Comment by luizaogs** [comment]
Oh odd, I did show up for the download workstation step: 

<img width="849" alt="Screenshot 2024-01-08 at 7 24 23 AM" src="https://github.com/arch-kiosk/arch-kiosk-office/assets/67970402/7987d4dd-2cbb-46e9-9e73-6c098e0fbaef">

**Comment by luizaogs** [comment]
Yeah, funny. The user is clearly logged for some actions and not others: 

<img width="867" alt="Screenshot 2024-01-08 at 7 26 26 AM" src="https://github.com/arch-kiosk/arch-kiosk-office/assets/67970402/50821c5f-9241-488a-b5ac-ad550161e3cc">

**Comment by luizaogs** [comment]
The rest is working, including privileges (as far as I can tell - privileges are not my forte).

**Comment by urapadmin** [comment]
> Yeah, funny. The user is clearly logged for some actions and not others: 
> 
> 
> 
> <img width="867" alt="Screenshot 2024-01-08 at 7 26 26 AM" src="https://github.com/arch-kiosk/arch-kiosk-office/assets/67970402/50821c5f-9241-488a-b5ac-ad550161e3cc">
> 
> 

I should have mentioned that. The user is only reported for upload and download for now. Logging it for the other actions would have taken more effort than its worth.

**Comment by urapadmin** [comment]
so I close this.
