### ISSUE TITLE
kiosk file repository: ability to input context-dependent descriptions in Kiosk request

### ISSUE THREAD

**Issue by lbestock** [arch-kiosk/arch-kiosk-office#2446]
Inputting legacy data for BUAP, we have now arrived at new workflows for getting images in with their original dates. We have imported images with "shot on" dates that are accurate, and have written a file picking rule to get them into the gallery despite having no contexts, and now have the ability either to add them in FM using the gallery or to add contexts to them in the File Repository.

I am finding both avenues useful but am using the File Repository to add contexts more than I expected - it is extremely fast and easy and I can get a whole day's images from one unit pretty much taken care of in minutes after typing the notes from that day. What I cannot do in the file repository is add context dependent descriptions. I know that being able to do so is not a small ask, but as it would be useful while I am doing this it gets a request ticket.

**Comment by urapadmin** [comment]
you are right, that's a bigger task and honestly out of the file repository's responsibility. We are dealing with files here, you are trying to add data to the archaeological record through the file repository.
Conceptually that is not the right place to do that and belongs to a browser based data input that we don't have.
