### ISSUE TITLE
Director's View: Images and loci missing when filtering

### ISSUE THREAD

**Issue by maychu16** [arch-kiosk/arch-kiosk-office#2450]
I finished working for the day and I was looking around in the Kiosk Hub and File Repository to make sure that everything is in order. However, I noticed that not all my Loci are showing up in the Director's View. Is there a limit on how many Loci are being shown at a time?
I selected today's date (29 XII 2023) and selected Op 175 but it only shows up to Locus 35. It should be showing up to Locus 81. I know that the data is there because I synced about two times since I finished inputting the data and Locus 81 is in the recording app.
I am just wondering why the director view does not show all Loci I have inputted. 

<img width="1512" alt="Screenshot 2023-12-29 at 11 01 23 PM" src="https://github.com/arch-kiosk/arch-kiosk-office/assets/153842762/a8b667c8-fa42-46f0-bd85-4ad2f9e45d78">

### related bugs
- [x] #2453
- [x] #2459 
- [x] #2460

**Comment by maychu16** [comment]
I just noticed the same is also true for photos. There are more than 23 photos that I inputted into Op 175. The loci and photos are all there in the File Repository, they are just not in the director's view. Also if I just select the date and not the specific Op, descriptions of Loci show up in narrative section but when I select Op 175 after selecting the date, there is 0 narrative.

**Comment by urapadmin** [comment]
ja, we definitely have some bugs here. I list them in the header of this ticket.

**Comment by urapadmin** [comment]
### Kiosk 1.5.17 addresses all the issues
- please close this if all the issues in the header of this issue here are closed.
