### ISSUE TITLE
recording: issue with dates in new team members list

### ISSUE THREAD

**Issue by luizaogs** [arch-kiosk/arch-kiosk-office#2451]
Testing #2415 

I wanted to fill out all fields to test if everything was synchronizing properly, so I added dates to my role in trench LA in PVD. But something is weird with the dates. Under from I typed 28 VI 2020 but ended up with 2000, as you can see below. Similar issue in the to field, where I typed 30 XII 2023 and also ended up with 2000.

<img width="812" alt="Screenshot 2023-12-30 at 9 51 00 AM" src="https://github.com/arch-kiosk/arch-kiosk-office/assets/67970402/a467f305-3db9-4132-9d53-a01a8ef43c6e">

**Comment by urapadmin** [comment]
that was wrong here, too: #2416

**Comment by urapadmin** [comment]
### recording 15.11.1
- maybe it is fixed now? One can only hope so.

**Comment by luizaogs** [comment]
Yep.
