### ISSUE TITLE
kiosk: coordinate points import did not work in MADP

### ISSUE THREAD

**Issue by luizaogs** [arch-kiosk/arch-kiosk-office#2452]
I tried to import coordinates using the CSV import feature in Kiosk a few days ago and it didn't work: I kept getting an error about decimal placement or something. I then did it manually because it was only 7 points and I wanted to get it over with, but I let you know here. I'm not sure if it's a bug or if there's an issue with the points themselves but the data looks to me to match what we are supposed to have in the CSV. 

[Main Control Points.csv](https://github.com/arch-kiosk/arch-kiosk-office/files/13797411/Main.Control.Points.csv)

**Comment by luizaogs** [comment]
Ah and now I tried to upload that to PVD to see if I got the same error and it weirdly says that the file was uploaded but the points do not appear.

Oh wait now I got the same error I got in the MADP server in PVD: 

<img width="1512" alt="Screenshot 2023-12-30 at 10 38 50 AM" src="https://github.com/arch-kiosk/arch-kiosk-office/assets/67970402/a570bb99-d567-4dcb-9052-e82d0954ef70">

**Comment by luizaogs** [comment]
Ok I realized there was an extra empty row in there, which I thought was causing the issue, so I deleted it and now I get this: 

<img width="1512" alt="Screenshot 2023-12-30 at 10 41 56 AM" src="https://github.com/arch-kiosk/arch-kiosk-office/assets/67970402/5bc18840-aa4e-4e58-a293-edf39779b279">

Here is the new file: 

[Main Control Points 2.csv](https://github.com/arch-kiosk/arch-kiosk-office/files/13797423/Main.Control.Points.2.csv)

**Comment by urapadmin** [comment]
Without looking up anything about it, there is an extra row 1: "Main Control Points". Hence line 2, column 2 is indeed not a number. It has "Latitude".
That might already be the issue. Delete that row and try again. 

I worry also a bit about the trailing commas. But those might get ignored.

**Comment by luizaogs** [comment]
Yeah, worked.
