### ISSUE TITLE
Director's View: narratives are not correctly filtered by unit

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#2453]
In BUAP filtering by unit leads to NO narratives. Filtering by excavator works, though.

**Comment by maychu16** [comment]
Some Loci are still missing when i filter by excavator.

**Comment by urapadmin** [comment]
if you have an example of a locus you are missing when just filtering by excavator, please let me know. Makes it easier to chase this bug down.

**Comment by maychu16** [comment]
When I select excavator, up to Locus 23 shows up under Op 275. If I select Op then it shows up to Locus 35. But there should be loci up to Locus 81 under Op 275

**Comment by urapadmin** [comment]
> When I select excavator, up to Locus 23 shows up under Op 275. If I select Op then it shows up to Locus 35. But there should be loci up to Locus 81 under Op 275

Hm. 
Are we talking about locus descriptions here? Because this ticket is about the missing narratives. At least I don't exactly know where to look. I was looking at 12/29/2023 for the missing narratives. So if we are indeed talking about locus descriptions here, please give me the exact date to look at. I have only OPs 145,172 and 175 and their locus descriptions on 12/29/2023.

**Comment by urapadmin** [comment]
### Kiosk 1.5.16.2
- all narratives of the selected unit should be visible now (except for the general cap of 100 records in the narrative widget)

**Comment by maychu16** [comment]
The narratives are all there. I noticed some Loci are missing. Is there a limit on how many Loci can be viewed at a time? On Dec 29, when I select Op 175, only 30 Loci show up. There should be about 80.

**Comment by urapadmin** [comment]
> The narratives are all there. I noticed some Loci are missing. Is there a limit on how many Loci can be viewed at a time? On Dec 29, when I select Op 175, only 30 Loci show up. There should be about 80.

Okay, then I understand that it is a bout the locus widget and not the narrative widget (where all the narratives were missing when filtering by a certain unit / OP). I make a separate ticket for this.

**Comment by urapadmin** [comment]
### Kiosk 1.5.17
- #2459 revealed that there is a general limit of 100 records (which can be different from the record type that is shown by the widget). For the narrative widget it means that not more than 100 narratives will be shown.
- this is indicated now in the header (100 of 105 narratives).

**Comment by luizaogs** [comment]
Could I get access to BUAP to test the director's view stuff? Unless May will test them herself. This would be hard to see in PVD.

**Comment by maychu16** [comment]
It seems to be working now and I can see all loci, narrative and photos that I inputted.

**Comment by urapadmin** [comment]
> It seems to be working now and I can see all loci, narrative and photos that I inputted.

okay, please have an eye on this during your future work. The director's view has never been flooded with these amounts of data per day, so this is a good test.
