### ISSUE TITLE
kiosk: issue with display of long descriptions in file repository

### ISSUE THREAD

**Issue by luizaogs** [arch-kiosk/arch-kiosk-office#2454]
Tiny thing I noticed when looking through the MADP file repository. Some context independent descriptions appear outside of the image thumbnails for some reason: 

<img width="1512" alt="Screenshot 2023-12-31 at 11 43 54 AM" src="https://github.com/arch-kiosk/arch-kiosk-office/assets/67970402/6d5abef9-c421-4e77-8f27-89ef5705181e">

<img width="1512" alt="Screenshot 2023-12-31 at 11 44 00 AM" src="https://github.com/arch-kiosk/arch-kiosk-office/assets/67970402/576a211b-1420-4466-bd0a-b0ea2611dc96">

**Comment by luizaogs** [comment]
Hm. Also, this photo was definitely imported but I don't see an import tag on there, which is weird? Not opening a ticket yet in case there is an easy explanation.

**Comment by urapadmin** [comment]
it has a tag: archival.

**Comment by luizaogs** [comment]
Well yes, the tag that I added. Does that mean that if I add a tag during import the default import with import time tag is not applied?

**Comment by urapadmin** [comment]
yes. The default import tag is only applied if you don't assign a tag yourself.

**Comment by luizaogs** [comment]
Ok, then ignore that part of the ticket please.

**Comment by urapadmin** [comment]
### Kiosk 15.5.16
- the other was due to a description that has no whitespace that would allow a line break. Now I break anyway.
