### ISSUE TITLE
kiosk: Import Error

### ISSUE THREAD

**Issue by maychu16** [arch-kiosk/arch-kiosk-office#2456]
I was working on the file repository and assigning contexts for the photos. Then I downloaded the file and worked in the recording app to add context description to the photos. Then I tried to upload the file back to the hub and sync. It is giving me this error. I have no idea what happened, please advise. Thank you. 
<img width="1512" alt="Screenshot 2023-12-31 at 4 14 01 PM" src="https://github.com/arch-kiosk/arch-kiosk-office/assets/153842762/8a967217-9c9c-494d-9f11-2ba3d2cd6115">

**Comment by maychu16** [comment]
Ahhh....I clicked on the Upload the database again option and then re-uploaded the file. It was successfully imported this time and I could also sync. I redownloaded it successfully and it has all the data I was working on before. I am not sure why there was the error the first time around.

**Comment by urapadmin** [comment]
hm. The error message is usually pretty correct. It does suggest that the database you uploaded the first time was an earlier file, from an earlier synchronization round. On your second upload you would have imported the right file. The only thing that might have happened (but I don't have evidence for it) is that your first upload failed at the very end thus not replacing the upload from a day before. And then in the import it would have tried to import the old one again. But that is highly soeculative 🤔
