### ISSUE TITLE
Kiosk File Repository: Use logged in user when assigning a context to a file

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#2457]
We imported a bunch of photos for BUAP. (@urapadmin did that via a local upload)
I am assigning them contexts in the file repository as I digitize old paper notes.
Once I do that they show up in the Director's View for the day the context itself was assigned. That is clearly catching the assignment of the context and thus the moving of the image into the recording, and this is what I would expect and want - it helps me use Director's View to have a view on what the legacy input team is doing. And the time stamp in Director's View addresses the time of the image being given a context, I believe. But it says admin did it, not that I did it, though I was logged in as myself to Kiosk.

_Originally posted by @lbestock in https://github.com/arch-kiosk/arch-kiosk-office/issues/2271#issuecomment-1872286723_

**Comment by urapadmin** [comment]
### kiosk 1.5.17
- the currently logged on user (the repl_user_id, not the Kiosk user id) should leave a mark on the relation between context and image now. That does not show in the file edit dialog but e.g. in the director's view and it should show in the recording app.

**Comment by luizaogs** [comment]
Works both in kiosk and recording.
