### ISSUE TITLE
kiosk/recording app: meet new tester

### ISSUE THREAD

**Issue by luizaogs** [arch-kiosk/arch-kiosk-office#2458]
New tester alert!

![D4A7B0F0-D9FD-4CC7-871E-004ED0DC7116](https://github.com/arch-kiosk/arch-kiosk-office/assets/67970402/10142b4d-5818-42d8-b5ca-9664648bee61)

**Comment by urapadmin** [comment]
oh. Finally! Those are good for some gobbledygook testing. She (?) has to leave that room, though :o)

**Comment by urapadmin** [comment]
I nearly adopted #3 today when a black cat behaved rather weirdly for hours in the backyard.

**Comment by luizaogs** [comment]
Ha. She loves the bathroom. But is exploring slowly :) I almost adopted a weird and totally lovely black cat myself today but I thought Jenny (for now) and I would get along.

**Comment by urapadmin** [comment]
Have you ever seen Bob ON Huxley? You immediately want two 🐈‍⬛Is she a shelter cat?

**Comment by urapadmin** [comment]
now you can cuddle up with a book AND a cat (once she is out of that room). That'll change your life!

**Comment by luizaogs** [comment]
She is a shelter cat! @lbestock found her for me :)

**Comment by luizaogs** [comment]
![IMG_9662](https://github.com/arch-kiosk/arch-kiosk-office/assets/67970402/4e325d29-c9bc-4119-9cb9-41c9a11c46c7)

**Comment by urapadmin** [comment]
good tail. Reminds me of my Cäsar.

**Comment by luizaogs** [comment]
Aw. I had not heard about Cäsar before :)

**Comment by urapadmin** [comment]
rests under the cherry tree 🌸

**Comment by luizaogs** [comment]
With such a tail, he must have been a lovely cat.

**Comment by luizaogs** [comment]
And I will close this because you don't need more tickets... but if you do need more cat pictures (as if you didn't have enough, but still!) you know where to find me :)

**Comment by urapadmin** [comment]
I totally expect the new tester to appear in the file repository not too infrequently 🐱

**Comment by luizaogs** [comment]
Oh she shall.
