### ISSUE TITLE
director's view: get rid of webpack

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#2462]
I can't even start the director's view any longer because of WebPack. I have always hated it and now it has to go for good.
So the task is to transform the whole project from webpack to the much better vite.

Unfortunately after that it needs to be tested as a whole

**Comment by urapadmin** [comment]
### Kiosk 1.5.17
- the director's view is now based on a more recent technology and needs a complete test:
  - the obvious (are the widgets doing what they obviously are supposed to do?)
  - quality control (do the markers show, do the little popups appear?)
  - see also #2450 etc.

**Comment by urapadmin** [comment]
@luizaogs  While I think that May will naturally test the others in the coming weeks in BUAP, it would be very helpful if you and Jenny tackle the more systematic test of the director's view. That can be done in PVD, but I will also update MAD-P.

**Comment by luizaogs** [comment]
On it.

**Comment by luizaogs** [comment]
Everything is working - except for the quality control markers. I do not see them at all.

**Comment by urapadmin** [comment]
### Kiosk 1.5.20.5
- the little quality control icons and messages should be back
