### ISSUE TITLE
Introduce new material field (further specification of the material)

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#2464]
a second field shall specify the general material a bit further (using a different list than material)

**Comment by urapadmin** [comment]
### recording 15.12
- there is a second drop down behind the material field (it does not have a label itself)
- the list is configured by "valuelist_material_specified". It automatically adds a "-" to select nothing.
- it can be hidden by setting "show_material_specified" to "nope". Default is that it is visible.

**Comment by luizaogs** [comment]
Should it have the light gray stripe there? I guess it helps to see that both are the same field since there is no label.

<img width="1029" alt="Screenshot 2024-01-12 at 11 26 23 PM" src="https://github.com/arch-kiosk/arch-kiosk-office/assets/67970402/ae4e5fd4-7b05-4974-89ae-3e0d36649811">

**Comment by luizaogs** [comment]
The rest is fine, including synchronization.

**Comment by urapadmin** [comment]
yes, that's why I put it there. It disappears if only the main material list is visible.

**Comment by luizaogs** [comment]
Yep.

**Comment by urapadmin** [comment]
I have to reopen this because I ran into a @lbestock note for BUAP:
- No concordance for Material2 - just take the words there, and configuration should be for a dynamic dropdown list

So apparently a configured value list is not what is expected here. A mistake for using this in the field from my point of view, so I'll give projects an option to either use a dynamic list or a configured valuelist and make the second the default.

**Comment by urapadmin** [comment]
we discussed it and won't put any effort in here for the time being. It stays a valuelist for now.

**Comment by urapadmin** [comment]
this time reopened because hiding it with show_material_specified did not work in ELRI. But then it did. Strange.

**Comment by urapadmin** [comment]
tried it again in the development db and it works and I can't see a reason why it wouldn't. 
Please check again in PASU and ELRI.

**Comment by luizaogs** [comment]
This is working in PASU - it is on by default but turning it off makes it go away. I can't test ELRI, however, since I don't think you released that?

**Comment by urapadmin** [comment]
there was nothing to roll out because I cannot find an error. So this is just about trying again in ELRI to see if the issue shows again. If not we forget about it.

**Comment by luizaogs** [comment]
Sorry, tiredness leads to a non-functioning brain apparently. ELRI is working.
