### ISSUE TITLE
recording app: visible menu/toolbar thing in FM

### ISSUE THREAD

**Issue by luizaogs** [arch-kiosk/arch-kiosk-office#2465]
The screenshot is pretty self explanatory. Happens when I am logged in as me and as admin, both in test mode and outside of it. This is in PVD, latest release.

<img width="1027" alt="Screenshot 2024-01-12 at 11 24 45 PM" src="https://github.com/arch-kiosk/arch-kiosk-office/assets/67970402/728f556f-7f64-46e9-957e-b06029ccceff">

**Comment by urapadmin** [comment]
### recording app 15.12.1
Should be gone.
