### ISSUE TITLE
Kiosk: BUAP locus no lot import an ANC# that should not have been accepted seems to have been

### ISSUE THREAD

**Issue by lbestock** [arch-kiosk/arch-kiosk-office#2466]
@maychu16 has caught an interesting issue.
@urapadmin is preparing the import of BUAP ANC# records from the FM database kept in common by Abydos projects.
It will import only ANC#s for which the locus and lot already exist in Kiosk.
A preliminary run returned 76 records for which the locus but not the lot existed already in Kiosk (almost entirely from @maychu16 data entry).
@lbestock asked @maychu16 to check those from OP172 so we can figure out where the problem lies. It is clear there are in fact several problems that led to this, including incomplete recording but more troublesomely, duplicate assigning of numbers. This is why people need natively digital recording systems.

But for this particular bug, the issue is rather:
ANC "37066 is not in the list you sent but it should also be assigned to 172-16 lot 32. This one does exist on the Locus 16 object list as well as ANC number log. I wonder how that one got imported. Lot 32 is the problematic one since it is assigned to two Loci. Please let me know how to proceed with this one."

I confirm: 37066 is in the ANC database and has Op 172, locus 16, lot 32. It is NOT on the Excel sheet of locus_no_lot @urapadmin produced on 15 I 2024. There are six records on that sheet that have the same Op, locus, and lot. Why are those treated differently in this process? 37066 should have been on the Excel list.

Op 172 locus 16 I confirm does exist in the BUAP Kiosk recording. @maychu16 has noted that in the physical notebook lot 32 was assigned both to locus 16 and to locus 23, and 172-23 lot 32 DOES exist in the recording. So both locus 16 and lot 32 exist in the recording, but not together, and the import expects them to be together. Still can't explain why ANC#s with locus 172-23 lot 16 were sometimes accepted and sometimes rejected.

**Comment by urapadmin** [comment]
> I confirm: 37066 is in the ANC database and has Op 172, locus 16, lot 32. It is NOT on the Excel sheet of locus_no_lot @urapadmin produced on 15 I 2024.

because it had material VOID in the anc database, so I skipped it entirely.
