### ISSUE TITLE
synchronization: Show details even if synchronization was successful

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#2470]
when solving #1354 I decided to hide the "show more details" checkbox if synchronization was successful.
Now that we want to see the log even if synchronization was successful, I need to go back to that issue.

**Comment by urapadmin** [comment]
### Kiosk 1.5.20
- I think this is better now (the code, though is so bad...). 
- It also shows everything that says "note" in a different colour and shows it right away (no need to click on details)

**Comment by luizaogs** [comment]
I don't see any "notes" and the following looks a bit weird: 

<img width="1512" alt="Screenshot 2024-01-15 at 8 32 54 PM" src="https://github.com/arch-kiosk/arch-kiosk-office/assets/67970402/c9c8c266-98e6-4683-a72f-857397924cb1">

**Comment by urapadmin** [comment]
hmpf. quite weird. You could perhaps have cache issues. But I am not sure. I'll look into it tomorrow.

**Comment by luizaogs** [comment]
Nope, just cleared the cache and it looks exactly the same. Both of these synchronizations didn't have the checkboxes checked since I was testing #2469 , in case that makes a difference.

**Comment by urapadmin** [comment]
ja, it isn't a cache issue. I looked at your synchronization result and things are just too weird. That's a bug.

**Comment by urapadmin** [comment]
### Kiosk 1.5.20.1
- this is very hard to test for me on the development system so I just roll out a version that might behave correctly. 
- BUT because of my changes these tests are needed:
  - [ ] a synchronization that is successful without any warnings or "note"s. That would be a totally smooth sync as you produced up there. A run without housekeeping is likeliest to get a warning free run
  - [ ] a synchronization that has a warning. I suppose running synchronization with housekeeping should lead to a few warnings
  - [ ] a synchronization that has an error. The only error you can easily trigger is running synchronization without having any workstation in "ready for synchronization" state. Try it with and without housekeeping.

**Comment by urapadmin** [comment]
also, please clear your cache before you start. (Or use a private tab if you are on an iPad)

**Comment by urapadmin** [comment]
@lbestock reported:

> The first try synchronization gave me 1119 CM successfully added!
> But housekeeping caught so many files tagged as broken that the synchronization log could not be properly displayed and it says "aw, snap" after a few seconds. Should I care?

That's definitely a result of the bug. So it makes sense to test this on buap-test, too.

**Comment by luizaogs** [comment]
@lbestock did you have any warnings? Because in PVD I apparently cannot get a synch without warnings to test the first checkbox.

**Comment by luizaogs** [comment]
The other two seem fine to me.

**Comment by lbestock** [comment]
So far I have only done the zillion warnings and not tried to get one without. Let me stop getting distracted and work on that...

**Comment by lbestock** [comment]
I take it an "info" line does not count as notes here? If that is the case, I just had a lovely clean synchronization that added 22 new CMs and I am so ready for this to be rolled out to real BUAP and start the fun with some actual objects.

**Comment by urapadmin** [comment]
> @lbestock did you have any warnings? Because in PVD I apparently cannot get a synch without warnings to test the first checkbox.

what warning do you get that you didn't get in the runs before?

**Comment by urapadmin** [comment]
but I want it from Luiza on PVD 🐑 and wonder why that is harder now to get

**Comment by luizaogs** [comment]
Oh. I don't know. I followed the same steps and ended up with a warning about locus relations.

**Comment by lbestock** [comment]
Looks to me like just the old friend that 5 locus relations cannot be fixed automatically. No way to have an utterly clean synchronization in PVD while that is still kicking around, is there?

**Comment by luizaogs** [comment]
I got it yesterday, which is why it was weird.

**Comment by urapadmin** [comment]
hmpf.

**Comment by urapadmin** [comment]
well, I'll take this as tested. I suppose we will easily run into it again should it still exist.
