### ISSUE TITLE
Kiosk Q&V refuses to fetch a tag

### ISSUE THREAD

**Issue by lbestock** [arch-kiosk/arch-kiosk-office#2471]
Doing a query on "Wheeler" in Q&V tells me things I can click on, including Wheeler rooms at which I would like to look. Clicking on a room gives me the following error:
![image](https://github.com/arch-kiosk/arch-kiosk-office/assets/49291909/81e4ca05-ef49-45c8-88fa-6d7afac41ed5)

I am logged in and the server is fine - I can get to this point, and the FR is working just fine for me.

**Comment by lbestock** [comment]
Other things in that list allow me to click on them. It looks like I can get to any CM but no tag from the list Q&V generates when I go to footsteps and type "Wheeler". Half of them are CM and half are tags.

**Comment by urapadmin** [comment]
that is correct. Tags are currently not covered by Q&V

**Comment by urapadmin** [comment]
see #2374

**Comment by urapadmin** [comment]
I close this because it is duplicate
