### ISSUE TITLE
recording app: CM registration relevant columns differ based on numbering strategies

### ISSUE THREAD

**Issue by lbestock** [arch-kiosk/arch-kiosk-office#2472]
I started a request ticket to ask for BUAP to have a column for locus to be visible in CM registration, but writing the ticket it has struck me this is a bigger issue.

In BUAP I cannot see information I need (both to be able to see it and to sort by it) in CM registration. There is a column for lot, but not one for locus, and the ANC# contains zero archaeological contextual information and so is not useful for me to know what I'm looking at. I can't tell where I am, in CM registration, and I want to be able to.

It wants some thinking. Which information is needed in CM registration is in part a function of how numbering works for a project. So USTP and URAP do NOT need locus as a column - that information is in there in the CM number and that can be sorted by. But USTP DOES need unit and URAP does NOT. And BUAP needs locus but not unit. Ideally I want a configuration key that lets me choose which columns are present in CM registration.

**Comment by urapadmin** [comment]
please add a label for either Kiosk or the Recording App. Otherwise I miss things.

**Comment by urapadmin** [comment]
### recording app 15.21
It is getting full in that layout.
- a new config key "show_locus_in_registration" needs to be set to "yup" to activate this feature
- when activated you get the unit/locus on top of the bulk number
- and headers on top of each other to sort bei either of them

**Comment by luizaogs** [comment]
This is working, but is the header for sorting supposed to say only locus or unit/locus? In PVD I am only getting context up there.

<img width="1030" alt="Screenshot 2024-01-16 at 5 40 20 PM" src="https://github.com/arch-kiosk/arch-kiosk-office/assets/67970402/2434029e-2392-43fe-a9bd-d5c2f5b3aa6c">

**Comment by lbestock** [comment]
The sorting now seems messed up. We found the order not to be numeric in BUAP once this was introduced.

**Comment by luizaogs** [comment]
PVD looked ok to me, unless I missed something.

**Comment by urapadmin** [comment]
I have seen BUAP to be not in order, so I'll look into what the difference can possibly be.

**Comment by luizaogs** [comment]
I mean, check PVD too! Maybe I'm misunderstanding. But the screenshot above looks ok, no?

**Comment by urapadmin** [comment]
here we are talking about the mode in which you can't see the new locus/unit and sort by bulk#.

**Comment by luizaogs** [comment]
Oh. I had not looked at that. Some of the sorting appears off in PVD too, then.

<img width="1024" alt="Screenshot 2024-01-17 at 3 57 00 PM" src="https://github.com/arch-kiosk/arch-kiosk-office/assets/67970402/5f971711-396f-4348-96bf-5edd83171359">

<img width="1019" alt="Screenshot 2024-01-17 at 3 57 18 PM" src="https://github.com/arch-kiosk/arch-kiosk-office/assets/67970402/133cc16c-76fc-4f22-b613-85aeb5365846">

**Comment by urapadmin** [comment]
Independent of the latest changes I made:
For buap we must make sure that the config key "registration_identifier_sort_method" is set to "context".
PVD is a mess anyways. I would suggest the same there.

**Comment by urapadmin** [comment]
### recording 15.13.1
yes, I think that is actually the problem. It has nothing really to do with the latest changes.
Nevertheless I found that the new "show_locus_in_registration" = yup mode would not obey the "registration_identifier_sort_method" and so I changed that. 
- It is hard to test, so just make sure the order is still okay in both "show_locus_in_registration" yup and nope.

**Comment by urapadmin** [comment]
please test in both PVD and BUAP and then later on in a project that uses "registration_identifier_sort_method" "domain". URAP should be the right project for that, so I will update that, too.

**Comment by luizaogs** [comment]
I'm going to test PVD and BUAP test now. I don't think you updated URAP?

**Comment by luizaogs** [comment]
PVD looks good after I set the sort method to context.

**Comment by luizaogs** [comment]
BUAP test looks good, too. So just let me know when URAP is updated.

**Comment by urapadmin** [comment]
URAP got an update now

**Comment by luizaogs** [comment]
The above is just sorting by bulk#. I haven't even checked by unit/locus because that seemed weird enough.

**Comment by urapadmin** [comment]
is that registration_identifier_sort_method set to domain or context?

**Comment by luizaogs** [comment]
Domain.

**Comment by urapadmin** [comment]
domain is very problematic in PVD because the records stem from so many different phases and old bugs etc. So if domain behaves properly in URAP and context behaves properly in PVD, I'd be fine.

**Comment by luizaogs** [comment]
This is domain in URAP and it does not seem proper to me, hence the question.

**Comment by urapadmin** [comment]
That's URAP? Wow I just looked at those identifiers and they did not look URAP at all. Sorry, I misunderstood the issue. Must be legacy data in URAP then. 
Hm. That is an interesting case because it means we have legacy data mixed with data that was recorded in the field. And for the latter "domain" does not work (it sorts partly by an identifier's domain, in case of a collected material that's the locus' identifier) and the running number within that domain. Legacy data does not have that running number because the identifiers are not auto generated but the result of free input. 
Hm.
I have to think about it.

**Comment by luizaogs** [comment]
Ha yeah, I figured it might be legacy because it didn't start with letters. Well. Sorry to give you another problem!

**Comment by urapadmin** [comment]
I have thought about it. I have no good idea. A project that has identifiers that were not auto-generated (this is also true for projects using free input for other reasons) must use "context" as the sort order in registration_identifier_sort_method. 
But to ease the pain I have applied the same trick that I used in the collected material list on unit level. It might look better than it is now.

**Comment by luizaogs** [comment]
Can you release this in URAP, since the original issue was spotted there please?

**Comment by luizaogs** [comment]
URAP released but I am now suffering MCP issues: 

<img width="705" alt="Screenshot 2024-01-20 at 10 00 43 AM" src="https://github.com/arch-kiosk/arch-kiosk-office/assets/67970402/891dbcb8-f480-4e32-8557-71a48ffd2d0d">

**Comment by urapadmin** [comment]
looks a bit overwhelmed, the Master Control Program.

**Comment by urapadmin** [comment]
wow, URAP could do with a file picking rule

**Comment by urapadmin** [comment]
just needed a second try

**Comment by luizaogs** [comment]
Oops. Sorry.

**Comment by luizaogs** [comment]
> ### recording 15.4
> I have thought about it. I have no good idea. A project that has identifiers that were not auto-generated (this is also true for projects using free input for other reasons) might be best of using "context" as the sort order in registration_identifier_sort_method.
> 
> * however, I have applied the same trick that I used in the collected material list on unit level. So it might look better now than it is actually is behind the scenes.

So just to make sure I understand. The idea here is to use context for URAP too, and to see what that looks like?

**Comment by urapadmin** [comment]
You can look at the domain setting and even that might be better. If not, then "context" is the only other option we have.

**Comment by urapadmin** [comment]
The background: "context" is simply not the best option for all numbers. FA-100-5 would be regarded a larger number than FA-100-100 and that looks counter-intuitive to archaeologists. the "domain" sorting method treats the last part as an actual number instead of a text. "context" can't do that.

**Comment by luizaogs** [comment]
Umm. URAP registration currently looks like this ...

<img width="1025" alt="Screenshot 2024-01-20 at 10 22 19 AM" src="https://github.com/arch-kiosk/arch-kiosk-office/assets/67970402/28735acd-399f-407b-bea9-ffd54e6bc672">

**Comment by urapadmin** [comment]
oh I hate FileMaker so much

**Comment by urapadmin** [comment]
did you switch to showing the unit/locus in the collected material? That's not what should be the standard for URAP.
(the stupid label in there is just something I want to kick FileMaker for)

**Comment by luizaogs** [comment]
I don't think I did? I definitely did not do it right now. Maybe I did it last time I was testing this, but I don't think i would have synchronized so that's odd.

**Comment by urapadmin** [comment]
ja, I hope it did not come it through a patch. 
However, new version 15.14.2 does away with the label. All projects would have had that.

**Comment by luizaogs** [comment]
URAP looks much better now.
