### ISSUE TITLE
BUAP: recognize ANC files in file import

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#2475]
Files named ANC37047a.tif have to be imported to context 37047

**Comment by urapadmin** [comment]
@lbestock You can do this now

**Comment by lbestock** [comment]
Happy.
You want to add a space, too, so ANC 34124.tif is recognized.

**Comment by lbestock** [comment]
Ah, something else for you to check: things that have words seem to get additional contexts added to them. ANC37002sideview.jpg gets added to contexts 37002 AND to 190. And I don't even know what 190 is or where it got that.

**Comment by urapadmin** [comment]
that is correct :o) 190 is the external id of 37002:
![image](https://github.com/arch-kiosk/arch-kiosk-office/assets/38838314/0bc9ec81-27f7-43cd-b4be-c24539d6f683)

**Comment by urapadmin** [comment]
after #2479 is applied the issue should not exist anymore at all

**Comment by lbestock** [comment]
Proper, checked both in the recording and in Q&V.

**Comment by urapadmin** [comment]
I extended this on both BUAP-TEST and BUAP so that it recognizes filenames like "ANC 12345", so with one or more spaces between ANC and the number.

**Comment by lbestock** [comment]
Happy. It makes me happy.
