### ISSUE TITLE
kiosk: thumbnail psd files in file repository 

### ISSUE THREAD

**Issue by lbestock** [arch-kiosk/arch-kiosk-office#2476]
BUAP CM photo importing. Magic. Makes me happy.

But there are some files in there that are psds. That is of course bad practice and they shouldn't be there, so your answer might be "go climb a tree" (convert them to something better and then try again). But at least I note that a psd is imported as a file and then not shown as an image. And in fact I cannot click on it in the file repository either, so I can't download it even, and that might be a bigger issue and not just a request.

You can find the one I'm talking about if you search CM photos in the file repository of BUAP.

**Comment by urapadmin** [comment]
- this is a non issue. We do import PSDs and we show thumbnails for them. There is only one PSD that isn't working: #2497

**Comment by urapadmin** [comment]
I close this in favour of #2497
