### ISSUE TITLE
Kiosk: BUAP import of ANC did not create small finds records properly

### ISSUE THREAD

**Issue by lbestock** [arch-kiosk/arch-kiosk-office#2478]
Whoops. The huge ANC import has labeled things small finds but not actually created the small finds tab that we can see in recording. We're not sure where our Excel column "type" that we labored over went.

**Comment by urapadmin** [comment]
### buap-test 17.I.2024 (no new version as this is project-specific)
- the small find records should be there now for the already existing cms
- when new collected materials are imported new small find records should be created, too. They also have their own line in the synchronization log.

**Comment by lbestock** [comment]
"Height" seems to go to "Storage" instead of being added to the description? At least in ANC 39982 I have a suspicious measurement under storage.

**Comment by lbestock** [comment]
The lot as shown in CM displays as having a prefix of the locus. That is not how it looks when one creates the lot. And now I need to check configuration of ID methods - it is applying a method to creating CM and there shouldn't be one.

**Comment by urapadmin** [comment]
> "Height" seems to go to "Storage" instead of being added to the description? At least in ANC 39982 I have a suspicious measurement under storage.

I need details here. What is a "suspicious" measurement?

**Comment by lbestock** [comment]
Any measurement at all. There are several in the storage field. That is not a storage. It got that number from somewhere else.

**Comment by lbestock** [comment]
> The lot as shown in CM displays as having a prefix of the locus. That is not how it looks when one creates the lot. And now I need to check configuration of ID methods - it is applying a method to creating CM and there shouldn't be one.

The ID methods were not set to free input for CM; that was easy. But I am still surprised by the lot number.

**Comment by lbestock** [comment]
(The small find record itself is at least showing up now properly.)

**Comment by urapadmin** [comment]
> > The lot as shown in CM displays as having a prefix of the locus. That is not how it looks when one creates the lot. And now I need to check configuration of ID methods - it is applying a method to creating CM and there shouldn't be one.
> 
> The ID methods were not set to free input for CM; that was easy. But I am still surprised by the lot number.

this has nothing to do with the import, that's a more general BUAP issue. Please make it its own ticket.

**Comment by urapadmin** [comment]
> > Any measurement at all. There are several in the storage field. That is not a storage. It got that number from somewhere else.
> 
> argl. That was also already wrong in the last import and has nothing to do with the small find record

yes, that was wrong already in the result of the first import step. Such things need more systematic testing. Field by field.
Now I do have to delete the already imported collected materials.

**Comment by urapadmin** [comment]
### buap-test 17.I.2024 > 21:30
- 39982 should have "Sohag magazine" in storage, which means the height is not any longer imported into that field but instead the location column from the ANCDB.

**Comment by lbestock** [comment]
Nope. Sohag magazine is nowhere, and the storage still says 6.3cm.

**Comment by urapadmin** [comment]
hm. It looks okay in the database. I have reset your workstation and recording group and it is preparing ...

**Comment by lbestock** [comment]
Argl. I had reset my workstation myself and done this twice, and then you do it and now it is OK? Now it is mostly OK. I still have the 3700x disappearing problem after I change the configuration of SCA# visibility. And in fact I have had 39982 disappear, too.

**Comment by urapadmin** [comment]
no it was resetting the recording group which did it.

**Comment by urapadmin** [comment]
this looks okay to me now. I can confirm that a simple restart of the server (or a synchronization run) would include the new cm identifiers in the cache and then they can be found.
