### ISSUE TITLE
ANC import: height

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#2480]
So far the ANC import does not seem to be importing the height.
I looked it up in the code: It should. 

So the only other explanation is that none of the loci we have recorded, yet, trigger a collected material that is a small find with a height.

Please test this.

**Comment by urapadmin** [comment]
but you have to wait for #2478

**Comment by urapadmin** [comment]
you might also want to check on the depth in cases where there is a depth

**Comment by lbestock** [comment]
The measurements still do not seem proper. 37002 has no measurements but had a height in the ANC database. 37211 had a height but that is missing, had a thickness that appears now in width.

**Comment by lbestock** [comment]
![image](https://github.com/arch-kiosk/arch-kiosk-office/assets/49291909/1c37cc2e-3db2-4f2b-b2f8-23fef173db9f)
All messed up where these fields are landing. Length for diameter, width for thickness, conservation notes end up in diameter?

**Comment by urapadmin** [comment]
### 17.I.2024 23:38
Yes, they were all shifted by one column. I hope I got the mapping right now, I checked all the fields once more,

**Comment by urapadmin** [comment]
- 37861 is okay now,
- 37002 has its height
- 37211 is correct now
