### ISSUE TITLE
BUAP Recording: lot displays with locus though they are independent in BUAP

### ISSUE THREAD

**Issue by lbestock** [arch-kiosk/arch-kiosk-office#2481]
BUAP recording, noticed while importing CM. 

BUAP's lots are unique per OP and are simple numbers, not concatenated. But they display in CM as locus (which includes the OP). I expected to see 3, not 174-2-03.

As first mentioned in #2478

**Comment by urapadmin** [comment]
This is really just how we display lots. They always have the unit and locus in front but what is actually stored in the database is the lot number itself. Benign and I am not sure we should change it just because of BUAP.

**Comment by lbestock** [comment]
OK. I'm fine with it. The selector gives me just the lot itself.
