### ISSUE TITLE
Recording: CM by unit sort order not proper

### ISSUE THREAD

**Issue by lbestock** [arch-kiosk/arch-kiosk-office#2482]
Noticed in testing the BUAP CM import. The sort order of CM by unit is not numerical. This was noted in #2478 and #2479. It is not the same thing as the sort order issue in registration, which was a configuration matter.

**Comment by urapadmin** [comment]
this is in fact very related to the sorting problem in #2472 only that it does not obey the "registration_identifier_sort_method" setting and I would rather not want to make it do that here until it allows to sort by column, which it currently does not do. 

So for now I have applied something to the current sorting method that should do the trick for now.
For later: #2483

**Comment by urapadmin** [comment]
### recording 15.13.2
- should be better now for BUAP and still as before for other projects (though PVD would have had issues, too, because the records are chaos by now).

**Comment by luizaogs** [comment]
For BUAP it looks good now but the lowest numbers are at the bottom, highest on top. I assume that is fine?

**Comment by urapadmin** [comment]
That is usually what we want (the most recent ones on top). But anyway, until #2483 that's okay.

**Comment by urapadmin** [comment]
> Can you please do the same thing to CM in loci? We had a scary moment.

different case. They are always sorted by creation date descending. Good for the field, not good for legacy data. This would need sortable column headers, I think (but that's work):

**Comment by urapadmin** [comment]
I close this again as this particular issue is solved.
