### ISSUE TITLE
kiosk: request CM description word search

### ISSUE THREAD

**Issue by lbestock** [arch-kiosk/arch-kiosk-office#2484]
I needed an ANC#. I needed it so I can rename a bunch of photos getting ready for an import. Possibly the nicest artifact I have ever found, and I couldn't find it in Kiosk. I knew its unit, and that it was a small find and stone. But that unit had hundreds of small finds and the quickest way for me to find the ANC# turned out to be to go into the ANC FM database, which was not what I wanted to do. 

What I did there was just a find on the word Harpocrates in the description field. I wanted to be able to do that in Kiosk.

(I would also want that ability in narratives and locus descriptions.)

**Comment by urapadmin** [comment]
a full text search is indeed on the list for Q&V. Won't happen too soon, though.

**Comment by urapadmin** [comment]
you have some full text search ability in #1754

**Comment by urapadmin** [comment]
- or rather #1756

**Comment by lbestock** [comment]
There you go. I forgot. I could have found my ANC# that way indeed. When you import the current photos you will be able to see this Harpocrates.

**Comment by urapadmin** [comment]
so this is basically the same as #2502, right?

**Comment by urapadmin** [comment]
now that you can do this in the file repository the rest is for query and view full text search one day.

**Comment by urapadmin** [comment]
only kinda the same ticket.
