### ISSUE TITLE
recording app: search malfunctions

### ISSUE THREAD

**Issue by lbestock** [arch-kiosk/arch-kiosk-office#2485]
> @urapadmin this is weird beyond belief. I am in recording. If I go to the start page and search 37002 I get nothing. (That is how I found the record prior to changing configuration.) And if I go to unit 172 and look at CM by unit, it is not in the long list of CM I can find there. But if I go to 172 locus 13 and look at the CM for the locus, there 37002 is. With its SCA# in the proper place on the small finds tab.

I suspect that is just a not update file identifier cache after my import. As soon as the server restarts or there is a synchronization run this will automatically be mended. It affects only the search,

_Originally posted by @urapadmin in https://github.com/arch-kiosk/arch-kiosk-office/issues/2479#issuecomment-1897675527_

**Comment by lbestock** [comment]
We are having all sorts of weirdness on the search front, and this right after a fresh download.
I am not able to search for ANY identifier when accessing the magnifying glass from the start page.
@maychu16 is searching via text for identifiers and for instance 370 pulls up several things, but not 37013. Which exists but came in with the last synchronization. But then 37015 DOES show up with the 370 search, and that came in through the same synchronization.

**Comment by urapadmin** [comment]
### kiosk 1.5.20.2
- at least May's issue should not reappear in the future. Otherwise, please complain.

**Comment by lbestock** [comment]
May hadn't changed configuration and she couldn't search for any identifier, either.

**Comment by urapadmin** [comment]
### kiosk 1.5.20.3
- FileMaker changed stuff with one of the last versions. Searching for an identifier would not have worked at all anymore.

**Comment by luizaogs** [comment]
You mentioned this in the latest release note but it doesn't look like you've released kiosk 1.5.20.3?

**Comment by urapadmin** [comment]
Just lost with numbers my little brain is. The first thing I improved was a Kiosk thing (1.5.20.2, only released to BUAP) and it is almost impossible to test, so forget about that one.
The other, really severe issue was in FileMaker itself and I typed nonsense. It should have been recording 15.14.

**Comment by luizaogs** [comment]
I can search for identifiers in BUAP now, but using the example above -- searching for 370 via text still does not pull up 37013. 37013 comes up if I search by identifier.

**Comment by urapadmin** [comment]
I did not even see that May was using the text search. Well that can only work if 37013 is actually being used in a text somewhere. The identifier fields are not being searched when searching by text.

**Comment by luizaogs** [comment]
So I think this is ok?

**Comment by urapadmin** [comment]
@lbestock: Was it really searching by text? There the outcome is less predictable. It might pull up some things and not others depending on what is mentioned in texts somewhere. Or is there something I don't get here, as is so often the case these days?

**Comment by urapadmin** [comment]
Let's move this ticket back to the people who filed it ...

**Comment by maychu16** [comment]
I was trying both text and identifier field. Strangely, some ANC numbers were showing up in text search and not in identifier search. But this is how it should be. It should only come up in the identifier search unless there is the same number I have typed into the narrative field (?)

**Comment by urapadmin** [comment]
yes. Text search is searching all the narrative and description fields everywhere. That can be a lot and if you search for "370" you do not find "370" but instead all the places where "370" is mentioned in a text. That might not even be what you want.

The identifier search is searching only for archaeological identifiers and guides you straight to the one you are looking for.

That you saw things in the text search but not in the identifier search was due to the fact that the identifier search did not work anymore on current FileMaker versions at all.

**Comment by urapadmin** [comment]
if you can find everything you need now, you may close this ticket.

**Comment by maychu16** [comment]
I am going to check the missing ANC number (from Locus_no_lot sheet) later this afternoon and it will be a perfect time to test this. If everything works then, I will close this.

**Comment by urapadmin** [comment]
> I am going to check the missing ANC numbers (from Locus_no_lot sheet) later this afternoon and it will be a perfect time to test this. If everything works then, I will close this.

Ah. You are still on yesterday's version. Can you please tell me your FileMaker version when you have the time?

**Comment by maychu16** [comment]
Oh, do I need to upload my database back and sync and download a new one before I start working? 
My FileMaker version is 19.6.3.302.

**Comment by urapadmin** [comment]
> Oh, do I need to upload my database back and sync and download a new one before I start working? My FileMaker version is 19.6.3.302.

yes, you get new versions of the recording app only after preparing your workstation again.

**Comment by maychu16** [comment]
This is not a major problem but I am just wondering why ANC numbers are showing up twice when I search by identifier. 

<img width="1512" alt="Screenshot 2024-01-20 at 3 47 24 PM" src="https://github.com/arch-kiosk/arch-kiosk-office/assets/153842762/b8e94300-55bb-46a9-9638-1b7ff4dbac69">

**Comment by maychu16** [comment]
Interestingly, it only happens for some and not the others. I am just tying in ANC numbers from locus_no_lot to check if they were all correctly imported. 

<img width="1512" alt="Screenshot 2024-01-20 at 3 49 29 PM" src="https://github.com/arch-kiosk/arch-kiosk-office/assets/153842762/88763ad4-d20a-4c54-b8c3-80902e2e658d">

**Comment by maychu16** [comment]
I think I know why it happens for some and not the others. For the ANC numbers that were corrected in the original filemaker database only shows up once. ANC numbers for which I created a new lot show up twice in the identifier search. 
Does it mean they got imported twice?

**Comment by maychu16** [comment]
I take the above statement back, for ANC numbers with lots I added today, they only show up once. 

<img width="1512" alt="Screenshot 2024-01-20 at 4 13 55 PM" src="https://github.com/arch-kiosk/arch-kiosk-office/assets/153842762/59aa718c-9f16-4f1e-a138-f4cda90bd795">

**Comment by urapadmin** [comment]
That was a helpful observation.
@lbestock: The search is fine (hence I close this ticket) but the import had started to import collected materials more than once. 
I have thrown them out and ran the import again and it should be remedied. But please keep an eye on it.
