### ISSUE TITLE
Recording App: 3 digits lot number not showing up correctly

### ISSUE THREAD

**Issue by maychu16** [arch-kiosk/arch-kiosk-office#2487]
I think there is a limit on how many lots can be there. When I tried lot 100, it shows Lot?OF (Photo 1)
When I tried lot 101, it said I need to talk to the boss. (Photo 2)
Could you please add more number for the lots?

<img width="1512" alt="Screenshot 2024-01-19 at 11 34 15 AM" src="https://github.com/arch-kiosk/arch-kiosk-office/assets/153842762/84bc3310-69a0-4a63-91f6-1bbbeab1f1dc">
<img width="1512" alt="Screenshot 2024-01-19 at 11 36 25 AM" src="https://github.com/arch-kiosk/arch-kiosk-office/assets/153842762/2d37503f-c981-4f5d-8288-77112bd3089e">

**Comment by urapadmin** [comment]
### recording 15.13.2
- this should generate numbers > 99 and not complain for project's that use "lot_auto_generate"="nope", which should be the case for BUAP.
- for other projects which have lots being created automatically it should work as before. lots are generated within a locus number and more than 100 lots per locus we don't allow.

**Comment by maychu16** [comment]
Although the number is not showing correctly, it did pull in the correct collected materials from the database. 

![Uploading Screenshot 2024-01-19 at 12.59.37 PM.png…]()

**Comment by urapadmin** [comment]
> Although the number is not showing correctly, it did pull in the correct collected materials from the database

That is correct. In fact the lot "100" had been created (only 101 was prevented) and the number just does not show properly in the recording app. So this makes sense.

**Comment by urapadmin** [comment]
### recording 15.13.2
- Lots were originally meant to be 2 digits with leading zeros, so a 2 would automatically be displayed as 02 and anything longer than two digits would produce the ?OF. Now Lots still have leading zeros IF they are smaller than 2 digits. otherwise they are just displayed as they are. So 2 becomes -02 and 112 becomes -112. I dropped the ?OF entirely.

**Comment by luizaogs** [comment]
Lutz, can you release 15.14 on BUAP test so I can test this stuff there? I don't think I can get it on PVD (or at least, not without creating 100+ lots) and I obviously do not want to test it on real BUAP.

**Comment by luizaogs** [comment]
Kidding. With the new config keys I think I can do this in PVD.
