### ISSUE TITLE
Recording App: Numbering for new lots (running number?)

### ISSUE THREAD

**Issue by maychu16** [arch-kiosk/arch-kiosk-office#2488]
When I was creating new lots until a few day ago, the number I get was always the latest running number of the whole unit. That is why I cannot create the same Lot number before. 
This morning, for some reason, the running number I get is just for the Locus. So now there can be two of the same lot numbers in the unit. 
We were not sure what is going on here. 

<img width="1512" alt="Screenshot 2024-01-19 at 11 53 05 AM" src="https://github.com/arch-kiosk/arch-kiosk-office/assets/153842762/2ac02c7f-e1cd-4b9e-aa16-c1238623f098">

**Comment by urapadmin** [comment]
### recording 15.14 
this should be covered by #2490

**Comment by luizaogs** [comment]
I don't think I can test this until I figure out the unit part (#2490). Lutz, help.

**Comment by urapadmin** [comment]
I am here. on it.

**Comment by luizaogs** [comment]
Should be fixed based on the tests I conducted in #2490
