### ISSUE TITLE
Recording App: Error Message for Creating New Lot with alphabets

### ISSUE THREAD

**Issue by maychu16** [arch-kiosk/arch-kiosk-office#2489]
This is just a need to change the language for the error message.
I was trying to add 34b but it won't let me add it saying it already exists when it doesn't. I think we just need to change the language for the error pop up saying it doesn't allow alphabets in lot numbers. 

<img width="1512" alt="Screenshot 2024-01-19 at 11 56 59 AM" src="https://github.com/arch-kiosk/arch-kiosk-office/assets/153842762/081f804f-1432-4f73-bdb2-3ca923104ddc">

**Comment by urapadmin** [comment]
### recording 15.14
- you should get a clear error message, one that you cannot ignore, when using non-numeric lots.
