### ISSUE TITLE
kiosk/recording app: Lot list

### ISSUE THREAD

**Issue by maychu16** [arch-kiosk/arch-kiosk-office#2491]
For the legacy data input, it would be nice to have a lot list either in kiosk or in recording app. Sometimes I need to create a new lot (for lots that have alphabets in the original recording), and I need a number that hasn't yet existed but as of now there is no easy way to do this since there is no lot list and the collected materials are not sorted correctly in order in the recording app.

**Comment by urapadmin** [comment]
I can easily produce that list. But it would only show the lots that have been recorded so far in Kiosk. How do you prevent using a new lot that is being used later in the journals?

**Comment by maychu16** [comment]
I realized after requesting this that I will have to go check the recording books for all lots and need to add it first. But luckily as of now I only need to do it for one unit and it is manageable. So this feature isn't urgent at all or even necessary since this only happened for that one unit.

**Comment by urapadmin** [comment]
closed until it comes up as a wish again...
