### ISSUE TITLE
locus/collected material: sortable column headers

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#2493]
if only it weren't the same stupid manual work with every single of those lists in FileMaker. But it is.
locus/collected material is currently sorted statically by the field "created". The columm headers should be clickable to determine the sort order.
Same as #2483

**Comment by urapadmin** [comment]
### recording app 15.20
- sortable they are

**Comment by luizaogs** [comment]
Is there a reason why the sorts for everything is in descending order, other than for type, which seems to be ascending? (I'm basing this off of the direction of the arrows.)

**Comment by luizaogs** [comment]
Oh wait, material is ascending too. Maybe I'm going crazy.

**Comment by urapadmin** [comment]
we usually look at dates and identifiers in descending order. But for material and type I find that strange so there it is ascending.

**Comment by luizaogs** [comment]
Ah ok, just wanted to make sure.
