### ISSUE TITLE
recording app: incorrect message about exceeding 100 lots

### ISSUE THREAD

**Issue by luizaogs** [arch-kiosk/arch-kiosk-office#2494]
I think this is a problem but since I still need to test about 500 lot configuration keys I'm not sure, but reporting it before I forget. 

I'm testing the auto generation of lots and I just got a message that I have exceeded the max 100 number of lots for a context, though the context clearly only has one lot: 

<img width="1029" alt="Screenshot 2024-01-20 at 8 30 56 AM" src="https://github.com/arch-kiosk/arch-kiosk-office/assets/67970402/68cf7731-4d74-4683-b227-e8114334c6a0">

**Comment by luizaogs** [comment]
Also getting this if I have no contexts. The combination of config keys I have currently is nope for auto_generate and free input for input_type: 

<img width="1021" alt="Screenshot 2024-01-20 at 8 38 10 AM" src="https://github.com/arch-kiosk/arch-kiosk-office/assets/67970402/3e70a4dc-0083-489c-9136-f9c1ed6077e8">

**Comment by luizaogs** [comment]
I'm also getting this for units, even if I do not have 100 lots in that unit.

**Comment by urapadmin** [comment]
that's miserable failure across the board then

**Comment by urapadmin** [comment]
> I think this is a problem but since I still need to test about 500 lot configuration keys I'm not sure, but reporting it before I forget.
> 
> I'm testing the auto generation of lots and I just got a message that I have exceeded the max 100 number of lots for a context, though the context clearly only has one lot:
> <img alt="Screenshot 2024-01-20 at 8 30 56 AM" width="1029" src="https://private-user-images.githubusercontent.com/67970402/298295197-68cf7731-4d74-4683-b227-e8114334c6a0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU3NzEwNjcsIm5iZiI6MTcwNTc3MDc2NywicGF0aCI6Ii82Nzk3MDQwMi8yOTgyOTUxOTctNjhjZjc3MzEtNGQ3NC00NjgzLWIyMjctZTgxMTQzMzRjNmEwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTIwVDE3MTI0N1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRiNDFiYjVhMDg2OTk1NmJmZjEzZDAzNDU5MDVkMzcwOTU1MDVjZTA4NWQ0MzQwZmE2MzQ3N2M3ZTA1ZDY3ODkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.o6y4Vx0QJ-C-PGzpyZqQ1lt0LdzdZlhsX5ERxILgc5I">

so in this one you had auto_generate "yup" and input_type "auto" and lot_domain "locus"?

**Comment by urapadmin** [comment]
ja, I can reproduce this one. Good.

**Comment by luizaogs** [comment]
I basically got the wrong warning for any combination of keys I was using.

**Comment by urapadmin** [comment]
ja this would have happened more or less as soon as you have an upper limit. Sometimes FileMaker does not take 100 for a number. Why that did not happen to me yesterday I can't tell. 

### recording 15.14.1
- it should be okay now

**Comment by urapadmin** [comment]
in this case it also makes sense to work with a lower upper limit, just because I once had the 100 hard coded and we would not catch a left over line with that in if we keep testing with 100.

**Comment by luizaogs** [comment]
Looks good now, and I tested with max 78 rather than 100 just in case.
