### ISSUE TITLE
recording app: search has overlapped text

### ISSUE THREAD

**Issue by luizaogs** [arch-kiosk/arch-kiosk-office#2495]
Probably small and silly, but in testing #2485 in PVD (before even typing an identifier in, in case you want to reproduce it) I get some overlapping text in the search window which makes it hard to see things properly: 

<img width="619" alt="Screenshot 2024-01-20 at 10 16 43 AM" src="https://github.com/arch-kiosk/arch-kiosk-office/assets/67970402/ba46308b-0687-4f72-aa81-608d3874e052">

**Comment by urapadmin** [comment]
that's for later.

**Comment by urapadmin** [comment]
### recording app 15.19.1
- too long texts break into lines now

**Comment by luizaogs** [comment]
Does not look right: 

![Uploading Screenshot 2024-05-18 at 1.11.29 PM.png…]()

**Comment by urapadmin** [comment]
needs a bit space between the columns

**Comment by urapadmin** [comment]
### recording app 15.20.1
there should be enough space now to distinguish the columns
