### ISSUE TITLE
kiosk/recording: mark data for different levels of access in publication

### ISSUE THREAD

**Issue by lbestock** [arch-kiosk/arch-kiosk-office#2501]
Very much a future ticket.

I am thinking about getting the BUAP data online and accessible.
For this data, all of it can go up and that is not a problem, but the issue is a substantial one in disseminating archaeological data: what data, and at what point, can/cannot be made public? And do we want to think about a way to mark things in Kiosk to manage that so that for instance the information is archived with all of its contextual links, and accessible to a restricted audience (the researchers who produced it at least), but not to general users of the website publishing the material. An example of the type of thing that might need to be redacted: site location (maps and coordinates), or images of burials. An example of something that might be rather a time issue is Abydos - I would not have been allowed to put this material online immediately after a season, as the SCA retains right of first announcement on all discoveries. 

Sort of like file picking rules for accessibility.

I am reading [this](https://www.cambridge.org/core/journals/advances-in-archaeological-practice/article/will-it-ever-be-fair/9073D28A74C2FE87E53B3C5A7437AC74) in thinking about it.

**Comment by urapadmin** [comment]
Kiosk won't be a publication platform so all these thoughts are rather questions for the platform that actually publishes things -> Library. I would expect such software to have accessibility rights and publication and reviewing workflows etc. A different world and even thinking about it briefly tells me that it would clutter Kiosk as a recording system. Yet another reason not to mix these things up.
But whether the data should be recorded in Kiosk might be to some degree valid. But not separate from the publication platform. First we need to know what transferring data to such a platform actually means and how far that even is an automated process. I have my doubts there and rather expect this to be a legacy grave for the library team. What if they have "finished" a project like BUAP publication and then new stuff comes pouring in, changes are being made etc. ? Who does that and how? If that needs the library staff over and over again they are screwed.

**Comment by urapadmin** [comment]
closed due to inactivity
