### ISSUE TITLE
kiosk: file repository not returning expected files from a description search

### ISSUE THREAD

**Issue by lbestock** [arch-kiosk/arch-kiosk-office#2502]
Searching "harpocrates" (cap or not) in description in the file repository of BUAP gives me no returns. But "Statue of Harpocrates" is a description of ANC37705 and I thought that worked previously. (Works fine as a text search in the recording app.)

**Comment by urapadmin** [comment]
Basically it is the image descriptions that are searched (that's the context-independent and the context-specific descriptions of an image). Those would not have harpocrates in it, or at least I don't see where that would come from.

And then we have a horribly hard-coded addition in the description search: the small find description and material (so the small find type) would be searched, too. So if you have a harpocrates image that is bound to a small find that has harpocrates in its description, that should be found. We are not talking about the collected material description, here! That is not being searched.

**Comment by urapadmin** [comment]
Q&V will do this much better when it offers full text search one day. And then I would even want to get rid of the horrible hardcoded exception in the current search. Until then you have to use the recording app.

**Comment by urapadmin** [comment]
okay. The hard-coded search of the small find description is not only horrible it is also moot because we gave up on the small find description entirely in 2022 here: #1502. I am too old to remember all these little details, we need a new developer.

It does not explain, though, why you think you had typed in harpocrates and got a result in the file repository. But you will again as it is easier to change the horrible hard-coded search to CM than getting rid of it.

**Comment by urapadmin** [comment]
### Kiosk 1.5.20.6
- searching for description in the file repository is now covering: 
  - the context-dependent (I guess) and context-independent (I see) image descriptions
  - the collected material description (deprecated, will go with Q&V full text search)
  - the small find type (deprecated, will go with Q&V full text search)

**Comment by urapadmin** [comment]
we have a ticket now for the full text search: #2504

**Comment by luizaogs** [comment]
Wait, so should this work for the deprecated items or not?

**Comment by urapadmin** [comment]
yes. They are only deprecated. Meaning, one day they will go away. But right now it should work.

**Comment by luizaogs** [comment]
Yeah, this is all working.
