### ISSUE TITLE
urap query: find "whorl"

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#2503]
URAP - find every place the word "whorl" appears. I don't remember ever finding a spindle whorl ourselves

**Comment by urapadmin** [comment]
CM description seems to be the most likely place for it, but the file repository would have caught that. 

So I fear that there is nowhere. I hoped this morning that it was a small finds type, but that does not seem to be the case. So I think I can exclude that anything from Wheeler was called a spindle whorl when entered into Kiosk, and now I have to go through the whole printed catalog and see if that reflects finds or bad data entry. And we did not register anything as a spindle whorl, or describe it as such in CM. If it's really easy to ask if "whorl" pops up in any narratives then I would still ask it, but the chances are very slim if the word isn't attached to any CM.

**Comment by urapadmin** [comment]
> CM description seems to be the most likely place for it, but the file repository would have caught that.

We know now that that was not the case because the obsolete small find description was searched.

**Comment by lbestock** [comment]
Well, it will help archaeologically because there is no such thing as a spindle wheel and so I have a spindle whorl, there. Argh.

**Comment by urapadmin** [comment]
searching pottery notes for both whorl and spindle did not reveal anything more

**Comment by urapadmin** [comment]
can we close?
