### ISSUE TITLE
recording app: able to log in without a user at all

### ISSUE THREAD

**Issue by luizaogs** [arch-kiosk/arch-kiosk-office#2505]
I THINK this is a bug? Seems wrong. I accidentally pressed return on my Mac right after opening the database and before typing in my username and it logged in anyway. Have tried it again, same results.

**Comment by urapadmin** [comment]
it might just have used the default? If that does not need a password then the return would have been buffered and used as soon as the login dialog appeared. You might not have seen it appearing and immediately vanishing. Possible?

**Comment by urapadmin** [comment]
ah, okay, that was the information I was missing, Yes, then it must be a bug. two tickets closed one new 😬

**Comment by luizaogs** [comment]
I'd say we've closed at least 5 :)

**Comment by urapadmin** [comment]
### recording 15.19.2
- it was possible to enter with an empty user id. Not anymore.
