### ISSUE TITLE
file repository: Tool to re-render thumbnails in the background

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#2506]
Coming out of #2440: 
Now that the colour issues are solved, all thumbnails need to be re-rendered bit by bit. That needs a tool that can run in the background.
Perhaps the administration module can start that process in the background for a project.
Or it could be a command line tool that I start on Beset.

**Comment by urapadmin** [comment]
### Kiosk 1.5.21 and MCP version 0.3
This got a bit bigger than I wanted:
- an improved MCP version 0.3 understands the "background_job" attribute. Such a job can run parallel to others and does not keep even system-lock jobs from starting (otherwise there would have been no synchronization while the file cache refresh was running.
- administration has a "trigger file cache refresh" button that starts the new file cache refresh process in the background
- the button is disabled while a file cache refresh job is running
- the file cache refresh job re-creates all cache-entries that are marked as "renew" and creates all cache entries that are "invalid". Housekeeping would not do anything about cache entries marked as "renew". Nor would unpackiosk. 
- the file cache refresh job pauses while other non-background jobs for the project are running. 
- unpackkiosk sets all cache entries to "renew" when using the --clear_file_cache option. It actually deletes and invalidates the file cache when using --clear_file_cache=force. The latter leads to immediate recreation of the auto representations at the end of unpackkiosk if the housekeeping option is on.

**Comment by urapadmin** [comment]
@luizaogs:
I used this on MADP and I think your orange should be better by now:
![image](https://github.com/arch-kiosk/arch-kiosk-office/assets/38838314/45d697b6-78da-46f1-af50-b80f2a2d3063)

(the left small sliver is the Kiosk preview and the right is the NEF).

**Comment by urapadmin** [comment]
please have a thorough look and then #2440 can be closed, too.

**Comment by luizaogs** [comment]
Yes, it looks good to me now. Sandstorm filter is gone.
