### ISSUE TITLE
kiosk/recording app: re-new thumbnails for projects

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#2509]
after #2440 is fixed all projects need a complete renewal of their thumbnails:

- [x] BUAP
- [x] MAD-P
- [x] URAP
- [x] KHPP
- [x] MKAP
- [x] PASU
- [x] USTP
- [x] KAMBE
- [x] ARCH1900 
- [x] PACHA

**Comment by urapadmin** [comment]
@lbestock: URAP thumbnails (which means all image versions that are not the original) are renewed. Can you please check?

**Comment by lbestock** [comment]
They look good. Less vibrant than before :) So less surprise when I download a NEF, even though I always liked the vibrancy.

**Comment by urapadmin** [comment]
@logs, @didi-elbehaedi : The MKAP images are re-rendered, too, to get rid of colour issues. Please check if the file repository images look okay to you.

**Comment by luizaogs** [comment]
You tagged another logs :) But yes, MKAP looks good to me.

**Comment by urapadmin** [comment]
oops
