### ISSUE TITLE
HM: contemporary and non-contemporary contradictions are not found

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#2512]
It looks to me that while circles of non-contemporary relations are found, circles, or rather contradictions, that originate in a mix of contemporary and non-contemporary nodes are not:

![image](https://github.com/arch-kiosk/arch-kiosk-office/assets/38838314/812fc039-558a-4978-9562-a9b675ee0651)

But they should

**Comment by luizaogs** [comment]
I think it worked? LA looks like this now, which is much better than your screenshot above: 

<img width="693" alt="Screenshot 2024-02-24 at 11 55 56 AM" src="https://github.com/arch-kiosk/arch-kiosk-office/assets/67970402/8594776b-fb41-47a9-91f9-804be51e98bb">

**Comment by urapadmin** [comment]
the question is: Is it correct or rather did my algorithm remove relations in a reasonable way? But that is very hard to test and I think we should wait for #2530, which will show the removed relations, to make it easier to analyse the situation. 
What befuddles me in the screenshot is the locus "108". Does the recording data support that?

**Comment by luizaogs** [comment]
It's cut by LA-004 so yes, I believe so.

<img width="1028" alt="Screenshot 2024-02-24 at 4 36 25 PM" src="https://github.com/arch-kiosk/arch-kiosk-office/assets/67970402/c8b55881-ab84-4052-a83c-c306e48e3faa">

**Comment by luizaogs** [comment]
Looking at this again now with the removed relations listed and CC and CA both show cyclic and non-temporal relations having been removed, and LA shows only non-temporal removed. I think this is working.

**Comment by urapadmin** [comment]
yes, but see #2570

**Comment by luizaogs** [comment]
Ok - I'll wait for you to investigate #2570

**Comment by urapadmin** [comment]
LA was wrong, indeed, see #2570

**Comment by luizaogs** [comment]
Ok, I've made comments in #2570 so close this. LA is good now.
