### ISSUE TITLE
HM: Some line issues that did not show in FA

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#2513]
in MKAP:
![image](https://github.com/arch-kiosk/arch-kiosk-office/assets/38838314/23c9093b-e9cb-4092-98c8-c34209b69903)

But this also exists in URAP m FI:
![image](https://github.com/arch-kiosk/arch-kiosk-office/assets/38838314/6e999ef3-4a13-426b-968e-78a63b8599a2)

And I have seen it in PASU's H as well. 

one idea to debug this is to vary the color of lines so that one knows which line is going where

**Comment by luizaogs** [comment]
Ah - have you done this yet? I was wondering about why some lines are in different colors and was confused about it so was going to open a ticket, but now I am seeing that maybe this is why? But I am still confused by the different colors though - I thought at first they were supposed to indicate something specific, but then I couldn't find a pattern as to why some were darker orange than others (in MKAP).

**Comment by luizaogs** [comment]
Ah, no - I think I am dealing with your following comment in the release notes: An experiment: the edges are drawn in different colour shades to help telling them apart. So I will open a new ticket: #2519

**Comment by urapadmin** [comment]
Meanwhile the colour version reveals what is going on in the line crowding:
![image](https://github.com/arch-kiosk/arch-kiosk-office/assets/38838314/660180ba-af87-4faf-94d2-f08dd805a7d4)
![image](https://github.com/arch-kiosk/arch-kiosk-office/assets/38838314/06f7493d-6756-431f-a7d9-10a0daee6b94)

So that's not a mistake of the algorithm, thank god, but an unfortunate outcome. I am wondering if I could allow the line connectors to spread a bit more and have the coming and the going connectors on different positions.  I think I'll make that a ticket.

**Comment by urapadmin** [comment]
an attempt to solve this is #2521 
I close this because it is in fact not a bug.
