### ISSUE TITLE
HM: Show contemporary relations

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#2514]
I am still not sure what the best way is to show them.

a) same node color 
b) lines (but where?)
c) markers 
d) show contemporary relations only when clicking on a unit. 

But they are necessary to understand what is going on, particularly when the recorded relations are not right

**Comment by urapadmin** [comment]
### Kiosk 1.5.22
- I have chosen dotted lines and markers for now. Both lines and markers can be switched off, theoretically (there is just no button, yet)
- when a node gets clicked on the contemporary relations of the node get highlighted and come to the foreground. And they get little arrows.

**Comment by lbestock** [comment]
The click on a node, highlight the relations, could be more visually obvious - I only really can see it when there are a lot of relations. Could it be a totally different color? Like red? I am also finding it a little bit confusing in terms of what it means. I click on something and see its relations highlighted and that helps me concentrate and trace thigns but is also potentially a trap - I immediately read it as meaning all the relations, and the HM doesn't render all relations and clicking on a node doesn't produce new lines. Is this misleading? (Too tired to think that through, just noting that the absence of a line in this case is not the absence of a relation, and I might read it like that when they are highlighted for a particular locus, even if I would not read the whole HM that way.)

**Comment by lbestock** [comment]
I really like that the contemporary lines are there. They show me what would have to move up and down together. And I like the dotted lines. I can only see them with some color combinations and particularly hvae trouble with the dotted line going behind a node when the background is white.

**Comment by lbestock** [comment]
Changing line weight rather than color might be more helpful when clicking on a node to see its connections? Not sure.

**Comment by luizaogs** [comment]
Oof, I was going to look at this now but I see that there are a bunch of questions from @lbestock so I think I will wait for @urapadmin to answer them before going in, particularly if they will lead to changes (I am dead and swamped and dead).

**Comment by luizaogs** [comment]
Well but then I was curious so I'm looking at it.

**Comment by luizaogs** [comment]
The click on a node highlight the relations is extremely clear in MKAP. Does it depend on the project's color palette? 

<img width="492" alt="Screenshot 2024-02-01 at 7 06 07 PM" src="https://github.com/arch-kiosk/arch-kiosk-office/assets/67970402/99887284-2322-4582-b441-5fd22b8344fa">

**Comment by luizaogs** [comment]
> The click on a node, highlight the relations, could be more visually obvious - I only really can see it when there are a lot of relations. Could it be a totally different color? Like red? I am also finding it a little bit confusing in terms of what it means. I click on something and see its relations highlighted and that helps me concentrate and trace thigns but is also potentially a trap - I immediately read it as meaning all the relations, and the HM doesn't render all relations and clicking on a node doesn't produce new lines. Is this misleading? (Too tired to think that through, just noting that the absence of a line in this case is not the absence of a relation, and I might read it like that when they are highlighted for a particular locus, even if I would not read the whole HM that way.)

Hm. That's a good point, actually. I wonder the same.

**Comment by luizaogs** [comment]
In terms of contemporary relations, which I guess is what this ticket is about, they look good to me.

**Comment by luizaogs** [comment]
> Changing line weight rather than color might be more helpful when clicking on a node to see its connections? Not sure.

I don't think so? At least not in the MKAP case where the highlighting is incredibly clear.

**Comment by luizaogs** [comment]
Are we still thinking that annotation would be possible here or no? Because my unit in MKAP doesn't have any recorded contemporary relations, but I would add some in interpretation if I had that option.

**Comment by luizaogs** [comment]
> I really like that the contemporary lines are there. They show me what would have to move up and down together. And I like the dotted lines. I can only see them with some color combinations and particularly hvae trouble with the dotted line going behind a node when the background is white.

I think the visibility issues are again because of URAP's color palette - MKAP is quite clear.

**Comment by urapadmin** [comment]
> I click on something and see its relations highlighted and that helps me concentrate and trace things but is also potentially a trap - I immediately read it as meaning all the relations, and the HM doesn't render all relations and clicking on a node doesn't produce new lines. Is this misleading?

I don't understand. It highlights all edges between a selected node and its immediately related node. Colour issues put aside I think that is incredibly helpful in complicated graphs to understand what is going where. So I don't think I understand what you find misleading here.

**Comment by urapadmin** [comment]
I have tried to base all the colours on a project's palette. But it is clear that that isn't possible. Kiosk's colour system has a flaw: It does not define body colors (a color scheme that is being used if there are no dialogs, pop-overs or controls that appear naturally on a coloured background. Instead we would need a palette for just an empty space. I think it is worth adding and that might solve most of the issues here: #2520

**Comment by urapadmin** [comment]
> Changing line weight rather than color might be more helpful when clicking on a node to see its connections? Not sure.

I would rather not, because a heavier line can possibly interfere with lines left and right (or above/below) of it. There is not that much space between the lines. I hope a more controlled colour palette will solve your issues.

**Comment by lbestock** [comment]
![image](https://github.com/arch-kiosk/arch-kiosk-office/assets/49291909/bf0d36fb-bc8b-47eb-8e08-1034b2654a13)
Oh wow the color scheme difference is very extreme. Luiza's screen shot above blew my mind because when I click a node in URAP this is what it looks like, and this is with the background that makes it easiest to see:
![image](https://github.com/arch-kiosk/arch-kiosk-office/assets/49291909/39782941-9658-4a03-bd23-689f9f013837)
That is FA-035 clicked on there. The node itself doesn't change color, and that the line has changed is barely perceptible.

**Comment by urapadmin** [comment]
yes, I know. Hence #2520

**Comment by urapadmin** [comment]
with #2519 this should be fine now in URAP (although it is currently using the Kiosk default body palette for the background and edges)

**Comment by luizaogs** [comment]
This looks good to me in URAP now, but I'll leave it to @lbestock to close.
