### ISSUE TITLE
kiosk: little weird white box next to the hamburger menu

### ISSUE THREAD

**Issue by luizaogs** [arch-kiosk/arch-kiosk-office#2516]
Tiny. I saw that this had appeared when you first released the HM lab but thought it would have then disappeared, but since it's still there I tell you: 

<img width="237" alt="Screenshot 2024-02-01 at 7 02 49 PM" src="https://github.com/arch-kiosk/arch-kiosk-office/assets/67970402/6a537574-8af2-4629-a618-f04c86e987a0">

**Comment by urapadmin** [comment]
That is the strangest thing. I don't see that on URAP or MKAP. Is this Safari or Chrome?

**Comment by luizaogs** [comment]
The screenshot is from MKAP. Chrome.

**Comment by urapadmin** [comment]
Not happening to me. Does always happen? And only in the hm lab module or everywhere? 
But also: You: 💤

**Comment by luizaogs** [comment]
Happens everywhere.

**Comment by luizaogs** [comment]
![image](https://github.com/arch-kiosk/arch-kiosk-office/assets/67970402/15385236-e986-4832-abb2-426dd447d9a9)

Someone is asleep…

**Comment by urapadmin** [comment]
OH, I see. That's when I prefer just to stay awake and enjoy that the creature can find such bliss next to me. Marvellous fur!

**Comment by luizaogs** [comment]
She’s pretty great :)

**Comment by urapadmin** [comment]
I see it now, too. It is only on Chrome. It is messing the animation of the burger menu up all of a sudden. I haven't touched that for years! There must have been a Chrome update of late that introduced this bug.
Hmpf. That'll be a nightmare to figure out. :zzz for me.

**Comment by luizaogs** [comment]
Ha. Well, good night.

**Comment by urapadmin** [comment]
### Kiosk 1.5.26
- I might have eliminated it? Please check all Browsers and iOS, too. My changes might have side effects on different browsers or platforms.
- Fine on Chrome and Firefox on Windows.

**Comment by luizaogs** [comment]
Fine on Chrome, Firefox, and Safari on my Mac. Also fine on Chrome and Safari on my iPad.
