### ISSUE TITLE
HM: ability to un-highlight (? that's not a word) nodes

### ISSUE THREAD

**Issue by luizaogs** [arch-kiosk/arch-kiosk-office#2517]
Am I just using it wrong? Once I highlight a node, I can't un-highlight it - I can only highlight another node instead. I think it would be useful to be able to click on it again and lose the highlight, particularly in light of what @lbestock brought up in #2514.

**Comment by urapadmin** [comment]
Ja, that makes some sense. 
I wonder if it could also be useful to toggle and that way highlight the edges of several nodes. 
In that case clicking on a node highlights its edges, clicking of a different node highlights those, too, clicking again un-highlights them. 
And clicking somewhere on the body, the background, un-highlights everything.

Nuances worth experimenting with.

**Comment by luizaogs** [comment]
Those all make sense to me, particularly clicking on the background to clear everything- I did that reflexively several times before realizing there was no way to clear at all.

**Comment by urapadmin** [comment]
### plugin version 0.3.1
- I have decided to implement only deselecting when you click somewhere on the body for now

**Comment by luizaogs** [comment]
Works.
