### ISSUE TITLE
HM: select layout options from menu

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#2523]
We shall have a little drop down menu with the layout options:
- multi colour edges on/off
- multi colour highlighting on/off
- dark background
(we drop the coloured background)
- light background
- black on white mode (for printing or exporting)

**Comment by urapadmin** [comment]
### hmlab plugin 0.3
There is a drop down menu now with these options:
- multi colour edges on/off
- multi colour highlighting on/off
- dark mode
(we drop the coloured background)
- light mode
- black on white mode (for printing or exporting)

**Comment by luizaogs** [comment]
What is the multi color highlighting supposed to do again? In MKAP it doesn't seem like it's doing much, if anything.

**Comment by luizaogs** [comment]
I guess if black and white only is selected, the node highlighting only highlights the nodes, not the edges. Is that right?

**Comment by luizaogs** [comment]
Otherwise, this is looking really good (and helpful).

**Comment by urapadmin** [comment]
> What is the multi color highlighting supposed to do again? In MKAP it doesn't seem like it's doing much, if anything.

if uses shades for the highlighted edges once you select a node. If it is switched off it uses a solid colour. 
It is really a nuance and I think I switched it off by default? Can't remember.

**Comment by urapadmin** [comment]
> I guess if black and white only is selected, the node highlighting only highlights the nodes, not the edges. Is that right?

yes. b/w is really for printing or exporting the image (later) for some sort of publication or documentation. No multicolour, no highlighting the edges.

**Comment by luizaogs** [comment]
> > What is the multi color highlighting supposed to do again? In MKAP it doesn't seem like it's doing much, if anything.
> 
> if uses shades for the highlighted edges once you select a node. If it is switched off it uses a solid colour. It is really a nuance and I think I switched it off by default? Can't remember.

Yes, it is off by default but I still don't see anything? Am I blind? 

This is it turned off: 
<img width="424" alt="Screenshot 2024-02-05 at 10 01 29 AM" src="https://github.com/arch-kiosk/arch-kiosk-office/assets/67970402/e06f3663-ac57-48bd-9026-4a5beff43378">

And turned on: 
<img width="347" alt="Screenshot 2024-02-05 at 10 02 37 AM" src="https://github.com/arch-kiosk/arch-kiosk-office/assets/67970402/fcb1785a-ff83-41b5-949e-587df9c17bf5">

**Comment by luizaogs** [comment]
Oh wait, weird. So if I go in and just turn it on, it works: 

<img width="344" alt="Screenshot 2024-02-05 at 10 03 39 AM" src="https://github.com/arch-kiosk/arch-kiosk-office/assets/67970402/d05c6b68-da2c-46eb-bbb3-788f13b0669d">

But then if I click multi color edges off and then back on again, while leaving multi color highlighting on the whole time, it no longer works: 

<img width="415" alt="Screenshot 2024-02-05 at 10 04 46 AM" src="https://github.com/arch-kiosk/arch-kiosk-office/assets/67970402/dd42621b-5afd-48e2-ad5d-dc35d04111f0">

**Comment by urapadmin** [comment]
### plugin version 0.3.1
- That was an oops. Should be fixed.
