### ISSUE TITLE
HM: handle the Kiosk reponses better in the case of errors

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#2525]

**Comment by urapadmin** [comment]
### hm lab plugin 0.5
still not beautiful but at least one gets a response when requesting nonsense or with Kiosk malfunctioning

**Comment by luizaogs** [comment]
I see the error when requesting a matrix for a unit that doesn't exist, and that looks fine. Should I be trying to trigger any other errors?

**Comment by urapadmin** [comment]
no, that's actually it for now on this one.

**Comment by lbestock** [comment]
The error message stays after I search for (and get) an HM for a unit with stratigraphic data, which is a bit confusing.

**Comment by luizaogs** [comment]
Sorry, I didn’t try that. I assume this should be reopened, then.
