### ISSUE TITLE
HM: analyze relations and show errors

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#2530]
particularly with 
- #2528 and 
- #2529 
but even without them some relations might not be up to snuff. 
a) the HM component needs to identify such errors and try to render a matrix without the faulty relations (though it is not always clear which relations are the problem, so it might rather be a group?)
b) those errors need to be visualized in 
  - the list of loci: #2527 
  - an error list?
  - visually? (But that would have to be outside of the normal rendering by boldly drawing them across everything else).

**Comment by urapadmin** [comment]
for instance: CC still simply does not load.

**Comment by urapadmin** [comment]
### plugin 0.10
- this is only a first preliminary version that shows all the relations that were removed to break cycles.
- with this it should be easier to test #2402 but also to test #2512 perhaps with a couple of test cases in PVD that need to be designed to attack this. I leave it to you, @arch-kiosk/test if you want to give this a try

**Comment by luizaogs** [comment]
I can try to test this, but I think I need a bit more explanation for you about what you are envisioning it for. What are some types of errors it would catch? Loci that are both earlier and later than other loci, stuff like that?

**Comment by urapadmin** [comment]
it should catch everything that makes a harris matrix impossible. So:
a) direct contradictions like A is earlier than B and B is than A.
b) direct contradictions with contemporary relations: A is earlier than B and B is same time as B
c) and then all kinds of more complex cycles without contemporary relations involved: A -> B -> C -> A 
d) complex cycles with contemporary relations involved A -> B -> C = D -> A 

We already have examples of all of them (CC is full of a), LA has d) but I am sure there are many more). In general I would say the errors we find in already existing data are most interesting. You just need to reconstruct the relations from the recorded data, which is work, to see if the algorithm does a decent job. 

But it also makes sense to construct a few examples in PVD to test if the algo gets it. You can imagine that I myself have tested the most simple examples of the patterns up there, so everything that is a bit around the corner and more elaborate (there can be easily overlapping cycles) is welcome.

**Comment by urapadmin** [comment]
### next steps
- perhaps think of something more intuitive than the toolbar button to show / hide the error pane
- when clicking on a relation it would make sense to actually show the involved nodes
- show the erroneous relations in the graph with diagonal lines that run on top of everything when a node or a relation is clicked on (only as long as the error pane is shown)
- highlight all nodes involved in a cycle when clicking on an erroneous relation or node (again only as long as the error pane is shown)

**Comment by urapadmin** [comment]
no, that would not be necessary. The next steps won't affect the algorithm

**Comment by luizaogs** [comment]
Ok. I'll try to get to it soon! Sorry for the delay, this is going to take more thinking than the usual testing and I need to get a few other things done first.

**Comment by luizaogs** [comment]
I'm trying to get my head around this now, starting with CC. The non-temporal relations are marked as such, but the cycles are not marked as cycles (just earlier). Does it make sense to also mark them as cyclical or something in the error pane? 

<img width="324" alt="Screenshot 2024-03-06 at 2 57 37 PM" src="https://github.com/arch-kiosk/arch-kiosk-office/assets/67970402/fee9f018-2abb-46f1-83fe-c3a490d7acf0">

**Comment by luizaogs** [comment]
Also, should only the non-temporal have the little error ! sign next to it? Or are the cyclical ones missing that?

**Comment by urapadmin** [comment]
### plugin 0.13
- there are different icons for different types of error now: Cycle, Contradiction and Non-temporal

**Comment by luizaogs** [comment]
This looks good to me. Do you want further testing?

**Comment by urapadmin** [comment]
we can always reopen. I am happy about any closed ticket, currently.
