### ISSUE TITLE
HM: FileMaker integration on locus level

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#2531]
given the issues with scrolling and zooming on iOS I would not want to venture and show whole units. Perhaps it is even possible but this here is about visualizing the locus relations on locus level while they get recorded. The biggest concern here is space. Where would one put the graph? Or would one only show it on clicking a button?

**Comment by urapadmin** [comment]
this will need a different JavaScript wrapper around the HM component. Which shows that it was good to keep the HM component as bare as possible.
The wrapper has to translate between FileMaker data and HMNodes and make sure that all the css variables are in place.

**Comment by urapadmin** [comment]
### recording 15.15.1
- there it is. Little button next to the locus relations. 
- Yes, it needs a button, I cannot possibly cram the graph in the locus layout. Not only because of space, also in order not to over-challenge FileMaker
- so far little error checking. Or rather reporting. The same checks as in the harris matrix app in Kiosk run but cyclic relations etc. would not be reported, just dropped. Currently I don't see a good way to get that information in FileMaker let alone how to present it.

**Comment by luizaogs** [comment]
Hm. First testing Filemaker on my Mac and the HM there and in Kiosk is different? 

<img width="1023" alt="Screenshot 2024-03-10 at 9 34 58 AM" src="https://github.com/arch-kiosk/arch-kiosk-office/assets/67970402/01b08bda-db52-4128-8518-edf1f8ed8c5a">

<img width="1068" alt="Screenshot 2024-03-10 at 9 35 07 AM" src="https://github.com/arch-kiosk/arch-kiosk-office/assets/67970402/f5973377-6f62-49bd-8383-951aa4682fb5">

**Comment by luizaogs** [comment]
LA-003 and LA-001 have somehow switched places.

**Comment by luizaogs** [comment]
Again some weird switching of nodes, this time also switching colors for locus types. This is LA-009. Still on my Mac.

<img width="1019" alt="Screenshot 2024-03-10 at 9 44 29 AM" src="https://github.com/arch-kiosk/arch-kiosk-office/assets/67970402/9d8371ad-93ec-4d02-8abc-8c37ab8d2de1">

<img width="1348" alt="Screenshot 2024-03-10 at 9 44 34 AM" src="https://github.com/arch-kiosk/arch-kiosk-office/assets/67970402/61ede2cc-9170-415b-8d03-59b82837a147">

**Comment by luizaogs** [comment]
Clicking around and highlighting nodes and contemporary relations is working just fine on my Mac.

**Comment by urapadmin** [comment]
slightly different node constellations are fine as long as the semantics stay the same

**Comment by luizaogs** [comment]
If you open LA-003 you'll see that things have also moved around and locus type colors have also changed. I'm going to stop checking for this and giving you screenshots because it seems to be a problem across the board.

**Comment by luizaogs** [comment]
> slightly different node constellations are fine as long as the semantics stay the same

Yes, that is the case. So the colors are the issue (if that's an issue).

**Comment by urapadmin** [comment]
FileMaker ist not obeying a project's Kiosk colour palette. It will look the same in FileMaker for all projects.

**Comment by luizaogs** [comment]
Ah ok. Then FM on the Mac is fine. I'm going to look at FM Go.

**Comment by luizaogs** [comment]
FM Go 19 is fine.

**Comment by luizaogs** [comment]
As is FM Go 20. So I think this is good.

**Comment by lbestock** [comment]
This is going to be extremely useful.
I am testing it on an iPad in FA-024, one of my favorite loci, and I have caught some things.
It tells me four relations have been dropped because they were incomplete.
Only two relations are dropped, as far as I can see. As in, there are two floating loci, and I have been through Q&V and there are no other relations that are not represented here. Both of those floating loci do have defined relations to FA-024.
The dropped relations are weird, because they both are in there as complete, by which I mean they have chronological information stated. One of those (FA-015) is a wonky one - its physical relation is adjacent to, which does not have an automatic chronological significance and so maybe that is the issue? But the FA-024 to FA-023 relation should not be a problem at all. That is a "seals" "later than" relation and should be rendered.

**Comment by luizaogs** [comment]
Hm. The PVD loci that I checked matched Kiosk in terms of dropped relations, so I guess we need more complex data for this.

**Comment by lbestock** [comment]
Yes, this is a difference between how the locus HM is not just rendered but computed between Kiosk and FM. In Kiosk there are no dropped relations for FA-024, and FA-015 and FA-023 are both are shown as earlier than it. As the relations would want.

**Comment by luizaogs** [comment]
Well dammit, now that I'm looking through more PVD loci I found one example of a mismatch between the HM in Kiosk and the HM in FM, too. LA-006 has four dropped relations in FM but only two in Kiosk.

**Comment by lbestock** [comment]
This misses simple cycles. I created one that was 1 is later than 2 and earlier than 4. And then I created 4 is earlier than 2. When producing the matrix from 4, I get a sandwich of 2 above 4 above 1. And when producing the matrix from 1 I get a sandwich 4 above 1 above 2.

Each correct for its local relations, but it is a cycle over the three and I thought that was what you expected to be dropped (but not reported). It would be great if we can think of a way to report precisely such a thing - that would be handy to catch right there in the field.

**Comment by lbestock** [comment]
See an example in #2565 for another broken relation that should have been perfectly fine and is doubled in the count. That was one relationship, and a simple "seals" "is later than".

**Comment by luizaogs** [comment]
Sorry. That was a pretty crappy test on my part, it seems.

**Comment by urapadmin** [comment]
I'll look into this tomorrow. But theoretically it can happen that the HM in FileMaker dropps different relations than Kiosk as it also can show nodes with slightly switched places (as Luiza found out above). The reason is the order of the relations as they are processed by the hms. FileMaker sorts these things against my will, Kiosk does not. 

And the order can theoretically lead to the effect that a cycle is processed starting with a different node of the cycle and hence a different relation is dropped from the cycle. 

The results should nonetheless always be valid (and that's why I will look into the examples). But a difference between the HM in Kiosk and the HM in FileMaker is not necessarily an error.

**Comment by urapadmin** [comment]
> This misses simple cycles. I created one that was 1 is later than 2 and earlier than 4. And then I created 4 is earlier than 2. When producing the matrix from 4, I get a sandwich of 2 above 4 above 1. And when producing the matrix from 1 I get a sandwich 4 above 1 above 2.
> 
> Each correct for its local relations, but it is a cycle over the three and I thought that was what you expected to be dropped (but not reported). It would be great if we can think of a way to report precisely such a thing - that would be handy to catch right there in the field.

no, that's correct in terms of rendering the direct relations of the locus visually. A complex cycle can't be detected here because that needs following up the relations of the related nodes. So in something like 1 -> 2 -> 3 -> 1 if we look at 2 then we see 1 -> 2 -> 3 but not 3 -> 1. 

The complex cycles would have to be checked separately and I will have to follow up all the relations I can find starting from a certain locus. New ticket for that:

**Comment by urapadmin** [comment]
> See an example in #2565 for another broken relation that should have been perfectly fine and is doubled in the count. That was one relationship, and a simple "seals" "is later than".

You must show me the actual records. I can't see the table of relations on that photo. It is really important with these relation issues that you give me the chance to reproduce this exactly - even a different order of things can turn out differently.

**Comment by lbestock** [comment]
![EF90ED16-062B-4FCC-9A18-664AD01CBA17](https://github.com/arch-kiosk/arch-kiosk-office/assets/49291909/0ef40e5f-ed6a-4859-b194-83a96801a69c)
Here are the (redacted for public consumption) records in question.

**Comment by luizaogs** [comment]
There isn't more to test here at the moment, right?

**Comment by urapadmin** [comment]
> ![EF90ED16-062B-4FCC-9A18-664AD01CBA17](https://private-user-images.githubusercontent.com/49291909/311689139-0ef40e5f-ed6a-4859-b194-83a96801a69c.jpeg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTAxODg5MDgsIm5iZiI6MTcxMDE4ODYwOCwicGF0aCI6Ii80OTI5MTkwOS8zMTE2ODkxMzktMGVmNDBlNWYtZWQ2YS00ODU5LWIxOTQtODNhOTY4MDFhNjljLmpwZWc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMxMVQyMDIzMjhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wOWQwY2I3ODMyYmQzOWMzN2UzYWU3MTgzMzUxODcwYThiMWQzMTg0MzM3MDQyOGVjNDRmNzExYWJhZmNmZjVmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.LHbMefZgBZaq_fTiXb5wXph9lPEFH7hAZS2yVQxgzpA) Here are the (redacted for public consumption) records in question.

I suspect that this is solved now, too with #2585 and #2584

**Comment by urapadmin** [comment]
So I leave it to @lbestock to close this ticket here finally
