### ISSUE TITLE
HM: pan and zoom

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#2535]
On iOS there are no scrollbars. That's bad.

But even thought that might be solvable I think we need pan (moving the thing around with the mouse or finger) and for sure zoom.
Apparently Safari is too dumb to zoom in on a panel beyond 100%. Ouch. 

Much better for navigation were a mini map: #2536. But pan and zoom is first and the other is for when I have time I never have.

**Comment by urapadmin** [comment]
### plugin 0.6
pan and zoom work like this:
- if the "hand" tool is on (default) you can click on nodes to select them and on the body to de-select them
- if you press the ALT key and click, you can move the graph around
- if the "move" tool is on it works the other way around: You can still select nodes but when you click on the body you can move the graph around (no ALT key)
- if the "move" tool is on and you click on the body with "ALT" pressed, you de-select a node
- you have three zoom buttons that should be self-explanatory (well, the last one just restores to100% zoom and moves the graph back to its origin)
- Perhaps the most useful tool: the mouse wheel zooms in / out to a certain point in the graph

No touch gestures, yet. That's a bit more complicated and touch screen are not what we want to support first with this.
But it also means: no pinching and zooming on touchpads.

**Comment by luizaogs** [comment]
> * if the "move" tool is on it works the other way around: You can still select nodes but when you click on the body you can move the graph around (no ALT or CTRL key)

I'm having a bit of trouble with this one. For instance, if the move tool is on and I am trying to click on a node ... this is where my little hand is and this is the node that gets highlighted, which seems off: 

<img width="1512" alt="Screenshot 2024-02-07 at 9 51 13 PM" src="https://github.com/arch-kiosk/arch-kiosk-office/assets/67970402/4151e7cb-587e-42aa-8b35-6a4d15db4abb">

(The higlighted node is not even visible on the screen, but where the cursor is is where I clicked)

**Comment by luizaogs** [comment]
Oh wait. I take that back. In URAP I can't see the right menu and I didn't realize there was an actual move tool, just the CTRL thing. Hang on...

**Comment by urapadmin** [comment]
urap still has a palette that does not highlight!

**Comment by luizaogs** [comment]
What do you mean? I see the yellow pretty well.

**Comment by urapadmin** [comment]
I should also have mentioned that on iOS only a bit of zoom works. No panning etc.

**Comment by urapadmin** [comment]
the selected node does not get highlighted. At least not when I tested it (iPad, though)

**Comment by luizaogs** [comment]
What I was having trouble with above is actually fine when I have the move tool on, ignore that.

**Comment by luizaogs** [comment]
Seems fine on my Mac...

<img width="759" alt="Screenshot 2024-02-07 at 9 58 13 PM" src="https://github.com/arch-kiosk/arch-kiosk-office/assets/67970402/3a2c79ea-ad6b-4807-abcf-d04c62cad486">

**Comment by urapadmin** [comment]
hm. Funny. Might be a cache issue. My nodes stay green on the iPad

**Comment by urapadmin** [comment]
yup. Now it works on my ipad.

**Comment by luizaogs** [comment]
Should this button be doing anything yet? It's not currently. I don't think it's one of the ones you mention here, but just to make sure.

<img width="56" alt="Screenshot 2024-02-07 at 10 00 01 PM" src="https://github.com/arch-kiosk/arch-kiosk-office/assets/67970402/40dcc803-7329-4264-b8cc-d7d2a02f52fa">

**Comment by urapadmin** [comment]
yes, that's #2515

**Comment by luizaogs** [comment]
Ah ok. I'll head there next.

**Comment by luizaogs** [comment]
Hm. The + works for me but not the -

**Comment by luizaogs** [comment]
> * Perhaps the most useful tool: the mouse wheel zooms in / out to a certain point in the graph. But you have to press the ALT or CTRL key to while you use the wheel

I can't test this - I don't have a mouse wheel.

**Comment by urapadmin** [comment]
> Hm. The + works for me but not the -

you mean the button or pressing the key?

**Comment by urapadmin** [comment]
both work for me in Chrome on URAP.

**Comment by luizaogs** [comment]
Pressing the key. Hm.

**Comment by luizaogs** [comment]
I'm having trouble with the whole + and - thing, honestly. What do you mean when you say to click on the matrix? I even have a node highlighted right now and all + and - do for me is zoom in or out of all of Kiosk, not the HM.

**Comment by urapadmin** [comment]
Ja, apparently you have to click on the white background of the matrix. So e.g. right next to a node but not on the node (that, indeed does not work, currently, which makes no sense). 
And after you clicked thus the matrix has the keyboard focus and gets your keys. 

Do the + and - keys without any other ctrl or so key pressed zoom in and out on MacOS?

**Comment by luizaogs** [comment]
Nope, not even clicking close to a node is working for me anymore. Something must have worked earlier because I got it to zoom in by using the + key at least, but not it stopped. 

On Mac you need to do + or - pls the command key. They don't work by themselves.

**Comment by urapadmin** [comment]
hm. Late night roll-outs. Total mess. 

Well, I guess I will have to look at his on a Mac and fix a few things tomorrow :o)

But now: 💤

**Comment by luizaogs** [comment]
Since only one of the things on your giant list of bullet points isn't working, I'd say it is definitely not a total mess :) 

Good night.

**Comment by urapadmin** [comment]
> Nope, not even clicking close to a node is working for me anymore. Something must have worked earlier because I got it to zoom in by using the + key at least, but now it stopped.
> 
> On Mac you need to do + or - plus the command key. They don't work by themselves.

moved to #2539

**Comment by luizaogs** [comment]
So if that was moved, I think this can be closed no? Unless someone needs to test the mouse wheel?

**Comment by urapadmin** [comment]
yes, that needs a test on Mac

**Comment by luizaogs** [comment]
Ok. I don't have a mouse wheel, so if you guys do I guess this is a @lbestock test.

**Comment by luizaogs** [comment]
Should this go back in test?

**Comment by urapadmin** [comment]
@lbestock: Our big M Apple has a logitech with a mouse-wheel that you can use to test this.

Normal Macs have something you can do on the touchspad that mimics it. Pinch? Or scrolling with two fingers? Something like it.

**Comment by luizaogs** [comment]
If mimicking on the touch pad is sufficient I can try to figure it out?

**Comment by urapadmin** [comment]
sure, otherwise this ticket will never be closed, I suspect

**Comment by lbestock** [comment]
I won't tell you how long it took to get the mouse connected.
This works! With both the actual scroll wheel mouse and the mimic.

**Comment by lbestock** [comment]
I'm not sure the hand tool is useful. At least, in Chrome on the Mac the only way to use it to move is to click control. And that does work, but clunkily -  it pops up a "save image" menu.

**Comment by lbestock** [comment]
Jesus. I get a taste of how much this has driven you both a bit nuts. 
The OPTION key makes the hand tool useful. It's all fine.
