### ISSUE TITLE
HM: right menu missing in URAP (HM too big)

### ISSUE THREAD

**Issue by luizaogs** [arch-kiosk/arch-kiosk-office#2537]
I didn't even realize there was a menu with zoom buttons because I was testing in URAP, where FA is too big - so when you first enter the HM Lab what you see is the screenshot below. Is there a way to snap the menu to fit in the screen, and just have the HM itself move around?

<img width="1512" alt="Screenshot 2024-02-07 at 9 54 18 PM" src="https://github.com/arch-kiosk/arch-kiosk-office/assets/67970402/135884f7-6633-4e06-8455-ab5eaf853cf6">

**Comment by luizaogs** [comment]
The ticket title makes it seem like the menu isn't there at all, which isn't the case - if I scroll right I find it.

**Comment by urapadmin** [comment]
- ja, that should not be the case. There should not be a horizontal scrollbar ever.

- Also: the toolbar scrolls away when scrolling down. Also not helpful, particularly on iPads (at least some very basic support for those should work)

**Comment by urapadmin** [comment]
### plugin 0.7
- this should be fixed
