### ISSUE TITLE
HM: + and - keys are not working properly

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#2539]
> Ja, apparently you have to click on the white background of the matrix. So e.g. right next to a node but not on the node (that, indeed does not work, currently, which makes no sense). 
And after you clicked thus the matrix has the keyboard focus and gets your keys. 

Do the + and - keys without any other ctrl or so key pressed zoom in and out on MacOS?

_Originally posted by @urapadmin in https://github.com/arch-kiosk/arch-kiosk-office/issues/2535#issuecomment-1933424112_

**Comment by urapadmin** [comment]
@luizaogs: 
> Nope, not even clicking close to a node is working for me anymore. Something must have worked earlier because I got it to zoom in by using the + key at least, but now it stopped.

> On Mac you need to do + or - plus the command key. They don't work by themselves.

**Comment by urapadmin** [comment]
### plugin 0.7
this is what I found
If you click on GO and get your first graph and click immediately on a note without ever having clicked on the graph's background the graph would not get the keyboard focus and hence not notice any keys pressed. Only clicking on the white background of the graph would turn the focus on the graph.

- I have fixex that part. Now clicking on a node will move the keyboard focus to the graph. 
- with #2540 I have a vague hope that maybe MacOS works, too (just a hope, I have not tested it)

**Comment by luizaogs** [comment]
This is still not working on my Mac. Clicking on either the node or the white background after GO leads to zooming in or out of Kiosk as a whole when I press + or -, not the HM.

**Comment by urapadmin** [comment]
and you are on Chrome, right?

**Comment by urapadmin** [comment]
and I thought you need an additional CMD key to zoom in and out in the whole Browser. I am confused

**Comment by luizaogs** [comment]
Yes, Chrome. And yes, when I say + or - I am always using CMD before, otherwise they do nothing.

**Comment by luizaogs** [comment]
Oh wait! I'm sorry, I'm dumb. I see -- so you made it so I don't have to use CMD. Ok, in that case, clicking on a node and using the - indeed works. The + is not yet working though.

**Comment by urapadmin** [comment]
ah. Good. No, no CMD. only + and - are supposed to work. I will have to analyze this on a MAC (pain)

**Comment by urapadmin** [comment]
On a US keyboard you need the shift to get a +. That works.

**Comment by luizaogs** [comment]
Ah.
