### ISSUE TITLE
HM: ipad support for dragging

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#2541]
coming from #2535 
One day we might need support for ipads and hence for touch gestures

**Comment by urapadmin** [comment]
try at least to have a look at it before arce. Otherwise it won't be as easy to show the harris matrix.

**Comment by urapadmin** [comment]
### Kiosk 1.5.29.2
- while we do not support two-finger zoom right now, we can at least support dragging on iPads. So now you can move the graph around. For zoom you have to rely on the buttons.
- this at least eliminates the erratic behaviour that we had seen before.

**Comment by luizaogs** [comment]
My iPad is undoubtedly dead so I'll have to test this later.
