### ISSUE TITLE
Kiosk: Identifier selector component

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#2543]
since we need to open identifiers left and right in the future, I should make a general selection component.

- this needs to work with CQL because I want to find identifiers that lead to locus relations. 
- it should be a normal listbox with auto-complete, I guess
- but it would also be handy to have a modal

_Originally posted by @urapadmin in https://github.com/arch-kiosk/arch-kiosk-office/issues/2518#issuecomment-1935073565_

**Comment by urapadmin** [comment]
### has been released as part of Kiosk 1.5.23.4
- first use is in the hm lab plugin

**Comment by luizaogs** [comment]
This is working, I believe. But as mentioned in #2518 I don't know if you want it to stay open.

**Comment by urapadmin** [comment]
this needs a test on iPads, too.
I myself would complain about the missing keyboard support here (no way to select the identifier without a mouse).

**Comment by luizaogs** [comment]
Hm ok, I suspect my iPad is dead so I'll test this soon.

**Comment by luizaogs** [comment]
I'm not sure what you mean on the iPad front? I can select identifiers just fine.

**Comment by luizaogs** [comment]
What doesn't work on the iPad is the move tool, but that's a different issue and I think I saw somewhere that you already know about it?

**Comment by urapadmin** [comment]
and that is all I want :) Safari on iOS is our weakest browser and I only using the more recent browser features, so if things fail, they fail on SafariOn 14. Feb 2024, at 10:34, luizaogs ***@***.***> wrote:﻿
I'm not sure what you mean on the iPad front? I can select identifiers just fine.

**Comment by luizaogs** [comment]
So I think this can be closed? 

Do you want a ticket for the move tool issue?

**Comment by urapadmin** [comment]
these email responses look horrible. I should not react to tickets while I am on my daily walk 🚶 
Let's close this, the move issue is covered somewhere else and as for the keyboard issue: I make that a new ticket.

**Comment by luizaogs** [comment]
You should definitely not check your email while on a daily walk!!
