### ISSUE TITLE
hm: lines hang in the air until selected

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#2545]
PVD unit SB: 
![image](https://github.com/arch-kiosk/arch-kiosk-office/assets/38838314/19a4e156-f044-4545-98f7-2b3136fc414a)

but I have seen it in other places, too. I thought it has something to do with bad recording but:
![image](https://github.com/arch-kiosk/arch-kiosk-office/assets/38838314/8e2dcd7f-cdab-4341-8eb7-4bd4fd6e841d)

Clicking on the node makes the relation visible. So why is it not visible when not selected?

**Comment by urapadmin** [comment]
see fa-058 in #2518

**Comment by urapadmin** [comment]
still okay in MKAP

**Comment by luizaogs** [comment]
Was going to report this in PVD but I see that you have already found it.

**Comment by luizaogs** [comment]
Should this be in testing?

**Comment by urapadmin** [comment]
yes, now it should :o)

### plugin 0.8.0
- found it
