### ISSUE TITLE
hm: load loci with a relation depth of 1

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#2548]
- this is what we will need for #2531 anyhow

**Comment by urapadmin** [comment]
should I try to supply a button that increases the relational depth?

**Comment by urapadmin** [comment]
where should I limit the relations? On the API side already or should I do it in the hm component? The latter might allow for more flexibility

**Comment by urapadmin** [comment]
in fact this is not at all necessary for #2531 but I will implement it for loci in the hm workspace, anyways.

**Comment by urapadmin** [comment]
### plugin 0.11
- This is implemented for loci: If you request a locus from Kiosk you will see that locus and its immediately related loci but not more
- Don't be surprised that a locus and its relations can look quite different in this view from the locus as part of a unit: In a unit view transitive relations are eliminated. If you request only a locus and its immediate relations, no relations can be transitive. So you see the, all. That is in fact, what we want.

**Comment by luizaogs** [comment]
Looked at several loci in FA and this looks good (I compared visible HM relations and relations in the relations list in Q&V).
