### ISSUE TITLE
hm: draw rows

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#2549]
currently we do not show rows (as the hm matrix does). That should not be too difficult.

**Comment by urapadmin** [comment]
### plugin version 0.9.0
I could not decide what the best way to do this would be, so I have extended the layout options by three new options:
- don't mark rows
- mark rows with dotted lines
- mark rows with background
the latter is the default. It somehow seems less distracting than yet another line.

**Comment by urapadmin** [comment]
nope, this is not working with the move tool! Argh. That'll become a nightmare. Apparently some things like those lanes have to partly disobey the transformation matrix.

**Comment by urapadmin** [comment]
I am really not a math genius. But I got it with try and error.
Should work no matter how much you pan and zoom.

**Comment by luizaogs** [comment]
Nevermind, I see the options so I assume 0.8.2.

**Comment by luizaogs** [comment]
For PASU, light background + mark rows with background is not very visible. The other palettes look good to me though, and this is a very helpful addition to the HM in general.
