### ISSUE TITLE
hm: show locus types

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#2550]
Ochre can do it. So can we. 
Question is: How? Colours? eh. I am not so sure can one memorize colours for types? 
I think symbols are easier to memorize. So we need a symbol per locus type. BUT locus types are project-specific and so it would be necessary to configure what symbol to use for what locus type. 
As a fall back I could show the name of the locus type.

Ochre is showing different shapes for nodes. What's that for? Surfaces?

**Comment by urapadmin** [comment]
### Plugin 0.8.2
- locus types are now colour coded with a symbol (the short id for locus types configured in the recording app)
- there are currently only colours for dp, ac, ot and bu. If we have a project with yet another type of locus we can extend the colour palette on a project basis (well, I can) in the custom configuration. Do we have such a project? Anyone with "cut" or so?
- the layout options allow you to switch this off. It is on by default.

**Comment by urapadmin** [comment]
The URAP colour palette needs an update. It is not up to those new tasks.

**Comment by luizaogs** [comment]
PASU has cut so that has to be configured.

**Comment by luizaogs** [comment]
Hm the MKAP cut (ct) appears to already be configured though?

**Comment by luizaogs** [comment]
This is all working as far as I can tell, but I return it to you for the URAP color palette (which is indeed not very visible currently) and to check on the cut configuration, even though it looks ok (at least in MKAP).

**Comment by urapadmin** [comment]
whenever it encounters a locus type that does not have a distinct colour set it falls back to a general background-2 colour. That is why you get the feeling in MKAP that it is configured, you just see that background colour. If you had a second locus type not specifically coloured, you would get the same backgrond-2 colour and the two would be indistinguishable on the colour front. 

I think ct is common enough among projects to give it a general colour in Kiosk. 
@lbestock, @luizaogs Do we have any other that are common? I can add those, too.

**Comment by urapadmin** [comment]
### Kiosk 1.5.24.1
- common colour for cut added

**Comment by luizaogs** [comment]
I was planning to check if there were other common locus types when this feature got released for other projects. Can you release 1.5.24.1 to everyone or is that too complicated? No other ones come to mind immediately.

**Comment by urapadmin** [comment]
I think it is easier for me to just look into the other project's databases.

**Comment by luizaogs** [comment]
I mean, I can also do that, if you want.

**Comment by urapadmin** [comment]
thank you, but I can really look it up straight within the databases (without downloading a bunch of stuff). It is really easier for me.

**Comment by urapadmin** [comment]
### plugin 0.8.3
- using the primary colour now instead of the accent colour, which makes it all a bit better for URAP and should also work for other projects. URAP still needs a better palette.

**Comment by urapadmin** [comment]
KAMBE has a "fl" for Fill
KHPP uses pt for (Pit/Cut)
arch1900 uses "su" for surface collection
USTP uses fi for fill, gr for grave and st for structure (but that was nonsense and should have been architecture)

**Comment by urapadmin** [comment]
### Kiosk 1.5.24.1
- fl and fi get the same colour
- su gets a colour
- gr gets a colour
- pt gets the same colour as ct
