### ISSUE TITLE
hm: colour by tag

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#2551]
At least I guess that's where we want colours. 

But I also wanted to try colours for phasing. 

Could I use something else to mark all the loci per tag?

**Comment by urapadmin** [comment]
### plugin 0.8.2
- there is a new drop down now, showing the locus tabs available for the loci in the matrix
- selecting one marks all loci tagged with that tag with a hopefully clear enough little ear mark

**Comment by luizaogs** [comment]
Works.

**Comment by urapadmin** [comment]
While this is working for now, I am reopening this because my little earmark is hard to see at times.
An idea I want to follow up one day is to show all nodes (and edges) that are not marked by the tag (or connected to a marked tag in the case of an edge) in a transparent way. That way I am hoping that the nodes of interest come to the foreground and the others retreat visually. This is hard to do, so I postpone this for now but it is an interesting option.

**Comment by urapadmin** [comment]
for the time being I think the best is to just colour the whole node instead of just the corner

**Comment by urapadmin** [comment]
### plugin version 0.11
- the tagged loci are now rendered with the ack colour as a background (that's a project's background for success messages).

**Comment by luizaogs** [comment]
In URAP this is incredibly hard to see: 

<img width="550" alt="Screenshot 2024-03-06 at 11 58 26 AM" src="https://github.com/arch-kiosk/arch-kiosk-office/assets/67970402/f4c4c58d-a522-4a15-ae1a-d00e78f44e20">

**Comment by luizaogs** [comment]
Do you need me to check projects one by one?

**Comment by urapadmin** [comment]
no, that won't be necessary. This was about whether it works at all. The URAP colour palette is increasingly problematic, but that is a URAP issue.

**Comment by luizaogs** [comment]
Ok, so do you want a new ticket for that and to close this?

**Comment by urapadmin** [comment]
I'll reopen the URAP colour palette ticket.
