### ISSUE TITLE
kiosk: synchronization tagging all images as NOT_AN_IMAGE

### ISSUE THREAD

**Issue by luizaogs** [arch-kiosk/arch-kiosk-office#2553]
I downloaded MADP since Laurel and I are going to talk about it soon and it gave me a patch to synchronize, which I did. But then synchronization looks very odd - a bunch of errors leading to NOT_AN_IMAGE which I do not think I had ever seen before on MADP, or at least not in this volume or I certainly would have noticed it. Is this normal? Not sure what would have prompted it, since I made absolutely no changes in the database before synchronizing it. 

<img width="1512" alt="Screenshot 2024-02-16 at 8 03 32 AM" src="https://github.com/arch-kiosk/arch-kiosk-office/assets/67970402/44553296-1bb9-44a2-9694-cdad9a4bf22f">

**Comment by urapadmin** [comment]
no, indeed. All of your images are tagged "NOT_AN_IMAGE" now. Unclear why. But since all the thumbnails are there at least, you can ignore it for now. I'll look into it later.

**Comment by luizaogs** [comment]
The same thing just happened in PASU, so this appears to be a bigger Beset issue.

**Comment by luizaogs** [comment]
And in MKAP.

**Comment by lbestock** [comment]
And in URAP, now that I have uploaded and synchronized a bunch of FA phasing tags.

**Comment by urapadmin** [comment]
### Kiosk 1.5.24.1
- fixed

**Comment by luizaogs** [comment]
Can you release this for MADP, please? The NOT_AN_IMAGE tag is still there so I wanted to get rid of it.

**Comment by luizaogs** [comment]
Actually, should I remove the tag manually from MKAP, URAP, PASU? What if it gets removed from something that is in fact not an image?

**Comment by luizaogs** [comment]
I'm going to stop untagging here until you look at #2568, because this will be harder to test otherwise.

**Comment by urapadmin** [comment]
I have released this for MADP now, too.

**Comment by urapadmin** [comment]
for the user's manual: the NOT_AN_IMAGE tag is removed automatically as soon as a file turns out to be an image. I thought that was only the case for the BROKEN_IMAGE tag but it is not.

**Comment by urapadmin** [comment]
A late addition to this older ticket (coming out of #2692):
The difference between tags set or removed by housekeeping (here: NOT_AN_IMAGE) and a user doing the same with bulk tagging is that the latter method sets a new modified date for the image with every tag that's being applied. That is correct as far as Kiosk is concerned. But we learn that tags that are set by the system also should be removed by the system (as is the case). So for the user's manual: Don't bulk untag tags that are applied by Kiosk itself. Currently that's NOT_AN_IMAGE and BROKEN_IMAGE.

**Comment by luizaogs** [comment]
Woops. Sorry.

**Comment by urapadmin** [comment]
No reason to be sorry. You asked, I gave you the go, not foreseeing this side effect. Can be repaired. My Covid brain just did not remember the case at all so I had to wade through logs for a while. Doing that I found out about the rather scary #2694. So some intel and a new ticket came out of it, anyway.

**Comment by luizaogs** [comment]
😳 that is scary.
