### ISSUE TITLE
Kiosk Kiosk kick-off ticket

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#2554]
Let's start thinking about the Kiosk Kiosk on ARCE and compile a list of tasks we need to do (which we then transform into tickets as soon as we tackle them)

- [x] #2560
- [ ] #2639
- [ ] #2561
- [x] #2559
- [x] #2621
- [x] #2558
- [ ] make it
- [ ] think about what scenarios / use cases we want to present
- [x] #2640
- [ ] swag? orange juice? giveaway ideas need a  #2581
- [ ] @luizaogs can send out the flyer and demo schedule to the EEF when ready to invite ARCE goers to come by the kiosk, as well as maybe snag some others not going to ARCE
- [x] #2582

**Comment by luizaogs** [comment]
Does clarify infrastructure at the conference include actually requesting a space? I don't know if there is a deadline, but that presumably needs to happen asap.

**Comment by lbestock** [comment]
Space is paid for. It comes with invitations to the President's Reception for all four of us whose registrations are connected to the Kiosk Kiosk. As well as half-page ads to design.

**Comment by urapadmin** [comment]
do I have to do all these schreckliche things?

**Comment by lbestock** [comment]
Maybe not allllll of them :)

**Comment by luizaogs** [comment]
> * think about what scenarios / use cases we want to present

Is the plan still to make some sort of demo schedule based on who will be available at the table at different times? If so, should we try and figure that out before getting to ARCE? Might be good to send it out to the EEF, etc.

**Comment by luizaogs** [comment]
Lutz, since I can't cure your covid I'll clean up the ARCE tickets instead. I know, helpful. Alas.

**Comment by urapadmin** [comment]
'tis the only way to make the ticket numbers go down right now :o(

**Comment by luizaogs** [comment]
You now have minus 3!
