### ISSUE TITLE
URAP: Amend and improve colour palette

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#2557]
URAP is a but old and does not have a few colours others have. Add them and improve contrast.

**Comment by urapadmin** [comment]
### URAP 18.II.2024
- did that

**Comment by luizaogs** [comment]
I think this looks fine? I'll leave it to @lbestock to close though.

**Comment by lbestock** [comment]
It's legible but I still find it really ugly. Can't we do something about that orange on green for AC? That makes my eyes hurt. I need some restful blue in there or some such.

**Comment by urapadmin** [comment]
### URAP 19.II.24 11:05
new urap-specific colors for HM configured. No orange. If you are still not happy, you can give me rgb or whatnot values for the colors you want and we use those.

**Comment by urapadmin** [comment]
new problem with the urap colour palette: bg-ack is hard to distinguish from the other backgrounds, of course, because they are all green. Hence problems in #2551

**Comment by lbestock** [comment]
![IMG_1477](https://github.com/arch-kiosk/arch-kiosk-office/assets/49291909/e84ae0ea-ed39-4a3b-abc8-fc150b218e7b)
Why do I have two different colour schemes in URAP HM in the same kiosk and plugin versions??

**Comment by urapadmin** [comment]
I suspect it is a cache issue. At least I don't see how it could be otherwise. 
Or are those two different browsers? Safari involved?

**Comment by urapadmin** [comment]
and what if you use Safari on the big mac? That one seems to be having an old colour palette.

**Comment by lbestock** [comment]
Cache. Now it's fine.

**Comment by lbestock** [comment]
Can't this be closed again?

**Comment by lbestock** [comment]
Ha, no, it cannot. Looking at #2556 and I can't see the marked loci because the greens are so similar.

**Comment by urapadmin** [comment]
postponed until URAP becomes relevant again.
