### ISSUE TITLE
think through demo data and then

### ISSUE THREAD

**Issue by lbestock** [arch-kiosk/arch-kiosk-office#2558]
Needs a landing page that is not the Hub but rather includes some information.
Needs to have enough archaeological information in it that it can be used to show features like the HM and File Repository. 
Needs to be blank enough that people can imagine themselves in it.
Demo server website needs to not have a password (is that possible? do we compromise Beset more broadly?)
An infinite download for conference goers who want to poke around.
But also hubs (maybe create 4 for 4 first signers up for a synchronization demo? - some thinking needed about how to demo synchronization with live real users that is not overwhelming) that can be uploaded.
Pre-processing pottery on.

- [ ] there are manual tasks in this thread that need to be done when we reach Pittsburgh.

**Comment by urapadmin** [comment]
@luizaogs @lbestock
The demo server and demo data is online. That's the system we intend to use for demonstration on ARCE. 
This is what I have done so far:

I used URAP as a basis. I copied the sites 'Fortress' and 'Western Desert'. 
then the units FA (big Harris Matrix), CC (bad recording), S003 (Survey unit), F035, F036, F096, F058 with all their loci, collected materials, photos and whatnot to the demo database. The related image files are in the file repository.

"Whatnot" does not include pottery right now, because I think we better have the PASU pottery module activated? We can show the warecode pottery module on a URAP device.

- I have tried to find and replace all real names. But I am sure I missed some:
- [ ] So our task here should be to read through as many records as possible and find personal data that needs to be replaced. DON'T REPLACE IT yourself, I do that in a script. Just tell me what you found that needs to be replaced (I don't even need to know where!). DON'T add or modify data. Those modifications would be eliminated when I reload the test data (which I will do whenever I have to replace a name or something). We might also decide to include data from other projects or more from URAP and that transfer would also eliminate all recording data you would have changed or added.

- You can synchronize and make changes to the configuration, locus types and collected material types, though. I manage them separately.

- I have created the users logs, ldb and orn so far for Kiosk. You guys may log in without a password and give yourself a password.

- when do we involved Oren and May?

**Comment by urapadmin** [comment]
- [ ] we need to go through the file repository and replace images with people that are clearly identifiable with something else. Don't delete them, replace them with something of your choice that isn't personal.

**Comment by luizaogs** [comment]
Will try to get started on this tonight.

**Comment by urapadmin** [comment]
oh, sorry: demo.arch-kiosk.brown.edu

**Comment by urapadmin** [comment]
> Needs a landing page that is not the Hub but rather includes some information.

what's that supposed to mean? Currently we can only set the landing page to one of the modules. So e.g. file repository or Q&V or director's view. Are you thinking of a special landing page here?

**Comment by urapadmin** [comment]
I have added May (mptc) as a user to the demo sever. Same thing: Blank password to begin with.

**Comment by luizaogs** [comment]
> I suggest that we take Anna's unit H from PASU. It has a decent Harris Matrix and ceramic preprocessing. It also has some sherd analysis.
> 
> A question that arises when using data from other projects is: What about images? What about small finds? Perhaps we want to do that only on the conference, where nobody can take the data away.
> 
> Or we create our own records to demonstrate ceramics.
> 
> What do you think?

I would say to use the PASU unit because that will make sense and give users a sense of how ceramics can fit into their Kiosk records - which I don't think fake data that we could come up with would do (think of PVD, though I recognize that it becomes crazier every day and that it was not so bad when we first started using it). Also, making fake data requires time and I at least am not in possession of much of that at the moment.

**Comment by luizaogs** [comment]
> * [ ]  we need to go through the file repository and replace images with people that are clearly identifiable with something else. Don't delete them, replace them with something of your choice that isn't personal.

What do you mean by clearly identifiable? Only those where we can see people's faces?

**Comment by luizaogs** [comment]
(I created a dock for myself because I need the right timezone. I'll delete it later.)

**Comment by luizaogs** [comment]
I've gone through the URAP records. 

To potentially replace: Marten (I guess this was supposed to be Martin?), Elsamany, Ennazeer, Ali (I assume this is Allie), Abi, Abby (I assume this is Abi).

I assume initials and Prof. B are fine.

**Comment by luizaogs** [comment]
> > * [ ]   we need to go through the file repository and replace images with people that are clearly identifiable with something else. Don't delete them, replace them with something of your choice that isn't personal.
> 
> What do you mean by clearly identifiable? Only those where we can see people's faces?

Does this, for instance, need replacing? Or only ones where Miriam is looking at the camera?

<img width="761" alt="Screenshot 2024-04-10 at 7 17 38 PM" src="https://github.com/arch-kiosk/arch-kiosk-office/assets/67970402/0278274f-321c-45d3-9fd2-bb383e64b64a">

**Comment by urapadmin** [comment]
I have a different tolerance here than others. I would replace this as I can clearly identify Miriam, and not only because I have been there in that situation. If faces are hidden by caps & glasses, hats or whatnot, I think we can leave the images in place.

**Comment by urapadmin** [comment]
> I've gone through the URAP records.
> 
> To potentially replace: Marten (I guess this was supposed to be Martin?), Elsamany, Ennazeer, Ali (I assume this is Allie), Abi, Abby (I assume this is Abi).
> 
> I assume initials and Prof. B are fine.

Thank you, that is very helpful.
- [ ] Marten 
- [ ] Elsamany, 
- [ ] Ennazeer, 
- [ ] Ali (I assume this is Allie), 
- [ ] Abi, 
- [ ] Abby

**Comment by luizaogs** [comment]
> I have a different tolerance here than others. I would replace this as I can clearly identify Miriam, and not only because I have been there in that situation. If faces are hidden by caps & glasses, hats or whatnot, I think we can leave the images in place.

Ok, that's done then.

**Comment by urapadmin** [comment]
I have added unit H (and everything related to it) from PASU. Only ceramics preprocessing and the sherd analysis is missing. I'll do that tomorrow.

**Comment by lbestock** [comment]
I am going to go through this this morning but will record here thoughts as I have them, which first off will not be about the data.

- [ ] Consider using the new logo on this project if it's not hard to put on. That will be pretty prominent at ARCE and we want to capitalize on the chance for visual familiarity.
- [ ] The landing page issue. Landing on the hub is fine, I think, but we want then to make sure that there are multiple workstations, that they are named things that make it obvious that the Hub is for bringing together data collected in different places (think "Trench 1 iPad, Trench 2 iPad, Registrar laptop), and include multiple types of docks, so let's think about exporting and reporting. Basically: the first view in Kiosk should be an in-your-face about what it does.

**Comment by lbestock** [comment]
![image](https://github.com/arch-kiosk/arch-kiosk-office/assets/49291909/5f35bb1d-1360-4019-b62f-4a0a593c3652)

What is going on with this? Holes in the dayplan look terrible, missing images looks terrible.

**Comment by urapadmin** [comment]
let's focus on the imported records themselves as long as we are in Providence. That means bringing together all the data from other projects that we want here: Do we want anything more than what we have? Are there systematic issues with the data (like the dayplan issue in H).

Configuration, registration, adding and modifying single records for demonstration, getting rid of stuff etc. can all be done while we are on the way or even at the conference. No need to spend our time on it now.

**Comment by lbestock** [comment]
![image](https://github.com/arch-kiosk/arch-kiosk-office/assets/49291909/599d8fcc-ecd8-49a3-96c4-685fff5125b3)

This does not look good. 

Also F034 was recorded in S003, it looks, but if one goes to F034 the "recorded in" tab is blank.

**Comment by lbestock** [comment]
> let's focus on the imported records themselves as long as we are in Providence. That means bringing together all the data from other projects that we want here: Do we want anything more than what we have? Are there systematic issues with the data (like the dayplan issue in H).
> 
> Configuration, registration, adding and modifying single records for demonstration, getting rid of stuff etc. can all be done while we are on the way or even at the conference. No need to spend our time on it now.

Good plan. We have to configure ceramics though because I need to be able to see that the PASU ceramics data are there to be looked at before we know we have all the data we want from that project.

My current feeling is that the amount of data is just about perfect. It is not overwhelming (good that the Western Desert is just a tidbit) and once we sort configuration so that registration and ceramics do what we want them to, I think it'll be good. I will ask Peter and Anna for permission to use theirs (but I might wait until tomorrow - Anna is defending in 24 hours!)

**Comment by lbestock** [comment]
Inventory! Add inventory data from URAP.

**Comment by urapadmin** [comment]
SU ceramics and ceramic preprocessing is included in the demo and I have tried to eliminate all names that I knew about (strangely few mentions of names at all).
But we have to check again (this time only the new 'H' and related records) if any other name needs to be replaced.

**Comment by urapadmin** [comment]
> ![image](https://private-user-images.githubusercontent.com/49291909/321651904-599d8fcc-ecd8-49a3-96c4-685fff5125b3.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI4NDk4MjcsIm5iZiI6MTcxMjg0OTUyNywicGF0aCI6Ii80OTI5MTkwOS8zMjE2NTE5MDQtNTk5ZDhmY2MtZWNkOC00OWEzLTk2YzQtNjg1ZmZmNTEyNWIzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDExVDE1MzIwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYxNTVmZDA5MGQwYTI3NDY5NzJhMTljODUzMjJiMDA2NmZlMmVjYTk5ZjY5YTVlM2I1NDRhNjYxYjAyODlkMGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ntvn7Ol0SlcxlLvqGbjsjkMKLqQvBnaXRTM_7ShoxCU)
> 
> This does not look good.
> 
> Also F034 was recorded in S003, it looks, but if one goes to F034 the "recorded in" tab is blank.

- [ ] todo: Those things we need to fix manually. Those are just results of ripping parts of the data out of its database.

**Comment by urapadmin** [comment]
- [ ] The qr codes don't render in the demo recording. I had encoding issues when transferring the configuration from urap. Perhaps that is the issue. Just try to import the HTML again.

**Comment by urapadmin** [comment]
- [ ] 

> * [ ]  Coordinate data from MADP - add? Only project that really used coordinate data.
> 
>     * [ ]  Should we consider bringing in other data from MADP? That project used Kiosk very differently than any other and there will be at least as many tomb recording people as excavators at ARCE.

That is for you guys to decide. If so, please tell me which unit.

**Comment by luizaogs** [comment]
> SU ceramics and ceramic preprocessing is included in the demo and I have tried to eliminate all names that I knew about (strangely few mentions of names at all). But we have to check again (this time only the new 'H' and related records) if any other name needs to be replaced.

Names to replace: Damiá, Damià, Lilliu (though this seems to be a past excavator there? I don't know), Quique, Peter, Jeremy.

**Comment by lbestock** [comment]
> * [ ]  colour scheme: Since I don't want to create a new one, I would opt for the MKAP colour scheme. Any Objections?

None from me - it's one of my favorites!

**Comment by urapadmin** [comment]
> > SU ceramics and ceramic preprocessing is included in the demo and I have tried to eliminate all names that I knew about (strangely few mentions of names at all). But we have to check again (this time only the new 'H' and related records) if any other name needs to be replaced.
> 
> Names to replace: Damiá, Damià, Lilliu (though this seems to be a past excavator there? I don't know), Quique, Peter, Jeremy.

You actually found a Peter and a Jeremy? I thought I replaced them.

**Comment by luizaogs** [comment]
If you did, it didn't go through I guess.

**Comment by urapadmin** [comment]
Hm. Full text search does not give me a Peter or a Jeremy, either. Hm. Perhaps I should have reset the recording group after making the changes.

**Comment by urapadmin** [comment]
I will attend to the other names you found and then reset the recording group.

**Comment by luizaogs** [comment]
> * [ ]
> 
> > * [ ]   Coordinate data from MADP - add? Only project that really used coordinate data.
> >   
> >   * [ ]   Should we consider bringing in other data from MADP? That project used Kiosk very differently than any other and there will be at least as many tomb recording people as excavators at ARCE.
> 
> That is for you guys to decide. If so, please tell me which unit.

I don't know if this would be useful or rather demonstrate that Kiosk is not yet optimized for this type of recording. As I mentioned to Laurel when we met about this a couple of months ago, Kiosk was immensely helpful - but we often worked around things, or made things work for us, things that weren't necessarily suitable. For instance, if we add MADP we're going to have hundreds of building blocks as collected material because that is how we recorded parts of walls, which might hinder the demonstration of registration. But up to you - you have my permission.

**Comment by urapadmin** [comment]
> > * [ ]
> > 
> > > * [ ]    Coordinate data from MADP - add? Only project that really used coordinate data.
> > >   
> > >   * [ ]    Should we consider bringing in other data from MADP? That project used Kiosk very differently than any other and there will be at least as many tomb recording people as excavators at ARCE.
> > 
> > 
> > That is for you guys to decide. If so, please tell me which unit.
> 
> I don't know if this would be useful or rather demonstrate that Kiosk is not yet optimized for this type of recording. As I mentioned to Laurel when we met about this a couple of months ago, Kiosk was immensely helpful - but we often worked around things, or made things work for us, things that weren't necessarily suitable. For instance, if we add MADP we're going to have hundreds of building blocks as collected material because that is how we recorded parts of walls, which might hinder the demonstration of registration. But up to you - you have my permission.

I agree with Luiza here. What MADP really illustrates is that we need this more image-based approach to such recording. Since that is the next and last big module we want to undertake, the current workaround might rather drive people away than attract them. But perhaps having a MADP database on one of the iPads, just in case, would suffice?

**Comment by urapadmin** [comment]
> ![image](https://private-user-images.githubusercontent.com/49291909/321649434-5f35bb1d-1360-4019-b62f-4a0a593c3652.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI4NTM3ODQsIm5iZiI6MTcxMjg1MzQ4NCwicGF0aCI6Ii80OTI5MTkwOS8zMjE2NDk0MzQtNWYzNWJiMWQtMTM2MC00MDE5LWI2MmYtNGEwYTU5M2MzNjUyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDExVDE2MzgwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTBlNWQyNGU4NTM5MGI5OGE2ZGE1MzMyNzk4MThhYmE5YjU2M2VkNWUzMTY2NTJkMTUyYjE0NGU2ODA0M2RjYzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.lk7M0n3UsdhpRGOrQ_XBrs7zaGIbw8dHzAUDJC6PKQ4)
> 
> What is going on with this? Holes in the dayplan look terrible, missing images looks terrible.

this should be solved

**Comment by urapadmin** [comment]
> Inventory! Add inventory data from URAP.

done

**Comment by lbestock** [comment]
> > > >   * [ ]     Should we consider bringing in other data from MADP? That project used Kiosk very differently than any other and there will be at least as many tomb recording people as excavators at ARCE.

> > I don't know if this would be useful or rather demonstrate that Kiosk is not yet optimized for this type of recording. 
> 
> I agree with Luiza here. What MADP really illustrates is that we need this more image-based approach to such recording. Since that is the next and last big module we want to undertake, the current workaround might rather drive people away than attract them. But perhaps having a MADP database on one of the iPads, just in case, would suffice?

OK I removed that as a possible action item - I agree with you guys. And no need to pre-load it on an ipad. I mean, if we need it, we log in and download. Because it's pretty cool.

**Comment by luizaogs** [comment]
Question: I just realized the demo icons are not the Egypt specific ones. For ARCE would it not make sense to have the king and crook/flail?

**Comment by luizaogs** [comment]
I liked. You just changed them.

**Comment by urapadmin** [comment]
I also took the demo server down now -> we are offline now!
