### ISSUE TITLE
make a flyer for the conference

### ISSUE THREAD

**Issue by lbestock** [arch-kiosk/arch-kiosk-office#2559]
Trifold handout for people walking by to pick up. 
Must include: photos of use in field.
One or two screenshots but not more.
List of projects using Kiosk that are in Egypt/Sudan (with contact names of people attending ARCE? only if it is impressive and they are willing to speak about it).
FAQs including those specific to Egypt:

- Can iPads work in the Egyptian sun?
- Setup costs.
- Internet needs.
- Support.

Why use it at all and not have your husband make a bespoke Filemaker database?

Look for a trifold template. Get in touch with Allegra about printing times. How many do we want?

**Comment by luizaogs** [comment]
If you want photos of use in Egypt, I have "Kiosk in the field" folders in both the MADP and MKAP drives that should be useful.

**Comment by lbestock** [comment]
Consideration of whether or not this is really the most effective way to do things? Lead time is not minor and we worry about a thing to lose, old-fashioned.

**Comment by luizaogs** [comment]
A QR code leading to a page on the website (one that we could print if you want something physical) would probably be better…

**Comment by lbestock** [comment]
We totally thought that, too! But then, what to put the QR code on...
We were thinking we need to look professional. Like, maybe even a table skirt (so cheesy). I have had total radio silence in the last week from the ARCE person after she asked me to get in touch with her again, so I'm getting a little worried about this.

**Comment by luizaogs** [comment]
I mean, you don't want the QR code to a website page on something permanent. At least, I wouldn't think so. If this were me I would have something like a postcard-sized (or smaller even, more like a business card type of thing) handout with the QR code and maybe a logo. It would be better to have it thick like a postcard, too, rather than a flimsy piece of paper. So then whoever came by could take that and whatever you decide you want to give away in #2581

**Comment by urapadmin** [comment]
QR Code on the back of the north sign. clear case 😀

**Comment by luizaogs** [comment]
But then if the website changes you have a north arrow with a defunct QR code. I don't know, I would separate those.

**Comment by urapadmin** [comment]
> But then if the website changes you have a north arrow with a defunct QR code. I don't know, I would separate those.

I don't see the danger that our web address will change too soon (nor do I think the north sign will actually be used, it is more for the semiotics that I like it)

**Comment by urapadmin** [comment]
ja, I really think the North arrow should be semiotic and does not have to be real. I suspect the real ones are also a but large. And we don't want to clutter the world with more plastic. So the idea would rather be a bookmark sized paper north arrow, perhaps made of a thicker cardboard material, but even that might turn out too expensive as a give-away. I still like the metaphor of it. And the back of it allows us to place Logo, words and a qr code.

**Comment by urapadmin** [comment]
where are we here? Is anything left to do except wait for the printer?
We have decided against a handout in favour of qr code and give-aways, right=

**Comment by luizaogs** [comment]
And we can close this?

**Comment by urapadmin** [comment]
Ja, we are not making a flyer and the rest is under way.
