### ISSUE TITLE
clarify infrastructure at the conference

### ISSUE THREAD

**Issue by lbestock** [arch-kiosk/arch-kiosk-office#2560]
What kind of table setup can we have? Can we get one big presentation table but two small coffee tables with seats, for instance?

We would really like to have a projector and screen but those are too big to travel with. Can they be provided by ARCE/the hotel (and for what cost?)

Would the Joukowsky sponsor this?

**Comment by lbestock** [comment]
Email sent to ARCE 20 II 24 asking these questions and about registrations.

**Comment by lbestock** [comment]
I have been trying to get a bloody phone meeting and tear my hair out about non-communication.

**Comment by luizaogs** [comment]
We can close this, no?

**Comment by urapadmin** [comment]
ja, I think so.
