### ISSUE TITLE
Kiosk kiosk at AIA?

### ISSUE THREAD

**Issue by luizaogs** [arch-kiosk/arch-kiosk-office#2563]
Bigger stage: we should think about AIA in January, too.

_Originally posted by @lbestock in https://github.com/arch-kiosk/arch-kiosk-office/issues/2562#issuecomment-1953241764_

Well I'm in a crappy mood and feeling crappy and apparently opening tickets a year in advance makes me feel slightly less crappy. Cool.

**Comment by luizaogs** [comment]
Are you (we?) still thinking about giving a talk? If so abstract is due August 5th.

**Comment by lbestock** [comment]
Yes. I will move it to the percolating part of my brain, and not try to whip out an abstract before going to Germany. But the AIA is a bigger stage than ASOR and a talk explicitly about Kiosk and its development is needed.

**Comment by luizaogs** [comment]
Last reminder about this (because I am currently writing an abstract for it).
