### ISSUE TITLE
hm: matrix canvas out of bounds

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#2567]
I must have changed something in the layout that causes the matrix to expand to its full width instead of staying within its parent boundaries. Not sure what it is, currently but it also makes the toolbar vanish to the right and scrollbars to appear.

**Comment by urapadmin** [comment]
### plugin 0.9
I might have solved this? It is strange.

**Comment by luizaogs** [comment]
FA looks good and that's the biggest one I know, so this seems fine.
