### ISSUE TITLE
hm: remove relations that are not temporal and list them as errors

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#2570]
Currently non-temporal relations are quietly dropped. That can lead to unconnected nodes in a graph, e.g. FA-019 if you open locus FA-003 as a locus (see #2548). 

- The dropped relations should be listed in the error pane (see #2530 ).

**Comment by urapadmin** [comment]
### plugin version 0.11
- they should be listed now as "non-temporal".

**Comment by urapadmin** [comment]
I thought I saw that it overrides all cyclic relations in LA (wasn't LA cyclic?), so I reopen this to check.

**Comment by luizaogs** [comment]
The only messages I see in LA are that non-temporal (is adjacent to) relations have been removed?

**Comment by urapadmin** [comment]
yes, and I think that is wrong. Wasn't it LA that had crazy cycles?
Anyways, I will look into it.

**Comment by urapadmin** [comment]
see also #2512

**Comment by luizaogs** [comment]
Hm ok. I never saw it like that, but you have that crazy screenshot up there so I guess? I'll let you see what you find then.

**Comment by urapadmin** [comment]
### plugin 0.13
whenever the original recording of a relation stated no chronology but the matrix component was able to amend it by using the spatial type (here: bonds with -> same time as) and that relation was involved in a cycle (for LA e.g. 009 <-> 003) the error list would report it as a non-temporal issue and not as a problem with a cycle. 

- that's fixed now and 
- I added icons for the different types of errors (cycle, contradiction, non-temporal)

**Comment by luizaogs** [comment]
Currently contradictions are showing up with non-temporal relations rather than with cycles. See CA in URAP for an example.

**Comment by luizaogs** [comment]
Nevermind - that's apparently not a contradiction but rather a double relation, as clarified in #2572 . Sorry for the confusion.

This is ok then, I believe.

**Comment by urapadmin** [comment]
yes, see also #2402
