### ISSUE TITLE
hm: unknown relation prevents whole graph from loading

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#2571]
It would be better to list such an error in the error pane:
![image](https://github.com/arch-kiosk/arch-kiosk-office/assets/38838314/0c059572-826a-41e8-82cb-2c19d2ac9548)

**Comment by luizaogs** [comment]
Yeah I'm getting this in PVD, too.

**Comment by urapadmin** [comment]
### plugin 0.13
- this should just be a non-temporal relation leading to the usual error in the error panel now

**Comment by luizaogs** [comment]
Hm no, I'm still getting this. Try MB in PVD.

**Comment by urapadmin** [comment]
That is a different error. The error above would have happened with AA in MKAP. And that opens fine now.
I close this here and make a new one. Sheesh.
