### ISSUE TITLE
HM: blank stripe on right of HM after closing error pane

### ISSUE THREAD

**Issue by luizaogs** [arch-kiosk/arch-kiosk-office#2574]
If I open a HM that has the error pane, if I then close the error pane I get this blank stripe right of the HM: 

<img width="1512" alt="Screenshot 2024-03-07 at 5 09 28 PM" src="https://github.com/arch-kiosk/arch-kiosk-office/assets/67970402/0ad8382c-e018-4900-83e4-a0cc85fcb67b">

Using the move tool doesn't fix it.

**Comment by urapadmin** [comment]
Did you by any chance change the size of your window after the hm was first rendered? It does not react to window changes and stays at its original width.

**Comment by luizaogs** [comment]
Nope. I didn’t change anything.

**Comment by urapadmin** [comment]
### plugin 0.14
- This should not happen anymore
- The new refresh button in the toolbar also fixes layout issues related to the width or height of the matrix (e.g. after you resized your window's width)
