### ISSUE TITLE
Q&V: formatting request for locus relations

### ISSUE THREAD

**Issue by lbestock** [arch-kiosk/arch-kiosk-office#2577]
Tiniest of requests for how locus relations look in Q&V.
The locus to which the relationship is had is currently all the way across the screen, the last column. But it's amongst the most important information, the first thing one wants to know when one is looking at that. I request that the "to locus" column move a few over and be the third column, so that it goes "locus", "type", "to locus" and then chronology and sketch.

**Comment by urapadmin** [comment]
see also #2566

**Comment by urapadmin** [comment]
### Kiosk 1.5.38.1
- changed
