### ISSUE TITLE
ARCE kiosk kiosk: giveaway ideas

### ISSUE THREAD

**Issue by lbestock** [arch-kiosk/arch-kiosk-office#2581]
Notes from a discussion about what to give away (instead of/in addition to a trifold).
The idea: something people walk around with that a) reminds them, and b) advertises to others that we exist.
sticker
bookmark
tote bag (rejected - ARCE will have one)
north arrow with our logo on it
photoscale
tape measures (I refuse to give up on that one)
hand salve (watch me, this will happen)
reusable coffee cup?

**Comment by urapadmin** [comment]
👎 thumbs down for the hand salve. 
Reusable coffee cup: Boring.

**Comment by urapadmin** [comment]
I give the north arrow a 👍 It has some metaphoric value, too. And is nicely related to recording. 
And can be used as a bookmark :o)

**Comment by lbestock** [comment]
At least we can get everyone who will work at the booth a Kiosk mug so we don't have to drink our coffee-break beverages from the crap :) So, not a giveaway but a sort of "ask me about Kiosk" badge.

**Comment by lbestock** [comment]
I thought more like the ones we get in Berlin, the recycled plastic reusable ones. I would want one for myself, America survival style.

**Comment by urapadmin** [comment]
Ah. More plastic. You know that they have a worse environmental impact when they are not reused?

**Comment by lbestock** [comment]
Yeah. Which they would not be. Scrap it.

**Comment by urapadmin** [comment]
also: Where would you get them? Can they be ordered with stuff printed on?

**Comment by urapadmin** [comment]
But I would not discard the real ceramic mug as a token (can be used in video tutorials as well) and equipment for the booth.

**Comment by urapadmin** [comment]
A stamp. I wonder if we can get a stamp made from our Logo with a qr code on. That's very environmental friendly.

**Comment by urapadmin** [comment]
- It all brings us back to: #2582

**Comment by lbestock** [comment]
The stamp with a QR code yes, for sure. I have ordered custom stamps before (think of bag tags in Uronarti!)

**Comment by lbestock** [comment]
![image](https://github.com/arch-kiosk/arch-kiosk-office/assets/49291909/9397b822-271a-4d99-b27b-79e8d7a9feef)
![image](https://github.com/arch-kiosk/arch-kiosk-office/assets/49291909/e49af0e0-bb09-43cc-b47e-d8b9bbfc3091)
For a variety of reasons I think hand balm is a better way to go than lip balm (it's the same recipe, really, but the precise consistency is less important in tins and the containers are cheaper, are two reasons). But labels need work still and I think the print yourself ones will never be as good as ones ordered with the design(s). It is realistic to make a few hundred hand balms before ARCE.

**Comment by lbestock** [comment]
![image](https://github.com/arch-kiosk/arch-kiosk-office/assets/49291909/3469c36c-ea52-421d-822a-835edf911faa)
Photo scale bookmarks also very feasible! (With QR code on the back, I would think, or making actual photos with them would get super annoying). But not on a home laser printer.

**Comment by lbestock** [comment]
![image](https://github.com/arch-kiosk/arch-kiosk-office/assets/49291909/e175e20d-0c45-4097-86bf-d1682aa86bfd)
Mugs also completely can be had.

**Comment by lbestock** [comment]
![image](https://github.com/arch-kiosk/arch-kiosk-office/assets/49291909/0bbc0ec6-5f1d-4556-87fc-9f760c3c609d)
North arrow/photo scale bookmark. Will happen.

**Comment by urapadmin** [comment]
> ![image](https://private-user-images.githubusercontent.com/49291909/313510885-e175e20d-0c45-4097-86bf-d1682aa86bfd.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA3NTE5NzAsIm5iZiI6MTcxMDc1MTY3MCwicGF0aCI6Ii80OTI5MTkwOS8zMTM1MTA4ODUtZTE3NWUyMGQtMGM0NS00MDk3LTg2YmYtZDE2ODJhYTg2YmZkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE4VDA4NDc1MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM0MjkwOGI2YTkyNDNhMzQ0MjI4M2Y5MjRkMmNmNzZlZjZlY2U3Mjc0MmQzY2VmNTE4ZmI1NjMwZTYyOTc3NTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.CVdlIKraSe6xKbWCz62GQHKzkkz53ld0fARP4qbbM1I) Mugs also completely can be had.
> 
> They don't get bulk pricing until you order a zillion. So we could also do individual ones and have out various different phrases on our mugs and see who notices in our videos. I like the round on the mug, I think.

enamel mugs would be more archaeological (and less heavy). But I suppose they  are too expensive.

**Comment by urapadmin** [comment]
If the top of the hand balm tins is a sticker that does not refer to hand balm it can be used as a sticker elsewhere, too.

**Comment by urapadmin** [comment]
Of what material are the tins made?

**Comment by lbestock** [comment]
The tins are aluminum. Not perfect. Now I've ordered a sample of cardboard flat rather than tube shaped ones, the same size as the tins. They are better for marketing, too, with their flat surfaces. But much more expensive and we'll see if they really work. Also could stamp rather than use a sticker for the top and/or bottom.

And we can totally do tin mugs, though I think your idea of what an archaeological project is like is a bit more rugged than most :) I just have to finalize the logo and then I will order a few.

**Comment by lbestock** [comment]
Came across a nice north arrow while evaluating search results in different places than Kiosk.

<img width="685" alt="image" src="https://github.com/arch-kiosk/arch-kiosk-office/assets/49291909/ef22964d-4704-4ed4-8ee5-19d7e1b3a7b0">

**Comment by lbestock** [comment]
Little glass jars with plastic lids might be the non-aluminum but easily available and not outrageously expensive way to go. The paper ones I have a sample coming but they are expensive and slow and I'm not sure about getting enough in time.

**Comment by urapadmin** [comment]
> Came across a nice north arrow while evaluating search results in different places than Kiosk.
> 
> 
> 
> <img width="685" alt="image" src="https://github.com/arch-kiosk/arch-kiosk-office/assets/49291909/ef22964d-4704-4ed4-8ee5-19d7e1b3a7b0">
> 
> 

Do you need a brush up course in Ethics?

**Comment by urapadmin** [comment]
> Little glass jars with plastic lids might be the non-aluminum but easily available and not outrageously expensive way to go. The paper ones I have a sample coming but they are expensive and slow and I'm not sure about getting enough in time.

glass is fine. Small as I hope they are the weight should not be a huge issue

**Comment by luizaogs** [comment]
Balms were clearly a hit and should presumably be made again for ASOR ... need to print arrows at the right scale, too. My very helpful takeaways from ARCE.
