### ISSUE TITLE
MAKE A LOGO

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#2582]
Apart fro the Spider/Kiosk combination that we already have (although we would also need an official vector version of that one, with a chosen font), we need a version that is descriptive since neither the Spider nor Kiosk serve that purpose.
That text is hard to find. 

the simplest I came up with so far are:

Digital
Archaeological
Recording

Digital
Field 
Recording

We have "Archaeological Field Recording and Management" on the web site and GitHub but that's a bit long and technical, I believe. Just "

Archaeological 
Field 
Recording" 

would be a possibility, too.

**Comment by urapadmin** [comment]
So, to be clear, that text would always come in combination with the Spider/Kiosk combination.

**Comment by urapadmin** [comment]
just fuzzing around a bit:

![image](https://github.com/arch-kiosk/arch-kiosk-office/assets/38838314/5f4a6ffc-6eda-4c48-b5e7-7835310c14a9)

**Comment by urapadmin** [comment]
still fuzzing ...

![image](https://github.com/arch-kiosk/arch-kiosk-office/assets/38838314/8aafdcac-4367-463c-8beb-e6cc2a0e51a4)

**Comment by urapadmin** [comment]
![image](https://github.com/arch-kiosk/arch-kiosk-office/assets/38838314/fe98d82c-47d9-4b6e-be19-50e259f2d014)

**Comment by urapadmin** [comment]
![image](https://github.com/arch-kiosk/arch-kiosk-office/assets/38838314/2f7ac524-b0ec-4337-a987-5ddc277b3f4d)

**Comment by urapadmin** [comment]
![image](https://github.com/arch-kiosk/arch-kiosk-office/assets/38838314/cf25c80d-36eb-4d20-b7ab-6ea10cda40c1)

**Comment by urapadmin** [comment]
![image](https://github.com/arch-kiosk/arch-kiosk-office/assets/38838314/b157beeb-72ab-44a9-8ba7-55537ef2de81)

**Comment by lbestock** [comment]
![image](https://github.com/arch-kiosk/arch-kiosk-office/assets/49291909/eb04ac63-9c40-480b-884a-8946a0e71a6e)

**Comment by lbestock** [comment]
![image](https://github.com/arch-kiosk/arch-kiosk-office/assets/49291909/eb4596ae-486f-4b80-963e-0f03a329060c)

**Comment by lbestock** [comment]
![image](https://github.com/arch-kiosk/arch-kiosk-office/assets/49291909/f2e36306-c1a6-40a2-b617-f907f1a24b28)

**Comment by lbestock** [comment]
![image](https://github.com/arch-kiosk/arch-kiosk-office/assets/49291909/56439d1c-c3e7-4b6c-a00a-b0754b96d0e0)

**Comment by lbestock** [comment]
![KIOSK](https://github.com/arch-kiosk/arch-kiosk-office/assets/49291909/afe5a8e9-3509-4537-890a-be1454ca4380)

**Comment by lbestock** [comment]
![KIOSK](https://github.com/arch-kiosk/arch-kiosk-office/assets/49291909/55887870-f746-4a72-af8e-03da03b63bc9)

**Comment by urapadmin** [comment]
it does look a little bit hand made, no?

**Comment by lbestock** [comment]
Intentionally and honestly :) It's drawn on top of a physical stamping. I found using the just pure svg much too slick and cold looking. I might try a little bit more in between.  (Also the first ones are even wonkier looking because those are just pasted images, so even the smooth text of the bottom part looks fuzzy.)

**Comment by urapadmin** [comment]
In the end we will need a vector, though. So you would have to vectorize it.

**Comment by lbestock** [comment]
It is vectorized.

**Comment by lbestock** [comment]
![kiosk logo 3](https://github.com/arch-kiosk/arch-kiosk-office/assets/49291909/fa110f3c-35c2-4d6f-b503-066fd320e872)

**Comment by urapadmin** [comment]
the qr code won't work reliably at that size, I suspect.

**Comment by lbestock** [comment]
![kiosk logo 4](https://github.com/arch-kiosk/arch-kiosk-office/assets/49291909/784ac417-623f-4add-951e-a8bc62a4a51d)

**Comment by lbestock** [comment]
Maybe we do QR codes on some logo applications but not all. The north arrow bookmark can have one, for instance. The round ones work better without it, I'm feeling so far.

**Comment by urapadmin** [comment]
round logos are hard to use. I like them, too, but they are not easy to integrate in layouts. I also note that the style will be hard to combine with other elements. On a web site there is text. So you might want to take the surroundings (even Kiosk itself) into consideration. What is fine on a tote bag might not work on s web site

**Comment by lbestock** [comment]
![kiosk logo 5 flat](https://github.com/arch-kiosk/arch-kiosk-office/assets/49291909/0a16acd9-44e4-40e9-9e9c-4956fb7158ba)

**Comment by lbestock** [comment]
![image](https://github.com/arch-kiosk/arch-kiosk-office/assets/49291909/11d0e07c-d507-4f9e-af9f-a17f20324899)
Round is perfect for little jars of Kiosk hand balm...

**Comment by urapadmin** [comment]
argl

**Comment by urapadmin** [comment]
are you explaining the punch line on the back of your hand balm? :o)

**Comment by urapadmin** [comment]
I add two alternatives that came to mind in the last years:

- Recording that Syncs"

- Off-Grid Digital Recording

**Comment by urapadmin** [comment]
I was wondering if one can make those new AI image rendering tools to create a bunch of archaeologists on Mars using Kiosk.

**Comment by urapadmin** [comment]
> ![kiosk logo 4](https://private-user-images.githubusercontent.com/49291909/313016006-784ac417-623f-4add-951e-a8bc62a4a51d.svg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA0OTU1MTAsIm5iZiI6MTcxMDQ5NTIxMCwicGF0aCI6Ii80OTI5MTkwOS8zMTMwMTYwMDYtNzg0YWM0MTctNjIzZi00YWRkLTk1MWUtYThiYzYyYTRhNTFkLnN2Zz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE1VDA5MzMzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTExMWI3YTYwNTI4NzQ0Zjk5YmE1NGY2YWE0MTc3YWNiOWVhODRhNmFkMzU4YzJhZDM4MTBjZjE2Mzk5YjM3MTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.qZj10pqT102rgZTt6Ylz0i5gqiV0VFd_EXVxF5mkv8Y)

I think I like the more handmade word "Kiosk" better in this settings than the font. Maybe you can work on the handmade one to make the distances and orientation of the single letters a bit more regular but keep a chiselled look?

**Comment by lbestock** [comment]
> I was wondering if one can make those new AI image rendering tools create a bunch of archaeologists on Mars using Kiosk.

Please try this. I would have used this image in a presentation this evening to the prospective graduate students. (At least they get the logo trials and some HM and a picture of the original spider.)

**Comment by lbestock** [comment]
> > ![kiosk logo 4](https://private-user-images.githubusercontent.com/49291909/313016006-784ac417-623f-4add-951e-a8bc62a4a51d.svg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA0OTU1MTAsIm5iZiI6MTcxMDQ5NTIxMCwicGF0aCI6Ii80OTI5MTkwOS8zMTMwMTYwMDYtNzg0YWM0MTctNjIzZi00YWRkLTk1MWUtYThiYzYyYTRhNTFkLnN2Zz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE1VDA5MzMzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTExMWI3YTYwNTI4NzQ0Zjk5YmE1NGY2YWE0MTc3YWNiOWVhODRhNmFkMzU4YzJhZDM4MTBjZjE2Mzk5YjM3MTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.qZj10pqT102rgZTt6Ylz0i5gqiV0VFd_EXVxF5mkv8Y)
> 
> I think I like the more handmade word "Kiosk" better in this settings than the font. Maybe you can work on the handmade one to make the distances and orientation of the single letters a bit more regular but keep a chiselled look?

I can work on it. Frustratingly I cannot find the original file I used to make the stamp the first time, which would have helped. But I have an idea what to do at least, which can be implemented while hand balm cools, maybe already this weekend.

**Comment by urapadmin** [comment]
> > I was wondering if one can make those new AI image rendering tools create a bunch of archaeologists on Mars using Kiosk.
> 
> Please try this. I would have used this image in a presentation this evening to the prospective graduate students. (At least they get the logo trials and some HM and a picture of the original spider.)

![image](https://github.com/arch-kiosk/arch-kiosk-office/assets/38838314/032abe52-8747-4529-9a00-2798cc6aa4b4)

All in google drive under presentations

**Comment by urapadmin** [comment]
I was not able to get a good archaeological trench on Mars out of the AI. But I think it is possible. I was simply nearing the end of my free account.

**Comment by lbestock** [comment]
Oh interesting. The prompt in there says a rectangular trench - was that a response to this weird roundness? It's not so bad a start (I would have used that in the presentation already).

**Comment by lbestock** [comment]
![kiosk logo 6](https://github.com/arch-kiosk/arch-kiosk-office/assets/49291909/53acacf5-8ea9-448d-bbef-5d28b5c4aef1)

**Comment by lbestock** [comment]
![image](https://github.com/arch-kiosk/arch-kiosk-office/assets/49291909/ae4d6d6f-975f-4efa-aae3-60c7f778a1f2)
(That is not really serious.)

**Comment by lbestock** [comment]
![image](https://github.com/arch-kiosk/arch-kiosk-office/assets/49291909/3918ac2c-28d5-4343-a8a7-f8c29eaf175d)
But I'm not sure I'm giving up on round yet. I am giving up on the day, however.

**Comment by lbestock** [comment]
![image](https://github.com/arch-kiosk/arch-kiosk-office/assets/49291909/3b158c69-5103-4f64-ac35-1bb22ccd539b)

**Comment by lbestock** [comment]
![image](https://github.com/arch-kiosk/arch-kiosk-office/assets/49291909/5b34a845-40ef-4cd1-bdc7-af093ba530ce)

**Comment by urapadmin** [comment]
![image](https://github.com/arch-kiosk/arch-kiosk-office/assets/38838314/3c1825e6-940b-4012-8e3c-497edb151850)

**Comment by urapadmin** [comment]
![image](https://github.com/arch-kiosk/arch-kiosk-office/assets/38838314/22704de3-8659-42f9-964b-f086cdf56d0c)

**Comment by urapadmin** [comment]
Just trying stuff. Maybe it gives you an idea.

**Comment by urapadmin** [comment]
I think whatever the logo will be, the handmade style can handle some dirt and scratching. I have uploaded dirt and scratch textures to the google drive under presentations/logo work.
my graphic means are very limited here and I cannot install anything Adobe on my computer without destroying it.
But this guy, whose textures those are, knows how to apply them: https://www.youtube.com/watch?v=bqZVxz84ecg&t=0s

**Comment by urapadmin** [comment]
Still also thinking about the words. What about a three-chime like "Record. Sync. Study" or "Dig. Record. Study." Or "Record. Study. Publish" ....

**Comment by urapadmin** [comment]
> ![image](https://private-user-images.githubusercontent.com/49291909/316211260-ae4d6d6f-975f-4efa-aae3-60c7f778a1f2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTExODc2MTAsIm5iZiI6MTcxMTE4NzMxMCwicGF0aCI6Ii80OTI5MTkwOS8zMTYyMTEyNjAtYWU0ZDZkNmYtOTc1Zi00ZWZhLWFhZTMtNjBjN2Y3NzhhMWYyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIzVDA5NDgzMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRhNmY5YzJiYzRmZWVmYmJmZTQwNGYyY2Q3NDM3MjY2MmM1ODU2OTNlOTU4ZWFjZTg5NzhlNDgwY2UyN2M0MTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.PGN6al6IQYKfxf0wHl_gPeOQ2CdtNH9W5iKz2sKPk9Y) (That is not really serious.)

I worry about contrast issues but putting the spider partly behind the font gives you at least the opportunity to combine the two in a more compact way. I am not a friend of the bend style, though. I am still missing unity. And it really does not work on the screen, as the screen shots below show in my opinion.

**Comment by urapadmin** [comment]
Only while playing around with the horror tattoo spider I realized that the black wood-cut spider is in fact creepy and far from a sympathetic little pet icon. We might want to reconsider that, honesty.

**Comment by lbestock** [comment]
![image](https://github.com/arch-kiosk/arch-kiosk-office/assets/49291909/9e647171-aed9-4bc0-b919-8fdc367ff7ad)

The half-round looks like a hippie sunrise to me. The full round graphical ones look like target practice. The backwards K reminded me simultaneously of the KKK (not sure why) and baseball (a backwards K means strikeout, which I think we don't want). The word "Kiosk" itself is starting to sound Russian to me. And now you say the spider is creepy! I am not going to seek a future career change into icon design.

**Comment by urapadmin** [comment]
doesn't sound like we are getting anywhere

**Comment by urapadmin** [comment]
I suspect insomniac associations are not very fertile ground for design decisions

**Comment by lbestock** [comment]
![image](https://github.com/arch-kiosk/arch-kiosk-office/assets/49291909/97ab8ba2-6a3c-4c77-8d68-84ab8f7622c9)
That tutorial I have to go through very, very slowly because it is _dense._ But helpful.

**Comment by lbestock** [comment]
Hm that looks different on my screen in photoshop than here. Argh.

**Comment by urapadmin** [comment]
I get the gist. I only don't know what you are trying, currently. Away from the spider? Adding a new graphic element? So I don't know how to comment. I do not, though, that the trowel reminded me of a spear head, particularly in the second one.

**Comment by lbestock** [comment]
I am trying things without the spider (two graphic elements there will not be - we discussed that). And trying to learn tools, including adding new fonts to Adobe and the grunginess, which I like.

**Comment by lbestock** [comment]
<img width="793" alt="image" src="https://github.com/arch-kiosk/arch-kiosk-office/assets/49291909/2a3547f8-5e0a-4385-87de-00858391cf6a">

**Comment by urapadmin** [comment]
because I ran into it in my search attempts: Camel Spiders have 10 legs.

**Comment by urapadmin** [comment]
you clearly got the tutorial down.

**Comment by urapadmin** [comment]
while that is impressive. I still think we are going off in the wrong direction. Our original spider is simpler, funnier and more versatile (apart from the fact that we are already using it left and right). I am really not sure what we are communicating with the logo up there. I think we kinda got here only through the woodblock tote bag. which was a funny idea and I love it but it black and white and all and I don't think this is the right choice.

**Comment by lbestock** [comment]
<img width="679" alt="image" src="https://github.com/arch-kiosk/arch-kiosk-office/assets/49291909/c4466891-cf89-493b-b2a5-ed70816991d9">
Ten legs is so much creepier than 6.

**Comment by urapadmin** [comment]
I once read that at least two (if not 4) of them are not actually used as legs. But I can't remember anymore.

**Comment by lbestock** [comment]
<img width="761" alt="image" src="https://github.com/arch-kiosk/arch-kiosk-office/assets/49291909/152468f1-2bb4-4fe7-b136-b9d2dd797de6">
Rocky Mountain Archaeology to me here.

**Comment by lbestock** [comment]
<img width="774" alt="image" src="https://github.com/arch-kiosk/arch-kiosk-office/assets/49291909/e86dc7ca-a01f-426d-b816-a74a393f6f41">


No longer legible as our spider, really.

**Comment by lbestock** [comment]
<img width="596" alt="image" src="https://github.com/arch-kiosk/arch-kiosk-office/assets/49291909/5b5fe676-eb7d-4650-a4e8-4d9df7841da7">


Looks like a wedding ring. This is not the path.

**Comment by urapadmin** [comment]
No. I guess just Logo and spider next to it is simpler. 
You had a version with the spider in the background (the hippi sunrise), perhaps there is a path?

**Comment by lbestock** [comment]
<img width="141" alt="image" src="https://github.com/arch-kiosk/arch-kiosk-office/assets/49291909/7d109a87-b1e5-4a5d-bb7c-4876d387d5e1">


This is not legible (but I accidentally created a new font...)

**Comment by urapadmin** [comment]
I would not say it is not legible, it is more that the format does not work in most scenarios. Is there a reason that the spider is upright? I guess so.

**Comment by lbestock** [comment]
The length of the spider is problematic with horizontal text. Either he goes behind the other letters, or if he is the O the other letters are too far apart.

**Comment by lbestock** [comment]
<img width="531" alt="image" src="https://github.com/arch-kiosk/arch-kiosk-office/assets/49291909/ea4f2c88-4a98-4909-a140-b94743d6d03e">

**Comment by urapadmin** [comment]
> The length of the spider is problematic with horizontal text. Either he goes behind the other letters, or if he is the O the other letters are too far apart.

I was thinking that theoretically you could rotate him. so he walks sidewise. They don't walk upright :o) But not really.

**Comment by lbestock** [comment]
<img width="560" alt="image" src="https://github.com/arch-kiosk/arch-kiosk-office/assets/49291909/428e0f3e-a704-4215-9964-c7495c06b83c">

Here he gets a big more breathing room.

**Comment by lbestock** [comment]
<img width="202" alt="image" src="https://github.com/arch-kiosk/arch-kiosk-office/assets/49291909/826d670a-a371-499f-93c5-d894b07ca482">

Which sideways is this. Rotated spider, pushing aside that 1 and S for all he is worth!

**Comment by urapadmin** [comment]
closing this and continue in #2614 before GitHub closes

**Comment by urapadmin** [comment]
@lbestock, @luizaogs: logos in different sizes now available under presentations\logo work\final in the shared Google Drive
