### ISSUE TITLE
hm: Check HM result for FA-024

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#2584]
I am testing it on an iPad in FA-024, one of my favorite loci, and I have caught some things.
It tells me four relations have been dropped because they were incomplete.
Only two relations are dropped, as far as I can see. As in, there are two floating loci, and I have been through Q&V and there are no other relations that are not represented here. Both of those floating loci do have defined relations to FA-024.
The dropped relations are weird, because they both are in there as complete, by which I mean they have chronological information stated. One of those (FA-015) is a wonky one - its physical relation is adjacent to, which does not have an automatic chronological significance and so maybe that is the issue? It has been assigned the chronological relation "later than" (and see below, Kiosk renders that properly in the HM lab). 

But the FA-024 to FA-023 relation should not be a problem at all. That is a "seals" "later than" relation and should be rendered.

_Originally posted by @lbestock in https://github.com/arch-kiosk/arch-kiosk-office/issues/2531#issuecomment-1987331462_

**Comment by urapadmin** [comment]
@lbestock write:   Yes, this is a difference between how the locus HM is not just rendered but computed between Kiosk and FM. In Kiosk there are no dropped relations for FA-024, and FA-015 and FA-023 are both are shown as earlier than it. As the relations would want.

**Comment by urapadmin** [comment]
### recording 15.15.2
- that was a clear bug: The chronology was not recognized at all.

**Comment by luizaogs** [comment]
No more relations in FM, so FA-024 now matches the Kiosk rendering.

**Comment by lbestock** [comment]
No relations dropped any longer, all is good with this locus.
