### ISSUE TITLE
FileMaker HM: check LA-006

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#2585]
I found one example of a mismatch between the HM in Kiosk and the HM in FM, too. LA-006 has four dropped relations in FM but only two in Kiosk.

_Originally posted by @luizaogs in https://github.com/arch-kiosk/arch-kiosk-office/issues/2531#issuecomment-1987334616_

**Comment by urapadmin** [comment]
### recording 15.15.2
- same bug as for #2584 - fixed

**Comment by luizaogs** [comment]
Matches the HM Kiosk errors now.
