### ISSUE TITLE
PASU: missing scrollbar in su_ceramics?

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#2586]
This might or might not have been solved:
In the specialist ceramics section, a list of scrollable collections appears: when you select one it shows the list of available items on the left. So far so good; the problem is that when there are many items in a single collection (usually many sherds in a single context) and the list is longer than the screen allows, the lower part of the list never shows up.

**Comment by lbestock** [comment]
This looks familiar. See #2219.
