### ISSUE TITLE
kiosk: URAP export error

### ISSUE THREAD

**Issue by luizaogs** [arch-kiosk/arch-kiosk-office#2587]
Haven't seen this before I don't think, so here is a screenshot: 

<img width="1512" alt="Screenshot 2024-03-11 at 10 47 03 AM" src="https://github.com/arch-kiosk/arch-kiosk-office/assets/67970402/f482c313-335c-47c3-bb89-4d9c0ad82d6c">

**Comment by luizaogs** [comment]
I won't try to export again until you see it in case you need the workstation in its current state.

**Comment by urapadmin** [comment]
an old "friend". Perhaps the server was a bit over-challenged and so it took more than 60 seconds long to prepare the file. You may try again. You may try again.

**Comment by luizaogs** [comment]
Nope, same error.

**Comment by luizaogs** [comment]
Rather than starting again, it starts at 95% and fails.

**Comment by urapadmin** [comment]
I'll look into it. Perhaps I made a mistake with the template.

**Comment by urapadmin** [comment]
no, that looks like a different error. And rather a FileMaker is stuck kind of error.

**Comment by urapadmin** [comment]
yup, FileMaker was completely blocked. 
Apart from that nothing wrong except that Beset is not the fastest sometimes...

**Comment by urapadmin** [comment]
URAP might want some filepicking one day ...

**Comment by luizaogs** [comment]
Agreed. Downloading takes forever.
