### ISSUE TITLE
Beset: upgrade to Postgresl 16

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#2605]
Currently Beset projects are using PostgreSQL 12. That's too far behind. Upgrading all the projects is a nightmare, though. There is no easy upgrade path for postgres as far as I can see. So it would be backups and restores for all projects. Grusel. 

A different approach would be installing PSQL 16 parallel to 12 and use the new - #2594 to run it on a different port. Then I could move the projects bit by bit.

I'll try that

But first:
- [ ] #2594

**Comment by urapadmin** [comment]
### Kiosk 1.5.27.1
- PVD is running on a parallel database server on Beset now for testing postgresql 16. You can see that in administration under postgresql:
![image](https://github.com/arch-kiosk/arch-kiosk-office/assets/38838314/63dfc744-fcf1-44b3-acfd-30aa5e101d85)
Now as for testing: try everything. I mean really everything! From Q&V to preparing workstations, changing descriptions in the file repository and synchronizing. The only exception: restore and backup won't work, please don't even try.

**Comment by luizaogs** [comment]
**hub**
delete workstation: works
new workstation: works
prepare workstations: works
upload workstation: works
import: failed with a really scary error

import error screenshot: 
<img width="1512" alt="Screenshot 2024-03-24 at 6 09 04 PM" src="https://github.com/arch-kiosk/arch-kiosk-office/assets/67970402/2d5fe4f7-bd06-4b38-8674-edb647afefcf">

**Comment by luizaogs** [comment]
I'll wait to test the rest until I know whether this is related to this update or not.

**Comment by urapadmin** [comment]
yup, this is an issue that appeared because of the new database version. Hmpf. That will be hard to find. 
However, we are back to postgres 12 for now on PVD.

**Comment by urapadmin** [comment]
notes to myself:
looks like an encoding issue. ''SHOW SERVER_ENCODING;" reveals UTF-8 on Postgres12 and WIN1252 on Postgres 16. I guess I would have had to specify that when installing either PostgreSQL or initiating the database server?

**Comment by urapadmin** [comment]
> notes to myself: looks like an encoding issue. ''SHOW SERVER_ENCODING;" reveals UTF-8 on Postgres12 and WIN1252 on Postgres 16. I guess I would have had to specify that when installing either PostgreSQL or initiating the database server?
> 
> I should add information about that to [the wiki](https://wiki.arch-kiosk.brown.edu/urapdev/doku.php?id=manuals:developer_manual:install_and_configure_postgresql_from_zip_and_set_codepage#how_to_make_sure_you_use_the_right_code_page)
> 
> this might help configure the default locale on Windows itself: https://stackoverflow.com/a/71948417/11150752
I opted out on the world wide beta feature that was mentioned there: Too dangerous on a live system. Instead I change the codepage of the terminal in which I run the postgres command like this:
``` poweshell
chcp 65001
$OutputEncoding = [console]::InputEncoding = [console]::OutputEncoding = New-Object System.Text.UTF8Encoding

```

the latter line is needed in powershell for the first line to show an effect. I don't really understand this, but here it is explained: 

> If setting the system locale to UTF-8 is not an option in your environment, use startup commands instead:
> 
> Note: The caveat re legacy console applications mentioned above equally applies here. If running legacy console applications is important to you, see eryksun's recommendations in the comments.
> 
>     For PowerShell (both editions), add the following line to your $PROFILE (current user only) or $PROFILE.AllUsersCurrentHost (all users) file, which is the equivalent of chcp 65001, supplemented with setting preference variable $OutputEncoding to instruct PowerShell to send data to external programs via the pipeline in UTF-8:
>         Note that running chcp 65001 from inside a PowerShell session is not effective, because .NET caches the console's output encoding on startup and is unaware of later changes made with chcp; additionally, as stated, Windows PowerShell requires $OutputEncoding to be set - see [this answer](https://stackoverflow.com/a/49481797/45375) for details.
> 
> $OutputEncoding = [console]::InputEncoding = [console]::OutputEncoding = New-Object System.Text.UTF8Encoding
> 
>     For example, here's a quick-and-dirty approach to add this line to $PROFILE programmatically:
> 
> '$OutputEncoding = [console]::InputEncoding = [console]::OutputEncoding = New-Object

**Comment by urapadmin** [comment]
### 25. III 2024 15:47 UTC
- back on PostgreSQL 16, hopefully with the codepage issue fixed

**Comment by urapadmin** [comment]
that issue looks okay now to me. Back to you, @luizaogs

**Comment by luizaogs** [comment]
Yes.

**Comment by urapadmin** [comment]
so, you may proceed with your doing-everything-at-least-once-test :o) Though, we are through the roughest part, I guess.

**Comment by luizaogs** [comment]
synchronization: works
synch and dock events: works
administration: seems ok
director's view: works

**file repository**
adding description: works
deleting image: works
import (bunch): works
adding context: works

point repository: appears fine
q&v: view is working, fts is working as expected
hm: working as expected

**Comment by luizaogs** [comment]
Did I forget anything?

**Comment by luizaogs** [comment]
Oh yes.

file manager: working

**Comment by urapadmin** [comment]
did you try to add a file picking rule or a user? Only to see if you can save in those realms. No need to test the file picking rule itself.

**Comment by luizaogs** [comment]
Yes, I just added a rule and it saved just fine.

**Comment by urapadmin** [comment]
okay, well, then it looks okay. 

I think I want to let it run for PVD a while longer and see if anything else comes up, so lets leave this open for a bit.

**Comment by urapadmin** [comment]
okay, today is the day:
- [ ] arch1900
- [ ] buap
- [ ] kambe
- [ ] khpp
- [ ] madp
- [ ] mkap
- [ ] pacha
- [ ] pasu
- [ ] pvd
- [ ] urap
- [ ] ustp

**Comment by urapadmin** [comment]
### Kiosk 1.5.29.1
- as of 5.IV.24 17:20 GMT-5 all projects are on PostgreSQL 16 and the latest Kiosk version.

**Comment by urapadmin** [comment]
test:
- [x] arch1900
- [x] buap
- [x] kambe
- [x] khpp
- [x] madp
- [x] mkap
- [x] pasu
- [x] urap
- [x] ustp
- [x] pvd
- [x] pacha
