### ISSUE TITLE
FTS: Use constants

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#2606]
currently hits are shown as something like "locus". Of course it has to be translated using the constants. Same for record types: collected_materials needs to be translated into "collected materials" on display. Same things as in Q&V

**Comment by urapadmin** [comment]
Is there a way to show the type of unit instead of just "unit"? Like "Survey unit", "feature unit" etc?

**Comment by urapadmin** [comment]
### Kiosk 1.5.29
- these are two different things: the "unit" is the record type and that is the same no matter what the recording method of that unit is (the recording method makes it survey/legacy etc.). So we show the record type. But not the technical term "collected_material" or "unit_narrative" but the project specific term for that. So locus might become context or SU or what have you
- the other one is not as trivial and I want to do it together with #2358, so I make a new ticket:

**Comment by luizaogs** [comment]
In PVD I still see unit_narrative and collected_material in PVD.

**Comment by urapadmin** [comment]
PVD might not be properly configured on that front. I'll check

**Comment by luizaogs** [comment]
This appears fine in MKAP so it might indeed just be a PVD configuration issue.

**Comment by urapadmin** [comment]
- [ ] I must make sure that in the case that there is no constant for a record type I remove the underscore at least

**Comment by urapadmin** [comment]
### Kiosk 1.5.29.2
- even if a project is not configured, the underscores in the record type get replaced with whitespace.
