### ISSUE TITLE
Q&V / FTS: jump to current record and record type in view

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#2613]
this is in fact not limited to FTS but that's where it seems to be most immediately useful:
When clicking on an identifier the correct view for that identifier opens. But there might be match in a different record type that lead to opening that view and it would be nice to navigate straight to that record.

Concrete example: If I find matches in narratives, the unit view opens but now I have to find the narrative. 

So View needs a general mechanism to go to and open (!) a certain part within it.

**Comment by urapadmin** [comment]
see also #2393 as it is strongly related

**Comment by urapadmin** [comment]
### Kiosk 1.5.29
Although a general Q&V feature, this only occurs in FTS right now:
- if you click on a search result you will be transported to the section in the view that shows this information
- if the match is in a list of records (e.g. unit narratives or site narratives) the section will be expanded (if it is collapsed by default) and the record with the match will be scrolled into view.

**Comment by luizaogs** [comment]
I have tried this for a bunch of different record types and it is working, as far as I can tell. The only thing I'm not sure about is whether it's working for images -- if the record type is an image description, view scrolls to the images but not to the correct image. Is that what is intended?

**Comment by urapadmin** [comment]
... as far as you can tell? That sounds a bit hesitant. Any issues along the way?

as for the images - it is not intended to stay that way. I wanted to test this first with the normal data tables and if that works extend it to other lists (well, currently I think that would be just image lists)

**Comment by luizaogs** [comment]
I couldn't find a pattern. When I first started testing I had one or two times when the scrolling didn't totally work, but then it started working for everything except for the images.

**Comment by urapadmin** [comment]
sometimes, when the view is already in view (ja, sorry) in the sense that the tab is visible I don't scroll to prevent wild jumping around. But that's only a thing when one is jumping to an identifier without jumping to a certain part or record. So that can't really have been it. 

However, I think if it works by and large and helps, we accept it at this stage and I make a new ticket for the image lists.
