### ISSUE TITLE
Logo Part II

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#2614]
<img width="202" alt="image" src="https://github.com/arch-kiosk/arch-kiosk-office/assets/49291909/826d670a-a371-499f-93c5-d894b07ca482">

Which sideways is this. Rotated spider, pushing aside that 1 and S for all he is worth!

_Originally posted by @lbestock in https://github.com/arch-kiosk/arch-kiosk-office/issues/2582#issuecomment-2018892161_

**Comment by urapadmin** [comment]
why do we have to look at it sidewise?

**Comment by lbestock** [comment]
We don't. I was playing to see if I could get more elements in there more coherently that way, but I cannot.
<img width="509" alt="image" src="https://github.com/arch-kiosk/arch-kiosk-office/assets/49291909/26ab00bb-3099-4422-b987-c53e0c54dd5f">

**Comment by lbestock** [comment]
<img width="440" alt="image" src="https://github.com/arch-kiosk/arch-kiosk-office/assets/49291909/47cc6b31-40b1-456d-a73f-177045d84a7f">

**Comment by lbestock** [comment]
<img width="435" alt="image" src="https://github.com/arch-kiosk/arch-kiosk-office/assets/49291909/00e9e87e-ad54-4894-ba23-0c4c2dd1068f">

**Comment by urapadmin** [comment]
> We don't. I was playing to see if I could get more elements in there more coherently that way, but I cannot. <img alt="image" width="509" src="https://private-user-images.githubusercontent.com/49291909/316651574-26ab00bb-3099-4422-b987-c53e0c54dd5f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE0MDA0NzUsIm5iZiI6MTcxMTQwMDE3NSwicGF0aCI6Ii80OTI5MTkwOS8zMTY2NTE1NzQtMjZhYjAwYmItMzA5OS00NDIyLWI5ODctYzUzZTBjNTRkZDVmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI1VDIwNTYxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU1YWE4NjE4YjYwZGVjOWExZDNlMmYwZTdmYmI2YjM2MDRiOGMwYWFjYjFjMWE1MWJlMGYxYzRiODRlMDdkMmYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.up1rAmKZ7_1LBIOybktZ4j-HHJe0tiTYiM97vSO0gr8">

I don't see why the spider could not be upright in such a scenario, just as a variation. Perhaps one has a use case one day (thinking of the north arrow or a bookmark or who knows)

**Comment by urapadmin** [comment]
it appears friendlier to me than the ones we got with the black woodcut spider

**Comment by lbestock** [comment]
<img width="370" alt="image" src="https://github.com/arch-kiosk/arch-kiosk-office/assets/49291909/16a3fc1c-7e08-4d0c-8386-4b1df92f7b1f">

And friendlier than the lurking grey huge one behind the no longer quite so hippy sunrise. Those eyes on the horizon.

**Comment by lbestock** [comment]
It is very linear on its own, which does not work well in all our spaces.

**Comment by lbestock** [comment]
![image](https://github.com/arch-kiosk/arch-kiosk-office/assets/49291909/b4b8b934-fef0-484c-8627-ee15408fd32d)

But maybe the font is kookie enough that we can sometimes have the spider for the O and sometimes have him below and it is recognizably the same thing?

![image](https://github.com/arch-kiosk/arch-kiosk-office/assets/49291909/b7dca31e-c8dd-4005-82b3-6d843e56de5d)

**Comment by lbestock** [comment]
<img width="622" alt="image" src="https://github.com/arch-kiosk/arch-kiosk-office/assets/49291909/81ca42f8-a537-427c-bc78-663737abec94">

I will sit with it a bit. I don't hate it. I have tried moving the font back towards more standard and that sort of kills it for me, but we know I am prone to the wacky so I await other thoughts.

**Comment by lbestock** [comment]
The out of the box font.
<img width="506" alt="image" src="https://github.com/arch-kiosk/arch-kiosk-office/assets/49291909/a1a4f769-9e91-4e89-9013-543acbf90851">

**Comment by urapadmin** [comment]
> <img alt="image" width="370" src="https://private-user-images.githubusercontent.com/49291909/316654692-16a3fc1c-7e08-4d0c-8386-4b1df92f7b1f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE0MDI1ODUsIm5iZiI6MTcxMTQwMjI4NSwicGF0aCI6Ii80OTI5MTkwOS8zMTY2NTQ2OTItMTZhM2ZjMWMtN2UwOC00ZDBjLTgzODYtNGIxZGY5MmY3YjFmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI1VDIxMzEyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFkMjA4ZTUwOTYwMzVjMDdhNTZjNjcwMGQ0OWE2YmU5MzJmYjJjNjYxZDc5OGYzOWIxZDg4NzA3MmRkMWU1MjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.IRh-S-pYPwHpc8HW9QsXDXFluQyRv776YQ7_RUVhPJQ">
> 
> And friendlier than the lurking grey huge one behind the no longer quite so hippy sunrise. Those eyes on the horizon.

Ja, the o in front of him looks a bit obscene, too. 
I do like the bend touch to the font, though.

**Comment by urapadmin** [comment]
> ![image](https://private-user-images.githubusercontent.com/49291909/316656655-b4b8b934-fef0-484c-8627-ee15408fd32d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE0MDI1ODUsIm5iZiI6MTcxMTQwMjI4NSwicGF0aCI6Ii80OTI5MTkwOS8zMTY2NTY2NTUtYjRiOGI5MzQtZmVmMC00ODRjLTg2MjctZWUxNTQwOGZkMzJkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI1VDIxMzEyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI2NGRhOGFmYjI4MjE5MzYwMDI1M2RhOTQyNDRhY2NkNjczMTQ5OWEzYWU3NmIxNDE4Y2U0OGE2YzljNzliMTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ejYAKe2Jl-gg9muHVR4qlNC8D2crHAz7oqjzxWG33wI)
> 
> But maybe the font is kookie enough that we can sometimes have the spider for the O and sometimes have him below and it is recognizably the same thing?

in the logo the font suggest to me that it could be stylized more. there is a triangular pattern to the K's up there. But I am more of a geometric mind in such things.

**Comment by lbestock** [comment]
The triangle is what I liked - it looked trowelish to me :) But what do you mean stylized more? 

<img width="574" alt="image" src="https://github.com/arch-kiosk/arch-kiosk-office/assets/49291909/11dfeb3a-e93c-4ad7-9b87-f8707fa68f08">

**Comment by lbestock** [comment]
Hmpf the text warping is in Photoshop and not compatible with my making my own font modifications to the type in Illustrator.

**Comment by urapadmin** [comment]
I see it only in the small version where you use it in the recording app

**Comment by lbestock** [comment]
It is the exact same triangle K in the recording app as in nearly all of these others. The recording app is the same logo, I just took the spider out and put an O back in.

**Comment by lbestock** [comment]
<img width="434" alt="image" src="https://github.com/arch-kiosk/arch-kiosk-office/assets/49291909/59f4fa06-f4e7-4587-b1e3-5320b756ec88">

I figured out the warping in Illustrator.

**Comment by urapadmin** [comment]
ja, but it is smaller. And sometimes when things get smaller they get more abstract. Can't explain it with words.

**Comment by lbestock** [comment]
![image](https://github.com/arch-kiosk/arch-kiosk-office/assets/49291909/a1a064e2-20ea-4d25-9da2-7de88f7dde45)

I was going to quit. And I should have quit. And now Bob, who is purring like a maniac and biting my hands, will break the computer if I do not quit.

**Comment by urapadmin** [comment]
![image](https://github.com/arch-kiosk/arch-kiosk-office/assets/38838314/dcb383c1-7c38-46ba-b459-8620cca0a009)
That's the rythm I noticed.

**Comment by urapadmin** [comment]
I do like your accidental font more in the slightly bend version.

**Comment by lbestock** [comment]
> ![image](https://private-user-images.githubusercontent.com/38838314/316676234-dcb383c1-7c38-46ba-b459-8620cca0a009.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE0MDgwMTIsIm5iZiI6MTcxMTQwNzcxMiwicGF0aCI6Ii8zODgzODMxNC8zMTY2NzYyMzQtZGNiMzgzYzEtN2MzOC00NmJhLWI0NTktODYyMGNjYTBhMDA5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI1VDIzMDE1MlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ4M2Q2NzJjNGM0Mjg2YWNmMTdmYzk3MjdmNmMwNTNhOWUxYjZkMTM2OGJmYWYzN2QxMjViY2VlMGU0ZWZiYmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.wRe0TdBqk2VZep6T5WF0XmAZ3GJNGyBHofS8rjXzf9g) That's the rythm I noticed.

This gives it to me. I can work with this (tomorrow).

**Comment by lbestock** [comment]
<img width="545" alt="image" src="https://github.com/arch-kiosk/arch-kiosk-office/assets/49291909/cc9c2ce3-6366-4ab7-ac3c-12c61314f55d">

A more extreme version with the angle more rigidly applied.

**Comment by lbestock** [comment]
<img width="676" alt="image" src="https://github.com/arch-kiosk/arch-kiosk-office/assets/49291909/97a27ce2-6c04-4394-befa-af1ec8e64d95">

Angle as guiding principle but made a little bit more regular because I caught that the letters were not the same size when trying to bend it a little.

**Comment by lbestock** [comment]
<img width="764" alt="image" src="https://github.com/arch-kiosk/arch-kiosk-office/assets/49291909/cb006cf8-168a-4e07-a5e7-0a6351b6a836">

Does not read well small with the spider in the middle. It's better with him out.

<img width="653" alt="image" src="https://github.com/arch-kiosk/arch-kiosk-office/assets/49291909/448d1173-e762-4106-b79c-165e8803fc90">

**Comment by urapadmin** [comment]
So far I think this is what I like best:

![image](https://github.com/arch-kiosk/arch-kiosk-office/assets/38838314/52a11873-6986-4742-b289-83521cd445f6)

**Comment by lbestock** [comment]
<img width="343" alt="image" src="https://github.com/arch-kiosk/arch-kiosk-office/assets/49291909/ff04aded-1442-49d1-8b28-9b5d7e659b86">

I cannot get the equivalent warping in Illustrator as I had in Photoshop. At least, the same tool does not do the same thing when it is not type and I don't like it as well. It's just sort of randomly bent, not arced along a path. Argh.

**Comment by lbestock** [comment]
> So far I think this is what I like best:
> 
> ![image](https://private-user-images.githubusercontent.com/38838314/316925268-52a11873-6986-4742-b289-83521cd445f6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE0NjY3NDAsIm5iZiI6MTcxMTQ2NjQ0MCwicGF0aCI6Ii8zODgzODMxNC8zMTY5MjUyNjgtNTJhMTE4NzMtNjk4Ni00NzQyLWIyODktODM1MjFjZDQ0NWY2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI2VDE1MjA0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIwMzIxMzljMjUyMjczMThhM2YyYjA3NTc2ZGUyZTM5YWZlMDFlOTEwNTQ1YmJmMTUwOTlmNDU5MDRlZjg0ZDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.f_tUOUhJxywDlasxMAfo4vYXBY8ltu0swDwuceWCPeQ)

Me too. I am trying to get there with a vector and not succeeding.

**Comment by urapadmin** [comment]
tutorial! Illustrator can do that.

**Comment by lbestock** [comment]
Can it? The bloody "warp" tool, which looks like it should work just like it does in Photoshop, does something different.

**Comment by urapadmin** [comment]
there is aligning text along a path, e.g. illustrator is like Photoshop: You really need to know it. It can do everything.

**Comment by lbestock** [comment]
It isn't text any longer is the problem.

**Comment by urapadmin** [comment]
then start again, align the text, then turn it into a path and then you can make your changes to single nodes. But really, I am the wrong person to ask, I never got into Illustrator. Even less than into photoshop. I only know that it can do everything in the hands of people who master it. Hence the tutorial. Or Simon?

**Comment by lbestock** [comment]
The Ks have to be the same K before the warping is applied - they need to start the same shape and end a different one or it won't work. I'm searching for tutorials. They all seem to be by Australians.

**Comment by lbestock** [comment]
It is interesting and I would like working on it if I weren't feeling so super stressed about time.

**Comment by urapadmin** [comment]
You can also do it in Photoshop for ARCE first.

**Comment by lbestock** [comment]
<img width="713" alt="image" src="https://github.com/arch-kiosk/arch-kiosk-office/assets/49291909/6d2821da-b2e4-4a2b-90b5-0ebfb1569417">
Now the spider is smooshed.

**Comment by lbestock** [comment]
I don't even remember what I did the first time anymore. Argh.

**Comment by urapadmin** [comment]
argl. You must have had the spider in it's own layer, covering the O

**Comment by urapadmin** [comment]
overweight spider. Apt.

**Comment by urapadmin** [comment]
looks a but like Bob

**Comment by lbestock** [comment]
I still don't know how I did it, but I know I did it in Illustrator, not Photoshop as I thought, and I have the above file as a vector. Thank god.

**Comment by lbestock** [comment]
<img width="232" alt="image" src="https://github.com/arch-kiosk/arch-kiosk-office/assets/49291909/1502395d-4e8d-414a-98ef-ea6b545a32c9">

And I can manipulate it to increase or decrease the arc, and put other text.

**Comment by lbestock** [comment]
<img width="282" alt="image" src="https://github.com/arch-kiosk/arch-kiosk-office/assets/49291909/36b2f206-b8e9-4476-abb2-8538fe4822d6">

**Comment by urapadmin** [comment]
Thank god. But I think I like it better if the bending is limited to the logo itself and the text stays normal. 
So looks like you have it for ARCE?

**Comment by lbestock** [comment]
<img width="218" alt="image" src="https://github.com/arch-kiosk/arch-kiosk-office/assets/49291909/c3a6f430-8f91-4929-8ef8-0eaf82756675">

Vector. With comprehension of what I am doing. We can zoom and adjust together the tiny details, but we are good for ARCE and beyond.

**Comment by lbestock** [comment]
<img width="368" alt="image" src="https://github.com/arch-kiosk/arch-kiosk-office/assets/49291909/5fa47f16-a1a8-4cd1-8fd7-4402ba407592">

2% more warp

**Comment by lbestock** [comment]
<img width="420" alt="image" src="https://github.com/arch-kiosk/arch-kiosk-office/assets/49291909/5d93b825-15f0-4be4-b1cd-e68d4ef7ac0c">

Now 2% more warped.

**Comment by urapadmin** [comment]
I am not sure I like that font. Can you try the monospace font instead?

**Comment by urapadmin** [comment]
I think it is too tall or so. The proportions with the logo aren't great.

**Comment by lbestock** [comment]
It is the same font as the top part. Yes, we can play with that, but such tinkering really is fast and better done via zoom and screen share.

**Comment by lbestock** [comment]
<img width="414" alt="image" src="https://github.com/arch-kiosk/arch-kiosk-office/assets/49291909/e00ebb67-0331-4cf9-bb33-8dccb8774a7a">

The letterspacing does have to be so much wider on the bottom line with this tagline. Regardless of font. Hm.

**Comment by urapadmin** [comment]
but you have to make dinner and then I need to go to bedOn 26. Mar 2024, at 23:51, lbestock ***@***.***> wrote:﻿
It is the same font as the top part. Yes, we can play with that, but such tinkering really is fast and better done via zoom and screen share.

**Comment by lbestock** [comment]
I didn't mean right now (though I am clearly not letting it go). I'm at the kitchen table. Multitasking.

**Comment by urapadmin** [comment]
too typewritery. But a not so tall font works better in my view. Perhaps one that has wider characters.

does it really have to be left and right aligned? 

You could also try the opposite and make it all less wide and place the qr code

**Comment by lbestock** [comment]
<img width="292" alt="image" src="https://github.com/arch-kiosk/arch-kiosk-office/assets/49291909/dc2f750b-0c26-44da-aa8a-5dbe5059ad5b">

We will do it together. So many things are possible if one learns how to do them. Which, I am not there with Illustrator. But for this particular task with this particular logo, we can futz together.

**Comment by lbestock** [comment]
<img width="434" alt="image" src="https://github.com/arch-kiosk/arch-kiosk-office/assets/49291909/90894206-5aa3-47a7-82ef-4cc57bf89297">

Endlessly variable.

**Comment by urapadmin** [comment]
Record. Research. Share. ?

**Comment by lbestock** [comment]
<img width="312" alt="image" src="https://github.com/arch-kiosk/arch-kiosk-office/assets/49291909/85b0b1ac-743e-4678-aeda-7becf2e9c5fe">

**Comment by lbestock** [comment]
<img width="727" alt="image" src="https://github.com/arch-kiosk/arch-kiosk-office/assets/49291909/f9ca7bba-0e1e-4dfc-89b4-53de6a37de7a">

**Comment by lbestock** [comment]
<img width="805" alt="image" src="https://github.com/arch-kiosk/arch-kiosk-office/assets/49291909/fe2e772e-e2d5-47b7-8f7c-e1922ecbe7ee">

**Comment by urapadmin** [comment]
If three words, then they need to be in one line. So much is clear.

This is about Kiosk, not about excavation. You don't even need to dig to use Kiosk (see MADP, legacy data etc.). So you can keep your cool word and use it somewhere even in combination with Kiosk but I don't think it is right as one of the three words that describe what Kiosk is for.

Still don't like that font.

But I think the logo works fine on the North arrow.

**Comment by urapadmin** [comment]
> <img alt="image" width="434" src="https://private-user-images.githubusercontent.com/49291909/317102737-90894206-5aa3-47a7-82ef-4cc57bf89297.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE1NjI3NTksIm5iZiI6MTcxMTU2MjQ1OSwicGF0aCI6Ii80OTI5MTkwOS8zMTcxMDI3MzctOTA4OTQyMDYtNWFhMy00N2E3LTgyZWYtNGNjNTdiZjg5Mjk3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI3VDE4MDA1OVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTdjMGIwMWFiYmY1MDg5NTI3MjE1YzU2NWI3N2UwZTQ0MDI5ZjBmZDZhYThlYWU2OTk5N2ExZTcyNGU0MTY3OGImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Q1WQTwBUt0O30DoDbZDFtn3pQvOW5fRtan8h4LijEiU">
> 
> Endlessly variable.

I forgot to say that I still don't dislike the rectangular combination with the qr code. And here we could go two lines with Digital Field Recording without even having to do the spacing. Just have a Flatterrand (good word) on the right.

**Comment by lbestock** [comment]
<img width="539" alt="image" src="https://github.com/arch-kiosk/arch-kiosk-office/assets/49291909/d0d81225-da15-4944-9b70-165d114d0ce4">

Old people go old school.
