### ISSUE TITLE
director's view: weird modification date

### ISSUE THREAD

**Issue by luizaogs** [arch-kiosk/arch-kiosk-office#2615]
Saw this while testing #2605 and it didn't seem related (though what do I know). I only changed things in LA today but there are two or so changes attributed to ADMIN in unit CA today as well. Did @lbestock do these? Otherwise I'm not sure why they are being marked in the director's view. 

I don't see anything for Laurel's workstation in PVD (in synch and dock events) so thought I would check...

**Comment by urapadmin** [comment]
I used your workstation today and I think I changed something in an interpretation saying "no clue" or so.

**Comment by luizaogs** [comment]
Ah. So this is fine, I suppose.
