### ISSUE TITLE
Kiosk timing out nearly instantly in Q&V with FTS

### ISSUE THREAD

**Issue by lbestock** [arch-kiosk/arch-kiosk-office#2616]
I keep having trouble staying logged in in Q&V. I can get there, and perform a search, so it seems like it is not the whole server down. But I get this:
<img width="1470" alt="image" src="https://github.com/arch-kiosk/arch-kiosk-office/assets/49291909/1d8485fe-23cb-4166-827e-dbf8421e3b15">

Did I type too quickly? It keeps happening. And then I can't get to the stuff that came up in results for my FTS.

But I am also really tired and I need to feed the cats and make the bed. So I would want to be more certain this is a pattern before you invest too much time in it.

**Comment by luizaogs** [comment]
If not down, it is currently very slow. Trying to test stuff and my dock won't prepare. It's processing forever.

**Comment by luizaogs** [comment]
Hm and now it stopped preparing altogether but doesn't even give me an error, so something is up (if not related to Laurel's original ticket, sorry - I can open a new one).

**Comment by urapadmin** [comment]
At least Luiza's issue is solved. Beset wasn't all that well. I hope that solves the Q&V issue, too.
