### ISSUE TITLE
Q&V: library upgrades

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#2625]
Q&V needs a new test (trying all you can imagine) due to massive upgrades of the underlying libraries I am using.

**Comment by urapadmin** [comment]
### kiosk 1.5.29
- for reference's sake: I upgraded vite, vaadin-grid, lit, vitest, typescript and the related libraries. So, more or less all of them, to new major (so called breaking) versions. And breaking it did. So please click everywhere on everything.

**Comment by luizaogs** [comment]
I've clicked on everything I can imagine, driving myself slightly insane in the process, and haven't run into any issues.

**Comment by urapadmin** [comment]
I do not want Kiosk to be a well of insanity for anybody else but me (inevitable). Good, that must do.
