### ISSUE TITLE
FTS / Q&V: Jump to image in image list

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#2627]
Coming out of #2613 

When clicking on a match in FTS that is an image description, the jump should not only go to the image list but also to the particular images (or at least make sure that it is in view).

**Comment by lbestock** [comment]
Yup - please.

**Comment by urapadmin** [comment]
### Kiosk 1.5.38.1
- the image should be moved into view (it will not be highlighted in any way)
