### ISSUE TITLE
q&v: typo in query

### ISSUE THREAD

**Issue by luizaogs** [arch-kiosk/arch-kiosk-office#2629]
Just because this is being shown at ARCE I expect ... maybe we want to change "unit" to "units" in this query and its description? 

<img width="280" alt="Screenshot 2024-04-06 at 9 08 00 AM" src="https://github.com/arch-kiosk/arch-kiosk-office/assets/67970402/780ad23b-8bc7-4ef3-bf75-1b77db5349c3">

**Comment by urapadmin** [comment]
That's not just a typo. It's more complicated:
![image](https://github.com/arch-kiosk/arch-kiosk-office/assets/38838314/9281a5bf-81fc-4f1f-9477-384050b6c98f)

But even though, it should be solvable.

**Comment by urapadmin** [comment]
hm. Have I solved this? I am not sure.

**Comment by lbestock** [comment]
You have not solved this as of 1.5.38. It's slightly annoying but not a super high priority.

**Comment by urapadmin** [comment]
### kiosk 1.5.38.1
- not technically a change in Kiosk proper. Only the view definition needs a change (we can test the new view installer now: #2658).
- BUT it also depends on the project's Kiosk configuration. This is using the "glossary" of the project. Nobody but I can configure that currently. I have set the defaults to "unit=units, locus=loci" etc. for Kiosk's default terminology.

**Comment by luizaogs** [comment]
Looks good in PVD (where we use trenches).

But do you want me to be more annoying? This is the only query that starts with a lowercase "what". Should we make it "What" to match the others?

**Comment by urapadmin** [comment]
do you feel my hands around your neck?

**Comment by urapadmin** [comment]
No, it's a good test for updating a query in #2658

**Comment by luizaogs** [comment]
You said you liked my typos...

**Comment by urapadmin** [comment]
:brain can't remember that

**Comment by luizaogs** [comment]
At ARCE. I remember it very clearly.

**Comment by urapadmin** [comment]
must have been after Donna the barkeeper forced that double Martini on me

**Comment by urapadmin** [comment]
let's move over to #2658

**Comment by luizaogs** [comment]
> must have been after Donna the barkeeper forced that double Martini on me

Don't lie to yourself!
