### ISSUE TITLE
kiosk: MCP down?

### ISSUE THREAD

**Issue by luizaogs** [arch-kiosk/arch-kiosk-office#2630]
Or at least, I am trying to export the MKAP data to Excel and the dock is processing forever...

**Comment by luizaogs** [comment]
Kidding! It just took forever.

**Comment by urapadmin** [comment]
hm. It shouldn't really. Unless somebody else was using the MKAP Kiosk and prepared a dock or so. But you would see that.

**Comment by urapadmin** [comment]
as for the export itself. I am surprised you use it. What's the goal? I am just curious.

**Comment by luizaogs** [comment]
Oh I don’t use it - Kelly wanted it. As for what, I don’t know. I will probably find out tomorrow when I zoom with her to show her how to use Kiosk again.

**Comment by urapadmin** [comment]
ah okay. That Excel export is about everything and it is of limited use unless one knows about the relations and all. 
Saying this because we have a few much better alternatives: Except reports and queries, and I am always happy to make them (we are still so low on real examples).
