### ISSUE TITLE
q&V: enter key not working if I pick an identifier from a drop-down

### ISSUE THREAD

**Issue by luizaogs** [arch-kiosk/arch-kiosk-office#2634]
Related to #2598. 

If I pick an identifier from the drop-down when running a query (for instance, MKAP for the "what unit exist per site" query) the enter key does not work and I need to click on the rocket button to get my results.

**Comment by urapadmin** [comment]
not as related as you think. The full text search is a very specific UI while the normal queries have a UI that serves all kinds of queries. As long as such a query relies only on one filter field, one would expect enter to start the query. It is not that straight forward if there is more than one filter field (in which case ENTER sometimes is supposed to move to the next field). 
I have to take that into consideration. But by default, I think the rocket button should indeed be fired on enter.

**Comment by urapadmin** [comment]
### Kiosk 1.5.29.2
- not trivial but implemented. Buttons can have a default for CANCEL or ENTER now. In this case ENTER defaults to the rocket button.
- because too many tickets on too little time: This only works currently for list boxes.
