### ISSUE TITLE
q&v: graphs?

### ISSUE THREAD

**Issue by luizaogs** [arch-kiosk/arch-kiosk-office#2636]
I don't think we need it right now for MKAP, but in talking to Kelly it struck me that some of the queries might benefit from graphic representations like we have for ceramics in the recording system. I remember finding this really cool in the Amara West British Museum database (I forget what it's called - the one Neal Spencer worked with) and I wonder if this is something that has been discussed for Kiosk and Q&V?

**Comment by urapadmin** [comment]
I have discussed it in my mind and it is imaginable. But I would want more concrete examples :o)

**Comment by luizaogs** [comment]
Ah this was just a general idea. When I have more concrete examples I’ll add them here.

**Comment by luizaogs** [comment]
Ok, so for instance, we are including pie charts for materials found in each unit (so the results of that query). It would be cool to be able to generate the pie graph in Kiosk itself, rather than a table of results.

This is the table Kelly made based on the results, and now this will be made into a graph:

<img width="654" alt="Screenshot 2024-04-07 at 2 05 59 PM" src="https://github.com/arch-kiosk/arch-kiosk-office/assets/67970402/fcedb950-fec7-4e10-9d18-90e92f3dbd7c">

**Comment by urapadmin** [comment]
Ja. But I also like that Kiosk data is being used in Excel. So did she generate that table from he exported excel data? 
That could be easily an Excel report. 

It also reminds me that a quick export of query results in Q&V would make sense.

**Comment by luizaogs** [comment]
I think she made this manually in Word, to be honest. I told her that the Excel export would have a lot of extraneous information and encouraged her to use Q&V itself, so I think she just ran that query and then took the numbers and added them to this table.

I think export of query results would be very helpful.

**Comment by lbestock** [comment]
If you want my three cents (inflation): this would be both cool and, clearly, usefull/used so while not as high priority as demo stuff, it's not the bottom of the list.

**Comment by lbestock** [comment]
WHOA. This is amazing. (It's also blazingly fast, which surprised me a bit somehow.)
The ability to uncheck things and thus basically rewrite/narrow the query while looking at it is extremely useful - that is the kind of thinking I actually do visually and it's easier for me to adjust such a thing while in it than write language of a query to result in it.
I imagine you already have thought of putting that same ability in the bar chart.

BONE is not showing up in the bar chart right now.

**Comment by urapadmin** [comment]
I close this and create two new tickets:
- #2687 
- #2686
