### ISSUE TITLE
Q&V: Export Query Results to Excel

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#2637]
Just exporting the table to an Excel file would make many excel reports superfluous, I suppose.

**Comment by urapadmin** [comment]
- coming out of #2636

**Comment by urapadmin** [comment]
this would be a good feature to show on ARCE, either

**Comment by lbestock** [comment]
> this would be a good feature to show on ARCE.

Yup, and like #2636 not by any means the last thing to think about.

**Comment by urapadmin** [comment]
### Kiosk 1.5.30
- There is a first button now in the sidebar left of the result rows. 
- it allows you to download the results either as XLS or CSV file
- or copy them to the clipboard in a tab separated format that can be pasted straight into an open Excel file and presumably into a google sheet (I have not tested that).
- A nuance: "CSV" does not render the field contents the way you see them in the result grid. It leaves them raw. That has the effect that e.g. dates are not turned into the latin date format. If you import such a CSV file with Excel dates are recognized as dates and automatically formatted the right way by Excel. That would not be the case otherwise. Currently, when exporting to XLS (or paste to clipboard), the cells get rendered exactly the way they appear in the grid. I am not sure what is better.

**Comment by luizaogs** [comment]
I got this for the Excel download: 

<img width="259" alt="Screenshot 2024-04-13 at 6 44 22 PM" src="https://github.com/arch-kiosk/arch-kiosk-office/assets/67970402/af06fe94-7aed-4311-8441-c47720db7dd1">

**Comment by luizaogs** [comment]
CSV worked.

**Comment by luizaogs** [comment]
Copying to clipboard worked for both Excel and Google sheets.

**Comment by urapadmin** [comment]
I reckon if you rename the data.xlsx to data.xls it works, right?

**Comment by luizaogs** [comment]
It does. Is that ok then? Or should it be downloading as data.xls in the first place?

**Comment by urapadmin** [comment]
### Kiosk 1.5.31
- it exports "xls" now.
