### ISSUE TITLE
ARCE: video loop

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#2639]
@lbestock How and what? As far as I have seen there is no projector that we could rent. 

- So if we want our own video loop, we'd need a projector (and presumably a screen to project onto?).

- Would about the logo in their video loop?

**Comment by urapadmin** [comment]
a few projectors I found:
- 600ANSI Lumen. Not sure that's enough: https://www.amazon.com/Officially-VOPLLS-Projector-Bluetooth-Keystone/dp/B0CLG8L3GB/ref=pd_ci_mcx_pspc_dp_d_2_t_5?pd_rd_w=riYqH&content-id=amzn1.sym.568f3b6b-5aad-4bfd-98ee-d827f03151e4&pf_rd_p=568f3b6b-5aad-4bfd-98ee-d827f03151e4&pf_rd_r=91YCBEPMM2RSA9H92PGR&pd_rd_wg=5yOql&pd_rd_r=e03ba9b6-48e3-448a-a21b-a91218e83a25&pd_rd_i=B0CLG8L3GB&th=1
- very small and brighter: https://www.amazon.com/Officially-VOPLLS-Projector-Bluetooth-Keystone/dp/B0CLG8L3GB/ref=pd_ci_mcx_pspc_dp_d_2_t_5?pd_rd_w=riYqH&content-id=amzn1.sym.568f3b6b-5aad-4bfd-98ee-d827f03151e4&pf_rd_p=568f3b6b-5aad-4bfd-98ee-d827f03151e4&pf_rd_r=91YCBEPMM2RSA9H92PGR&pd_rd_wg=5yOql&pd_rd_r=e03ba9b6-48e3-448a-a21b-a91218e83a25&pd_rd_i=B0CLG8L3GB&th=1
- 50" table top projector screen: https://www.projectorscreen.com/grandview-pt-b50-4-3-wm4-ab-u-work-table-top-screens-50-30x40-video-4-3-wm4-black-case.html
-

**Comment by urapadmin** [comment]
I can't find a projector screen that would possibly fit in a suitcase. They are all too wide.
E.g. - 50" table top projector screen: https://www.projectorscreen.com/grandview-pt-b50-4-3-wm4-ab-u-work-table-top-screens-50-30x40-video-4-3-wm4-black-case.html. In that case less brightness might not be so important.

**Comment by urapadmin** [comment]
this might work: https://www.amazon.com/dp/B0C6WZKK21?ref=emc_s_m_5_i_atc

this definitely fits: https://www.amazon.com/Projector-Screen-Stand-Portable-Projection/dp/B07YFZXX8F/ref=pd_ci_mcx_pspc_dp_d_2_t_4?pd_rd_w=aMbtn&content-id=amzn1.sym.568f3b6b-5aad-4bfd-98ee-d827f03151e4&pf_rd_p=568f3b6b-5aad-4bfd-98ee-d827f03151e4&pf_rd_r=8HYGNCP5WYFRFYX8SHHR&pd_rd_wg=n9MJ5&pd_rd_r=578bb20a-b389-46cd-86bd-b5691fcba6d0&pd_rd_i=B07YFZXX8F

**Comment by urapadmin** [comment]
here is a backdrop stand that would fit, so maybe we could just hang a white PVC backdrop? 

https://www.amazon.com/Aureday-Adjustable-Horizontal-Photography-Decoration/dp/B0C1GRFJD4/ref=sr_1_10?crid=3BQVXLS3NYIQN&dib=eyJ2IjoiMSJ9.pBt5vDzmLosRAXgPRXlhHqnaw9sKMsljPtfYCJvfDor59-ZM5gFsNIWi9rX9fTIAmv0kB4w6NgkLiWbM7HP4WcC62O5Ca1UQAndQsu7Y7r-_romiRSsxBs7ZpZiUcXqIt4yYg15d_xREvlnQ6AO9_6kNy7_LW2ezlTbXIY3vGRaRtBp5oGN5om68jX7NT1t1IHwKmYrp39aytqxgIdrp0C1dJniIMmu5-GBzk2kXXk0CT-rC_zbfxy72WvhZdkw80eEDC4XriK-7LasW-McRKrLV6xt2PdYA5UU7dX8gORM.fudGJUUnuOyDvqBW-BGLEcfQZ06CIyT80J7OwUTW6YE&dib_tag=se&keywords=backdrop+stand+travel+photography&qid=1712786564&s=electronics&sprefix=backdrop+stand+travel+photography%2Celectronics%2C91&sr=1-10

The PVC backdrop:
https://www.amazon.com/Selens-100X200CM-40X80INCH-Photography-Background/dp/B01ESIYKMS/ref=sr_1_27?crid=30330F5THUZA5&dib=eyJ2IjoiMSJ9.m2EdYZEYjVRY8mlFXXibmAwfTW7N5e3cRoRVvnher0HQwX9D9aBZaGiIHP-vzzaLu3qXoYbnOS3CuY_Kc13MxflTvNiG1pwkcu0GoNVjASidSOdRHYX_SvTI3YAVXYn0Qske8N0OEr6Ty7YCAHy6WJW00iywhVfyzQrB4MqhxyMjVtZO8-XWFbpkez5LR0-yAmDweY-jecUbQebBVpQfcRMsAcxjzSPu7LyZ-I0H4w62kQq823CEXud2XW83qOwNJcmE62owLzc2j5OOlzNdbPq6UeambGiuyETO2MPYd1c.EUBnEcLubG0PXbyNdhrg52eSEHD8ts1YSboy3mimm4M&dib_tag=se&keywords=pvc%2Bwhite%2Bblack%2Bbackdrop&qid=1712787123&s=electronics&sprefix=pvc%2Bwhite%2Bblack%2Bbackdrop%2Celectronics%2C100&sr=1-27&th=1

**Comment by urapadmin** [comment]
another one that might work:
https://www.amazon.com/Projector-Screen-84-Portable-Projection/dp/B0C6WZKK21

**Comment by urapadmin** [comment]
miroir projector:
https://www.amazon.com/dp/B07KMK1DCS?ref=emc_s_m_5_i_atc&th=1

**Comment by urapadmin** [comment]
Optoma projector: https://www.amazon.com/Optoma-ML750-Portable-Projector-Enabled/dp/B00GGGQHG8/ref=sr_1_2?crid=FNMO7S9SV9D3&dib=eyJ2IjoiMSJ9.sb6t-WvvuET_1xcrVyTY-u5b35P5nynU8JsfjL7qMeXHVa8JFjHdNE9Y5L8OALjktLKogJcvQ8ibPtXaqBQJ8HtimRpoFJaodapzz1ldD_2VrA0H5eGDIFquTykNX756jtO7gWstg2F3AoITvtUELZysMkszHc0tj0xZx9OY91fdii1xK6W3R0tNN8JnA4jXk2V-_Cj9hOHbbmsqucFG8ALNCqCaTlNMmKbZ9kEE61pTtrCdDzDk-OhHwsKNpWXauBBs8NM7B5aDat_Ap3Bm14m4L1Aqg7qKRn_tOjB1SjM.hLbISRmdvSFwlLBAa_SAzzAWuhkLHOGPglLLSdNQWvc&dib_tag=se&keywords=travel%2Bprojector%2B750%2Blumen&qid=1712793184&sprefix=travel%2Bprojector%2B750%2Blumen%2Caps%2C106&sr=8-2&th=1

**Comment by lbestock** [comment]
Projector issues potentially solved, this needs now to move into deciding what to PUT on the loop. This is a priority (but since we will not have time to make new videos, also not a "must be done now in Providence" priority.) I wish we had videos from the field projects. Greatest hits from the tutorials would seem a good start, maybe with CC if that's possible since we'll be playing this without sound. We want to see a lot of screens on the screen but enough people, too, no? People currently are just @urapadmin and @lbestock.

**Comment by urapadmin** [comment]
Honestly, I am not thinking of a loop with videos. I don't see when we would find the time for stitching together video feed. I was only thinking of Powerpoint.
