### ISSUE TITLE
ARCE: equipment to bring

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#2640]
- [ ] Pack a bunch of iPads (and Apple pens?) to give as loaners during the conference so interested people can spend a few hours making data while bored in talks (they'll need to leave a passport or some such to check one out).
- [ ] local server, router etc.
- [ ] projector and screen? see #2639 
- [ ] extension cable 
- [ ] cable binders
- [ ] multi-purpose purpose tape
- [ ] what local server?

**Comment by luizaogs** [comment]
Do you want me to take my iPad?

**Comment by urapadmin** [comment]
We are bringing the Institute's iPads, but if your luggage allows for it I think it would not hurt to have an extra.

**Comment by luizaogs** [comment]
Ok. Shouldn’t be a problem.
