### ISSUE TITLE
Q&V: jump to matching record when new View is loaded

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#2644]
> A few times when I have clicked on the identifier in the returned hits list when it is a narrative I have been flown to the top of the unit information, not to the proper narrative. All these narratives I could subsequently get to by scrolling up again and clicking again, but it was a little disconcerting. And now: I think I am finding a pattern, in trying to force it. If the unit has not previously been opened below, then clicking on the identifier just opens the unit, it doesn't fly to the proper narrative. If that unit was open already, then clicking the identifier takes you straight to the right narrative. The unit can be open from a previous search, even, all that seems to matter is that it be previously open.

_Originally posted by @lbestock in https://github.com/arch-kiosk/arch-kiosk-office/issues/2504#issuecomment-2048530738_

**Comment by lbestock** [comment]
This is higher priority.

**Comment by urapadmin** [comment]
sound like a timing problem. Not sure I can do much about it right now. It would need a different approach, I guess.

**Comment by urapadmin** [comment]
confirmed. Clear timing problem. Does not occur on local servers as they deliver the view fast enough.

**Comment by urapadmin** [comment]
### Kiosk 1.5.38.1
- I tried to get around the timing issue. But it needs testing of both cases: going to something in an already existing view and one that needs to be loaded first. Test on Beset, but also test locally!

**Comment by luizaogs** [comment]
So I think this is kinda working? For a new view, it went right to the narrative. For something that is already open, though, I'm currently getting it to scroll OVER the right narrative when I click on a search result. Which means that the narrative isn't immediately visible, only once one scrolls up slightly. Not sure if you can do anything about that...

**Comment by urapadmin** [comment]
that is a bit surprising that it behaves differently. Is the right narrative totally out of view or is it just partly in view?

**Comment by luizaogs** [comment]
The two I tested were just one line, so they were totally out of view. That might not be the case if it is a longer narrative, however.

**Comment by urapadmin** [comment]
hm. What was your search and which ones did you click on?

**Comment by luizaogs** [comment]
Uhh let me try to remember...

**Comment by luizaogs** [comment]
Ok. Open LA and have that open. Then search for "office" in FTS and click on the LA result at the bottom. It's the first narrative in the unit, but view scrolls just below it after you click on that result.

**Comment by urapadmin** [comment]
okay, I see it. But I also see it when the view isn't already open. So the difference between the two does not occur here. And I think it has something to do with the toolbar covering it or so.

**Comment by urapadmin** [comment]
I'll look into that again. Perhaps I can give it a bit of an offset.

**Comment by urapadmin** [comment]
### Kiosk 1.5.38.3
- As I suspected: The toolbar is covering the element that is moved into view. There isn't really anything I can do here except a horrible hack: After the element was moved into view I scroll programmatically by -60 pixels. It might help, it just hurts.

**Comment by urapadmin** [comment]
Nope, that did not work anymore when the Q&V app runs within the Kiosk Framework. I have to think of something else.

**Comment by urapadmin** [comment]
### Kiosk 1.5.38.3 / ui-component 0.5.11
- The toolbar is covering the element that is moved into view. While my first hack did not work out, I have a new one in place now. Now it seems to work and I am waiting of the side effects.

**Comment by luizaogs** [comment]
> Ok. Open LA and have that open. Then search for "office" in FTS and click on the LA result at the bottom. It's the first narrative in the unit, but view scrolls just below it after you click on that result.

Followed the same steps that I mentioned here and no scrolling is happening at all.

**Comment by luizaogs** [comment]
Actually, that's not true - every time I click on LA things scroll up slightly. But I am nowhere close to the narrative I want.

**Comment by urapadmin** [comment]
So now it is not only that it misses it by about the height of the toolbar, it almost does not scroll there at all?

**Comment by luizaogs** [comment]
It doesn't scroll to the view, it just kinda moves around in the FTS results.

**Comment by urapadmin** [comment]
that is so weird. Chrome on Mac?

**Comment by luizaogs** [comment]
Yes.

**Comment by urapadmin** [comment]
Let's make sure the cache isn't in the way. Here is a super reliable way to do that: You go to the developer tools (It is ctrl+shift + I on Windows or in Chrome's menu it is advanced tools (or so, I have only a German Chrome here) -> Developer Tools. 
Then you get this:
![image](https://github.com/arch-kiosk/arch-kiosk-office/assets/38838314/64bc1310-5673-47ef-aff0-dd90e3a4ca1d)

In the "Network" tab you have a checkbox "Disable Cache". And when that is set and you reload Q&V you can be absolutely sure that nothing old was being used. Normally clearing the cache should do that, too, but Chrome has lost my trust long ago on that front.

**Comment by urapadmin** [comment]
could you please send me a screenshot of your whole browser window if it remains?

**Comment by luizaogs** [comment]
Yes, same issue. Which tab of the developer tools do you want in the screenshot?

**Comment by urapadmin** [comment]
oh, not the developer tools, those you can close now that we know the cache was emptied. 

I need to see the browser after you clicked on the LA. I want an idea of the proportions over there. Mac users tend to use their screen space differently.

**Comment by luizaogs** [comment]
Oh.

<img width="1512" alt="Screenshot 2024-05-25 at 9 37 29 AM" src="https://github.com/arch-kiosk/arch-kiosk-office/assets/67970402/be49f94c-38fb-414b-9c27-45bb0182e842">

**Comment by urapadmin** [comment]
ja, absolutely nothing happened there. hm.

**Comment by urapadmin** [comment]
ja. I can reproduce that reliably on our Mac. Happens both in Safari and Chrome.
That'll need some digging ...

**Comment by urapadmin** [comment]
### Kiosk 1.5.38.4
this is harder than you'd think. 
So on MacOS and iOS all Browsers behave differently than on Windows. All I could come up with here is using a timer to make sure that the scrolling into view happens first and then another scroll by -60px after that. It seems to have the required effect right now but I would not be surprised if this comes up again in the future.

**Comment by urapadmin** [comment]
it is also clear to me that marking the search result in the view will be inevitable in the end. It just too hard to spot the right narrative and the Browser search does not really help all that much depending on the Browser.

**Comment by luizaogs** [comment]
Working.
