### ISSUE TITLE
file maker recording: FA-021 does not show a Harris Matrix

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#2647]
and that's not the only locus that doesn't. FA-005 doesn't, either although it has quite a few relations.
There is something going wrong.

**Comment by urapadmin** [comment]
### recording app 15.15.4
- this is fixed now. If a reverse relation is missing the relation gets dropped with a message that describes the problem

**Comment by luizaogs** [comment]
Both are now rendering but I don't see error messages of any sort. Should I?

**Comment by urapadmin** [comment]
yes, I should have thought so. Something about a missing reverse relation. If I remember correctly, FA-021 seals FA-040 but FA-040 is not sealed by FA-021.

**Comment by urapadmin** [comment]
too late to look into it again, today. I'll double-check tomorrow.

**Comment by urapadmin** [comment]
the data in FA-021 was fixed on the demo server, so this is the correct result.
