### ISSUE TITLE
recording system: request ability for admin to delete locus types

### ISSUE THREAD

**Issue by lbestock** [arch-kiosk/arch-kiosk-office#2653]
Configuring ELRI and there are a lot of old locus types floating around. They want a much more restricted list. I would like to be able to delete some of these for this project as an admin.

**Comment by urapadmin** [comment]
### recording app 16.2.4
- there should be a red trash can button if you are admin (and not when you are not)
- it'll ask if you really want to do that and then deletes the locus type
- if the locus type is still in use it will ask you again but still give you the option to delete the type
