### ISSUE TITLE
add a field "area" on the trench tab in FM

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#2654]
what is it supposed to be? Just a text field? A valuelist? A self-populating dropdown?

**Comment by urapadmin** [comment]
### recording 15.16 and Kiosk > 23.04.2024 13:30
- there should be a field if the new config key "label_sector" has a value. The field should have that label.
- ELRI wants to call that an "area"

**Comment by lbestock** [comment]
This is working and is dynamic and is good. I won't close it however because I think the field should also be present in the initial unit creation.

**Comment by urapadmin** [comment]
there is virtually no space on that layout
