### ISSUE TITLE
recording: "ceramic building materials" does not fit. 

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#2655]
Although I changed it to "ceramic build. materials" it still does not fit in the list of collected materials. 
I might change the font size in the end

**Comment by urapadmin** [comment]
### 15.16
"ceramic build. material" should fit now in registration, cm list under unit and cm list under locus and on the cm form itself.

**Comment by luizaogs** [comment]
Unit list looks fine.

**Comment by luizaogs** [comment]
Registration looks fine except with this combination: 

<img width="1027" alt="Screenshot 2024-04-25 at 3 19 13 PM" src="https://github.com/arch-kiosk/arch-kiosk-office/assets/67970402/4675ae10-ddcf-4118-bc81-ad1859f664ce">

**Comment by luizaogs** [comment]
Locus list does not look fine: 

<img width="1026" alt="Screenshot 2024-04-25 at 3 20 00 PM" src="https://github.com/arch-kiosk/arch-kiosk-office/assets/67970402/7c0b0b09-5cff-4d84-84d9-ef7ee9251c04">

**Comment by lbestock** [comment]
Aha, Candace said they can abbreviate that CBM. So we can change it, alas after working to make it fit.

**Comment by urapadmin** [comment]
but does she prefer it?

**Comment by lbestock** [comment]
Well, you know, communication. That was not specified. But she did mention without prompting that they usually just write CBM, so I would read it as yes.

**Comment by urapadmin** [comment]
well, the app can handle both now, the rest is configuration

**Comment by cmrice-arch** [comment]
Totally happy with CBM. I don't get notifications for any of the top comments with check boxes, so if there's something that should I need to respond to there, I might need to be tagged?

**Comment by luizaogs** [comment]
I configured this to CBM now.
