### ISSUE TITLE
QC reminder for locus relations - red tab like photos

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#2656]
making the tab red, okay. But should be a warning or an error?

**Comment by urapadmin** [comment]
### recording 15.16.1
I made it a warning. Needs testing.

**Comment by luizaogs** [comment]
Where is this update available?

**Comment by luizaogs** [comment]
Ok well I figured out the ELRI URL but I would need a login to test this stuff.
