### ISSUE TITLE
coordinates don't seem to work for ELRI?

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#2659]
what is not working here?

**Comment by urapadmin** [comment]
@lbestock ???

**Comment by lbestock** [comment]
I was wrong, it works fine. I was somewhat confused by the category tab - it made it look like it was possible to input multiple images, but it isn't - that's one image and a description category. Easiest way to make me not confused in future, if that is even worth doing, is to put a grey help text in the description field (or a label?) for the category tab.

**Comment by urapadmin** [comment]
then please make a new ticket for what you request there so that we don't entirely bury it in this ticket that is about to be closed ...
