### ISSUE TITLE
kiosk: PASU warning

### ISSUE THREAD

**Issue by luizaogs** [arch-kiosk/arch-kiosk-office#2663]
I'm configuring stuff for #2657 and ran across this error which seems to require your attention: 

<img width="1480" alt="Screenshot 2024-04-26 at 8 11 45 PM" src="https://github.com/arch-kiosk/arch-kiosk-office/assets/67970402/624856a8-52fa-4b7d-bee7-6e606baf0e27">

**Comment by urapadmin** [comment]
ja, I have seen that, a couple of times before. It isn't critical but I have to look at it when I turn to PASU.

**Comment by luizaogs** [comment]
Can I change the configuration and synchronize while it's there or no?

**Comment by urapadmin** [comment]
yes, it is harmless.

**Comment by urapadmin** [comment]
I don't see it anymore. Might have been a hiccup. Let's reopen this if it appears somewhere again.
