### ISSUE TITLE
USTP export error

### ISSUE THREAD

**Issue by luizaogs** [arch-kiosk/arch-kiosk-office#2667]
Huh...

I got an error that exporting images had taken more than 60 seconds or something of that sort, so I tried to prepare again and now this looks weirder so I leave it alone.

<img width="1512" alt="Screenshot 2024-04-27 at 9 40 33 AM" src="https://github.com/arch-kiosk/arch-kiosk-office/assets/67970402/2bbc39b0-e75b-403e-89e0-b5d842ca972a">

**Comment by urapadmin** [comment]
ja, that's because we were in each other's hair. see #2657
