### ISSUE TITLE
FM coordinates: add label to category tab

### ISSUE THREAD

**Issue by lbestock** [arch-kiosk/arch-kiosk-office#2669]
I was somewhat confused by the category tab - it made it look like it was possible to input multiple images, but it isn't - that's one image and a description category. Easiest way to make me not confused in future, if that is even worth doing, is to put a grey help text in the description field (or a label?) for the category tab.

_Originally posted by @lbestock in https://github.com/arch-kiosk/arch-kiosk-office/issues/2659#issuecomment-2081182099_

**Comment by urapadmin** [comment]
I deemed this not worth it
