### ISSUE TITLE
FM locus relations feature request: locus type shown in locus chooser

### ISSUE THREAD

**Issue by lbestock** [arch-kiosk/arch-kiosk-office#2672]
It can be hard to keep one's loci straight in one's head. Creating a relationship to the wrong locus is a constant danger for me when I am inputting relations. It strikes me while testing ELRI that there is room in the dropdown list from which one chooses the relationship for a bit of text. Even just having the locus type there would be very helpful - if I know I'm trying to define a relationship to a wall but the number I think it is shows up as a deposit, I know to go back and check what number my desired wall is. (Even better would be something more differentiated, but that would need both another recording field in the first place from which to draw that information and then users to use it so as to help with the relations issue. I think the locus type addition would be very helpful without requiring so much change, though I may underestimate how hard it is to implement.)

**Comment by urapadmin** [comment]
### recording 15.17
- the new config key "show_locus_type_for_related_locus" adds the locus type (the abbreviation) to the related locus in brackets.
- set it to nope to get the old behaviour. A project like Pacha might have that an issue because of the length of the identifiers.

**Comment by urapadmin** [comment]
anything but that abbreviation is too long for too many projects, from my perspective. So in that case we would need a specific selector instead of a dropdown here. But I also would need some more specific idea about what exactly to show during the selection:

>  Even better would be something more differentiated, but that would need both another recording field in the first place from which to draw that information and then users to use it so as to help with the relations issue.

is a bit vague.

**Comment by luizaogs** [comment]
This is working (I still have to test the rest of the relations stuff though). 

But just to make sure: you know that if it's on the type appears after the locus identifier in the locus form too, yes? An example: 

<img width="1025" alt="Screenshot 2024-04-28 at 9 32 12 AM" src="https://github.com/arch-kiosk/arch-kiosk-office/assets/67970402/50ee11ad-428a-4c66-8ff2-a9b2a246ebd5">

**Comment by lbestock** [comment]
> anything but that abbreviation is too long for too many projects, from my perspective. So in that case we would need a specific selector instead of a dropdown here. But I also would need some more specific idea about what exactly to show during the selection:
> 
> > Even better would be something more differentiated, but that would need both another recording field in the first place from which to draw that information and then users to use it so as to help with the relations issue.
> 
> is a bit vague.

What would be most useful is I think impossible. One often has sort of short-hand for loci that make sense in the moment (which is why people often fail to write the number in thinks like descriptions, too, because it's easier to remember "north wall" than "FA-004"). North wall, yellow sand, looter's pit, etc. All things that would be part of the description.

**Comment by luizaogs** [comment]
If the relation is across units the type does not show up for the locus from the other unit. Not sure if that matters.

<img width="940" alt="Screenshot 2024-04-28 at 9 35 47 AM" src="https://github.com/arch-kiosk/arch-kiosk-office/assets/67970402/98fd0f11-e865-4ea7-a45c-61d673bc6f4c">

**Comment by luizaogs** [comment]
Other than those two comments I believe this is good.

**Comment by urapadmin** [comment]
I was not aware that the locus header uses the same dropdown list. Does it properly work to switch between loci?
If so, I'd say it does not hurt to see the type there, too.

**Comment by urapadmin** [comment]
### recording app 15.17.1
It seems to work properly, so I'll leave it there.
- relations across unit types now show the locus type, too

**Comment by luizaogs** [comment]
Yes, sorry, the arrows work fine.

**Comment by luizaogs** [comment]
This is solved. Can I close it or do we want to leave it open for Laurel's comment above?

**Comment by lbestock** [comment]
I think the comments above are not an action plan. I expect this here to have made a difference that will be appreciated, and if in future someone (me or someone else) requests more we'll make a new ticket.
