### ISSUE TITLE
auto-jump to weight field after special finds type entered

### ISSUE THREAD

**Issue by lbestock** [arch-kiosk/arch-kiosk-office#2674]
Tiniest of bugs - I caught a remaining automatic jump between fields.
Testing ELRI.
Made small finds records.
If I choose a type from the dropdown list, it then jumps me several fields down to the weight field.
I have been able to repeat this several times but it also didn't happen once when I expected it, and I can't figure out the variable. It definitely does not happen if I type a type (it's a dynamic dropdown).

**Comment by urapadmin** [comment]
those tab stops are like bad pennies

**Comment by urapadmin** [comment]
### recording app 15.17.1
- removed

**Comment by lbestock** [comment]
My brain is slow and it is tying me in knots that @luizaogs  tests stuff in ELRI online in a version ahead of what I am testing for the local server here. Also then I take all these adorable pictures of Huxley in the recording data and Luiza can't see them. Terrible.

**Comment by urapadmin** [comment]
you'll get that version, soon.

**Comment by luizaogs** [comment]
That is pretty terrible. I wanna see Huxley.

**Comment by urapadmin** [comment]
🧠

**Comment by lbestock** [comment]
Dayplan/narrative: 
![image](https://github.com/arch-kiosk/arch-kiosk-office/assets/49291909/64e49482-db42-45ee-90da-281dec3d65fd)

**Comment by luizaogs** [comment]
Oh my god.

**Comment by lbestock** [comment]
Special find:
![image](https://github.com/arch-kiosk/arch-kiosk-office/assets/49291909/d19374dc-ecaa-4aa8-9238-b01c875dc4c8)

**Comment by lbestock** [comment]
There's not a lot of action around here...

**Comment by luizaogs** [comment]
You want mine? She was screaming at me until about 5 minutes ago and now is finally taking a nap.

**Comment by urapadmin** [comment]
that is not an adequately cute Bob picture. Makes him look scraggly compared to the looker.

**Comment by lbestock** [comment]
Maybe a trade. Bob took a major obsessive bath on me at 5am and I never got back to sleep. No sign of remorse over there in that special find.

**Comment by lbestock** [comment]
Ja I'm afraid he's not at his most handsome right now. But content, even when I moved the blanket hoping for a better angle.
![image](https://github.com/arch-kiosk/arch-kiosk-office/assets/49291909/3b1916db-d554-41de-ade2-a954991e0dbe)

**Comment by luizaogs** [comment]
Great, I'll Fedex. 

(Bob does have a little rat tail, Lutz, compared to Huxley's luxurious fur.)

**Comment by lbestock** [comment]
Now I'm getting the tongue thing. 
![3B3D50B6-C074-4284-AD2F-2040DD58B6F8](https://github.com/arch-kiosk/arch-kiosk-office/assets/49291909/34c0b998-d05f-4573-8cfe-c186c4ea7bbc)

**Comment by urapadmin** [comment]
everybody his nagging at the poor cat's tail. Good, he doesn't care.

**Comment by urapadmin** [comment]
One day GitHub will close our repository, I am sure.

**Comment by luizaogs** [comment]
I'm pretty sure everyone loves cat pictures. Github probably loves us.

**Comment by urapadmin** [comment]
To get back to topic:

> ### recording app 15.17.1
> 
>     * removed

**Comment by luizaogs** [comment]
You haven't actually released that yet, right?

**Comment by urapadmin** [comment]
no, I was distracted by the pictures of the cats in the other room. But it is now.

**Comment by lbestock** [comment]
He got cuter.
![image](https://github.com/arch-kiosk/arch-kiosk-office/assets/49291909/5efb3af8-adc8-4e86-8e38-d3bd48f2d00c)

**Comment by luizaogs** [comment]
He's very cute.

**Comment by luizaogs** [comment]
This is probably an iPad only thing, no? Or at least it's not happening on my Mac. My iPad is dead so @lbestock maybe you can look at this one when you get it in your local server?

**Comment by luizaogs** [comment]
Actually, it's not dead. I lied. Let me see...

**Comment by luizaogs** [comment]
Now if I pick a type from the dropdown it doesn't jump down to weight but it also just doesn't disappear - I get the value in the field highlighted and the dropdown options popping up instead. Is that ok?

**Comment by lbestock** [comment]
![image](https://github.com/arch-kiosk/arch-kiosk-office/assets/49291909/652a12b5-f71e-491e-85f7-a683058ba74c)
Wow I like having a real camera. And sunshine. And tulips.

**Comment by urapadmin** [comment]
That should be the case with all dropdowns. It is the downside of not jumping to the next field in FileMaker.

**Comment by luizaogs** [comment]
The squirrels will be there to eat it soon, I expect.
