### ISSUE TITLE
ELRI FM trench record information modified thing floats where it should not

### ISSUE THREAD

**Issue by lbestock** [arch-kiosk/arch-kiosk-office#2675]
In ELRI testing on the local server.
If I'm in the trench, regardless of which of the tabs I am in, there is the little "modified" pencil and indicator in the lower right corner:
![D6DBD7EC-9691-4937-A814-50840C96194F](https://github.com/arch-kiosk/arch-kiosk-office/assets/49291909/2acd7247-2a4d-4580-95d5-4acf476a6fa4)

That should only be visible on the trench tab, no? Here on the contexts tab for instance it is still definitely the thing from "trench" - it contains information that is not accurate for when the contexts were modified. It disappears if I go into a context or a CM.

**Comment by urapadmin** [comment]
### recording 15.17.1
yes, that is the trench record information and it is meant to be. The locus record information is shown below the locus list as soon as a locus is active,

But I guess it is confusing here and so I moved it into the "trench" tab.
