### ISSUE TITLE
FM QR code: ability to size on the iPad to fit frame for object photography

### ISSUE THREAD

**Issue by lbestock** [arch-kiosk/arch-kiosk-office#2676]
A thought occurred to me while I was giving an object photography tutorial Friday. And it sticks with me.
Sequence QR codes are the way to go, they are a game-changer even more than the in the image QR codes were. 
Object photography sequence QR codes are rough because the camera is mounted and moving that camera around is a major pain in the tuchus. If I'm on an iPad and I've got the camera set up to shoot coins, there's no way the frame is large enough to get the ipad in. My Apple Watch hack is fun and clever but has a couple of extra steps (and an extra piece of equipment) that make it not really a solution, we know. But what if one could choose to have a tiny QR code on the iPad? One that could be pinched to size to fit? Or even making the sequence QR code always small is not a terrible idea - it's then more visually distinct from the photoboard one and in fact I always find it a little awkward that I have to set the QR code, then step back from it to photograph the iPad, then take my photos. That is the tiniest of awkwardnesses that could be avoided if the code were small on the screen; the pinchable for object photography is really the point.

**Comment by urapadmin** [comment]
pinching is not really supported by FileMaker but I guess I can find a different way to switch between small and large sequence qr codes

**Comment by lbestock** [comment]
Not sure it is relevant and might just be a different ticket. If I'm doing object photos, the place I really want to be able to access that QR code, the little one, is from registration. It is SO handy that I can access the registration checkboxes from that layout without even going into the CM record. What if having a line in registration highlit gave me also the ability to make a QR code for that CM? I would be able to whip through photography. Without ever leaving that view I could take photos and check the boxes saying I had done so.

**Comment by urapadmin** [comment]
ja, different ticket, no question :o)

**Comment by lbestock** [comment]
I am getting a show over here, but I think it's about to shift in mood.
![image](https://github.com/arch-kiosk/arch-kiosk-office/assets/49291909/7deaeb4d-e3da-4dbd-bd28-21eb91b4bc0a)

**Comment by urapadmin** [comment]
### recording app 15.18
- you can choose now to have a small sequence qr code in the qr code selector

**Comment by urapadmin** [comment]
now the normal photo board qr codes don't work anymore ...

**Comment by urapadmin** [comment]
### recording 15.18.1
- fixed

**Comment by luizaogs** [comment]
Works well. But I leave it to @lbestock to judge if it is small enough before closing.

**Comment by lbestock** [comment]
I think the size is great - because it's a sequence code it can fill the camera frame.

I note that the "close QR code" message when you click to exit is now cut off by the size and should be slightly reformatted.

**Comment by luizaogs** [comment]
Woops I'm on my Mac and used the X so didn't notice.

**Comment by urapadmin** [comment]
Ja, I know. I can't make the whole shebang fit in 200px but I should be able to fit in the close button and its label. 
By the way: In sequence qr codes you can also click outside of the qr code and that closes the qr code in one step.

**Comment by lbestock** [comment]
> By the way: In sequence qr codes you can also click outside of the qr code and that closes the qr code in one step.

Hm, no that isn't working on the iPad.

**Comment by urapadmin** [comment]
@luizaogs: testing recording features on the Mac is sub optimal. It just happens too often that things look different on an iPad, don't work the same way on FileMaker Go etc. We really need to test the recording app primarily on the iPads.

**Comment by urapadmin** [comment]
well, maybe not everywhere outside. Tap the identifier or the little camera or the date ...

**Comment by lbestock** [comment]
OK that works :)
Now I want to go take some object photos instead of get ready for my last class of the semester and a fun meeting.

**Comment by luizaogs** [comment]
> @luizaogs: testing recording features on the Mac is sub optimal. It just happens too often that things look different on an iPad, don't work the same way on FileMaker Go etc. We really need to test the recording app primarily on the iPads.

Yes, I know. Sorry. I never have the iPad on me. I'll pay more attention.

**Comment by urapadmin** [comment]
fitting the button in: postponed.
