### ISSUE TITLE
QR code access from registration in FM

### ISSUE THREAD

**Issue by lbestock** [arch-kiosk/arch-kiosk-office#2677]
> Not sure it is relevant and might just be a different ticket. If I'm doing object photos, the place I really want to be able to access that QR code, the little one, is from registration. It is SO handy that I can access the registration checkboxes from that layout without even going into the CM record. What if having a line in registration highlit gave me also the ability to make a QR code for that CM? I would be able to whip through photography. Without ever leaving that view I could take photos and check the boxes saying I had done so.

_Originally posted by @lbestock in https://github.com/arch-kiosk/arch-kiosk-office/issues/2676#issuecomment-2081596858_

**Comment by lbestock** [comment]
Can a QR code ever be scanned and lead us to the right place in the recording? As in, if I have a QR code scanner in FM and I point it at a QR code, can it navigate me to the record? Because if THAT were possible and we had QR codes accessible from in registration then I, as registrar, would get a little bluetooth thermal printer and I would be printing QR code labels to actually put on my CM bags.

**Comment by urapadmin** [comment]
we had that idea and were not convinced that the thermal sticker would stick to the bags. On the recognition front that's imaginable. I am not convinced it would be worth the effort, though. Can't see the projects doing something so sophisticated. 
But possible it is.

**Comment by urapadmin** [comment]
different ticket, though :o)

**Comment by urapadmin** [comment]
### recording 15.18
- there is a qr code button in the menu now

**Comment by urapadmin** [comment]
nope. Looks like Brown restarted the servers. 15 minutes ...

**Comment by urapadmin** [comment]
back

**Comment by luizaogs** [comment]
Oh cool! Works.
