### ISSUE TITLE
Director's View: number counter in widgets is always at total, even with a sort

### ISSUE THREAD

**Issue by lbestock** [arch-kiosk/arch-kiosk-office#2678]
In Director's View when I sort within a widget, say for narratives that are only collected materials, the counter at the widget stays the same as it was before the sort. So today (28 IV 24) in ELRI, for instance I have 40 narratives. If I sort for CM, it stays set at "40 of 40 Narrative(s)". Shouldn't that now read "5 of 40 narratives" since only 5 of the 40 total are CM? Same thing happens in files.

If I sort by a unit or a person it does reform the search and gives me 7 of 7 narratives, for instance. But the "of" always separates two copies of the same number, which doesn't make a ton of sense.

**Comment by lbestock** [comment]
Going through open tickets and while this isn't critical, it's the first in the list that I think I would want attended to before going into the field.

**Comment by urapadmin** [comment]
### Kiosk 1.5.38.3
- That UI really needs an update one day. Looks ancient.
- However, the record count should be okay now with narratives and files

**Comment by luizaogs** [comment]
Narratives looks ok but it looks like you flipped the numbers for the files widget: 

<img width="684" alt="Screenshot 2024-05-25 at 8 42 57 AM" src="https://github.com/arch-kiosk/arch-kiosk-office/assets/67970402/0774508b-3d33-44e1-bc76-82a92e10672b">

Should be 23 of 100, presumably.

**Comment by urapadmin** [comment]
### Kiosk 1.5.38.4
- kinda. Not really switched them but the x of y should only be visible if the number of images in the widget exceeds the maximum number of images that the widget is allowed to show (100).
