### ISSUE TITLE
File Repository: default setting for file format in file import "ton" is jpg, it should be blank

### ISSUE THREAD

**Issue by lbestock** [arch-kiosk/arch-kiosk-office#2679]
The file import defaults to having jpg set. More often than not people are not importing jpgs. The default should be blank.

**Comment by urapadmin** [comment]
changed for ELRI, although I don't really agree with you. You are the only one shooting RAW files so far. I have only encountered jpgs otherwise. No file extension is not the best default, that's why you tried to import an XMP file, see #2680. It would be better to use useful extensions instead.
