### ISSUE TITLE
File Import Failure

### ISSUE THREAD

**Issue by lbestock** [arch-kiosk/arch-kiosk-office#2680]
![CCA062C5-0877-47E1-BEF9-8F944C42E35C](https://github.com/arch-kiosk/arch-kiosk-office/assets/49291909/1c7b18fb-4f35-4961-9ff0-820bb4c799e8)

Testing ELRI local server and got this.

**Comment by lbestock** [comment]
The 35 imported files are definitely in there and fine.

**Comment by lbestock** [comment]
I will not try to import the rest until you look at it.

**Comment by urapadmin** [comment]
hm. I can't see anything except that there was an xmp file could not be imported but after that the process tried another file, so I doubt that was the cause. Also the import folder seems clear and everything in done, right?

**Comment by urapadmin** [comment]
I reran the import and it worked fine. At least it finisihed with a proper response. So I think last time the response did not make it to the client - we have such hickups more often than I wish - but the result was the same. At least the result looks the same in the logs and on the drive afterwards. Two files have not been processed:
<img width="702" alt="Screenshot 2024-04-29 at 4 36 14 PM" src="https://github.com/arch-kiosk/arch-kiosk-office/assets/38838314/4ff300cc-7668-43ee-9bff-c04446f2b95e">

**Comment by urapadmin** [comment]
this is correct for the xmp file. I am not sure what is different with the DSC_8730.NEF than with the others. I tried to import it with the option to take the date from the EXIF data. The image is this:
![DSC_8730 Small](https://github.com/arch-kiosk/arch-kiosk-office/assets/38838314/e13c5fcf-7ec1-4b5d-8a8f-df723e2072e7)
