### ISSUE TITLE
Q&V: Query for ELRI / USTP that shows graphs per locus/material

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#2681]
We have two pie charts in the recording app that show weight/count per locus (by the way of relying on the fact that all collected material from a locus is in one bag).
What the projects really want is those charts per locus for a certain material.

I could also try to change the recording app. In the end the outcome would be the same even for current USTP as there cannot be a second bag with ceramics per locus that mustn't be added.
@lbestock: right?

**Comment by luizaogs** [comment]
Would it be better to have the context number in parentheses? Other than that, this is working I think. Tested on the iPad.

![IMG_50B1E59E65A9-1](https://github.com/arch-kiosk/arch-kiosk-office/assets/67970402/f9e714be-924c-4116-a5e9-5cd5c6afff96)

**Comment by luizaogs** [comment]
Oh wait, weird. If I have the bulk graphs up and click on the one by count and then on "analyze context," only the weight graph changes. Is that intended?

**Comment by urapadmin** [comment]
### Kiosk 1.5.33
- the same new chart is available in Q&V now. see #2687

**Comment by urapadmin** [comment]
### recording app 15.19.1
- weirdness should be gone
- context identifier added to brackets
