### ISSUE TITLE
recording app: close button does not fit small sequence qr code

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#2683]
fitting the button in: postponed.

_Originally posted by @urapadmin in https://github.com/arch-kiosk/arch-kiosk-office/issues/2676#issuecomment-2084111901_

**Comment by urapadmin** [comment]
### recording app 15.19.2
- small qr codes don't show a close button at all anymore. They close on click.

**Comment by luizaogs** [comment]
This does not appear to be working reliably. Sometimes I can close it with a single click, sometimes multiple clicks don't work, and in one case while in photoboard I even got the message below while trying to click to close it: 

![Screenshot 2024-05-18 at 13 56 12](https://github.com/arch-kiosk/arch-kiosk-office/assets/67970402/7782f042-8b42-4434-b61e-82c252a38f93)

**Comment by luizaogs** [comment]
Also, sequence ones require two clicks currently, and that seems to be pretty reliable, but not sure if two clicks was the intention.

**Comment by luizaogs** [comment]
Ah wait, the photoboard ones are also closing if one does two clicks in succession.

**Comment by urapadmin** [comment]
If you click inside of the qr code, two clicks are normal. That 's the old FileMaker problem that if something is shown in a Browser (the qr code is inside a Browser component) the Browser has to be activated first (first click) and only the next click then get's registered by the browser itself. There is nothing I can do about that part.
What adds to confusion is the fact that outside of the browser you only need to click once. 

So depending on WHERE you click you might get different responses. In case of the error message above I'd be curious where exactly you tapped (assuming you use an iPad here?)

**Comment by luizaogs** [comment]
Yes, I am using an iPad.

In photoboard, clicking once in the white space to the right of the code doesn't work. I need to click twice, independent of where I'm clicking. I am getting that error reliably if I click on the date in photoboard.

Clicking outside the QR code in sequence doesn't do anything. I can only leave that one if I click on the code. (Ah no, apparently clicking on the identifier once lets me go too.)

**Comment by urapadmin** [comment]
### recording app 15.20.1
- Ja, that was chaos. I hope it is better now. 
- BUT we also have to test if the PI stuff would still work. Not so much if the e-paper function itself still works - only I could do that - but more if the ui in the large sequence qr code and photoboard qr code appears and is useable. So lan-address needs to be set to something like 192.168.1.1 or so.

**Comment by luizaogs** [comment]
Hm, no. I can still get that pop up above reliably if I click on the date in photoboard. Also, now if I double click on the white space to the right of the QR code in photoboard I get the stop execution of current script? thing. Not every time, but it has already happened twice in the three times I've tried it.

**Comment by luizaogs** [comment]
Sequence appears to be working correctly - one click outside of the QR code in the white space does the trick, and clicking twice on the code itself works also. So the problem seems to be with photoboard.

**Comment by luizaogs** [comment]
I also have no idea how to test the PI stuff so haven't tried that.

**Comment by urapadmin** [comment]
you just set the config key eink/eink_lan_address to something other than "-" and then you get the close button and the PI option when clicking on the qr code in photoboard and large sequence qr code. The small sequence qr code should not show further option on click and just keep closing right away. 

But it seems I have to look at the photoboard again. Meh.

**Comment by luizaogs** [comment]
Ah ok. Yes, I'll try that once you release a new version then.

**Comment by urapadmin** [comment]
### recording app 15.20.2
- if this isn't fix now I'll scream! 😱

**Comment by luizaogs** [comment]
Um. Kinda? This is the state of things: 

In photoboard: two clicks on the QR code lets me exit. One click on the date does as well. One click on the identifier works. However, if I click on the space between the QR code and the identifier I have to click twice still. And if I click once there, expecting it to close, and then click twice in the same space in quick succession I get the stop the current script? crap.

Small sequence QR code: seems good to go, as I said before (one click on the white space closes it, as does one click on the date/identifier, and two clicks on the code itself). 

BIG sequence QR code (I apologize, I forgot this option existed - a comment above this coming below): white space to the right of the QR code is the same issue as photoboard, in that one click does not close it and if I then click twice in quick succession I get the stop the current script? popup. Two clicks on the QR code closes it. One click on the date, as well as on the identifier, also closes it. 

So I think we have the same as in the last update with photoboard, and it seems like the same situation in big sequence QR code (and yes, I'm on 15.20.2).

**Comment by luizaogs** [comment]
The reason why I forgot to test the big QR code in the first place is that it seems like the default (at least in PVD) is currently the small one, so since I didn't have to check the little option I forgot it existed. Should that be the default? Seems like Laurel really only wanted it for object photography, so my assumption is that the big one should be the default instead.

**Comment by luizaogs** [comment]
As for the PI key: works as it should when it is on.

**Comment by urapadmin** [comment]
> The reason why I forgot to test the big QR code in the first place is that it seems like the default (at least in PVD) is currently the small one, so since I didn't have to check the little option I forgot it existed. Should that be the default? Seems like Laurel really only wanted it for object photography, so my assumption is that the big one should be the default instead.

we decided that to be the default, indeed. It is generally easier to photograph a smaller qr code with an SLR than a larger one. Since the idea of the sequence qr codes is that you can photograph them in the shade under your umbrella it is in fact easier to do that with a small qr code so that you don't have to hold the camera far away from the iPad.

**Comment by luizaogs** [comment]
Hm ok, then disregard that part.

**Comment by urapadmin** [comment]
### recording app 15.20.3
- needless to say that this drives me nuts. I can't really control this properly because of the web browser. So where exactly the line between one-click close and two-click close is, I can't control. That's why I have now finally added a close button in the upper right corner for all of them. I never wanted that because I didn't want a UI control appear in the photos. But there it is now. Now users know where to click and that is always a one click.
- I have added something to suppress the stop the current script crap. But I don't exactly know in which script this occurs, so this is tapping in the dark again.

I loathe FileMaker.

**Comment by luizaogs** [comment]
Well it may not look as nice in photos, but it works.
