### ISSUE TITLE
q&v charts: column chart and toggling categories

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#2686]
this is less trivial than it seems because somehow the column chart has a strange relation between the column and the category it shows.

**Comment by luizaogs** [comment]
The top material in the legend is currently unlabeled in the "what material" query for the weight view. I realized this when I was toggling the bar graph, but I now see that it is also the case for weight in the pie chart view:

<img width="1456" alt="Screenshot 2024-05-01 at 1 18 02 PM" src="https://github.com/arch-kiosk/arch-kiosk-office/assets/67970402/9b120c27-c95f-4c80-ba09-a0a5466a014d">

<img width="1443" alt="Screenshot 2024-05-01 at 1 18 16 PM" src="https://github.com/arch-kiosk/arch-kiosk-office/assets/67970402/4ebd2cad-4da8-4688-8f99-4cf5b501f14a">

**Comment by luizaogs** [comment]
Toggling it on and off does not help.

**Comment by luizaogs** [comment]
Ah yes you are right. PBA has one. Sorry. This is fine, then.
