### ISSUE TITLE
q&v chart: allow for multiple charts per chart type

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#2687]
In the first version only one chart per type was allowed. Hence we only have a pie chart and a bar chart.
Now what we really need is the ability to define several charts per query (based always on the exact same data). 
Each chart type gets a selector that allows to switch between the charts. 
We keep the title in the chart so that it gets exported in the image export.

**Comment by urapadmin** [comment]
### Kiosk 1.5.33
- Queries that offer more than one chart per type have a selection on top of the chart that allows switching between the charts
- currently the new query "how much pottery has been found ... " offers pie and column charts for weight and count. The results should match the results of the new charts in the recording (see #2681)
- the query "what materials and how much " has count and weight pie charts now

**Comment by luizaogs** [comment]
It took me a while to figure out how to change from weight to count. I don't know if moving the dropdown to the left would help? At least that's where my eye goes first, rather than to the right where it currently is.

**Comment by luizaogs** [comment]
I also note that the percentages for the graphs in Kiosk have more decimal spaces, presumably because there is more space. So it's the same results but the Kiosk graphs have a higher accuracy / specificity.

**Comment by luizaogs** [comment]
Don't know if you want a separate ticket for this so I don't open one yet. Weird thing in PVD: I was trying to see how the graphs were working for the "what materials and how much" query and first tried pulling it up for LA, but that was a crappy spread of data so then I switched to PBA, which was better. But somehow I've ended up with the results for PBA (you can see that PBA is in the selection box) but a label for the graph mentioning LA: 

<img width="1512" alt="Screenshot 2024-04-30 at 9 30 34 PM" src="https://github.com/arch-kiosk/arch-kiosk-office/assets/67970402/333631b3-28a4-460d-a77d-e9904e9671cb">

**Comment by luizaogs** [comment]
Also, for the "what materials and how much" query the pie chart starts with the default view of quantity whereas the bar graph starts by default on weight. Does it make sense to start the two on the same one, either quantity or weight?

**Comment by urapadmin** [comment]
> It took me a while to figure out how to change from weight to count. I don't know if moving the dropdown to the left would help? At least that's where my eye goes first, rather than to the right where it currently is.

The title stacked twice looked unappealing. I got rid of the title in the graph now. On second thought it might be better that way. If people want to copy the chart into a document they might prefer it without the title in order to avoid a different font. So the selector is kinda the title now. If there isn't anything to select the dropdown button vanishes and it does not drop.

**Comment by urapadmin** [comment]
### Kiosk 1.5.33.1
- the weird thing should not happen anymore
- I have dealt with the title and selector (see above)
- we keep the decimals in Kiosk, I'd rather get rid of the unnecessary precision in FileMaker but it's not worth finding out how to do that until somebody is actually annoyed by it.
- optimized the order of graphs in the query "what material and how much ..."
-

**Comment by luizaogs** [comment]
I'm still finding the selector hard to see/find, but maybe I'm just being picky and you should get a second opinion from @lbestock 

Is there a way to move the arrow of the drop down to the left, close to the graph title? It's so far away.

**Comment by urapadmin** [comment]
ja, that's what I feared would happen next. The selector is now far away from the text. 

I cannot move the arrow closer to the text because I do not know where the text ends. I can set it to a fixed width but then we risk cutting of some titles, which would be worse. 

So the only option that's left would be making the title right aligned again. That way your eye would not find a title anymore where it expects it (on the left), you would go search for it and find it with the arrow next to the title. 
Or I put the arrow in front of the right aligned text. But that is rather unusual. 

But this is also a thing that once found out is learned (We have drop down arrows on the right in other places in Q&V, too). So I would not want to jump through too many more loops with this.

**Comment by luizaogs** [comment]
Ok, if you don't want to move it before the text (that might be easier to find, even if it's not usually where one would put an arrow) then this is good to go.

**Comment by urapadmin** [comment]
Ha. I hadn't looked at this because yesterday the room was turning around me most of the day when I looked at anything. (Covid is really nasty). 
But also because I feared you found another bug  in the charting library. What a charming way to put the user-designer conundrum (and Bob and Huxley prove this every day). Made me smile :o) (which still makes the room wobble)

**Comment by luizaogs** [comment]
I'm so sorry you're still feeling so poorly :( I hate covid.

**Comment by urapadmin** [comment]
### kiosk 1.5.33.3
- not giving up here: Now I went all explicit. If there is more than one chart to choose from, you get a label in front of the selector.

**Comment by urapadmin** [comment]
not that cats usually follow signs, but I hope the cat / user analogy isn't going too far :o)

**Comment by luizaogs** [comment]
Your incompetent human user says thank you.
