### ISSUE TITLE
recording: ELRI banner cut off

### ISSUE THREAD

**Issue by luizaogs** [arch-kiosk/arch-kiosk-office#2688]
iPad. You can see that the ELRI project name is cut off in the header: 

![IMG_C3270D2ECA50-1](https://github.com/arch-kiosk/arch-kiosk-office/assets/67970402/1d1c813c-6eab-4eef-b9cc-df1fc7360d67)

**Comment by urapadmin** [comment]
### recording app 16.2.4
- it should break into two lines now (as will others if they are longish ...)
