### ISSUE TITLE
Q&V: Can't click on images anymore and other issues

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#2691]
... they don't open in the edit file dialog.

ALSO: loci in the unit / locus list have no foot step to jump to the locus

Neither does the site in the unit view

**Comment by urapadmin** [comment]
that's a side effect of a quick fox I applied before the ARCE conference:

>What exactly causes the issue is not clear to me. But it has to do with something that tries to load jquery and that collides for some reason with code in the queryandview app. But only in that one. Hub, director's view etc. were all okay. Very mysterious.
The workaround is that the queryandviewplugincontroller load the template now with a modifier: return render_template('queryandview.html', no_third_party_js=True). That has the effect that the kioskbasic.html'loads kiosk_main_no_third_party.js instead of kiosk_main.js. The kiosk_main_no_third_party.js skips all jquery modules like dmUploader, iziToast etc. And that did the trick. 

So now I have the problem: Either charts or opening images, Opening images is using magnificent Popup and that depends on jquery.

**Comment by urapadmin** [comment]
I could use this as a reason to turn to #2405. But that's a bigger task and I even wanted to thing about IIIFEs.
see http://openseadragon.github.io/

But perhaps I start smaller?

**Comment by urapadmin** [comment]
### kiosk 1.5.33.5
- that was a big fix. documented here: https://wiki.arch-kiosk.brown.edu/urapdev/doku.php?id=manuals:developer_manual:kiosk_front-end_apps#how_to_load_kiosk_front_end_apps_dynamically
- the result should be that query and view both shows charts and allows you to click on images
- check if all other apps are loading properly: Director's view, Hub, logmanager, stratigraphy studio

**Comment by urapadmin** [comment]
This is only addressing the image issue. The others are still open:

- loci in the unit / locus list have no foot step to jump to the locus

- Neither does the site in the unit vie

**Comment by luizaogs** [comment]
Images and charts are both working. Leaving this open for the footsteps.

**Comment by luizaogs** [comment]
(Checking if other apps are working properly is being done in #2699)

**Comment by urapadmin** [comment]
### Kiosk 1.5.35.5
- site footsteps in unit view are there now
- locus footsteps in locus list in unit: #2708 
---
- footsteps in data table is covered by #2709

**Comment by urapadmin** [comment]
looks good on local PASU
