### ISSUE TITLE
PASU/URAP/MADP: All images have the modification date set to 24.II.2024

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#2692]
it must have something to do with #2553 but I am not sure what that would be. I fixed that issue with version 1.5.24.3.
But how and would the wrong modification date be the result of that or the error before?

**Comment by urapadmin** [comment]
I found out now that #2553 was about a wrong return result that would have cause KioskLogicalFile.create_auto_representations alwais fail. As a consequence housekeeping would assume the file was not an image and add the NOT_AN_IMAGE tag. 
So far so good. Only: Neither setting the tag nor removing it later after #2553 was fixed would set a new modification date. 
So it is still unclear how that happened.

**Comment by urapadmin** [comment]
simulation shows: housekeeping is not the culprit. The new modified date must have been set somewhere else.

**Comment by urapadmin** [comment]
I got it. It was a user who went through the pains of untagging the NOT_AN_IMAGE tag. #2553 even explains it.
Hmpf. I guess I should try to restore the original modification dates from a backup for these three projects. 
The point why this even came up was that when I tried to transfer PASU from the online server to the offline server transfer_kiosk wanted to transfer ALL images. An that's because all images had a newer modified date. So I guess that is not necessarily the best way of going about it in transfer_kiosk. I'll make that a ticket:

**Comment by urapadmin** [comment]
### 05.May
I have set the modified dates back to their original dates for PASU, MADP and URAP

**Comment by urapadmin** [comment]
@luizaogs 
Just double checking: To me it seems that you did not reset the tags for MKAP via bulk tagging (#2553 showed that MKAP was affected by the NOT_AN_IMAGE TAG). Can you remember? I can only query four images that have a modified date later than 23 Feb 2024.

**Comment by luizaogs** [comment]
I don't actually remember whether I did it or not, but I guess if there are only 4 I must not have?

**Comment by urapadmin** [comment]
then we call this done.
