### ISSUE TITLE
jquery: deprecation warning asks for an upgrade

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#2699]
deprecation warning for jquery:

![image](https://github.com/arch-kiosk/arch-kiosk-office/assets/38838314/5c7e8f49-1d6b-49b9-ac4f-ad6b82d1b87e)

I have not upgraded jquery for years. In fact I wish I had never started with it. I need to get rid of it but that would also mean I have to get rid of all the other libraries, particularly magnificentPopup and fmUploader. That's too much work. 

So let's try if an update works.

**Comment by urapadmin** [comment]
also connected to #2691 that is straight from jquery library hell

**Comment by urapadmin** [comment]
### kiosk 1.5.33.5
- upgraded to jquery 3.7.1 (this time minified).
- this can cause errors more or less everywhere. Particularly in our older modules like file repository, hub, especially file import but also administration and whatnot. So we have to go everywhere at least once and see if it behaves properly. 
- @lbestock All import methods have to be tested again

**Comment by luizaogs** [comment]
**Hub**
create new dock: works
delete dock: works
prepare dock: works
download: works
upload: works
import: works
synchronization: works
excel export: works
download of export from file manager: works

Did I forget anything Hub-ish? Let me know.

**Comment by luizaogs** [comment]
**Administration**
housekeeping: works
file manager: potential related issues in #2700 
file picking: can add and delete rules (if you need more than that tested, let me know)
logs: works
privileges: can add and delete
users: can add and delete

If I forget anything here, let me know...

**Comment by luizaogs** [comment]
**Director's view**
widgets working correctly, including quality control markers

I haven't actually added new data to see if it shows up properly - if that is needed just let me know.

**Comment by luizaogs** [comment]
**File repository**
adding contexts: works
adding contextual-independent description: works
adding tags: works
downloading files: works
adding file names: works
deleting files: works
little star and trash can icons: work
bulk tagging: works

Haven't tested file imports because it sounds like @lbestock is going to do so, but if not also let me know.

**Comment by luizaogs** [comment]
I think that covers everything?

**Comment by urapadmin** [comment]
I think this should have revealed if upgrading jquery has any side effects. So I think we're fine. We will test file import and the basics again with the local server for PASU and USTP anyhow here. 

Nothing of what you encountered has actually to do with jquery. It is funny how one finds unrelated stuff all the time when conducting this kind of "test everything" test. There are always bugs somewhere. 
Thank, you. This was very helpful.
