### ISSUE TITLE
file repository: clicking enter while in contextual-independent description

### ISSUE THREAD

**Issue by luizaogs** [arch-kiosk/arch-kiosk-office#2701]
If I'm in the edit file dialogue and I'm trying to write a contextual-independent description, and I need to write something on a new line, clicking on return/enter (which I expected to let me write on a new line) instead closes the dialogue. Clicking on return + option, which I expected would be a workaround, also just closes the dialogue. Should adding different lines to this description box be possible? Doesn't seem to be the case currently.

**Comment by urapadmin** [comment]
### Kiosk 1.5.36.1
- the return key should now make new lines in that particular field

**Comment by luizaogs** [comment]
It sounds like this was resolved when you tested it, Lutz?

**Comment by urapadmin** [comment]
yes, I think we can close this. it is also rolled out to PVD and URAP meanwhile, so you may double check.

**Comment by luizaogs** [comment]
Ah yes, it is working.
