### ISSUE TITLE
file import: get date from folder does not process two-digit years correctly and needs a dot between latin date parts

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#2704]
trying this in URAP:
1. currently latin dates need a dot, so 1IV12 does not work at all
2. 1.IV.12 leads to 1 Apr 0012 instead of 2012. The same year guessing that we use elsewhere should apply. (Only it does not seem to work in the file repository either see #2439

**Comment by urapadmin** [comment]
### kiosk 1.5.36
- old code. Now the file import is using the same date guessing mechanism as the file repository. So 1IV22 should be accepted as 1.4.2022. For details see also #2439

**Comment by lbestock** [comment]
PASU is still on the local server and testable there?

**Comment by urapadmin** [comment]
I'll have to update it with latest Kiosk version first

**Comment by lbestock** [comment]
Wow either I no longer know how to configure a bloody import, or it's still not working. A bunch of things imported from ton, in folders named 1.IV.12 and 2IV12 did not come in with dates at all.

**Comment by lbestock** [comment]
Yeah wow, ok phew.
