### ISSUE TITLE
Q&V: request that full-text search include tags and context independent description from FR

### ISSUE THREAD

**Issue by lbestock** [arch-kiosk/arch-kiosk-office#2705]
I am using URAP today in a meeting about Semna. We input the images from 2012 and I have added descriptions to some, and may tag those that show Semna and/or the Semna desert wall. I would like full text search to grab those, too, if possible - the ability to bring together the Kiosk recorded data from the Semna desert wall and our earlier photos that have no context yet would be great. Some of the desert wall ones I even want to add to the contexts created in 2018/19, but we haven't worked at and won't the fortress and I still want to be able to find those in Q&V, not just the FR.

**Comment by urapadmin** [comment]
full text search in Q&V cannot possibly find things that are not connected to any context. The result of Q&V is always a context (in our sense, so an identifier). 

You have to use the file repository for that, where you already can search for such things. So I am not sure what exactly you are asking for.

**Comment by lbestock** [comment]
Hm, yes I totally see. Hm. What I wanted was one place to see everything associated with Semna. If I use Q&V I get the features and survey units, which I do indeed want to see with that. When I'm in the file repository, I get only the things described themselves as Semna, not images of units where Semna is in the unit description but not the image description. So neither place gets me everything that I wanted to see

**Comment by urapadmin** [comment]
And it will be that way until you connect your images with the context

**Comment by urapadmin** [comment]
once the images are connected to a context their descriptions will be found by full text search in Q&V, by the way.

**Comment by lbestock** [comment]
But not the other way around, the FR does not find images of contexts where the context description includes the search term.

Semna isn't a context. The desert wall is, and I can add the old photos to the more recently created context on that front. I'll think about whether or not I should make the fortress a survey unit retrospectively.

**Comment by urapadmin** [comment]
see #2631
