### ISSUE TITLE
PASU 2024 configuration changes

### ISSUE THREAD

**Issue by lbestock** [arch-kiosk/arch-kiosk-office#2706]
A running list of things I notice to change in PASU before sending it out the door.
- [x] turn off area (by which I mean sector, the new field added for ELRI)
- [x] set prefix for loci to SU24- (which means, set ceramic prefix to SU24)
- [x] should numbers really start with 000? loci and sample CM numbers both do
- [x] turn off phantom second material in CM (bulk, sample, and special find all have it)
- [x] labels/term_for_ceramic_fragment
- [x] Kiosk: Configure Glossary: set fragment to the same as term_for_ceramic_fragment
- [x] temporal relations in relations need to be configured - there are none
- [x] do they use alternate locus ID? because it's kicking around there and called locus so I reaaaalllly doubt it, and that should be turned off
- [x] yeah, no, see the list in a comment below - ticket not closable until that is finished

**Comment by lbestock** [comment]
I changed finds but not SUs to start with 1. We must have had SU at 0 for a reason. Test this!

**Comment by lbestock** [comment]
"phantom second material" isn't totally clear to me in config. I am disabling "show_material_specified" and need to check if that has the desired effect.

**Comment by lbestock** [comment]
"term for ceramic fragment" is currently fragment. I don't see why to change that.

**Comment by lbestock** [comment]
I have configured the FM for PASU locally. I then backed up - the backup took ages longer than I expected, but says it was successful. I will now download and test the configuration on an iPad (and test the download on the big Mac, too, to make sure the security warning there is gone...)

But @urapadmin I did not address the last checkbox. Not sure if you want to do that before or after I download to an iPad to test things? Or if it matters? But I have to cook dinner anyway.

**Comment by urapadmin** [comment]
> I have configured the FM for PASU locally. I then backed up - the backup took ages longer than I expected, but says it was successful. I will now download and test the configuration on an iPad (and test the download on the big Mac, too, to make sure the security warning there is gone...)
> 
> But @urapadmin I did not address the last checkbox. Not sure if you want to do that before or after I download to an iPad to test things? Or if it matters? But I have to cook dinner anyway.

does not matter for backup / restore

**Comment by urapadmin** [comment]
> I have configured the FM for PASU locally. I then backed up - the backup took ages longer than I expected, but says it was successful. I will now download and test the configuration on an iPad (and test the download on the big Mac, too, to make sure the security warning there is gone...)
> 
> But @urapadmin I did not address the last checkbox. Not sure if you want to do that before or after I download to an iPad to test things? Or if it matters? But I have to cook dinner anyway.

you did not backup the whole file repository, I hope?

**Comment by lbestock** [comment]
I so backed up the whole file repository.

**Comment by lbestock** [comment]
Whoa none of the relations have automatic temporal implications in PASU! They would be HM-less. That needs configuration after all these test data are wiped out.

**Comment by lbestock** [comment]
@urapadmin discovered that these were deliberately not set, or at least so it looks in PASU 2022. And going into Anna's data, sometimes the temporal relation was manually set and sometimes not. This would be a killer with the HM. Once tested, we really must configure this for them and let them know we have done so.

**Comment by urapadmin** [comment]
> @urapadmin discovered that these were deliberately not set, or at least so it looks in PASU 2022. And going into Anna's data, sometimes the temporal relation was manually set and sometimes not. This would be a killer with the HM. Once tested, we really must configure this for them and let them know we have done so.

and they are set correctly by default in the template, so they must have been set that way in 2022. 
You should also check the other config keys about relations.

**Comment by lbestock** [comment]
Synchronizes fine. This checklist now is stuff for @lbestock to do when testing is done.

- [ ] delete testing images from the FR BEFORE restore
- [ ] after restore, change the valuelist to have temporal relations in config key valuelist_locus_relatsion_spatial_to_chron
- [ ] set the config key show_locus_relations_chronology to yup (is now at depends)
- [ ] tell PASU we have made this change and why

**Comment by urapadmin** [comment]
also: #2153 asks you to check the keys "labels/standard_term_for_cm" and "labels/plurals". From my perspective at least the former should be set to bulk. We want to change that to collected material.
