### ISSUE TITLE
FM: tags search function?

### ISSUE THREAD

**Issue by luizaogs** [arch-kiosk/arch-kiosk-office#2717]
Testing here and this is another case where I'm not sure if this is just a testing annoyance or if it could be relevant in the field. I know @lbestock uses a lot of tags in URAP so perhaps she would have a better idea than I would. 

The issue is that there is no way to easily navigate to a tag in the manage tags module (or if there is, I haven't figured out how to use it). I can totally search for a tag using the search button on the homepage, but that leads me to the tag analysis module. And then to find the tag to actually edit it when one has a bunch of tags isn't super easy, since you have to move through a bunch of them in the manage tags module using the arrows. But again, PVD has a million - not sure how relevant this is in a real project scenario.

**Comment by urapadmin** [comment]
I had the same issue when I was testing it. I suppose it would not hurt to have a navigation in the tag module

**Comment by urapadmin** [comment]
### recording app 15.20.1
- there it is: little magnifying glass reveals a list from which you can pick your tag

**Comment by luizaogs** [comment]
Cool. Thank you.
