### ISSUE TITLE
kiosk: weird error after import

### ISSUE THREAD

**Issue by luizaogs** [arch-kiosk/arch-kiosk-office#2718]
A weird error upon import that I don't recognize so I tell you. I didn't do anything in this database - I literally just downloaded and then imported it before doing anything because I got a patch.

<img width="1512" alt="Screenshot 2024-05-18 at 1 44 42 PM" src="https://github.com/arch-kiosk/arch-kiosk-office/assets/67970402/18f586fa-c174-4487-8860-e0c33cfe51fd">

**Comment by urapadmin** [comment]
that is very weird, indeed.
Can you remember that you did anything related to pottery? I suspect not, hm?

**Comment by luizaogs** [comment]
Nope.

**Comment by luizaogs** [comment]
Also maybe weird that I followed the same exact in PASU after the same update and did not get this.

**Comment by urapadmin** [comment]
> Also maybe weird that I followed the same exact in PASU after the same update and did not get this.

not that weird: PASU isn't using the pottery table because it is using an entirely different ceramics module. "pottery" is about warecode pottery, which must be what we are using in PVD.

**Comment by urapadmin** [comment]
but the error itself is very weird. I can confirm that there is a record in the pottery table in FileMaker that FileMaker itself has trouble to display:

![image](https://github.com/arch-kiosk/arch-kiosk-office/assets/38838314/b3f504d6-c334-4a75-b816-ad864fcef653)

The left side is the content of the pottery table in the database that was sent to the workstation, the right side is the table in the database that came back. So apparently a record got destroyed. Looks very much like FileMaker corrupting the file to me. Particularly because Luiza was not even near warecode pottery. Next I have to look into the template database.

**Comment by urapadmin** [comment]
pottery table looks fine in both the main postgreSQL database and the fork for Luiza's workstation.
Also, everything looks fine in the template. So the issue really happened in Luiza's file for the first time. 
Let's see what repairing the file leads to ...

**Comment by urapadmin** [comment]
Does not help. The foul record stays in place. That does not look like a corrupted file then.
Hm. No idea what caused this.

**Comment by urapadmin** [comment]
- prepared a different workstation on the basis of the existing default template and the import caused no issues. 
- The faulty pottery record belongs to collected material 810C, context 810 and trench PA. @luizaogs Do any of these ring a bell? For instance when you tested #2169 ? I am trying to find out which parts of the recording app you might have used in the session that lead to the faulty record.

**Comment by luizaogs** [comment]
Wait yes, I deleted 810 I believe because it was tagged with “sting” and I was testing that ticket. But I thought I deleted it after uploading the database … is 810 still there in the database you’re looking at?

**Comment by urapadmin** [comment]
no, it is gone

**Comment by urapadmin** [comment]
Let's see if I can reproduce this by deleting 810 after downloading...

**Comment by urapadmin** [comment]
does not happen. The record gets properly removed without a trace. But I do think that the accident must have happened during that operation because there should not have been any record at all after you deleted that locus. A bit worrisome that FileMaker blunders with a basic database operation like that. 
On what exact FileMaker version are you?

**Comment by urapadmin** [comment]
- that's not an entirely critical error, so I want to use this example to enable Kiosk to import this on second try using the safe mode we already have. Needs some coding in Kiosk ...

**Comment by luizaogs** [comment]
Sorry, got distracted by a cat. FM 19.6.3.

**Comment by luizaogs** [comment]
Is it possible that something went wrong because I uploaded a database and then while it was still uploading it I went in and did stuff in it? I do that all the time when there's a patch and it's never led to an error before, but I could swear I uploaded the file before deleting it. But maybe I'm just going crazy.

**Comment by urapadmin** [comment]
that sounds indeed dangerous. So you don't close the filemaker file before you are uploading it? Even that is dangerous and actually the browser should deny the attempt because the file is already open. So, ja, theoretically, if the timing is really bad and all, harm could come from that.

**Comment by luizaogs** [comment]
No, I close it. It starts uploading. And then I actually test stuff in it by reopening it.

**Comment by urapadmin** [comment]
Ah. Well. If the upload is slow and in progress and you manage to change things while it is going on, I suppose it can go wrong. IT depends on how FileMaker is actually working under the hood. I don't know exactly if it is working with the original file or in a copy of it until things get actually saved. However: You better let the upload finish before you reopen the file.

**Comment by urapadmin** [comment]
@lbestock I am adding your here just in case you follow the same practice. I think by and large it is a testing issue only. One gets tired of waiting ...

**Comment by urapadmin** [comment]
Might be worth mentioning in the Q&A, too?

**Comment by luizaogs** [comment]
I really do this all the time when there are patches in testing and have never had an issue, but yesterday I was using a hotspot and the upload was particularly slow so maybe that had something to do with it.

**Comment by luizaogs** [comment]
I can do the Q&A, but do you mean generally not using a file after uploading it? Would anyone do that in a field scenario?

**Comment by urapadmin** [comment]
### Kiosk 1.5.37
- That particular error now leads to the option to repeat the import in repair mode.
- Repair mode skips importing the record from that workstation, 
- A missing record would normally be interpreted by synchronization as a record that got deleted. However, in repair mode nothing ever gets deleted and so the record should prevail in untouched the master database.

**Comment by urapadmin** [comment]
So this is what one gets when Kiosk notices the issue on first import:
![image](https://github.com/arch-kiosk/arch-kiosk-office/assets/38838314/10085985-1eb6-4b51-8921-4d2521f99803)

After that one has access to the repair mode:
![image](https://github.com/arch-kiosk/arch-kiosk-office/assets/38838314/3925d4a3-d67c-4e67-be5f-4ce1503166bb)

That leads to something like this:
![image](https://github.com/arch-kiosk/arch-kiosk-office/assets/38838314/a9c5d76d-6453-4e11-b2c9-7b48d02f8304)

And here the same error is reported as a warning and would have led to a removal but the latter was skipped.

**Comment by urapadmin** [comment]
> I can do the Q&A, but do you mean generally not using a file after uploading it? Would anyone do that in a field scenario?

No, you can totally work in the file AFTER the upload has finished (normal users shouldn't because changes can't be uploaded again, but that's a different story). The problem here can be that two things are happening in the file at the same time when it is uploaded and manipulated simultaneously.

**Comment by luizaogs** [comment]
Yeah, that's what I meant - during the upload. Ok. I'll add something to that effect.

**Comment by urapadmin** [comment]
That was a good one. Quite enjoyed it.

**Comment by urapadmin** [comment]
> Yeah, that's what I meant - during the upload. Ok. I'll add something to that effect.

since you are on it, you might also want to mention the particular import error somewhere in the section where we explain the workstation's repair mode. I have added a few real-life screen shots above for illustration. One so rarely gets the chance to make a picture of these exotic beasts.

**Comment by luizaogs** [comment]
Hm. I can't find a mention of the repair mode in here?

**Comment by luizaogs** [comment]
Ah wait, there is this one: 

What if work was done in the wrong file. Is it really irretrievably lost, or can I override Kiosk and get those data in?

**Comment by luizaogs** [comment]
Ah and this: 

A file that was uploaded had an error or was refused for import. Why and what do I do?

Better there, I guess.

**Comment by urapadmin** [comment]
> Ah and this:
> 
> A file that was uploaded had an error or was refused for import. Why and what do I do?
> 
> Better there, I guess.

I agree, that sounds promising,

**Comment by luizaogs** [comment]
Done.
