### ISSUE TITLE
Kiosk: export to filemaker fails with cryptic message if a filemaker instance is open

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#2719]
There seems to be a difference between a FileMaker instance that already has the file open I am trying to open and an existing instance that has a different (or no) file open. The latter fails with a cryptic message nobody can understand.

**Comment by urapadmin** [comment]
### Kiosk 1.5.37.1
- the error message would now be "Attempt to use start_fm_database when there is still a connection to a different database open. Please close FileMaker first!" while for the old test of an instance that has the same file open it would be "Attempt to use start_fm_database when there is still a connection open. Please close FileMaker first!"
- This cannot be tested on Beset. But I tested it locally and it seems to work. The issue is: I hate changing code in these parts because they are ooooold and well tested at this point. My change might lead to side effects that I don't anticipate. So: This is under observation and every little issue with the export or in general with Kiosk exporting to or importing from FileMaker needs to be reported now. So please be vigilant and test if things work properly on Beset (E.g. by triggering workstation operations in two different projects).

**Comment by luizaogs** [comment]
Same here - did you want me to try workstations in two separate projects? Or just to leave it under observation?

**Comment by urapadmin** [comment]
It take this one over and test it on PASU local

**Comment by urapadmin** [comment]
Works on local pasu
