### ISSUE TITLE
MADP: Kiosk update request

### ISSUE THREAD

**Issue by luizaogs** [arch-kiosk/arch-kiosk-office#2720]
Maarten is working on the data from our last season by using Q&V but MADP seems to be in the Kiosk version where we can’t navigate to loci from the locus list in the unit view. Could you please update it for us?

**Comment by urapadmin** [comment]
of course.

**Comment by urapadmin** [comment]
voilá

**Comment by luizaogs** [comment]
Thank you.

**Comment by urapadmin** [comment]
I have also just updated the recording app for MADP because the versions need each other,
