### ISSUE TITLE
director's view: last line getting cut off in widgets

### ISSUE THREAD

**Issue by luizaogs** [arch-kiosk/arch-kiosk-office#2724]
Testing #2673 and I just realized that I have reached the end of the scroll bar in the CM widget but there is clearly at least a line of results getting cut off: 

<img width="649" alt="Screenshot 2024-05-25 at 8 40 57 AM" src="https://github.com/arch-kiosk/arch-kiosk-office/assets/67970402/e70d9026-025d-4559-8541-08427ee50ff3">

**Comment by luizaogs** [comment]
Ok actually, this is also the case in narratives and contexts.

**Comment by urapadmin** [comment]
Well, but you can scroll down to make it fully appear. I cannot control the height of this to a degree that it only shrinks and grows in full line heights. So as long as you can scroll down it is okay. That MacOS hides the scroll bars when they are not needed is Apple's design decision and this is an example that shows it isn't always helpful. 
I can live with this unless you can't scroll down to the hidden content.

**Comment by luizaogs** [comment]
I can't scroll down further and it remains cut off, that's why I thought it was an issue.

**Comment by urapadmin** [comment]
that would be an issue. Hm. I can't reproduce that at all here on the Mac let alone on Windows. Are you at 100% zoom level?

**Comment by luizaogs** [comment]
Yup.

**Comment by urapadmin** [comment]
sorry for the dumb question, but you have tried moving up/down with two fingers in the widget and no scroll bar appears?

**Comment by luizaogs** [comment]
This is what happens. You can see the scroll bar getting cut off, too. This is as far as it will let me go.

<img width="1512" alt="Screenshot 2024-05-26 at 9 34 45 AM" src="https://github.com/arch-kiosk/arch-kiosk-office/assets/67970402/c017a942-7767-4719-a9f6-2b31b802ef5c">

**Comment by urapadmin** [comment]
is it the same on your Safari?

**Comment by luizaogs** [comment]
No, Safari looks fine - I can scroll to the end and see the last line.

**Comment by urapadmin** [comment]
I love those Browser incompatibilities. Chrome on Windows fine, too. FireFox on Windows fine, too.
But I did manage to find a browser Size for Chrome where I can see it, too. Pff.

**Comment by luizaogs** [comment]
I always find the fun issues...

**Comment by urapadmin** [comment]
### Kiosk 1.5.38.5
Well, since you are the most active tester by far, it is kinda natural :o) 
- However, it is super weird and I had to change the layout strategy quite a bit for all of the widgets to get around it. So now I am waiting for the side effects. 
- There is also a strange blank space at the end of the files list at times which I have battled since I was on it.

I have rolled this out separately to PVD, so no lifted Kiosk Version in this case.

**Comment by luizaogs** [comment]
Do you mean that you already rolled it out? Because it looks good now.

**Comment by urapadmin** [comment]
yes, I just replaced the plugin. Too lazy to roll out a whole Kiosk.

You're sure? Try Safari, too, please. And an iPad.

**Comment by luizaogs** [comment]
Yes, just checked Safari and Chrome on both.

**Comment by urapadmin** [comment]
yippieh
