### ISSUE TITLE
PASU/KAMBE: darker/lighter shades of bg-colors are not showing in query and view

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#2727]
I suspect they have not been defined in the color scheme. This is in PASU and I believe PASU is using the same color scheme as KAMBE?

This is important so that the field boundaries of a field are visible in a View

**Comment by urapadmin** [comment]
I just rolled out the updated colour scheme for PASU on Beset. But you'll have to refresh your cache again before it gets activated.

**Comment by luizaogs** [comment]
Ah yes, much better. But this can't be closed because you still need to do KAMBE, yes?

**Comment by urapadmin** [comment]
I have attended to KAMBE and made sure it works.
