### ISSUE TITLE
kiosk: insecure download in chrome

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#2733]
We encountered that on MacOS:
after downloading from a local server Chrome gives a security warning that the download was from an insecure source. 
All http connections are regarded insecure and the Browsers fight it more and more aggressively. 

On MacOS and Windows you can click with on the little insecure or info icon in the address bar:

![image](https://github.com/arch-kiosk/arch-kiosk-office/assets/38838314/4632a81c-2b79-4ecf-b28e-88c8223fd19d)

choose "website settings" and then you get a loooong list of things you can allow or not allow.
find "insecure content" or so and select "allow":
![image](https://github.com/arch-kiosk/arch-kiosk-office/assets/38838314/512093d2-418c-4d05-9cdd-eec2b81a8497)

After that your downloads should be fine.

**Comment by urapadmin** [comment]
needs English screenshots, I suppose ...

**Comment by urapadmin** [comment]
one day we have to switch to https on our local network. That's so annoying because it makes running the Kiosk server so much harder ....: #2734.

**Comment by urapadmin** [comment]
This here can be closed as soon as the Q&A are updated.

**Comment by lbestock** [comment]
In English, on Mac this looks like this:
![image](https://github.com/arch-kiosk/arch-kiosk-office/assets/49291909/5811cf52-0b10-4c19-98cf-a1c633e3f4a6)

![image](https://github.com/arch-kiosk/arch-kiosk-office/assets/49291909/0ce6c717-7dd7-49d6-a23b-28461834835e)

So it doesn't even download until you tell it it's OK.

**Comment by lbestock** [comment]
![image](https://github.com/arch-kiosk/arch-kiosk-office/assets/49291909/fffc9534-5fa1-4689-a141-1840b16dc2e1)

And here how to solve it more than once.

**Comment by lbestock** [comment]
AND updated in the Q&A.
