### ISSUE TITLE
q&v: empty lots field in records with no lots (eg PASU)

### ISSUE THREAD

**Issue by luizaogs** [arch-kiosk/arch-kiosk-office#2735]
Somewhat related but not opening a ticket yet because I don't know if it's a problem: if a project doesn't use lots, should the field show up in Q&V? I just noticed a blank lot field when testing this in PASU: 

<img width="1512" alt="Screenshot 2024-05-27 at 2 48 42 PM" src="https://github.com/arch-kiosk/arch-kiosk-office/assets/67970402/e32b5625-974f-41dd-b3a4-c886476348f4">

_Originally posted by @luizaogs in https://github.com/arch-kiosk/arch-kiosk-office/issues/2381#issuecomment-2134078059_

**Comment by urapadmin** [comment]
### Koisk 1.5.39.2
- tackled. The lot field should only appear if there is actually a value in lot (which is never the case in lot-less projects)
