### ISSUE TITLE
Q&V terms for ceramic preprocessing not the same as in FM

### ISSUE THREAD

**Issue by lbestock** [arch-kiosk/arch-kiosk-office#2738]
Yet another configuration thing? This one I have my doubts about.
In PASU testing on the local server, in Q&V ceramic preprocessing. The two left columns are labeled "category 1" and "category 2". In FM for PASU these are configured as and render properly in FM as "functional category" and "component part". (This might get super confusing because in Q&V fragments for PASU there IS a correctly labeled "functional category". But that is not the same one.)

**Comment by urapadmin** [comment]
Tested on PaSU local
