### ISSUE TITLE
q&v: query with graphs for ceramics preprocessing

### ISSUE THREAD

**Issue by luizaogs** [arch-kiosk/arch-kiosk-office#2739]
> This looks good, and I don't have any trouble getting to quantity and weight totals from the CM. And I get the fragments right below, just as I would like. But...I do miss the graphs. We have them in Q&V for materials in general, and we have them in FM for preprocessing, but we don't have them in Q&V for preprocessing.

_Originally posted by @lbestock in https://github.com/arch-kiosk/arch-kiosk-office/issues/2381#issuecomment-2135867992_

**Comment by luizaogs** [comment]
I saw the need for a ticket and created it.

**Comment by urapadmin** [comment]
@lbestock  I am bit puzzled here. There is already a query "How much pottery has been found in each ceramic category" and it does come with all the charts. Did I do that after #2381? 
However, please look at it and tell me if that query is what you were missing.

**Comment by luizaogs** [comment]
I think you did that around the same time?

**Comment by luizaogs** [comment]
Can I get this out of testing? Or is there anything to do?

**Comment by urapadmin** [comment]
I should think this could be closed if the need for the actual graphs is met. Is it?

**Comment by luizaogs** [comment]
I don't know.

**Comment by lbestock** [comment]
Broken! Needs #2776 before I can answer.
