### ISSUE TITLE
project management to do for Laurel before CA

### ISSUE THREAD

**Issue by lbestock** [arch-kiosk/arch-kiosk-office#2740]
- [ ] configure MHT
- [ ] test MHT config
- [x] configure IBASA
- [x] test IBASA config
- [x] touch base with Alyssa about setting up Bridge and iPad - was going to be in person, cannot be
- [ ] finish updating Q&A - look at the release notes AND USERS MANUAL TICKETS to make sure everything new and relevant to field seasons is in there
- [ ] load the updated Q&A to the website
- [ ] should the Q&A be in Kiosk itself somehow? So you don't have to have the internet to get it?
- [x] finish the SCRIBE ad

**Comment by urapadmin** [comment]
can we close this now that you are in CA?

**Comment by lbestock** [comment]
Well, we didn't finish the stuff. The SCRIBE ad is not off. You did Q&A stuff, but the big piece I hadn't tackled was HM stuff. I haven't touched MHT.

**Comment by lbestock** [comment]
I will send that SCRIBE ad today or jump off a bridge, rather than make a new ticket for that.

**Comment by lbestock** [comment]
Sent.
