### ISSUE TITLE
Q&V: registration status in text, not code

### ISSUE THREAD

**Issue by lbestock** [arch-kiosk/arch-kiosk-office#2741]
Since we have moved much more to using check boxes for registration workflow, and since Q&V will be used by team members who are not registrars, I think it would be helpful to have registration status there in text or in the graphic checkbox way. I know it will be a disruption to the layout. But even in URAP the to do and done codes really no longer tell me anything just as codes and hence are more confusing than helpful in view.

**Comment by urapadmin** [comment]
duplicate: #2736
