### ISSUE TITLE
Update IBASA to latest recording app

### ISSUE THREAD

**Issue by lbestock** [arch-kiosk/arch-kiosk-office#2744]
The production release ticket says all field projects are updated to recording 15.20, but IBASA is still on 15.19 and you almost got a reopened QR code ticket because of that, and that ticket already made you want to scream. (Check MHT, too - I haven't started configuring that one yet but plan to today.)

**Comment by urapadmin** [comment]
almost all recording apps still need to be upgraded to the latest version.

**Comment by urapadmin** [comment]
done for ibasa, mht coming next ...
