### ISSUE TITLE
feature of the month updates

### ISSUE THREAD

**Issue by lbestock** [arch-kiosk/arch-kiosk-office#2745]
The release notes are helpful.
But I suspect most projects that already use Kiosk are not aware of many of the features, and I wonder if doing a regular (but not too often, not really monthly, maybe quarterly) message to users highlighting a feature they might not know about or use to its fullest would be good. It could also be a thing on the website so you get a popup feature of the month greeting you. I just had the idea about inventory, as I'm going through the Q&A. Who uses it? But a query that more or less spit out a shopping list would be so useful, and the capability is there.

A project of the month would also be an idea, reminding users that there are lots of other users and they should feel encouraged to spread the word. But that would need users to supply information and photos and might not be feasible.

**Comment by lbestock** [comment]
The image of you would have to be one of the slides in the slide show at least. That's a good idea. No text needed, more dynamic, the very variety of places would be evident. 

I agree about not spamming people. I don't know how to find the balance between not being annoyingly intrusive and communicating that there are hidden depths to this product. The idea of doing it in Kiosk itself is appealing; users go there, whereas I don't know that they go to the website much at all. I was thinking slightly in the face, so not a "tips" section in the hamburger menu but a popup on login with a "did you know Kiosk can X?" But I know from Adobe that this can indeed be super annoying and intrusive and thus counterproductive.

**Comment by urapadmin** [comment]
we won't be able to maintain this, so I close this
