### ISSUE TITLE
test: check and synchronize patches

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#2747]
I am rolling out recording app 15.20.3. Because it contains a patch I want to make sure that it gets synchronized back in. So please check if the new version is working (it is enough to just see the patch message and correct version) for these projects and synchronize the patch back in:

- [x] khpp  (LK)
- [x] pasu (LK)
- [ ] ustp (LK)
- [ ] elri (LK)
- [x] aac (LK)
- [x] mht (LK)
- [x] ibasa (LK)
- [x] madp
- [x] mkap
- [x] pacha
- [ ] arch1900
- [x] kambe
- [x] buap
- [x] urap

**Comment by urapadmin** [comment]
> I can do the others later today (though Lutz, it looks like you want to do USTP and ELRI?).

yes. Everything marked as LK is for me.

**Comment by luizaogs** [comment]
The arch1900 password is not in the wiki so I can't do that one.

**Comment by luizaogs** [comment]
For KAMBE, I'm trying to use the admin password in the wiki to login because I don't have privileges to synchronize but that's not working. Is the password in the wiki wrong? Anyway, if you can go in and synchronize KAMBE that's fine too.

**Comment by luizaogs** [comment]
URAP just needs to be synchronized now -- see #2750

**Comment by luizaogs** [comment]
Ok, URAP synchronized and KAMBE needs synchronization still.

**Comment by urapadmin** [comment]
yes, KAMBE had admin as password. Not okay. I changed it to what it should be. And I have synchronized it.
