### ISSUE TITLE
kiosk: MCP error

### ISSUE THREAD

**Issue by luizaogs** [arch-kiosk/arch-kiosk-office#2748]
Testing #2747 and I got the error below, so I guess I'll wait to try and synchronize the other patches:

<img width="1512" alt="Screenshot 2024-05-30 at 12 50 11 PM" src="https://github.com/arch-kiosk/arch-kiosk-office/assets/67970402/573ff4e7-507c-4b81-840a-0f28e36ddcc2">

**Comment by urapadmin** [comment]
I suspect that's just a hiccup

**Comment by urapadmin** [comment]
actually three hiccups on a day with much going on on Beset. Until we see it on a local server or it reoccurs on Beset over several days, I ignore it.

See #
