### ISSUE TITLE
recording app: Warning if admin

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#2749]
I think the recording app should warn users if they are logged in as admin and record data.
I am not sure what the best place and way for such a warning would be.

But I have seen too many examples where users have not logged out before they recorded data

**Comment by urapadmin** [comment]
@arch-kiosk/test any suggestions?

**Comment by lbestock** [comment]
Yes. It could really be triggered the moment someone leaves the start page tabs, no? Any time one hits any of the five buttons (five if one is a registrar) in the upper area. Even making units or site notes really shouldn't be done by someone logged in as admin.

I would like a popup saying "You are currently logged in as admin, which should only be used for configuration changes. Please log out and log in again as yourself to create records." And is it possible to have a button IN a popup that logs one out and reopens? Because that would increase compliance.

**Comment by luizaogs** [comment]
I second Laurel's suggestions.

**Comment by urapadmin** [comment]
### recording app 1.6.2
less trivial than it seems:
- if you are admin you'll get a popup warning with the option to log out and close, switch the user or go on as admin.
- you can also suppress that message for the current session (will be back after logout or switching a user) 
- it gets activated whenever you leave the start page to a different layout, except
- if that layout is an admin layout (I have only bothered to exclude the layouts admins are actually likely to use)
- as a side effect we also have a "switch user" now in the admin tab
- Just in case you find it: There is a glitch I accept: If you go create a new unit and you get the message and you choose to either log out or switch user, you are likely not be allowed out of the unit layout because information is missing. So the log out is interrupted. The problem: Now the admin reminder will not come back in this session.

**Comment by luizaogs** [comment]
This is also 15.22 then, yeah?

**Comment by luizaogs** [comment]
I currently see none of these things. There is no popup, no switch user button in the admin tab, etc.

**Comment by luizaogs** [comment]
And yes, I am in 15.22.

**Comment by urapadmin** [comment]
hm. I just downloaded your database. The switch user button doesn't appear, that is a developer mode issue. But I do get the reminder. It is timed, so it appears after a second or two. E.g. when you enter excavating or what have you. I am looking at it on Windows. Did you use an ipad?

**Comment by luizaogs** [comment]
Yes. I was even able to create a locus without getting anything, so I don’t think it was a timing issue on my end.

**Comment by urapadmin** [comment]
I cannot reproduce this on an ipad, either. I downloaded your dock from Kiosk, logged in as admin and then went to a unit and a second later the message pops up). I am on FM Go 20.3.1.31 and iOS 17.5.1.

**Comment by luizaogs** [comment]
I see it now. I don’t know what to tell you - it wasn’t there yesterday. The only difference is that today’s database is “old” so I get that message when I log in, too.

**Comment by urapadmin** [comment]
Ah. Well. That's a bit worrisome. There are theoretically ways to suppress that message, like with the accepted glitch I described above. So I wonder if you managed to trigger something like that that I did not forsee. 

The "old" message is normal simply because, well, it is unusually old for the field. I cannot see a connection there.

**Comment by luizaogs** [comment]
Yeah I know what that message is for. I just meant that it was the only difference I could think of from yesterday. 

I can't think of how I might have triggered a glitch. As far as I remember, I went straight to the unit and nothing showed up.

**Comment by urapadmin** [comment]
### recording app 15.22.1
- I tackled the button 
- Until we can reproduce the other thing, I can't think of anything to do about it.

**Comment by luizaogs** [comment]
The switch user button in admin is now there, however, and it works.

**Comment by urapadmin** [comment]
> Again, going straight from the start page to unit LA. I do not get a pop up. This is in 15.22.1. On my iPad.

and can you repeat it?

**Comment by luizaogs** [comment]
Yes, I still don't see any popups.

**Comment by urapadmin** [comment]
please describe the exact steps from starting the app to being in LA. Yesterday you did see the popup. There must be something that is different.

**Comment by urapadmin** [comment]
what if you go somewhere else from the start page, like Site Notes or site settings with the gear.

**Comment by luizaogs** [comment]
Steps:
1. Open the app.
2. Click on the trowel to go into LA. 

No pop up. This is the same thing I did yesterday.

**Comment by luizaogs** [comment]
Site notes does not give me a pop up. The gears do not either.

**Comment by luizaogs** [comment]
I know you think there is no correlation, but literally the only difference is that this is still not an old database and I am not seeing that warning when I log in.

**Comment by luizaogs** [comment]
Try downloading this version of the database, before it is "old," and see if you get the pop up. I don't know what else it could be.

**Comment by luizaogs** [comment]
I waited until the old warning showed up and, sure enough, the admin popup appears now.

**Comment by luizaogs** [comment]
Can you also get rid if the large X on the top left of the popup? It isn’t clickable and I assume users should use one of the three options to dismiss the popup anyway.

**Comment by urapadmin** [comment]
that must be the most ridiculous timing problem I have ever seen. I'll try to change the timing ,,,

**Comment by urapadmin** [comment]
### recording app 15.22.2
- changed the timing of that popup - just trying here
- deleted the superfluous button
