### ISSUE TITLE
kiosk: URAP synchronization issue

### ISSUE THREAD

**Issue by luizaogs** [arch-kiosk/arch-kiosk-office#2750]
Not sure if related to the other synchronization issue I had earlier today #2748 but it looks weirder so I'm opening a new ticket. 

The URAP synchronization was in the Initializing, please wait .... state seemingly forever. I tried leaving to the hub and coming back and the hub would just tell me that the synchronization was still in progress. A while later (I would guess 10 minutes?) I went back to check if it had actually started and I see this: 

<img width="1512" alt="Screenshot 2024-05-30 at 8 02 26 PM" src="https://github.com/arch-kiosk/arch-kiosk-office/assets/67970402/448cbc5d-2be9-474e-9b12-17587e437b56">

**Comment by urapadmin** [comment]
it was indeed another MCP failure. I had one, too. Strange but I keep ignoring it on Beset. Urap synxhronized now.
