### ISSUE TITLE
Add column for context description under the context tab?

### ISSUE THREAD

**Issue by cmrice-arch** [arch-kiosk/arch-kiosk-office#2751]
@urapadmin @lbestock -- is this where a request like this should go? Or somewhere more general as it could apply to multiple projects?

Is it possible to add a column with the context description to the context tab view? This would ideally be between context and type (see image). Space is perhaps a problem, but if there's a way around that, it would be great. 

<img width="923" alt="image" src="https://github.com/arch-kiosk/elri/assets/68063513/121ade00-798e-44d9-8d8d-3e9313d7421f">

**Is your feature request related to a problem? Please describe.**
It's frustrating to have to click through loads of individual contexts looking for a particular one that you just can't remember. I find this happens a lot when trying to add relations or the descriptions for new contexts. 

**Describe the solution you'd like**
A column that includes the description of each context.

**Comment by urapadmin** [comment]
Talked it over witg @lbestock. We'll give the two - line version a try first.

**Comment by urapadmin** [comment]
see also #1052

**Comment by urapadmin** [comment]
### Recording App 15.21
- The locus list has two lines now with the current fields stacked and the additional two-line description field using the rest of the space. We lose space that way, so the number of records in the view is smaller. Let us know if that's a bad trade-off for you.
- additionally you can now use the filter feature in the list to filter records by description. That might also help to identify a locus if you remember a word that is likely to appear in its description.
- I have opted against making the description sortable. Makes little actual sense.

**Comment by urapadmin** [comment]
this is rolled out to USTP as that is the next project.

**Comment by cmrice-arch** [comment]
Awesome. Thanks!

**Comment by luizaogs** [comment]
This is incredibly helpful.
