### ISSUE TITLE
Q&V: Maximize Charts

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#2752]
The charts don't have all that much space in query. A maximize button that uses the whole browser height might help with overlapping text and all.

**Comment by urapadmin** [comment]
### kiosk 1.6.1
- bit wonky perhaps, but it should do its job of maximizing the chart. Unfortunately in my tests that did not help all that much with overlapping labels in pie charts :(

**Comment by luizaogs** [comment]
Using my Mac. I currently can't scroll in the graph once it has been maximized, so the bottom of it is getting cut off.

**Comment by urapadmin** [comment]
### kiosk 1.6.1.1
- a fiddly case. Next try is better, I hope. 
- Don't try things like rotating your iPad or changing the window height and width. The view will not automatically adapt to it.

**Comment by urapadmin** [comment]
looks okay on Windows FireFox and Chrome. BUT: I had to tell both Browsers to clear the cache vigorously.

**Comment by luizaogs** [comment]
Looks good on both my Mac and iPad now (Chrome on the Mac and Safari on the iPad).
