### ISSUE TITLE
recording app: locus relations - selecting loci by number only

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#2757]
in USTP related loci are not necessarily in the same trench.
But because the locus number does not reveal to what trench it belongs, selecting that locus in the locus relations is a pain: One has to select the trench first to get to a locus.

It should be possible to simply type in a locus number in the cross-unit locus selector and get all the loci and their trenches that fit the pattern

**Comment by urapadmin** [comment]
@cmrice-arch @Tfranconi 
If this is something you feel a need for in the field this season, let me know. Might be worth sending you an update of the recording app.

**Comment by cmrice-arch** [comment]
Yes, if we could easily relate and equate contexts across trenches, that would be ideal. We're going to have a lot of cross-trench contexts this season as we're opening a final series of rooms in between previous trenches and they're going to share so many walls!

**Comment by urapadmin** [comment]
wow, I can't use my own software. 

This is already perfectly possible. All you need to do is clear the unit filter. Then you can search among all loci.

**Comment by urapadmin** [comment]
### recording app 1.6.2
to turn this blunder into something useful:
-  I have changed the default a bit: If there is no locus currently selected as "to trench" and you click on the selector next to unit to open the search popup the "unit" filter will not be populated with anything and the cursor stands in the search field
- the cursor will always be in the search field in general (although I am not entirely sure this is all that helpful on iPads). 
- searching in the search field happens while typing

**Comment by luizaogs** [comment]
You haven't released this, right? (sorry - a bit confused by the recording app update but Kiosk versioning?)

**Comment by urapadmin** [comment]
oh, ja. Well, you are for good reasons. No, it is not released yet and I fix the numbering.
