### ISSUE TITLE
kiosk: Tool to analyze the image load per trench / per record type / per year

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#2764]
Leaving out collected material for USTP didn't do all that much for the overall file size. 
A tool could help with estimating the distribution of file size among typical file picking categories lke

- unit
- record type
- date

That way applying file picking rules would be less of a tap in the dark

**Comment by urapadmin** [comment]
perhaps I can develop this before #2760 ?

**Comment by urapadmin** [comment]
what I really should do is use Query and View for this. Wow. It did not occur to me at first.
But then I ran into several Q&V issues with this that need to be solved first:
- #2766 
- #2765 
- #2769 
- #2768 
- #2767

**Comment by urapadmin** [comment]
### Kiosk 1.6.2.2
- the query "Image load distribution" is showing where to find the largest number of images so that they can be suppressed with file picking
- it has a pie chart "by unit", "by year", "by unit type" and "by record type"

**Comment by luizaogs** [comment]
The "image load by record type" graph has the record types with underscores that you tend to avoid, I believe: 

<img width="1449" alt="Screenshot 2024-06-21 at 3 16 36 PM" src="https://github.com/arch-kiosk/arch-kiosk-office/assets/67970402/d16e2726-9a89-4683-839f-d9fe6e0afd2a">

**Comment by urapadmin** [comment]
that is a general issue everywhere that needs a general solution. We can ignore it here and close this,

**Comment by luizaogs** [comment]
Do you need a new ticket for that then? I forgot to ask.

**Comment by urapadmin** [comment]
no, that's already covered by a ticket
