### ISSUE TITLE
timezone: IBASA digging in a time zone different from the server's

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#2774]
> with Alyssa's workstation set to GMT-5 (which is both Central, where she is now, and Peru) she was getting a "you're earlier than the server, we're giving you the experimental workaround" message. What? Can't have that.

That is correct. And can't be changed except with making Kiosk timezone aware (something we get farther and farther away from as we progress with new features). 

It is by design that the Kiosk Server and the iPads are in the same TimeZone while being in the field. 

The only thing I could do is to allow suppressing that message with a configuration key. The issue remains. We have not had any real issues anymore with this and @luizaogs is testing for quite a while now in time zones that are earlier than the server's. 

- see #2075 and #1184

**Comment by urapadmin** [comment]
- see also #2463
- but that should not be an issue here as long as Alyssa does not use Kiosk and the recording app at the same time to manipulate data

**Comment by urapadmin** [comment]
### recording app 15.22.3
- the new configuration key "admin/allow_earlier_local_timezone" can be set to "yup" to suppress the message for good. This synchronizes, though. So all device will finally be allowed to operate in an earlier time zone. 
- I have configured the IBASA users so that they don't have the privilege to modify data. That way #2463 cannot happen even incidentally.

**Comment by urapadmin** [comment]
I am reopening this to review it again under the light of time zone support

**Comment by luizaogs** [comment]
Uh. Should this key still exist? I am not finding it under advanced config.

**Comment by urapadmin** [comment]
sorry, that was not about testing the specific solution, it is rather to test the underlying issue and even see if it is relevant at all. I reopened it rather for myself at first. Taking it out of "testing".

**Comment by urapadmin** [comment]
### recording app 16.2.4
- the setting is marked obsolete now and moved to the category "deprecated".
- it is still in use for projects that operate with a Kiosk that does not support time zones
- as soon as the recording app is operating with a Kiosk with time zone support this is indeed obsolete. The server's time zone plays no role anymore.

**Comment by luizaogs** [comment]
The first bullet point is fine, but if you want the other two tested I need this to be released for another project.

**Comment by luizaogs** [comment]
Should I use RuBab to test this?

**Comment by urapadmin** [comment]
that is actually a good idea. I make you a user.
@lbestock adding your so that you know you're not the only one on rubab

**Comment by urapadmin** [comment]
logs user created - no password on first login. I have made you an operator for now as I would rather have you test this as a "normal" user without extended privileges of any sort.

**Comment by luizaogs** [comment]
Should it be set as yup or nope for RuBab? I have to synchronize to test it so wanted to leave it with the correct configuration.

**Comment by luizaogs** [comment]
Actually never mind, I'll leave it as nope to avoid confusion when configuring things for them. But this is working fine.

**Comment by urapadmin** [comment]
yes, that is the setting I would prefer.
