### ISSUE TITLE
website: testimonials and citations page

### ISSUE THREAD

**Issue by lbestock** [arch-kiosk/arch-kiosk-office#2780]
Need to solicit testimonials and citation information from projects. At the end of the summer season would be a good time to remind users to cite us in their publications, and to send us citations that mention Kiosk as we put them up on our website.

Testimonials to solicit specifically:

- [x] Liza and Leah, ARCH 1900
- [ ] Candace, three seasons Vacone and then lightening fast creation of two new Kiosks (not sure we want to advertise the fastness of the latter, though)
- [ ] add the MADP testimonial, below

**Comment by luizaogs** [comment]
If you want one from a project primarily focused on a different type of recording, I can ask my friend Guilherme to send one (he was the one doing the recording of individual limestone blocks and walls with me, and this was also his first ever experience in the field and Kiosk helped him learn the types of information that we need to record).

**Comment by lbestock** [comment]
We want it all!

**Comment by luizaogs** [comment]
Ok, he says he will send me something soonish.

**Comment by luizaogs** [comment]
As a first-time member of an archaeological project, I initially had concerns about how quickly I could familiarize myself with the complexities of archaeological recording. However, using Kiosk significantly eased the learning process. The software proved to be extremely helpful, intuitive, and user-friendly, which was particularly valuable given the extensive number of blocks we had to measure on-site! I highly recommend Kiosk as both an educational and recording tool for any archaeological team.

Guilherme Borges Pires
PhD Candidate and Researcher at CHAM (FCSH/NOVA)
Member of the Mastaba of Akhmerutnisut Documentation Project (MAD-P)

**Comment by urapadmin** [comment]
we can use those on presentations etc. I have dropped them from the website for now. Lack of maintenance.
