### ISSUE TITLE
arch1900: Thumbnail creation fails for a bunch of images in MB10 because of EXIF issues

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#2788]
exporting a workstation for AJM shows the issue

**Comment by urapadmin** [comment]
refreshing the thumbnails did not help

**Comment by urapadmin** [comment]
@lrn5 Just so that you know, there are a bunch of images in the old MB units that don't get processed properly and hence have no thumbnails (in which case one sees a strange tentaculair icon in the file repository instead of the image). Should you encounter something like that in the current site, please let me know.

**Comment by lrn5** [comment]
Thanks for the heads up!

**Comment by urapadmin** [comment]
The synchronization log reports a ton of those errors because of the files that cannot be turned into thumbnails:
![image](https://github.com/user-attachments/assets/fcdf8acb-5299-4991-a816-c34d790ffb0f)

Couple things to find out here: 

- [x] don't let a problematic EXIF record screw up the thumbnails
- [x] figure out why these particular images have problematic EXIF records in the first place. 
- [ ] don't allow the log to get populated with messages longer than let's say 240 bytes or so.

**Comment by lrn5** [comment]
Hi Lutz,
I’m not sure I follow what the problem is, but we also haven’t tried to synchronize data yet from this year.

**Comment by urapadmin** [comment]
You don't need to follow this thread, I just gather all evidence and data until finally, and that is when you come in again, I roll a bug fix out for you to test. So just ignore the GitHub emails you get for this until then. Just my gibberish. :o)

**Comment by urapadmin** [comment]
EXIF data can be read by third party tools, so there must be something amiss in our exif code. 
That's the EXIF data for '92437ea2-4b2e-44e0-bd15-f2edc8c34355':
![image](https://github.com/user-attachments/assets/f4de5e07-76e3-4f47-aa46-87d706a9e194)

**Comment by urapadmin** [comment]
### Kiosk 1.6.2.1
- fixed and rolled out to arch1900
- synchronization should not stumble over these issues any more in the future
- the missing image thumbnails in MB10 are there now in arch1900
