### ISSUE TITLE
Syncronization

### ISSUE THREAD

**Issue by maychu16** [arch-kiosk/arch-kiosk-office#2797]
This is my third or fourth time running into this issue. 
Sometimes when I refresh, I can see the syncronization progress bar but this time the page is just blank although I am told syncronization is running. 
I thought it might be because of my slow internet connection or the internet censorship here. In case it is not, I am uploading these to make sure everything is running the way they should be. 

After I logged out and logged in again, it does show me that the sycronization is finished. 

<img width="1512" alt="Screenshot 2024-08-17 at 10 47 16 PM" src="https://github.com/user-attachments/assets/a1524bc6-2237-483e-b04c-e5a65ec6fb3e">
<img width="1512" alt="Screenshot 2024-08-17 at 10 48 41 PM" src="https://github.com/user-attachments/assets/baf30802-8932-407d-afdb-de7e3859b3d0">
<img width="1507" alt="Screenshot 2024-08-17 at 10 48 53 PM" src="https://github.com/user-attachments/assets/8d9548a0-d2f8-48c6-b014-4b8d63a123fb">

**Comment by urapadmin** [comment]
ja, I have always wanted to look into that particular part again. It is a communication delay of some sort between server and browser. Harmless and so for you it is just one of those Kiosk  "hiccups". When you see the white screen or the "could not start an operation" thing, you might want to do a full browser refresh (F5 on Windows, and as usually I am not sure on Mac) Something like this button should work: 
![image](https://github.com/user-attachments/assets/c92601d9-e072-4de5-bebc-135ff5d8c710) )

Sometimes that does not do the trick and then it is likely that your log in isn't valid anymore. In that case logout / in again. 

The important info is: If you see the hint that a synchronization has finished successfully just recently , you can trust that it was okay. 
It is also only then that all workstations are back to "synchronized - needs preparation". 

But thanks for letting me know, it is very helpful for me to have a feeling of what kind of hiccup comes up more often. one gets used to them too easily ...

**Comment by maychu16** [comment]
Thank you for looking into this.
