### ISSUE TITLE
video tutorials: break out all the things that were in "new for 2023" as their own mini videos

### ISSUE THREAD

**Issue by lbestock** [arch-kiosk/arch-kiosk-office#2798]
Some features that were new in 2023 have no other effective documentation than in the video for "new in 2023". We just discovered this with the links between narratives/dayplans, a killer feature if ever there was one. I think the tiny segments were pretty great and could be their own little videos, but ugh they presumably need intros and outros then...

Needs watching and then extracting a list from what is there, first off, and seeing which pieces have already been addressed more thoroughly and where.

Videos from all the new features from 2023.
(make a list here...)

Users manual write-ups for all the features
(make a list here...)

- [x] #2799

**Comment by urapadmin** [comment]
this is not a good idea for a list. We have many of them and they usually just vanish from existence. I rather make this a ticket for the need of a video tutorial.

**Comment by urapadmin** [comment]
or do you actually think that just cutting that part out is enough? They were rather meant to let people know that features exist and not necessarily how they work or what to use them for.

**Comment by lbestock** [comment]
No I just watched it again. At first I thought it would work to just cut the pieces out. But I think not now; they want proper documentation. I was a little shocked to find that there was no good explanation of how to do the links.

**Comment by urapadmin** [comment]
So, if you ask me from the perspective of what we can possibly maintain: Let's close your list and open a tutorial ticket whenever a user wants one or we want one.

**Comment by lbestock** [comment]
Which you have done. Yes.

**Comment by urapadmin** [comment]
we also still have more or less nothing on the new 2024 features. Not even an overview :o( But now 2024 is over.

**Comment by lbestock** [comment]
Yet I DID write Harris Matrices into the manual. So coherent.
