### ISSUE TITLE
tz-combo-box: not focusable and hitting ESC or RETURN must not bubble

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#2805]
- [ ] when giving a koisk-tz-combo-box a tabindex it becomes focusable BUT the outer element gets the focus, not the Vaadin combobox. 
- [x] hitting ESC or RETURN must not bubble, otherwise outer popups close

**Comment by urapadmin** [comment]
- the focus is not really an issue (a second tab leads to the inner Vaadin combo and I don't want to lose too much life time on such a detail). More important is the ESC / RETURN issue

**Comment by urapadmin** [comment]
### kiosk 1.6.6
- ESC and RETURN/Enter don't propagate anymore. 
- So when being in the time zone setting dialog hitting ESC or Enter won't close the popup anymore.

**Comment by luizaogs** [comment]
Does this refer to the timezone menu in the user profile? If so, hitting return on my Mac did close the popup.

**Comment by urapadmin** [comment]
there it is actually okay. This is referring to the dock settings (same ad creating a dock) rather.

**Comment by luizaogs** [comment]
Hitting return on my mac closes that, too.

**Comment by urapadmin** [comment]
perhaps I have to be more precise: Hitting enter when selecting from the drop down list mustn't close the dialog but only the drop down list. Same with ESC. When the drop down is closed Enter might close the dialog if that is what also happens when you press Enter on some other field.
