### ISSUE TITLE
kiosk/recording app: make an earthworm button

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#2815]
As there are no camel spiders in Providence, we need an earthworm button.
It was requested by arch1900 a long time ago and this year it'll happen.

**Comment by urapadmin** [comment]
### recording app 16
- lots of configuration keys for the spider button: It has its own category now in admin.
- first of all: without any settings everything should be as it was: Spider button shows dancing spider

- these are the config keys: 
  - spider_counter_animation_frames: needs to be 2 for the spider and 4 for the worm
  - spider_counter_fps: How often does the move a step per second? Usually 2
  - spider_counter_max_frames: After how many steps does the counter popup close? Usually 10, so we have a 5 second screen presence.
  - spider_counter_title: Not very important. Should be "spider counter" for spiders and "worm counter" for worms. 
  - spider_counter_type: "worm" shows the earth worm, otherwise it is the spider.

- I hope I updated all the spider buttons we have.

**Comment by urapadmin** [comment]
that is not a pertinent testing response :o) 
And I want my cow back. From your real number.  🐮 Or I make you a cow button.

**Comment by luizaogs** [comment]
I want a cow button.

I will try to test this later, if the hotel internet allows it.

**Comment by urapadmin** [comment]
Start a project in Ireland or so. Then you get a cow button and I come install it.

Meanwhile I have simply rolled this out to arch1900 - they can test it themselves. Enjoy your cows (or whatever wildlife is around you where ever you are) 🐐 🐄 🦌 🐫 🕷️ 🪱 🦟

**Comment by luizaogs** [comment]
Mostly 🐏

Ok, so no need to test this? I have a deep fear of worms so won’t complain in this case…

**Comment by urapadmin** [comment]
no, no worm testing for scoleciphobics. And you also need some rest before we get into something real: testing time zones. That'll make you feel faint without a worm involved , I promise.

**Comment by luizaogs** [comment]
😬

**Comment by lbestock** [comment]
The worm dances much less grossly than a praying mantis would. But it's still hidden behind a button that looks like a spider. You hit the spider, the worm dances, even with all the configuration keys correct.

**Comment by lbestock** [comment]
The button is correct in the menu. But not as visible in the narratives tab (which is where I usually count my gross spiders).

**Comment by urapadmin** [comment]
> The button is correct in the menu. But not as visible in the narratives tab (which is where I usually count my gross spiders).
the spider button moved to the menu years ago. That's where it lives now. Or do you miss it in a menu somewhere?

**Comment by lbestock** [comment]
But it is still visible and pressable in the narratives tab, which I like. And in ARCH1900, while it's a worm button in the menu, in the narratives tab it is still a spider button that, when pressed, leads to a worm dance.

**Comment by urapadmin** [comment]
ah, I did not know that it was even still there in the narratives tab. I'll check,

**Comment by urapadmin** [comment]
### recording 16.1.1
- those two complaints were one, right? At least I didn't see anything else wrong except for the button above the narratives. That's fixed.

**Comment by urapadmin** [comment]
@lrn5 slightly new version rolled out to arch1900 that has the new earthworm button on top of the narrative list. Will be active for all docks that get prepared from now on.

**Comment by lbestock** [comment]
> ### recording 16.1.1
> * those two complaints were one, right? At least I didn't see anything else wrong except for the button above the narratives. That's fixed.

Yup, those two were one.

**Comment by luizaogs** [comment]
This is working now. This worm doesn't scare me :) (Still gross though.)

**Comment by urapadmin** [comment]
It should be mentioned that Rose made it.

**Comment by luizaogs** [comment]
Well then I am glad I tested it. The dancing is pretty fantastic.
