### ISSUE TITLE
tz: don't allow the FM database to run on a system that is not in the expected time zone

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#2824]
with a time zoned Kiosk that is lethal for the image import: 

- I had set my user time zone to India. 
- When I prepared my dock, the fork time was set to 09:09: 23:40 Asia/Calcutta, which is UTC+5:30
- I opened that FileMaker database on my local system, which is on US/East Coast time, so UTC-4:00 on 09.IX 15:00
- I got the start message "This database has been prepared in the future (09.09.2024 23:40:04).  That suggests that the server or the local ipad are not set to the same date and time. It is also possible that the workstation in Kiosk has a wrong time zone setting"
- I added an image. The image got the time stamp 9.9. 15:05:31
- when FileMaker tried to export all modified images NONE was exported because my image was added BEFORE the for time 09:09: 23:40 Asia/Calcutta.
- Image broken

I had the idea to set the time that is pertinent for the image export on the client itself. Perhaps on first open. That way it would not have been an Asia/Calcutta time but a UTC-4 time. 
- when the server opens that FileMaker file to trigger exporting all images FM would compare the UTC-4 image time with the UTC-4 modified time stamp and export the correct images
- BUT it could happen that images get exported that were no modified after that local time.
- all the dates are misinterpreted when the data gets imported again. 

SO: NO! Under no circumstances, not even for the admin, is it allowed to operate a dock in the wrong time zone. Only developers are allowed to do that.

**Comment by urapadmin** [comment]
### recording 16.1.2
- that should not be possible anymore for Kiosk's with time zone support
- 16.1.2 should behave normally on Kiosk's without time zone support. Meaning: If you mess with time zones, like being in a different one than the server or different from your Kiosk's GMT setting you should be let in as admin and you get the familiar messages. (that's why I roll this out to PVD now).

**Comment by luizaogs** [comment]
Is the test here that I should no longer be able to see the "This database has been prepared in the future (09.09.2024 23:40:04). That suggests that the server or the local ipad are not set to the same date and time. It is also possible that the workstation in Kiosk has a wrong time zone setting" message? Sorry, a bit confused.

**Comment by urapadmin** [comment]
the first test here on the current Kiosk version is making sure that time zone related messages in FM appear as they  always have because this version will be used on both Kiosk's with tz support and older versions without

**Comment by urapadmin** [comment]
changed my roll out message. Was confusing, indeed. FM should behave exactly the way you are used to on start-up

**Comment by luizaogs** [comment]
Hm, no. I get this, which I've never seen before: 

<img width="815" alt="Screenshot 2024-09-11 at 10 59 21 PM" src="https://github.com/user-attachments/assets/d8fc121d-1840-4a70-b5cf-82f1258e3ed5">

**Comment by urapadmin** [comment]
welcome to the new restrictive time zone message. 
Just a bit early for you. I'll look into it.

**Comment by urapadmin** [comment]
### recording app 16.1.3
- I hope this works now for the current PVD

**Comment by luizaogs** [comment]
Looks normal now.
