### ISSUE TITLE
Kiosk/Recording: Issue logging in immediately after setting a new password

### ISSUE THREAD

**Issue by liviah848** [arch-kiosk/arch-kiosk-office#2833]
I was asked to create a password when logging in for the first time, which I did. When taken back to the home page and instructed to log in with the new password, I did so but encountered this error. 

<img width="1436" alt="Screenshot 2024-09-12 at 2 26 41 PM" src="https://github.com/user-attachments/assets/a6b6e599-f249-4756-a852-d9a999191855">

**Comment by lbestock** [comment]
I had set privileges at operator. Shouldn't that allow access to the hub, etc?

**Comment by lbestock** [comment]
Changing @liviah848 to admins gave her access, so possibly this was just me forgetting which setting to use?

**Comment by urapadmin** [comment]
there is a video tutorial on that: https://www.youtube.com/watch?v=0ZrynQF4Yn4

**Comment by urapadmin** [comment]
in order to have "operator" doing anything it needs to have privileges assigned. There are only admins and "class".
