### ISSUE TITLE
import stuck at 100% and not moving part 2

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#2835]
After uploading with no problem, the import of a BUAP workstation got stuck at 100% and never moved on.
![image](https://github.com/user-attachments/assets/e408f363-d430-44a7-9df4-1057ce9f42c3)
I got impatient and told it to synchronize anyway, and now THAT is stuck at initialization. So I suspect a server problem.

**Comment by liviah848** [comment]
Hello! I just wanted to ask if I can continue my work, or if I should wait. Please let me know if I can and should proceed!

**Comment by urapadmin** [comment]
unfortunately we have not heard anything from IT services and as long as you are on FileMaker 21 (and Brown does not offer FileMaker 20 for Macs anymore) it is safer to wait. That hurts. If we don't hear back from Brown on Monday, I'll supply you with a Macbook that has FileMaker 20 installed.

**Comment by liviah848** [comment]
I apologize for the frustrating situation, though I am glad to know that we have a plan B. Please keep me in the loop, and let me know if I can help with anything regarding this issue!

**Comment by urapadmin** [comment]
@liviah848: 
We have all we need now to get to the bottom of this. It seems more complex than just FileMaker 21. 
It has something to do with the specific two photos or the way they got into FileMaker

Can you describe to me 
- how you made those two photos (I know, it was your iPhone, but do you e.g. have the "live" photo option on when shooting a photo?)
- how you transported them to your Mac
- how you inserted them into FileMaker? Was it drag and drop, copy and paste or did you simply select the file from your computer with the FileMaker menu?

And please tell me
- what iOS version does the iPhone have that you used to make the two photos?
- on what MacOS version is your Mac?

**Comment by liviah848** [comment]
Sure! 
- the photos do not have the "live" photo enabled
- I transported them to my mac by airdropping them
- I inserted them into FileMaker with a drag and drop method
- I have an iphone 12 pro, and its iOS version is 17.6.1
- my mac is on MacOS 13.3.1 (a)

**Comment by urapadmin** [comment]
this is getting one of those baroque FileMaker issues. 
This is what it looks like:
- If I add the two images to the recording app using **FileMaker 21** and a **Mac** they won't get processed by a Kiosk using a Windows FileMaker 20 in the background (that's the scenario in which the error surfaced).
- If I add the exact same images to the recording app using a **Windows FileMaker 20** the images get processed just fine with a Kiosk using FileMaker 20 in the background.
- If I add the exact same images to the recording app using a **Windows FileMaker 21** the images get processed properly by a Kiosk using FileMaker 20 in the background. 
- If I add the exact same images to the recording app using a **Mac FileMaker 19** (I don't have a Mac 20) the images get processed properly by a Kiosk using FileMaker 20 in the background.

That's a bit crazy. The only combination that is NOT working is FM21 on Mac. I don't think the MacOS version is the issue here. My FM19 test works fine on Mac OS Sonoma 14.4.1 but my FM21 test fails on MacOS Sonoma 14.6.1. Livia ran into the issue using MacOS is 13.

I really don't know what is going on with these versions, let alone what exactly is so special about those particular two HEIC files. 
This needs more research.

The one thing that could help Livia is unfortunately still not available: OIT failed to provide FM20 for MacOS. I am hoping for tomorrow.

**Comment by urapadmin** [comment]
There we are. We should have a solution for @liviah848 :

- trash FileMaker 21 on your Mac first
- go Brown's Software Catalog and install FileMaker 20 instead. The missing link there has been repaired by OIT.

And now you can carry on. Since your last work is synchronized and I have already prepared your dock, you just download and go.

To be on the safe side I would ask you to just do a little bit at first (involving just 2 or 3 images) and then upload, import and synchronize (please ask if you need support for that). If that all works successfully prepare your dock again and download and then check if your latest images are actually there in FileMaker.

**Comment by liviah848** [comment]
I am glad we have reached a solution! My schedule today is a bit hectic, but tonight I can certainly trash FileMaker 21, download FileMaker 20, and then do a test run a few images. Thank you for helping me with this issue, which I am sure was a time commitment!

**Comment by urapadmin** [comment]
the last mystery is solved, too: The two images that caused trouble in this weird constellation were made with the High Efficiency setting on in iOS (That's in settings -> Camera -> Formats and it is on by default). Images taken with "Most Compatible" worked (they are simple JPEGs). 

But that's just for clarification. Kiosk is fine with the High Efficiency format and with FM20 on Mac I have not encountered any trouble again. However, if you want to be on the safest side, just switch to Most Compatible when scanning stuff for BUAP.

**Comment by urapadmin** [comment]
> I am glad we have reached a solution! My schedule today is a bit hectic, but tonight I can certainly trash FileMaker 21, download FileMaker 20, and then do a test run a few images. Thank you for helping me with this issue, which I am sure was a time commitment!

Don't worry. We much rather encounter such issues in Providence than with a team in Egypt where it would get so much harder to find out what's going on. With every such issue solved Kiosk gets a bit more stable. 

I just wished you had a smoother start with your Kiosk work 😏

**Comment by liviah848** [comment]
<img width="1439" alt="Screenshot 2024-09-17 at 2 54 10 PM" src="https://github.com/user-attachments/assets/fd8e1377-d102-4c59-8f06-0a89903afba6">
I apologize but I am still struggling to work with Kiosk. I opened the original file (the one that would not import) and made one change (just fixed a typo), but now I am unable for some reason to complete the upload? I am repeatedly met with this message. I apologize for prolonging this issue, it is possible I might have made an error on my part!

**Comment by liviah848** [comment]
Wait never mind it uploaded! I had to upload the second file I opened and then it worked.

**Comment by urapadmin** [comment]
hm. That sounds a bit ominous. 

The "there is no access to the action panel" is indeed usually a sign that your log in had expired. In that case the little blue link is the right thing to follow to get a fresh log in to Kiosk.

But I don't really understand what you mean with "file"? 
First of all you downloaded your dock from Kiosk again, right? And then worked in the newly downloaded FileMaker file. And then you tried to upload that one back to Kiosk, right?

**Comment by urapadmin** [comment]
I looked at the synchronization log and it reads as if you have made no real changes in your database. Just to make sure, let me quickly summarize the Kiosk worflow:
a) if your dock is in state "synchronized needs preparation" you prepare the dock until it shows "ready for download" or so.
b) You download a FileMaker File from the dock. That file must replace all other FileMaker databases you had used before on your computer.
c) you work in that just downloaded file for as long as you like until ...
d) you use log out and close in FileMaker and
e) upload that FileMaker File back to Kiosk.
f) when that has happened, you use "import" and finally from the main menu in Kiosk the "synchronize" option.
And then you start again with a). Once you uploaded and imported a FileMaker file to Kiosk you can as well delete the local file on your computer to make sure that you only work with the new file that your next download will provide you.

And always use Chrome! Safari has made trouble in the past.

**Comment by liviah848** [comment]
oh ok, thank you for the clarification! and I will make sure to use chrome!

**Comment by urapadmin** [comment]
I think we have clarified this issue by now, so I close this
