### ISSUE TITLE
recording app: Test FM GO 21 with PVD

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#2838]
- maybe this can shed some light on #2834 and the FM 21 issue

**Comment by urapadmin** [comment]
@arch-kiosk/test Should somebody want an adventure, download FM GO 21 and test some.

**Comment by luizaogs** [comment]
Can also do, but again you don’t want me to do that right now. I shall get to it soon!

**Comment by lbestock** [comment]
Adventure. Adventure with the caveat that I undertook it after quite a long day, as a sort of winding down.

I put in a small amount of data on FM Go 21. Uploaded and imported just fine as far as I could see. But synchronization failed. It said there as nothing to do as no workstation is in back_from_field. But there really should have been, so I will not touch this until you look at it. 

I made notes on what types of images I imported. Here is a screenshot from the recording app, where I took those notes.

![Image](https://github.com/user-attachments/assets/dd1dd9a9-6734-4087-a906-6916ae6d6a4b)

**Comment by urapadmin** [comment]
looks fine. You ran Synchonization in quick succession. I suspect you had the feeling it did not start at first and then started it again? 
The first synchronization log showed this:
![grafik](https://github.com/user-attachments/assets/fb4617bd-e141-436f-bcc8-5bf58fdaa19b)

**Comment by urapadmin** [comment]
- this does strike me to have similarities with what I observed on arch1900 today #2846. I will look if we have an MCP issue here. But that has nothing to do with FM21, so you may carry on here.

**Comment by luizaogs** [comment]
So images seem ok? Are we testing everything?

**Comment by urapadmin** [comment]
yes, a new FileMaker workstation can always come with new problems. 
So everything means just looking around a bit, add some relations, create a qr code, add some ceramics, use navigation .... Just to see if everything seems to be working.

**Comment by luizaogs** [comment]
I assume this is FM Go 2024? How dumb of them not to include the versions anymore.

**Comment by urapadmin** [comment]
yes, and you can always double check that you are using the right version with the little info button in "about" on the start page. That should show the version number

**Comment by luizaogs** [comment]
Was going to do a full test with relations and what have you but I have run into issues with images so I will let you know rather than continuing.

Tried to add two images to narratives from Photos in the iPad and neither of them seem to have actually entered FM - the image containers are empty (though I get a timestamp as if I added something) and they are also not in the gallery as far as I can tell, definitely not at the top once I sort by descending order, which is where I expected them to be.

![IMG_5814850B7900-1](https://github.com/user-attachments/assets/0b132375-d42e-4488-922e-1d5b82edb389)

**Comment by luizaogs** [comment]
These are the two images … they were already on my iPad so I didn’t have to airdrop or anything.

![IMG_1853](https://github.com/user-attachments/assets/f2652838-2d13-426d-9a76-1430b30ca7c8)
![IMG_1835](https://github.com/user-attachments/assets/fa35f51f-7421-4896-8b3d-4eaf686a0625)

**Comment by luizaogs** [comment]
A picture taken with the actual iPad works.

![IMG_0464](https://github.com/user-attachments/assets/ed7fe7c0-431f-4b9a-b630-c721a9e4a153)

**Comment by luizaogs** [comment]
Another one from the library after that does not. It’s really odd - for all of these that aren’t working, this was my process:

Create new dayplan container
Click on the image container and select Photos
Pick the photo and the menu disappears but nothing else happens, I don’t even see the timestamp
Then if I click outside the container I see the timestamp but no image

**Comment by urapadmin** [comment]
I really don't want image container issues 😱 
Do you still have FM20 on the same iPad? Please try if it behaves differently.

**Comment by urapadmin** [comment]
those two images have been shot with the same iPad? Just with the Apple Camera app?

**Comment by luizaogs** [comment]
No, the images were shot with my phone but transferred to the iPad through the Cloud so I didn't do any manual transferring. Let me see if FM20 has the same issue...

**Comment by luizaogs** [comment]
Ok, I know what the issue is. Because they were transferred through photo stream (iCloud) those images were not actually in my iPad library, they needed to be downloaded. I was not using wifi at the airport so they could not be downloaded then.

FM20 deals with this just fine: it downloads them from the Cloud and adds them to the image containers (now that I am on wifi properly). FM21, however, does not: it freezes and when I leave and come back the image is not there. 

Not sure how relevant this is: probably not very relevant for the field, at least, but for legacy data it could be. I will ignore it for now and proceed with testing the other stuff regarding FM21, but can open a separate ticket for this issue if you want me to.

**Comment by urapadmin** [comment]
good. I am glad. The last thing I ever want to touch again is FileMaker image containers. So this is just a result of the crazy half-working technology we all live with. If I weren't so lazy I would consider pulling a Thoreau.

**Comment by urapadmin** [comment]
ja, we totally ignore this issue. It is crazy Apple and crazy Claris mixed into one. There would not be anything I can possibly do about it. I suspect once you have made sure that the image is actually downloaded to your device the inserting works fine even in FM21.

Perhaps worth mentioning in the FAQ.

**Comment by luizaogs** [comment]
Tested (and if I don't open a ticket or say anything below, things are looking fine):

qr codes in different layouts
created new contexts with relations
added SU style ceramics
using navigation
used the image gallery

**Comment by luizaogs** [comment]
I think FM21 is fine. Anything else you want me to test?

**Comment by luizaogs** [comment]
> ja, we totally ignore this issue. It is crazy Apple and crazy Claris mixed into one. There would not be anything I can possibly do about it. I suspect once you have made sure that the image is actually downloaded to your device the inserting works fine even in FM21.
> 
> Perhaps worth mentioning in the FAQ.

Yes, if the image is downloaded it can be added to FM21.

**Comment by urapadmin** [comment]
the harris matrix in locus relations and 
are the charts there in ceramic preprocessing?

**Comment by luizaogs** [comment]
Harris Matrix looks fine. Yes, the charts are there in preprocessing.

**Comment by urapadmin** [comment]
then you may close this. I still find it too early to recommend FM GO 21 but we know at least that there is no basic trouble with it
