### ISSUE TITLE
recording app: Issue during file export should not block FileMaker on Beset

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#2840]
- This is coming out of #2834 
The issue there was that during the script that exports image files from the FileMaker database to the operating system something went wrong (the container file could not be exported) and FileMaker was showing that message on the screen with no user present to confirm it.

From my point of view this should fail the import and FileMaker should close properly.

Look at the ExportImages script.

**Comment by urapadmin** [comment]
I looked. FileMaker does not suppress that message even if Errors are to be caught. FileMaker is still full of nasty surprises. Known issue for years, nobody cares, as usual.

However, I found at least a hacky way of checking whether a file is likely to have that issue: Getting the MD5 attribute of the container fails for these images. 

The troublesome files are HEICs again. Apple must have invented something new that FileMaker 20 cannot export. FM21 can. But that is not the point of this ticket here.

**Comment by urapadmin** [comment]
### recording app 16.1.4
- the hacky way is implemented. Those files will still not be imported but at least FileMaker will not block all of Beset because of it.
- #2839 is an issue that follows this one here. It is just not as urgent.

**Comment by urapadmin** [comment]
### recording app 16.1.4
I tested if the particular issue is solved. It is. 
@arch-kiosk/test: Please test if adding / modifying images but also files that are not images still allows a successful import of the dock AND check that the files are in the file repository afterwards. So in fact just check if adding files to the recording app works out as it should.

**Comment by luizaogs** [comment]
Just checking: should the import here be HEICs, which seem to have caused the problem in the first place? Or should I just test importing whatever? (In terms of images, I mean, I know you also want other types of files)

**Comment by urapadmin** [comment]
all types of files. This is to make sure that recording images and whathaveyou works still normally. You may throw in a Heic, too, but that's not the point here (that part I have focussed on myself enough, I hope).

**Comment by luizaogs** [comment]
Import and synchronization worked, and my Word document got a tentaculaire. That seems proper?

**Comment by urapadmin** [comment]
yes, particuLarly if you can download that original file from the file repository.

**Comment by urapadmin** [comment]
🛌 ???

**Comment by luizaogs** [comment]
I can download it, yes. (And yes, I was going to bed :) )
