### ISSUE TITLE
tz: system messages in Kiosk don't work anymore after time zone support

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#2848]

**Comment by urapadmin** [comment]
that's fixed

**Comment by urapadmin** [comment]
### Kiosk 1.6.3
- system messages like "Master Control is not up" or the hint that Kiosk is using a general store with an Id etc. should work as usual (you should be able to close them and they should not reappear)
- as soon as you are logged in these messages should show the time stamp in terms of user time zone

**Comment by urapadmin** [comment]
@arch-kiosk/test 
I reopen this to move it to the new tz test column in the test project. 
All time zone related issues need some coordinated test with different time zones in mind. While it is fine and necessary to first test if something works at all (that's what the "single test" column is for) time zone related things cannot be closed until tested in an actual time zone scenario. Whatever that is depends on the issue at hand. But it needs some thinking and presumably some coordination between testers.

**Comment by luizaogs** [comment]
Ok, well, this is still working for me in my new timezone (I have now tested it in two different ones). So @lbestock let me know what you want to do in terms of coordinating here.

**Comment by luizaogs** [comment]
Actually, problem: I've now closed the General Store message several times and it keeps coming back.

**Comment by urapadmin** [comment]
as it should. It comes back whenever a new server process starts (happens all the time). 
What you should see is that the new message also has a new time. If you see a message coming back with the exact time of the one you closed you have found a bug.

**Comment by urapadmin** [comment]
I should have added that what complicates the issue slightly here is that "time" in this case means user time zone. (I think I should soon give you access to the documentation). user time zone is the time zone your browser reports, so currently it should be what your operating system is set to. But as long as you stay in the same time zone your test is as simple as described in the comment up there.

**Comment by luizaogs** [comment]
You said above that they should not reappear so I was confused.

Maybe a bug, then: it's now 11:09am but the message still says 10:43. Yes, I have refreshed the page. 

<img width="1512" alt="Screenshot 2024-09-23 at 11 09 45 AM" src="https://github.com/user-attachments/assets/c78d5c46-c461-4379-a8fb-e7f2458a9a7c">

**Comment by urapadmin** [comment]
and you are sure you closed 10:43 before? The time you see is the time when the message was generated by the server. 
There is one other complication here: When you are in the login page you see the messages and you can close them but that never lasts (I can't check if you have the privileges to close a message for good until you have logged on). So for this test you better stay logged in.

**Comment by luizaogs** [comment]
I'm logged in. No, I'm not sure. I'll close this one now and see.

**Comment by luizaogs** [comment]
The timestamp on the new message is correct, so nevermind.

**Comment by urapadmin** [comment]
- because of #2884 :
- [ ] the system messaging tables need "timestamptz" as datatype.
