### ISSUE TITLE
kiosk/tz: still layout issues with time zone and user id in the header

### ISSUE THREAD

**Issue by luizaogs** [arch-kiosk/arch-kiosk-office#2854]
Funny. I logged in and in the hub, under the little person icon on the top right, I'm now Central Europe. That really only shows up if I click on the icon, otherwise it's just a jumble of letters because I presume "Central Europe" is too long. 

And, yes, my user profile details are still correct.

<img width="134" alt="Screenshot 2024-09-20 at 8 24 04 AM" src="https://github.com/user-attachments/assets/e8114240-ade4-49d1-86c6-8853246b0ed7">

<img width="299" alt="Screenshot 2024-09-20 at 8 24 09 AM" src="https://github.com/user-attachments/assets/e284cb6e-36de-440b-9486-6fdc39a5f948">

<img width="209" alt="Screenshot 2024-09-20 at 8 24 15 AM" src="https://github.com/user-attachments/assets/20ddd99b-3983-45f1-b0c7-123a5ff2940c">

**Comment by urapadmin** [comment]
is that Safari or Chrome?

**Comment by luizaogs** [comment]
Chrome.

**Comment by urapadmin** [comment]
could you please violently refresh your cache and see if that changes anything?

**Comment by luizaogs** [comment]
Yes but the Krakow airport wifi apparently sucks so it will have to wait.

**Comment by luizaogs** [comment]
Uh wait, I haven't refreshed anything yet and Kiosk finally loaded and it looks ok...

<img width="116" alt="Screenshot 2024-09-20 at 8 01 15 PM" src="https://github.com/user-attachments/assets/3efab0d8-f631-4ddb-8027-9f8cb0992782">

**Comment by urapadmin** [comment]
That's what it is supposed to look like. Could be that the new styles came in delayed if you are on a really slow network. Who knows. The internet is often a big mystery.

**Comment by luizaogs** [comment]
Well, I guess I close it and let you know if it shows up again?

**Comment by urapadmin** [comment]
on it
