### ISSUE TITLE
advertising Kiosk in email lists

### ISSUE THREAD

**Issue by luizaogs** [arch-kiosk/arch-kiosk-office#2859]
MADP presented about our season at the Current Research in Egyptology (CRE) conference last month (I wasn't there). We had a slide where we talked about Kiosk and how it helped with recording (and what it let us record and how), and I just heard yesterday that they got a lot of interest and questions about the software. The team told everyone who asked to look at the website and to get in touch. We haven't gotten any emails sent to the kiosk team address, however, so I think something is getting lost in translation.

I think sending a short blurb with the website link, telling people to contact us if they want Kiosk, to a few field-specific email lists (EEF, ASOR, Agade) could be really useful. I would be happy to write a blurb and send it, but for that I don't know if the website needs updating. 

I've also told Laurel that we should ask ARCE to send it to their list.

**Comment by urapadmin** [comment]
@lbestock yours

**Comment by lbestock** [comment]
Thank you for returning it to the top of my messbox. 
@luizaogs Yes. Do this. Please. The website isn't ideal. But it exists, and waiting for it to get updated would be missing an opportunity.

**Comment by luizaogs** [comment]
A first attempt at a blurb. It might be too long. I'll wait for your thoughts before I send it off. 

"Do you have a field project? Are you looking for a more efficient way to gather your data and analyze it for publication?

Kiosk is an integrated iPad recording platform and browser-based data manager for field archaeology. It is currently used in the recording of excavation data in projects from Egypt to Sardinia and Cyprus, in surveys in Sudan and Peru, and to facilitate tomb documentation in Egypt. Beyond allowing for the recording and integration of data while in the field (from field journals and photographs, to unit and context information and the automatic rendering of Harris Matrices), it also enables the analysis of data for publication (by allowing users to easily query, as well as easily search through, their data online post-season). 

Kiosk is available and free to anyone who wishes to use it, and is suitable for everything from a one-summer survey project run by a graduate student, to a field school, to an ongoing legacy excavation with decades of old data to digitize.

Find out more about Kiosk and its capabilities on our [website](https://sites.brown.edu/kiosk/), and get in touch with us at kiosk-team@brown.edu!"

**Comment by lbestock** [comment]
I would bold "free" since it comes so late! And will definitely be important. And I might add "Kiosk is **free**, including tech support for customization and while in the field. It is suitable..."

This sentence is too complicated and wants simplifying I think, but my brain is mushed by boring job applications and I am having trouble editing it. I think chopping the second parenthetical out would help?

"Beyond allowing for the recording and integration of data while in the field (from field journals and photographs, to unit and context information and the automatic rendering of Harris Matrices), it also enables the analysis of data for publication (by allowing users to easily query, as well as easily search through, their data online post-season)."

Something about object management? Should we add that? No. I think it's a super helpful part of the package, but the point of this message is to remind people they have heard of this and get them to email for more details.

Use the logo in the message when you send it!!!
![kiosk logo](https://github.com/user-attachments/assets/82a4621f-8a59-44b4-9639-0011d0cddfae)

**Comment by lbestock** [comment]
Ok not that big on the logo, I just dropped the file there :)

**Comment by luizaogs** [comment]
I can also move the free and contact stuff to the top, but I wasn't sure how to fit it in.

**Comment by luizaogs** [comment]
Do you have a field project? Are you looking for a more efficient way to gather your data and analyze it for publication?

Kiosk is an integrated iPad recording platform and browser-based data manager for field archaeology. It is currently used in the recording of excavation data in projects from Egypt to Sardinia and Cyprus, in surveys in Sudan and Peru, and to facilitate tomb documentation in Egypt. It allows for the recording and integration of data while in the field, from field journals and photographs, to unit and context information and the automatic rendering of Harris Matrices, to object registration. Kiosk also enables the analysis of data for publication by allowing users to easily query, as well as easily search through, their data online post-season.

Kiosk is **free** to anyone who wishes to use it, including tech support for customization and while in the field. It is suitable for everything from a one-summer survey project run by a graduate student, to a field school, to an ongoing legacy excavation with decades of old data to digitize.

Find out more about Kiosk and its capabilities on our [website](https://sites.brown.edu/kiosk/), and get in touch with us at [kiosk-team@brown.edu](mailto:kiosk-team@brown.edu)!

![image](https://github.com/user-attachments/assets/1ba6d91f-4269-42f8-8da4-784f6998e334)

**Comment by luizaogs** [comment]
Yeah, I'll see if I can make the logo smaller. That's a giant spider. 

Instead of cutting the parenthetical I just made it two sentences, but can also just cut it if you prefer.

I also added a mention of object registration.

**Comment by luizaogs** [comment]
Oh and we also need a subject line that makes sense. Free field recording software? Kiosk: digital field recording? Kiosk: archaeological field recording and management? 

My brain is also mush.

**Comment by urapadmin** [comment]
call me nitpicky but could we please stick to the google drive for exchanging logos and files? That's where they live.

**Comment by lbestock** [comment]
OK logos are in the drive (materials_for_development - images).
Let's title the email: Kiosk: digital field recording for archaeology

And then yes, let's move "free" in bold to the first line of the second paragraph, "Kiosk is a free integrated iPad..."

**Comment by urapadmin** [comment]
I take issues with overemphasising the free. Sounds like throwing around free candy, which is usually the worst. 
"free and open source"? And not bold?

**Comment by lbestock** [comment]
Ha. A point. OK I agree, particularly with the inclusion of "open source".

**Comment by luizaogs** [comment]
Ok, so this? 

**Kiosk: digital field recording for archaeology**

Do you have a field project? Are you looking for a more efficient way to gather your data and analyze it for publication?

Kiosk is a free and open source integrated iPad recording platform and browser-based data manager for field archaeology. It is currently used in the recording of excavation data in projects from Egypt to Sardinia and Cyprus, in surveys in Sudan and Peru, and to facilitate tomb documentation in Egypt. It allows for the recording and integration of data while in the field, from field journals and photographs, to unit and context information and the automatic rendering of Harris Matrices, to object registration. Kiosk also enables the analysis of data for publication by allowing users to easily query, as well as easily search through, their data online post-season.

Kiosk is available to anyone who wishes to use it, including tech support for customization and while in the field. It is suitable for everything from a one-summer survey project run by a graduate student, to a field school, to an ongoing legacy excavation with decades of old data to digitize.

Find out more about Kiosk and its capabilities on our [website](https://sites.brown.edu/kiosk/), and get in touch with us at [kiosk-team@brown.edu](mailto:kiosk-team@brown.edu)!

**Comment by lbestock** [comment]
It looks good to me!

**Comment by urapadmin** [comment]
looks better than free candy to me

**Comment by luizaogs** [comment]
- [x] EEF
- [x] Agade
- [x] ARCE
- [x] ASOR

**Comment by luizaogs** [comment]
The EEF and Agade didn't include the logo. Grr. But they sent it out.
