### ISSUE TITLE
Kiosk: temp password did not work

### ISSUE THREAD

**Issue by lbestock** [arch-kiosk/arch-kiosk-office#2865]
Alyssa had forgotten her password, so I set it to reset and got the temporary one. That did not allow her to log in.

**Comment by lbestock** [comment]
Also: why don't I see users in the hamburger menu any longer? Logged in as myself, in admin, can't get to users. I set the password reset using the button on the landing page in the admin part (and @urapadmin I accidentally hit yours, first, so you should have a temp password too and I took a screenshot of that before it disappeared if you want to see this). I won't touch anything else there for the time being...

**Comment by urapadmin** [comment]
I think I have already recommended the video on privileges, haven't I? Same issue. You are a field worker and field workers are not allowed to tamper with user data. That's for admins. 
You can really bet that whenever you can't see something it is a matter of groups and privileges. Of course, you can only change your privileges when you are logged in as admin, But making everybody an admin is like giving everybody the same password. That's not good policy.

**Comment by urapadmin** [comment]
I have real trouble to believe that the temp password did not work. That part has never failed before. It is sometimes hard to write it down. I and 1 and other things can be confused and the "." is not part of the temporary password. 
What is the current state? Alyssa not able to log in?

**Comment by urapadmin** [comment]
ah, I see that her password is still to be changed. Alas, there is really nothing I can do without even having that password that does not work.

**Comment by lbestock** [comment]
Ja I really cannot schedule kiosk things for office hours, it is clear. That does not work for my head.
I didn't capture her temp password. She was not able to sign in.
But when I accidentally hit yours I got it:
![image](https://github.com/user-attachments/assets/412a9722-1369-4575-89ef-8c07d2e36c6c)

And now on to next kiosk meeting in office hours with Livia.

**Comment by urapadmin** [comment]
well, I can be zoomed and called now

**Comment by urapadmin** [comment]
mine worked fine and I was successfully able to set it back to my real one. So I go with disbelief until this happens again.

**Comment by urapadmin** [comment]
I don't believe this and it might have been an instance of #2867
