### ISSUE TITLE
Kiosk: import fails saying the file had not been opened, which is not the case

### ISSUE THREAD

**Issue by lbestock** [arch-kiosk/arch-kiosk-office#2866]
IBASA
downloaded laurel's mac to my iPad. 
saw an "update" synchronization message.
created a new user.
uploaded fine.
tried to import, got the error that the database had not been opened.
checked on the iPad that I had in fact exported from FM the correct file and had imported from the right place, and I had, so the error is wrong and it should accept the file for import.

not touching anything further.

**Comment by urapadmin** [comment]
that check is pretty foolproof by now. We have not seen issues with it for ages. I'll look into it.

**Comment by urapadmin** [comment]
hm. I looked into the file that was uploaded for ldbmac.
The user table shows 4 users and they all have an old modification date. To me this does look like an untouched file, indeed. Since the date of the file was from today, it clearly got uploaded. 
Did you use Bridge here?

**Comment by lbestock** [comment]
There should have been five users, the last created today. Maybe I did upload the wrong file? I don't see how, but a me error induced by apple file management is easier to believe in.

I did NOT use Bridge. 

I have to run (oh my god this day) so I won't even see if you want me to reexport from FM or use bridge or whatnot. Tonight.

**Comment by urapadmin** [comment]
yes, hand over that iPad
