### ISSUE TITLE
Kiosk: can the login be made case insensitive for user ID?

### ISSUE THREAD

**Issue by lbestock** [arch-kiosk/arch-kiosk-office#2867]
I suspect we've been through this and that the answer is no. But I ran into it again yesterday that people who have their iPads set to auto capitalize often have trouble logging in to Kiosk in the browser because they enter, for instance, Ldb instead of ldb. It would be great if either cases didn't matter or three variants could be recognized as all the same thing: Ldb, ldb, LDB.

**Comment by urapadmin** [comment]
If can try to switch autocapitalization and auto everything off for both the user id and password

my notes: 
`autocorrect="off" autocapitalize="none" autocomplete="off"`

**Comment by urapadmin** [comment]
### Kiosk 1.6.4.3
- did that. the login form and the user profile should not auto-capitalize in both the user id and the password at least on iOS. I am not sure about Android. This has not been standardized properly in Browsers.

**Comment by lbestock** [comment]
This is not released yet, right?

**Comment by urapadmin** [comment]
nope

**Comment by luizaogs** [comment]
Not working, I don't think. Just tried to use Test_logs and it didn't let me. TEST_LOGS doesn't work either.

**Comment by urapadmin** [comment]
that is also not what it is supposed to do!
Capitalization still matters. BUT the Auto-Capitalization feature of iOS (and Android) should be inactive on the login fields.

**Comment by luizaogs** [comment]
Ok. Since the result is the same I assumed it was the same thing. I'll try again.

**Comment by luizaogs** [comment]
Auto-capitalization is indeed not active. But above Laurel wanted LDB to also work - I guess that's not what you decided to do then?

**Comment by urapadmin** [comment]
correct, she is not granted her wish.

**Comment by urapadmin** [comment]
it is also really not the same thing! Particularly when it comes to passwords. xoiaDkfuB should be very different from XOIADKFUB as a psasword.

**Comment by luizaogs** [comment]
Well yes, but she wanted user ID and not password. Anyway, it's working as you want it to work.

**Comment by urapadmin** [comment]
but you have not checked Android, right?

**Comment by luizaogs** [comment]
I don't own Android. Someone else will have to do it then.

**Comment by urapadmin** [comment]
I will

**Comment by luizaogs** [comment]
I am moving this to your testing lane then, otherwise I'll keep seeing it and thinking I have to deal with it.

**Comment by urapadmin** [comment]
okay on Android
