### ISSUE TITLE
Recording app: no quality control for archivers

### ISSUE THREAD

**Issue by lbestock** [arch-kiosk/arch-kiosk-office#2868]
Mina is inputting legacy data for ARCH 1900.
We are missing LOTS of the documentation from earlier seasons of ARCH 1900.
Units are known from two of the three excavations.
None of the context sheets are had! so some of the context numbers and even descriptions are known from reports. FBC has a finds register and that includes context numbers. (Terminology changed between sites and even seasons, as did methods - JNBC went from contexts that were 10cm passes to contexts that were changed with observed differences in soil. Shoot me now.)

ARCH 1900 is of course configured for digging, and quality controls are tight because students are learning and need to be reminded to add all relevant data.

Most of the relevant data is missing entirely for the legacy data. In order to get what data IS there in, we need to turn QC off entirely for the legacy recording group. Is that possible? Can it be made possible, if not, please?

**Comment by urapadmin** [comment]
no, that is not possible, currently. QC rules are project-bound.
- The easiest would be to switch em off for a session via a button. 
- Or I could bind it to a group in the recording app itself, you know, like "registrar" or "tester". We would have a "archiver" or whatever. Perhaps that's a way?

**Comment by cmrice-arch** [comment]
Delightful... How much work would it be to create separate projects for the old sites? Having an "archiver" role seems workable. But is there a reason to keep them all together in the same project?

**Comment by urapadmin** [comment]
too much work, honestly. That's why we have sites. 
We would need sub-domains on Beset, Beset would have to run separate server processes etc. Not worth it.

**Comment by cmrice-arch** [comment]
Understood - makes sense!

**Comment by urapadmin** [comment]
### recording app 16.1.6
- there is a new role "archiver" that can be checked for a team member
- it deactivates quality control for this team member

**Comment by lbestock** [comment]
An elegant solution that will be useful in the long run. Which is helpful! But also: there are tons of context sheets from past College Hill seasons, though it's not yet clear if they are all there. There was in fact no need to delay inputting data and there will be no interference between current work and inputting legacy data.

**Comment by cmrice-arch** [comment]
Lutz for the win!!

**Comment by urapadmin** [comment]
@luizaogs would you like to test this?

**Comment by urapadmin** [comment]
> @luizaogs would you like to test this?

don't worry about it, I have tested it.

**Comment by luizaogs** [comment]
I was just about to close it...

**Comment by urapadmin** [comment]
### recording app 16.1.6 rolled out for arch1900
This is now available in arch1900 and I have made Mina an archiver. So Quality Control does not kick in anymore if she is logged in but still works for others (except for ldb, which is also an archiver in arch1900).

**Comment by urapadmin** [comment]
> I was just about to close it...

ha. It's bullet proof then :o)
