### ISSUE TITLE
show list of collected material per unit in the collected material tab

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#287]

**Comment by urapadmin** [comment]
currently we have to select a locus first and show the collected material of that locus

**Comment by urapadmin** [comment]
do we really want to do that?

**Comment by urapadmin** [comment]
yes. We want to. And we want filters and counters:
- by material 
- by locus
- anything else?

**Comment by urapadmin** [comment]
see #1498

**Comment by urapadmin** [comment]
adding a collected material right there won't be possible anymore, though,

**Comment by urapadmin** [comment]
### @test recording 12.4
- cm list in full excavation shows the list of cm per unit now
- filter by material and type are possible. 
- resulting rows are counted in the upper left corner
- the filter by type is the same as in the locus cm list. So if set in one of them it will be active in the other, too.

**Comment by luizaogs** [comment]
I'm not getting the resulting rows? 

<img width="1021" alt="Screen Shot 2022-04-05 at 7 58 11 AM" src="https://user-images.githubusercontent.com/67970402/161758842-e3c7eb8a-9c39-4ecb-91f5-5b8a0e23f487.png">

**Comment by luizaogs** [comment]
Lastly this SU number gets cut off but I don't know if that's because it's SU + a PVD identifier and that's why it's too long, so this might just be a test case that won't happen in real life.

<img width="920" alt="Screen Shot 2022-04-05 at 8 03 04 AM" src="https://user-images.githubusercontent.com/67970402/161759796-a5cfbd90-46f0-4df2-b372-783a8c5cda1b.png">

**Comment by urapadmin** [comment]
Some identifiers are just trouble. We really need to get to test the numbers of those upcoming field projects - some of them will cause problems. Here in the list I have now eliminated the lot as its own column and append it to the identifier. That way there is a lot more room for the identifier.

- The lot should only be mentioned in the heading if use_lots is on
- the "/" only appears if there is actually a lot

**Comment by luizaogs** [comment]
So use lots is off and "lot" does indeed not show up in the header, but should it still show up in the list itself after the identifier? If yes this is all working.

**Comment by urapadmin** [comment]
yes, that is okay.
