### ISSUE TITLE
users manual: legacy data input

### ISSUE THREAD

**Issue by lbestock** [arch-kiosk/arch-kiosk-office#2872]
There are enough things about settings and workflow that are different between ordinary field data creation and inputting legacy data that we should write a section of the manual specific to legacy data. 

These include "archiver" user status, temporary free input, image inputting. The ability to bring in previous databases and even our ANC object database auto link could be discussed as a possible thing, though that will be bespoke by project and so maybe we don't want to advertise it. But I was really struck in Krakow, and we're now dealing with both ARCH1900 and BUAP legacy and we had real issues with URAP since that wasn't even contextual data, that there are very few current excavations that don't also have legacy data. So this would be handy right now, but also in future.

**Comment by lbestock** [comment]
Mina has just had the trouble of needing temporary free input to change unit names while inputting legacy data. The solution here is two-fold. First, use the extant instructions in the admins manual to change the units already named. Then, as admin, change the ID methods for those units themselves so that other numbers aren't auto-generated. Critical for the legacy data user's manual will be what to do when you're simultaneously inputting old data and digging. Turning quality control off for "archivers" was part of that. There must be a better way to do numbering some things by free input and some without. It's too much to ask the legacy data inputters to mess around with configuration itself, which is what I'm doing for Mina.

**Comment by urapadmin** [comment]
you can use different id methods per unit

**Comment by lbestock** [comment]
I know, that's what I just implemented. But what you can't do is leave ID methods invisible for some units and visible/editable for others. So I left them visible right now, thinking that all the currently excavated units are likely created already for the semester and no one will be getting in there to muck around. And that will help Mina make any legacy units free input.

**Comment by urapadmin** [comment]
we could use the archiver role to switch on temporary free input semi-permanently

**Comment by lbestock** [comment]
Ooo good idea. That is the role where all the differences between what works best for field input and what works best for legacy could be controlled.

**Comment by urapadmin** [comment]
> Ooo good idea. That is the role where all the differences between what works best for field input and what works best for legacy could be controlled.

good as that idea might be, we decided against it: our options are getting too baroque. adding the three "free input" identification methods to each new unit is the way to go here.

Can we close this?
