### ISSUE TITLE
TZ: Microseconds need to be dropped systematically

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#2878]
Synchronization resulted in warnings:

WARNING: Synchronization.synchronize_files_v2: No file matching 7c820040-592d-4d3d-845f-bb382905cff5 under C:\notebook_source\kiosk\server\kiosk\kiosk\sync\sync\filemaker\from_work_station\x1lk2\files

WARNING: Synchronization.synchronize_files_v2: No file matching b667f850-60aa-47a2-b9e8-f39f9ae35e03 under C:\notebook_source\kiosk\server\kiosk\kiosk\sync\sync\filemaker\from_work_station\x1lk2\files

The two files were both not bound to any context, so the gallery got them due to file picking. I did not touch those images!

So why were they expected by synchronization to come back from the workstation?

And why would they have a time zone index of 40079121 (America/New York) when I never touched them?

Afterwards the thumbnails were gone from the file repository (housekeeping would have re-created them because the files themselves were there). 

This is a pretty unclear case. I must restore and try this again from scratch.

_Originally posted by @urapadmin in https://github.com/arch-kiosk/arch-kiosk-office/issues/2874#issuecomment-2390461551_

**Comment by urapadmin** [comment]
Microseconds! When sending records to FileMaker some have microseconds (presumably records that had been imported in Kiosk or modified in the file repository). When the record comes back from FileMaker it lacks microseconds because FM stores only seconds. The result is that the value that comes back is NOT the same as the value that was sent and thus it is assumed to have changed. And all changed modifed fields are converted from user time zone to UTC. In this case that's fatal.

- this is presumably also the problem of #2819

**Comment by urapadmin** [comment]
they are dropped now during fork systematically. 
That does not account for synchronization proper. There it could imo still happen that a record has changed (due to the modification dates being different in microseconds) and then all the timestamp fields might differ in microseconds only as well and they all get changed.

**Comment by urapadmin** [comment]
now that they are dropped synchronization looked clean afterwards. So that might actually have solved #2819

**Comment by urapadmin** [comment]
it still needs a closer look at synchronization and how it handles it

**Comment by urapadmin** [comment]
### Kiosk 1.6.5.1
- microseconds are cut off by fork thus letting no timestamps with microseconds into the FileMaker realm at all
- synchronization is ignoring microseconds when comparing timestamp and timestamptz fields to find out what fields got modified
- this is extremely hard to test and I have to think about a realistic scenario. 
- this is also the first real alteration of the synchronization code for years. That's potentially dangerous.

**Comment by luizaogs** [comment]
Let me know when you figure out a test for this.

**Comment by luizaogs** [comment]
Lutz, any ideas for testing here now that tz is done?

**Comment by urapadmin** [comment]
honestly, no. Currently I really lack imagination how to test any of this in a way that I would call it tested. 
So I will test again if it actually happens the way it is designed (by checking the raw data in the database) but if it has any side effects that can cause strange behaviour down the road escapes my imagination right now and so I am afraid time will tell.
What we really would need is a team of testers around the globe all working and changing data like crazy in the same moment and check the results. But we can't have that :o(

**Comment by urapadmin** [comment]
let's assume this works until somebody sees microseconds somewhere.
