### ISSUE TITLE
possible project(s): field school in Hawaii and CRM

### ISSUE THREAD

**Issue by luizaogs** [arch-kiosk/arch-kiosk-office#2879]
In my new position as Archaeology Director (sigh) I received an inquiry about whether UCI would be interested in supporting a field school in Hawaii (run by a CRM archaeologist who has a daughter going here right now). When I said that, yes, I would be excited to meet to talk about this I asked if he would be interested in learning about Kiosk, that it is being used in a practicum at Brown to great effect. He said YES in all caps so I think this could work out. I sent him a link to the website so he should have an idea of what Kiosk does.

He also said he'd be interested to try it in his two CRM companies (one in Hawaii and one in Micronesia). They've been using Survey 123 by ArcGIS (https://survey123.arcgis.com/) and have found it kind of limiting - he's interested in Kiosk because he said it looked like it would allow them to record more types of data. What's the perspective on CRM usage? Last I remember Laurel wasn't very enthusiastic about it, but if we have someone genuinely interested I don't know if we would want to talk about the possibility. 

I am meeting with him in person on October 25th when he will be in town.

**Comment by urapadmin** [comment]
we'll need a surfin' spider

That's my contribution :o) I leave the rest to the directors

**Comment by lbestock** [comment]
I have not been super enthusiastic about pursuing CRM because I thought we were less likely to meet their needs as is, and as they are not our primary audience I don't want to spend too much development time making things to suit different needs. There will be no turning off narratives! But if there are CRM projects that want to use us as is then my gosh I am totally all for it. And not against getting some ideas from there, as with any project, just not a total reorientation. A CRM guy who is interested will know his needs way better than I can and it is great that you are meeting with him. And maybe we would finally get someone who will do the work (not difficult, we think, but never done) to link Kiosk data and GIS.

**Comment by urapadmin** [comment]
the reason I am not super enthusiastic about CRM is that I don't think commercial projects should be and would want to be hosted at Brown. If they would want an online server we'd be out. I am the only one who can set Kiosk up online and manage it as long as FileMaker is our recording app.
If a local server is all they'd need, it would be possible. 
But I would be interested to know more about that ArcGIS Survey module and what it does...

**Comment by luizaogs** [comment]
Ok. I will see what he would need and want for the CRM front and let you know.

**Comment by luizaogs** [comment]
As for Survey123, I wrote two sentences about it in the article that was not published: 

"Additional tools produced by Esri, the company behind ArcGIS, are used by archaeologists to collect data; these include ArcGIS Field Maps,16 ArcGIS Survey 123,17 and the ArcGIS Collector Mobile App (see e.g., Lindsay and Kong 2020).18 While such tools can be helpful for survey projects that rely on accurate and updated geographic information, they are paid options. Customization is also performed by users and is considerable, as the platforms are not designed explicitly for archaeological data and workflows."

The impression I got was that it (and these other ones) are much more geared towards GIS data. This guy (Mike) said they created some forms in the app, I suspect like context sheets, to put on their iPads (so they already use iPads) and record data that way, but that the attempt was not very successful.

**Comment by urapadmin** [comment]
- would that be a synchronizing system?
- why was it not successful?
- what do such forms look like?

**Comment by luizaogs** [comment]
The website is unhelpful. Says that it can be used on or offline, but that updates can be automatically synchronized "to access the latest information." There is a free trial on there, if you wanted to check it out. But I'll ask him. 

Unsuccessful it sounds because the types of data they could record were limited. He is interested in Kiosk because he says it is more robust. I can also ask for more details. 

I can ask him for a form, too. Do you want it now or when I meet with him?

**Comment by urapadmin** [comment]
no rush. I am just generally interested in other solutions and why users love or hate them.

**Comment by luizaogs** [comment]
Thoughts on what I should show tomorrow at this meeting? I’m fine using MKAP or MADP since I’m involved in both, but not sure they are the best ones to show in this case.

**Comment by urapadmin** [comment]
I suspect hat MKAP would actually make sense (MADP is so special in its (ab)use of the data structure that I think it is not well suited as a demo. MKAP has proper stratigraphy and you know where to find it.
But I have also rolled back the demo server for you. It is on the point where it was on the ARCE conference. It has a bit of s'urachi, which also has great stratigraphy and s'Urachi is using both ceramic preprocessing and even the ceramic analysis module.

**Comment by urapadmin** [comment]
and you are an admin user on the demo server

**Comment by luizaogs** [comment]
Ok, thanks.

**Comment by urapadmin** [comment]
please note that the demo server is a time zone server. It just tripped me myself.

**Comment by luizaogs** [comment]
Cleaning up after myself. If this ever happens it will take forever so if it does I'll get back to you about using Kiosk.
