### ISSUE TITLE
ts: last synchronization time stamp should be shown in terms of the browser's time zone

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#2882]
- [ ] sync manager: last synchronization time stamp should be in terms of user time zone:
![image](https://github.com/user-attachments/assets/2d7a9ba0-802b-443e-a56c-0bef9b283d40)

_Originally posted by @urapadmin in https://github.com/arch-kiosk/arch-kiosk-office/issues/2874#issuecomment-2390459092_

**Comment by urapadmin** [comment]
### Kiosk 1.6.5
this is showing the last synchronization time in terms of the browser's time zone, which is the actual wristwatch time of the user. That is potentially different from the user time zone that is configured for the user! Here it makes no sense to use the set user time zone. Here we really want to see a time stamp that makes sense compared to the user's wristwatch.

**Comment by luizaogs** [comment]
Also waiting on #2884 because I have no hub from which to synchronize...

**Comment by luizaogs** [comment]
Do you want me to have a user timezone set to test this?

**Comment by urapadmin** [comment]
you may, but this is really about your browser's time zone, so setting an explicit user time zone should NOT do anything. But this also only shows any difference after a synchronization ran on this Kiosk, which has not happened, yet.

**Comment by luizaogs** [comment]
Yeah I was waiting for your response before synchronizing.

**Comment by urapadmin** [comment]
ja, and you will wait longer :o( Can't get PVD to work properly, currently. Now I am stuck with the bloody pottery/ceramics table confusion.
I need a break. I'll let you know when testing makes any sense again.

**Comment by luizaogs** [comment]
This is fine. Do you want a test from a different timezone or is this sufficient?

**Comment by urapadmin** [comment]
no, if it shows your proper Chicago time, this is fine.

**Comment by urapadmin** [comment]
sorry, you know, your new Chicago.
