### ISSUE TITLE
kiosk: system messaging corrupted message

### ISSUE THREAD

**Issue by luizaogs** [arch-kiosk/arch-kiosk-office#2884]
Seems bad? 

<img width="1476" alt="Screenshot 2024-10-05 at 9 29 19 AM" src="https://github.com/user-attachments/assets/5c679a24-0a0f-4b8c-9cd8-e0b64b8a2310">

**Comment by luizaogs** [comment]
Not sure if related:

<img width="276" alt="Screenshot 2024-10-05 at 9 30 57 AM" src="https://github.com/user-attachments/assets/75c4a6e0-ec04-49c5-a95b-0b5b61d91f83">

**Comment by luizaogs** [comment]
Also don't know if related or not, but the Hub is entirely empty.

**Comment by urapadmin** [comment]
ja, PVD is kaputt. Not sure why ...

**Comment by urapadmin** [comment]
in administration:
![image](https://github.com/user-attachments/assets/c8c6d859-63ab-43b7-80b3-06affaa63fd7)

something like that is never supposed to happen in administration as that's they only way to get to the backup and restore buttons.

**Comment by urapadmin** [comment]
- [x] a python package called "charset_normalizer" is missing? I have no idea what that is and why it is missing all of a sudden. But installing it did it for now.
- [x] I have to reopen #2848

**Comment by urapadmin** [comment]
while Kiosk is working again, please don't close this, these things are fishy and I have to look into them at more depth.
