### ISSUE TITLE
kiosk: forking error

### ISSUE THREAD

**Issue by luizaogs** [arch-kiosk/arch-kiosk-office#2886]
Something is still up in 1.6.5.1. I can't prepare my workstation, forking leads to this: 

<img width="1512" alt="Screenshot 2024-10-06 at 10 53 42 AM" src="https://github.com/user-attachments/assets/0542f0f8-1d5e-4086-87dc-08ce22e6d95f">

**Comment by lbestock** [comment]
I just made a new dock and didn't get this and prepped successfully. Not going to look at it right now because my brain is bleeding after 62 job applications and I deserve a break! But I give you both that point of data.

**Comment by lbestock** [comment]
Whereas the previously existing doc for me threw the same error.

**Comment by urapadmin** [comment]
I am sorry. I forgot to renew the docks. All docks need to be "renewed" before they work again.
