### ISSUE TITLE
Kiosk Q&V: todos and some new fields

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#2891]
- The whole todo part should at least have a query and/or a report.
- collected material has new fields: research_notes and period_uncertain

**Comment by urapadmin** [comment]
### Kiosk 1.6.2.2 (this needs no new version) 09 IX 24 12:00
- added research_notes and period_uncertain to the cm view even though the latter has a flaw: #2894 which I won't tackle right now.
- added a very bare bones query "tasks on the to-do list". 
  - due to current limitations of Q&V it is presorted by state, date, priority and then title. So states first, then within a single state by date etc... 
  - it only allows filtering by participant, currently. Q&V needs to make progress before we ca do something more useful here. But perhaps this is enough to at least get an overview of open tasks. 
  - I left the "description" out because that would pop the list and just reduce "title" to a less useful width.

**Comment by luizaogs** [comment]
How do I test this for MKAP? I don't really want to create fake data in a real system with real data.

**Comment by urapadmin** [comment]
I have backed MKAP up already:

> kiosk_Wed_091024-1757.dmp

That can always bring us back to where we are.

I think adding some data in the playground and a to-do item that you can delete afterwards does not do any harm. That's at least what I would do myself.

**Comment by urapadmin** [comment]
### Kiosk 1.6.2.4 / 1.6.5.3
- added research_notes and period_uncertain to the cm view even though the latter has a flaw: #2894 which I won't tackle right now.
- added a very bare bones query "tasks on the to-do list". 
  - due to current limitations of Q&V it is presorted by state, date, priority and then title. So states first, then within a single state by date etc... 
  - it only allows filtering by participant, currently. Q&V needs to make progress before we ca do something more useful here. But perhaps this is enough to at least get an overview of open tasks. 
  - I left the "description" out because that would pop the list and just reduce "title" to a less useful width.
- added the uncertain period to small finds, which has the same flaw as the other one right now: It shows up although there is no period at all
