### ISSUE TITLE
RuBab: interested project

### ISSUE THREAD

**Issue by luizaogs** [arch-kiosk/arch-kiosk-office#2897]
See the email below. I assume next step is to meet with him on Zoom. Would you like me to do it? Laurel, do you want to meet him together? Do you want to meet him yourself? Let me know and I can respond accordingly. 

This is the project website: https://csaw.uwr.edu.pl/en/rubab/

**Dear KIOSK-team,
I am currently running a drone survey including excavation of a rural site in Southern Babylonia. After a first exploratory season in Spring 2024, excavation would be planned this November, or if not possible, Spring 2025 (excavation permission is pending).

For my project RuBab (Rural Babylonia: ca. 720-150BC), I use an ipad pro (the last generation, not the most recent). Therefore, I would be very much interested to give KIOSK a try for the documentation of the excavation. For field survey, I mainly use an Android app, called ArchaeoTracker as an addition to conventional documentation.

**Comment by urapadmin** [comment]
sorry, that I have put the cap of a moderator on my head, but can we please keep personal data out of the publicly available GitHub space? E-Mail is better suited for that.

**Comment by luizaogs** [comment]
Sorry. I don't know what you guys want to use as communication for stuff like this - it seemed like a ticket would be more centralized. I have removed his name.

**Comment by luizaogs** [comment]
Or delete the ticket if you want.

**Comment by urapadmin** [comment]
I would say let's use email until it actually becomes a task in Kiosk. So the project management task itself can be in the repository.
Alternatively we could use the project management repository, which is not publicly available. But in such a case as this E-Mail seems more natural to me.
