### ISSUE TITLE
Export error

### ISSUE THREAD

**Issue by Mina-nk** [arch-kiosk/arch-kiosk-office#2899]
Hi all. As I started working today, this happened. Anyway around it?

![Screenshot 2024-10-10 110054](https://github.com/user-attachments/assets/8994d34c-601d-4f99-a1c0-a1fbf31601da)

**Comment by urapadmin** [comment]
first thing you can always try is trying again. Sometimes the server is just busy. If that doesn't help, I'll have to look into it

**Comment by Mina-nk** [comment]
I tried twice. I am going to leave it for a few hours and try again.

Στις Πέμ, 10 Οκτ 2024, 11:13 π.μ. ο χρήστης kioskadmin <
***@***.***> έγραψε:

**Comment by urapadmin** [comment]
twice is enough. I'll take care of it.

**Comment by urapadmin** [comment]
taken care of. Something was stuck. Your dock is ready for download now.

**Comment by Mina-nk** [comment]
Thank you!!!!

Στις Πέμ, 10 Οκτ 2024, 11:31 π.μ. ο χρήστης kioskadmin <
***@***.***> έγραψε:

**Comment by urapadmin** [comment]
you are welcome
