### ISSUE TITLE
recording app: copy opening and closing elevations from top / bottom layer

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#2900]
coming out of #2309 
a button either copies from a top layer to opening elevations or from a bottom layer to closing elevations

**Comment by urapadmin** [comment]
### recording 16.2.3
- this is only available for projects using full elevations
- there is a button on top of the opening elevations that let's you select every related locus that is "above" (explicitly!) the current locus
- there is a button on top of the closing elevations that let's you select every related locus that is "below" the current. 
- there is currently no way to configure the exact name of those relations. I am assuming that all projects use "above" and "below"
- I also chimed in a button for each elevation section that clears all five elevations

**Comment by luizaogs** [comment]
SO HELPFUL. And working. Thank you.

**Comment by urapadmin** [comment]
my pleasure
