### ISSUE TITLE
q&v: ability to copy text displayed in results

### ISSUE THREAD

**Issue by luizaogs** [arch-kiosk/arch-kiosk-office#2904]
A request from Maarten, but I have confirmed that this is the case and second the request. 

We're using Q&V to prepare publications, and Maarten just realized that it is impossible to select any of the text in any of the results in Q&V, which makes it impossible to copy it onto a document. The text in the list of search results is selectable and thus copyable (are these real words? I don't know), but once we click on an identifier and open the actual context records ... that text is not. 

It would be helpful if that text could also be selected and thus copied. 

Since I'm not sure the issue appears in all browsers, I let you know that I am using Chrome.

**Comment by urapadmin** [comment]
sorry, I became an archiver and was gone to the NYU basement for two days. Tomorrow I will attend to this right away.
It is actually a bug and easy to tackle.

**Comment by urapadmin** [comment]
### Kiosk 1.6.2.5
- copying text should be possible now throughout a view
- only field contents (your data) but not the texts that belong to the UI (e.g. labels) should be "copyable"

**Comment by urapadmin** [comment]
this is rolled out. For it to take effect you might have to clear your browser cache. Browsers are pretty stubbornly clinging to style definitions. Ctrl+F5 did not do it for me. So it might need ctrl+shif+DEL in Chrome on Windows and as usual I have forgotten what the short cut is on Mac.

**Comment by luizaogs** [comment]
Also works and is incredibly helpful.
