### ISSUE TITLE
q&v: leave image that was just viewed highlighted

### ISSUE THREAD

**Issue by luizaogs** [arch-kiosk/arch-kiosk-office#2905]
A me request this time. 

Using Q&V to remember what the hell I excavated in Giza. Looking through a lot of images in context records and getting a migraine. The migraine comes because I am missing a handy feature that the file repository already has: there, if I click on an image and then out of it, the image remains kinda highlighted so I can see what image I had been looking at. So many of the images I'm looking at right now look the same and having that slight highlighting around the one I have just looked at would be so helpful.

Does that even make sense? A screenshot of what I mean in the file repository: (oh in this case I guess I also get a highlight when I'm hovering above images, which would also be helpful in Q&V)

<img width="1512" alt="Screenshot 2024-10-15 at 4 31 07 PM" src="https://github.com/user-attachments/assets/6be08b73-b80d-4bef-848e-33fa6d538704">

**Comment by urapadmin** [comment]
ja, I got it. That should be an easy thing to add.

More elaborate but presumably worth looking into would be a history of things you looked at. Like we have in FM. But I think that should not only be about images but also about all navigations steps. But again, that's a Q&V 2.0 feature. Currently we are at 0.2 or so :/ -> #2909

**Comment by luizaogs** [comment]
- Would totally be helpful, of course. Related to this, I think: #2725

**Comment by urapadmin** [comment]
### kiosk 1.6.2.5
- first pretty hacky version that does what the file repository does. 

This is the quick and dirty solution which can be eliminated once the more elaborate implementation described above is realized in a future iteration of Q&V (#2909)

**Comment by urapadmin** [comment]
same as #2904 : This might need a cache purge first.

**Comment by luizaogs** [comment]
Works and is very helpful. Thank you.
