### ISSUE TITLE
q&v: MADP query request

### ISSUE THREAD

**Issue by luizaogs** [arch-kiosk/arch-kiosk-office#2910]
Woof. Sorry for the recent influx of requests... particularly for a module you don't currently want to work on :) 

If you can't get to this soon no worries, I can do it manually.

In MADP I would like a query that allows me to bring up all loci of a certain type excavated across all units (if unit can be a way to sort results, that would be useful). In this case I want architecture, but it strikes me as a query that could be useful for other projects if you broaden it and allow one to choose the locus type they want when running the query.

**Comment by urapadmin** [comment]
ja, that isn't too hard to do and might be a useful query for others, too.

**Comment by urapadmin** [comment]
is there any other information except locus id and unit id that you would want in the result table? 
Note that architectural details or depositional details would be hard to do but everything from the main locus layout I could do.

**Comment by luizaogs** [comment]
Is description too long for this? For my purposes locus id, unit id, and description would be great. 

I could see others wanting formation process, too, though.

**Comment by urapadmin** [comment]
description will be cut off if too long. I leave it in because it can be useful even to have the first part of it.

**Comment by urapadmin** [comment]
### no kiosk update needed
the query is available in MADP: "loci by type" or so.

**Comment by luizaogs** [comment]
Thank you.
