### ISSUE TITLE
kiosk: cannot export MADP

### ISSUE THREAD

**Issue by luizaogs** [arch-kiosk/arch-kiosk-office#2912]
Getting this error: 

<img width="1482" alt="Screenshot 2024-10-17 at 4 49 18 PM" src="https://github.com/user-attachments/assets/e3e6d19f-caa6-448d-a3bf-bca986760219">

**Comment by urapadmin** [comment]
Dock might need a renewal?

**Comment by luizaogs** [comment]
Nope. Tried renewing it, same error.

**Comment by urapadmin** [comment]
ja. You might need a better admin, soon. 
I just forgot to update the recording app itself for MADP. It is done now.

**Comment by luizaogs** [comment]
Alternatively, I could stop bothering you.

**Comment by urapadmin** [comment]
that can't be the solution
