### ISSUE TITLE
recording app: cannot delete a site

### ISSUE THREAD

**Issue by lbestock** [arch-kiosk/arch-kiosk-office#2913]
In the Demo FM getting it ready for a demo.
I tried to delete Nuraghe S'Urachi. It told me I could not because it was in use by units: ? 
I was concerned already that it could not tell me what units it was in use by, but malesh, I went and deleted unit H, which was the only unit in S'Urachi.
That worked fine, there is no longer an H.
But I still cannot delete the site, and still get the same error.

I can go ahead with the demo because there are now no sensitive data of anyone else in there, but the issue I leave to @urapadmin

**Comment by lbestock** [comment]
(I thought for a second it might be because the site map still existed. But even after deleting that, same thing.)

**Comment by urapadmin** [comment]
### recording app 16.2.4
- the issue here was that Nuraghe S'Urachi has a ' in its name. That's why it never happened before. Fixed.
