### ISSUE TITLE
tz: Coordinates in Kiosk need to set the correct modified values

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#2921]
and hence work properly parallel to FileMaker in synchronization

**Comment by urapadmin** [comment]
### Kiosk 1.6.6
- that's fixed
- note that this is the user's active time zone! So either what comes straight from the Browser or what is set explicitly in the time zone popup.

**Comment by luizaogs** [comment]
Is this in reference to the point repository?

**Comment by urapadmin** [comment]
yes

**Comment by luizaogs** [comment]
Didn't work. My points were added at 10:07 Pacific Time and in the point repository it says this: 

![Image](https://github.com/user-attachments/assets/6878c662-c474-41d0-baf7-cc283535aabe)

**Comment by urapadmin** [comment]
### Kiosk 1.6.6.1 (or rather pointrepository plugin 1.1)
- showing wrist watch time now in the list (it was UTC)
