### ISSUE TITLE
rubab: configuration

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#2928]
my notes on the rubab config (I only mention things I changed or think worth noting):

- label_bulk_number "BULK#" and the "standard_term_for_cm" is "bulk"
- NO alternative CM Number. But it might be useful for legacy input?
-  lots are on
- ceramic preprocessing is reacting to the material type "ceramic". That's controlled by "modules/ceramic - diag."
- su ceramic analysis is active, in English and creates numbers on the basis of the underlying bulk#. 
- registration codes are 
   - B=Back from the field
   - R=Registered
   - C=Ceramics Processed
   - W=Washed
   - S=Sieved
   - P=Photographed
   - D=Drawn
- I changed the registration code "H" to "B" because that is what is being used for the defaults per cm type and material
- I have switched off the other type list for locus type "other"
- relations are 
   - above
   - abuts
   - below
   - bonds with
   - seals
   - is sealed by
   - cuts through
   - cut by
   - fills
   - is adjacent to
   - is abutted by
   - is filled by
   - equals
- the "equals" relation was missing in the list BUT occurred in the list that configures the opposites, so I added it.
- NO material specified list
- period is 
   - Middle Kingdom
   - 12th Dynasty (a more specific designation; a subset of MK)
   - Second Intermediate Period
   - New Kingdom
   - 18th Dynasty (a more specific designation; a subset of NK)
   - totally uncertain
- period is NOT shown in collected material
- BUT it is shown in special finds
- the spider button is off
- unit coordinates are not shown
- I have switched off unit-specific identification methods. I think that is too confusing.

- The deposit locus type was not configured correctly under "locus types". It would not have shown any deposit details. That's fixed.
- Surveys and transects and feature want free input (which, of course is a synchronization hazard!)
- quality control is on and has our default qc rules active
- the archiver role is available and works

**Comment by urapadmin** [comment]
team members should be configured BEFORE finally downloading the ipads. Otherwise the excavators would have to be added to the ipads. And then if one excavator is added to two iPads it will duplicate in synchronization. 

Valuelists should have their final config before downloading the iPads as well. Otherwise additions will have to be made to all iPads individually. Here at least is no danger of duplication involved. But one of the iPads that made changes to the same valuelist will win,

**Comment by lbestock** [comment]
Hm going through this now and the SU ceramics shows up in Italian, which is contrary to what I expected.

**Comment by urapadmin** [comment]
odd. I could swear I have set the language to en

**Comment by lbestock** [comment]
How does one, even? I don't see how in configuration.

**Comment by urapadmin** [comment]
search for language?On 26. Oct 2024, at 12:28, lbestock ***@***.***> wrote:﻿
How does one, even? I don't see how in configuration.

**Comment by lbestock** [comment]
Ja helps if one spells "language" properly.

**Comment by lbestock** [comment]
Annnnd new ticket: that configuration key does not synchronize properly is the issue.

**Comment by urapadmin** [comment]
can we close this?
