### ISSUE TITLE
kiosk: there is no good way to get rid of wrong queries

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#2939]
- update_default_kiosk_queries should have a parameter that deletes all existing query records first. Currently it only modifies and adds queries.
- the same should be true for the same option in administration
- I have already reactivated the KioskQuery admin view for 1.6.6.2

**Comment by urapadmin** [comment]
### Kiosk 1.6.6.2
- at least the KioskQuery admin view allows to delete a query again.

**Comment by luizaogs** [comment]
The queries UI is back but I don't want to delete one because I don't know how to put it back.

**Comment by urapadmin** [comment]
I tested it

**Comment by urapadmin** [comment]
(actually: if you delete a regular query it will appear again at some point (e.g. by pressing the button "reload all kiosk queries" in administration). One can only permanently delete erroneous queries that won't be reinstalled)
