### ISSUE TITLE
tz: importing a dock checks the importing user's time zone instead of the dock's time zone

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#2940]
during import the current Kiosk user's time zone should not matter at all I think.

Also the message is wrong from my point of view: The dock was prepared for Mountain Time and NOT for America/New_York

![image](https://github.com/user-attachments/assets/e07292b7-f8b6-4f5d-b607-c87132ca229f)

**Comment by urapadmin** [comment]
okay, I rather keep to the warning in and of itself. Even though the import does not strictly need the current dock's time zone in Kiosk because it operates on the time zone that was embedded into the fm database on export, I would rather warn about a discrepancy. This will ALWAYS happen if an admin tries to import all the workstation from an international team and the respective time zones are not set on dock level. But is what we strongly recommend: If you have an international team always set a time zone on the dock.

**Comment by urapadmin** [comment]
### Kiosk 1.6.6.2
- the warning should correctly show the two disparate time zones.
- warning stays: Test it!
  - that means: if the dock has no time zone set and the current user is in a different time zone than on export: Warning
  - that's the only way to get there. The other way would be to have a dock on time zone X on export that changes its time zone to Y on import. But there is no UI that would allow that. I would have to tweak that directly in the database.
  - if the dock's time zone is the same on export and import everything should be fine.

**Comment by urapadmin** [comment]
Okay, that works now.
The error message now looks like this:
![image](https://github.com/user-attachments/assets/a1ede485-8659-47e2-a3bb-49dd83aefb6f)

Note that I have already attended to the missing space in there.

More important: This will need to be addressed in the FAQ. It usually points to an international team that did not set anything up to be international. International teams should set a time zone on every dock.

There are three ways to handle this situation and using repair mode is the least recommended. The easiest should be to do the import from the ipad in its time zone. If the iPad isn't available or the user on the iPad is not allowed to import or so, the Kiosk user doing the import could set his / her own time zone specifically to the time zone that was used on export of the dock. Don't fortget to logout / log in again after changing the time zone.

**Comment by urapadmin** [comment]
Having written that it turns out it isn't that simple. Windows is using a deprecated IANA time zone America/Phoenix for Moutain Time. That is a time zone we do not offer in our time zone selector (there are hundreds of deprecated time zone names). So I must compare UTC offsets here.

![image](https://github.com/user-attachments/assets/6abddb99-91df-4751-afb6-a7d5105886ea)

**Comment by urapadmin** [comment]
### Kiosk 1.6.6.3
- regarding this check "Mountain Time (US/Arizona)" is now considered compatible with "America/Phoenix" because I check the UTC offset. I suspect the fact that operating systems report deprecated time zone names will cause some headache in the future.

- Time Zone names keep being tricky. "Mountain Time (US/Mountain)" has a different UTC offset than "Mountain Time (US/Arizona)". Projects might needs some help there.

**Comment by urapadmin** [comment]
this needs to be mentioned in the FAQ

**Comment by luizaogs** [comment]
I might be misunderstanding something here, but would it make sense to change the label of the tz setting on dock level from "user's timezone"? Isn't that the same thing as the timezone for the user set in the hub? Would it make sense to call it "dock timezone" or something?

**Comment by luizaogs** [comment]
The test worked fine, and I will open a new ticket for my question above.

**Comment by luizaogs** [comment]
For the manual, is this what you want? I admit to not have mastered the tz stuff so want to check before I add it to the Google doc: 

**I am getting a warning that my dock cannot be imported because it was exported in a certain timezone and is now being imported in a different timezone. What do I do?** 

This will always happen if an admin tries to import all docks and users are recording in different timezones. If your team is working in different places, we recommend that the timezone is always set on the dock level. That way the admin of an international team can import the docks with no issues because they will have been exported and imported in the same timezone (that of the dock itself).

If the dock timezones were not set initially and you are now running into this error, the easiest thing to do is to do the import from the iPad associated with that dock in its timezone. If the iPad is not available or the user of the iPad is not allowed to import, the Kiosk user doing the import could set their own timezone specifically to the timezone that was used on export of the dock (for that change to take effect, you will have to log out and back in again). Using the repair mode for import is the least recommended method.

One thing to look out for: timezone names can be tricky. For instance, "Mountain Time (US/Mountain)" has a different UTC offset than "Mountain Time (US/Arizona)". Make sure you are using the correct timezone for what you need!

**Comment by luizaogs** [comment]
Also, if the repair mode is the least recommended course of action should it be removed from the warning?? If someone reads that the first thing they'll do is probably use repair mode, not go to the manual (or at least that's what I would do...).

**Comment by urapadmin** [comment]
### Kiosk 1.6.6.5
> Also, if the repair mode is the least recommended course of action should it be removed from the warning?? If someone reads that the first thing they'll do is probably use repair mode, not go to the manual (or at least that's what I would do...).

I have changed it to "Please consult the FAQ or user manual to learn about your options.".

**Comment by urapadmin** [comment]
> For the manual, is this what you want? I admit to not have mastered the tz stuff so want to check before I add it to the Google doc:
> 
> **I am getting a warning that my dock cannot be imported because it was exported in a certain timezone and is now being imported in a different timezone. What do I do?**
> 
> This will always happen if an admin tries to import all docks and users are recording in different timezones. If your team is working in different places, we recommend that the timezone is always set on the dock level. That way the admin of an international team can import the docks with no issues because they will have been exported and imported in the same timezone (that of the dock itself).
> 
> If the dock timezones were not set initially and you are now running into this error, the easiest thing to do is to do the import from the iPad associated with that dock in its timezone. If the iPad is not available or the user of the iPad is not allowed to import, the Kiosk user doing the import could set their own timezone specifically to the timezone that was used on export of the dock (for that change to take effect, you will have to log out and back in again). Using the repair mode for import is the least recommended method.
> 
> One thing to look out for: timezone names can be tricky. For instance, "Mountain Time (US/Mountain)" has a different UTC offset than "Mountain Time (US/Arizona)". Make sure you are using the correct timezone for what you need!

Yes, I think that's okay for a FAQ. I can't write any such thing anymore because my FAQ would be two pages long and list all possible circumstances and people would be dizzy and confused. One thing, though. I think it makes sense to actually quote the error message as users presumably search the FAQ:
>FileMakerWorkstation._import_check_fm_time_zones: Error importing data from a filemaker source that on export was set to user time zone X but now is expected in user time zone Y. 

What we should really consider is another section "How to set up Kiosk for a international team" or so at some point.

**Comment by luizaogs** [comment]
Ok. I added it.
