### ISSUE TITLE
KioskBridge: Connection with PVD not reliable

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#2941]
~~not sure which it is, but I was not able to connect as "lkh-7" to the dock "utc-7".~~

No, that is apparently not the issue. But see below.

**Comment by urapadmin** [comment]
no idea why, but I was able to connect with lkh1 to utc-1 to download a database but when I want to upload I get "connect to Kiosk" all the time. It flashes green, so the credentials are okay but then turns it to "No connection to Kiosk". Bridge has a problem. It happens as soon as the file got transferred to FileMaker Go. It does not even have to come back from there.

Happens on TWO ipads!

**Comment by urapadmin** [comment]
@arch-kiosk/test 
Could you guys please test if Kiosk Bridge works correctly with a normal project like BUAP or MADP or MKAP?

**Comment by luizaogs** [comment]
MKAP just worked fine for both download and upload through Bridge.

**Comment by lbestock** [comment]
And on BUAP, also just fine.

**Comment by urapadmin** [comment]
please try rubab, too

**Comment by lbestock** [comment]
Rubab works, no problem. Do you need to know what our users or docks were called?

**Comment by urapadmin** [comment]
> Rubab works, no problem. Do you need to know what our users or docks were called?

no, I just wanted to make sure that it still works on the current public release

**Comment by urapadmin** [comment]
### Kiosk 1.6.6.5
- that was a time zone bug in Kiosk and now Bridge should work just fine.

**Comment by luizaogs** [comment]
Hmm my upload failed. I'll try again later, may be the fact that I'm using a hotspot.

**Comment by urapadmin** [comment]
mine just worked, so something might have been a bit too slow?

**Comment by urapadmin** [comment]
at least if you made to the upload you were past the bug here. I have tested it here, too. So I take the liberty and close it.
