### ISSUE TITLE
recording app: in "find stuff" there is a modified time stamp 

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#2944]
and I don't think it is _ww time

**Comment by urapadmin** [comment]
### recording app 16.5.2
- that was still using the "modified" field and hence showing records in terms of the current user's time zone. But that's not what we want to see here. It should be the wristwatch time of the moment of the last modification. I think at least that's what we want here. And that is what it is now. 
- to test this you need to modify a record while in time zone X, synchronize and then prepare the workstation for a time zone Y. In Y dock you should see what was the time when modifying the record while in X

**Comment by luizaogs** [comment]
Any record? What is “find stuff”?

**Comment by urapadmin** [comment]
the search function (it has "find stuff" in the title of the popup)

records would be locus, locus_photo, cm, cm_photo, unit.

And perhaps I should have mentioned that we are talking about the "most recent" tab

**Comment by luizaogs** [comment]
Another stupid question for you, I guess. In the search function the only timestamp I see is a date, no actual time. Is the modified I'm looking for that in the locus record (or whatever record I navigate to with the search function)? Unless I'm looking in the wrong place, but I don't see a most recent tab, only recently changed. 

<img width="625" alt="Screenshot 2024-11-08 at 5 21 49 PM" src="https://github.com/user-attachments/assets/8ea5ba26-8a3b-43d8-963a-ee9af38a0c5c">

**Comment by urapadmin** [comment]
These things are so hard to test. To see if it is correct you would have to choose a moment when the dock time zone of the displaying dock was on a different day than the wrist watch time in the moment of recording. 

So: iPad A is in Los Angeles and changes a record at 8pm and synchronizes. After that iPad B gets prepared in Berlin (where it was a day later at 5am when the change happened in Los Angeles). iPad B should show the Los Angeles date in this list. 

Also the order, even tough you only see dates, takes the time into consideration. But that gets even harder to test. It will be okay.

**Comment by luizaogs** [comment]
Worked. Changed a locus record on 8 XI 2024 Pacific Time and downloaded another workstation on 9 XI 2024 Ankara time. Search shows that locus having been changed on the 8th.

**Comment by urapadmin** [comment]
### recording app 16.5.2
- reopened because of #2986 
- unfortunately I must ask you to repeat this test

**Comment by luizaogs** [comment]
This has changed now to user's timezone rather than ww right? Or at least that's what I got from #2986  

So the result of the same test I did yesterday should show the record having been changed in the Ankara time, correct?

**Comment by urapadmin** [comment]
Language beginning to fail us here. The test here should turn out exactly as last time. There is still the wristwatch time on display. Only the order of records can be affected by #2986 and the latest changes.

**Comment by luizaogs** [comment]
Hmm not quite. Now I get the time in my second download, 3:15am. Which is correct because I again used the time in Ankara (and it was 4:15pm PST), but should it not show up as 10 XI 2024 since it's not the same day? 

![IMG_295DBE5BA7C6-1](https://github.com/user-attachments/assets/1684d511-55fc-4137-afdf-ddd020434258)

**Comment by urapadmin** [comment]
I don't understand. Why does it show 03:15 if it was 04:15 in Ankara?
Actually I am also not so sure if this would be 12hour clock or 24h clock in this case? 

Have you uploaded this one?

**Comment by luizaogs** [comment]
It was 4:15 in Irvine and 3:15 in Ankara. Yes, it was uploaded.

**Comment by urapadmin** [comment]
great. It was 16:15 in Irvine and FileMaker returns 04:15. Which it should not. I really hate inches, foot, am, pm and all those British measurements. They make no sense.

**Comment by urapadmin** [comment]
again, you have changed the record in Irvine at 16:15
you looked at it in a dock that was set to Ankara time zone. 
And the device you were using to look at it was set to Ankara time zone and time, right?

**Comment by urapadmin** [comment]
hm. I have downloaded your logsipad. It is set to be in Irvine and the wristwatch time of 222 is 16:15, so that was Irvine, too. So that would be correct. Let me look at logsmac...

**Comment by urapadmin** [comment]
ah. The wristwatch time in logsmac is 03:15, That is not okay. It should be the same in both time zones. There is still something amiss then.

**Comment by urapadmin** [comment]
### recording app 16.5.4
- next try. There was still something wrong with the timestamps in FileMaker. I really hope that's it now.
- I skip the the am / pm issue for now. I should really look at the whole app myself with a US Date setting one day.

**Comment by luizaogs** [comment]
Woops sorry I went out to dinner and didn’t see this. I’ll try it again tomorrow.

**Comment by luizaogs** [comment]
Seems good now.
