### ISSUE TITLE
tz: change dock tz label from "user's timezone"?

### ISSUE THREAD

**Issue by luizaogs** [arch-kiosk/arch-kiosk-office#2946]
I might be misunderstanding something here, but would it make sense to change the label of the tz setting on dock level from "user's timezone"? Isn't that the same thing as the timezone for the user set in the hub? Would it make sense to call it "dock timezone" or something?

_Originally posted by @luizaogs in https://github.com/arch-kiosk/arch-kiosk-office/issues/2940#issuecomment-2450984494_

**Comment by urapadmin** [comment]
ah. That's a relict from the complex time zone implementation. I'll change that.

**Comment by urapadmin** [comment]
### kiosk 1.6.6.5
- fixed
