### ISSUE TITLE
Kiosk: synchronization issues apparently mostly with photos

### ISSUE THREAD

**Issue by lbestock** [arch-kiosk/arch-kiosk-office#2955]
Two of the five people working on BUAP today, right after a new release, have had HEIC issues. I will not touch it until @urapadmin looks at the synchronization logs.

**Comment by urapadmin** [comment]
- see #2835

FileMaker 21 on Mac not working. We must use FileMaker 20 until the server is up to 21, which I would want to avoid until there are a few fixes from Claris.

**Comment by urapadmin** [comment]
yup. Definitely FM21 on Mac meeting FM20 on the Windows server like with #2835.
Everybody using a Mac must stay on FM20. 

I can also see that one random HEIC that TJH made of 201-4 made it through BUT without connection to a context. I can only suspect that it caused already trouble in FM. At least it is image 281f9e1c-8792-416e-a014-9c4aa4979164 which has indeed no connection to a context within TJH's FM database. Instead the same motive is in there several times and a different version of it is connected to the locus 201-4. 
So there must have been trouble already "on the ground" which I can not reconstruct here. This must be the same machine that caused trouble ADDING a locus? (Or was it adding a photo to a locus?)

**Comment by urapadmin** [comment]
@ThomasHaunstetter @lbestock 
I have resurrected the lost images. Tom, please check next time if everything looks the way you recorded it.
- Otherwise see #2959
