### ISSUE TITLE
recording: red boxes appearing in locus form outside of test mode

### ISSUE THREAD

**Issue by luizaogs** [arch-kiosk/arch-kiosk-office#2957]
I have turned test mode off but am getting this developer/test stuff anyway:

![IMG_0470](https://github.com/user-attachments/assets/9a2bbba9-6712-4b9f-9821-7283a797aae7)

**Comment by luizaogs** [comment]
They are also appearing when I’m searching for loci in relations.

**Comment by urapadmin** [comment]
### kiosk 16.4
- they were bound to your role as tester. I have changed that now to the usual test mode binding.
