### ISSUE TITLE
recording: extend architecture layout

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#2960]
- coming out of #2948 

> For what it’s worth Lutz, and since you still have room in the layout, a “further observations on measurements” text field (similar to what we did for CM) or something could be useful. I only chime in because it is something that could have been useful for MADP too but I think we just ended up adding notes to the general locus observations since they didn’t fit here.

The downside of too many description fields in several places might be that information gets a bit scattered and it gets harder to get the whole picture. But I thought a free input in the architecture layout cannot hurt.
However, I before I extend the architecture layout I want to hear what BUAP and Abydos actually need. There might be more ...

_Originally posted by @urapadmin in https://github.com/arch-kiosk/arch-kiosk-office/issues/2948#issuecomment-2454992109_

**Comment by luizaogs** [comment]
Also #1375. But for MADP (and I imagine similar projects) an extension of the layout would be most productive alongside the drawing module so probably beyond the scope of what you want to do right now.

**Comment by urapadmin** [comment]
I closed #1375 in favour of this one here. Nothing really came out of #1375 and I think the image annotation module, should I ever even get there, will raise the MADP questions in a very different way again,

So this here is really only about an additional field. @lbestock: Do you see value in it. It is really not a big deal for me to add a field. The question is would projects use it?

**Comment by lbestock** [comment]
Hm, honestly I would just change the label on "mortar description" to be something like "notes on measurements and mortar" if this is going to be in the architecture layout. When one has architecture there are already measurements in two different tabs. There are too many text fields and those run into precisely the problem @urapadmin identifies above. The problem I see @luizaogs running into is that without a label or hint one might forget to make notes at all, or might make them in inconsistent places. But this is not ever going to be a field by which one sorts things. I think it is better handled by a project-by-project decision on how to use extant fields and configuring their hints or changing their labels to reflect that than by a new field.

**Comment by urapadmin** [comment]
so we just close this?
