### ISSUE TITLE
recording: locus selector in relations no longer filtering by trench

### ISSUE THREAD

**Issue by luizaogs** [arch-kiosk/arch-kiosk-office#2961]
This was working when I tested the creating locus from relations thing a couple of days ago so I expect it's a side effect of one of your latest changes. I can no longer filter by trench in the selector in relations, and a default trench doesn't appear there either so I don't think the problem is an incorrect config key: 

![IMG_EF5F1E6447AF-1](https://github.com/user-attachments/assets/f4720c7d-4e1f-436a-8781-9f7b41b01c0b)

**Comment by urapadmin** [comment]
ja, that is a bug. It should only be that way when you use the locus selector in the header.

**Comment by urapadmin** [comment]
### recording app 16.4.1
- should be fixed now
