### ISSUE TITLE
recording: moving through loci with arrows does not respect domain sorting

### ISSUE THREAD

**Issue by luizaogs** [arch-kiosk/arch-kiosk-office#2963]
Title pretty self explanatory. If I have the domain sorting on, my locus selector and my locus list give me buapish-2 after buapish-1. Nice. But if I am moving through loci with the arrows I go from buapish-1 to buapish-10. Unexpected.

(Or really, that was expected in this case and I did it in the first place to confirm that it would work like this. But it's a bit weird to have sorting done one way in the selector in the header and then the arrows doing something else. Not sure if you can do anything about it, or if it's worth doing if you can.)

**Comment by urapadmin** [comment]
wow. It did not occur to me even to think about synchronizing the sort order in the selector and the movement of the arrows.
I'll see what I can do ...

**Comment by urapadmin** [comment]
### recording 16.4.1
That was a good one. I liked it.

**Comment by luizaogs** [comment]
Ha. You're welcome.
