### ISSUE TITLE
bridge: dock is being prepared but bridge still offers to download it

### ISSUE THREAD

**Issue by luizaogs** [arch-kiosk/arch-kiosk-office#2964]
I'm not sure if this was always the case. If so, I had never noticed it. 

I'm preparing my dock in the hub after a new test release. This morning I had used Bridge to download from that same dock, but currently the dock is "processing". However, Bridge still gives me the two options that I should see when a dock is prepared: "send to FM again" or "download from Kiosk again". 

Once the dock is indeed prepared again, Bridge does not refresh automatically and I still get those two options which really are relevant to my morning download rather than this one. In order to get the correct "download from Kiosk" rather than "download from Kiosk AGAIN," I need to go into Bridge's settings and click on reset app state.

A bit of a confusing workflow.

**Comment by luizaogs** [comment]
Perhaps relevant is the fact that I did not upload that dock, so perhaps an issue more relevant to testing.

**Comment by urapadmin** [comment]
yes, that is a bit of a test issue. If you don't upload, Bridge can still be expecting something back from FileMaker. If a new state in Kiosk automatically reset the Bridge state it could lead to losing the option to upload current recording data (which in some scenarios I would want to do to use the "repair mode" of the import). I remember that I decided to decouple the Bridge states from those in Kiosk at some point to be a bit more flexible. I think for the regular recording cycle in the field this is okay.

**Comment by urapadmin** [comment]
see also #2942
