### ISSUE TITLE
recording: loci descriptions not showing up in locus list

### ISSUE THREAD

**Issue by luizaogs** [arch-kiosk/arch-kiosk-office#2965]
Screenshot demonstrates that the selected locus does indeed have a description, but that it's not showing up in the list any longer: 

![IMG_0474](https://github.com/user-attachments/assets/9d9bab39-3565-47fe-88ff-d2a2bb937ec6)

**Comment by urapadmin** [comment]
oops. How did that happen`?

**Comment by urapadmin** [comment]
### recording app 16.4.2
- the description field got caught up with the invisible test fields there.
