### ISSUE TITLE
ANC database/BUAP question

### ISSUE THREAD

**Issue by lbestock** [arch-kiosk/arch-kiosk-office#2972]
@urapadmin you will test the link to the ANC database yourself. But I just added a day's data from 2008 and see that at least one ANC record got brought in properly with the new ID method for loci, so I am thinking things are likely working.

But I did notice that CM brought in this way do not appear in the director's view. I know you're checking modification dates and the like, and this may be expected and desired? But I wanted to see what ANCs got brought in today and the DV is where I go to see recent changes.

**Comment by lbestock** [comment]
When I find the ANC# via Q&V there is what appears to be a date/time related either to the locus creation or the import of the ANC# (it's today, but I didn't check it quickly enough to know which of those it might be) but under "pottery remarks":

![image](https://github.com/user-attachments/assets/8c0823ea-aea2-4d25-a5bd-b47c0cfe09db)

Funny.

**Comment by lbestock** [comment]
Hmpf I'm not happy about "period uncertain" or "is grave good" there either. Looking in the ANC database, those very certain "no"s do not correspond to anything in the original database. Would be better to leave them blank.

**Comment by urapadmin** [comment]
> Hmpf I'm not happy about "period uncertain" or "is grave good" there either. Looking in the ANC database, those very certain "no"s do not correspond to anything in the original database. Would be better to leave them blank.

leads us to the conclusions: No checkboxes anymore, ever. Because they do not have a blank state. We must always use a three state value.
I don't want to attend to this singular state and rather make a new ticket for the general issue: #2975

**Comment by urapadmin** [comment]
we want the modified field to be the timestamp of the import of the ANC recording into Kiosk.
The modified field from the ANC database has to go into what is currently pottery remarks.

**Comment by urapadmin** [comment]
### BUAP Kiosk 05.XI.24
- modified gets set to the current utc timestamp and the wrist watch time to US/Eastern. That happens for both the collected material and the small find record.

**Comment by lbestock** [comment]
Have not had a small find yet, but works properly for bulk. Only see #2977 - it isn't showing up in Director's View.

**Comment by urapadmin** [comment]
small find needs a test too, because an error in there could break the import

**Comment by lbestock** [comment]
Do you want me to do this now and go through another synchronization, or do you want to figure out first why nothing shows up in DV from the last one before I do this?

**Comment by lbestock** [comment]
Small finds come in no problem.

**Comment by urapadmin** [comment]
in that case this is done.
