### ISSUE TITLE
Kiosk: how to allow for a new upload after a "no new records" synchronization?

### ISSUE THREAD

**Issue by lbestock** [arch-kiosk/arch-kiosk-office#2973]
I am 100% sure there is already a way to do this, but I cannot find it in the admins user manual. Only for when someone has worked in the wrong file. So this is a support ticket for a particular user but also a user's manual ticket for @lbestock

@JohnCarroll27 uploaded a BUAP workstation. It imported just fine but synchronization said there were no new files. John has checked on his laptop and there's only one buap file flying around so it can't be that he worked in a different one than he uploaded. 

The dock is now back in synchronized needs preparation state.

**Comment by JohnCarroll27** [comment]
Hello, I had the file open since I first began working on it on Friday, and I finally logged out and closed this morning.  When I attempted to re-open the file, I received the following error message: 
![image](https://github.com/user-attachments/assets/b78b811c-76ee-4ec5-a7c3-79c2b82bfa99)

**Comment by lbestock** [comment]
OK this ticket is a big nothing burger of hilarity. @JohnCarroll27 - all is good, your data uploaded fine when you did this yesterday. I was wrong. The "repair" message Lutz saw while synchronizing was only because you hadn't closed your file, but it was properly repaired. Lutz's worry was that there were no IMAGES which I understood to mean there were no DATA. Just a miscommunication here. 

The above message is proper when you reopen a file across the divide of the timezone, but also irrelevant. Since the data you entered are properly in the central database that file can be trashed before your next download.

**Comment by JohnCarroll27** [comment]
Ah I see, no worries!  Glad to hear that everything uploaded properly.
