### ISSUE TITLE
recording app: move collected material to a different locus.

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#2976]
> What would happen if I made a change in the ANC database to a record that was already imported? As in, if something was already brought in as 175-15, and then I decided I could tell that it was 175-15B and changed that in the ANC database? Would it import it properly into 15B, and would it remove it from 15? Or should I, once I realize this, delete it from 15, change it in the ANC database, and let it be imported anew and properly?

First of all we would have to find out where the latest ANC DB is. I guess I would be able to find that.
Then you would have to make the changes there.
Then I would have to import that into the ANC copy in Buap (lives in the background).

Let's say collected material 512 has locus 175-15b and lot 1 in the anc db. If there is a locus 175-15b and a lot 1 in BUAP, that would pull the collected material 512 in. BUT. it would NOT delete the same one that already got pulled in to 175-15 back in the days. So you would have to delete that first.

Not a good way of dealing with this problem. We better add a feature that allows us to move a collected material over to a different locus.

_Originally posted by @urapadmin in https://github.com/arch-kiosk/arch-kiosk-office/issues/2956#issuecomment-2458471292_

**Comment by urapadmin** [comment]
we also want this to be accessible only if a project is configured to need it

**Comment by urapadmin** [comment]
### recording app 16.5
- there is a new button in the burger menu of collected material. Unfortunately it is orange. It appears only if the user is registrar AND has switched on temporary free input (I am actually not sure how smart that was).
- if you press it you can select a new unit/locus for the collected material and on okay the cm will be moved to that locus.
- after the move you are kicked out of the collected material layout and the collected material gets deleted from the navigation histories
- note that you would still have to rename the collected material yourself in the target locus. If you move 142-15-1 to 141-16 it will still have the identifier "142-15-1". You must use temporary free input to change that manually.

**Comment by luizaogs** [comment]
Sigh. Orange. 

This is working but since the identifier is only modifiable with temporary free input if you're an admin the workflow is a bit odd (I had to log out and back in to then change the identifier). If the expectation is that registrars can do this, then should registrars also be able to change the id of an existing identifier with free input? Rather than requiring the latter to be only admins?

**Comment by urapadmin** [comment]
ja, I suppose so. Or we make it all admin. @lbestock ?

**Comment by lbestock** [comment]
Let me give it a test run. I think this is a testing issue and we can leave renaming the CM to admin. At least as relates to legacy data, but I'm pretty sure ordinarily, too. The point is that a CM CANNOT be renamed 99.999999% of the time. The whole reason this is a mess is that the number is on a tag on this object in the magazine. If the number in Kiosk does not match that tag, we're screwed. I suppose it's conceivable that someone holding that object would change the number on the bag IF the project were using hierarchically numbered CM IDs to begin with and its locus changed. But that is such a special case, and would not be happening at the same time the new locus designation is being made, that keeping it behind an admin wall doesn't bother me. For BUAP it's essential that the ANC number not change when the CM gets moved to another locus.

But I'll give it a run through now while thinking of actual use-cases.

**Comment by lbestock** [comment]
Nice cow :)

I think it should stay as it is. The process of moving CM from one locus to another works and should be quite rare. The process of renaming a CM is a separate one and is a huge deal and much rarer and I like the added "stop and think about it" of having to login as admin. If everyone who moves a CM to a different locus thinks that means renaming the CM we have a problem.
