### ISSUE TITLE
Kiosk:things missing in DV after synch? 

### ISSUE THREAD

**Issue by lbestock** [arch-kiosk/arch-kiosk-office#2977]
I just input some actual BUAP data to test the ANC import after some changes.
Having put in two narratives and a few lots and one locus, I uploaded and syncrhonized.

The Director's View does not show me any imported ANCs which surprised me - one of the notes in the narrative I typed said 3 baskets of ceramics.

Even more worrisome, the DV does not show me the new locus - 145-12. 

That locus IS there if I try to find it in Query and View, so on the locus front at least it seems to be a Director's View problem not an absence of the record. Now I will hunt the ANCs that should have been imported.

**Comment by lbestock** [comment]
I think it's a Director's View thing. The ANCs got brought in properly and can be seen in Q&V.

**Comment by urapadmin** [comment]
I can see the 145-12 locus, too and the modified time stamps look fine:
![image](https://github.com/user-attachments/assets/e4569dae-f58d-4737-8b94-8d98890ec3aa)
(the new queries Time Zone test queries are helpful with that).

So indeed, director's view does not like something about that locus.

**Comment by urapadmin** [comment]
I suspect the anc records look fine on the timestamp front, too:
![image](https://github.com/user-attachments/assets/066dcb3c-5122-4217-a392-a45245b93d5f)

**Comment by lbestock** [comment]
And the Director's View missed the narratives from that synchronization, too. So it's not just the locus. Weeeird.

**Comment by urapadmin** [comment]
but it is not missing everything you did, or is it?

**Comment by lbestock** [comment]
Everything I did with this synchronization, I think.

**Comment by urapadmin** [comment]
could be a time zone issue as utc is currently a day ahead of us

**Comment by lbestock** [comment]
Aha. There's our example of where it gets confusing!

**Comment by urapadmin** [comment]
no, it shouldn't. The wristwatch time of those records should be today and it should be compared to wristwatch time now as we are in the same time zone.

**Comment by urapadmin** [comment]
so everything that shows up under your name in DV is from earlier today?

**Comment by lbestock** [comment]
Yes.

**Comment by lbestock** [comment]
And after another cycle in order to test if small finds come in properly, still the same problem of things from the last two synchronizations not showing up in DV (though the ANC small find import was just fine).

**Comment by urapadmin** [comment]
what makes it worse: I get different results for 145-11 in FireFox than in Chrome. So that must have something to do with the browser's own time zones and the Vaadin date picker.

145-11 has ww time 5.XI.24 21:29:09 but UTC time 6.XII.24 02:29:09

**Comment by urapadmin** [comment]
no worse. It is not Chrom that makes the difference, It is BUAP. BUAP and my local development system don't react the same.
That is worrisome.

**Comment by urapadmin** [comment]
Beset on 06.XI.24:
![image](https://github.com/user-attachments/assets/6834c1bd-c3cc-49ed-a49d-fb143eb0d06b)

local:
![image](https://github.com/user-attachments/assets/fb761442-573b-4b88-84c3-86b27d0428ca)

**Comment by urapadmin** [comment]
no. Not a time zone error. A moron error, Apparently I did not include the latest version of the directorsview into the Kiosk rollout. 
### Kiosk 1.6.6.7
- this time with the "new" directorsview

**Comment by urapadmin** [comment]
It looks now as I would expect it. But I suggest you have a look yourself at the 5th and 6th and perhaps make a new test.
The time of day played a role here because the old director's view used the UTC time instead of the wrist watch time. And the UTC time was already on a different day than the ww time in Providence. Made sense to me.

**Comment by lbestock** [comment]
All looks proper now, including after a new test with real material this afternoon.
