### ISSUE TITLE
Kiosk: Sync telling me Locus relationship has error

### ISSUE THREAD

**Issue by maychu16** [arch-kiosk/arch-kiosk-office#2979]
This is my first time running into this error and I do not know what has triggered it. The sync report does not allow me to click that error and find out what I need to fix. Could you please let me know how to solve this?

Thank you. 

<img width="1512" alt="Screenshot 2024-11-06 at 1 26 07 AM" src="https://github.com/user-attachments/assets/766beae4-d100-4320-bb8f-1ee1c2c03fbf">

**Comment by maychu16** [comment]
I have figured out that I can click "show more details" to see which Locus relationship was the problem. Since it is not part of the Op that I am working on, I will leave it there.

**Comment by urapadmin** [comment]
first of all, it isn't really an error, more a hint, so synchronization was fine.
You get more information if you click on "more details", Then many more grey lines appear below that warning. 
They should tell you what locus needs its relations improved.

**Comment by urapadmin** [comment]
btw. It is totally possible that it has nothing to do with what you just synchronized. Kiosk checks all locus relations over and over again after every sync run.
