### ISSUE TITLE
recording: red box in unit creation

### ISSUE THREAD

**Issue by luizaogs** [arch-kiosk/arch-kiosk-office#2981]
New unit creation in PVD has a red box floating around: 

<img width="1030" alt="Screenshot 2024-11-06 at 9 41 27 AM" src="https://github.com/user-attachments/assets/e71c7738-6f42-4aed-a193-3a98c02f802b">

**Comment by urapadmin** [comment]
hard to see. But I found it. 
Are you travelling?

**Comment by luizaogs** [comment]
Unfortunately very much in this cursed country, catatonic on my couch. But perhaps southern California will be engulfed in fire soon...

**Comment by urapadmin** [comment]
I see. I was just wondering because this time you didn't get MY cow (well, not really a cow)

**Comment by luizaogs** [comment]
Well that's upsetting. Let me see...

**Comment by urapadmin** [comment]
perhaps a real cow would have been cheering you up more. But I thought I share the first printed article on Kiosk with you. You should have been mentioned. Reporters!

**Comment by luizaogs** [comment]
Well, it's good for you guys and the project I'm sure!

**Comment by urapadmin** [comment]
I am not sure the Brown Alumni magazine has any impact. But on a day like this one takes what comes ones way.

**Comment by lbestock** [comment]
I read it every month to see if anyone I went to college with has died. But I have heard today from two people about that article :) Only one of whom I am at all regularly in touch with. The other one I hadn't heard from in 25 years but he sent it to me, and added that he had seen me on YouTube...

**Comment by urapadmin** [comment]
### recording app 16.5.1
- no more red boxes but a cow
