### ISSUE TITLE
file repository: make context-bound descriptions?

### ISSUE THREAD

**Issue by lbestock** [arch-kiosk/arch-kiosk-office#2983]
The inability to make context-bound photo descriptions in the file repository creates a workflow for BUAP that has consequences, and so I raise the possible desirability, at least from the point of this project but I suspect any legacy project with lots of photos (see Abydos....), of being able to make context-bound descriptions in the FR.

Attaching photos to contexts is much, much, much easier in the FR that in the recording app. It's just easier to see them and see what you're looking at - I keep having these little tiny boards to read and in my browser I can just zoom in. There is no way I'm not going to be doing this for attaching photos.

It's also at that point that I know what they show. So I type the description, say "closing shot OP 145, 29 XII 2008" right then. 

But of course that's a context independent description because that's what I have in the file repository, and so back in FM I get just big lines of undescribed images. It would be a major pain in the butt to add a context-bound description at that point and I never bother.

Is this really a problem for me as an archaeologist? Not particularly - I don't expect to use these data in the recording app in the end, and in Q&V it doesn't matter - I see my images with my descriptions in my contexts just the way I want to. But I bring to your attention that it is then an inconsistency, where we get what is in effect precisely the same kind of data in two different places.

**Comment by urapadmin** [comment]
there is really no way to do this in Kiosk in the file repository. You rather get me to regret that I ever allowed adding contexts in the file repository. That option doesn't belong there, either. 

So if you want to improve the. buap workflow you have two possibilities: a) add something to the recording app or b) add a Buap specific module to Kiosk. Whatever that would look like. a) is the only right choice given our current architecture. Kiosk is not for recording data. That's the path we chose.

**Comment by lbestock** [comment]
Hm I think I want to do nothing. The BUAP workflow is really good from my perspective after I thought about that. Only that the same type of description happens in two different places, but that doesn't trouble my archaeological heart as much as I expected it to trouble your developer's heart. There is no imaginable way it could be even half as easy in the recording app, and please do not take away contexts in the file repository! For a legacy project that is a total lifesaver, I do not really see how else one would get masses of photos attached to their contexts and it will be so very useful to have them there.

**Comment by urapadmin** [comment]
so, what about showing the context independent description in the recording app somewhere? I am not sure where. it could be shown in its context but then what if there is a context-dependent description as well, or rather: What if you want to add one. 

The image annotation module, which is really 3/4 of a recording app, will at least have the necessary tools to do something like this in Kiosk itself. I am just not getting even to start it.

**Comment by lbestock** [comment]
I suppose it would address the issue if, when there IS a context independent description and NO context dependent description, the former gets displayed wherever the image is. 

The only place I miss it is in the narrative/image tab where there are so many images and it's not easy to tell what is what. I don't miss it the same way in loci.

But: this is not a good use of time. The image annotation module is a good use of time. I closed this for a reason.

**Comment by urapadmin** [comment]
adding the context-independent description to the recording app has always been on my mind. Same with image tags. So that is worth a ticket for the recording app and unlike the other requests in this ticket it would not consume weeks of my time.
So that one I save: #2984
