### ISSUE TITLE
Kiosk/heading for Director's View still says Query and View

### ISSUE THREAD

**Issue by lbestock** [arch-kiosk/arch-kiosk-office#2985]
Just noticed in BUAP that the heading when I went to Director's View from Query and View stayed at Q&V.

![image](https://github.com/user-attachments/assets/cd29eff2-945e-458c-92e1-3cbdde2d67da)

**Comment by urapadmin** [comment]
### Kiosk 1.6.7.1
- that is fixed

**Comment by luizaogs** [comment]
I assume I can test this in PVD? It wouldn't have been a BUAP only thing?

**Comment by urapadmin** [comment]
yes, that was a general bug (and director's view just always said Query & View, no matter where you came from)

**Comment by urapadmin** [comment]
just looked at it. It's fine now.
