### ISSUE TITLE
recording: when should a record appear in recently changed?

### ISSUE THREAD

**Issue by luizaogs** [arch-kiosk/arch-kiosk-office#2986]
Question. Was testing #2944 and realized that the locus record I modified did not show up in the recently changed tab of find stuff immediately. In fact I could not see it at all until I synchronized and downloaded the database again (in this case on a different day because of a different timezone). Is that as intended? Or should a modified record show up there immediately?

**Comment by urapadmin** [comment]
no, that is not intended. Your local changes should appear in the recently changed search on top. 

By the way, the recently search does show time if the date is the same as the local today, so you should be seeing the time of your local change and not the date.


And I was not able to reproduce it easily. 
What exactly did you change about that locus? E.g. I am not looking at locus details (architecture etc.). But I am looking at relations and photos. 

Well, theoretically time zones can have an impact here, but I doubt that is what you were seeing:
If iPad A changed a lot (more than 10 identifiers) in Berlin and you are downloading that in Los Angeles the wristwatch time is 9 hours ahead of you. So for 9 hours none of your local changes would make it. That's yet another interesting case that shows that there is no single good way to deal with timestamps of different time zones.

**Comment by luizaogs** [comment]
I changed the locus description of locus 222 in LA. Just reopened it and it still doesn't show up in recently changed, though the locus modified time in the locus record is correct.

I still have the database, if you want it - not sure that would help.

**Comment by urapadmin** [comment]
and that one you did not sync?

**Comment by luizaogs** [comment]
Oh I did, I just kept the old database so I could compare if need be. This is the change that showed up correctly in #2944

**Comment by urapadmin** [comment]
Thought about it some more. While it is true that there isn't one perfect answer to this - it depends on the use case - I think it is better to favour the correct order over coherent displaying it. In the end one wants to see the recently modified records and ones own just applied changes should be at the top. 
So: I will order by the modified time stamp in terms of the user's current time zone. The disadvantage will be that my changes in Berlin will show up lower down in the list (compared to your recent change in LA) although they are even in the future (according to what is displayed)

**Comment by urapadmin** [comment]
> Oh I did, I just kept the old database so I could compare if need be. This is the change that showed up correctly in #2944

The database you have there, is that the one you last uploaded? In that case I can access it.

**Comment by luizaogs** [comment]
Should be.

**Comment by urapadmin** [comment]
okay, please don't upload anything. I'll look at it.

**Comment by luizaogs** [comment]
I think this was my iPad dock rather than my Mac but admit that I'm not 100% sure. It should be the last thing uploaded by me in either dock.

**Comment by urapadmin** [comment]
can you show me the record info of that locus so that I can be sure I am looking at the right one?

**Comment by luizaogs** [comment]
The change I made was the last line of the description (which, apparently I still think we're in October. Cool).

<img width="1030" alt="Screenshot 2024-11-09 at 8 50 04 AM" src="https://github.com/user-attachments/assets/7820c7fa-b8f8-43ea-80ce-91a94aac1cf1">

**Comment by urapadmin** [comment]
got it. It even shows up with the WRONG time stamp in the recently changed list.

**Comment by luizaogs** [comment]
The 31st? Not sure that's wrong -- I have been using this locus to test stuff for the past few weeks, and it's very possible that the second line of the description was from a synchronization on that day.

**Comment by urapadmin** [comment]
### recording app 16.5.3
- So the whole "recently modified" needs a thorough test again, even independent of time zones. Please test with different record types: unit, locus, collected material. 
- changes in dayplans or narratives would not have marked the unit as changed. I have added that. locus_architecture and deposit etc. are still not marking the locus as changed. The code just gets too baroque and slow.
- hidden loci were listed - they should not be
- as for the original issue:
the list is ordered descending by the modified time stamp in terms of the displaying user's current time zone (so NOT the wristwatch time!). The advantage is that the order reflects the succession of events independent of any time zones. The disadvantage is that changes in Berlin will show up lower down in the list (compared to the more recent change in LA) although they even read as if in the future (according to what is displayed). 

This is a lot of torturing ones brain for a rare use case. But I want to get this right.

**Comment by luizaogs** [comment]
I THINK this is ok?

![Image](https://github.com/user-attachments/assets/d70768f1-c539-4952-ad7f-ec9a1ff24f59)
