### ISSUE TITLE
recording: scrolling not working in search on the iPad

### ISSUE THREAD

**Issue by luizaogs** [arch-kiosk/arch-kiosk-office#2987]
I can no longer scroll down the list of results in the search function on my iPad. I can do so on my Mac.

**Comment by urapadmin** [comment]
hm. I don't see what I could have changed for that to happen. What if you click once into the list. can you scroll then?

What FM Go are you using?

**Comment by luizaogs** [comment]
Ah yes, clicking on the header enables it. Is that ok then? 

FM Go 20.3.1.31

**Comment by urapadmin** [comment]
ja, unfortunately that is the old FM thing with having to click twice when I use a browser inside FileMaker. 
Nothing I can do about it.
