### ISSUE TITLE
admin

### ISSUE THREAD

**Issue by Mina-nk** [arch-kiosk/arch-kiosk-office#2989]
I am trying to log as admin to do some changes but authentication is failing. Any ideas?

**Comment by urapadmin** [comment]
you try to log in as admin into Kiosk itself or into the FileMaker recording app? 

I just logged in as admin to arch1900.arch-kiosk.brown.edu and it worked fine. 
The password for the local admin should be still admin, unless @lrn5 has changed that password? I doubt it, though.

**Comment by urapadmin** [comment]
have you figured it out or does the issue remain?

**Comment by Mina-nk** [comment]
All is well! Thank you! I had the wrong password, but Leah came to the rescue.
