### ISSUE TITLE
Kiosk/Recording: unable to deselect an option for soil compact type

### ISSUE THREAD

**Issue by efinn27** [arch-kiosk/arch-kiosk-office#2990]
Within the deposit description, if you select soil compact type but decide you no longer want to record anything in that space (so not just change the type, but revert back to the blank space it starts as) you can't do that. There does not seem to be a way to either unselect the current type or select the blank space again. I don't know if this impacts any of the other drop-downs either in the deposit section or elsewhere. 

Thank you!! 😄

**Comment by urapadmin** [comment]
good point. That is currently indeed not possible in this particular field.

**Comment by urapadmin** [comment]
@lbestock 
What we do have, though is "not observed". Isn't that semantically the same as not selecting anything?

**Comment by lbestock** [comment]
Aha, yes, that would work here. Let's implement that as a best practice in BUAP.
