### ISSUE TITLE
import error with a BUAP file sent via Bridge

### ISSUE THREAD

**Issue by lbestock** [arch-kiosk/arch-kiosk-office#2991]
@efinn27 just used Bridge for the first time so she could use her iPad to make photos of context sheets. The upload went fine. I just attempted to import and got this:
<img width="1482" alt="image" src="https://github.com/user-attachments/assets/dd4d8c0a-fbd5-4bb0-9b47-0c83a282ce7c">

**Comment by urapadmin** [comment]
FileMaker hiccup. I just repeated it and it went through.
