### ISSUE TITLE
Kiosk / recording app: BUAP import with warnings

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#2993]
@lbestock 
What was that? 
![image](https://github.com/user-attachments/assets/4e0efdaa-a61a-4daf-8706-c8e9d8eb24ee)

**Comment by urapadmin** [comment]
the files are actually not in the file repository.

**Comment by urapadmin** [comment]
okay, yours

**Comment by lbestock** [comment]
Bloody Filemaker compatibility. I will take care of it immediately before I forget. After I make an ANC gimlet.

**Comment by urapadmin** [comment]
can we close this?

**Comment by lbestock** [comment]
We can!
