### ISSUE TITLE
requests for stratigraphic studio interface

### ISSUE THREAD

**Issue by lbestock** [arch-kiosk/arch-kiosk-office#3002]
When I get the "these locus relations have missing information" I always expect those to be things I can click on and go to the record for that thing. Is it possible to make it so those jump one into Q&V for the record in question?

And maybe a key for the icons? I don't remember what they mean/why my relation is a problem! I do want to be able to know that when I am stratigraphic studio but am also thinking about what workflow would be to go in and check and change it.

**Comment by urapadmin** [comment]
- see #2524

**Comment by lbestock** [comment]
Closed as duplicate.
