### ISSUE TITLE
file picking: rule that addresses the modified field

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#3005]
the idea is to include only images that have been modified / added in the last xyz days.
I don't think we can do that already, or can we? What does the existing date rule address?

**Comment by urapadmin** [comment]
### Kiosk 1.6.9
- new file picking rule: DAYS_OLD: 
- DAYS_OLD < 5 would produce files that have been MODIFIED after the current date - 5 days. 
- DAYS_OLD > 5 would produce files that have been MODIFIED before the current date - 5 days. 
- documented here: https://wiki.arch-kiosk.brown.edu/urapdev/doku.php?id=manuals:developer_manual:file_picking#rules_types

**Comment by luizaogs** [comment]
Would it be possible to test this in BUAP? Since we don't have a regular flow of data into PVD.

**Comment by urapadmin** [comment]
I'd rather not as it has the potential to screw things up (like all of a sudden NO images get transported or some such). First we need to know that it does not have such catastrophic results. Then we can try BUAP.

**Comment by luizaogs** [comment]
Note for myself: DAYS_OLD > 5 worked in PVD.

**Comment by luizaogs** [comment]
Question for Lutz: I can't remember. If images are dummy images as a result of file picking, do they not show up in the image gallery in FM? My gallery is currently empty.

**Comment by luizaogs** [comment]
Does it always have to be 5 days? I tried DAYS_OLD < 30 in PVD because as I mentioned above testing this with only 5 days is not possible there currently, and that definitely did not work. I have a bunch of images in FM, and there's no way they were all modified in the last 30 days.

**Comment by urapadmin** [comment]
> Question for Lutz: I can't remember. If images are dummy images as a result of file picking, do they not show up in the image gallery in FM? My gallery is currently empty.


dummy images never show up in the gallery.
dummy images without a description don't even show up in any image list.

**Comment by urapadmin** [comment]
> Does it always have to be 5 days? I tried DAYS_OLD < 30 in PVD because as I mentioned above testing this with only 5 days is not possible there currently, and that definitely did not work. I have a bunch of images in FM, and there's no way they were all modified in the last 30 days.

no, it should of course use your value. It might not work properly.

**Comment by urapadmin** [comment]
I am a bit puzzled. You current rule is setting all images that have been modified in the last 30 days to dummy. Is that what you wanted? Apart from that all context-bound images would be visible (low). So from my point of view you should see a lot of images in your gallery.
What actual rules were you employing?

**Comment by luizaogs** [comment]
I misunderstood what the rule is supposed to do, I suppose.

**Comment by urapadmin** [comment]
it is more that the rule interacts with the other file picking rules the way all file picking rules do.
I would of course learn from your misunderstanding.

**Comment by urapadmin** [comment]
but for now I have tested it myself on PVD and it did what it was supposed to. So I close this.
Unfortunately it doesn't serve the purpose for BUAP that I thought it would. But that is a different misunderstanding.
