### ISSUE TITLE
new record type and interface: archival material

### ISSUE THREAD

**Issue by lbestock** [arch-kiosk/arch-kiosk-office#3007]
I had a 4am thought stemming from our experiences in the archives coupled with Gunnar's request for ink inscriptions on Aha jars. It is a large task but also one that would make a major difference to the usefulness of Kiosk for archival projects well beyond Abydos (I'd use it immediately for BUAP and ANC).

The physical records are objects in and of themselves and their physical and intellectual management should be handled in Kiosk. Can we create a proper numbering system for boxes, individual notebooks, binders of slides, CDs, and an interface to manage them? 

I see the need, as with excavated objects, to use a number to link the physical thing itself and the information gotten from it. And rather like artifacts, that there will be initial observations and physical management of the things, followed only later by detailed study, is relevant. I want to be able to give a brief (and then searchable) description of the notebook and what is in it long before students enter the data into the context recording. It will help me figure out where to go for particular information while we're still in the data entry process, will help us keep track of who is doing what and what is done (I'll be able to see if a season is finished, for instance, quite easily), and will help going forward with the physical archives and their maintenance.

It has to be separate from the types of recording we already have, is why it is a big deal. Not a number of a notebook appended to the context record that was created when someone was reading that notebook, a record entry type for the notebook itself, not hierarchical under anything else. And the ability to link it to the OPs and loci in it once those are created. It would even be handy to be able to create the OPs from the notebook record, much like we can now create loci from the relationship - that's where one encounters it first. Many notebooks contain multiple OPs. Many OPs are spread across multiple notebooks, too.

As a first thought, the archival entity interface would need to have: an identifier, a "type" (notebook, 1:20 plan, CD, etc), a description field, a location field, start and end dates, a registration-like workflow manager (assigned to, entered into Kiosk, the like), a condition field, and some way to link it to the identifiers of archaeological stuff that it recorded. Archival entities themselves need to be able to link to other archival entities as they will sometimes be nested - a box will contain notebooks and slides, for instance, and a CD will have scans of notebooks. 

This would really help us keep track of what has already been scanned, too, so we know when we don't have to look at the physical materials anymore.

The semantics of the number would matter much less once it is possible to have data attached to them otherwise.

**Comment by urapadmin** [comment]
if you want that for BUAP and Abydos in the next 6-12 months we would have to implement it in FM although it doesn't sound like something one does in the trench

**Comment by urapadmin** [comment]
config key for type of archival entity: valuelist_archival_entity_type

**Comment by urapadmin** [comment]
this is getting more complicated than I first thought. Implications so far:

- you might want to add images to archival entities in the file repository 
- or even by file import? That is only possible with archaeological identifiers
- file picking rules that pick up images based on identifiers only work with archaeological identifiers

**Comment by urapadmin** [comment]
I am wondering if we want something like "season" or so. I remember that dates and particularly years were confusing. Though this ties into #981 and I never really had a good idea how to deal with seasons. In the end one would need a list of seasons managed in a separate table that one could relate to. Making it much more complex but it would come with the benefit that I could start using it in the future in other places.

**Comment by urapadmin** [comment]
### recording app 16.6
- this is available now 
- and has only one config key for type of archival entity: valuelist_archival_entity_type
- this needs a thorough test for navigation (back and forth, jumping to a archival item in the navigation menu etc.)
- there is a file container that wants proper testing, too.
- IT also has a pin board and all kinds of buttons in the menu. Not all of them might make sense (totally forgot about temporary free input), yet, so please report.

NOTE: IT WON'T SYNC, YET! I want you to test it first. If that results in changes to the database structure I don't have to do things twice.

**Comment by lbestock** [comment]
There are two configuration keys! 
Also the ID method one. I am setting it to free input but that is also specified as free input of an archaeological identifier, and this isn't an archaeological identifier it is free input of a non-archaeological identifier. That doesn't matter, right?

**Comment by urapadmin** [comment]
just  names

**Comment by lbestock** [comment]
The team members interface is lifted straight from fieldwork. This is a risk because it makes it look like it is the place for entering information that is IN the record, and that is not the point. So we want to think about this. Is this really needed at all? Is it not in the log in the way we envision using this? If we do want it we want it separate from fieldwork. Otherwise the roles look like the ones of people in the notebook, and what we mean here is who was assigned this notebook to input things into Kiosk. 

I do indeed want to be able to sort archival entities by those to whom they have been assigned. But I think a text search in the log does that better, no? 

Currently the text search in the menu does not catch things in the log. I expect that (and want that) to search both the content overview and the log.

The text search needs a "clear" button. And right now if I manually clear a search that did not result in any hits, I am taken back to some other archival entity than the one I was in when I performed the search. That is not what I expect.

**Comment by lbestock** [comment]
What is the number field below the identifier? It is prepopulated with "1" and cannot be modified.

**Comment by lbestock** [comment]
I would even think getting rid of "team members and roles" on the landing tab and deleting the content description tab and moving that field to the initial tab would be better. It throws me a bit not to get to the description of the content, which is paramount, until the second tab.

**Comment by lbestock** [comment]
"Who" in the activity log is a little confusing because often enough that will be two people: person doing the assigning, and person to whom it is assigned. As in - I open the box and see it has 16 notebooks in it. I am going to give half of them to Livia and half to May and I want to note that in the activity log. Am I the person, or are the people Livia and May?

**Comment by lbestock** [comment]
Image description runs on top of the image awkwardly:
![image](https://github.com/user-attachments/assets/bb08a169-1a4f-4b25-8151-76c599e72a92)

**Comment by lbestock** [comment]
Temporary free input as admin to change an errant number would be very appreciated. (It looks like it is there, but when I login as admin and try to change a wrong number I cannot.) One makes wrong numbers with free input in the first place. There are sound reasons to use digital recording.

**Comment by lbestock** [comment]
The need to come up with a naming/numbering convention that makes sense remains severe.

**Comment by lbestock** [comment]
There is no tag for these images in the file repository yet, I find them just as candids. (I suspect you just haven't gotten there yet, just noting things I see. And about to end with that because I'm wiped out and not testing well.)

**Comment by urapadmin** [comment]
> Image description runs on top of the image awkwardly:

I don't call that akward, I call that a compromise. The option would be to make the image even smaller and so I decided on this compromise where you can see both the image and the text.

**Comment by urapadmin** [comment]
> The team members interface is lifted straight from fieldwork. This is a risk because it makes it look like it is the place for entering information that is IN the record, and that is not the point. So we want to think about this. Is this really needed at all? Is it not in the log in the way we envision using this? If we do want it we want it separate from fieldwork. Otherwise the roles look like the ones of people in the notebook, and what we mean here is who was assigned this notebook to input things into Kiosk.

the purpose of that is indeed to mark who wrote the notebook, recorded the CD, packed the box .... So that IS the point.

**Comment by urapadmin** [comment]
You are still trying to use this to model the workflow with your team. I still think you should not do that because that is what will make the UI feature baroque. It creates yet another channel for communication and the more complicated of your requests (e.g. search in the activities) stem from that. We have a to-do feature if you need to manage tasks with them. I would rather not replicate that here again. Too many redundant features for me.

The activities are finished activities so that one knows later on who did something with a box or Journal and what the result was,  but not necessarily at what stage a running task is and what tasks are planned.

**Comment by urapadmin** [comment]
> The need to come up with a naming/numbering convention that makes sense remains severe.

That needs an apt identification method if we cannot use any of the ones we already have. Do you want to try my idea of a free input prefix plus running number combination?

**Comment by urapadmin** [comment]
### recording app 16.7 / Kiosk 1.6.11
- tagged now as "archival_entity", which is also the recording_context a.k.a record type (immaterial).
- strange number field gone
- clear button for filter text
- temporary free input activates the identifiers in the list for editing. I hope that's enough for now. If we get a domain involved here I will have to complicate matters here.
- the new "idgen_prefixed_serial" identification method is documented here: https://wiki.arch-kiosk.brown.edu/urapdev/doku.php?id=manuals:developer_manual:context_identification_-_generation_functions#idgen_prefixed_serial 
- the settings (that I'll apply to BUAP and ANC one day) for this identification method for the archive are:
 
![image](https://github.com/user-attachments/assets/323f758c-49ac-466c-880c-12dc4a2bd7f6)

- currently I will format the number to have three digits with leading zeroes, but that can be changed in the config.
-syncs now with Kiosk 1.6.11

**Comment by urapadmin** [comment]
> "Who" in the activity log is a little confusing because often enough that will be two people: person doing the assigning, and person to whom it is assigned. As in - I open the box and see it has 16 notebooks in it. I am going to give half of them to Livia and half to May and I want to note that in the activity log. Am I the person, or are the people Livia and May?

this is really where you are trying to use this as a GitHub. Although you can add several people here or whatever you want to add by just typing, I rather want a single person here reporting what happened to the activity. And if Livia and May were assigned the same task they nonetheless report independently. Everything else is a mess imo. So if you keep insisting to use this as a to-do list, which is isn't: Make two records. One for Livia and one for May.

**Comment by urapadmin** [comment]
> The text search needs a "clear" button. And right now if I manually clear a search that did not result in any hits, I am taken back to some other archival entity than the one I was in when I performed the search. That is not what I expect.

It'll get a clear button BUT you are always taken to the first record in the list if you change filters (searching is a filter) etc. No matter if your filter leads to records or none at all.

**Comment by luizaogs** [comment]
I assume this is still a @lbestock test, but if all that is needed now is making sure the newest changes are implemented and you'd like me to do it, just let me know.

**Comment by urapadmin** [comment]
- no, this is fully implemented now and you may give it a go

**Comment by luizaogs** [comment]
Filtering by team member only works with initials, not full names. Is that ok?

**Comment by luizaogs** [comment]
Problem. Searched for a term in the log rather than the description, got the warning that no records were found. Which is fine, I think, based on your response above. But now I'm stuck on a screen like this: 

![IMG_777D0FADD283-1](https://github.com/user-attachments/assets/04296e19-7396-4ed2-90b7-80a289090eee)

And if I click anywhere I get this: 

![IMG_1DE49B829E49-1](https://github.com/user-attachments/assets/0261142b-774c-4eb1-b915-ad13de9b097f)

Ah if I click on the plus button it does let me add a new record, even though the plus button is grayed out as in the first screenshot above. Clicking on the back arrow also lets me go out of the module. If I then go back in, my search word is still in the box but now everything looks ok: 

![IMG_0479](https://github.com/user-attachments/assets/10bf2d79-3044-4976-8592-36b79eeb050f)

**Comment by luizaogs** [comment]
Weirder. Logged out, logged back in as admin to test the free input, and as admin I see no records in the module. If I click anywhere, I get the same "no records are present" warning in the screenshot above.

If I click the minus/clear button in the search box I can then see my records, but there was nothing typed in there so I should have been able to see them without doing that, I expect.

Huh. Now I logged out and logged back in as admin again, and now things are there. I'm confused.

**Comment by luizaogs** [comment]
The rest of what you list above, including synchronization, is working. 

I cannot test the new ID method though since this is not rolled out to BUAP.

**Comment by urapadmin** [comment]
> Filtering by team member only works with initials, not full names. Is that ok?

yes

**Comment by urapadmin** [comment]
> The rest of what you list above, including synchronization, is working.
> 
> I cannot test the new ID method though since this is not rolled out to BUAP.

but you are testing it - it is the same that is rolled out to PVD. I just need to remember that I configure BUAP to have it as well.

**Comment by luizaogs** [comment]
Then it's not working. There was no serial number generated, it was just fully free input for me.

**Comment by urapadmin** [comment]
![image](https://github.com/user-attachments/assets/3bc87bd2-a79f-420b-bff9-44c222cc23a0)
That is FileMaker having contortions and it is beyond my influence. Looks like it has memory issues or so. iPad? MacOS?

The stupid default message "no records are present" cannot be suppressed or altered. There have been discussions on that ever since in the FM Boards since version 12 and guess what, they never do anything about it. So with that one we have to live. But it is just dumb, not harmful.

**Comment by urapadmin** [comment]
Currently I don't clear the filters when leaving the layout. It is always a conundrum. There are use cases where you would want your filter to be stable (e.g. going somewhere and returning) and where you don't.

> Weirder. Logged out, logged back in as admin to test the free input, and as admin I see no records in the module. If I click anywhere, I get the same "no records are present" warning in the screenshot above.
> 
> If I click the minus/clear button in the search box I can then see my records, but there was nothing typed in there so I should have been able to see them without doing that, I expect.
> 
> Huh. Now I logged out and logged back in as admin again, and now things are there. I'm confused.

I will make sure that the filters get properly cleared when re-opening the app.

**Comment by luizaogs** [comment]
> ![image](https://private-user-images.githubusercontent.com/38838314/392155081-3bc87bd2-a79f-420b-bff9-44c222cc23a0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzMyNjQ4NTEsIm5iZiI6MTczMzI2NDU1MSwicGF0aCI6Ii8zODgzODMxNC8zOTIxNTUwODEtM2JjODdiZDItYTc5Zi00MjBiLWJmZjktNDRjMjIyY2MyM2EwLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjAzVDIyMjIzMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA3NzVhMjNjZWNjMDdjNTVkY2MwZmVkZWIxNjk5MDZlNzgyNWQ0NTRiY2E3M2ViZDQ4MDczM2RhZTk5YTg4MGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.xMkv7zz_d6RtJcZg_8fH6D-oga8kg-uZ31kYfI-03UQ) That is FileMaker having contortions and it is beyond my influence. Looks like it has memory issues or so. iPad? MacOS?
> 
> The stupid default message "no records are present" cannot be suppressed or altered. There have been discussions on that ever since in the FM Boards since version 12 and guess what, they never do anything about it. So with that one we have to live. But it is just dumb, not harmful.

iPad.

**Comment by urapadmin** [comment]
> 
> iPad.

keep it in mind, in case it happens again and then again. But from how it looks I'll treat it as a temporal peculiarity for now.

**Comment by urapadmin** [comment]
> Then it's not working. There was no serial number generated, it was just fully free input for me.

odd. I could have sworn I synchronized my changes yesterday. However, I have configured the new id method again and this time I have synchronized. Once you prepare your dock again it should work. (But I'll also release a new version in a few minutes)

**Comment by urapadmin** [comment]
### recording app 16.7.1
- addresses the issue that filtes kept being active even after closing the database.

**Comment by luizaogs** [comment]
> > iPad.
> 
> keep it in mind, in case it happens again and then again. But from how it looks I'll treat it as a temporal peculiarity for now.

Yeah, this happens every time I search for a term that leads to no records.

**Comment by luizaogs** [comment]
But the rest is ok, so I guess I will close this?

**Comment by urapadmin** [comment]
no, not if this happens always. We need to test this on a different iPad then. 
@lbestock - what about yours?

**Comment by lbestock** [comment]
I have tested this now on two different iPads and I do not get the FM going bonkers issue, just the inescapable "no records" result.
iPad mini iOS 18.1.1, FM go 21.1.1.36
iPad pro iOS 18.1.1 FM go 21.1.1.36

**Comment by lbestock** [comment]
I have battled Github and 2FA crap and now can at least be on Github on those iPads. Wow that was painful.

I have thoughts about the filter searching for team members issue and their inclusion in the list with the team members, however. Like yesterday on the train to NY when I wanted to be on Github but couldn't from an iPad and didn't have my computer. I can actually search in the filter for people by name who are in there but not in there with initials. I made a bunch of records where Ramadan was attached to the team members. This is real life - Ramadan was one of the guftis on BUAP and the excavators he worked with had no idea what his initials were but they certainly recorded his presence and rightly so. I haven't created "gufti" as a role yet but I will before any real records are made. I can use the filter to filter results by Ramadan, but when I use the pop up to connect people, because he has no initials, I have to type his name each time. Which risks mistyping and thus rendering improper results in the filter.

**Comment by urapadmin** [comment]
> I have battled Github and 2FA crap and now can at least be on Github on those iPads. Wow that was painful.
> 
> I have thoughts about the filter searching for team members issue and their inclusion in the list with the team members, however. Like yesterday on the train to NY when I wanted to be on Github but couldn't from an iPad and didn't have my computer. I can actually search in the filter for people by name who are in there but not in there with initials. I made a bunch of records where Ramadan was attached to the team members. This is real life - Ramadan was one of the guftis on BUAP and the excavators he worked with had no idea what his initials were but they certainly recorded his presence and rightly so. I haven't created "gufti" as a role yet but I will before any real records are made. I can use the filter to filter results by Ramadan, but when I use the pop up to connect people, because he has no initials, I have to type his name each time. Which risks mistyping and thus rendering improper results in the filter.

so add him to the team?
- which reminds me of #2920

**Comment by urapadmin** [comment]
> > > iPad.
> > 
> > 
> > keep it in mind, in case it happens again and then again. But from how it looks I'll treat it as a temporal peculiarity for now.
> 
> Yeah, this happens every time I search for a term that leads to no records.

iOS version, iPad version, FM Go Version?

**Comment by lbestock** [comment]
> so add him to the team?
> 
> * which reminds me of [recording app: rethink team members UI #2920](https://github.com/arch-kiosk/arch-kiosk-office/issues/2920)

I thought the whole point of the team members and their roles was that one could add people who were not team members in the FM login sense. I cannot make Ramadan a team member because I don’t know his initials. He doesn’t need a login, he just needs to be added consistently as a Gufti in the “team members and their roles”.

**Comment by luizaogs** [comment]
> > > > iPad.
> > > 
> > > 
> > > keep it in mind, in case it happens again and then again. But from how it looks I'll treat it as a temporal peculiarity for now.
> > 
> > 
> > Yeah, this happens every time I search for a term that leads to no records.
> 
> iOS version, iPad version, FM Go Version?

iOS 17.7, FM Go 20.3.1.31, recording 16.7.1.

**Comment by urapadmin** [comment]
> > so add him to the team?
> > 
> > * which reminds me of [recording app: rethink team members UI #2920](https://github.com/arch-kiosk/arch-kiosk-office/issues/2920)
> 
> I thought the whole point of the team members and their roles was that one could add people who were not team members in the FM login sense. I cannot make Ramadan a team member because I don’t know his initials. He doesn’t need a login, he just needs to be added consistently as a Gufti in the “team members and their roles”.

So you either type his name in whenever needed or you make him a team member and use his name where you usually type in initials. That team member's user ids are initials is a convention but not a rule. I really don't see what else to do here for this special case.

**Comment by urapadmin** [comment]
> > > > > iPad.
> > > > 
> > > > 
> > > > keep it in mind, in case it happens again and then again. But from how it looks I'll treat it as a temporal peculiarity for now.
> > > 
> > > 
> > > Yeah, this happens every time I search for a term that leads to no records.
> > 
> > 
> > iOS version, iPad version, FM Go Version?
> 
> iOS 17.7, FM Go 20.3.1.31, recording 16.7.1.

how much other apps are potentially draining memory in the background? This does look a bit like a memory issue.

**Comment by urapadmin** [comment]
@lbestock I would roll this out now to BUAP, okay?

**Comment by luizaogs** [comment]
When testing I don't have other apps open. Other than Bridge, that is.

**Comment by lbestock** [comment]
Yes please! I have the BUAP girls coming by tomorrow to get more records to work on over the break. So it will be used immediately.

**Comment by urapadmin** [comment]
> Yes please! I have the BUAP girls coming by tomorrow to get more records to work on over the break. So it will be used immediately.

will do. What are the iOS and FM versions you are using on the ipads where you don't encounter Luiza's issues?

**Comment by lbestock** [comment]
> I have tested this now on two different iPads and I do not get the FM going bonkers issue, just the inescapable "no records" result. 

iPad mini iOS 18.1.1, FM go 21.1.1.36 iPad pro iOS 18.1.1 FM go 21.1.1.36

**Comment by urapadmin** [comment]
> > I have tested this now on two different iPads and I do not get the FM going bonkers issue, just the inescapable "no records" result.
> 
> iPad mini iOS 18.1.1, FM go 21.1.1.36 iPad pro iOS 18.1.1 FM go 21.1.1.36

Ah. Could you try to find an iPad with something < FM GO 21?

And Luiza, do you get this on FM GO21, too? (Let's leave iOS 18 beside for now)

**Comment by lbestock** [comment]
Wow five iPads on this sofa with me right now. Bonkers. I think I found one…

**Comment by urapadmin** [comment]
> > Yes please! I have the BUAP girls coming by tomorrow to get more records to work on over the break. So it will be used immediately.
> 
> will do. What are the iOS and FM versions you are using on the ipads where you don't encounter Luiza's issues?

I only saw now that your BUAP dock were in the field. I hope you made no changes, because importing that would be a pain,

**Comment by lbestock** [comment]
No nothing. It was to test something.

**Comment by lbestock** [comment]
For me. Were others?

**Comment by lbestock** [comment]
OK one of the big iPads hadn’t been updated. So: iPS 16.4.1 FM Go 19.5.2

No problem - I do not run into the @luizaogs crazy stuff above.

**Comment by luizaogs** [comment]
> And Luiza, do you get this on FM GO21, too? (Let's leave iOS 18 beside for now)

Yes, same issue using FM Go21 (21.1.1.36).

**Comment by urapadmin** [comment]
can you think of anything that sheds light on what causes it? Any steps that lead to it or don't? Does it happen immediately or onl on second attempt? What if you close Kiosk Bridge and try again? 
Have you tried restarting the iPad?

**Comment by luizaogs** [comment]
Restarted the iPad, only FM Go20 is open right now (Bridge is not open). 

I think I got it, or at least one way to cause it: if I search for a term that I know is not in any description and use the "next" key in the keyboard to do the search, this doesn't happen. It happens every single time I search for a term not in any records and click on the header, rather than using the next key, to get the search going.

So: clicking on "next" works fine. Clicking outside of the keyboard to run the search leads to the issue.

**Comment by lbestock** [comment]
Interesting.
That gave me stuff to try. So in FM 19 when I hit “next” after inputting a term I know won’t be there, it takes me to the “starts” field to put something there.
When I click on the header it simply tells me there are no records that match my criteria.

In FM21, hitting “next” gets me “no records” on a blank white page.
Hitting the update button in the header gives me the no records message, but not on a white page just against the view of the FM layout.

So I also get two different responses when doing those two things. I also get different differences in FM 19 and FM 21. And still I cannot produce what @luizaogs sees.

**Comment by luizaogs** [comment]
Still only with FM 20 open. 

Huh, I guess I forgot to note this above but I also see a difference in screens. When using "next" I get the no records message against a white screen. When clicking elsewhere (eg the header) I see the message in the FM layout, and that's when I get the weird blank buttons showing up after I click on "aha..."

(When I say header, by the way, I don't mean the refresh button. That also gives me the message on a blank screen but then everything looks normal once I click on "aha")

**Comment by urapadmin** [comment]
can you please give me a screen shot of the two different "no records" messages?

**Comment by lbestock** [comment]
![IMG_0078](https://github.com/user-attachments/assets/8ac152a9-3c51-4f88-9f25-3d318040ecf1)
![IMG_0079](https://github.com/user-attachments/assets/3aed7367-72c6-43a7-be11-aba5041d524f)

The top one is if I press “next” (return, I guess) on the keyboard. And below is if I hit the refresh button (now red).

**Comment by luizaogs** [comment]
I see the same variations, though as explained above in different circumstances than Laurel does.

**Comment by urapadmin** [comment]
different? How? You don't get the strange white background on Tab (next)?

**Comment by luizaogs** [comment]
I do. But I also get the blank screen when I use the refresh button, which Laurel does not.

**Comment by urapadmin** [comment]
would make more sense to me if you got the missing icons always together with the strange white background and Laurel would never get the empty background. But it is FileMaker. It does not make sense.

This is getting a nightmare ticket and since everything works except this here, I deem it closed and open up a new ticket for this particular phenomenon.

**Comment by urapadmin** [comment]
continued in #3012
