### ISSUE TITLE
Aha: configure web server and everything

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#3018]
our new server: abydos-kiosk dot brown dot edu
our first sub domains: test, anc and buap.

**Comment by urapadmin** [comment]
@arch-kiosk/test 
### 15/XII/24 - there it is
- test dot abydos-kiosk dot brown dot edu
- this is a completely new machine and the last time I have set one up was in 2018. So everything can happen  here. Please test.

**Comment by lbestock** [comment]
Funny: I have just logged in, and my tab in my browser is called "PVD Kiosk". Which is not accurate.

**Comment by lbestock** [comment]
Alright I am in there already as Doctora Laurel?! Ahmed said today that when he talks about Doctora Laurel, which has been a lot recently, everyone says "Souad!" It feels really lovely to be remembered warmly and with that name.

Connection with Bridge through download no problem at all. And now I shall sleep. Big day tomorrow. I'm glad this is up. It's in the work plan I have now formally filed with the Ministry of Antiquities, this Kiosking of Abydos :)

**Comment by luizaogs** [comment]
Did you want me to test this also, Lutz?

**Comment by urapadmin** [comment]
always!

**Comment by luizaogs** [comment]
This is really a test of the server rather than the recording, right? Because I currently can't add CM but I suspect that's configuration and irrelevant here.

**Comment by luizaogs** [comment]
I don't think I'm currently able to import anything into the file repository? At least this is what my full menu when in the repository looks like:

<img width="253" alt="Screenshot 2024-12-17 at 9 16 26 AM" src="https://github.com/user-attachments/assets/13e94904-59ef-4faf-91b5-a91625d77992" />

**Comment by urapadmin** [comment]
worth noting, but you are right, that's not a server issue unless cm wouldn't sync or so

**Comment by luizaogs** [comment]
> worth noting, but you are right, that's not a server issue unless cm wouldn't sync or so

Well I don't know because I couldn't add any, but the rest of what I uploaded synchronized.

**Comment by luizaogs** [comment]
Tested: 
docks (creation, deletion, disabling, enabling)
adding a user
synchronization
director's view
file repository (added a context, bulk tagged)
point repository
q&v
stratigraphy studio
log viewer

If I forgot something that is relevant let me know.

**Comment by lbestock** [comment]
I am also not able to import photos.

**Comment by urapadmin** [comment]
### 29.XII.24 10:21
- file import there now on abydos-test
- logo issues under control on abydos-test (see #3019 )

**Comment by urapadmin** [comment]
if importing photos is the last thing that didn't work on abydos-kiosk, I can start building the real anc.abydos-kiosk server space.

**Comment by lbestock** [comment]
Importing works with and without context. Do you need me to do a thorough run through of all possibilities, or with those working as expected are we good?

**Comment by urapadmin** [comment]
> Importing works with and without context. Do you need me to do a thorough run through of all possibilities, or with those working as expected are we good?

no, if it works at all it is enough for this test,

**Comment by urapadmin** [comment]
alright. Web-Server is ready for sub domains. This can be closed
