### ISSUE TITLE
kiosk: Logo not looking great on phone

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#3019]
![image](https://github.com/user-attachments/assets/d9d0376c-f1dd-49a8-8087-c2194726643d)

**Comment by urapadmin** [comment]
- not using an svg logo so far
- the whole header layout is, erm, old. That needs some closer look. It might also affect other projects that's why I am a bit careful here. It is for now tackled on test.abydos-kiosk (see #3018 )

**Comment by lbestock** [comment]
svg logo now in drive

**Comment by urapadmin** [comment]
I have changed it manually, but: There is a canvas around the logo that adds an enormous margin to it. When you export an svg in future please make sure that you export really only the rectangle around the visible parts.
