### ISSUE TITLE
filemaker should show where and when the last modification was made

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#368]
it needs to make a select on all the tables. Perhaps the transfer_repl_data table can help finding out the table names.

**Comment by urapadmin** [comment]
perhaps an option to go right back to that modification would be nice, too

**Comment by urapadmin** [comment]
### recording 12.16
I squeezed and twisted FileMaker into doing this:
- it shows the last x modifications, when and by whom and one can jump right back there.
- this fabulous new feature can be marveled at in the find button on the start page

How many of the last modifications are shown is set by the config key "visibility/history_something", I have forgotten what it's called. It's set to 10 currently.

**Comment by lbestock** [comment]
Very first thoughts.
This is pretty fantastic.
On an iPad I cannot scroll down to get all 10, I get only the first seven.
I made a new context and did a bunch of things in it, including making a new photo, new deposit info, etc. But not CM yet. But the "recently changed" shows two identical lines for the context itself, not photo. I am not sure if photo is something one would want to go back to really, but in any case one cannot yet.
![image](https://user-images.githubusercontent.com/49291909/166338554-8934cf8c-50ef-41ef-a2b7-0aeb23d633e1.png)

It strikes me that being able to sort by type would be great. Imagine the registrar did a bunch of CM at night. All those most recent records are CM then. But I am an excavator and I want to jump to the last context I was digging.

**Comment by urapadmin** [comment]
I can only show identifiers. Changing a locus photo is a change to the locus and so one can jump to the locus, not to the photo. Changing collected material photo a change to the collected material. It can thus happen that a cm or locus appears twice with slightly different dates. It would be quite complicated to change that so for the time being I can live with it. You may make a new ticket if you don't want to forget about it.

**Comment by urapadmin** [comment]
- [ ] the scrolling on the ipad is the only thing here that I would count as a bug. Bloody fm go. That means you also can only access 7 lines when you use the search, right?

**Comment by lbestock** [comment]
Correct, I can only access 7 lines.

**Comment by urapadmin** [comment]
- [ ] also not optimal: Instead of the real collected material type name I show the collected material type id. Has to be special find not small_find.

**Comment by urapadmin** [comment]
what operating system is this?

**Comment by luizaogs** [comment]
Sorry. Mac OS 12.3.1, Filemaker Pro 19.4.2, v 12.16.

**Comment by urapadmin** [comment]
It's just more Filemaker bugs I don't know how to battle. So I have resized that window so that more identifiers should become visible and the layout might behave slightly differently. On Windows there is a scrollbar when one is needed, so ...

As for the invisible label on Luiza's Mac I am clueless. It does not occur on Laurel's Mac.  OS: 12.1. FM: 19.4.2

**Comment by luizaogs** [comment]
I'm still having the issue on my Mac but if it works on Laurel's I guess we can ignore it? I see all 10 entries on my iPad now, so I think this is good.

**Comment by urapadmin** [comment]
first I'll look at another Mac to double check

**Comment by urapadmin** [comment]
while we can close this here I will keep the missing scrollbar in a new ticket:
