### ISSUE TITLE
cache subdirectories

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#376]
After having done it for the file repository itself we need sub directories for the cache next. 
see also #165

**Comment by urapadmin** [comment]
### Kiosk 1.2.8
Wasn't done, yet. Now it is:
- files are cached in subdirectories according to the first two digits of their uid
- the old way of organizing the file cache gets restructured by unpackkiosk

**Comment by luizaogs** [comment]
Seems to be just fine.
