### ISSUE TITLE
migration for urap: set terms for trench/area and locus for all units and numbering(?!)

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#418]

**Comment by urapadmin** [comment]
"terms" means that for urap all the new configuration settings and the new unit attributes need to be defined. So far in urap we called a locus locus - hardwired. Now we have to fill in the fields so that it is called locus again.

**Comment by urapadmin** [comment]
### @test: kiosk v0.7
A migration script should be doing this on the urap server. So you should only encounter the proper terms "unit" and "locus" for all existing units.

**Comment by lbestock** [comment]
As far as I can see this is fine.
