### ISSUE TITLE
customizable Locus: Architecture form?

### ISSUE THREAD

**Issue by lbestock** [arch-kiosk/arch-kiosk-office#433]
We discussed making the architecture form more customizable because, for instance, bricks are really not the standard building material most places.

**Comment by urapadmin** [comment]
No, we did not discuss that, finall. You wanted to think about it. There is always a balance one wants to find between customization and just leaving fields one does not need blank. However, please tell me what exactly has to be customizable about it.

**Comment by urapadmin** [comment]
now in #1375
