### ISSUE TITLE
locus relations: new field for chronological order

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#614]
we want to separate the chronological from the spatial relationship. But the spatial relationship should still trigger the chronological.
above should lead to later, below to earlier, adjacent to unclear, do we even need "same time"? 

Perhaps I can make the configuration of this so that it allows some keys to enforce the chronology and other to leave it to the user and just make a suggestion.
Above e.G. MUST be later then something BELOW. But is that as clear for abuts, let alone adjacent? 

While we want to allow for more than one spatial relation between the same two loci, we do not allow for to different chronological relations between them.

---
- [ ] document config keys
- [x] #1401
- [x] #1094 
- [x] #1414 
- [x] #1415 
- [x] #1416

**Comment by urapadmin** [comment]
we really need to document the examples Laurel gathered from Zach and Tyler because it was hard to come up with a compelling reason as to why we need to allow for two different spatial relations between the same two loci. I can't remember anymore, why.

**Comment by urapadmin** [comment]
is that related to #252?

**Comment by urapadmin** [comment]
have we finally decided to do this? I think so, right? In that case I would put it on the recording system 10 list.

**Comment by lbestock** [comment]
Oh yes, please - it has become more evidently important in recent days as I'm writing.

**Comment by urapadmin** [comment]
recording system 11 means January 2021 - just for the records (milestones are my attempt to time things).

**Comment by urapadmin** [comment]
see #1027

**Comment by urapadmin** [comment]
I wonder. Do really all spatial relations trigger a chronological relation? In many of the "same time" cases we might just not know. 
So we would rather need "unclear" or some such. Or just leave it blank.

**Comment by urapadmin** [comment]
in [https://github.com/tsdye/harris-matrix](https://github.com/tsdye/harris-matrix) there are typical problem cases related to Harris Matrices. We should look at them in depth and see if they already are issues on the level of recording the locus relations.

**Comment by urapadmin** [comment]
I will tackle this together with #791

**Comment by urapadmin** [comment]
but not for arch1900

**Comment by urapadmin** [comment]
@lbestock: Please review this in the light of FAIMS and Parker's project before I go implementing it.

**Comment by lbestock** [comment]
FAIMS allows one to set two or even more different relationships between the same two loci, and they do auto-generate the opposite relation. So S0001-3001 can be simultaneously above, the same as, and below S0001-3002. Why? Is that an archaeological decision? Parker tends to prefer smaller loci (no lots) so my expectation would be that these physical relations with their chronological implications would make Parker himself want to separate different loci in here rather than assign multiple relations between the same two loci. Time to copy Parker on a ticket.

**Comment by urapadmin** [comment]
> The FAIMS locus relations Parker was using are remarkably similar to ours but do not have a specified chronological component. I am wondering if we want this in the recording, or if what we really mean is how it builds a Harris matrix. As noted above, we do not allow two different physical relations between the same two loci.

for the Harris Matrix the important information is the chronological order. And there it is necessary, I think, that two loci have either no or exactly one chronological relationship with one another. Having locus A being above locus B and locus B being above locus A at the same time means that their chronological order isn't clear anymore. 

Allowing an additional input of a chronological order (in cases where the spatial relationship does not imply it) would be a prerequisite for the generation of a Harris Matrix later. And that was the idea here. If Parker wants it or not is from my point of view not the most important question. It's for everybody. Let's not get overly focussed on the needs of a single project.

**Comment by urapadmin** [comment]
config keys:
visibility/show_locus_relations_chronology
valuelists/valuelist_locus_relations_chron
valuelists/valuelist_locus_relations_spatial_to_chron

**Comment by urapadmin** [comment]
- opposite chronological relation depends on the value given to the relation in the form. 
- That can either be the default of the spatial relation or a value selected from the checkbox
- the default from the spatial relation is always applied if there is one.
- if there is no default the chron. value will not change
- the default will only be applied on selecting a new spatial value

**Comment by urapadmin** [comment]
### test: recording 12.1.0
see instructions above.

**Comment by luizaogs** [comment]
Kidding, I guess I don't close this since you're tracking stuff above.

**Comment by urapadmin** [comment]
@arch-kiosk/test short explanation for y'all:

> I guess I don't close this since you're tracking stuff above.

yes, you got that right. We close issues only if the tracked issues are done, too. Then one of us has a last review and if the original intend is met we close the whole thing. 

That's the general idea how to work on bigger issues and feature requests in the future. It also means we keep the tracking issues rather clean and single out detailed issues in new tracked issues. 

Unfortunately GitHub only properly tracks tickets that are in the body (the very first comment) so in future we also have to keep an eye on the body and add things to it.
