### ISSUE TITLE
pottery processing images no context  

### ISSUE THREAD

**Issue by lbestock** [arch-kiosk/arch-kiosk-office#628]
Images created in pottery processing on lines that do not have pottery numbers appear as if they have no context in the file repository. I am not sure if that is a bug or an oversight or how we want to deal with it.

![image](https://user-images.githubusercontent.com/49291909/82157998-ed0cca00-9852-11ea-8f38-a03df450b654.png)

And in detail:

![image](https://user-images.githubusercontent.com/49291909/82158003-f433d800-9852-11ea-9cc6-ce0133bfca0c.png)

They are found under a general search for pottery processing images, but there is no way to know either from the general view or when one clicks on them that they are associated with CM QA-002-1. (I have then attempted to see if they can be found by searching QA and have run into another problem, new ticket to be filed in half a minute.)

**Comment by lbestock** [comment]
#629 issue is what is preventing me from testing if a search for the context from which the pottery images come, QA-002-1 in this case, returns them.

**Comment by urapadmin** [comment]
### recording 9.1
the #629 issue can be solved by restarting the server for the time being. But this here has nothing to do with it. 
- [ ] If they don't have a pottery id, pottery photos will be referenced by the cm number.
- [ ] If do have a pottery id, they will be referenced by the cm number or the pottery number. 

In both cases the record type is pottery_photo or some such.
This behavior is also true within filemaker: 

- [ ] if a pottery photo does not have a pottery id, the gallery should show it only under the cm# and that gallery entry should also have the photo's description.

- [ ] if a pottery photo does have a pottery id, the gallery should show it with the pottery# and only that entry should have the photo's description. (It also answers to the cm#, but without the description)

**Comment by lbestock** [comment]
Not working properly in file repository. Those without a pottery number still think they have no context at all. Even those with a pottery number are not found in a search for the unit, and a search for QA-003 returned "identifier unknown". This is all URAP 0.7.4 after synchronizing records made on Alice in 9.2.

![image](https://user-images.githubusercontent.com/49291909/82597498-0f665680-9b77-11ea-92cc-10efb2808417.png)
(QA search, no pottery photos at all)

![image](https://user-images.githubusercontent.com/49291909/82597562-26a54400-9b77-11ea-8db1-aa9dc03124a3.png)
(pottery photos all - those without pottery numbers have not been given their CM as context, including those made since the update to 9.2/0.7.4)

**Comment by urapadmin** [comment]
that there are no pottery photos when searching for a unit is correct. Pottery is not in the scope of a unit. They only appear in the context of collected material (or pottery number).

**Comment by urapadmin** [comment]
see also #626

**Comment by lbestock** [comment]
Presumably this needs a rethink with the huge changes in finds and ceramics. PASU ceramic numbers are not recognized as contexts for directly assigned in the file repository.

**Comment by urapadmin** [comment]
Then please open a new ticket in which you follow the scheme: What is expected? What is the case? I suspect that su-ceamic based projects simply need a different kiosk configuration.
I'd say this here can stay closed.
