### ISSUE TITLE
narrative missing after synchronization (emoji problem?)

### ISSUE THREAD

**Issue by lbestock** [arch-kiosk/arch-kiosk-office#638]
First synchronization performed by LDB on the USTP Brown server. Downloaded, made one narrative and one image, uploaded. Sam had already uploaded. Synchronized. Did not pay attention to the synchronization log in detail but there were no red lines. Downloaded again. Sam's additions are there and the image is there and the narrative container is there with my initials and the date stamp. But the narrative itself is blank. Interestingly I had put in an emoji.

So next step: I repeat it all having made a new narrative that has no emoji.

This time I look carefully at the log and make a screen shot, and there is still no red and the warnings are mostly the same ones as last time (option gen_random_uuid() etc...)

And viola - the narrative without the emoji synchronized properly. Possibly we are meeting an old friend?

We're in kiosk 0.8 and FM 9.2.

**Comment by urapadmin** [comment]
The developer's log says "It was not that easy, but finally the data of the Uronarti Season 2015/16 made it into the master database. The last thing I had to battle was codepages. Because we had a little cute tentaculaire emoticon in the dayplan narratives python freaked out about what filemaker delivered. I had to set both explicitly on UTF-8. That was easy with python and - of course - an issue with filemaker. I had to switch the opening process of the filemaker database from pure connectionstring to a combination of creating a dsn first and then using that in the connection string. That is the only way to control the MultiByteString handling of filemaker. If one does not use a dsn, filemaker uses Latin1, no matter what. Hate.". I should check if that is still in place. I believe to remember that I made the call modes of filemaker configurable.

**Comment by urapadmin** [comment]
The code that fixed the issue when the Emoji was a tentaculair is still in place and active. I have to dive deeper...

**Comment by urapadmin** [comment]
we have to try to reproduce this. It is too long ago to find a useful log

**Comment by lbestock** [comment]
HA HA HA I didn't even HAVE to download it again. I mean I did, following my usual steps. But then I thought: hey wait, I can check on those narratives in the director's view without downloading my FM database again. So I did. There's my penguin emoji in my narrative where it belongs. In director's view. It did get messed up in re-exporting however and no longer looks like a penguin in FM. But at least the narrative is present.

How it looks in kiosk:
![image](https://user-images.githubusercontent.com/49291909/108296831-40a49f00-7168-11eb-9f43-e8ea06889df2.png)


How it looks on downloading after synchronization in FM (which is not what it looked like before synchronization):
![image](https://user-images.githubusercontent.com/49291909/108296906-6467e500-7168-11eb-9632-0697a5e2790b.png)

**Comment by urapadmin** [comment]
that is a different and less problematic issue. I wish you could repeat the old one. Did you perhaps use a different emoji?

**Comment by lbestock** [comment]
Almost certainly - there are nine zillion emojis and I did not note the first time which I had used.

**Comment by urapadmin** [comment]
however, it looks rather like an issue in fork. I'll look into that again.

**Comment by urapadmin** [comment]
I cannot reproduce the effect that the narrative is empty (which does not mean that there mightn't be a single emoji causing that issue, we just don't know which one).
But I can see that during fork or export to filemaker emojis get lost. 

That's okay with me, I postpone this until post-v1: Don't use emojis in archaeological recording!

**Comment by lbestock** [comment]
:) Oh wait, that's nearly an emoji, except that I have them not automatic on my keyboard. Note for administrators prior to seasons: before you hand out the iPads, do this:
Go Settings from the iPad main screen.
Tap General.
Tap Keyboard:
Tap Keyboards:
Tap Edit:
Tap the delete button next to the Emoji option:
Tap Delete.

Then tell your team not to add them back again, too.

**Comment by urapadmin** [comment]
It is important to make sure that this gets configured and communicated before the 2022 field seasons!

**Comment by lbestock** [comment]
The sequence of steps has been added to the questions guide.
