### ISSUE TITLE
making new tags needs improvement

### ISSUE THREAD

**Issue by myjaylee1123** [arch-kiosk/arch-kiosk-office#828]
when you're trying to add a new tag for a feature, you have to:
1) click edit tags (which is dumb - how can you edit a tag that doesn't exist?)
2) within edit tags you have to zoom out of the mini-popup screen in order to access the + symbol (god why i didn't see this the first time i was trying to make tags so i gave up)

this is gross

**Comment by urapadmin** [comment]
1. Although there is a subtle difference between "edit tag" and "edit tags" it might be clearer to call it "manage tags".
2. that one I don't understand. Can you show that on a screenshot?

**Comment by myjaylee1123** [comment]
![IMG_0362](https://user-images.githubusercontent.com/47072505/89739347-eb1b6700-da4d-11ea-9cac-969d5c9c835c.PNG)
Here is, of course, our beloved making tags popup.
![IMG_0363](https://user-images.githubusercontent.com/47072505/89739349-ec4c9400-da4d-11ea-83c5-5ca7ff639b6d.PNG)
Here, there is no + button visible. It's only because of a misclick I was able to zoom out and find this:
![IMG_0364](https://user-images.githubusercontent.com/47072505/89739350-ece52a80-da4d-11ea-8954-352892a8f238.PNG)
Making the window fit into the smaller space and making the user zoom IN to type would maybe be better?

**Comment by SamKimball-BrownU** [comment]
Info: it appears you are using the ipad in vertical. Is that right?

**Comment by myjaylee1123** [comment]
Yes. I can't really reach the entirety of the iPad without going vertical.

**Comment by SamKimball-BrownU** [comment]
This problem does not exist if you put it in landscape. Only vertical.

I do think it needs to be fixed, now that we support vertical orientation in the software. BUT, this is a tidbit to include in user manuals, that often times things look/act weird when in vertical orientation. Thus I'm marking it as user manual.

**Comment by urapadmin** [comment]
### recording 31.7.6
- "dumb" label improved
- popup  to manage the tags should fit the screen now in portrait mode and landscape mode.

**Comment by luizaogs** [comment]
The label is now "edit tags." Is that what you intended? 

(This ticket is horrific. It makes me angry.)

**Comment by urapadmin** [comment]
no, it should look like this:
![image](https://user-images.githubusercontent.com/38838314/202710737-66868dde-ff03-41e2-9f94-17756907e9b8.png)
But I suppose you were looking in tag analysis and I had only changed it in locus interpretation. 

### recording 31.7.7
It is now changed there, too.

**Comment by urapadmin** [comment]
> (This ticket is horrific. It makes me angry.)

You know what we do with such things? We CLOSE them! 🚽

**Comment by luizaogs** [comment]
I was actually looking in the feature layout, where it is still edit tags in 13.8. It is also still edit tags in survey interpretation.

**Comment by urapadmin** [comment]
ah. Okay. 🚽 will have to wait another round ...

**Comment by urapadmin** [comment]
### recording 13.8.2
I hope I got them all now

**Comment by luizaogs** [comment]
Yep.
