### ISSUE TITLE
show only a user's workstation in sync-manager

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#838]
current privileges don't allow for user specific content - that's a general issue.
one instance is that user's should only see their own workstation - unless they have the privilege to see them all.

**Comment by urapadmin** [comment]
also related to #229

**Comment by urapadmin** [comment]
### kiosk 0.21
- this is available now. Workstation have a new field "grant_access_to" in settings and when being created. It is set to "*", meaning that the workstation is not meant for any particular user.
- In compatibility mode the hub will show all workstations that use the wildcard. So in this mode we would have to give every single workstation a particular user if we want users to see only their workstation.
- However, if the kiosk config key `kiosk\syncmanagerplugin\grant_by_wildcard` is set to False the opposite is the case: Only workstation that are explicitly granted to a certain user are visible to that user
- reporting and file-export docks don't have the "grant_access_to" attribute. 
- ReportingDocks are always accessible to all users that have the privilege "operate reporting" or "manage reporting"
- FileExportDocks are always accessible to all users that have the privilege "file export"
- FileMakerRecordingWorkstation Docks are always accessible to users who have the privilege "prepare workstation"

**Comment by luizaogs** [comment]
I'm not sure I'm misunderstanding compatibility mode. So if a field_worker in PVD right now has a workstation assigned to them, should they still be able to see all of the wildcard ones in addition to that workstation? That is the case.

**Comment by luizaogs** [comment]
In PASU test a field_worker can only see their assigned workstation, as expected.

**Comment by urapadmin** [comment]
> I'm not sure whether I'm misunderstanding compatibility mode. So if a field_worker in PVD right now has a workstation assigned to them, should they still be able to see all of the wildcard ones in addition to that workstation? That is the case.

yes, that is correct. In compatibility mode "*" workstations are always accessible. Without compatibility mode the wildcard does not do anything.

**Comment by luizaogs** [comment]
Ok, then I think this is good!

**Comment by urapadmin** [comment]
@lbestock: Now we have to decide whether we promote this. It asks more of the admin but gives utmost guidance to the field workers.

**Comment by lbestock** [comment]
I think we should discuss it with @nparkervan first off - he has the biggest team and the most knowledge of what it means. Part of it might come down to if a project admin will be collecting and redistributing iPads or leaving them in the hands of the team. In the latter case it really does make things much simpler for the field workers to only see their own dock.

**Comment by urapadmin** [comment]
it also depends on whether it is practical to assign a single ipad to a single user. Because that is how it would work, currently. If ipads are "orange ipad" and "black ipad" and the users vary, this would not work.

**Comment by urapadmin** [comment]
But one can mix and match! E.g. all the blue and green ipads can be visible to everybody but X1LK only to me myself.

**Comment by lbestock** [comment]
Which should now be named lkx1 so it gets alphabetized properly! 
That's useful.
I am curious about this. On Uronarti we don't so much work with trench supervisors so the iPads by color make more sense, but with a supervisor system it makes things a bit simpler to have people in charge be the dock names. And take the responsibility for charging the iPads. And then the one-dock visible becomes both possible and streamlined, but also less necessary as you're not so likely to mess up your own name even in a long list.
