### ISSUE TITLE
support webp as an image format

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#846]
Pillow, and I am sure OpenCV natively support it, I just have to add it to the list of supported file formats

It is much better than jpg for thumbnails. And all major Browsers are now supporting it. 

So maybe I should also use for at least the thumbnails in the file repository. Perhaps even for FM?

**Comment by urapadmin** [comment]
### kiosk 1.3
- WebP is supported now as input format (file import) 
- and as output format (e.g. to turn TIFs or NEFs or such into thumbnails)

**Comment by urapadmin** [comment]
- it might not work (have not tested it) on Beset because so far I have no installed a third party software that might be needed. But I want to try without it first.

**Comment by urapadmin** [comment]
pvd has now a resolution "smaller" in the file repository list and it looks as if webp works quite well.

**Comment by urapadmin** [comment]
- one issue with this, which is presumably not connected to webp in particular: When downloading the "smaller" thumbnail it comes as a file with the extension ".jpg" instead of webp.

**Comment by urapadmin** [comment]
### kiosk 1.3.1
- [ ] Downloading the "smaller" thumbnail from the edit file dialog should download a webp file with the proper extension 'webp'
- [ ] All other thumbnails should have their respective proper extension (usually jpg, except for the original, of course) on download, too.

**Comment by luizaogs** [comment]
As usual, I have dumb questions. Where should I be seeing the "smaller" option? I only see "download small thumbnail," and I am getting jpgs for that.

**Comment by luizaogs** [comment]
Ah. It's working :)

**Comment by urapadmin** [comment]
Also, this is only available on PVD and be aware of #1962: You'll see many tentaculaires in the file repository

**Comment by urapadmin** [comment]
not in the file repository itself. Those are webp - thumbnails, too, if you choose "smaller" as resolution. And I get many tentaculairs in there if I just show all images. But that's a different issue and I have made it a ticket.

**Comment by luizaogs** [comment]
Ah, I had to do some scrolling to see them.
