### ISSUE TITLE
contextual description for pottery image not imported when duplicate

### ISSUE THREAD

**Issue by lbestock** [arch-kiosk/arch-kiosk-office#974]
Small thing. Testing #441. When I put the same image in as dayplan and locus photo it grabbed both of the contextual descriptions I gave it. When I put the same image in as CM photo and pottery photo it grabbed only one description, though it got both contexts correctly. I did this in both directions, so with the first file in CM in one case and with the first file in pottery once. In both cases it took the contextual description from CM but not pottery.

**Comment by urapadmin** [comment]
I don't understand. What system are we talking about? Kiosk and the file import? Filemaker?

**Comment by lbestock** [comment]
In FM I added the same image in two places, one of which was a pottery photo. I gave it different contextual descriptions in those two places (Daffodils 1, Daffodils 2). After synchronization, the file repository has both of its locations properly, but is missing Daffodils 2, which was the contextual description from the pottery record. That does not happen with contextual descriptions for duplicate images in other containers; both end up in the file repository. The next download of the database, now opened in Filemaker, DOES have that contextual description still, so it wasn't lost, but it didn't get to the file repository. 
![image](https://user-images.githubusercontent.com/49291909/110816978-d9a37300-8259-11eb-8c6c-d94ef6b01395.png)
![image](https://user-images.githubusercontent.com/49291909/110816999-e031ea80-8259-11eb-81d7-cca1b8aa9193.png)

**Comment by urapadmin** [comment]
I don't think that has anything to do with duplicate images. I think I skip the pottery image description in order to not have the description in the file repository get out of hand. I'll look into the code and see how I assemble all the different descriptions in the file repository and in what order.

**Comment by urapadmin** [comment]
no, there is confusion in the configuration. On what server are we here?

**Comment by urapadmin** [comment]
got it. It was indeed just a configuration issue. 
- [ ] Fixed on Hillside/Pvd.

**Comment by urapadmin** [comment]
Needs to be fixed on
- [ ] Hillside/Urap
- [ ] Beset/USTP
- [ ] Beset/khpp
- [ ] Beset/PVD
- [ ] Beset/Urap

**Comment by urapadmin** [comment]
@lbestock : Please test and close this

**Comment by lbestock** [comment]
This one over to you, @luizaogs, for finishing up.

**Comment by luizaogs** [comment]
I didn't think I could test this. It's Hillside/PVD.

**Comment by lbestock** [comment]
Oh you totally can - that's just wrong. It's on PVD on Beset. And I gave it to you after testing it twice wrong last night myself, first not giving it a pottery number and then not giving it a second contextual description, and I threw up my hands and said I should accept that you're better at this than I am and make sure the actual ticket gets closed :)

**Comment by luizaogs** [comment]
Yeah I'm not better at this than you. I don't actually know how to use the ceramic analysis module properly, I've realized, so also forgot the pottery number the first time I did it. Figured it out, though, and this is working.

I am not sure what is going on with the checkboxes above, though. If testing this on PVD on Beset is sufficient this can be closed.

**Comment by urapadmin** [comment]
now that this is tested to be working on Beset/PVD, I have to configure all the other projects accordingly:


- [ ] Beset/USTP and ustp-test
- [ ] Beset/khpp and khpp-test
- [ ] Beset/arch1900
- [ ] Beset/urap and urap-test

**Comment by urapadmin** [comment]
@luizaogs Can you please make a screenshot of what it actually looks like now that it is working?

**Comment by luizaogs** [comment]
<img width="1431" alt="Screen Shot 2022-02-27 at 1 19 17 PM" src="https://user-images.githubusercontent.com/67970402/155896527-25eccc1a-d017-46cf-b864-d6412b29e42c.png">

**Comment by urapadmin** [comment]
![image](https://user-images.githubusercontent.com/38838314/155896762-3eb69967-e575-4daa-b770-4a02c304ea30.png)

**Comment by urapadmin** [comment]
does the collected material record itself have a description? If not, would you please make one so that we can see what it looks like if all three descriptions have data?

**Comment by luizaogs** [comment]
It didn't have one, does now. But it doesn't show up in the file repository as far as I can tell? I did download the database again to make sure it was there, and it is.

**Comment by urapadmin** [comment]
just so that you note, @lbestock:
that is how I will configure it for urap and ustp, too, now: for pottery images only the description of the sherd will be displayed in the file repository.

**Comment by luizaogs** [comment]
OH WAIT. You wanted the description of the pottery collected material. Hang on, that's not what I did :)

**Comment by luizaogs** [comment]
Oh just kidding, that pottery collected material already had an old description. Crisis averted.

**Comment by urapadmin** [comment]
now I am confused.

**Comment by luizaogs** [comment]
Ignore me. I thought I had messed something up but I did not.

**Comment by urapadmin** [comment]
can we close this?

**Comment by luizaogs** [comment]
You said above that you needed to configure the others? If you have it can be closed - it's fine on PVD.

**Comment by luizaogs** [comment]
@urapadmin ? Do you need me to do anything here?

**Comment by urapadmin** [comment]
not currently, thank you.

**Comment by lbestock** [comment]
Sending this back to you because it should not lurk in testing when you say it is on your plate.

**Comment by urapadmin** [comment]
It is definitely configured in the default_config that all projects share. So I can close this for the time being.
