### ISSUE TITLE
image counter in all image lists

### ISSUE THREAD

**Issue by urapadmin** [arch-kiosk/arch-kiosk-office#979]
I personally have trouble - particularly on desktop computers - to see if there is more than one photo in a list and at which one I am looking. This is in locus photos and collected material photos, but should also apply to pottery photos.  
A counter like "1 of x images" would help me.

**Comment by urapadmin** [comment]
### @test recording 12.4.3
I added it to collected material photos and locus photos. 
That seems enough to me.

**Comment by luizaogs** [comment]
Works.
